"use client";
import { Activity, Banknote, HeartPulse, History, Landmark, UsersRound } from "lucide-react";
import type { SeasonState } from "@/game-engine/season";
import { lifeEventsForClub, medicalCasesForClub } from "@/game-engine/advanced-world";
import styles from "./advanced-club-view.module.css";
const eur=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(v);
export default function AdvancedClubView({season,onOpenClub}:{season:SeasonState;onOpenClub:()=>void}){const club=season.league.clubs.find(c=>c.id===season.selectedClubId)??season.league.clubs[0],advanced=season.advancedWorld,stadium=advanced.stadiums[club.id],finance=advanced.finances[club.id],medical=medicalCasesForClub(advanced,club.id),life=lifeEventsForClub(advanced,club.id);return <div className={styles.shell}>
 <section className={styles.hero}><div><span>GESTÃO & LEGADO</span><h2>{club.name}</h2><p>Médico, vida do elenco, estádio, torcida, finanças e memória histórica do save em uma única área.</p></div><Landmark/></section>
 <div className={styles.metrics}><Metric icon={<HeartPulse/>} label="CASOS MÉDICOS" value={`${medical.filter(m=>!m.closed).length}`} detail="em recuperação"/><Metric icon={<UsersRound/>} label="PÚBLICO MÉDIO" value={stadium?stadium.averageAttendance.toLocaleString("pt-BR"):"0"} detail={stadium?`capacidade ${stadium.capacity.toLocaleString("pt-BR")}`:"—"}/><Metric icon={<Banknote/>} label="CAIXA SIMULADO" value={finance?eur(finance.cashBalanceEur):"—"} detail="diretoria controla os recursos"/><Metric icon={<History/>} label="TEMPORADAS" value={`${advanced.history.length}`} detail="registradas no legado"/></div>
 <div className={styles.grid}><section className={styles.panel}><header><HeartPulse/><div><span>SPRINT 20</span><h3>Departamento médico avançado</h3></div></header>{medical.length?medical.slice(0,8).map(item=><article className={styles.row} key={item.id}><div><b>{item.playerName}</b><small>{item.injury} • {item.severity}</small></div><div className={styles.right}><strong>{item.stage}</strong><small>recaída {item.recurrenceRisk}%</small></div></article>):<p className={styles.empty}>Nenhum caso médico registrado. Lesões futuras criarão histórico, risco de recaída e estágio de retorno.</p>}</section>
 <section className={styles.panel}><header><UsersRound/><div><span>SPRINT 24</span><h3>Estádio & torcida</h3></div></header>{stadium&&<div className={styles.details}><p><b>Último público</b><strong>{stadium.lastAttendance.toLocaleString("pt-BR")}</strong></p><p><b>Atmosfera</b><strong>{stadium.atmosphere}/100</strong></p><p><b>Receita de jogos</b><strong>{eur(stadium.matchdayRevenueEur)}</strong></p><p><b>Momento</b><strong>{stadium.protest?"Protestos":stadium.mosaic?"Mosaico/festa":"Estável"}</strong></p></div>}</section>
 <section className={styles.panel}><header><Banknote/><div><span>SPRINT 28</span><h3>Finanças sob o papel do treinador</h3></div></header>{finance&&<div className={styles.details}><p><b>Receitas da temporada</b><strong>{eur(finance.seasonRevenueEur)}</strong></p><p><b>Despesas estimadas</b><strong>{eur(finance.seasonExpensesEur)}</strong></p><p><b>Premiações</b><strong>{eur(finance.prizeMoneyEur)}</strong></p><p><b>Orçamento de transferências</b><strong>{eur(club.transferBudgetEur)}</strong></p></div>}<button className={styles.action} onClick={onOpenClub}>PEDIR RECURSOS À DIRETORIA</button><small className={styles.note}>O treinador não administra o caixa: ampliações de verba e estrutura continuam dependendo de aprovação da diretoria.</small></section>
 <section className={styles.panel}><header><Activity/><div><span>SPRINT 23</span><h3>Vida do jogador</h3></div></header>{life.length?life.slice(0,8).map(event=><article className={styles.life} key={event.id}><i>{event.impact==="Positivo"?"+":"!"}</i><div><b>{event.title}</b><p>{event.summary}</p><small>{event.date} • {event.impact}</small></div></article>):<p className={styles.empty}>O calendário ainda não gerou eventos pessoais. Adaptação, família, disciplina, empresário e entorno social passam a surgir ao longo dos dias.</p>}</section>
 </div>
 <section className={styles.panel}><header><History/><div><span>SPRINT 29</span><h3>História do mundo</h3></div></header>{advanced.history.length?<div className={styles.history}>{advanced.history.map(record=><article key={record.year}><b>{record.year}</b><div><strong>{record.competitionName}: {record.leagueChampion}</strong><span>{record.userClub} terminou em {record.userPosition}º • artilheiro: {record.topScorer} ({record.topScorerGoals})</span><small>{record.cupChampions.join(" • ")||"Sem copas concluídas registradas"}</small></div></article>)}</div>:<p className={styles.empty}>O primeiro registro histórico será fechado ao virar a temporada. Campeões, sua posição, artilheiro e campeões de copas ficarão preservados entre décadas.</p>}</section>
 </div>}
function Metric({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail:string}){return <article className={styles.metric}><i>{icon}</i><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></article>}
