"use client";

import{Activity,BarChart3,BriefcaseBusiness,Building2,ChevronRight,ClipboardList,Coins,GraduationCap,HeartPulse,Search,ShieldCheck,Target,TrendingUp,Users,Stethoscope}from"lucide-react";
import type{SeasonState}from"@/game-engine/season";
import{clubOperationsProfile,promoteYouthProspect,requestBoardAction,requestBoardTransferContact,requestExternalScout,requestOpponentAnalysis,observeYouthProspect,scoutingTargets,type ClubActionResult,type DepartmentKey}from"@/game-engine/club-management";
import{academySquads,clubStaff,humanMarketProfile,managerWorld,medicalDepth,scoutingReport,youthDevelopmentMultiplier}from"@/game-engine/depth-systems";
import styles from"./club-management-view.module.css";

export default function ClubManagementView({season,onResult,onOpenInbox}:{season:SeasonState;onResult:(result:ClubActionResult)=>void;onOpenInbox?:()=>void}){
 const club=season.league.clubs.find(item=>item.id===season.selectedClubId)??season.league.clubs[0],profile=clubOperationsProfile(season),targets=scoutingTargets(season,8),activeTasks=profile.tasks.filter(task=>task.status==="Em andamento"),finished=profile.tasks.filter(task=>task.status==="Concluída"),board=season.livingWorld.boardConfidence,boardMeeting=season.livingWorld.inbox.find(event=>event.kind==="Diretoria"&&event.unread&&!event.resolved),staff=clubStaff(club),academy=academySquads(club,season.year),managers=managerWorld(season.league,season.year).filter(m=>m.clubId!==club.id).sort((a,b)=>b.reputation-a.reputation).slice(0,6),medical=[...club.players].sort((a,b)=>medicalDepth(b,club).recurrenceRisk-medicalDepth(a,club).recurrenceRisk).slice(0,6);
 return <div className={styles.shell}>
  {boardMeeting&&<section className={styles.panel}><header><div><span>AGENDA DA DIRETORIA</span><h3>{boardMeeting.title}</h3></div><Building2/></header><p className={styles.intro}>{boardMeeting.body}</p><button className={styles.bigAction} onClick={onOpenInbox}><ClipboardList/> ABRIR PAUTA E RESPONDER <ChevronRight/></button></section>}
  <section className={styles.hero}><div><span>ESTRUTURA DO CLUBE 2.0</span><h2>{club.name}</h2><p>Staff individual, conhecimento de scouting, Sub-17/Sub-20, carga médica e decisões delegadas agora dependem da qualidade real das pessoas do clube.</p></div><div className={styles.heroMetrics}><HeroMetric label="DIRETORIA" value={`${board}%`} detail={board>=70?"confiança alta":board>=45?"relação estável":"relação pressionada"}/><HeroMetric label="ORÇ. TRANSF." value={eur(club.transferBudgetEur)} detail="disponível"/><HeroMetric label="TETO SALARIAL" value={brl(club.wageBudgetBrlMonthly)} detail="por mês"/></div></section>

  <section className={styles.departments}><DepartmentCard icon={<BriefcaseBusiness/>} department={profile.departments.Futebol}/><DepartmentCard icon={<Search/>} department={profile.departments.Observação}/><DepartmentCard icon={<GraduationCap/>} department={profile.departments.Base}/><DepartmentCard icon={<BarChart3/>} department={profile.departments.Análise}/><DepartmentCard icon={<HeartPulse/>} department={profile.departments.Médico}/></section>

  <div className={styles.gridWide}>
   <section className={styles.panel}><header><div><span>STAFF INDIVIDUAL</span><h3>A qualidade da delegação agora tem dono</h3></div><Users/></header><p className={styles.intro}>Um adjunto forte lê melhor a partida; um olheiro forte reduz a incerteza; fisioterapeutas melhores refinam risco; o diretor de futebol melhora a leitura de negociação.</p><div className={styles.tasks}>{staff.map(member=><article key={member.id}><span>{member.role}</span><div><b>{member.name}</b><small>Tática {member.tactical} • Julgamento {member.judging} • Motivação {member.motivation} • Médico {member.medical} • Negociação {member.negotiation} • Base {member.youth}</small></div><em>OVR {member.overall}</em></article>)}</div></section>
   <section className={styles.panel}><header><div><span>MUNDO DOS TÉCNICOS</span><h3>Carreiras, estilos e rivais do seu save</h3></div><Target/></header><div className={styles.tasks}>{managers.map(manager=><article key={manager.id}><span>{manager.formation}</span><div><b>{manager.name} • {manager.clubName}</b><small>{manager.style} • carreira {manager.careerYears} anos • rivalidade {manager.rivalry}/100 • provocação {manager.provocation}/100</small></div><em>REP {manager.reputation}</em></article>)}</div></section>
  </div>

  <div className={styles.gridWide}>
   <section className={styles.panel}><header><div><span>SCOUTING COM INCERTEZA</span><h3>Você não conhece mais tudo de todo mundo</h3></div><Search/></header><p className={styles.intro}>O que aparece depende do nível do seu olheiro e das observações já feitas. OVR e potencial podem vir como faixa; personalidade só fica clara após conhecimento suficiente.</p><div className={styles.targetList}>{targets.map(({player,club:targetClub})=>{const task=profile.tasks.find(item=>item.targetPlayerId===player.id),observationCount=task?.status==="Concluída"?3:task?1:0,report=scoutingReport(player,club,observationCount),market=humanMarketProfile(player,club,targetClub);return <article key={player.id}><div><b>{player.name}</b><span>{targetClub.name} • {player.position} • {player.age} anos</span><small>Conhecimento: {report.knowledgeLabel} ({report.confidence}%) • OVR {report.overall} • POT {report.potential}</small><small>Personalidade: {report.personality}</small><small>Interesse em vir: {market.interest}% • risco de recusa {market.rejectionRisk}% • status desejado: {market.preferredStatus}</small></div>{task?.status==="Concluída"?<div className={styles.targetActions}><em className={styles.ready}>DOSSIÊ ATUALIZADO</em><button onClick={()=>onResult(requestBoardTransferContact(season,player.id))}>PEDIR CONTATO</button></div>:task?<em className={styles.progress}>{`OBSERVANDO ATÉ R${task.dueRound}`}</em>:<button onClick={()=>onResult(requestExternalScout(season,player.id))}>OBSERVAR</button>}</article>})}</div>{finished.filter(task=>task.kind==="Observação externa").slice(0,3).map(task=><article className={styles.report} key={task.id}><b>{task.title}</b><p>{task.result}</p></article>)}</section>

   <section className={styles.panel}><header><div><span>SUB-17 / SUB-20</span><h3>Academia viva • intake {season.year}</h3></div><GraduationCap/></header><p className={styles.intro}>A geração muda a cada temporada e é influenciada pela estrutura. O plano individual altera o multiplicador de desenvolvimento; atletas mais velhos sem espaço recebem indicação de empréstimo.</p><div className={styles.youthList}>{academy.slice().sort((a,b)=>a.squad.localeCompare(b.squad)||b.potential-a.potential).slice(0,12).map(prospect=><article key={prospect.id}><div className={styles.youthMain}><span className={styles.youthAvatar}>{initials(prospect.name)}</span><div><b>{prospect.name}</b><small>{prospect.squad} • {prospect.position} • {prospect.age} anos • {prospect.personality}</small></div></div><div className={styles.youthStats}><span>OVR <b>{prospect.overall}</b></span><span>POT <b>{prospect.potential}</b></span><span>Plano <b>{prospect.plan}</b></span><span>Progresso <b>{prospect.progress}%</b></span></div><small>Desenvolvimento ×{youthDevelopmentMultiplier(club,prospect.plan).toFixed(2)} {prospect.loanRecommended?"• empréstimo recomendado":"• manter em formação"}</small></article>)}</div><hr/><b>BASE JÁ PERSISTIDA NO SAVE</b><div className={styles.youthList}>{profile.youth.filter(item=>!item.promoted).slice(0,6).map(prospect=><article key={prospect.id}><div className={styles.youthMain}><span className={styles.youthAvatar}>{initials(prospect.name)}</span><div><b>{prospect.name}</b><small>{prospect.position} • {prospect.age} anos • {prospect.personality}</small></div></div><div className={styles.youthStats}><span>Prontidão <b>{prospect.readiness}%</b></span><span>Potencial <b>{prospect.observed?prospect.potential:"?"}</b></span><span>OVR <b>{prospect.observed?prospect.overall:"?"}</b></span></div><div className={styles.youthActions}>{!prospect.observed?<button onClick={()=>onResult(observeYouthProspect(season,prospect.id))}>AVALIAR</button>:<button className={styles.promote} onClick={()=>onResult(promoteYouthProspect(season,prospect.id))}>PROMOVER</button>}</div></article>)}</div></section>
  </div>

  <section className={styles.panel}><header><div><span>MÉDICO & PERFORMANCE 2.0</span><h3>Carga, reincidência, prontidão e jogo no sacrifício</h3></div><Stethoscope/></header><div className={styles.tasks}>{medical.map(player=>{const m=medicalDepth(player,club);return <article key={player.id}><span>{m.recurrenceRisk}% risco</span><div><b>{player.name} • {player.position}</b><small>Carga semanal {m.weeklyLoad}% • prontidão {m.readiness}% • minutos recomendados {m.recommendedMinutes}</small><small>{m.doctorOpinion} {m.canPlayThroughPain?"• pode ser liberado no sacrifício por decisão do treinador":""}</small></div><em>{m.injuryHistorySignal}</em></article>})}</div></section>

  <div className={styles.grid}>
   <section className={styles.panel}><header><div><span>DIRETORIA E FUTEBOL</span><h3>Solicitações institucionais</h3></div><Building2/></header><div className={styles.boardGrid}><BoardButton icon={<Coins/>} title="Mais verba de transferências" text="Solicitar reforço no caixa." onClick={()=>onResult(requestBoardAction(season,"Orçamento de transferências"))}/><BoardButton icon={<TrendingUp/>} title="Ampliar teto salarial" text="Pedir margem para contratos." onClick={()=>onResult(requestBoardAction(season,"Teto salarial"))}/><BoardButton icon={<Search/>} title="Investir em observação" text="Melhorar precisão dos relatórios." onClick={()=>onResult(requestBoardAction(season,"Investimento em observação"))}/><BoardButton icon={<GraduationCap/>} title="Investir na base" text="Melhorar formação dos jovens." onClick={()=>onResult(requestBoardAction(season,"Investimento na base"))}/><BoardButton icon={<HeartPulse/>} title="Melhorar Médico/Performance" text="Reduzir risco e melhorar diagnóstico." onClick={()=>onResult(requestBoardAction(season,"Estrutura médica"))}/><BoardButton icon={<BarChart3/>} title="Reforçar análise" text="Aumentar leitura de desempenho." onClick={()=>onResult(requestBoardAction(season,"Análise de desempenho"))}/></div></section>
   <section className={styles.panel}><header><div><span>ANÁLISE DE DESEMPENHO</span><h3>Próximo adversário</h3></div><ClipboardList/></header><p className={styles.intro}>Peça um dossiê tático antes da rodada para preparar pressão, corredores e plano de jogo.</p><button className={styles.bigAction} onClick={()=>onResult(requestOpponentAnalysis(season))}><BarChart3/> PEDIR ANÁLISE <ChevronRight/></button>{finished.filter(task=>task.kind==="Análise de adversário").slice(0,2).map(task=><article className={styles.report} key={task.id}><b>{task.title}</b><p>{task.result}</p></article>)}</section>
  </div>

  <section className={styles.panel}><header><div><span>FILA DOS DEPARTAMENTOS</span><h3>{activeTasks.length} solicitação(ões) em andamento</h3></div><Activity/></header>{activeTasks.length?<div className={styles.tasks}>{activeTasks.map(task=><article key={task.id}><span>{task.department}</span><div><b>{task.title}</b><small>{task.kind} • solicitado R{task.requestedRound}</small></div><em>Entrega R{task.dueRound}</em></article>)}</div>:<div className={styles.empty}><ShieldCheck/><b>Nenhuma solicitação pendente</b><p>Observação, análise interna e demais relatórios aparecem aqui.</p></div>}</section>
 </div>;
}

function DepartmentCard({department,icon}:{department:{key:DepartmentKey;label:string;headName:string;level:number;description:string};icon:React.ReactNode}){return <article><i>{icon}</i><div><span>{department.label}</span><b>{department.headName}</b><small>{department.description}</small><em>Nível {department.level}/5</em></div></article>}
function BoardButton({icon,title,text,onClick}:{icon:React.ReactNode;title:string;text:string;onClick:()=>void}){return <button onClick={onClick}><i>{icon}</i><span><b>{title}</b><small>{text}</small></span><ChevronRight/></button>}
function HeroMetric({label,value,detail}:{label:string;value:string;detail:string}){return <div><span>{label}</span><b>{value}</b><small>{detail}</small></div>}
function eur(value:number){return value>=1_000_000?`€${(value/1_000_000).toLocaleString("pt-BR",{maximumFractionDigits:1})} mi`:`€${Math.round(value/1_000).toLocaleString("pt-BR")} mil`}
function brl(value:number){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",notation:"compact",maximumFractionDigits:1}).format(value)}
function initials(name:string){return name.split(" ").slice(0,2).map(part=>part[0]).join("")}
