import{describe,expect,it}from"vitest";
import{aggregateLabel,competitionTable,postMatchCompetitionResults}from"./competition-view-model";
import type{WorldCompetitionMatch,WorldParticipant,WorldTournamentState}from"../game-engine/world-competitions";

const team=(id:string,name:string,activeClubId?:string):WorldParticipant=>({id,name,shortName:name.slice(0,3).toUpperCase(),country:"Brasil",reputation:80,activeClubId});
const pal=team("pal","Palmeiras","club-pal"),riv=team("riv","River Plate"),cer=team("cer","Cerro Porteño"),cri=team("cri","Sporting Cristal"),fla=team("fla","Flamengo"),bol=team("bol","Bolívar");
const match=(id:string,home:WorldParticipant,away:WorldParticipant,extra:Partial<WorldCompetitionMatch>={}):WorldCompetitionMatch=>({id,competitionId:"LIB",stage:"Fase de grupos",roundDue:1,date:"2026-04-07",home,away,played:true,homeGoals:0,awayGoals:0,tableStage:true,...extra});
function tournament(matches:WorldCompetitionMatch[]):WorldTournamentState{return{definition:{id:"LIB",name:"CONMEBOL Libertadores",shortName:"Libertadores",kind:"Continental",participants:32,roundInterval:3,format:"Grupos + mata-mata",rulesSummary:"",groupCount:8,groupSize:4,stages:[{name:"Fase de grupos",dates:["2026-04-07"],legs:1,kind:"groups",rule:""},{name:"Oitavas de final",dates:["2026-08-11","2026-08-18"],legs:2,kind:"knockout",rule:""}]},participants:[pal,riv,cer,cri,fla,bol],matches,currentStage:"Fase de grupos",currentStageIndex:0,completed:false}}

describe("competition presentation model",()=>{
 it("builds the focused Libertadores group table instead of mixing groups",()=>{const t=tournament([match("a1",pal,riv,{group:"A",homeGoals:2,awayGoals:0}),match("a2",cer,cri,{group:"A",homeGoals:1,awayGoals:1}),match("b1",fla,bol,{group:"B",homeGoals:8,awayGoals:0})]);const rows=competitionTable(t,"Fase de grupos","club-pal");expect(rows.map(row=>row.participant.id)).toEqual(expect.arrayContaining(["pal","riv","cer","cri"]));expect(rows.some(row=>row.participant.id==="fla")).toBe(false);expect(rows[0].participant.id).toBe("pal");expect(rows[0].points).toBe(3)});
 it("keeps partial and final aggregate scores for two-leg ties",()=>{const first=match("ko-1",riv,pal,{stage:"Oitavas de final",tableStage:false,tieId:"tie-1",leg:1,date:"2026-08-11",homeGoals:1,awayGoals:2}),second=match("ko-2",pal,riv,{stage:"Oitavas de final",tableStage:false,tieId:"tie-1",leg:2,date:"2026-08-18",played:false,homeGoals:undefined,awayGoals:undefined}),t=tournament([first,second]);expect(aggregateLabel(t,first)).toBe("Agregado parcial 1–2");second.played=true;second.homeGoals=1;second.awayGoals=0;second.winnerId="pal";expect(aggregateLabel(t,second)).toBe("Agregado 3–1")});
 it("returns the other cup results from the same leg for the post-match central",()=>{const user=match("ko-user",pal,riv,{stage:"Oitavas de final",tableStage:false,tieId:"u",leg:1}),other=match("ko-other",fla,bol,{stage:"Oitavas de final",tableStage:false,tieId:"o",leg:1}),returnLeg=match("ko-return",riv,pal,{stage:"Oitavas de final",tableStage:false,tieId:"u",leg:2,date:"2026-08-18"}),t=tournament([other,returnLeg,user]);expect(postMatchCompetitionResults(t,user).map(item=>item.id)).toEqual(["ko-user","ko-other"])});
});
