"use client";

import Image from "next/image";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Activity, BarChart3, Bell, BriefcaseBusiness, Building2, CalendarDays, ChevronRight, CircleGauge, ClipboardList, Crown, Flag, Globe2, Home, Inbox, Landmark, LayoutGrid, MessageSquareText, Newspaper, Search, Settings, Shield, Sparkles, Target, Trophy, UserRoundSearch, Users, X, Zap } from "lucide-react";
import { professionalCompetitionById } from "@/data/brazil-2026/competitions";
import { clubOperationsProfile } from "@/game-engine/club-management";
import type { GamePreferences } from "@/game-engine/game-preferences";
import { sortedStandings, type LeagueClub, type LeaguePlayer } from "@/game-engine/league";
import { dressingRoomSummary } from "@/game-engine/people";
import { getSelectedClub, getUserFixtures, type SeasonState } from "@/game-engine/season";
import { playerInfluence } from "@/game-engine/social";
import styles from "./fm-experience.module.css";

export type FmEntity={type:"player"|"club"|"competition";id:string};
export const FM_ENTITY_EVENT="v90-fm-open-entity";
export function openFmEntity(entity:FmEntity){if(typeof window!=="undefined")window.dispatchEvent(new CustomEvent<FmEntity>(FM_ENTITY_EVENT,{detail:entity}));}

type Group={label:string;icon:typeof Home;items:{label:string;icon:typeof Home}[]};
export const FM_GROUPS:Group[]=[
 {label:"Início",icon:Home,items:[{label:"Visão geral",icon:Home},{label:"Caixa de entrada",icon:Inbox},{label:"Calendário",icon:CalendarDays},{label:"Notícias",icon:Newspaper}]},
 {label:"Elenco",icon:Users,items:[{label:"Elenco",icon:Users},{label:"Planejamento",icon:ClipboardList},{label:"Vestiário",icon:MessageSquareText},{label:"Central de Dados",icon:BarChart3}]},
 {label:"Jogo",icon:LayoutGrid,items:[{label:"Táticas",icon:LayoutGrid},{label:"Classificação",icon:Trophy}]},
 {label:"Recrutamento",icon:UserRoundSearch,items:[{label:"Mercado",icon:UserRoundSearch}]},
 {label:"Clube",icon:Building2,items:[{label:"Clube",icon:Building2},{label:"Diretoria",icon:Landmark},{label:"Responsabilidades",icon:Shield},{label:"Gestão & Legado",icon:Crown}]},
 {label:"Mundo",icon:Globe2,items:[{label:"Mundo",icon:Globe2},{label:"Seleção",icon:Flag},{label:"Carreira",icon:BriefcaseBusiness},{label:"Mídia & Redes",icon:Bell},{label:"Configurações",icon:Settings}]},
];
export const FM_MOBILE_PRIMARY=["Visão geral","Elenco","Táticas","Calendário"] as const;

export function FmSidebarNav({active,onNavigate,pendingEvents=0,pendingMedia=0}:{active:string;onNavigate:(screen:string)=>void;pendingEvents?:number;pendingMedia?:number}){
 const initial=FM_GROUPS.find(group=>group.items.some(item=>item.label===active))?.label??"Início";
 const[group,setGroup]=useState(initial);
 useEffect(()=>{const owner=FM_GROUPS.find(item=>item.items.some(child=>child.label===active));if(owner)queueMicrotask(()=>setGroup(owner.label));},[active]);
 const selected=FM_GROUPS.find(item=>item.label===group)??FM_GROUPS[0];
 return <div className={styles.navShell}>
  <div className={styles.primaryNav}>{FM_GROUPS.map(item=>{const Icon=item.icon;const hot=item.items.some(child=>child.label===active);return <button key={item.label} className={hot?styles.primaryActive:""} onClick={()=>setGroup(item.label)} title={item.label}><Icon size={17}/><span>{item.label}</span></button>})}</div>
  <div className={styles.secondaryNav}><small>{selected.label.toUpperCase()}</small>{selected.items.map(item=>{const Icon=item.icon;const count=item.label==="Caixa de entrada"?pendingEvents:item.label==="Mídia & Redes"?pendingMedia:0;return <button key={item.label} className={active===item.label?styles.secondaryActive:""} onClick={()=>onNavigate(item.label)}><Icon size={16}/><span>{item.label}</span>{count>0&&<i>{Math.min(99,count)}</i>}</button>})}</div>
 </div>;
}

export function FmMobileMenu({active,onNavigate,pendingEvents=0,pendingMedia=0,onClose}:{active:string;onNavigate:(screen:string)=>void;pendingEvents?:number;pendingMedia?:number;onClose:()=>void}){
 return <div className={styles.mobileGroups}>{FM_GROUPS.map(group=><section key={group.label}><header><group.icon size={15}/><b>{group.label}</b></header><div>{group.items.filter(item=>!FM_MOBILE_PRIMARY.includes(item.label as typeof FM_MOBILE_PRIMARY[number])).map(item=>{const Icon=item.icon,count=item.label==="Caixa de entrada"?pendingEvents:item.label==="Mídia & Redes"?pendingMedia:0;return <button key={item.label} className={active===item.label?styles.mobileGroupActive:""} onClick={()=>{onNavigate(item.label);onClose()}}><Icon size={17}/><span>{item.label}</span>{count>0&&<i>{Math.min(99,count)}</i>}</button>})}</div></section>)}</div>;
}

function groupFor(active:string){return FM_GROUPS.find(group=>group.items.some(item=>item.label===active))?.label??"Início";}

export function FmContextBar({season,active,onNavigate}:{season:SeasonState;active:string;onNavigate:(screen:string)=>void}){
 const[searchOpen,setSearchOpen]=useState(false),[query,setQuery]=useState(""),[entity,setEntity]=useState<FmEntity|null>(null);
 useEffect(()=>{const listener=(event:Event)=>setEntity((event as CustomEvent<FmEntity>).detail);window.addEventListener(FM_ENTITY_EVENT,listener);return()=>window.removeEventListener(FM_ENTITY_EVENT,listener);},[]);
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setSearchOpen(true)}if(event.key==="Escape"){setSearchOpen(false);setEntity(null)}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[]);
 const club=getSelectedClub(season),competition=professionalCompetitionById(season.competitionId),advice=assistantAdvice(season);
 const results=useMemo(()=>searchResults(season,query),[season,query]);
 return <>
  <div className={styles.contextBar}>
   <div className={styles.breadcrumb}><button onClick={()=>onNavigate("Visão geral")}>V90</button><ChevronRight/><span>{groupFor(active)}</span><ChevronRight/><b>{active}</b></div>
   <button className={styles.assistantChip} onClick={()=>onNavigate(advice.target)}><Sparkles/><span><small>ADJUNTO</small><b>{advice.title}</b></span><ChevronRight/></button>
   <button className={styles.searchButton} onClick={()=>setSearchOpen(true)}><Search/><span>Pesquisar no mundo</span><kbd>Ctrl K</kbd></button>
  </div>
  {searchOpen&&<div className={styles.overlay} onClick={()=>setSearchOpen(false)}><section className={styles.searchPanel} onClick={event=>event.stopPropagation()}><header><Search/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Jogador, clube, competição ou área do jogo..."/><button onClick={()=>setSearchOpen(false)}><X/></button></header><div className={styles.searchMeta}><span>{club.name}</span><span>{competition.shortName}</span><span>{results.length} resultado{results.length===1?"":"s"}</span></div><div className={styles.searchResults}>{results.slice(0,18).map(result=><button key={`${result.kind}-${result.id}`} onClick={()=>{if(result.screen){onNavigate(result.screen);setSearchOpen(false)}else if(result.entity){setEntity(result.entity);setSearchOpen(false)}}><i>{result.kind}</i><span><b>{result.title}</b><small>{result.detail}</small></span><ChevronRight/></button>)}</div></section></div>}
  {entity&&<EntityProfile season={season} entity={entity} onClose={()=>setEntity(null)} onNavigate={onNavigate}/>} 
 </>;
}

type SearchResult={id:string;kind:string;title:string;detail:string;screen?:string;entity?:FmEntity};
function searchResults(season:SeasonState,query:string):SearchResult[]{
 const q=query.trim().toLocaleLowerCase("pt-BR"),competition=professionalCompetitionById(season.competitionId);
 const screens=FM_GROUPS.flatMap(group=>group.items.map(item=>({id:item.label,kind:"ÁREA",title:item.label,detail:`${group.label} • abrir módulo`,screen:item.label} satisfies SearchResult)));
 const clubs=season.league.clubs.map(club=>({id:club.id,kind:"CLUBE",title:club.name,detail:`${competition.shortName} • reputação ${club.reputation}`,entity:{type:"club",id:club.id} as FmEntity}));
 const players=season.league.clubs.flatMap(club=>club.players.map(player=>({id:player.id,kind:"JOGADOR",title:player.name,detail:`${club.shortName} • ${player.position} • ${player.age} anos • OVR ${player.overall}`,entity:{type:"player",id:player.id} as FmEntity})));
 const competitionResult:SearchResult={id:season.competitionId,kind:"COMPETIÇÃO",title:competition.name,detail:`Temporada ${season.year} • ${season.league.clubs.length} clubes`,entity:{type:"competition",id:season.competitionId}};
 const all=[competitionResult,...screens,...clubs,...players];if(!q)return all.slice(0,14);return all.filter(item=>`${item.title} ${item.detail} ${item.kind}`.toLocaleLowerCase("pt-BR").includes(q)).sort((a,b)=>rankSearch(a,q)-rankSearch(b,q)||a.title.localeCompare(b.title));
}
function rankSearch(item:SearchResult,q:string){const title=item.title.toLocaleLowerCase("pt-BR");return title===q?0:title.startsWith(q)?1:title.includes(q)?2:3;}

export function ManagerPortal({season,onNavigate}:{season:SeasonState;onNavigate:(screen:string)=>void}){
 const club=getSelectedClub(season),standings=sortedStandings(season.league),row=standings.find(s=>s.clubId===club.id),position=Math.max(1,standings.findIndex(s=>s.clubId===club.id)+1),pending=season.livingWorld.inbox.filter(event=>!event.resolved),summary=dressingRoomSummary(club,season.currentRound),advice=assistantAdvice(season),next=getUserFixtures(season).find(f=>!f.played&&Boolean(f.date)&&f.date!>=season.currentDate),opponent=next?season.league.clubs.find(c=>c.id===(next.homeClubId===club.id?next.awayClubId:next.homeClubId)):undefined,board=season.boardState;
 return <div className={styles.portal}>
  <section className={styles.portalHero}><div><span>PORTAL DO TREINADOR • {formatLongDate(season.currentDate)}</span><h2>{dayGreeting(season.currentDate)}, treinador.</h2><p>{pending.length?`${pending.length} assunto${pending.length===1?" exige":"s exigem"} sua atenção antes de avançar.`:"Não há decisões obrigatórias neste momento. Use o calendário e a comissão para preparar o próximo passo."}</p></div><button onClick={()=>onNavigate(advice.target)}><Sparkles/><span><small>CONSELHO DA COMISSÃO</small><b>{advice.title}</b><em>{advice.detail}</em></span><ChevronRight/></button></section>

  <TwoWeekCalendar season={season} onNavigate={onNavigate}/>

  <div className={styles.portalGrid}>
   <section className={`${styles.fmCard} ${styles.decisionCard}`}><header><span>VOCÊ PRECISA DECIDIR</span><button onClick={()=>onNavigate("Caixa de entrada")}>Ver tarefas <ChevronRight/></button></header>{pending.length?pending.slice(0,4).map((event,index)=><button key={event.id} className={index===0?styles.priorityDecision:""} onClick={()=>onNavigate(event.kind==="Diretoria"?"Diretoria":event.kind==="Coletiva"?"Mídia & Redes":"Caixa de entrada")}><i>{event.kind.slice(0,3).toUpperCase()}</i><span><b>{event.title}</b><small>{event.body}</small></span><em>{index===0?"PRIORIDADE":`R${event.round}`}</em></button>):<div className={styles.emptyTile}><Shield/><b>Agenda limpa</b><small>Sem decisões pendentes.</small></div>}</section>
   <section className={styles.fmCard}><header><span>PRÓXIMO JOGO</span><button onClick={()=>onNavigate("Táticas")}>Preparar <ChevronRight/></button></header>{next&&opponent?<div className={styles.nextGame}><button onClick={()=>openFmEntity({type:"club",id:club.id})}><Image src={club.imageUrl} alt={club.name} width={46} height={46}/><b>{club.shortName}</b></button><div><small>{formatCompactDate(next.date)}</small><strong>VS</strong><em>{next.homeClubId===club.id?"CASA":"FORA"}</em></div><button onClick={()=>openFmEntity({type:"club",id:opponent.id})}><Image src={opponent.imageUrl} alt={opponent.name} width={46} height={46}/><b>{opponent.shortName}</b></button></div>:<div className={styles.emptyTile}><CalendarDays/><b>Sem jogo marcado</b><small>O calendário será atualizado quando houver novo compromisso.</small></div>}</section>
   <section className={styles.fmCard}><header><span>STATUS DO TRABALHO</span><button onClick={()=>onNavigate("Diretoria")}>Diretoria <ChevronRight/></button></header><div className={styles.statusGrid}><Metric label="LIGA" value={`${position}º`} detail={row?`${row.points} pts • ${row.played} J`:"—"}/><Metric label="DIRETORIA" value={`${season.livingWorld.boardConfidence}%`} detail={board.mandate?.name??"Mandato"}/><Metric label="VESTIÁRIO" value={`${Math.round((summary.avgHappiness+summary.avgTrust+summary.unity)/3)}%`} detail={`${summary.concerns.length} questões`}/><Metric label="FORMA" value={season.recentForm.slice(-5).join(" ")||"—"} detail="últimos jogos"/></div></section>
   <section className={styles.fmCard}><header><span>HOJE NO FUTEBOL</span><button onClick={()=>onNavigate("Notícias")}>Central <ChevronRight/></button></header><div className={styles.newsStack}>{season.livingWorld.news.slice(0,4).map((item,index)=><article key={item.id} className={index===0?styles.leadNews:""}><small>{item.source}</small><b>{item.headline}</b><p>{item.summary}</p></article>)}</div></section>
  </div>
 </div>;
}

function TwoWeekCalendar({season,onNavigate}:{season:SeasonState;onNavigate:(screen:string)=>void}){
 const club=getSelectedClub(season),fixtures=getUserFixtures(season),days=Array.from({length:14},(_,index)=>addDays(season.currentDate,index));
 return <section className={styles.fortnight}><header><div><span>PRÓXIMAS DUAS SEMANAS</span><b>Jogos, treino, mídia e recuperação</b></div><button onClick={()=>onNavigate("Calendário")}>Calendário completo <ChevronRight/></button></header><div>{days.map((date,index)=>{const fixture=fixtures.find(item=>!item.played&&item.date===date),opp=fixture?season.league.clubs.find(c=>c.id===(fixture.homeClubId===club.id?fixture.awayClubId:fixture.homeClubId)):undefined,media=season.mediaWorld.sessions?.some(session=>session.status==="Aberta"&&session.round===season.currentRound),label=fixture?`Jogo • ${opp?.shortName??"Adversário"}`:index===0&&media?"Imprensa":index%7===0?"Recuperação":season.trainingPlan;return <button key={date} className={`${date===season.currentDate?styles.todayDay:""} ${fixture?styles.matchDay:""}`} onClick={()=>onNavigate(fixture?"Táticas":"Calendário")}><small>{weekday(date)}</small><b>{date.slice(8)}</b><span>{label}</span></button>})}</div></section>;
}

export function FmSpecialView({active,season,onNavigate,onPreferencesChange}:{active:string;season:SeasonState;onNavigate:(screen:string)=>void;onPreferencesChange:(preferences:GamePreferences)=>void}){
 if(active==="Planejamento")return <SquadPlanner season={season} onNavigate={onNavigate}/>;
 if(active==="Diretoria")return <BoardConfidence season={season} onNavigate={onNavigate}/>;
 if(active==="Responsabilidades")return <ResponsibilitiesHub season={season} onChange={onPreferencesChange}/>;
 return null;
}

export function DataHubDecisionStrip({season,onNavigate}:{season:SeasonState;onNavigate:(screen:string)=>void}){
 const club=getSelectedClub(season),players=club.players,avgCondition=Math.round(players.reduce((s,p)=>s+p.condition,0)/Math.max(1,players.length)),avgFatigue=Math.round(players.reduce((s,p)=>s+p.fatigue,0)/Math.max(1,players.length)),lowMood=players.filter(p=>p.happiness<55||p.managerTrust<48).length,goals=players.reduce((s,p)=>s+p.goals,0),shots=players.reduce((s,p)=>s+p.shots,0),conversion=shots?Math.round(goals/shots*100):0;
 const insights=[
  {tone:avgFatigue>45?"warn":"ok",title:avgFatigue>45?"Carga física acima do ideal":"Carga física controlada",detail:`Condição média ${avgCondition}% • fadiga ${avgFatigue}%.`,action:"Treino",target:"Elenco"},
  {tone:lowMood>=4?"warn":"ok",title:lowMood>=4?`${lowMood} jogadores em zona de atenção":"Vestiário sem alerta coletivo",detail:"Confiança, satisfação e minutos afetam a resposta do grupo.",action:"Vestiário",target:"Vestiário"},
  {tone:conversion<9?"warn":"ok",title:conversion<9?"Eficiência ofensiva pede revisão":"Ataque convertendo em faixa aceitável",detail:`${goals} gols em ${shots} finalizações registradas • ${conversion}% de conversão.`,action:"Táticas",target:"Táticas"},
 ];
 return <section className={styles.dataDecisions}><header><Activity/><div><span>DATA HUB • DECISÕES</span><b>Transforme números em ações</b></div></header><div>{insights.map(item=><button key={item.title} className={item.tone==="warn"?styles.insightWarn:""} onClick={()=>onNavigate(item.target)}><span><b>{item.title}</b><small>{item.detail}</small></span><em>{item.action} <ChevronRight/></em></button>)}</div></section>;
}

function SquadPlanner({season,onNavigate}:{season:SeasonState;onNavigate:(screen:string)=>void}){
 const club=getSelectedClub(season),slots=["GOL","LD","ZAG","LE","VOL","MC","MEI","PD/PE","ATA"],groups=slots.map(slot=>({slot,players:club.players.filter(player=>plannerSlot(player.position)===slot).sort((a,b)=>b.overall-a.overall)}));
 return <div className={styles.workspace}><section className={styles.workspaceHero}><div><span>PLANEJAMENTO DE ELENCO</span><h2>Quem joga, quem cobre e onde o elenco precisa evoluir</h2><p>Uma visão de squad planner: profundidade, idade, potencial e necessidade de mercado por setor.</p></div><ClipboardList/></section><div className={styles.plannerGrid}>{groups.map(group=>{const first=group.players[0],depth=group.players.length,quality=first?.overall??0,need=!first?"URGENTE":depth<2||quality<64?"ALTA":depth<3?"MÉDIA":"BAIXA";return <section className={styles.positionCard} key={group.slot}><header><b>{group.slot}</b><span className={need==="URGENTE"||need==="ALTA"?styles.needHigh:""}>NECESSIDADE {need}</span></header><div>{group.players.slice(0,4).map((player,index)=><button key={player.id} onClick={()=>openFmEntity({type:"player",id:player.id})}><i>{index===0?"1":index===1?"2":"•"}</i><span><b>{player.name}</b><small>{player.age} anos • OVR {player.overall} • POT {player.potential}</small></span><em>{index===0?"Titular":index===1?"Cobertura":player.squadRole}</em></button>)}</div>{depth<3&&<button className={styles.marketNeed} onClick={()=>onNavigate("Mercado")}><UserRoundSearch/> Encontrar opção para {group.slot}<ChevronRight/></button>}</section>})}</div></div>;
}

function BoardConfidence({season,onNavigate}:{season:SeasonState;onNavigate:(screen:string)=>void}){
 const board=season.boardState,club=getSelectedClub(season),standings=sortedStandings(season.league),position=standings.findIndex(s=>s.clubId===club.id)+1,avgMood=Math.round(club.players.reduce((s,p)=>s+p.morale,0)/Math.max(1,club.players.length)),wage=club.players.reduce((s,p)=>s+p.contract.salaryBrlMonthly,0),finance=Math.round(Math.min(100,club.wageBudgetBrlMonthly/Math.max(1,wage)*80)),last=board.evaluations?.[0];
 const grades=[{label:"Resultados",score:Math.max(0,Math.min(100,78-(position-board.targetPosition)*10))},{label:"Vestiário",score:avgMood},{label:"Finanças",score:finance},{label:"Base",score:board.objectives.find(o=>o.id==="youth")?.progress??50},{label:"Mercado",score:Math.round((club.transferBudgetEur>0?70:50)+(club.players.filter(p=>p.age<=23&&p.potential>p.overall+4).length*2))}];
 return <div className={styles.workspace}><section className={styles.boardHero}><div><span>CONFIANÇA DA DIRETORIA</span><h2>{season.livingWorld.boardConfidence}% • {last?.verdict??"Avaliação em andamento"}</h2><p>{board.mandate.description}</p></div><CircleGauge/></section><div className={styles.boardGrid}><section className={styles.fmCard}><header><span>MANDATO</span><b>{board.mandate.name}</b></header><dl><div><dt>Meta na liga</dt><dd>Top {board.targetPosition}</dd></div><div><dt>Pressão</dt><dd>{board.mandate.pressure}</dd></div><div><dt>Paciência</dt><dd>{board.mandate.patience}/100</dd></div></dl><div className={styles.nonNegotiables}>{board.mandate.nonNegotiables.map(item=><span key={item}><Target/> {item}</span>)}</div></section><section className={styles.fmCard}><header><span>AVALIAÇÃO POR ÁREA</span><button onClick={()=>onNavigate("Clube")}>Gestão <ChevronRight/></button></header><div className={styles.gradeList}>{grades.map(item=><div key={item.label}><span><b>{item.label}</b><em>{grade(item.score)}</em></span><i><b style={{width:`${Math.max(0,Math.min(100,item.score))}%`}}/></i></div>)}</div></section></div><section className={styles.fmCard}><header><span>OBJETIVOS DA TEMPORADA</span><b>{board.objectives.length}</b></header><div className={styles.objectiveGrid}>{board.objectives.map(objective=><article key={objective.id}><span>{objective.category} • {objective.priority}</span><b>{objective.title}</b><p>{objective.description}</p><div><i><b style={{width:`${objective.progress}%`}}/></i><em>{objective.progress}% • {objective.status}</em></div></article>)}</div></section>{last&&<section className={styles.fmCard}><header><span>ÚLTIMA AVALIAÇÃO</span><b>Rodada {last.round}</b></header><p className={styles.boardSummary}>{last.summary}</p></section>}</div>;
}

function ResponsibilitiesHub({season,onChange}:{season:SeasonState;onChange:(preferences:GamePreferences)=>void}){
 const prefs=season.preferences,rows:[keyof GamePreferences["responsibilities"],string,string[]][]=[
  ["matchSelection","Escalação e banco",["Treinador","Adjunto"]],["training","Planejamento de treino",["Treinador","Adjunto"]],["pressConferences","Coletivas de imprensa",["Treinador","Adjunto"]],["teamTalks","Palestras ao elenco",["Treinador","Adjunto"]],["transferTargets","Alvos de contratação",["Treinador","Diretor de futebol"]],["contractRenewals","Prioridades de renovação",["Treinador","Diretor de futebol"]],["outgoingTransfers","Saídas e empréstimos",["Treinador","Diretor de futebol"]],["scouting","Scouting e relatórios",["Treinador","Diretor de futebol"]],["youthDevelopment","Desenvolvimento da base",["Treinador","Responsável pela base"]],
 ];
 const change=(key:keyof GamePreferences["responsibilities"],value:string)=>onChange({...prefs,responsibilities:{...prefs.responsibilities,[key]:value} as GamePreferences["responsibilities"]});
 return <div className={styles.workspace}><section className={styles.workspaceHero}><div><span>RESPONSABILIDADES</span><h2>O que é seu e o que fica com o staff</h2><p>Delegue rotinas sem perder a decisão estratégica. Cada responsabilidade continua gravada por carreira.</p></div><Shield/></section><section className={styles.responsibilityBoard}><header><b>VOCÊ</b><span>ÁREA</span><b>STAFF / DIRETORIA</b></header>{rows.map(([key,label,options])=>{const value=String(prefs.responsibilities[key]);return <article key={key}><div className={value==="Treinador"?styles.ownerActive:""}>Treinador</div><span><b>{label}</b><small>{responsibilityDetail(key)}</small></span><select value={value} onChange={e=>change(key,e.target.value)}>{options.map(option=><option key={option}>{option}</option>)}</select></article>})}</section></div>;
}

function EntityProfile({season,entity,onClose,onNavigate}:{season:SeasonState;entity:FmEntity;onClose:()=>void;onNavigate:(screen:string)=>void}){
 const[tab,setTab]=useState("Visão geral");
 useEffect(()=>setTab("Visão geral"),[entity.type,entity.id]);
 const playerFound=findPlayer(season,entity.id),club=entity.type==="club"?season.league.clubs.find(c=>c.id===entity.id):playerFound?.club,player=entity.type==="player"?playerFound?.player:undefined,competition=professionalCompetitionById(season.competitionId);
 const tabs=player?["Visão geral","Atributos","Desempenho","Desenvolvimento","Contrato","Felicidade","Relações","Histórico"]:club?["Visão geral","Elenco","Resultados","Finanças"]:["Visão geral","Classificação","Estatísticas"];
 return <div className={styles.entityBackdrop} onClick={onClose}><section className={styles.entitySheet} onClick={event=>event.stopPropagation()}><header className={styles.entityTop}><div>{player?<div className={styles.entityAvatar}>{initials(player.name)}</div>:club?<Image src={club.imageUrl} alt={club.name} width={58} height={58}/>:<Trophy size={48}/>}<span><small>{player?`${club?.name} • ${player.position}`:club?competition.name:`COMPETIÇÃO • ${season.year}`}</small><h2>{player?.name??club?.name??competition.name}</h2><p>{player?`${player.age} anos • ${player.nationality??"—"} • ${player.squadRole}`:club?`Reputação ${club.reputation} • elenco ${club.players.length}`:`${season.league.clubs.length} clubes • temporada ${season.year}`}</p></span></div><button onClick={onClose}><X/></button></header><nav className={styles.entityTabs}>{tabs.map(item=><button key={item} className={tab===item?styles.entityTabActive:""} onClick={()=>setTab(item)}>{item}</button>)}</nav><div className={styles.entityContent}>{player&&club?<PlayerEntity season={season} club={club} player={player} tab={tab} onNavigate={onNavigate}/>:club?<ClubEntity season={season} club={club} tab={tab}/>:<CompetitionEntity season={season} tab={tab}/>}</div></section></div>;
}

function PlayerEntity({season,club,player,tab,onNavigate}:{season:SeasonState;club:LeagueClub;player:LeaguePlayer;tab:string;onNavigate:(screen:string)=>void}){
 const influence=playerInfluence(player),attributes=derivedAttributes(player),teammates=club.players.filter(p=>p.id!==player.id).sort((a,b)=>Math.abs(a.overall-player.overall)-Math.abs(b.overall-player.overall)).slice(0,4);
 if(tab==="Atributos")return <div className={styles.attributeGrid}>{attributes.map(group=><section key={group.name}><header>{group.name}</header>{group.items.map(item=><div key={item.label}><span>{item.label}</span><b>{item.value}</b><i><em style={{width:`${item.value}%`}}/></i></div>)}</section>)}</div>;
 if(tab==="Desempenho")return <div className={styles.entityStats}><Metric label="JOGOS" value={String(player.appearances)} detail={`${player.starts} como titular`}/><Metric label="MINUTOS" value={String(player.minutes)} detail={`${player.goals} gols • ${player.assists} assist.`}/><Metric label="NOTA" value={player.ratedMatches?player.averageRating.toFixed(2):"—"} detail={`última ${player.lastRating||"—"}`}/><Metric label="FORMA" value={`${player.form}/10`} detail={`${player.shots} finalizações`}/></div>;
 if(tab==="Desenvolvimento")return <div className={styles.entityColumns}><section><span>DESENVOLVIMENTO</span><h3>OVR {player.overall} → POT {player.potential}</h3><p>Progresso acumulado: {Math.round(player.developmentProgress*100)}%. Foco individual: {player.individualTrainingFocus??"Equilibrado"}.</p><div className={styles.historyBars}>{(player.overallHistory??[]).slice(-8).map(point=><div key={`${point.year}-${point.round}-${point.reason}`}><small>R{point.round}</small><i><b style={{width:`${point.overall}%`}}/></i><strong>{point.overall}</strong></div>)}</div></section><section><span>PLANO</span><h3>{player.retrainingPosition?`Adaptação para ${player.retrainingPosition}`:"Posição consolidada"}</h3><p>{player.mentorPlayerId?"Mentoring ativo com atleta mais experiente.":"Sem mentor definido neste momento."}</p><button onClick={()=>{onNavigate("Elenco");onCloseViaEvent()}}>Abrir gestão do jogador <ChevronRight/></button></section></div>;
 if(tab==="Contrato")return <div className={styles.entityColumns}><section><span>CONTRATO</span><h3>Até {player.contract.endYear}</h3><dl><div><dt>Salário</dt><dd>{brl(player.contract.salaryBrlMonthly)}/mês</dd></div><div><dt>Empresário</dt><dd>{player.contract.agentName}</dd></div><div><dt>Cláusula</dt><dd>{player.contract.releaseClauseEur?eur(player.contract.releaseClauseEur):"—"}</dd></div><div><dt>Mercado</dt><dd>{player.marketValueEur?eur(player.marketValueEur):"—"}</dd></div></dl></section><section><span>STATUS</span><h3>{player.transferListed?"Listado para transferência":player.wantsToLeave?"Deseja sair":"Sem intenção de saída"}</h3><p>{player.promises?.find(p=>p.status==="Ativa")?"Há promessa ativa que pode afetar confiança e felicidade.":"Nenhuma promessa ativa neste momento."}</p></section></div>;
 if(tab==="Felicidade")return <div className={styles.entityStats}><Metric label="FELICIDADE" value={`${player.happiness}%`} detail={player.happiness>=70?"satisfeito":player.happiness>=55?"estável":"atenção"}/><Metric label="CONFIANÇA" value={`${player.managerTrust}%`} detail="relação com treinador"/><Metric label="MORAL" value={`${player.morale}%`} detail={player.personality}/><Metric label="INFLUÊNCIA" value={`${influence}%`} detail={player.squadRole}/></div>;
 if(tab==="Relações")return <div className={styles.entityColumns}><section><span>INFLUÊNCIA SOCIAL</span><h3>{influence}/100</h3><p>O papel no elenco, personalidade e tempo de clube determinam quanto uma decisão sobre este atleta pode repercutir.</p></section><section><span>JOGADORES PRÓXIMOS NO ELENCO</span>{teammates.map(item=><button key={item.id} onClick={()=>openFmEntity({type:"player",id:item.id})}>{item.name}<small>{item.position} • OVR {item.overall}</small><ChevronRight/></button>)}</section></div>;
 if(tab==="Histórico")return <div className={styles.entityColumns}><section><span>CARREIRA NO SAVE</span><h3>{player.joinedClubYear?`No clube desde ${player.joinedClubYear}`:"Histórico inicial"}</h3><p>{player.appearances} partidas, {player.goals} gols e {player.assists} assistências nesta carreira persistente.</p></section><section><span>PROMESSAS</span>{player.promises?.length?player.promises.map(p=><p key={p.id}><b>{p.type}</b> • {p.status} • {p.progressAppearances}/{p.targetAppearances}</p>):<p>Nenhuma promessa registrada.</p>}</section></div>;
 return <div className={styles.entityOverview}><div className={styles.entityStats}><Metric label="OVR" value={String(player.overall)} detail={`potencial ${player.potential}`}/><Metric label="CONDIÇÃO" value={`${player.condition}%`} detail={`fadiga ${player.fatigue}%`}/><Metric label="MORAL" value={`${player.morale}%`} detail={player.status}/><Metric label="VALOR" value={player.marketValueEur?eur(player.marketValueEur):"—"} detail={player.contract.agentName}/></div><section className={styles.profileNarrative}><span>RESUMO DO STAFF</span><h3>{player.squadRole} • {player.personality}</h3><p>{player.overall>=75?"É um dos jogadores capazes de decidir jogos no nível atual do clube.":player.potential-player.overall>=6?"Ainda existe margem importante de evolução e o desenvolvimento deve entrar no planejamento.":"É uma opção estabilizada para a rotação atual."} {player.happiness<55?"Há sinais de insatisfação que precisam ser acompanhados.":"O ambiente individual está controlado."}</p><div><button onClick={()=>openFmEntity({type:"club",id:club.id})}>Ver {club.name}</button><button onClick={()=>onNavigate("Planejamento")}>Ver no Planner</button></div></section></div>;
}
function onCloseViaEvent(){/* A navegação troca a superfície; o painel pode ser fechado pelo usuário. */}

function ClubEntity({season,club,tab}:{season:SeasonState;club:LeagueClub;tab:string}){
 const table=sortedStandings(season.league),standing=table.find(s=>s.clubId===club.id),position=table.findIndex(s=>s.clubId===club.id)+1,avg=Math.round(club.players.reduce((s,p)=>s+p.overall,0)/Math.max(1,club.players.length)),top=[...club.players].sort((a,b)=>b.overall-a.overall).slice(0,6),fixtures=season.league.fixtures.filter(f=>f.played&&(f.homeClubId===club.id||f.awayClubId===club.id)).slice(-6).reverse();
 if(tab==="Elenco")return <div className={styles.entityList}>{top.map(player=><button key={player.id} onClick={()=>openFmEntity({type:"player",id:player.id})}><span><b>{player.name}</b><small>{player.position} • {player.age} anos</small></span><strong>{player.overall}</strong><ChevronRight/></button>)}</div>;
 if(tab==="Resultados")return <div className={styles.entityList}>{fixtures.map(f=>{const home=season.league.clubs.find(c=>c.id===f.homeClubId),away=season.league.clubs.find(c=>c.id===f.awayClubId);return <article key={f.id}><span><b>{home?.shortName} {f.homeGoals} × {f.awayGoals} {away?.shortName}</b><small>Rodada {f.round} • {formatCompactDate(f.date)}</small></span></article>})}</div>;
 if(tab==="Finanças")return <div className={styles.entityStats}><Metric label="VALOR ELENCO" value={eur(club.marketValueEur)} detail="referência de mercado"/><Metric label="ORÇ. TRANSF." value={eur(club.transferBudgetEur)} detail="disponível"/><Metric label="TETO SALARIAL" value={brl(club.wageBudgetBrlMonthly)} detail="por mês"/><Metric label="REPUTAÇÃO" value={String(club.reputation)} detail="0–100"/></div>;
 return <div className={styles.entityOverview}><div className={styles.entityStats}><Metric label="POSIÇÃO" value={`${position}º`} detail={standing?`${standing.points} pontos`:"—"}/><Metric label="OVR MÉDIO" value={String(avg)} detail={`${club.players.length} jogadores`}/><Metric label="REPUTAÇÃO" value={String(club.reputation)} detail="força institucional"/><Metric label="MERCADO" value={eur(club.marketValueEur)} detail="valor do elenco"/></div><section className={styles.profileNarrative}><span>IDENTIDADE DO CLUBE</span><h3>{club.name}</h3><p>Equipe de reputação {club.reputation}, atualmente em {position}º na competição. O elenco tem overall médio {avg} e orçamento de transferências de {eur(club.transferBudgetEur)}.</p></section></div>;
}

function CompetitionEntity({season,tab}:{season:SeasonState;tab:string}){
 const competition=professionalCompetitionById(season.competitionId),table=sortedStandings(season.league),played=season.league.fixtures.filter(f=>f.played),goals=played.reduce((s,f)=>s+(f.homeGoals??0)+(f.awayGoals??0),0);
 if(tab==="Classificação")return <div className={styles.entityList}>{table.slice(0,12).map((row,index)=>{const club=season.league.clubs.find(c=>c.id===row.clubId)!;return <button key={club.id} onClick={()=>openFmEntity({type:"club",id:club.id})}><em>{index+1}</em><span><b>{club.name}</b><small>{row.won}V {row.drawn}E {row.lost}D • SG {row.goalsFor-row.goalsAgainst}</small></span><strong>{row.points} pts</strong></button>})}</div>;
 if(tab==="Estatísticas")return <div className={styles.entityStats}><Metric label="JOGOS" value={String(played.length)} detail={`${season.league.fixtures.length} no calendário`}/><Metric label="GOLS" value={String(goals)} detail={played.length?`${(goals/played.length).toFixed(2)} / jogo`:"—"}/><Metric label="CLUBES" value={String(season.league.clubs.length)} detail={`${season.league.totalRounds??"—"} rodadas`}/><Metric label="TEMPORADA" value={String(season.year)} detail={season.currentDate}/></div>;
 return <div className={styles.entityOverview}><div className={styles.entityStats}><Metric label="CLUBES" value={String(season.league.clubs.length)} detail={competition.country}/><Metric label="RODADAS" value={String(season.league.totalRounds??"—")} detail={`rodada atual ${season.currentRound}`}/><Metric label="JOGOS" value={String(played.length)} detail="disputados"/><Metric label="GOLS" value={String(goals)} detail="registrados"/></div><section className={styles.profileNarrative}><span>COMPETIÇÃO</span><h3>{competition.name}</h3><p>Temporada {season.year}. A competição agora funciona como entidade navegável: clubes, classificação e números podem ser explorados sem abandonar o contexto do save.</p></section></div>;
}

function assistantAdvice(season:SeasonState){const club=getSelectedClub(season),summary=dressingRoomSummary(club,season.currentRound),fatigue=Math.round(club.players.reduce((s,p)=>s+p.fatigue,0)/Math.max(1,club.players.length)),next=getUserFixtures(season).find(f=>!f.played&&f.date&&f.date>=season.currentDate);if(season.livingWorld.boardConfidence<45)return{title:"A diretoria está aumentando a pressão",detail:"Confira objetivos e margem de confiança antes de avançar.",target:"Diretoria"};if(summary.concerns.length>=4)return{title:"Há tensão suficiente para uma conversa no grupo",detail:`${summary.concerns.length} atletas pedem atenção.`,target:"Vestiário"};if(fatigue>=45)return{title:"Considere reduzir a carga antes do próximo jogo",detail:`Fadiga média do elenco em ${fatigue}%.`,target:"Elenco"};if(next)return{title:"Prepare o plano do próximo adversário",detail:`Jogo marcado para ${formatCompactDate(next.date)}.`,target:"Táticas"};return{title:"Use o Data Hub para procurar a próxima vantagem",detail:"Não há alerta urgente no momento.",target:"Central de Dados"};}
function findPlayer(season:SeasonState,id:string){for(const club of season.league.clubs){const player=club.players.find(item=>item.id===id);if(player)return{club,player};}return undefined;}
function plannerSlot(position:string){const p=position.toUpperCase();if(p.includes("GOL"))return"GOL";if(p==="LD"||p.includes("DIREIT"))return"LD";if(p.includes("ZAG"))return"ZAG";if(p==="LE"||p.includes("ESQUERD"))return"LE";if(p.includes("VOL"))return"VOL";if(p==="MC"||p.includes("MEIO-CAMPISTA"))return"MC";if(p.includes("MEI"))return"MEI";if(p.includes("PONTA")||p==="PD"||p==="PE")return"PD/PE";return"ATA";}
function derivedAttributes(player:LeaguePlayer){const v=(offset:number)=>Math.max(35,Math.min(99,Math.round(player.overall+offset+(player.form-6)*1.5)));return[{name:"TÉCNICO",items:[{label:"Finalização",value:v(player.goals>3?4:0)},{label:"Passe",value:v(player.assists>3?3:-1)},{label:"Primeiro toque",value:v(1)},{label:"Técnica",value:v(2)}]},{name:"MENTAL",items:[{label:"Decisões",value:v(player.managerTrust>70?3:0)},{label:"Determinação",value:v(player.personality==="Competitivo"?5:1)},{label:"Trabalho em equipe",value:v(player.happiness>70?3:0)},{label:"Compostura",value:v(player.morale>75?4:0)}]},{name:"FÍSICO",items:[{label:"Condição",value:player.condition},{label:"Resistência",value:Math.max(35,100-player.fatigue)},{label:"Ritmo",value:v(player.age<=24?4:player.age>=32?-4:1)},{label:"Força",value:v(player.age>=27?2:0)}]}];}
function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <div className={styles.fmMetric}><span>{label}</span><b>{value}</b><small>{detail}</small></div>}
function responsibilityDetail(key:keyof GamePreferences["responsibilities"]){const map:Record<keyof GamePreferences["responsibilities"],string>={matchSelection:"Escolha dos 11 e banco no dia de jogo.",training:"Carga e foco semanal da preparação.",pressConferences:"Coletivas pré e pós-jogo.",teamTalks:"Mensagens antes, intervalo e pós-jogo.",transferTargets:"Quem define prioridades e nomes de mercado.",contractRenewals:"Quem prioriza vínculos que precisam ser renovados.",outgoingTransfers:"Quem propõe venda, empréstimo e saída.",scouting:"Quem aciona observação e organiza relatórios.",youthDevelopment:"Quem direciona a evolução das categorias de base."};return map[key];}
function grade(value:number){return value>=85?"A+":value>=76?"A":value>=68?"B":value>=58?"C":value>=45?"D":"E";}
function addDays(iso:string,days:number){const date=new Date(`${iso}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10);}
function weekday(iso:string){return new Intl.DateTimeFormat("pt-BR",{weekday:"short",timeZone:"UTC"}).format(new Date(`${iso}T12:00:00Z`)).replace(".","").toUpperCase();}
function formatLongDate(iso:string){return new Intl.DateTimeFormat("pt-BR",{weekday:"long",day:"2-digit",month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${iso}T12:00:00Z`));}
function formatCompactDate(iso?:string){if(!iso)return"data a definir";return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",timeZone:"UTC"}).format(new Date(`${iso}T12:00:00Z`));}
function dayGreeting(iso:string){const day=new Date(`${iso}T12:00:00Z`).getUTCDay();return day===0?"Domingo de futebol":day===6?"Sábado de jogo":"Bom trabalho";}
function initials(name:string){return name.split(" ").slice(0,2).map(part=>part[0]).join("");}
function eur(value:number){return value>=1_000_000?`€ ${(value/1_000_000).toLocaleString("pt-BR",{maximumFractionDigits:1})} mi`:`€ ${Math.round(value/1_000).toLocaleString("pt-BR")} mil`;}
function brl(value:number){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(value);}
