"use client";

import Image from "next/image";
import { CalendarDays, ChevronRight, Shield, Sparkles } from "lucide-react";
import { sortedStandings } from "@/game-engine/league";
import { dressingRoomSummary } from "@/game-engine/people";
import { getSelectedClub, type SeasonState } from "@/game-engine/season";
import { clubCommitments, nextClubCommitment } from "@/game-engine/calendar-coordinator";
import { openFmEntity } from "./fm-nav";
import styles from "./fm-experience.module.css";

export default function ManagerPortal({season,onNavigate}:{season:SeasonState;onNavigate:(screen:string)=>void}){
 const club=getSelectedClub(season),table=sortedStandings(season.league),row=table.find(item=>item.clubId===club.id),position=Math.max(1,table.findIndex(item=>item.clubId===club.id)+1),pending=season.livingWorld.inbox.filter(item=>!item.resolved),summary=dressingRoomSummary(club,season.currentRound),advice=assistantAdvice(season),next=nextClubCommitment(season),opponent=next?.opponentClubId?season.league.clubs.find(item=>item.id===next.opponentClubId):undefined;
 return <div className={styles.portal}>
  <section className={styles.portalHero}><div><span>PORTAL DO TREINADOR • {longDate(season.currentDate)}</span><h2>{greeting(season.currentDate)}, treinador.</h2><p>{pending.length?`${pending.length} assunto${pending.length===1?" exige":"s exigem"} sua atenção antes de avançar.`:"Agenda limpa. Use o staff, o calendário e os dados para preparar o próximo passo."}</p></div><button onClick={()=>onNavigate(advice.target)}><Sparkles/><span><small>CONSELHO DA COMISSÃO</small><b>{advice.title}</b><em>{advice.detail}</em></span><ChevronRight/></button></section>
  <TwoWeeks season={season} onNavigate={onNavigate}/>
  <div className={styles.portalGrid}>
   <section className={`${styles.fmCard} ${styles.decisionCard}`}><header><span>VOCÊ PRECISA DECIDIR</span><button onClick={()=>onNavigate("Caixa de entrada")}>Ver tarefas <ChevronRight/></button></header>{pending.length?pending.slice(0,4).map((event,index)=><button key={event.id} className={index===0?styles.priorityDecision:""} onClick={()=>onNavigate(event.kind==="Diretoria"?"Diretoria":event.kind==="Coletiva"?"Mídia & Redes":"Caixa de entrada")}><i>{event.kind.slice(0,3).toUpperCase()}</i><span><b>{event.title}</b><small>{event.body}</small></span><em>{index===0?"PRIORIDADE":`R${event.round}`}</em></button>):<div className={styles.emptyTile}><Shield/><b>Sem decisões pendentes</b><small>Você pode avançar ou preparar o próximo compromisso.</small></div>}</section>
   <section className={styles.fmCard}><header><span>PRÓXIMO JOGO</span><button onClick={()=>onNavigate("Táticas")}>Preparar <ChevronRight/></button></header>{next?<div className={styles.nextGame}><TeamButton name={club.name} shortName={club.shortName} imageUrl={club.imageUrl} clubId={club.id}/><div><small>{shortDate(next.date)} • {next.competition}</small><strong>VS</strong><em>{next.isHome?"CASA":"FORA"}</em></div><TeamButton name={next.opponentName} shortName={opponent?.shortName??shortTeam(next.opponentName)} imageUrl={opponent?.imageUrl} clubId={opponent?.id}/></div>:<div className={styles.emptyTile}><CalendarDays/><b>Sem jogo marcado</b></div>}{next?.rescheduledReason&&<p style={{fontSize:10,color:"#8aa39b",margin:"8px 14px 14px"}}>Agenda ajustada: {next.rescheduledReason}</p>}</section>
   <section className={styles.fmCard}><header><span>STATUS DO TRABALHO</span><button onClick={()=>onNavigate("Diretoria")}>Diretoria <ChevronRight/></button></header><div className={styles.statusGrid}><Metric label="LIGA" value={`${position}º`} detail={row?`${row.points} pts • ${row.played} J`:"—"}/><Metric label="DIRETORIA" value={`${season.livingWorld.boardConfidence}%`} detail={season.boardState.mandate.name}/><Metric label="VESTIÁRIO" value={`${Math.round((summary.avgHappiness+summary.avgTrust+summary.unity)/3)}%`} detail={`${summary.concerns.length} questões`}/><Metric label="FORMA" value={season.recentForm.slice(-5).join(" ")||"—"} detail="últimos jogos"/></div></section>
   <section className={styles.fmCard}><header><span>HOJE NO FUTEBOL</span><button onClick={()=>onNavigate("Notícias")}>Central <ChevronRight/></button></header><div className={styles.newsStack}>{season.livingWorld.news.slice(0,4).map((item,index)=><article key={item.id} className={index===0?styles.leadNews:""}><small>{item.source}</small><b>{item.headline}</b><p>{item.summary}</p></article>)}</div></section>
  </div>
 </div>;
}

function TeamButton({name,shortName,imageUrl,clubId}:{name:string;shortName:string;imageUrl?:string;clubId?:string}){return <button onClick={()=>clubId&&openFmEntity({type:"club",id:clubId})} disabled={!clubId}><Image src={imageUrl??"/generic-club.svg"} alt={name} width={46} height={46}/><b>{shortName}</b></button>}

function TwoWeeks({season,onNavigate}:{season:SeasonState;onNavigate:(screen:string)=>void}){const fixtures=clubCommitments(season),days=Array.from({length:14},(_,index)=>addDays(season.currentDate,index));return <section className={styles.fortnight}><header><div><span>PRÓXIMAS DUAS SEMANAS</span><b>Jogos, treino e recuperação</b></div><button onClick={()=>onNavigate("Calendário")}>Calendário completo <ChevronRight/></button></header><div>{days.map((date,index)=>{const fixture=fixtures.find(item=>!item.played&&item.date===date),label=fixture?`${fixture.competition} • ${shortTeam(fixture.opponentName)}`:index%7===0?"Recuperação":season.trainingPlan;return <button key={date} className={`${date===season.currentDate?styles.todayDay:""} ${fixture?styles.matchDay:""}`} onClick={()=>onNavigate(fixture?"Táticas":"Calendário")} title={fixture?`${fixture.competition} • ${fixture.stage} • ${fixture.opponentName}`:undefined}><small>{weekday(date)}</small><b>{date.slice(8)}</b><span>{label}</span></button>})}</div></section>}

function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <div className={styles.fmMetric}><span>{label}</span><b>{value}</b><small>{detail}</small></div>}
function assistantAdvice(season:SeasonState){const club=getSelectedClub(season),summary=dressingRoomSummary(club,season.currentRound),fatigue=Math.round(club.players.reduce((sum,player)=>sum+player.fatigue,0)/Math.max(1,club.players.length)),next=nextClubCommitment(season);if(season.livingWorld.boardConfidence<45)return{title:"A diretoria está aumentando a pressão",detail:"Revise mandato e objetivos.",target:"Diretoria"};if(summary.concerns.length>=4)return{title:"O vestiário pede intervenção",detail:`${summary.concerns.length} atletas em atenção.`,target:"Vestiário"};if(fatigue>=45)return{title:"Considere reduzir a carga",detail:`Fadiga média ${fatigue}%.`,target:"Elenco"};if(next)return{title:`Prepare ${next.competition}`,detail:`${next.opponentName} em ${shortDate(next.date)}.`,target:"Táticas"};return{title:"Procure a próxima vantagem no Data Hub",detail:"Sem alerta urgente.",target:"Central de Dados"}}
function addDays(iso:string,days:number){const date=new Date(`${iso}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10)}
function weekday(iso:string){return new Intl.DateTimeFormat("pt-BR",{weekday:"short",timeZone:"UTC"}).format(new Date(`${iso}T12:00:00Z`)).replace(".","").toUpperCase()}
function longDate(iso:string){return new Intl.DateTimeFormat("pt-BR",{weekday:"long",day:"2-digit",month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${iso}T12:00:00Z`))}
function shortDate(iso?:string){if(!iso)return"data a definir";return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",timeZone:"UTC"}).format(new Date(`${iso}T12:00:00Z`))}
function greeting(iso:string){const day=new Date(`${iso}T12:00:00Z`).getUTCDay();return day===0?"Domingo de futebol":day===6?"Sábado de jogo":"Bom trabalho"}
function shortTeam(name:string){const words=name.split(/\s+/).filter(Boolean);return(words.length===1?words[0]:words.map(word=>word[0]).join("")).slice(0,5).toUpperCase()}
