"use client";

import { useState } from "react";
import { BadgeCheck, CalendarRange, ChevronRight, Flag, Globe2, Shield, Trophy, UserRoundCog } from "lucide-react";
import type { SeasonState } from "@/game-engine/season";
import { managerForClub } from "@/game-engine/club-ai";
import { userWorldCompetitionMatches } from "@/game-engine/world-competitions";
import { NATIONAL_COMPETITIONS_2026, NATIONS_LEAGUE_2026_27_GROUPS, WORLD_CUP_2026_GROUPS } from "@/data/national-teams-2026";
import styles from "./football-world-view.module.css";

type Tab="Competições"|"Seleções"|"Técnicos";
export default function FootballWorldView({season}:{season:SeasonState}){
 const[tab,setTab]=useState<Tab>("Competições"),club=season.league.clubs.find(c=>c.id===season.selectedClubId)!,world=season.worldCompetitions,ai=season.clubAi,userCupMatches=userWorldCompetitionMatches(world,club.id),manager=managerForClub(ai,club.id);
 return <div className={styles.shell}>
  <section className={styles.hero}><div><span>MUNDO DO FUTEBOL</span><h2>O calendário mundial agora faz parte do save</h2><p>Competições de clubes, seleções, formatos reais, técnicos, demissões e mudanças de estilo evoluem junto com a sua carreira.</p></div><div className={styles.heroStat}><Globe2/><div><small>COMPETIÇÕES DE CLUBES</small><b>{world.tournaments.length}</b></div></div></section>
  <nav className={styles.tabs}>{(["Competições","Seleções","Técnicos"] as const).map(item=><button key={item} className={tab===item?styles.active:""} onClick={()=>setTab(item)}>{item==="Competições"?<Trophy/>:item==="Seleções"?<Flag/>:<UserRoundCog/>}{item}</button>)}</nav>
  {tab==="Competições"&&<div className={styles.grid}>
   <section className={styles.panel}><header><div><span>SEU CLUBE NAS COPAS</span><h3>{userCupMatches.length} compromisso{userCupMatches.length===1?"":"s"} agendado{userCupMatches.length===1?"":"s"}</h3></div><CalendarRange/></header><div className={styles.cupList}>{userCupMatches.length?userCupMatches.slice(0,24).map(({tournament,match})=><article key={match.id}><div><b>{tournament.definition.shortName}</b><small>{match.stage}{match.leg?` • ${match.leg}º jogo`:""} • {match.date}</small></div><div className={styles.score}><span>{match.home.shortName}</span><strong>{match.played?`${match.homeGoals} × ${match.awayGoals}`:"×"}</strong><span>{match.away.shortName}</span></div><em>{match.played?(match.decidedByPenalties?"Final • pênaltis":"Final"):"Agendado"}</em></article>):<Empty text="Seu clube não está classificado para uma competição paralela neste momento."/>}</div></section>
   <section className={styles.panel}><header><div><span>TORNEIOS</span><h3>Formatos reais do mundo do save</h3></div><Trophy/></header><div className={styles.tournaments}>{world.tournaments.map(t=><article key={t.definition.id}><div><i><Shield/></i><div><b>{t.definition.name}</b><span>{t.definition.format} • {t.definition.participants.toLocaleString("pt-BR")} participantes</span></div></div><div className={styles.tournamentMeta}><small>{t.completed?"CAMPEÃO":"FASE ATUAL"}</small><strong>{t.completed?world.history.find(h=>h.year===world.season&&h.competitionId===t.definition.id)?.championName??"Definido":t.currentStage}</strong></div><p className={styles.rules}>{t.definition.rulesSummary}</p></article>)}</div></section>
   <section className={`${styles.panel} ${styles.wide}`}><header><div><span>HISTÓRICO DE CAMPEÕES</span><h3>Memória do mundo</h3></div><BadgeCheck/></header><div className={styles.history}>{world.history.length?world.history.slice(0,30).map(item=><article key={`${item.year}-${item.competitionId}`}><b>{item.year}</b><span>{item.competitionName}</span><strong>{item.championName}</strong></article>):<Empty text="Os campeões aparecerão conforme as competições forem concluídas."/>}</div></section>
  </div>}
  {tab==="Seleções"&&<div className={styles.grid}>
   {season.nationalCareer?.status==="Empregado"&&<section className={styles.panel}><header><div><span>SEU CARGO INTERNACIONAL</span><h3>{season.nationalCareer.teamName}</h3></div><Flag/></header><div className={styles.nationIntro}><b>{season.nationalCareer.squadIds.length} convocados</b><span>Trabalho paralelo ao {club.name}</span><p>Próximo compromisso: {season.nationalCareer.fixtures.find(f=>!f.played&&f.date>=season.currentDate)?.date??"a definir"}. Gerencie a convocação no módulo Seleção.</p></div></section>}{NATIONAL_COMPETITIONS_2026.map(comp=><section className={styles.panel} key={comp.id}><header><div><span>SELEÇÕES NACIONAIS</span><h3>{comp.name}</h3></div><Flag/></header><div className={styles.nationIntro}><b>{comp.participants} seleções</b><span>{comp.format}</span><p>{comp.rulesSummary}</p></div><div className={styles.stageList}>{comp.stages.map(stage=><article key={stage.name}><b>{stage.name}</b><span>{stage.dates.join(" → ")}</span><small>{stage.rule}</small></article>)}</div></section>)}
   <section className={`${styles.panel} ${styles.wide}`}><header><div><span>COPA DO MUNDO FIFA 2026</span><h3>12 grupos de quatro seleções</h3></div><Trophy/></header><div className={styles.groupGrid}>{Object.entries(WORLD_CUP_2026_GROUPS).map(([group,teams])=><article key={group}><b>GRUPO {group}</b>{teams.map((team,index)=><span key={team}><i>{index+1}</i>{team}</span>)}</article>)}</div></section>
   <section className={`${styles.panel} ${styles.wide}`}><header><div><span>UEFA NATIONS LEAGUE 2026/27</span><h3>Ligas A–D e seus grupos oficiais</h3></div><Flag/></header>{Object.entries(NATIONS_LEAGUE_2026_27_GROUPS).map(([league,groups])=><div className={styles.nationsLeague} key={league}><h4>LIGA {league}</h4><div className={styles.groupGrid}>{Object.entries(groups).map(([group,teams])=><article key={group}><b>{group}</b>{[...teams].map((team,index)=><span key={team}><i>{index+1}</i>{team}</span>)}</article>)}</div></div>)}</section>
  </div>}
  {tab==="Técnicos"&&<div className={styles.grid}>
   <section className={styles.panel}><header><div><span>BASE REAL DO SEU CLUBE</span><h3>{manager?.managerName??"Treinador"}</h3></div><UserRoundCog/></header>{manager&&<><div className={styles.managerCard}><div><small>BASE</small><b>{manager.realWorldBase?"Mundo real":"Gerado no save"}</b></div><div><small>DATA-BASE</small><b>{manager.realWorldAsOf??"Dinâmica"}</b></div><div><small>ESTILO</small><b>{manager.style}</b></div><div><small>FORMAÇÃO</small><b>{manager.formation}</b></div><div><small>SEGURANÇA</small><b>{manager.jobSecurity}%</b></div><div><small>PACIÊNCIA</small><b>{manager.patience}</b></div></div><p className={styles.managerNote}>Ao iniciar a carreira, o banco usa o técnico real. Quando você assume o clube, ele passa a ser a referência anterior daquele projeto; demissões e contratações futuras podem divergir da realidade.</p></>}</section>
   <section className={styles.panel}><header><div><span>MERCADO DE TÉCNICOS</span><h3>{ai.history.length} mudança{ai.history.length===1?"":"s"} registrada{ai.history.length===1?"":"s"}</h3></div><ChevronRight/></header><div className={styles.moves}>{ai.history.length?ai.history.slice(0,18).map(move=><article key={move.id}><b>{move.clubName}</b><span>{move.oldManager} → {move.newManager}</span><small>R{move.round} • {move.reason}</small></article>):<Empty text="Nenhum clube trocou de treinador dentro do save ainda."/>}</div></section>
   <section className={`${styles.panel} ${styles.wide}`}><header><div><span>TÉCNICOS DA LIGA</span><h3>Base real em 06/09/2026 + evolução dinâmica</h3></div><UserRoundCog/></header><div className={styles.managerTable}>{[...ai.managers].sort((a,b)=>a.jobSecurity-b.jobSecurity).map(item=>{const owner=season.league.clubs.find(c=>c.id===item.clubId);return <article key={item.clubId}><div><b>{owner?.name}</b><span>{item.managerName}{item.realWorldBase?" • base real":" • contratação do save"}</span></div><em>{item.style}</em><span>{item.formation}</span><strong className={item.jobSecurity<35?styles.risk:""}>{item.jobSecurity}%</strong></article>})}</div></section>
  </div>}
 </div>
}
function Empty({text}:{text:string}){return <div className={styles.empty}><Globe2/><b>Mundo em movimento</b><p>{text}</p></div>}
