"use client";
import { useMemo, useState } from "react";
import { Activity, Crosshair, GraduationCap, History, Search, Shield, Star, Stethoscope, UsersRound } from "lucide-react";
import type { SeasonState } from "@/game-engine/season";
import { managerCareerFor } from "@/game-engine/club-ai";
import { scoutingSnapshot, type SetPiecePlan } from "@/game-engine/football-depth";
import styles from "./football-operations-view.module.css";

type Result={state:SeasonState;message:string};
type Tab="Visão"|"Scouting"|"Base"|"Staff"|"Médico"|"Bolas paradas"|"Técnicos";
type Props={season:SeasonState;onResult:(result:Result)=>void;onNavigate:(target:string)=>void;onScout:(playerId:string)=>void;onFavorite:(playerId:string)=>void;onCompare:(playerId:string)=>void;onPromote:(prospectId:string)=>void;onSetPieces:(patch:Partial<SetPiecePlan>)=>void};
const tabs:Tab[]=["Visão","Scouting","Base","Staff","Médico","Bolas paradas","Técnicos"];

export default function FootballOperationsView({season,onNavigate,onScout,onFavorite,onCompare,onPromote,onSetPieces}:Props){
 const[tab,setTab]=useState<Tab>("Visão"),[search,setSearch]=useState("");const club=season.league.clubs.find(c=>c.id===season.selectedClubId)!;
 const allPlayers=useMemo(()=>season.league.clubs.flatMap(c=>c.players.map(player=>({club:c,player}))),[season.league.clubs]),query=search.trim().toLowerCase(),results=query?allPlayers.filter(x=>x.player.name.toLowerCase().includes(query)||x.club.name.toLowerCase().includes(query)||x.player.position.toLowerCase().includes(query)).slice(0,14):[];
 const favoritePlayers=season.depth.favorites.map(id=>allPlayers.find(x=>x.player.id===id)).filter((x):x is NonNullable<typeof x>=>Boolean(x)),comparison=season.depth.comparison.map(id=>allPlayers.find(x=>x.player.id===id)).filter((x):x is NonNullable<typeof x>=>Boolean(x)),digest=season.depth.weeklyDigests[0],highRisk=season.depth.medical.filter(m=>m.injuryRisk>=65),topYouth=[...season.depth.youth].filter(y=>y.status==="Base").sort((a,b)=>b.potential-a.potential).slice(0,5),topReports=[...season.depth.scoutingReports].sort((a,b)=>b.fit-a.fit||b.knowledge-a.knowledge).slice(0,8);
 return <div className={styles.shell}>
  <section className={styles.hero}><div><span>DEPARTAMENTO DE FUTEBOL</span><h2>Staff, scouting, base, medicina e inteligência</h2><p>Quanto melhor a estrutura, melhores ficam as decisões delegadas, a precisão dos relatórios, a recuperação e o desenvolvimento dos jovens.</p></div><UsersRound/></section>
  <div className={styles.shortcuts}><button onClick={()=>onNavigate("Táticas")}>Preparar partida</button><button onClick={()=>onNavigate("Mercado")}>Abrir mercado</button><button onClick={()=>onNavigate("Vestiário")}>Vestiário</button><button onClick={()=>onNavigate("Calendário")}>Calendário</button></div>
  <label className={styles.globalSearch}><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar jogador, clube ou posição no mundo carregado"/></label>
  {results.length>0&&<section className={styles.searchResults}>{results.map(({club:owner,player})=>{const report=scoutingSnapshot(season.depth,player,owner.id,club.id,season.baseSeed);return <article key={player.id}><div><b>{player.name}</b><small>{owner.name} • {player.position} • {player.age} anos</small></div><span>OVR {report.overall[0]===report.overall[1]?report.overall[0]:`${report.overall[0]}–${report.overall[1]}`}</span><em>{report.knowledge}% conhecido</em><button onClick={()=>onScout(player.id)}>Observar</button><button className={season.depth.favorites.includes(player.id)?styles.activeIcon:""} onClick={()=>onFavorite(player.id)} title="Favorito"><Star/></button><button className={season.depth.comparison.includes(player.id)?styles.activeIcon:""} onClick={()=>onCompare(player.id)} title="Comparar">⇄</button></article>})}</section>}
  <div className={styles.tabs}>{tabs.map(item=><button key={item} className={tab===item?styles.active:""} onClick={()=>setTab(item)}>{item}</button>)}</div>

  {tab==="Visão"&&<div className={styles.grid}>
   <section className={styles.panel}><header><Activity/><div><b>RESUMO DA SEMANA</b><small>{digest?.date??season.currentDate}</small></div></header>{digest?<ul>{digest.headlines.map(line=><li key={line}>{line}</li>)}</ul>:<p>O primeiro resumo será gerado ao completar uma semana de calendário.</p>}</section>
   <section className={styles.panel}><header><Star/><div><b>FAVORITOS</b><small>{favoritePlayers.length} monitorados</small></div></header>{favoritePlayers.length?favoritePlayers.slice(0,6).map(x=><PlayerLine key={x.player.id} season={season} ownerId={x.club.id} playerId={x.player.id}/>):<p>Use a busca global para marcar jogadores.</p>}</section>
   <section className={styles.panel}><header><Shield/><div><b>COMPARAÇÃO</b><small>Até dois jogadores</small></div></header>{comparison.length?<div className={styles.compare}>{comparison.map(x=>{const report=scoutingSnapshot(season.depth,x.player,x.club.id,club.id,season.baseSeed);return <div key={x.player.id}><b>{x.player.name}</b><span>OVR {report.overall[0]}–{report.overall[1]}</span><span>POT {report.potential[0]}–{report.potential[1]}</span><span>Encaixe {report.fit}%</span></div>})}</div>:<p>Selecione dois atletas pelo ícone ⇄.</p>}</section>
   <section className={styles.panel}><header><History/><div><b>HISTÓRICO DE NOTIFICAÇÕES</b><small>Scouting, base, médico e rivalidades</small></div></header><div className={styles.notifications}>{season.depth.notifications.slice(0,8).map(n=><article key={n.id}><span>{n.kind}</span><p>{n.text}</p><small>{n.date}</small></article>)}</div></section>
  </div>}

  {tab==="Scouting"&&<div className={styles.grid}><section className={styles.panel}><header><Crosshair/><div><b>MISSÕES DE SCOUTING</b><small>Responsabilidade: {season.preferences.responsibilities.scouting}</small></div></header>{season.depth.assignments.map(a=><div className={styles.assignment} key={a.id}><div><b>{a.name}</b><small>{a.scope} • {a.focus}</small></div><progress max="100" value={a.progress}/><span>{a.progress}%</span></div>)}</section><section className={styles.panel}><header><Search/><div><b>MELHORES RELATÓRIOS</b><small>Precisão cresce com observação e qualidade do olheiro</small></div></header>{topReports.map(r=>{const found=allPlayers.find(x=>x.player.id===r.playerId);if(!found)return null;return <article className={styles.report} key={r.playerId}><div><b>{found.player.name}</b><small>{found.club.name} • {found.player.position}</small></div><span>Conhecimento {r.knowledge}%</span><span>OVR {r.estimatedOverall[0]}–{r.estimatedOverall[1]}</span><strong>Fit {r.fit}%</strong></article>})}</section></div>}

  {tab==="Base"&&<div className={styles.grid}><section className={styles.panel}><header><GraduationCap/><div><b>CATEGORIAS DE BASE</b><small>Sub-17 e Sub-20 • geração anual</small></div></header>{topYouth.map(y=><article className={styles.youth} key={y.id}><div><b>{y.name}</b><small>{y.squad} • {y.position} • {y.age} anos • {y.personality}</small></div><span>OVR {y.overall}</span><span>POT {y.potential}</span><progress max="100" value={y.development}/><button onClick={()=>onPromote(y.id)}>PROMOVER</button></article>)}</section><section className={styles.panel}><header><UsersRound/><div><b>MENTORIAS</b><small>Líderes influenciam jovens do elenco principal</small></div></header>{season.depth.mentorships.map(m=>{const mentor=club.players.find(p=>p.id===m.mentorId),mentee=club.players.find(p=>p.id===m.menteeId);return <article className={styles.mentor} key={`${m.mentorId}-${m.menteeId}`}><b>{mentor?.name??"Mentor"} → {mentee?.name??"Jovem"}</b><span>Química {m.chemistry}%</span></article>})}</section></div>}

  {tab==="Staff"&&<section className={styles.staffGrid}>{season.depth.staff.map(member=><article key={member.id}><span>{member.role}</span><h3>{member.name}</h3><b>Qualidade {member.ability}</b><div><small>Tática {member.tactics}</small><small>Pessoas {member.people}</small><small>Físico {member.fitness}</small><small>Médico {member.medical}</small><small>Capacidade {member.judgingAbility}</small><small>Potencial {member.judgingPotential}</small></div><em>Contrato até {member.contractEndYear}</em></article>)}</section>}

  {tab==="Médico"&&<section className={styles.panel}><header><Stethoscope/><div><b>CENTRO MÉDICO</b><small>{highRisk.length} atletas em atenção</small></div></header><div className={styles.medical}>{[...season.depth.medical].sort((a,b)=>b.injuryRisk-a.injuryRisk).map(m=>{const p=club.players.find(x=>x.id===m.playerId);if(!p)return null;return <article key={m.playerId}><div><b>{p.name}</b><small>{p.position} • condição {p.condition}% • fadiga {p.fatigue}%</small></div><strong className={m.injuryRisk>=72?styles.high:m.injuryRisk>=52?styles.medium:""}>Risco {m.injuryRisk}%</strong><span>Recidiva {m.recurrenceRisk}%</span><p>{m.advice}</p>{m.minutesRestriction&&<em>Limite sugerido: {m.minutesRestriction} min</em>}</article>})}</div></section>}

  {tab==="Bolas paradas"&&<section className={styles.panel}><header><Crosshair/><div><b>BOLAS PARADAS</b><small>As escolhas alimentam o motor da partida</small></div></header><div className={styles.setPieces}><Select label="Escanteio ofensivo" value={season.depth.setPieces.cornerAttack} options={["Primeiro pau","Segundo pau","Curto"]} onChange={v=>onSetPieces({cornerAttack:v as SetPiecePlan["cornerAttack"]})}/><Select label="Defesa de escanteio" value={season.depth.setPieces.cornerDefense} options={["Zona","Mista","Individual"]} onChange={v=>onSetPieces({cornerDefense:v as SetPiecePlan["cornerDefense"]})}/><PlayerSelect label="Pênaltis" value={season.depth.setPieces.penaltyTakerId} players={club.players} onChange={v=>onSetPieces({penaltyTakerId:v})}/><PlayerSelect label="Faltas diretas" value={season.depth.setPieces.freeKickTakerId} players={club.players} onChange={v=>onSetPieces({freeKickTakerId:v})}/><PlayerSelect label="Alvo aéreo" value={season.depth.setPieces.targetId} players={club.players} onChange={v=>onSetPieces({targetId:v})}/></div></section>}

  {tab==="Técnicos"&&<div className={styles.grid}><section className={styles.panel}><header><UsersRound/><div><b>MUNDO DOS TÉCNICOS</b><small>Carreiras, estilos e pressão</small></div></header>{season.clubAi.managers.slice().sort((a,b)=>b.jobSecurity-a.jobSecurity).map(m=>{const career=managerCareerFor(season.clubAi,m.managerName),owner=season.league.clubs.find(c=>c.id===m.clubId),rel=season.depth.managerRelations.find(r=>r.managerName===m.managerName);return <article className={styles.managerLine} key={m.clubId}><div><b>{m.managerName}</b><small>{owner?.name} • {m.style} • {m.formation}</small></div><span>Segurança {m.jobSecurity}</span><span>Rep. {career?.reputation??60}</span>{rel&&<em>Rivalidade {rel.rivalry}% • {rel.meetings} jogos</em>}</article>})}</section><section className={styles.panel}><header><History/><div><b>MUDANÇAS DE COMANDO</b><small>Histórico persistente</small></div></header>{season.clubAi.history.slice(0,14).map(h=><article className={styles.change} key={h.id}><b>{h.clubName}</b><span>{h.oldManager} → {h.newManager}</span><small>R{h.round} • {h.reason}</small></article>)}</section></div>}
 </div>;
}
function PlayerLine({season,ownerId,playerId}:{season:SeasonState;ownerId:string;playerId:string}){const club=season.league.clubs.find(c=>c.id===ownerId),player=club?.players.find(p=>p.id===playerId),mine=season.selectedClubId;if(!club||!player)return null;const r=scoutingSnapshot(season.depth,player,club.id,mine,season.baseSeed);return <div className={styles.playerLine}><b>{player.name}</b><span>{club.name}</span><em>OVR {r.overall[0]===r.overall[1]?r.overall[0]:`${r.overall[0]}–${r.overall[1]}`}</em></div>}
function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(value:string)=>void}){return <label><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></label>}
function PlayerSelect({label,value,players,onChange}:{label:string;value?:string;players:SeasonState["league"]["clubs"][number]["players"];onChange:(value:string)=>void}){return <label><span>{label}</span><select value={value??""} onChange={e=>onChange(e.target.value)}><option value="">Automático</option>{[...players].sort((a,b)=>b.overall-a.overall).map(p=><option value={p.id} key={p.id}>{p.position} • {p.name} • OVR {p.overall}</option>)}</select></label>}
