"use client";
import { useState } from "react";
import { BarChart3,CalendarDays,GitBranch,ListOrdered,Trophy } from "lucide-react";
import type { WorldCompetitionId,WorldCompetitionsState,WorldTournamentState } from "@/game-engine/world-competitions";
import { competitionGroupTables,competitionLeagueTable,internationalQualification,internationalTeamStats } from "@/game-engine/international-browser";
import styles from "./international-competition-browser.module.css";

const IDS:WorldCompetitionId[]=["LIB","SUD","UCL","UEL","UECL"];
type View="Classificação"|"Calendário"|"Mata-mata"|"Estatísticas";
export default function InternationalCompetitionBrowser({state}:{state:WorldCompetitionsState}){
  const tournaments=state.tournaments.filter(item=>IDS.includes(item.definition.id)),[id,setId]=useState<WorldCompetitionId>(tournaments[0]?.definition.id??"LIB"),[view,setView]=useState<View>("Classificação"),tournament=tournaments.find(item=>item.definition.id===id)??tournaments[0];
  const stats=tournament?internationalTeamStats(tournament):[];if(!tournament)return null;
  return <section className={styles.shell}><header><div><span>COMPETIÇÕES INTERNACIONAIS</span><h3>O continente inteiro dentro do seu save</h3><p>Classificações, calendário, mata-mata e estatísticas evoluem com os resultados simulados do universo do Vestiário 90.</p></div><Trophy/></header>
    <div className={styles.picker}>{tournaments.map(item=><button key={item.definition.id} className={item.definition.id===tournament.definition.id?styles.active:""} onClick={()=>setId(item.definition.id)}><b>{item.definition.shortName}</b><small>{item.currentStage}</small></button>)}</div>
    <div className={styles.competitionHead}><div><span>{tournament.definition.format}</span><h4>{tournament.definition.name}</h4><p>{tournament.definition.rulesSummary}</p></div><strong>{tournament.completed?"ENCERRADA":tournament.currentStage.toUpperCase()}</strong></div>
    <nav>{(["Classificação","Calendário","Mata-mata","Estatísticas"] as const).map(item=><button key={item} className={view===item?styles.viewActive:""} onClick={()=>setView(item)}>{item==="Classificação"?<ListOrdered/>:item==="Calendário"?<CalendarDays/>:item==="Mata-mata"?<GitBranch/>:<BarChart3/>}{item}</button>)}</nav>
    {view==="Classificação"&&<Classification tournament={tournament}/>} {view==="Calendário"&&<Calendar tournament={tournament}/>} {view==="Mata-mata"&&<Knockout tournament={tournament}/>} {view==="Estatísticas"&&<div className={styles.stats}><Ranking title="MELHORES ATAQUES" rows={[...stats].sort((a,b)=>b.goalsFor-a.goalsFor).slice(0,10).map(x=>({name:x.participant.name,sub:`${x.played} jogos`,value:String(x.goalsFor)}))}/><Ranking title="MAIS VITÓRIAS" rows={[...stats].sort((a,b)=>b.won-a.won).slice(0,10).map(x=>({name:x.participant.name,sub:`${x.played} jogos`,value:String(x.won)}))}/><Ranking title="MELHORES DEFESAS" rows={[...stats].filter(x=>x.played).sort((a,b)=>a.goalsAgainst-b.goalsAgainst).slice(0,10).map(x=>({name:x.participant.name,sub:`${x.played} jogos`,value:String(x.goalsAgainst)}))}/></div>}
  </section>;
}
function Classification({tournament}:{tournament:WorldTournamentState}){const groups=competitionGroupTables(tournament);if(groups.length)return <div className={styles.groups}>{groups.map(({group,rows})=><section key={group}><b>GRUPO {group}</b><Table rows={rows} id={tournament.definition.id}/></section>)}</div>;const rows=competitionLeagueTable(tournament);return rows.length?<div className={styles.singleTable}><Table rows={rows} id={tournament.definition.id}/></div>:<p className={styles.empty}>Esta competição está em fase eliminatória. Consulte a aba Mata-mata.</p>}
function Table({rows,id}:{rows:ReturnType<typeof competitionLeagueTable>;id:WorldCompetitionId}){return <div className={styles.table}><header><span>#</span><span>CLUBE</span><span>J</span><span>SG</span><span>PTS</span></header>{rows.map((row,index)=>{const zone=internationalQualification(id,index+1);return <article key={row.participant.id}><strong>{index+1}</strong><div><b>{row.participant.name}</b>{zone&&<small data-tone={zone.tone}>{zone.label}</small>}</div><span>{row.played}</span><span>{row.goalsFor-row.goalsAgainst}</span><b>{row.points}</b></article>})}</div>}
function Calendar({tournament}:{tournament:WorldTournamentState}){const matches=[...tournament.matches].sort((a,b)=>a.date.localeCompare(b.date)||a.stage.localeCompare(b.stage));return <div className={styles.calendar}>{matches.map(match=><article key={match.id}><div><span>{match.date}</span><small>{match.group?`Grupo ${match.group} • `:""}{match.stage}{match.matchday?` • J${match.matchday}`:""}</small>{match.originalDate&&<em>remarcado de {match.originalDate}</em>}</div><b>{match.home.name}</b><strong>{match.played?`${match.homeGoals} × ${match.awayGoals}`:"×"}</strong><b>{match.away.name}</b></article>)}</div>}
function Knockout({tournament}:{tournament:WorldTournamentState}){const stages=tournament.definition.stages.filter(stage=>stage.kind==="knockout"),matches=tournament.matches.filter(match=>!match.tableStage);return <div className={styles.knockout}>{stages.map(stage=>{const stageMatches=matches.filter(match=>match.stage===stage.name);return <section key={stage.name}><header><div><b>{stage.name}</b><small>{stage.rule}</small></div><span>{stage.dates.join(" • ")}</span></header>{stageMatches.length?<div>{stageMatches.map(match=><article key={match.id}><span>{match.date}</span><b>{match.home.name}</b><strong>{match.played?`${match.homeGoals} × ${match.awayGoals}`:"×"}</strong><b>{match.away.name}</b>{match.decidedByPenalties&&<em>PÊNALTIS</em>}</article>)}</div>:<p>Confrontos serão definidos quando a fase anterior terminar.</p>}</section>})}</div>}
function Ranking({title,rows}:{title:string;rows:Array<{name:string;sub:string;value:string}>}){return <section><b>{title}</b>{rows.map((row,index)=><article key={`${title}-${row.name}`}><i>{index+1}</i><div><strong>{row.name}</strong><small>{row.sub}</small></div><em>{row.value}</em></article>)}</section>}
