"use client";

import { useState } from "react";
import { Globe2, Search, ArrowRightLeft, Handshake } from "lucide-react";
import type { SeasonState } from "@/game-engine/season";
import { directorMakeInternationalOffer, finalizeInternationalOfferByBoard, globalWindowLabel, isGlobalTransferWindowOpen, listInternationalTargets, reviewInternationalIncomingByBoard, type InternationalMarketResult } from "@/game-engine/international-market";
import { formatEur } from "@/game-engine/market";
import styles from "./market.module.css";

export default function InternationalMarketPanel({season,onResult}:{season:SeasonState;onResult:(result:InternationalMarketResult)=>void}){
 const[query,setQuery]=useState(""),market=season.internationalMarket,targets=listInternationalTargets(season,query).slice(0,100),open=isGlobalTransferWindowOpen(season.currentDate,season.competitionId),incoming=market.offers.filter(o=>o.direction==="Saída").slice(0,20),pendingIncoming=incoming.filter(o=>o.status==="Pendente"),outgoing=market.offers.filter(o=>o.direction==="Entrada").slice(0,30);
 return <div className={styles.proposalGrid}>
  <section className={styles.panel}><header><div><span>MERCADO INTERNACIONAL</span><h2>{open?"Janela global aberta":"Janela global fechada"}</h2><small>Referência do save: {globalWindowLabel(season.competitionId)}.</small></div><label className={styles.search}><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Jogador, clube, país ou posição"/></label></header><div className={styles.tableWrap}><table><thead><tr><th>Jogador</th><th>Clube</th><th>País</th><th>Pos.</th><th>Idade</th><th>Valor</th><th>Ação</th></tr></thead><tbody>{targets.map(target=><tr key={target.id}><td><b>{target.name}</b><small>{target.competitionName}</small></td><td>{target.clubName}</td><td>{target.country}</td><td>{target.position}</td><td>{target.age}</td><td>{target.marketValueEur?formatEur(target.marketValueEur):"—"}</td><td><button disabled={!open} onClick={()=>onResult(directorMakeInternationalOffer(season,target.id))}>Solicitar à diretoria</button></td></tr>)}</tbody></table></div></section>
  <section className={styles.panel}><header><div><span>NEGOCIAÇÕES INTERNACIONAIS</span><h2>{pendingIncoming.length} oferta{pendingIncoming.length===1?"":"s"} em análise da diretoria</h2></div><Globe2/></header><div className={styles.cards}>{incoming.map(offer=><article key={offer.id}><span>{offer.externalCompetitionId}</span><h3>{offer.externalClubName} → {offer.playerName}</h3><strong>{formatEur(offer.feeEur)}</strong><p>{offer.message}</p>{offer.status==="Pendente"&&<div className={styles.decision}><button onClick={()=>onResult(reviewInternationalIncomingByBoard(season,offer.id))}>DIRETORIA DECIDIR</button></div>}</article>)}{!incoming.length&&<Empty text="Nenhuma proposta de fora da sua liga está aguardando resposta."/>}</div><div className={styles.cards}>{outgoing.map(offer=><article key={offer.id}><span>{offer.status}</span><h3>{offer.playerName}</h3><strong>{formatEur(offer.feeEur)}</strong><p>{offer.externalClubName} • {offer.message}</p>{offer.status==="Aceita"&&<button className={styles.finish} onClick={()=>onResult(finalizeInternationalOfferByBoard(season,offer.id))}>Cobrar conclusão da diretoria</button>}</article>)}</div></section>
  <section className={`${styles.panel}`}><header><div><span>TRANSFERÊNCIAS IA × IA</span><h2>Mundo em movimento</h2></div><ArrowRightLeft/></header><div className={styles.history}>{market.history.slice(0,50).map(deal=><article key={deal.id}><Globe2/><div><b>{deal.playerName}</b><span>{deal.from} → {deal.to}</span><small>{deal.kind} • {formatEur(deal.feeEur)} • {deal.year} / R{deal.round}</small></div></article>)}{!market.history.length&&<Empty text="As negociações entre clubes do mundo aparecerão ao avançar a temporada."/>}</div></section>
 </div>
}
function Empty({text}:{text:string}){return <div className={styles.empty}><Handshake/><b>Mercado global tranquilo</b><p>{text}</p></div>}
