"use client";

import { useState } from "react";
import { Globe2, Search, ArrowRightLeft, Handshake, Clock3, Newspaper } from "lucide-react";
import type { SeasonState } from "@/game-engine/season";
import { globalWindowLabel, isGlobalTransferWindowOpen, listInternationalTargets, requestInternationalInterest, type InternationalMarketResult } from "@/game-engine/international-market";
import { formatEur } from "@/game-engine/market";
import styles from "./market.module.css";

export default function InternationalMarketPanel({season,onResult}:{season:SeasonState;onResult:(result:InternationalMarketResult)=>void}){
 const[query,setQuery]=useState("");
 const market=season.internationalMarket;
 const targets=listInternationalTargets(season,query).slice(0,100);
 const open=isGlobalTransferWindowOpen(season.currentDate,season.competitionId);
 const sagas=(market.negotiations??[]).slice().sort((a,b)=>b.createdDate.localeCompare(a.createdDate));
 const active=sagas.filter(item=>item.stage!=="Concluída"&&item.stage!=="Encerrada");
 const incoming=active.filter(item=>item.direction==="Saída");
 const outgoing=active.filter(item=>item.direction==="Entrada");
 return <div className={styles.proposalGrid}>
  <section className={styles.panel}><header><div><span>MERCADO INTERNACIONAL</span><h2>{open?"Janela global aberta":"Janela global fechada"}</h2><small>Referência do save: {globalWindowLabel(season.competitionId)}. O interesse pode ser registrado fora da janela; proposta e registro aguardam a abertura.</small></div><label className={styles.search}><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Jogador, clube, país ou posição"/></label></header><div className={styles.tableWrap}><table><thead><tr><th>Jogador</th><th>Clube</th><th>País</th><th>Pos.</th><th>Idade</th><th>Valor</th><th>Seu pedido</th></tr></thead><tbody>{targets.map(target=>{const process=sagas.find(item=>item.targetId===target.id&&item.stage!=="Concluída"&&item.stage!=="Encerrada");return <tr key={target.id}><td><b>{target.name}</b><small>{process?`Processo: ${process.stage}`:target.competitionName}</small></td><td>{target.clubName}</td><td>{target.country}</td><td>{target.position}</td><td>{target.age}</td><td>{target.marketValueEur?formatEur(target.marketValueEur):"—"}</td><td>{process?<em className={styles.warn}>{process.stage}</em>:<div className={styles.actions}><button onClick={()=>onResult(requestInternationalInterest(season,target.id,"Compra"))}>Interesse em compra</button><button onClick={()=>onResult(requestInternationalInterest(season,target.id,"Empréstimo"))}>Interesse em empréstimo</button></div>}</td></tr>})}</tbody></table></div></section>
  <section className={styles.panel}><header><div><span>PROCESSOS INTERNACIONAIS</span><h2>{active.length} negociação{active.length===1?"":"ões"} em andamento</h2></div><Clock3/></header><div className={styles.cards}>{active.length===0?<Empty text="Nenhuma negociação internacional está em andamento."/>:active.map(item=><article key={item.id}><span>{item.direction==="Entrada"?"ALVO DO TREINADOR":"PROPOSTA PELO SEU ELENCO"} • {item.type} • {item.stage}</span><h3>{item.playerName}</h3><strong>{item.agreedFeeEur?formatEur(item.agreedFeeEur):`ref. ${formatEur(item.referenceFeeEur)}`}</strong><p>{item.direction==="Entrada"?`${season.league.clubs.find(c=>c.id===season.selectedClubId)?.name} ↔ ${item.externalClubName}`:`${item.externalClubName} → seu clube`}</p><small>Próxima atualização: {formatDate(item.nextActionDate)}</small>{item.rivalClubName&&<p><Globe2 size={13}/> {item.rivalClubName} também está na disputa.</p>}{item.leaked&&<p><Newspaper size={13}/> A abordagem vazou para a imprensa e pode encarecer a operação.</p>}<div style={{borderTop:"1px solid #29332f",marginTop:10,paddingTop:8}}>{item.timeline.slice(0,4).map(event=><div key={`${event.date}-${event.label}`} style={{display:"grid",gridTemplateColumns:"62px 1fr",gap:8,padding:"5px 0"}}><small>{formatDate(event.date).slice(0,5)}</small><div><b style={{fontSize:9}}>{event.label}</b><p style={{margin:"2px 0 0",fontSize:8}}>{event.detail}</p></div></div>)}</div></article>)}</div></section>
  <section className={styles.panel}><header><div><span>PROPOSTAS INTERNACIONAIS RECEBIDAS</span><h2>{incoming.length} situação{incoming.length===1?"":"ões"} ativa{incoming.length===1?"":"s"}</h2></div><Globe2/></header><div className={styles.cards}>{incoming.length===0?<Empty text="Nenhum clube estrangeiro está negociando por um jogador do seu elenco."/>:incoming.map(item=><article key={item.id}><span>INFORMATIVO DA DIRETORIA • {item.stage}</span><h3>{item.externalClubName} → {item.playerName}</h3><strong>{formatEur(item.agreedFeeEur??item.referenceFeeEur)}</strong><p>{item.timeline[0]?.detail}</p><small>Você não precisa aprovar ou rejeitar. Diretoria e jogador decidem e informam o resultado pela Caixa de entrada e Notícias.</small></article>)}</div></section>
  <section className={styles.panel}><header><div><span>INTERESSES INTERNACIONAIS SOLICITADOS</span><h2>{outgoing.length} alvo{outgoing.length===1?"":"s"}</h2></div><Handshake/></header><div className={styles.cards}>{outgoing.length===0?<Empty text="Use a lista acima para manifestar interesse em compra ou empréstimo."/>:outgoing.map(item=><article key={item.id}><span>{item.type} • {item.stage}</span><h3>{item.playerName}</h3><strong>{item.agreedFeeEur?formatEur(item.agreedFeeEur):`ref. ${formatEur(item.referenceFeeEur)}`}</strong><p>{item.externalClubName} • {item.timeline[0]?.detail}</p></article>)}</div></section>
  <section className={styles.panel}><header><div><span>TRANSFERÊNCIAS IA × IA</span><h2>Mundo em movimento</h2></div><ArrowRightLeft/></header><div className={styles.history}>{market.history.slice(0,50).map(deal=><article key={deal.id}><Globe2/><div><b>{deal.playerName}</b><span>{deal.from} → {deal.to}</span><small>{deal.kind} • {formatEur(deal.feeEur)} • {deal.year} / R{deal.round}</small></div></article>)}{!market.history.length&&<Empty text="As negociações entre clubes do mundo aparecerão ao avançar a temporada."/>}</div></section>
 </div>
}
function Empty({text}:{text:string}){return <div className={styles.empty}><Handshake/><b>Mercado global tranquilo</b><p>{text}</p></div>}
function formatDate(iso:string){const[y,m,d]=iso.split("-");return`${d}/${m}/${y}`}
