"use client";

import { useEffect, useMemo, useState } from "react";
import { ChevronRight, Gauge, Lightbulb, Pause, Play, Repeat2, ShieldAlert, Users } from "lucide-react";
import type { LeagueClub } from "@/game-engine/league";
import { advanceLiveMatchMinute,isLiveMatchRunning,makeSubstitution,requiredUserSubstitutions,resumeSecondHalf,setTeamTalk,startLiveMatch,updateLiveTactic,type HeatCell,type LiveMatchState,type MatchSpeed,type TeamTalk } from "@/game-engine/live-match";
import { normalizeTactic,type AttackFocus,type BuildUp,type DefensiveLine,type Marking,type Mentality,type SetPiecePost,type TeamWidth } from "@/game-engine/match";
import { layoutLineup } from "@/game-engine/tactics-layout";
import liveStyles from "./live-match.module.css";

const SPEED_MS:Record<MatchSpeed,number>={normal:900,fast:300,very_fast:90};
const SPEED_LABEL:Record<MatchSpeed,string>={normal:"NORMAL",fast:"RÁPIDO",very_fast:"MUITO RÁPIDO"};
const POSITIONS=["GOL","LD","ZAG","LE","VOL","MC","MEI","PD","PE","ATA"];
const HEAT:HeatCell[]=["def-left","def-center","def-right","mid-left","mid-center","mid-right","att-left","att-center","att-right"];
const emptyHeat=()=>Object.fromEntries(HEAT.map(k=>[k,0])) as Record<HeatCell,number>;

export default function LiveMatchView({session,home,away,defaultSpeed,assistantTeamTalks,showStaffAdvice,onChange,onFinish}:{session:LiveMatchState;home:LeagueClub;away:LeagueClub;defaultSpeed:MatchSpeed;assistantTeamTalks:boolean;showStaffAdvice:boolean;onChange:(next:LiveMatchState)=>void;onFinish:(session:LiveMatchState)=>void}){
 const [running,setRunning]=useState(false),[speed,setSpeed]=useState<MatchSpeed>(defaultSpeed),[outId,setOutId]=useState(""),[inId,setInId]=useState("");
 const userSide=session.userSide,userClub=userSide==="home"?home:away,lineupIds=userSide==="home"?session.homeLineupIds:session.awayLineupIds,benchIds=userSide==="home"?session.homeBenchIds:session.awayBenchIds,raw=userSide==="home"?session.homeTactic:session.awayTactic,tactic=normalizeTactic(raw),required=requiredUserSubstitutions(session),subs=session.substitutions.filter(s=>s.side===userSide);
 const byId=useMemo(()=>new Map([...home.players,...away.players].map(p=>[p.id,p])),[home,away]);
 const rank=(id:string)=>{const p=byId.get(id),r=POSITIONS.indexOf(p?.position??"");return (r<0?99:r)*100-(p?.overall??0)};
 const lineup=[...lineupIds].sort((a,b)=>rank(a)-rank(b)),bench=[...benchIds].sort((a,b)=>rank(a)-rank(b));
 const homeLayout=layoutLineup(session.homeLineupIds.map(id=>byId.get(id)).filter((p):p is NonNullable<typeof p>=>Boolean(p)),session.homeTactic.formation),awayLayout=layoutLineup(session.awayLineupIds.map(id=>byId.get(id)).filter((p):p is NonNullable<typeof p>=>Boolean(p)),session.awayTactic.formation);
 const heat:Record<HeatCell,number>=userSide==="home"?(session.homeHeatmap??emptyHeat()):(session.awayHeatmap??emptyHeat()),zones=userSide==="home"?(session.homeAttackZones??{left:0,center:0,right:0}):(session.awayAttackZones??{left:0,center:0,right:0}),zoneTotal=Math.max(1,zones.left+zones.center+zones.right),heatMax=Math.max(1,...HEAT.map(k=>heat[k])),momentum=(userSide==="home"?1:-1)*(session.momentumHome??0);
 useEffect(()=>{if(!running||!isLiveMatchRunning(session)||required.length)return;const timer=window.setTimeout(()=>{const next=advanceLiveMatchMinute(session,home,away);onChange(next);if(next.phase==="halftime"||next.phase==="fulltime"||requiredUserSubstitutions(next).length)setRunning(false);},SPEED_MS[speed]);return()=>window.clearTimeout(timer);},[running,speed,session,home,away,onChange,required.length]);
 useEffect(()=>{if(!assistantTeamTalks||session.phase!=="halftime"||session.teamTalk)return;const gf=userSide==="home"?session.homeGoals:session.awayGoals,ga=userSide==="home"?session.awayGoals:session.homeGoals;onChange(setTeamTalk(session,gf<ga?"Cobrar":gf>ga?"Acalmar":"Incentivar"));},[assistantTeamTalks,session,onChange,userSide]);
 const change=(patch:Partial<typeof raw>)=>onChange(updateLiveTactic(session,userSide,{...raw,...patch})),setPiece=(patch:Partial<typeof tactic.setPieces>)=>change({setPieces:{...tactic.setPieces,...patch}});
 const phase=session.phase==="pre_match"?"PRÉ-JOGO":session.phase==="first_half"?"1º TEMPO":session.phase==="halftime"?"INTERVALO":session.phase==="second_half_window"?"2º TEMPO":"ENCERRADO";
 const gf=userSide==="home"?session.homeGoals:session.awayGoals,ga=userSide==="home"?session.awayGoals:session.homeGoals,shots=userSide==="home"?session.shotsHome:session.shotsAway,oppShots=userSide==="home"?session.shotsAway:session.shotsHome;
 let advice="Manter o plano atual.";let patch:Partial<typeof raw>|undefined;if(session.currentMinute>=65&&gf<ga){advice="Buscar o resultado com linha alta, amplitude e construção mais direta.";patch={mentality:"Ofensiva",defensiveLine:"Alta",width:"Ampla",buildUp:"Direta",pressing:Math.min(90,tactic.pressing+10)};}else if(session.currentMinute>=70&&gf>ga){advice="Controlar vantagem com linha mais baixa e posse curta.";patch={defensiveLine:"Baixa",buildUp:"Curta",tempo:Math.max(40,tactic.tempo-10)};}else if(momentum<-35){advice="O adversário tomou o momentum; mude o corredor principal e acelere.";patch={attackFocus:tactic.attackFocus==="Por dentro"?"Pelos lados":"Por dentro",tempo:Math.min(90,tactic.tempo+8)};}else if(shots+3<oppShots){advice="Estamos cedendo mais finalizações; ajuste marcação e pressão.";patch={marking:"Zona",pressing:Math.min(90,tactic.pressing+7)};}
 const start=()=>{onChange(startLiveMatch(session,home));setRunning(true)},resume=()=>{const next=resumeSecondHalf(session);onChange(next);if(next.phase==="second_half_window")setRunning(true)},substitute=()=>{if(!outId||!inId)return;onChange(makeSubstitution(session,userSide,outId,inId));setOutId("");setInId("");};
 return <div className={liveStyles.layout}>
  <section className={liveStyles.scoreboard}><div className={liveStyles.clock}><span>{phase}</span><strong>{session.phase==="halftime"?"INT":session.phase==="fulltime"?"90′":`${session.currentMinute}′`}</strong></div><div className={liveStyles.scoreLine}><b>{home.shortName}</b><strong>{session.homeGoals}<i>×</i>{session.awayGoals}</strong><b>{away.shortName}</b></div><div className={liveStyles.matchStats}><span>POSSE <b>{session.possessionHome}%</b>–<b>{100-session.possessionHome}%</b></span><span>CHUTES <b>{session.shotsHome}</b>–<b>{session.shotsAway}</b></span><span>xG <b>{session.xgHome.toFixed(2)}</b>–<b>{session.xgAway.toFixed(2)}</b></span><span>ESCANTEIOS <b>{session.cornersHome??0}</b>–<b>{session.cornersAway??0}</b></span></div><div style={{maxWidth:680,margin:"10px auto",display:"grid",gap:5}}><small>MOMENTUM • {momentum>25?`${userClub.shortName} domina`:momentum<-25?"adversário domina":"equilibrado"}</small><div style={{height:9,borderRadius:9,background:"rgba(255,255,255,.12)",position:"relative"}}><i style={{position:"absolute",left:"50%",height:"100%",width:2,background:"#fff"}}/><em style={{position:"absolute",height:"100%",left:momentum>=0?"50%":`${50+momentum/2}%`,width:`${Math.abs(momentum)/2}%`,background:"currentColor",borderRadius:9}}/></div></div><div className={liveStyles.transport}>{session.phase==="pre_match"?<button className={liveStyles.primary} onClick={start}><Play size={15}/> COMEÇAR</button>:session.phase==="fulltime"?<button className={liveStyles.primary} onClick={()=>onFinish(session)}>ENCERRAR <ChevronRight size={16}/></button>:session.phase!=="halftime"?<button className={liveStyles.playPause} disabled={required.length>0} onClick={()=>setRunning(v=>!v)}>{running?<><Pause size={15}/> PAUSAR</>:<><Play size={15}/> CONTINUAR</>}</button>:null}{session.phase!=="pre_match"&&session.phase!=="fulltime"&&<div className={liveStyles.speed}><Gauge size={15}/>{(["normal","fast","very_fast"] as MatchSpeed[]).map(v=><button key={v} className={speed===v?liveStyles.speedActive:""} onClick={()=>setSpeed(v)}>{SPEED_LABEL[v]}</button>)}</div>}</div></section>
  {required.length>0&&<div className={liveStyles.injuryStop}><ShieldAlert/><div><b>TROCA OBRIGATÓRIA</b><span>{required.map(id=>byId.get(id)?.name).filter(Boolean).join(", ")}</span></div></div>}
  {session.phase==="halftime"&&<section className={liveStyles.halftime}><div><Users/><h3>Conversa de intervalo</h3><p>A mensagem altera o momentum no começo do segundo tempo.</p></div><div className={liveStyles.talks}>{(["Cobrar","Incentivar","Acalmar"] as TeamTalk[]).map(v=><button key={v} disabled={assistantTeamTalks} className={session.teamTalk===v?liveStyles.active:""} onClick={()=>onChange(setTeamTalk(session,v))}>{v}</button>)}</div><button className={liveStyles.primary} onClick={resume}>INICIAR 2º TEMPO</button></section>}
  <section className={liveStyles.matchGrid}><div className={liveStyles.pitchPanel}><header><div><b>MAPA TÁTICO AO VIVO</b><small>ocupação 3×3 e zonas de ataque</small></div></header><div className={liveStyles.pitch}><div className={liveStyles.centerCircle}/><div className={`${liveStyles.box} ${liveStyles.topBox}`}/><div className={`${liveStyles.box} ${liveStyles.bottomBox}`}/>{HEAT.map((cell,i)=>{const power=heat[cell]/heatMax;return <div key={cell} style={{position:"absolute",left:`${i%3*33.333}%`,top:`${Math.floor(i/3)*33.333}%`,width:"33.333%",height:"33.333%",background:`rgba(255,255,255,${.02+power*.2})`,border:"1px solid rgba(255,255,255,.04)",pointerEvents:"none"}}/>})}{homeLayout.map(({slot,player})=><div key={player.id} className={`${liveStyles.pitchPlayer} ${liveStyles.homePlayer} ${userSide==="home"?liveStyles.userPlayer:""}`} style={{left:`${slot.x}%`,top:`${slot.y}%`}}><i>{player.position}</i><b>{player.name.split(" ")[0]}</b><small>{session.playerStates[player.id]?.rating.toFixed(1)??"6.0"}</small></div>)}{awayLayout.map(({slot,player})=><div key={player.id} className={`${liveStyles.pitchPlayer} ${liveStyles.awayPlayer} ${userSide==="away"?liveStyles.userPlayer:""}`} style={{left:`${100-slot.x}%`,top:`${100-slot.y}%`}}><i>{player.position}</i><b>{player.name.split(" ")[0]}</b><small>{session.playerStates[player.id]?.rating.toFixed(1)??"6.0"}</small></div>)}</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,paddingTop:10}}>{[["ESQUERDA",zones.left],["CENTRO",zones.center],["DIREITA",zones.right]].map(([l,v])=><div key={String(l)}><small>{l}</small><b style={{display:"block"}}>{Math.round(Number(v)/zoneTotal*100)}%</b></div>)}</div></div>
   <div className={liveStyles.controlColumn}>{showStaffAdvice&&<div className={`${liveStyles.panel} ${liveStyles.staffPanel}`}><header><Lightbulb size={16}/><b>COMISSÃO</b></header><p>{advice}</p>{patch&&<button onClick={()=>change(patch)}>APLICAR AJUSTE</button>}</div>}<div className={liveStyles.panel}><header><ShieldAlert size={16}/><b>INSTRUÇÕES</b></header><Select label="Mentalidade" value={tactic.mentality} options={["Defensiva","Equilibrada","Ofensiva"] as Mentality[]} onChange={v=>change({mentality:v as Mentality})}/><Range label="Pressão" value={tactic.pressing} onChange={v=>change({pressing:v})}/><Range label="Ritmo" value={tactic.tempo} onChange={v=>change({tempo:v})}/><Select label="Ataque" value={tactic.attackFocus} options={["Equilibrado","Pelos lados","Por dentro","Esquerda","Direita"] as AttackFocus[]} onChange={v=>change({attackFocus:v as AttackFocus})}/><Select label="Linha defensiva" value={tactic.defensiveLine} options={["Baixa","Média","Alta"] as DefensiveLine[]} onChange={v=>change({defensiveLine:v as DefensiveLine})}/><Select label="Amplitude" value={tactic.width} options={["Estreita","Normal","Ampla"] as TeamWidth[]} onChange={v=>change({width:v as TeamWidth})}/><Select label="Construção" value={tactic.buildUp} options={["Curta","Mista","Direta"] as BuildUp[]} onChange={v=>change({buildUp:v as BuildUp})}/><Select label="Marcação" value={tactic.marking} options={["Zona","Individual","Mista"] as Marking[]} onChange={v=>change({marking:v as Marking})}/></div><div className={liveStyles.panel}><header><ShieldAlert size={16}/><b>BOLAS PARADAS</b></header><Select label="Escanteio" value={tactic.setPieces.cornerAttack} options={["Primeiro pau","Segundo pau","Centro"] as SetPiecePost[]} onChange={v=>setPiece({cornerAttack:v as SetPiecePost})}/><Select label="Defesa" value={tactic.setPieces.cornerDefense} options={["Zona","Individual","Mista"]} onChange={v=>setPiece({cornerDefense:v as "Zona"|"Individual"|"Mista"})}/>{(["cornerTakerId","freeKickTakerId","penaltyTakerId","targetPlayerId"] as const).map((key,i)=><PlayerSelect key={key} label={["Escanteio","Falta","Pênalti","Alvo"][i]} value={tactic.setPieces[key]??""} ids={lineup} byId={byId} onChange={v=>setPiece({[key]:v||undefined})}/>)}</div><div className={liveStyles.panel}><header><Repeat2 size={16}/><b>SUBSTITUIÇÕES {subs.length}/{session.maxSubstitutions}</b></header><div className={liveStyles.subRow}><label>SAI<select value={outId} onChange={e=>setOutId(e.target.value)}><option value="">Selecione</option>{lineup.map(id=><option key={id} value={id}>{byId.get(id)?.name} • {session.playerStates[id]?.condition.toFixed(0)??100}%</option>)}</select></label><label>ENTRA<select value={inId} onChange={e=>setInId(e.target.value)}><option value="">Selecione</option>{bench.map(id=><option key={id} value={id}>{byId.get(id)?.name}</option>)}</select></label><button disabled={!outId||!inId} onClick={substitute}>TROCAR</button></div></div></div></section>
  <section className={liveStyles.panel}><header><b>NARRAÇÃO & ALTERAÇÕES TÁTICAS</b></header><div style={{display:"grid",gap:6,maxHeight:300,overflow:"auto"}}>{session.events.slice().reverse().slice(0,30).map((e,i)=><div key={`${e.minute}-${i}`} style={{display:"grid",gridTemplateColumns:"42px 1fr",gap:8,borderBottom:"1px solid rgba(255,255,255,.08)",padding:6}}><b>{e.minute}′</b><span>{e.text}</span></div>)}</div></section>
 </div>;
}
function Select({label,value,options,onChange}:{label:string;value:string;options:readonly string[];onChange:(v:string)=>void}){return <label style={{display:"grid",gap:4,marginTop:8}}><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(v=><option key={v}>{v}</option>)}</select></label>}
function Range({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label style={{display:"grid",gap:4,marginTop:8}}><span>{label} <b>{value}</b></span><input type="range" min="20" max="90" value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
function PlayerSelect({label,value,ids,byId,onChange}:{label:string;value:string;ids:string[];byId:Map<string,{name:string;position:string}>;onChange:(v:string)=>void}){return <label style={{display:"grid",gap:4,marginTop:8}}><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}><option value="">Automático</option>{ids.map(id=><option key={id} value={id}>{byId.get(id)?.position} • {byId.get(id)?.name}</option>)}</select></label>}
