"use client";

import { useEffect, useMemo, useState } from "react";
import { ChevronRight, Gauge, Lightbulb, Pause, Play, Repeat2, ShieldAlert, Users } from "lucide-react";
import type { LeagueClub } from "@/game-engine/league";
import { advanceLiveMatchMinute, isLiveMatchRunning, makeSubstitution, requiredUserSubstitutions, resumeSecondHalf, setTeamTalk, startLiveMatch, updateLiveTactic, type HeatCell, type LiveMatchState, type MatchSpeed, type TeamTalk } from "@/game-engine/live-match";
import type { AttackFocus, BuildUp, DefensiveLine, Marking, Mentality, SetPiecePost, TeamWidth } from "@/game-engine/match";
import { normalizeTactic } from "@/game-engine/match";
import { layoutLineup } from "@/game-engine/tactics-layout";
import liveStyles from "./live-match.module.css";

const SPEED_MS:Record<MatchSpeed,number>={normal:900,fast:300,very_fast:90};
const SPEED_LABEL:Record<MatchSpeed,string>={normal:"NORMAL",fast:"RÁPIDO",very_fast:"MUITO RÁPIDO"};
const POSITION_ORDER=["GOL","LD","ZAG","LE","VOL","MC","MEI","PD","PE","ATA"];
const positionRank=(position?:string)=>{const rank=POSITION_ORDER.indexOf(position??"");return rank<0?99:rank};
const HEAT:HeatCell[]=["def-left","def-center","def-right","mid-left","mid-center","mid-right","att-left","att-center","att-right"];

export default function LiveMatchView({session,home,away,defaultSpeed,assistantTeamTalks,showStaffAdvice,onChange,onFinish}:{session:LiveMatchState;home:LeagueClub;away:LeagueClub;defaultSpeed:MatchSpeed;assistantTeamTalks:boolean;showStaffAdvice:boolean;onChange:(next:LiveMatchState)=>void;onFinish:(session:LiveMatchState)=>void}){
 const [running,setRunning]=useState(false),[speed,setSpeed]=useState<MatchSpeed>(defaultSpeed),[outId,setOutId]=useState(""),[inId,setInId]=useState("");
 const userClub=session.userSide==="home"?home:away,userLineupIds=session.userSide==="home"?session.homeLineupIds:session.awayLineupIds,userBenchIds=session.userSide==="home"?session.homeBenchIds:session.awayBenchIds,userTacticRaw=session.userSide==="home"?session.homeTactic:session.awayTactic,userTactic=normalizeTactic(userTacticRaw);
 const substitutions=session.substitutions.filter(s=>s.side===session.userSide),required=requiredUserSubstitutions(session);
 const playerById=useMemo(()=>new Map([...home.players,...away.players].map(p=>[p.id,p])),[home,away]);
 const sortIds=(ids:string[])=>[...ids].sort((a,b)=>positionRank(playerById.get(a)?.position)-positionRank(playerById.get(b)?.position)||(playerById.get(b)?.overall??0)-(playerById.get(a)?.overall??0)||(playerById.get(a)?.name??"").localeCompare(playerById.get(b)?.name??""));
 const sortedLineupIds=sortIds(userLineupIds),sortedBenchIds=sortIds(userBenchIds);
 const homeAssignments=layoutLineup(session.homeLineupIds.map(id=>playerById.get(id)).filter((p):p is NonNullable<typeof p>=>Boolean(p)),session.homeTactic.formation);
 const awayAssignments=layoutLineup(session.awayLineupIds.map(id=>playerById.get(id)).filter((p):p is NonNullable<typeof p>=>Boolean(p)),session.awayTactic.formation);

 useEffect(()=>{if(!running||!isLiveMatchRunning(session)||required.length)return;const timer=window.setTimeout(()=>{const next=advanceLiveMatchMinute(session,home,away);onChange(next);if(next.phase==="halftime"||next.phase==="fulltime"||requiredUserSubstitutions(next).length)setRunning(false);},SPEED_MS[speed]);return()=>window.clearTimeout(timer);},[running,speed,session,home,away,onChange,required.length]);
 useEffect(()=>{if(!assistantTeamTalks||session.phase!=="halftime"||session.teamTalk)return;const goalsFor=session.userSide==="home"?session.homeGoals:session.awayGoals,goalsAgainst=session.userSide==="home"?session.awayGoals:session.homeGoals,talk:TeamTalk=goalsFor<goalsAgainst?"Cobrar":goalsFor>goalsAgainst?"Acalmar":"Incentivar";onChange(setTeamTalk(session,talk));},[assistantTeamTalks,session,onChange]);

 function changeTactic(patch:Partial<typeof userTacticRaw>){onChange(updateLiveTactic(session,session.userSide,{...userTacticRaw,...patch}));}
 function changeSetPieces(patch:Partial<typeof userTactic.setPieces>){changeTactic({setPieces:{...userTactic.setPieces,...patch}});}
 function substitute(){if(!outId||!inId)return;onChange(makeSubstitution(session,session.userSide,outId,inId));setOutId("");setInId("");}
 function start(){onChange(startLiveMatch(session,home));setRunning(true);}
 function resume(){const next=resumeSecondHalf(session);onChange(next);if(next.phase==="second_half_window")setRunning(true);}
 const phaseLabel=session.phase==="pre_match"?"PRÉ-JOGO":session.phase==="first_half"?"1º TEMPO":session.phase==="halftime"?"INTERVALO":session.phase==="second_half_window"?"2º TEMPO":"ENCERRADO";
 const userGoals=session.userSide==="home"?session.homeGoals:session.awayGoals,oppGoals=session.userSide==="home"?session.awayGoals:session.homeGoals,userShots=session.userSide==="home"?session.shotsHome:session.shotsAway,oppShots=session.userSide==="home"?session.shotsAway:session.shotsHome,userPossession=session.userSide==="home"?session.possessionHome:100-session.possessionHome,scoreDiff=userGoals-oppGoals;
 const userMomentum=(session.userSide==="home"?1:-1)*(session.momentumHome??0),userZones=session.userSide==="home"?(session.homeAttackZones??{left:0,center:0,right:0}):(session.awayAttackZones??{left:0,center:0,right:0}),userHeat=session.userSide==="home"?(session.homeHeatmap??{}):(session.awayHeatmap??{}),zoneTotal=Math.max(1,userZones.left+userZones.center+userZones.right),heatMax=Math.max(1,...HEAT.map(k=>userHeat[k]??0));
 const fatigueCandidates=sortedLineupIds.map(id=>({id,p:playerById.get(id),state:session.playerStates[id]})).filter(x=>x.p&&x.state).sort((a,b)=>((a.state?.condition??100)+(a.state?.rating??6)*5-(a.state?.fatigue??0))-((b.state?.condition??100)+(b.state?.rating??6)*5-(b.state?.fatigue??0))),tired=fatigueCandidates[0],forcedId=required[0],subOutId=forcedId??((session.currentMinute>=55&&(tired?.state?.condition??100)<74)?tired?.id:undefined),subOutPlayer=subOutId?playerById.get(subOutId):undefined,subInId=subOutPlayer?(sortedBenchIds.find(id=>playerById.get(id)?.position===subOutPlayer.position)??sortedBenchIds[0]):undefined;
 let staffTitle="Manter o plano",staffDetail="A comissão não vê necessidade de uma mudança estrutural neste momento.",staffPatch:Partial<typeof userTacticRaw>|undefined;
 if(required.length){staffTitle="Troca obrigatória";staffDetail=`${playerById.get(required[0])?.name??"Um jogador"} não consegue continuar.`;}else if(session.currentMinute>=65&&scoreDiff<0){staffTitle="Buscar o resultado";staffDetail=`Atrás no placar, o plano recomendado combina linha alta, mais amplitude e construção direta.`;staffPatch={mentality:"Ofensiva",pressing:Math.min(90,userTactic.pressing+10),tempo:Math.min(90,userTactic.tempo+8),defensiveLine:"Alta",width:"Ampla",buildUp:"Direta"};}else if(session.currentMinute>=70&&scoreDiff>0){staffTitle="Controlar a vantagem";staffDetail="Baixar a linha e circular curto reduz transições adversárias e poupa energia.";staffPatch={mentality:"Equilibrada",pressing:Math.max(38,userTactic.pressing-8),tempo:Math.max(40,userTactic.tempo-10),defensiveLine:"Baixa",buildUp:"Curta"};}else if(userMomentum<-35){staffTitle="Virar o momentum";staffDetail="O adversário domina a sequência recente. Alterar zona de ataque e acelerar a circulação pode quebrar o padrão.";staffPatch={attackFocus:userTactic.attackFocus==="Por dentro"?"Pelos lados":"Por dentro",tempo:Math.min(90,userTactic.tempo+8)};}else if(session.currentMinute>=30&&userPossession<42){staffTitle="Recuperar controle";staffDetail="Posse baixa. Construção curta e marcação por zona ajudam a recuperar território.";staffPatch={buildUp:"Curta",marking:"Zona",pressing:Math.min(90,userTactic.pressing+5)};}

 return <div className={liveStyles.layout}>
  <section className={liveStyles.scoreboard}>
   <div className={liveStyles.clock}><span>{phaseLabel}</span><strong>{session.phase==="halftime"?"INT":session.phase==="fulltime"?"90′":`${String(session.currentMinute).padStart(2,"0")}′`}</strong></div>
   <div className={liveStyles.scoreLine}><b>{home.shortName}</b><strong>{session.homeGoals}<i>×</i>{session.awayGoals}</strong><b>{away.shortName}</b></div>
   <div className={liveStyles.matchStats}><span>POSSE <b>{session.possessionHome}%</b>–<b>{100-session.possessionHome}%</b></span><span>FINALIZAÇÕES <b>{session.shotsHome}</b>–<b>{session.shotsAway}</b></span><span>xG <b>{session.xgHome.toFixed(2)}</b>–<b>{session.xgAway.toFixed(2)}</b></span><span>ESCANTEIOS <b>{session.cornersHome??0}</b>–<b>{session.cornersAway??0}</b></span><span>TROCAS <b>{substitutions.length}/{session.maxSubstitutions}</b></span></div>
   <div style={{display:"grid",gap:6,maxWidth:720,margin:"10px auto 0"}}><div style={{display:"flex",justifyContent:"space-between",fontSize:11,fontWeight:800}}><span>MOMENTUM {away.shortName}</span><b>{userMomentum>20?"VOCÊ ESTÁ POR CIMA":userMomentum<-20?"ADVERSÁRIO PRESSIONA":"PARTIDA EQUILIBRADA"}</b><span>{home.shortName}</span></div><div style={{height:9,borderRadius:99,background:"rgba(255,255,255,.12)",position:"relative",overflow:"hidden"}}><i style={{position:"absolute",left:"50%",top:0,bottom:0,width:2,background:"rgba(255,255,255,.65)"}}/><em style={{position:"absolute",top:1,bottom:1,left:userMomentum>=0?"50%":`${50+userMomentum/2}%`,width:`${Math.abs(userMomentum)/2}%`,background:"currentColor",borderRadius:99}}/></div></div>
   <div className={liveStyles.transport}>{session.phase==="pre_match"?<button className={liveStyles.primary} onClick={start}><Play size={15} fill="currentColor"/> COMEÇAR PARTIDA</button>:session.phase==="fulltime"?<button className={liveStyles.primary} onClick={()=>onFinish(session)}>ENCERRAR PARTIDA <ChevronRight size={16}/></button>:session.phase!=="halftime"?<button className={liveStyles.playPause} disabled={required.length>0} onClick={()=>setRunning(v=>!v)}>{running?<><Pause size={15} fill="currentColor"/> PAUSAR</>:<><Play size={15} fill="currentColor"/> CONTINUAR</>}</button>:null}{session.phase!=="pre_match"&&session.phase!=="fulltime"&&<div className={liveStyles.speed}><Gauge size={15}/>{(["normal","fast","very_fast"] as MatchSpeed[]).map(value=><button key={value} className={speed===value?liveStyles.speedActive:""} onClick={()=>setSpeed(value)}>{SPEED_LABEL[value]}</button>)}</div>}</div>
  </section>
  {required.length>0&&<div className={liveStyles.injuryStop}><ShieldAlert/><div><b>PARTIDA PAUSADA POR LESÃO</b><span>{required.map(id=>playerById.get(id)?.name).filter(Boolean).join(", ")} precisa ser substituído.</span></div></div>}
  {session.phase==="halftime"&&<section className={liveStyles.halftime}><div><Users/><span>INTERVALO</span><h3>Qual é a mensagem para o elenco?</h3><p>A resposta influencia o momentum inicial do segundo tempo.</p></div><div className={liveStyles.talks}>{(["Cobrar","Incentivar","Acalmar"] as TeamTalk[]).map(talk=><button key={talk} disabled={assistantTeamTalks} className={session.teamTalk===talk?liveStyles.active:""} onClick={()=>onChange(setTeamTalk(session,talk))}>{talk}</button>)}</div><button className={liveStyles.primary} disabled={required.length>0} onClick={resume}><Play size={15} fill="currentColor"/> INICIAR 2º TEMPO</button></section>}
  <section className={liveStyles.matchGrid}>
   <div className={liveStyles.pitchPanel}><header><div><b>MAPA TÁTICO AO VIVO</b><small>Ocupação simplificada + zonas de ataque</small></div><span>{userTactic.formation} • {userTactic.mentality}</span></header>
    <div className={liveStyles.pitch}><div className={liveStyles.centerCircle}/><div className={`${liveStyles.box} ${liveStyles.topBox}`}/><div className={`${liveStyles.box} ${liveStyles.bottomBox}`}/>{HEAT.map((cell,index)=>{const col=index%3,row=Math.floor(index/3),power=(userHeat[cell]??0)/heatMax;return <div key={cell} title={`${cell}: ${userHeat[cell]??0}`} style={{position:"absolute",left:`${col*33.333}%`,top:`${row*33.333}%`,width:"33.333%",height:"33.333%",background:`rgba(255,255,255,${Math.min(.22,.025+power*.18)})`,border:"1px solid rgba(255,255,255,.04)",pointerEvents:"none"}}/>;})}{homeAssignments.map(({slot,player})=><div key={`h-${player.id}`} className={`${liveStyles.pitchPlayer} ${liveStyles.homePlayer} ${session.userSide==="home"?liveStyles.userPlayer:""}`} style={{left:`${slot.x}%`,top:`${slot.y}%`}}><i>{player.position}</i><b>{player.name.split(" ")[0]}</b><small>{session.playerStates[player.id]?.rating.toFixed(1)??"6.0"}</small></div>)}{awayAssignments.map(({slot,player})=><div key={`a-${player.id}`} className={`${liveStyles.pitchPlayer} ${liveStyles.awayPlayer} ${session.userSide==="away"?liveStyles.userPlayer:""}`} style={{left:`${100-slot.x}%`,top:`${100-slot.y}%`}}><i>{player.position}</i><b>{player.name.split(" ")[0]}</b><small>{session.playerStates[player.id]?.rating.toFixed(1)??"6.0"}</small></div>)}</div>
    <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,padding:"10px 0"}}>{([['Esquerda',userZones.left],['Centro',userZones.center],['Direita',userZones.right]] as const).map(([label,value])=><div key={label} style={{padding:9,border:"1px solid rgba(255,255,255,.12)",borderRadius:8}}><small>{label.toUpperCase()}</small><b style={{display:"block",fontSize:18}}>{Math.round(value/zoneTotal*100)}%</b><span style={{fontSize:11,opacity:.7}}>{value} ataques</span></div>)}</div>
   </div>
   <div className={liveStyles.controlColumn}>
    {showStaffAdvice&&<div className={`${liveStyles.panel} ${liveStyles.staffPanel}`}><header><Lightbulb size={16}/><div><b>COMISSÃO TÉCNICA</b><small>Leitura de momentum, território e carga.</small></div></header><div className={liveStyles.staffAdvice}><b>{staffTitle}</b><span>{staffDetail}</span></div><div className={liveStyles.staffActions}>{staffPatch&&<button onClick={()=>changeTactic(staffPatch)}>APLICAR AJUSTE</button>}{subOutId&&subInId&&session.phase!=="pre_match"&&session.phase!=="fulltime"&&<button onClick={()=>{setOutId(subOutId);setInId(subInId)}}>PREPARAR TROCA</button>}</div></div>}
    <div className={liveStyles.panel}><header><ShieldAlert size={16}/><div><b>INSTRUÇÕES DA EQUIPE</b><small>Mudanças entram no comportamento da simulação no minuto seguinte.</small></div></header>
     <label>Mentalidade</label><div className={liveStyles.choices}>{(["Defensiva","Equilibrada","Ofensiva"] as Mentality[]).map(value=><button key={value} className={userTactic.mentality===value?liveStyles.active:""} onClick={()=>changeTactic({mentality:value})}>{value}</button>)}</div>
     <label>Pressão <b>{userTactic.pressing}</b></label><input type="range" min="20" max="90" value={userTactic.pressing} onChange={e=>changeTactic({pressing:Number(e.target.value)})}/><label>Ritmo <b>{userTactic.tempo}</b></label><input type="range" min="20" max="90" value={userTactic.tempo} onChange={e=>changeTactic({tempo:Number(e.target.value)})}/>
     <TacticalSelect label="Zona de ataque" value={userTactic.attackFocus} options={["Equilibrado","Pelos lados","Por dentro","Esquerda","Direita"] as AttackFocus[]} onChange={v=>changeTactic({attackFocus:v as AttackFocus})}/>
     <TacticalSelect label="Linha defensiva" value={userTactic.defensiveLine} options={["Baixa","Média","Alta"] as DefensiveLine[]} onChange={v=>changeTactic({defensiveLine:v as DefensiveLine})}/>
     <TacticalSelect label="Amplitude" value={userTactic.width} options={["Estreita","Normal","Ampla"] as TeamWidth[]} onChange={v=>changeTactic({width:v as TeamWidth})}/>
     <TacticalSelect label="Construção" value={userTactic.buildUp} options={["Curta","Mista","Direta"] as BuildUp[]} onChange={v=>changeTactic({buildUp:v as BuildUp})}/>
     <TacticalSelect label="Marcação" value={userTactic.marking} options={["Zona","Individual","Mista"] as Marking[]} onChange={v=>changeTactic({marking:v as Marking})}/>
    </div>
    <div className={liveStyles.panel}><header><ShieldAlert size={16}/><div><b>BOLAS PARADAS</b><small>Cobradores, alvo e zona planejada.</small></div></header>
     <TacticalSelect label="Escanteio ofensivo" value={userTactic.setPieces.cornerAttack} options={["Primeiro pau","Segundo pau","Centro"] as SetPiecePost[]} onChange={v=>changeSetPieces({cornerAttack:v as SetPiecePost})}/>
     <TacticalSelect label="Defesa de escanteio" value={userTactic.setPieces.cornerDefense} options={["Zona","Individual","Mista"]} onChange={v=>changeSetPieces({cornerDefense:v as "Zona"|"Individual"|"Mista"})}/>
     <PlayerSelect label="Cobrador de escanteio" value={userTactic.setPieces.cornerTakerId??""} ids={sortedLineupIds} playerById={playerById} onChange={v=>changeSetPieces({cornerTakerId:v||undefined})}/><PlayerSelect label="Faltas diretas" value={userTactic.setPieces.freeKickTakerId??""} ids={sortedLineupIds} playerById={playerById} onChange={v=>changeSetPieces({freeKickTakerId:v||undefined})}/><PlayerSelect label="Pênaltis" value={userTactic.setPieces.penaltyTakerId??""} ids={sortedLineupIds} playerById={playerById} onChange={v=>changeSetPieces({penaltyTakerId:v||undefined})}/><PlayerSelect label="Jogador alvo" value={userTactic.setPieces.targetPlayerId??""} ids={sortedLineupIds} playerById={playerById} onChange={v=>changeSetPieces({targetPlayerId:v||undefined})}/>
    </div>
    <div className={liveStyles.panel}><header><Repeat2 size={16}/><div><b>SUBSTITUIÇÕES • {substitutions.length}/{session.maxSubstitutions}</b><small>Condição e nota ao vivo.</small></div></header><div className={liveStyles.subRow}><label>SAI<select value={outId} onChange={e=>setOutId(e.target.value)}><option value="">Selecione</option>{sortedLineupIds.map(id=>{const p=playerById.get(id);return <option key={id} value={id}>{required.includes(id)?"🩺 ":""}{p?.position} • {p?.name} • {session.playerStates[id]?.condition.toFixed(0)??p?.condition}% • N {session.playerStates[id]?.rating.toFixed(1)??"6.0"}</option>})}</select></label><label>ENTRA<select value={inId} onChange={e=>setInId(e.target.value)}><option value="">Selecione</option>{sortedBenchIds.map(id=>{const p=playerById.get(id);return <option key={id} value={id}>{p?.position} • {p?.name} • OVR {p?.overall}</option>})}</select></label><button disabled={!outId||!inId||substitutions.length>=session.maxSubstitutions||session.phase==="pre_match"||session.phase==="fulltime"} onClick={substitute}>TROCAR</button></div></div>
   </div>
  </section>
  <section className={liveStyles.panel}><header><div><b>NARRAÇÃO E ALTERAÇÕES</b><small>Chances, bolas paradas e mudanças de plano ficam visíveis no histórico.</small></div></header><div style={{display:"grid",gap:7,maxHeight:310,overflow:"auto"}}>{session.events.slice().reverse().slice(0,28).map((event,index)=><div key={`${event.minute}-${index}-${event.text}`} style={{display:"grid",gridTemplateColumns:"44px 1fr",gap:8,padding:"8px 4px",borderBottom:"1px solid rgba(255,255,255,.08)"}}><b>{event.minute}′</b><span>{event.text}</span></div>)}</div></section>
 </div>;
}

function TacticalSelect({label,value,options,onChange}:{label:string;value:string;options:readonly string[];onChange:(value:string)=>void}){return <label style={{display:"grid",gap:5,marginTop:9}}><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(option=><option key={option} value={option}>{option}</option>)}</select></label>}
function PlayerSelect({label,value,ids,playerById,onChange}:{label:string;value:string;ids:string[];playerById:Map<string,{name:string;position:string}>;onChange:(value:string)=>void}){return <label style={{display:"grid",gap:5,marginTop:9}}><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}><option value="">Automático</option>{ids.map(id=>{const p=playerById.get(id);return <option key={id} value={id}>{p?.position} • {p?.name}</option>})}</select></label>}
