"use client";

import Image from"next/image";
import{useState}from"react";
import{ArrowLeft,BriefcaseBusiness,ChevronRight,Clock3,FolderOpen,Play,Shield,Trash2,Trophy,Users}from"lucide-react";
import{PROFESSIONAL_COMPETITIONS,professionalCompetitionById,type ProfessionalCompetitionId}from"@/data/brazil-2026/competitions";
import{createVacancies,evaluateInterview,INTERVIEW_QUESTIONS,type ClubVacancy,type NewGameMode}from"@/game-engine/new-game";
import{deleteSaveSlot,listSaveSlots,loadSaveSlot,type SaveSlot,type SaveSlotMeta}from"@/game-engine/save-slots";
import styles from"./main-menu.module.css";

export default function MainMenu({onLoad,onStart}:{onLoad:(slot:SaveSlot)=>void;onStart:(competitionId:ProfessionalCompetitionId,clubTransfermarktId:number,saveName?:string)=>void}){
 const[saves,setSaves]=useState<SaveSlotMeta[]>(()=>listSaveSlots()),[view,setView]=useState<"home"|"load"|"mode"|"league"|"clubs"|"vacancies"|"interview">("home"),[mode,setMode]=useState<NewGameMode>("direct"),[competitionId,setCompetitionId]=useState<ProfessionalCompetitionId>("BRA1"),[interview,setInterview]=useState<ClubVacancy|null>(null),[question,setQuestion]=useState(0),[answers,setAnswers]=useState<string[]>([]),[result,setResult]=useState<ReturnType<typeof evaluateInterview>|null>(null),[rejected,setRejected]=useState<number[]>([]),[seed]=useState(()=>`new-career-${Date.now()}`),competition=professionalCompetitionById(competitionId);
 const vacancies=createVacancies(competitionId,seed,8),reload=()=>setSaves(listSaveSlots()),back=()=>{if(view==="load"||view==="mode")setView("home");else if(view==="league")setView("mode");else if(view==="clubs"||view==="vacancies")setView("league");else if(view==="interview"){setInterview(null);setResult(null);setQuestion(0);setAnswers([]);setView("vacancies")}},chooseMode=(next:NewGameMode)=>{setMode(next);setView("league")},chooseLeague=(id:ProfessionalCompetitionId)=>{setCompetitionId(id);setView(mode==="direct"?"clubs":"vacancies")},openInterview=(vacancy:ClubVacancy)=>{setInterview(vacancy);setQuestion(0);setAnswers([]);setResult(null);setView("interview")},answer=(id:string)=>{if(!interview)return;const next=[...answers,id];setAnswers(next);if(question<INTERVIEW_QUESTIONS.length-1)setQuestion(question+1);else setResult(evaluateInterview(interview,next,seed));},remove=(id:string)=>{deleteSaveSlot(id);reload()};
 return <main className={styles.screen}><div className={styles.backdrop}/><section className={styles.panel}>
  <header className={styles.brand}><div className={styles.mark}>V90</div><div><b>VESTIÁRIO 90</b><span>Suas decisões. O mundo reage.</span></div></header>{view!=="home"&&<button className={styles.back} onClick={back}><ArrowLeft size={16}/> Voltar</button>}
  {view==="home"&&<div className={styles.home}><div className={styles.hero}><span>MANAGER DE FUTEBOL</span><h1>Construa sua carreira.<br/>O clube continua vivo.</h1><p>Assuma um clube no Brasil ou nas principais ligas de Inglaterra, Espanha e França — ou dispute uma vaga no mercado.</p></div><div className={styles.homeActions}><button className={styles.primary} onClick={()=>setView("mode")}><span><Play/><b>INICIAR NOVO JOGO</b><small>Escolher país, competição, clube ou buscar emprego</small></span><ChevronRight/></button><button className={styles.secondary} onClick={()=>{reload();setView("load")}}><span><FolderOpen/><b>CARREGAR JOGO</b><small>{saves.length?`${saves.length} save${saves.length>1?"s":""} disponível${saves.length>1?"is":""}`:"Nenhuma carreira salva"}</small></span><ChevronRight/></button></div>{saves[0]&&<button className={styles.continue} onClick={()=>{const slot=loadSaveSlot(saves[0].id);if(slot)onLoad(slot)}}><Clock3/><div><span>CONTINUAR</span><b>{saves[0].name}</b><small>{saves[0].clubName} • {saves[0].competitionName} • {formatDate(saves[0].currentDate)}</small></div><ChevronRight/></button>}<div className={styles.database}><span>BASE 2026/27</span><b>Brasil A/B/C • Premier League • LaLiga • Ligue 1</b><small>Elencos versionados • estatísticas persistentes • evolução de jogadores • saves independentes</small></div></div>}
  {view==="load"&&<section className={styles.content}><Title kicker="CARREIRAS" title="Carregar jogo" text="Cada carreira é salva separadamente e atualizada automaticamente enquanto você joga."/>{!saves.length?<Empty/>:<div className={styles.saveList}>{saves.map(save=><article className={styles.saveCard} key={save.id}><div className={styles.saveIcon}><Shield/></div><div className={styles.saveInfo}><span>{save.competitionName} • {formatDate(save.currentDate)}</span><b>{save.name}</b><small>{save.clubName} • Temporada {save.year} • Rodada {save.currentRound}</small></div><button className={styles.loadButton} onClick={()=>{const slot=loadSaveSlot(save.id);if(slot)onLoad(slot)}}>CARREGAR</button><button className={styles.delete} aria-label="Excluir save" onClick={()=>remove(save.id)}><Trash2 size={16}/></button></article>)}</div>}</section>}
  {view==="mode"&&<section className={styles.content}><Title kicker="NOVO JOGO" title="Como você quer começar?" text="Você pode assumir um clube diretamente ou iniciar como treinador disponível no mercado."/><div className={styles.modeGrid}><Choice icon={<Trophy/>} title="Assumir um clube" text="Escolha a liga e comece imediatamente no comando do time." onClick={()=>chooseMode("direct")}/><Choice icon={<BriefcaseBusiness/>} title="Buscar emprego" text="Veja cargos disponíveis, participe da entrevista e convença a diretoria." onClick={()=>chooseMode("job-market")}/></div></section>}
  {view==="league"&&<section className={styles.content}><Title kicker={mode==="direct"?"ESCOLHA DO CLUBE":"MERCADO DE TREINADORES"} title="Escolha a competição" text={mode==="direct"?"A liga define calendário, adversários, regras do banco e contexto esportivo do save.":"As vagas e a exigência das entrevistas mudam conforme país e competição."}/><div className={styles.leagueGrid}>{PROFESSIONAL_COMPETITIONS.map(item=><button key={item.id} className={styles.leagueCard} onClick={()=>chooseLeague(item.id)}><span>{leagueLabel(item.id,item.country)}</span><b>{item.name}</b><small><Users size={14}/>{item.clubs.length} clubes • {item.country} • 2026/27</small><ChevronRight/></button>)}</div></section>}
  {view==="clubs"&&<section className={styles.content}><Title kicker={`${competition.country.toUpperCase()} • ${competition.shortName.toUpperCase()}`} title="Escolha seu clube" text="O save será criado com elenco, finanças, estatísticas, departamentos e calendário próprios deste clube."/><div className={styles.clubGrid}>{competition.clubs.map(club=><button key={club.transfermarktId} className={styles.clubCard} onClick={()=>onStart(competitionId,club.transfermarktId)}><Crest src={club.imageUrl} name={club.name}/><div><b>{club.name}</b><small>{club.players.length} jogadores • {formatEur(club.marketValueEur)}</small></div><ChevronRight/></button>)}</div></section>}
  {view==="vacancies"&&<section className={styles.content}><Title kicker={`${competition.country.toUpperCase()} • ${competition.shortName.toUpperCase()} • VAGAS`} title="Clubes buscando treinador" text="A diretoria avaliará suas respostas, o perfil do projeto e o nível de exigência da vaga."/><div className={styles.vacancyList}>{vacancies.map(v=><article key={v.clubTransfermarktId} className={`${styles.vacancy} ${rejected.includes(v.clubTransfermarktId)?styles.rejected:""}`}><Crest src={v.imageUrl} name={v.clubName}/><div><span>{v.boardProfile.toUpperCase()} • {v.difficulty}</span><b>{v.clubName}</b><small>{formatEur(v.marketValueEur)} em valor de elenco</small></div>{rejected.includes(v.clubTransfermarktId)?<em>CANDIDATURA ENCERRADA</em>:<button onClick={()=>openInterview(v)}>FAZER ENTREVISTA</button>}</article>)}</div></section>}
  {view==="interview"&&interview&&<section className={styles.content}><Title kicker={`ENTREVISTA • ${interview.clubName}`} title={result?result.approved?"Você recebeu a proposta":"Diretoria escolheu outro perfil":`Pergunta ${question+1} de ${INTERVIEW_QUESTIONS.length}`} text={result?result.message:`Perfil da diretoria: ${interview.boardProfile} • vaga ${interview.difficulty.toLowerCase()}`}/>{!result?<div className={styles.interview}><div className={styles.progress}><i style={{width:`${((question+1)/INTERVIEW_QUESTIONS.length)*100}%`}}/></div><h2>{INTERVIEW_QUESTIONS[question].question}</h2>{INTERVIEW_QUESTIONS[question].answers.map(item=><button key={item.id} onClick={()=>answer(item.id)}>{item.label}<ChevronRight/></button>)}</div>:<div className={`${styles.interviewResult} ${result.approved?styles.approved:styles.denied}`}><strong>{result.score}</strong><span>ADERÊNCIA À DIRETORIA</span>{result.approved?<button onClick={()=>onStart(competitionId,interview.clubTransfermarktId,`${interview.clubName} • carreira`)}>ASSINAR E ASSUMIR O CLUBE</button>:<button onClick={()=>{setRejected([...rejected,interview.clubTransfermarktId]);setInterview(null);setResult(null);setQuestion(0);setAnswers([]);setView("vacancies")}}>VOLTAR AO MERCADO</button>}</div>}</section>}
 </section></main>;
}
function leagueLabel(id:ProfessionalCompetitionId,country:string){if(id==="BRA1")return"BRASIL • 1ª DIVISÃO";if(id==="BRA2")return"BRASIL • 2ª DIVISÃO";if(id==="BRA3")return"BRASIL • 3ª DIVISÃO";return country.toUpperCase()+" • 1ª DIVISÃO";}
function Title({kicker,title,text}:{kicker:string;title:string;text:string}){return <header className={styles.title}><span>{kicker}</span><h1>{title}</h1><p>{text}</p></header>}
function Choice({icon,title,text,onClick}:{icon:React.ReactNode;title:string;text:string;onClick:()=>void}){return <button className={styles.choice} onClick={onClick}><i>{icon}</i><b>{title}</b><p>{text}</p><span>Selecionar <ChevronRight size={15}/></span></button>}
function Empty(){return <div className={styles.empty}><FolderOpen/><b>Nenhum jogo salvo</b><p>Crie uma nova carreira para começar.</p></div>}
function Crest({src,name}:{src:string;name:string}){return <span className={styles.crest}><Image src={src} alt={`Escudo ${name}`} width={44} height={44}/></span>}
function formatDate(iso:string){try{return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(`${iso}T12:00:00Z`));}catch{return iso}}
function formatEur(value:number){return value>=1_000_000?`€ ${(value/1_000_000).toLocaleString("pt-BR",{maximumFractionDigits:1})} mi`:`€ ${Math.round(value/1000).toLocaleString("pt-BR")} mil`}
