"use client";

import Image from "next/image";
import { useLayoutEffect, useMemo, useState } from "react";
import { ArrowLeft, BriefcaseBusiness, Check, ChevronRight, Clock3, FolderOpen, Globe2, Play, RotateCcw, Settings, Shield, Trash2, Trophy, UserRoundCog, Users } from "lucide-react";
import { PROFESSIONAL_COMPETITIONS, professionalCompetitionById, type ProfessionalCompetitionId } from "@/data/brazil-2026/competitions";
import { createVacancies, evaluateInterview, INTERVIEW_QUESTIONS, type ClubVacancy, type NewGameMode } from "@/game-engine/new-game";
import { setPendingNewGameSetup, type ManagerSetupProfile } from "@/game-engine/new-game-setup";
import { deleteSaveSlotAsync, listSaveSlots, loadSaveSlotAsync, recoverSaveSlotBackup, type SaveSlot, type SaveSlotMeta } from "@/game-engine/save-slots";
import { setCareerAutosavePaused } from "./use-career-autosave";
import GlobalSettingsView from "./global-settings-view";
import styles from "./main-menu.module.css";

type MenuView="home"|"load"|"manager"|"database"|"mode"|"league"|"clubs"|"vacancies"|"interview"|"settings";
const FIELD_STYLE={width:"100%",height:44,border:"1px solid #34433d",borderRadius:10,background:"#0d1512",color:"#f2f5f3",padding:"0 12px",fontSize:12} as const;
const SMALL_BUTTON={minHeight:34,border:"1px solid #34433d",borderRadius:9,background:"#17201d",color:"#dce5e1",padding:"7px 11px",fontSize:9,fontWeight:900,cursor:"pointer"} as const;

export default function MainMenu({onLoad,onStart}:{onLoad:(slot:SaveSlot)=>void;onStart:(competitionId:ProfessionalCompetitionId,clubTransfermarktId:number,saveName?:string)=>void}){
 const[saves,setSaves]=useState<SaveSlotMeta[]>(()=>listSaveSlots()),[view,setView]=useState<MenuView>("home"),[mode,setMode]=useState<NewGameMode>("direct"),[competitionId,setCompetitionId]=useState<ProfessionalCompetitionId>("BRA1"),[interview,setInterview]=useState<ClubVacancy|null>(null),[question,setQuestion]=useState(0),[answers,setAnswers]=useState<string[]>([]),[result,setResult]=useState<ReturnType<typeof evaluateInterview>|null>(null),[rejected,setRejected]=useState<number[]>([]),[loadingId,setLoadingId]=useState<string|null>(null),[saveError,setSaveError]=useState(""),[managerName,setManagerName]=useState(""),[managerNationality,setManagerNationality]=useState("Brasil"),[managerAge,setManagerAge]=useState(35),[managerBackground,setManagerBackground]=useState<ManagerSetupProfile["background"]>("Sem carreira profissional"),[managerError,setManagerError]=useState(""),[selectedLeagues,setSelectedLeagues]=useState<ProfessionalCompetitionId[]>(["BRA1"]),[seed]=useState(()=>`new-career-${Date.now()}`),competition=professionalCompetitionById(competitionId);
 useLayoutEffect(()=>{setCareerAutosavePaused(true);return()=>setCareerAutosavePaused(false)},[]);
 const vacancies=createVacancies(competitionId,seed,8),reload=()=>setSaves(listSaveSlots()),selectedDefinitions=useMemo(()=>PROFESSIONAL_COMPETITIONS.filter(item=>selectedLeagues.includes(item.id)),[selectedLeagues]);
 const back=()=>{setSaveError("");setManagerError("");if(view==="load"||view==="manager"||view==="settings")setView("home");else if(view==="database")setView("manager");else if(view==="mode")setView("database");else if(view==="league")setView("mode");else if(view==="clubs"||view==="vacancies")setView("league");else if(view==="interview"){setInterview(null);setResult(null);setQuestion(0);setAnswers([]);setView("vacancies")}};
 const continueManager=()=>{const name=managerName.trim();if(name.length<2){setManagerError("Digite o nome do treinador para continuar.");return}if(managerAge<18||managerAge>80){setManagerError("A idade do treinador deve ficar entre 18 e 80 anos.");return}setManagerError("");setManagerName(name);setView("database")};
 const toggleLeague=(id:ProfessionalCompetitionId)=>setSelectedLeagues(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);
 const choosePreset=(kind:"brazil"|"main"|"all")=>{const countries=kind==="main"?new Set(["Brasil","Inglaterra","Espanha","França","Itália","Alemanha","Portugal"]):null;setSelectedLeagues(PROFESSIONAL_COMPETITIONS.filter(item=>kind==="all"||(kind==="brazil"?item.country==="Brasil":countries!.has(item.country))).map(item=>item.id));};
 const chooseMode=(next:NewGameMode)=>{setMode(next);const first=selectedDefinitions[0];if(first)setCompetitionId(first.id);setView("league")},chooseLeague=(id:ProfessionalCompetitionId)=>{setCompetitionId(id);setView(mode==="direct"?"clubs":"vacancies")},openInterview=(vacancy:ClubVacancy)=>{setInterview(vacancy);setQuestion(0);setAnswers([]);setResult(null);setView("interview")},answer=(id:string)=>{if(!interview)return;const next=[...answers,id];setAnswers(next);if(question<INTERVIEW_QUESTIONS.length-1)setQuestion(question+1);else setResult(evaluateInterview(interview,next,seed));};
 const startCareer=(clubTransfermarktId:number,clubName:string,saveName?:string)=>{const active=Array.from(new Set<ProfessionalCompetitionId>([competitionId,...selectedLeagues]));setPendingNewGameSetup({manager:{name:managerName.trim(),nationality:managerNationality.trim()||"Brasil",age:managerAge,background:managerBackground},loadedCompetitionIds:active});onStart(competitionId,clubTransfermarktId,saveName??`${managerName.trim()} • ${clubName}`)};
 const remove=async(id:string)=>{if(loadingId)return;setLoadingId(id);setSaveError("");try{const removeResult=await deleteSaveSlotAsync(id);if(!removeResult.ok)setSaveError(removeResult.error??"A carreira foi bloqueada contra restauração, mas a limpeza durável ficou pendente.");}finally{setLoadingId(null);reload()}};
 const openSave=async(id:string,recover=false)=>{if(loadingId)return;setLoadingId(id);setSaveError("");try{const slot=recover?await recoverSaveSlotBackup(id):await loadSaveSlotAsync(id);if(slot){onLoad(slot);return}setSaveError(recover?"Não foi possível recuperar uma versão anterior deste save.":"O save não pôde ser validado. Tente recuperar o backup disponível.");}finally{setLoadingId(null);reload()}};
 return <main className={styles.screen}><div className={styles.backdrop}/><section className={styles.panel}>
  <header className={styles.brand}><div className={styles.mark}>V90</div><div><b>VESTIÁRIO 90</b><span>Suas decisões. O mundo reage.</span></div></header>{view!=="home"&&<button className={styles.back} onClick={back}><ArrowLeft size={16}/> Voltar</button>}
  {view==="home"&&<div className={styles.home}><div className={styles.hero}><span>MANAGER DE FUTEBOL</span><h1>Construa sua carreira.<br/>O clube continua vivo.</h1><p>Crie seu treinador, escolha quais ligas terão simulação ativa e então decida onde sua carreira vai começar.</p></div><div className={styles.homeActions}><button className={styles.primary} onClick={()=>setView("manager")}><span><Play/><b>INICIAR NOVO JOGO</b><small>Criar treinador, selecionar ligas e escolher o clube</small></span><ChevronRight/></button><button className={styles.secondary} onClick={()=>{reload();setView("load")}}><span><FolderOpen/><b>CARREGAR JOGO</b><small>{saves.length?`${saves.length} save${saves.length>1?"s":""} disponível${saves.length>1?"is":""}`:"Nenhuma carreira salva"}</small></span><ChevronRight/></button><button className={styles.secondary} onClick={()=>setView("settings")}><span><Settings/><b>CONFIGURAÇÕES DO JOGO</b><small>Base de dados, autosave e comportamento geral</small></span><ChevronRight/></button></div>{saves[0]&&<button className={styles.continue} disabled={loadingId===saves[0].id} onClick={()=>void openSave(saves[0].id)}><Clock3/><div><span>{loadingId===saves[0].id?"VALIDANDO SAVE...":"CONTINUAR"}</span><b>{saves[0].name}</b><small>{saves[0].clubName} • {saves[0].competitionName} • {formatDate(saves[0].currentDate)}{saves[0].saveVersion?" • Save 2.1":""}</small></div><ChevronRight/></button>}<div className={styles.database}><span>BASE 2026/27 • SAVE 2.1</span><b>{PROFESSIONAL_COMPETITIONS.length} ligas disponíveis para configurar por save</b><small>As ligas escolhidas avançam junto com a sua carreira</small></div></div>}
  {view==="settings"&&<section className={`${styles.content} ${styles.settingsContent}`}><GlobalSettingsView/></section>}
  {view==="load"&&<section className={styles.content}><Title kicker="CARREIRAS • SAVE 2.1" title="Carregar jogo" text="As carreiras são validadas antes de abrir. Saves antigos continuam compatíveis e mantêm todas as ligas ativas, como funcionavam antes."/>{saveError&&<div className={styles.empty}><Shield/><b>Proteção de save ativada</b><p>{saveError}</p></div>}{!saves.length?<Empty/>:<div className={styles.saveList}>{saves.map(save=><article className={styles.saveCard} key={save.id}><div className={styles.saveIcon}><Shield/></div><div className={styles.saveInfo}><span>{save.competitionName} • {formatDate(save.currentDate)}</span><b>{save.name}</b><small>{save.clubName} • Temporada {save.year} • Rodada {save.currentRound}</small><small>{save.saveVersion?`SAVE 2.1 • ${save.storage==="indexeddb"?"armazenamento durável":"compatibilidade local"} • ${save.backupCount??0} backup${(save.backupCount??0)===1?"":"s"}${save.sizeBytes?` • ${formatBytes(save.sizeBytes)}`:""}`:"Save legado • será migrado ao próximo salvamento"}</small></div><button className={styles.loadButton} disabled={Boolean(loadingId)} onClick={()=>void openSave(save.id)}>{loadingId===save.id?"PROCESSANDO...":"CARREGAR"}</button>{Boolean(save.backupCount)&&<button className={styles.loadButton} disabled={Boolean(loadingId)} onClick={()=>void openSave(save.id,true)}><RotateCcw size={14}/> RECUPERAR</button>}<button className={styles.delete} aria-label={loadingId===save.id?"Excluindo save":"Excluir save"} disabled={Boolean(loadingId)} onClick={()=>void remove(save.id)}><Trash2 size={16}/></button></article>)}</div>}</section>}
  {view==="manager"&&<section className={styles.content}><Title kicker="NOVO JOGO • 1 DE 3" title="Crie seu treinador" text="Esse perfil acompanhará a carreira e ficará salvo junto com a história, reputação e passagens pelos clubes."/><div style={{maxWidth:650,margin:"0 auto",padding:20,border:"1px solid #2d3934",borderRadius:16,background:"#121a17",display:"grid",gap:14}}><div style={{display:"flex",alignItems:"center",gap:12,paddingBottom:6}}><span style={{width:48,height:48,borderRadius:14,display:"grid",placeItems:"center",background:"#183527",color:"#54d28c"}}><UserRoundCog/></span><div><b style={{display:"block",fontSize:14}}>Perfil do treinador</b><small style={{color:"#8b9992"}}>Dados pessoais e experiência inicial</small></div></div><label style={{display:"grid",gap:6}}><small style={{fontWeight:900,color:"#aab5b0"}}>NOME</small><input autoFocus value={managerName} onChange={event=>setManagerName(event.target.value)} placeholder="Ex.: Raul Soares" style={FIELD_STYLE}/></label><div style={{display:"grid",gridTemplateColumns:"1fr 120px",gap:10}}><label style={{display:"grid",gap:6}}><small style={{fontWeight:900,color:"#aab5b0"}}>NACIONALIDADE</small><input value={managerNationality} onChange={event=>setManagerNationality(event.target.value)} style={FIELD_STYLE}/></label><label style={{display:"grid",gap:6}}><small style={{fontWeight:900,color:"#aab5b0"}}>IDADE</small><input type="number" min={18} max={80} value={managerAge} onChange={event=>setManagerAge(Number(event.target.value)||18)} style={FIELD_STYLE}/></label></div><label style={{display:"grid",gap:6}}><small style={{fontWeight:900,color:"#aab5b0"}}>EXPERIÊNCIA ANTERIOR</small><select value={managerBackground} onChange={event=>setManagerBackground(event.target.value as ManagerSetupProfile["background"])} style={FIELD_STYLE}><option>Sem carreira profissional</option><option>Ex-jogador amador</option><option>Ex-jogador profissional</option></select></label>{managerError&&<small style={{color:"#ff8e96",fontWeight:800}}>{managerError}</small>}<button className={styles.primary} onClick={continueManager}><span><UserRoundCog/><b>CONTINUAR</b><small>Escolher as ligas deste save</small></span><ChevronRight/></button></div></section>}
  {view==="database"&&<section className={styles.content}><Title kicker="NOVO JOGO • 2 DE 3" title="Quais ligas estarão ativas?" text="Só as ligas selecionadas serão simuladas rodada a rodada. Você ainda poderá consultar referências das demais ligas na base do V90."/><div style={{maxWidth:940,margin:"0 auto",display:"grid",gap:12}}><div style={{display:"flex",gap:7,flexWrap:"wrap",alignItems:"center",justifyContent:"space-between",padding:"10px 12px",border:"1px solid #2d3934",borderRadius:12,background:"#121a17"}}><div><b style={{display:"block",fontSize:12}}>{selectedLeagues.length} liga{selectedLeagues.length===1?"":"s"} ativa{selectedLeagues.length===1?"":"s"}</b><small style={{color:"#8b9992"}}>{selectedDefinitions.reduce((sum,item)=>sum+item.clubs.length,0)} clubes no universo simulado</small></div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><button style={SMALL_BUTTON} onClick={()=>choosePreset("brazil")}>SÓ BRASIL</button><button style={SMALL_BUTTON} onClick={()=>choosePreset("main")}>PRINCIPAIS</button><button style={SMALL_BUTTON} onClick={()=>choosePreset("all")}>TODAS</button><button style={SMALL_BUTTON} onClick={()=>setSelectedLeagues([])}>LIMPAR</button></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:8,maxHeight:390,overflow:"auto",padding:2}}>{PROFESSIONAL_COMPETITIONS.map(item=>{const active=selectedLeagues.includes(item.id);return <button key={item.id} onClick={()=>toggleLeague(item.id)} style={{minHeight:82,border:`1px solid ${active?"#54d28c":"#2d3934"}`,borderRadius:12,background:active?"#183527":"#121a17",color:"#e9efec",padding:12,textAlign:"left",cursor:"pointer",display:"grid",gridTemplateColumns:"1fr auto",gap:5}}><span><small style={{display:"block",fontSize:8,color:active?"#83e3ad":"#829089",fontWeight:900}}>{item.country.toUpperCase()} • {item.shortName.toUpperCase()}</small><b style={{display:"block",fontSize:11,marginTop:4}}>{item.name}</b><small style={{color:"#84928b",fontSize:8}}>{item.clubs.length} clubes</small></span><i style={{width:25,height:25,borderRadius:8,display:"grid",placeItems:"center",background:active?"#54d28c":"#202a26",color:active?"#07130d":"#66736d"}}>{active?<Check size={15}/>:<Globe2 size={14}/>}</i></button>})}</div><button className={styles.primary} disabled={!selectedLeagues.length} style={{opacity:selectedLeagues.length?1:.45}} onClick={()=>selectedLeagues.length&&setView("mode")}><span><Globe2/><b>CONTINUAR COM {selectedLeagues.length} LIGA{selectedLeagues.length===1?"":"S"}</b><small>Definir como a carreira vai começar</small></span><ChevronRight/></button></div></section>}
  {view==="mode"&&<section className={styles.content}><Title kicker="NOVO JOGO • 3 DE 3" title="Como você quer começar?" text={`${managerName} • ${selectedLeagues.length} liga${selectedLeagues.length===1?"":"s"} ativa${selectedLeagues.length===1?"":"s"}. Agora escolha assumir um clube ou disputar uma vaga no mercado.`}/><div className={styles.modeGrid}><Choice icon={<Trophy/>} title="Assumir um clube" text="Escolha uma das ligas ativas e comece imediatamente no comando do time." onClick={()=>chooseMode("direct")}/><Choice icon={<BriefcaseBusiness/>} title="Buscar emprego" text="Escolha uma liga ativa, veja cargos disponíveis e participe da entrevista." onClick={()=>chooseMode("job-market")}/></div></section>}
  {view==="league"&&<section className={styles.content}><Title kicker={mode==="direct"?"ESCOLHA DO CLUBE":"MERCADO DE TREINADORES"} title="Escolha a competição" text={mode==="direct"?"Somente as ligas que você marcou como ativas aparecem aqui.":"As vagas serão abertas dentro do universo de ligas selecionado para este save."}/><div className={styles.leagueGrid}>{selectedDefinitions.map(item=><button key={item.id} className={styles.leagueCard} onClick={()=>chooseLeague(item.id)}><span>{leagueLabel(item.id,item.country)}</span><b>{item.name}</b><small><Users size={14}/>{item.clubs.length} clubes • {item.country} • 2026/27</small><ChevronRight/></button>)}</div></section>}
  {view==="clubs"&&<section className={styles.content}><Title kicker={`${competition.country.toUpperCase()} • ${competition.shortName.toUpperCase()}`} title="Escolha seu clube" text={`${managerName} iniciará a carreira com ${selectedLeagues.length} liga${selectedLeagues.length===1?"":"s"} em simulação ativa.`}/><div className={styles.clubGrid}>{competition.clubs.map(club=><button key={club.transfermarktId} className={styles.clubCard} onClick={()=>startCareer(club.transfermarktId,club.name)}><Crest src={club.imageUrl} name={club.name}/><div><b>{club.name}</b><small>{club.players.length} jogadores • {formatEur(club.marketValueEur)}</small></div><ChevronRight/></button>)}</div></section>}
  {view==="vacancies"&&<section className={styles.content}><Title kicker={`${competition.country.toUpperCase()} • ${competition.shortName.toUpperCase()} • VAGAS`} title="Clubes buscando treinador" text="A diretoria avaliará suas respostas, o perfil do projeto e o nível de exigência da vaga."/><div className={styles.vacancyList}>{vacancies.map(v=><article key={v.clubTransfermarktId} className={`${styles.vacancy} ${rejected.includes(v.clubTransfermarktId)?styles.rejected:""}`}><Crest src={v.imageUrl} name={v.clubName}/><div><span>{v.boardProfile.toUpperCase()} • {v.difficulty}</span><b>{v.clubName}</b><small>{formatEur(v.marketValueEur)} em valor de elenco</small></div>{rejected.includes(v.clubTransfermarktId)?<em>CANDIDATURA ENCERRADA</em>:<button onClick={()=>openInterview(v)}>FAZER ENTREVISTA</button>}</article>)}</div></section>}
  {view==="interview"&&interview&&<section className={styles.content}><Title kicker={`ENTREVISTA • ${interview.clubName}`} title={result?result.approved?"Você recebeu a proposta":"Diretoria escolheu outro perfil":`Pergunta ${question+1} de ${INTERVIEW_QUESTIONS.length}`} text={result?result.message:`Perfil da diretoria: ${interview.boardProfile} • vaga ${interview.difficulty.toLowerCase()}`}/>{!result?<div className={styles.interview}><div className={styles.progress}><i style={{width:`${((question+1)/INTERVIEW_QUESTIONS.length)*100}%`}}/></div><h2>{INTERVIEW_QUESTIONS[question].question}</h2>{INTERVIEW_QUESTIONS[question].answers.map(item=><button key={item.id} onClick={()=>answer(item.id)}>{item.label}<ChevronRight/></button>)}</div>:<div className={`${styles.interviewResult} ${result.approved?styles.approved:styles.denied}`}><strong>{result.score}</strong><span>ADERÊNCIA À DIRETORIA</span>{result.approved?<button onClick={()=>startCareer(interview.clubTransfermarktId,interview.clubName,`${managerName.trim()} • ${interview.clubName}`)}>ASSINAR E ASSUMIR O CLUBE</button>:<button onClick={()=>{setRejected([...rejected,interview.clubTransfermarktId]);setInterview(null);setResult(null);setQuestion(0);setAnswers([]);setView("vacancies")}}>VOLTAR AO MERCADO</button>}</div>}</section>}
 </section></main>;
}

function leagueLabel(id:ProfessionalCompetitionId,country:string){if(id==="BRA1")return"BRASIL • 1ª DIVISÃO";if(id==="BRA2")return"BRASIL • 2ª DIVISÃO";if(id==="BRA3")return"BRASIL • 3ª DIVISÃO";if(id==="BRA4")return"BRASIL • 4ª DIVISÃO";return country.toUpperCase()+" • LIGA";}
function Title({kicker,title,text}:{kicker:string;title:string;text:string}){return <header className={styles.title}><span>{kicker}</span><h1>{title}</h1><p>{text}</p></header>}
function Choice({icon,title,text,onClick}:{icon:React.ReactNode;title:string;text:string;onClick:()=>void}){return <button className={styles.choice} onClick={onClick}><i>{icon}</i><b>{title}</b><p>{text}</p><span>Selecionar <ChevronRight size={15}/></span></button>}
function Empty(){return <div className={styles.empty}><FolderOpen/><b>Nenhum jogo salvo</b><p>Crie uma nova carreira para começar.</p></div>}
function Crest({src,name}:{src:string;name:string}){return <span className={styles.crest}><Image src={src} alt={`Escudo ${name}`} width={44} height={44}/></span>}
function formatDate(iso:string){try{return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(`${iso}T12:00:00Z`));}catch{return iso}}
function formatEur(value:number){return value>=1_000_000?`€ ${(value/1_000_000).toLocaleString("pt-BR",{maximumFractionDigits:1})} mi`:`€ ${Math.round(value/1000).toLocaleString("pt-BR")} mil`}
function formatBytes(value:number){if(value<1024)return`${value} B`;if(value<1024*1024)return`${Math.round(value/1024)} KB`;return`${(value/1024/1024).toLocaleString("pt-BR",{maximumFractionDigits:1})} MB`}
