"use client";

import { useState } from "react";
import { ArrowRightLeft, BadgeDollarSign, BriefcaseBusiness, CircleDollarSign, FileSignature, Handshake, Search, UsersRound } from "lucide-react";
import type { SeasonState } from "@/game-engine/season";
import { clubWageSpend, concludeAcceptedOffer, formatBrl, formatEur, isTransferWindowOpen, makeOfferForPlayer, recommendedOffer, renewPlayerContract, respondToIncomingOffer, signFreeAgent, toggleTransferList, type MarketActionResult } from "@/game-engine/market";
import styles from "./market.module.css";
import InternationalMarketPanel from "./international-market-panel";

export default function MarketView({season,onResult}:{season:SeasonState;onResult:(result:MarketActionResult)=>void}){
  const [tab,setTab]=useState<"Elenco"|"Oportunidades"|"Internacional"|"Propostas"|"Histórico">("Elenco");
  const [search,setSearch]=useState("");
  const club=season.league.clubs.find(c=>c.id===season.selectedClubId)!;
  const market=season.market;
  const open=isTransferWindowOpen(season.currentRound);
  const wageSpend=clubWageSpend(club);
  const incoming=market.offers.filter(o=>o.sellerClubId===club.id&&o.status==="Pendente");
  const outgoing=market.offers.filter(o=>o.buyerClubId===club.id).slice(0,20);
  const query=search.toLowerCase();
  const opportunities=season.league.clubs.flatMap(c=>c.id===club.id?[]:c.players.map(player=>({club:c,player}))).filter(({player})=>!query||player.name.toLowerCase().includes(query)||player.position.toLowerCase().includes(query)).sort((a,b)=>(Number(b.player.transferListed)+Number(b.player.wantsToLeave))*1e10-(Number(a.player.transferListed)+Number(a.player.wantsToLeave))*1e10+recommendedOffer(b.player)-recommendedOffer(a.player)).slice(0,80);
  return <div className={styles.shell}>
    <div className={styles.metrics}>
      <Metric icon={<CircleDollarSign/>} label="ORÇAMENTO" value={formatEur(club.transferBudgetEur)} detail="para taxas de transferência"/>
      <Metric icon={<BadgeDollarSign/>} label="FOLHA" value={formatBrl(wageSpend)} detail={`teto ${formatBrl(club.wageBudgetBrlMonthly)}/mês`}/>
      <Metric icon={<ArrowRightLeft/>} label="JANELA" value={open?"ABERTA":"FECHADA"} detail={open?`rodada ${season.currentRound}`:"abre novamente na rodada 19"}/>
      <Metric icon={<Handshake/>} label="PROPOSTAS" value={String(incoming.length)} detail="aguardando sua decisão"/>
    </div>
    <div className={styles.tabs}>{(["Elenco","Oportunidades","Internacional","Propostas","Histórico"] as const).map(item=><button key={item} className={tab===item?styles.active:""} onClick={()=>setTab(item)}>{item}</button>)}</div>
    {tab==="Elenco"&&<section className={styles.panel}><header><div><span>CONTRATOS DO SEU CLUBE</span><h2>{club.players.length} jogadores • folha simulada</h2></div><small>Salários são mecânica do jogo, não dado do Transfermarkt.</small></header><div className={styles.tableWrap}><table><thead><tr><th>Jogador</th><th>Pos.</th><th>Valor TM</th><th>Salário/mês</th><th>Contrato</th><th>Agente</th><th>Mercado</th><th>Ações</th></tr></thead><tbody>{[...club.players].sort((a,b)=>recommendedOffer(b)-recommendedOffer(a)).map(player=><tr key={player.id}><td><b>{player.name}</b><small>{player.squadRole} • {player.appearances} jogos</small></td><td>{player.position}</td><td>{formatEur(player.marketValueEur??recommendedOffer(player))}</td><td>{formatBrl(player.contract.salaryBrlMonthly)}</td><td><b>{player.contract.endYear}</b><small>{player.contract.releaseClauseEur?`cláusula ${formatEur(player.contract.releaseClauseEur)}`:"sem cláusula"}</small></td><td>{player.contract.agentName}</td><td>{player.wantsToLeave?<em className={styles.danger}>Quer sair</em>:player.transferListed?<em className={styles.warn}>Listado</em>:<em>Normal</em>}</td><td><div className={styles.actions}><button onClick={()=>onResult(renewPlayerContract(season,player.id))}><FileSignature/> Renovar</button><button onClick={()=>onResult(toggleTransferList(season,player.id))}><BriefcaseBusiness/> {player.transferListed?"Retirar":"Listar"}</button></div></td></tr>)}</tbody></table></div></section>}
    {tab==="Oportunidades"&&<section className={styles.panel}><header><div><span>SCOUTING DE MERCADO</span><h2>Jogadores dos outros 19 clubes</h2></div><label className={styles.search}><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar jogador ou posição"/></label></header><div className={styles.tableWrap}><table><thead><tr><th>Jogador</th><th>Clube</th><th>Pos.</th><th>Idade</th><th>Valor TM</th><th>Referência</th><th>Contrato</th><th>Negociar</th></tr></thead><tbody>{opportunities.map(({club:owner,player})=><tr key={player.id}><td><b>{player.name}</b><small>{player.transferListed?"Na lista de transferências":player.wantsToLeave?"Deseja sair":`${player.appearances} jogos na Série A`}</small></td><td>{owner.name}</td><td>{player.position}</td><td>{player.age}</td><td>{player.marketValueEur?formatEur(player.marketValueEur):"—"}</td><td><b>{formatEur(recommendedOffer(player))}</b></td><td>até {player.contract.endYear}</td><td><div className={styles.actions}><button disabled={!open} onClick={()=>onResult(makeOfferForPlayer(season,player.id,"Compra"))}>Comprar</button><button disabled={!open} onClick={()=>onResult(makeOfferForPlayer(season,player.id,"Empréstimo"))}>Empréstimo</button></div></td></tr>)}</tbody></table></div></section>}
    {tab==="Internacional"&&<InternationalMarketPanel season={season} onResult={onResult}/>}
    {tab==="Propostas"&&<div className={styles.proposalGrid}><section className={styles.panel}><header><div><span>PROPOSTAS RECEBIDAS</span><h2>{incoming.length} pendente{incoming.length===1?"":"s"}</h2></div></header><div className={styles.cards}>{incoming.length===0?<Empty text="Nenhum clube fez proposta pelo seu elenco nesta rodada."/>:incoming.map(offer=>{const player=club.players.find(p=>p.id===offer.playerId),buyer=season.league.clubs.find(c=>c.id===offer.buyerClubId);return <article key={offer.id}><span>{offer.type}</span><h3>{buyer?.name} → {player?.name}</h3><strong>{formatEur(offer.feeEur)}</strong><p>Expira na rodada {offer.expiresRound}. {player?.wantsToLeave?"O jogador deseja sair.":"O jogador não pediu para sair."}</p><div className={styles.decision}><button onClick={()=>onResult(respondToIncomingOffer(season,offer.id,true))}>Aceitar</button><button onClick={()=>onResult(respondToIncomingOffer(season,offer.id,false))}>Recusar</button></div></article>})}</div></section><section className={styles.panel}><header><div><span>SUAS PROPOSTAS</span><h2>Negociações recentes</h2></div></header><div className={styles.cards}>{outgoing.length===0?<Empty text="Você ainda não enviou propostas."/>:outgoing.map(offer=>{const found=season.league.clubs.flatMap(c=>c.players).find(p=>p.id===offer.playerId);return <article key={offer.id}><span>{offer.status}</span><h3>{found?.name??"Jogador negociado"}</h3><strong>{formatEur(offer.feeEur)}</strong><p>{offer.message}</p>{offer.status==="Aceita"&&<button className={styles.finish} onClick={()=>onResult(concludeAcceptedOffer(season,offer.id))}>Concluir com jogador</button>}</article>})}</div></section></div>}
    {tab==="Histórico"&&<div className={styles.proposalGrid}><section className={styles.panel}><header><div><span>TRANSFERÊNCIAS CONCLUÍDAS</span><h2>Histórico do save</h2></div></header><div className={styles.history}>{market.history.length===0?<Empty text="O mercado ainda não registrou transferências."/>:market.history.map(deal=>{const from=season.league.clubs.find(c=>c.id===deal.fromClubId)?.name??"Sem clube",to=season.league.clubs.find(c=>c.id===deal.toClubId)?.name??"Sem clube";return <article key={deal.id}><UsersRound/><div><b>{deal.playerName}</b><span>{from} → {to}</span><small>{deal.type} • {formatEur(deal.feeEur)} • {deal.year} / R{deal.round}</small></div></article>})}</div></section><section className={styles.panel}><header><div><span>AGENTES LIVRES</span><h2>{market.freeAgents.length} disponíveis</h2></div></header><div className={styles.cards}>{market.freeAgents.length===0?<Empty text="Nenhum contrato expirou até agora."/>:market.freeAgents.slice(0,30).map(player=><article key={player.id}><span>{player.position} • {player.age} anos</span><h3>{player.name}</h3><strong>{formatBrl(player.contract.salaryBrlMonthly)}/mês</strong><p>Agente: {player.contract.agentName}</p><button className={styles.finish} onClick={()=>onResult(signFreeAgent(season,player.id))}>Oferecer contrato</button></article>)}</div></section></div>}
  </div>;
}

function Metric({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail:string}){return <article className={styles.metric}><i>{icon}</i><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></article>}
function Empty({text}:{text:string}){return <div className={styles.empty}><Handshake/><b>Mercado tranquilo</b><p>{text}</p></div>}
