"use client";

import { Clock3, FileCheck2, Gavel, Handshake, MessageSquareText, Newspaper, Scale, Users } from "lucide-react";
import type { SeasonState } from "@/game-engine/season";
import { formatEur, transferNegotiations, type MarketActionResult, type TransferNegotiationStage } from "@/game-engine/market";
import styles from "./market.module.css";

const STEPS:TransferNegotiationStage[]=["Análise da diretoria","Contato inicial","Negociação com clube","Termos pessoais","Documentação","Concluída"];

export default function MarketNegotiationPanel({season}:{season:SeasonState;onResult:(result:MarketActionResult)=>void}){
 const negotiations=transferNegotiations(season),active=negotiations.filter(n=>n.stage!=="Concluída"&&n.stage!=="Encerrada"),finished=negotiations.filter(n=>n.stage==="Concluída"||n.stage==="Encerrada").slice(0,12);
 return <div className={styles.proposalGrid}>
  <section className={styles.panel}><header><div><span>CENTRAL DE NEGOCIAÇÕES</span><h2>{active.length} operação{active.length===1?"":"ões"} em andamento</h2></div><small><Clock3/> O mercado agora evolui por dias, não por clique.</small></header><div className={styles.cards}>{active.length===0?<Empty/>:active.map(item=>{const seller=season.league.clubs.find(c=>c.id===item.sellerClubId),buyer=season.league.clubs.find(c=>c.id===item.buyerClubId),step=Math.max(0,STEPS.indexOf(item.stage));return <article key={item.id}><span>{item.direction==="Entrada"?"ALVO DO TREINADOR":"PROPOSTA PELO SEU ELENCO"} • {item.type}</span><h3>{item.playerName}</h3><strong>{item.agreedFeeEur?formatEur(item.agreedFeeEur):`ref. ${formatEur(item.estimatedFeeEur)}`}</strong><p>{buyer?.name??"Clube comprador"} ↔ {seller?.name??"Clube vendedor"}</p><div style={{display:"grid",gridTemplateColumns:"repeat(6,minmax(0,1fr))",gap:4,margin:"10px 0"}}>{STEPS.map((label,index)=><div key={label} title={label} style={{height:5,borderRadius:999,background:index<=step?"#36c275":"#29332f"}}/>)}</div><small>Etapa: <b>{item.stage}</b>{item.stage!=="Concluída"&&item.stage!=="Encerrada"?` • próxima atualização ${dateLabel(item.nextActionDate)}`:""}</small>{item.rivalClubIds.length>0&&<p><Users size={13}/> {item.rivalClubIds.map(id=>season.league.clubs.find(c=>c.id===id)?.name).filter(Boolean).join(", ")} também disputa(m) o jogador.</p>}{item.leaked&&<p><Newspaper size={13}/> A negociação vazou e perdeu confidencialidade.</p>}<div style={{borderTop:"1px solid #29332f",marginTop:10,paddingTop:8}}>{item.timeline.slice(0,5).map(event=><div key={`${event.date}-${event.label}`} style={{display:"grid",gridTemplateColumns:"62px 1fr",gap:8,padding:"5px 0"}}><small>{dateLabel(event.date)}</small><div><b style={{fontSize:9}}>{event.label}</b><p style={{margin:"2px 0 0",fontSize:8}}>{event.detail}</p></div></div>)}</div></article>})}</div></section>
  <section className={styles.panel}><header><div><span>COMO FUNCIONA</span><h2>Você pede. A diretoria executa.</h2></div><Gavel/></header><div className={styles.cards}><Guide icon={<Scale/>} title="1. Análise da diretoria" text="Orçamento, salário, necessidade do setor, potencial e confiança institucional definem se o clube autoriza a abordagem."/><Guide icon={<MessageSquareText/>} title="2. Contato e concorrência" text="O diretor procura clube e empresário. Vazamentos podem atrair rivais e elevar a pedida."/><Guide icon={<Handshake/>} title="3. Acordos separados" text="Primeiro os clubes chegam a um princípio de acordo; depois o empresário negocia os termos pessoais com o jogador."/><Guide icon={<FileCheck2/>} title="4. Documentação" text="Mesmo com tudo acertado, exames, minutas e registro levam dias e podem sofrer atraso antes do anúncio oficial."/></div></section>
  {finished.length>0&&<section className={styles.panel}><header><div><span>PROCESSOS RECENTES</span><h2>Concluídos e encerrados</h2></div></header><div className={styles.cards}>{finished.map(item=><article key={item.id}><span>{item.stage} • {item.type}</span><h3>{item.playerName}</h3><p>{item.timeline[0]?.detail}</p><small>{item.timeline[0]?.date?dateLabel(item.timeline[0].date):"—"}</small></article>)}</div></section>}
 </div>;
}

function Guide({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <article><span>{icon} FLUXO DA DIRETORIA</span><h3>{title}</h3><p>{text}</p></article>}
function Empty(){return <div className={styles.empty}><Clock3/><b>Nenhuma negociação ativa</b><p>Na aba Oportunidades, manifeste interesse em compra ou empréstimo. A partir daí o processo passa a avançar com o calendário.</p></div>}
function dateLabel(iso:string){const[y,m,d]=iso.split("-");return`${d}/${m}/${y}`}
