"use client";

import { useState } from "react";
import { ArrowRightLeft, BadgeDollarSign, BriefcaseBusiness, CircleDollarSign, Clock3, FileSignature, Handshake, Search, UsersRound } from "lucide-react";
import type { SeasonState } from "@/game-engine/season";
import { clubWageSpend, formatBrl, formatEur, isTransferWindowOpen, recommendedOffer, requestTransferInterest, transferNegotiations, type MarketActionResult } from "@/game-engine/market";
import styles from "./market.module.css";
import InternationalMarketPanel from "./international-market-panel";
import MarketNegotiationPanel from "./market-negotiation-panel";
import { requestBoardContractRenewal, requestBoardFreeAgentSigning, requestBoardTransferListing } from "@/game-engine/club-management";

export default function MarketView({season,onResult}:{season:SeasonState;onResult:(result:MarketActionResult)=>void}){
  const [tab,setTab]=useState<"Elenco"|"Oportunidades"|"Negociações"|"Internacional"|"Propostas"|"Histórico">("Elenco");
  const [search,setSearch]=useState("");
  const [selectedPlayerId,setSelectedPlayerId]=useState<string|null>(null);
  const club=season.league.clubs.find(c=>c.id===season.selectedClubId)!;
  const market=season.market;
  const open=isTransferWindowOpen(season.currentRound);
  const wageSpend=clubWageSpend(club);
  const negotiations=transferNegotiations(season);
  const incoming=market.offers.filter(o=>o.sellerClubId===club.id).slice(0,30);
  const activeIncoming=negotiations.filter(n=>n.direction==="Saída"&&n.stage!=="Concluída"&&n.stage!=="Encerrada");
  const query=search.toLowerCase();
  const opportunities=season.league.clubs.flatMap(c=>c.id===club.id?[]:c.players.map(player=>({club:c,player}))).filter(({player})=>!query||player.name.toLowerCase().includes(query)||player.position.toLowerCase().includes(query)).sort((a,b)=>(Number(b.player.transferListed)+Number(b.player.wantsToLeave))*1e10-(Number(a.player.transferListed)+Number(a.player.wantsToLeave))*1e10+recommendedOffer(b.player)-recommendedOffer(a.player)).slice(0,100);
  const selected=selectedPlayerId?season.league.clubs.flatMap(c=>c.players.map(player=>({club:c,player}))).find(item=>item.player.id===selectedPlayerId):undefined;
  const tabs=["Elenco","Oportunidades","Negociações","Internacional","Propostas","Histórico"] as const;
  return <div className={styles.shell}>
    <div className={styles.metrics}>
      <Metric icon={<CircleDollarSign/>} label="ORÇAMENTO" value={formatEur(club.transferBudgetEur)} detail="a diretoria controla a execução"/>
      <Metric icon={<BadgeDollarSign/>} label="FOLHA" value={formatBrl(wageSpend)} detail={`teto ${formatBrl(club.wageBudgetBrlMonthly)}/mês`}/>
      <Metric icon={<ArrowRightLeft/>} label="JANELA" value={open?"ABERTA":"FECHADA"} detail={open?`rodada ${season.currentRound}`:"interesse pode ser registrado mesmo assim"}/>
      <Metric icon={<Clock3/>} label="EM ANDAMENTO" value={String(negotiations.filter(n=>n.stage!=="Concluída"&&n.stage!=="Encerrada").length)} detail="processos com prazo em dias"/>
    </div>
    <div className={styles.tabs}>{tabs.map(item=><button key={item} className={tab===item?styles.active:""} onClick={()=>setTab(item)}>{item}</button>)}</div>
    {tab==="Elenco"&&<section className={styles.panel}><header><div><span>CONTRATOS DO SEU CLUBE</span><h2>{club.players.length} jogadores • folha simulada</h2></div><small>Você define prioridades esportivas. Diretoria, clube comprador e jogador conduzem as decisões de mercado.</small></header><div className={styles.tableWrap}><table><thead><tr><th>Jogador</th><th>Pos.</th><th>Valor TM</th><th>Salário/mês</th><th>Contrato</th><th>Agente</th><th>Mercado</th><th>Ações</th></tr></thead><tbody>{[...club.players].sort((a,b)=>recommendedOffer(b)-recommendedOffer(a)).map(player=><tr key={player.id}><td><b>{player.name}</b><small>{player.squadRole} • {player.appearances} jogos</small></td><td>{player.position}</td><td>{formatEur(player.marketValueEur??recommendedOffer(player))}</td><td>{formatBrl(player.contract.salaryBrlMonthly)}</td><td><b>{player.contract.endYear}</b><small>{player.contract.releaseClauseEur?`cláusula ${formatEur(player.contract.releaseClauseEur)}`:"sem cláusula"}</small></td><td>{player.contract.agentName}</td><td>{player.wantsToLeave?<em className={styles.danger}>Quer sair</em>:player.transferListed?<em className={styles.warn}>Listado</em>:<em>Normal</em>}</td><td><div className={styles.actions}><button onClick={()=>onResult(requestBoardContractRenewal(season,player.id))}><FileSignature/> Pedir renovação</button><button onClick={()=>onResult(requestBoardTransferListing(season,player.id))}><BriefcaseBusiness/> {player.transferListed?"Pedir retirada":"Sugerir saída"}</button></div></td></tr>)}</tbody></table></div></section>}
    {tab==="Oportunidades"&&<section className={styles.panel}><header><div><span>SCOUTING DE MERCADO</span><h2>Manifeste interesse — a diretoria decide se aborda</h2></div><label className={styles.search}><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar jogador ou posição"/></label></header><div className={styles.tableWrap}><table><thead><tr><th>Jogador</th><th>Clube</th><th>Pos.</th><th>Idade</th><th>Valor TM</th><th>Referência</th><th>Contrato</th><th>Seu pedido</th></tr></thead><tbody>{opportunities.map(({club:owner,player})=>{const active=negotiations.find(n=>n.direction==="Entrada"&&n.playerId===player.id&&n.stage!=="Concluída"&&n.stage!=="Encerrada");return <tr key={player.id}><td><button className={styles.playerLink} onClick={()=>setSelectedPlayerId(player.id)}>{player.name}</button><small>{active?`Processo: ${active.stage}`:player.transferListed?"Na lista de transferências":player.wantsToLeave?"Deseja sair":`${player.appearances} jogos`}</small></td><td>{owner.name}</td><td>{player.position}</td><td>{player.age}</td><td>{player.marketValueEur?formatEur(player.marketValueEur):"—"}</td><td><b>{formatEur(recommendedOffer(player))}</b></td><td>até {player.contract.endYear}</td><td><div className={styles.actions}>{active?<em className={styles.warn}>{active.stage}</em>:<><button onClick={()=>onResult(requestTransferInterest(season,player.id,"Compra"))}>Interesse em compra</button><button onClick={()=>onResult(requestTransferInterest(season,player.id,"Empréstimo"))}>Interesse em empréstimo</button></>}</div></td></tr>})}</tbody></table></div></section>}
    {tab==="Negociações"&&<MarketNegotiationPanel season={season} onResult={onResult}/>}
    {tab==="Internacional"&&<InternationalMarketPanel season={season} onResult={onResult}/>}
    {tab==="Propostas"&&<div className={styles.proposalGrid}><section className={styles.panel}><header><div><span>PROPOSTAS PELO SEU ELENCO</span><h2>{activeIncoming.length} processo{activeIncoming.length===1?"":"s"} em andamento</h2></div><small>A decisão é da diretoria e do jogador. Você recebe atualizações pela Caixa de entrada e Notícias.</small></header><div className={styles.cards}>{incoming.length===0?<Empty text="Nenhum clube fez proposta pelo seu elenco recentemente."/>:incoming.map(offer=>{const player=club.players.find(p=>p.id===offer.playerId),buyer=season.league.clubs.find(c=>c.id===offer.buyerClubId),process=negotiations.find(n=>n.offerId===offer.id);return <article key={offer.id}><span>{offer.type} • {process?.stage??offer.status}</span><h3>{buyer?.name} → {player?.name??process?.playerName??"Jogador"}</h3><strong>{formatEur(offer.feeEur)}</strong><p>{offer.message}</p><small>{process?`Próxima atualização: ${process.stage==="Concluída"||process.stage==="Encerrada"?"processo encerrado":formatDate(process.nextActionDate)}`:"Aguardando registro no fluxo da diretoria."}</small></article>})}</div></section><section className={styles.panel}><header><div><span>INTERESSES SOLICITADOS</span><h2>A diretoria conduz o contato</h2></div></header><div className={styles.cards}>{negotiations.filter(n=>n.direction==="Entrada").length===0?<Empty text="Você ainda não manifestou interesse em jogadores."/>:negotiations.filter(n=>n.direction==="Entrada").slice(0,30).map(item=><article key={item.id}><span>{item.type} • {item.stage}</span><h3>{item.playerName}</h3><strong>{item.agreedFeeEur?formatEur(item.agreedFeeEur):`ref. ${formatEur(item.estimatedFeeEur)}`}</strong><p>{item.timeline[0]?.detail??"Processo em análise."}</p><small>{item.rivalClubIds.length?`${item.rivalClubIds.length} concorrente(s) identificado(s)`:item.leaked?"Informação vazou para a imprensa":"Sem concorrência confirmada"}</small></article>)}</div></section></div>}
    {tab==="Histórico"&&<div className={styles.proposalGrid}><section className={styles.panel}><header><div><span>TRANSFERÊNCIAS CONCLUÍDAS</span><h2>Histórico do save</h2></div></header><div className={styles.history}>{market.history.length===0?<Empty text="O mercado ainda não registrou transferências."/>:market.history.map(deal=>{const from=season.league.clubs.find(c=>c.id===deal.fromClubId)?.name??"Sem clube",to=season.league.clubs.find(c=>c.id===deal.toClubId)?.name??"Sem clube";return <article key={deal.id}><UsersRound/><div><b>{deal.playerName}</b><span>{from} → {to}</span><small>{deal.type} • {formatEur(deal.feeEur)} • {deal.year} / R{deal.round}</small></div></article>})}</div></section><section className={styles.panel}><header><div><span>AGENTES LIVRES</span><h2>{market.freeAgents.length} disponíveis</h2></div></header><div className={styles.cards}>{market.freeAgents.length===0?<Empty text="Nenhum contrato expirou até agora."/>:market.freeAgents.slice(0,30).map(player=><article key={player.id}><span>{player.position} • {player.age} anos</span><h3>{player.name}</h3><strong>{formatBrl(player.contract.salaryBrlMonthly)}/mês</strong><p>Agente: {player.contract.agentName}</p><button className={styles.finish} onClick={()=>onResult(requestBoardFreeAgentSigning(season,player.id))}>Manifestar interesse</button></article>)}</div></section></div>}
    {selected&&selected.club.id!==club.id&&<div className={styles.drawerBackdrop} onClick={()=>setSelectedPlayerId(null)}><aside className={styles.drawer} onClick={e=>e.stopPropagation()}><button className={styles.close} onClick={()=>setSelectedPlayerId(null)}>×</button><span>PERFIL DE MERCADO</span><h2>{selected.player.name}</h2><p>{selected.club.name} • {selected.player.position} • {selected.player.age} anos • {selected.player.nationality??"—"}</p><div className={styles.playerMetrics}><div><small>OVR</small><b>{selected.player.overall}</b></div><div><small>VALOR</small><b>{selected.player.marketValueEur?formatEur(selected.player.marketValueEur):"—"}</b></div><div><small>REFERÊNCIA</small><b>{formatEur(recommendedOffer(selected.player))}</b></div><div><small>CONTRATO</small><b>{selected.player.contract.endYear}</b></div></div><section><b>Seu papel como treinador</b><p>Você indica que deseja o jogador e se prefere compra ou empréstimo. A diretoria avalia orçamento e encaixe, procura o clube, negocia com o empresário e cuida da documentação.</p></section><div className={styles.drawerActions}><button onClick={()=>onResult(requestTransferInterest(season,selected.player.id,"Compra"))}>INTERESSE EM COMPRA</button><button onClick={()=>onResult(requestTransferInterest(season,selected.player.id,"Empréstimo"))}>INTERESSE EM EMPRÉSTIMO</button></div></aside></div>}
  </div>;
}

function Metric({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail:string}){return <article className={styles.metric}><i>{icon}</i><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></article>}
function Empty({text}:{text:string}){return <div className={styles.empty}><Handshake/><b>Mercado tranquilo</b><p>{text}</p></div>}
function formatDate(iso:string){const[y,m,d]=iso.split("-");return`${d}/${m}/${y}`}
