"use client";
import{useEffect,useMemo,useRef,useState}from"react";
import type{LeagueClub,LeaguePlayer}from"@/game-engine/league";
import type{LiveMatchState,MatchSide}from"@/game-engine/live-match";
import type{MatchEvent}from"@/game-engine/match";
import{layoutLineup}from"@/game-engine/tactics-layout";
import styles from"./match-2d-pitch.module.css";

type Point={x:number;y:number};type Marker={player:LeaguePlayer;side:MatchSide;base:Point;x:number;y:number;role:"actor"|"assist"|"support"|"normal"};
const clamp=(v:number,min=3,max=97)=>Math.max(min,Math.min(max,v)),mix=(a:number,b:number,t:number)=>a+(b-a)*t,ease=(t:number)=>t<.5?2*t*t:1-Math.pow(-2*t+2,2)/2,zoneX=(z?:"left"|"center"|"right")=>z==="left"?24:z==="right"?76:50;
const hash=(s:string)=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0};
function label(type:MatchEvent["type"]){return type==="goal"?"FINALIZAÇÃO • GOL":type==="chance"?"FINALIZAÇÃO":type==="corner"?"BOLA PARADA • ESCANTEIO":type==="free_kick"?"BOLA PARADA • FALTA":type==="penalty"?"BOLA PARADA • PÊNALTI":type==="card"?"JOGO PARADO • CARTÃO":type==="red_card"?"JOGO PARADO • EXPULSÃO":type==="injury"?"JOGO PARADO • ATENDIMENTO":type==="tactical"?"REORGANIZAÇÃO TÁTICA":type==="halftime"?"INTERVALO":type==="fulltime"?"FIM DE JOGO":"POSSE E CONSTRUÇÃO"}
function attackY(side:MatchSide,kind:"build"|"mid"|"create"|"shot"|"goal"){const home={build:78,mid:57,create:30,shot:13,goal:2},away={build:22,mid:43,create:70,shot:87,goal:98};return(side==="home"?home:away)[kind]}
function pointAlong(points:Point[],t:number){const p=clamp(t,0,1)*(points.length-1),i=Math.min(points.length-2,Math.floor(p)),u=ease(p-i);return{x:mix(points[i].x,points[i+1].x,u),y:mix(points[i].y,points[i+1].y,u)}}
export default function Match2DPitch({session,home,away}:{session:LiveMatchState;home:LeagueClub;away:LeagueClub}){const[now,setNow]=useState(0),[sceneStart,setSceneStart]=useState(0),raf=useRef<number|undefined>(undefined),lastPaint=useRef(0),event=session.events[session.events.length-1],eventKey=`${event?.minute}:${event?.type}:${event?.team}:${event?.playerId??""}:${event?.assistPlayerId??""}:${session.homeGoals}-${session.awayGoals}`;useEffect(()=>{let first=true;const loop=(ts:number)=>{if(first){first=false;setSceneStart(ts)}if(ts-lastPaint.current>45){lastPaint.current=ts;setNow(ts)}raf.current=requestAnimationFrame(loop)};raf.current=requestAnimationFrame(loop);return()=>{if(raf.current)cancelAnimationFrame(raf.current)}},[eventKey,session.phase]);const byId=useMemo(()=>new Map([...home.players,...away.players].map(p=>[p.id,p])),[home,away]),elapsed=Math.max(0,(now-sceneStart)/1000),fresh=Boolean(event&&session.currentMinute-event.minute<=1&&!["kickoff","halftime","fulltime","tactical"].includes(event.type)),attacking:MatchSide=event?.team==="home"||event?.team==="away"?event.team:session.possessionHome>=50?"home":"away",duration=event?.type==="goal"?2.65:event?.type==="corner"||event?.type==="free_kick"||event?.type==="penalty"?2.35:2.1,playT=fresh?Math.min(1,elapsed/duration):((elapsed*.18)%1),focusX=zoneX(event?.zone),goal={x:50,y:attackY(attacking,"goal")};
 const layouts=(side:MatchSide,ids:string[],formation:string)=>layoutLineup(ids.map(id=>byId.get(id)).filter((p):p is LeaguePlayer=>Boolean(p)),formation as never).map(({player,slot})=>({player,side,base:{x:side==="home"?slot.x:100-slot.x,y:side==="home"?8+slot.y*.78:92-slot.y*.78}}));const raw=[...layouts("home",session.homeLineupIds,session.homeTactic.formation),...layouts("away",session.awayLineupIds,session.awayTactic.formation)],attackers=raw.filter(v=>v.side===attacking),defenders=raw.filter(v=>v.side!==attacking),actor=event?.playerId?raw.find(v=>v.player.id===event.playerId):undefined,assistant=event?.assistPlayerId?raw.find(v=>v.player.id===event.assistPlayerId):undefined,candidates=attackers.filter(v=>v.player.id!==actor?.player.id&&v.player.id!==assistant?.player.id).sort((a,b)=>{const ap=["VOL","MC","MEI","LD","LE","ZAG"].includes(a.player.position)?0:1,bp=["VOL","MC","MEI","LD","LE","ZAG"].includes(b.player.position)?0:1;return ap-bp||b.player.overall-a.player.overall}),initiator=candidates[hash(eventKey)%Math.max(1,candidates.length)],connector=candidates[(hash(eventKey+":c")%Math.max(1,candidates.length))];
 let ball:Point,phase="POSSE";if(fresh&&event){if(event.type==="corner"){phase=playT<.4?"COBRANÇA":"ATAQUE À ÁREA";const corner={x:event.zone==="left"?3:event.zone==="right"?97:focusX,y:attackY(attacking,"goal")},box={x:mix(focusX,50,.62),y:attackY(attacking,"shot")};ball=pointAlong([corner,box,goal],playT)}else if(event.type==="penalty"){phase="PÊNALTI";ball=pointAlong([{x:50,y:attackY(attacking,"shot")},goal],Math.max(0,(playT-.32)/.68))}else if(event.type==="free_kick"){phase=playT<.45?"PREPARAÇÃO":"COBRANÇA";ball=pointAlong([{x:focusX,y:attackY(attacking,"create")},{x:focusX,y:attackY(attacking,"shot")},goal],playT)}else if(event.type==="chance"||event.type==="goal"){phase=playT<.24?"CONSTRUÇÃO":playT<.52?"PROGRESSÃO":playT<.74?"CRIAÇÃO":"FINALIZAÇÃO";const build={x:initiator?.base.x??50,y:attackY(attacking,"build")},mid={x:connector?.base.x??focusX,y:attackY(attacking,"mid")},create={x:assistant?focusX:mix(focusX,50,.25),y:attackY(attacking,"create")},shot={x:focusX,y:attackY(attacking,"shot")};ball=pointAlong([build,mid,create,shot,goal],playT)}else{phase="JOGO PARADO";ball=actor?.base??{x:50,y:50}}}else{phase="POSSE E CIRCULAÇÃO";const lane=attacking==="home"?1:-1,osc=(Math.sin(elapsed*1.4)+1)/2;ball={x:mix(38,62,osc),y:50+lane*6*Math.sin(elapsed*.72)}}
 const nearest=new Set(defenders.map(v=>({id:v.player.id,d:Math.hypot(v.base.x-ball.x,v.base.y-ball.y)})).sort((a,b)=>a.d-b.d).slice(0,2).map(v=>v.id));const markers:Marker[]=raw.map(v=>{let{x,y}=v.base,role:Marker["role"]="normal";if(fresh&&event&&["card","red_card","injury"].includes(event.type)){if(v.player.id===actor?.player.id){x=mix(x,ball.x,.7);y=mix(y,ball.y,.7);role="actor"}}else if(v.side===attacking){const dir=attacking==="home"?-1:1;y=clamp(y+dir*(fresh?7:2.4));x=clamp(mix(x,ball.x,fresh?.09:.025));if(v.player.id===actor?.player.id){role="actor";x=mix(v.base.x,focusX,ease(Math.min(1,playT*1.35)));y=mix(v.base.y,attackY(attacking,"shot"),ease(Math.min(1,playT*1.3)))}else if(v.player.id===assistant?.player.id){role="assist";x=mix(v.base.x,focusX,ease(Math.min(1,playT*1.25)));y=mix(v.base.y,attackY(attacking,"create"),ease(Math.min(1,playT*1.15)))}else if(v.player.id===initiator?.player.id||v.player.id===connector?.player.id){role="support";x=mix(x,ball.x,.12);y=mix(y,ball.y,.1)}else if(fresh&&playT>.45){role="support";y+=dir*3.5}}else{const compact=fresh?.16:.055,press=nearest.has(v.player.id)?(fresh?.42:.12):compact;x=mix(x,ball.x,press);y=mix(y,ball.y,press*.55)}return{player:v.player,side:v.side,base:v.base,x:clamp(x),y:clamp(y),role}});
 const eventDone=fresh&&playT>=.96,actorName=actor?.player.name,assistName=assistant?.player.name;return <section className={styles.wrap}><header><div><span>MOTOR 2D • TÁTICO</span><b>{session.currentMinute}′ • {fresh&&event?label(event.type):"JOGO CORRIDO"}</b></div><div className={styles.phase}><i/>{phase}</div></header><div className={`${styles.pitch} ${event?.type==="goal"&&eventDone?styles.goalScene:""}`}><i className={styles.half}/><i className={styles.circle}/><i className={`${styles.box} ${styles.topBox}`}/><i className={`${styles.box} ${styles.bottomBox}`}/><i className={`${styles.goal} ${styles.topGoal}`}/><i className={`${styles.goal} ${styles.bottomGoal}`}/>{markers.map(v=><div key={v.player.id} className={`${styles.player} ${v.side==="home"?styles.home:styles.away} ${v.role==="actor"?styles.onBall:v.role==="assist"?styles.assistant:v.role==="support"?styles.support:""}`} style={{transform:`translate3d(${v.x}cqw,${v.y}cqh,0) translate(-50%,-50%)`}}><b>{v.player.position}</b><span>{v.player.name.split(" ")[0]}</span></div>)}<div className={styles.ball} style={{transform:`translate3d(${ball.x}cqw,${ball.y}cqh,0) translate(-50%,-50%)`}}/><div className={styles.focusRing} style={{transform:`translate3d(${ball.x}cqw,${ball.y}cqh,0) translate(-50%,-50%)`}}/>{fresh&&event&&<div className={styles.commentary}><b>{event.minute}′</b><span>{event.text}</span></div>}{event?.type==="goal"&&eventDone&&<div className={styles.eventBadge}>⚽ {actorName??"GOL"}{assistName?` • assistência ${assistName}`:""}</div>}{fresh&&event&&["card","red_card","injury"].includes(event.type)&&<div className={styles.eventBadge}>{event.type==="card"?"🟨":event.type==="red_card"?"🟥":"🩺"} {actorName??event.text}</div>}</div></section>}
