"use client";

import { ChevronRight, LoaderCircle, Newspaper, Radio, Trophy } from "lucide-react";
import type { LeagueClub, LeagueFixture, LeagueStanding } from "@/game-engine/league";
import type { MatchResult } from "@/game-engine/match";
import { aggregateScoreForMatch, type WorldCompetitionMatch, type WorldTournamentState } from "@/game-engine/world-competitions";
import { aggregateLabel, competitionTable, focusGroupForTournament, postMatchCompetitionResults, tieMatches } from "./competition-view-model";
import styles from "./matchday-flow.module.css";

type NewsItem={id:string;source:string;headline:string;summary?:string;round:number};
export type CupPostMatchContext={tournament:WorldTournamentState;match:WorldCompetitionMatch};

export function AdvanceDaysOverlay({date,reason,news}:{date:string;reason:string;news:NewsItem[]}){
 return <div className={styles.advanceOverlay} role="status" aria-live="polite"><section className={styles.advancePanel}><header><LoaderCircle/><div><span>V90 • MUNDO EM MOVIMENTO</span><b>{date}</b></div></header><p>{reason||"Calendário, treinos, mercado e notícias sendo processados."} O avanço para automaticamente quando sua presença for necessária.</p><div className={styles.advanceTrack}><i/></div><div className={styles.advanceNews}><strong>ENQUANTO VOCÊ AVANÇA</strong>{news.slice(0,3).map(item=><article key={item.id}><span>{item.source}</span><b>{item.headline}</b></article>)}{!news.length&&<small>As redações estão preparando as próximas manchetes...</small>}</div></section></div>
}

export function OverviewNewsStrip({news,onOpen}:{news:NewsItem[];onOpen:()=>void}){
 return <section className={styles.overviewNews}><header><div><Newspaper/><span>HOJE NO FUTEBOL</span></div><button onClick={onOpen}>Ver tudo <ChevronRight/></button></header><div>{news.slice(0,4).map((item,index)=><article className={index===0?styles.leadNews:""} key={item.id}><small>{item.source} • R{item.round}</small><b>{item.headline}</b>{index===0&&item.summary?<p>{item.summary}</p>:null}</article>)}{!news.length&&<article className={styles.leadNews}><small>VESTIÁRIO 90</small><b>O mundo do futebol está aguardando os próximos acontecimentos.</b></article>}</div></section>
}

export function PostMatchRoundView({home,away,result,roundFixtures,clubs,standings,selectedClubId,news,cupContext,onContinue}:{home:LeagueClub;away:LeagueClub;result:MatchResult;roundFixtures:LeagueFixture[];clubs:LeagueClub[];standings:LeagueStanding[];selectedClubId:string;news:NewsItem[];cupContext?:CupPostMatchContext;onContinue:()=>void}){
 const ordered=[...roundFixtures].sort((a,b)=>Number(b.homeClubId===selectedClubId||b.awayClubId===selectedClubId)-Number(a.homeClubId===selectedClubId||a.awayClubId===selectedClubId)),cupResults=cupContext?postMatchCompetitionResults(cupContext.tournament,cupContext.match):[],aggregate=cupContext?aggregateScoreForMatch(cupContext.tournament,cupContext.match):undefined,aggregateText=cupContext?aggregateLabel(cupContext.tournament,cupContext.match):undefined,tableRows=cupContext?.match.tableStage?competitionTable(cupContext.tournament,cupContext.match.stage,selectedClubId):[],group=cupContext?.match.tableStage?focusGroupForTournament(cupContext.tournament,cupContext.match.stage,selectedClubId):undefined,tie=cupContext&&!cupContext.match.tableStage?tieMatches(cupContext.tournament,cupContext.match):[],userParticipant=cupContext?.tournament.participants.find(participant=>participant.activeClubId===selectedClubId),knockoutWinner=aggregate?.winnerId??cupContext?.match.winnerId,knockoutResolved=Boolean(knockoutWinner&&(aggregate?aggregate.legsPlayed===aggregate.legsTotal:cupContext?.match.played)),knockoutStatus=knockoutResolved?(knockoutWinner===userParticipant?.id?"CLASSIFICADO":"ELIMINADO"):"CONFRONTO EM ABERTO";
 const competitionLabel=cupContext?`${cupContext.tournament.definition.shortName} • ${cupContext.match.stage}`:"CAMPEONATO DE LIGA";
 return <div className={styles.postMatch}>
  <section className={styles.postHero}><span>V90 MATCHDAY • {competitionLabel.toUpperCase()}</span><div><b>{home.name}</b><strong>{result.homeGoals}<i>×</i>{result.awayGoals}</strong><b>{away.name}</b></div><small>Posse {result.possessionHome}%–{100-result.possessionHome}% • Finalizações {result.shotsHome}–{result.shotsAway}{aggregateText?` • ${aggregateText}`:cupContext?` • ${cupContext.match.stage}`:" • A rodada já foi consolidada"}</small><button onClick={onContinue}>SEGUIR A CARREIRA <ChevronRight/></button></section>
  <div className={styles.postGrid}>
   <section className={styles.postPanel}><header><Radio/><div><span>{cupContext?"CENTRAL DA COMPETIÇÃO":"CENTRAL DA RODADA"}</span><b>{cupContext?`${cupContext.tournament.definition.shortName} • ${cupContext.match.stage}`:"Resultados finais"}</b></div></header><div className={styles.roundResults}>{cupContext?cupResults.map(match=><article key={match.id} className={match.home.activeClubId===selectedClubId||match.away.activeClubId===selectedClubId?styles.userResult:""}><span>{match.home.shortName||match.home.name}</span><strong>{match.homeGoals??0}–{match.awayGoals??0}</strong><span>{match.away.shortName||match.away.name}</span>{aggregateLabel(cupContext.tournament,match)&&<em>{aggregateLabel(cupContext.tournament,match)}</em>}</article>):ordered.length?ordered.map(fixture=>{const h=clubs.find(c=>c.id===fixture.homeClubId),a=clubs.find(c=>c.id===fixture.awayClubId);return <article key={fixture.id} className={fixture.homeClubId===selectedClubId||fixture.awayClubId===selectedClubId?styles.userResult:""}><span>{h?.shortName??h?.name}</span><strong>{fixture.homeGoals??0}–{fixture.awayGoals??0}</strong><span>{a?.shortName??a?.name}</span></article>}):<small>Nenhum outro resultado consolidado nesta rodada.</small>}</div></section>
   <section className={styles.postPanel}><header><Trophy/><div><span>IMPACTO IMEDIATO</span><b>{cupContext?.match.tableStage?`Classificação${group?` • Grupo ${group}`:""}`:cupContext?"Situação do confronto":"Classificação"}</b></div></header>{cupContext?.match.tableStage?<div className={styles.postTable}>{tableRows.map((row,index)=><article key={row.participant.id} className={row.participant.activeClubId===selectedClubId?styles.userStanding:""}><i>{index+1}</i><span>{row.participant.shortName||row.participant.name}</span><small>{row.played}J • SG {row.goalDifference}</small><strong>{row.points} pts</strong></article>)}</div>:cupContext?<div className={styles.tieSummary}><strong>{knockoutStatus}</strong>{tie.map(match=><article key={match.id}><span>{match.leg?`${match.leg}º jogo`:"Jogo único"}</span><b>{match.home.shortName||match.home.name} {match.played?`${match.homeGoals??0}–${match.awayGoals??0}`:"×"} {match.away.shortName||match.away.name}</b></article>)}{aggregate&&aggregate.legsPlayed>0&&<div className={styles.aggregateScore}><small>{aggregate.legsPlayed<aggregate.legsTotal?"AGREGADO PARCIAL":"PLACAR AGREGADO"}</small><b>{aggregate.homeGoals}–{aggregate.awayGoals}</b>{aggregate.decidedByPenalties&&<em>decidido nos pênaltis</em>}</div>}</div>:<div className={styles.postTable}>{standings.map((standing,index)=>{const club=clubs.find(c=>c.id===standing.clubId);return <article key={standing.clubId} className={standing.clubId===selectedClubId?styles.userStanding:""}><i>{index+1}</i><span>{club?.shortName??club?.name}</span><small>{standing.played}J</small><strong>{standing.points} pts</strong></article>})}</div>}</section>
   <section className={`${styles.postPanel} ${styles.postNews}`}><header><Newspaper/><div><span>O QUE ESTÃO DIZENDO</span><b>Repercussão</b></div></header>{news.slice(0,5).map(item=><article key={item.id}><small>{item.source}</small><b>{item.headline}</b>{item.summary?<p>{item.summary}</p>:null}</article>)}{!news.length&&<small>As primeiras repercussões ainda estão chegando.</small>}</section>
  </div>
  <section className={styles.postEvents}><header><span>LINHA DO TEMPO • EVENTOS IMPORTANTES</span></header>{result.events.filter(event=>["goal","card","red_card","injury"].includes(event.type)).map((event,index)=><article key={`${event.minute}-${index}`}><time>{event.minute}′</time><i>{event.type==="goal"?"⚽":event.type==="card"?"🟨":event.type==="red_card"?"🟥":"🩺"}</i><p>{event.text}</p></article>)}</section>
 </div>;
}
