"use client";
import{useEffect,useMemo,useState}from"react";
import type{LeagueClub,LeaguePlayer}from"@/game-engine/league";
import type{LiveMatchState}from"@/game-engine/live-match";
import{layoutLineup}from"@/game-engine/tactics-layout";
import styles from"./match-2d-pitch.module.css";

const hash=(s:string)=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0};
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
export default function Match2DPitch({session,home,away}:{session:LiveMatchState;home:LeagueClub;away:LeagueClub}){const[tick,setTick]=useState(0);useEffect(()=>{if(session.phase==="pre_match"||session.phase==="fulltime")return;const id=window.setInterval(()=>setTick(v=>v+1),260);return()=>window.clearInterval(id)},[session.phase]);const all=useMemo(()=>new Map([...home.players,...away.players].map(p=>[p.id,p])),[home,away]),latest=[...session.events].reverse().find(e=>e.minute<=session.currentMinute&&["chance","goal","corner","free_kick","penalty"].includes(e.type)),attacking=latest?.team==="away"?"away":latest?.team==="home"?"home":session.possessionHome>=50?"home":"away",zone=latest?.zone??"center",ballX=zone==="left"?27:zone==="right"?73:50,ballY=attacking==="home"?24:76;
 const team=(side:"home"|"away",ids:string[],formation:string)=>{const players=ids.map(id=>all.get(id)).filter((p):p is LeaguePlayer=>Boolean(p)),layout=layoutLineup(players,formation as never);return layout.map((assignment)=>{const p=assignment.player,slot=assignment.slot,seed=hash(`${p.id}:${session.currentMinute}:${tick}`),jx=((seed%9)-4)*.55,jy=(((seed>>4)%9)-4)*.5,hasBall=latest?.playerId===p.id,attackShift=(attacking===side?-6:4)*(side==="home"?1:-1),press=side==="home"?session.homeTactic.pressing:session.awayTactic.pressing,pressShift=(attacking!==side?(press-50)/10:0)*(side==="home"?-1:1),x=clamp(slot.x+jx+(zone==="left"?-2:zone==="right"?2:0),7,93),baseY=side==="home"?92-slot.y*.78:8+slot.y*.78,y=clamp(baseY+jy+attackShift+pressShift,5,95);return{p,x,y,hasBall};});};
 const hp=team("home",session.homeLineupIds,session.homeTactic.formation),ap=team("away",session.awayLineupIds,session.awayTactic.formation);return <section className={styles.wrap}><header><div><span>MOTOR 2D</span><b>{session.currentMinute}′ • {latest?.type==="goal"?"GOL":latest?.type==="chance"?"ATAQUE":latest?.type==="corner"?"ESCANTEIO":"JOGO CORRIDO"}</b></div><small>movimento derivado da formação, pressão, posse, corredor e eventos da simulação</small></header><div className={styles.pitch}><i className={styles.half}/><i className={styles.circle}/><i className={`${styles.box} ${styles.topBox}`}/><i className={`${styles.box} ${styles.bottomBox}`}/>{[...hp,...ap].map(({p,x,y,hasBall})=><div key={p.id} className={`${styles.player} ${hp.some(v=>v.p.id===p.id)?styles.home:styles.away} ${hasBall?styles.onBall:""}`} style={{left:`${x}%`,top:`${y}%`}}><b>{p.position}</b><span>{p.name.split(" ")[0]}</span></div>)}<div className={styles.ball} style={{left:`${ballX}%`,top:`${ballY}%`}}/></div></section>}
