"use client";
import{useEffect,useMemo,useState}from"react";
import type{LeagueClub,LeaguePlayer}from"@/game-engine/league";
import type{LiveMatchState,MatchSide}from"@/game-engine/live-match";
import type{MatchEvent}from"@/game-engine/match";
import{layoutLineup}from"@/game-engine/tactics-layout";
import styles from"./match-2d-pitch.module.css";
const clamp=(v:number,min=4,max=96)=>Math.max(min,Math.min(max,v));
const zoneX=(zone?:"left"|"center"|"right")=>zone==="left"?24:zone==="right"?76:50;
function label(type:MatchEvent["type"]){return type==="goal"?"GOL":type==="chance"?"FINALIZAÇÃO":type==="corner"?"ESCANTEIO":type==="free_kick"?"FALTA":type==="penalty"?"PÊNALTI":type==="card"?"CARTÃO":type==="red_card"?"EXPULSÃO":type==="injury"?"ATENDIMENTO":type==="tactical"?"AJUSTE TÁTICO":type==="halftime"?"INTERVALO":type==="fulltime"?"FIM DE JOGO":"JOGO CORRIDO"}
export default function Match2DPitch({session,home,away}:{session:LiveMatchState;home:LeagueClub;away:LeagueClub}){const[frame,setFrame]=useState(0);const event=session.events[session.events.length-1];const eventKey=`${event?.minute}:${event?.type}:${event?.team}:${event?.playerId??""}:${event?.assistPlayerId??""}:${session.homeGoals}-${session.awayGoals}`;useEffect(()=>{if(session.phase==="pre_match"||session.phase==="fulltime")return;const id=window.setInterval(()=>setFrame(v=>(v+1)%12),110);return()=>window.clearInterval(id)},[eventKey,session.phase]);const byId=useMemo(()=>new Map([...home.players,...away.players].map(p=>[p.id,p])),[home,away]);
 const build=(side:MatchSide,ids:string[],formation:string)=>{const players=ids.map(id=>byId.get(id)).filter((p):p is LeaguePlayer=>Boolean(p)),layout=layoutLineup(players,formation as never),attacking=event?.team===side,stopped=event&&["card","red_card","injury","halftime","fulltime"].includes(event.type);return layout.map(({player,slot})=>{const baseX=side==="home"?slot.x:100-slot.x,baseY=side==="home"?8+slot.y*.78:92-slot.y*.78;let x=baseX,y=baseY;if(!stopped){const direction=side==="home"?1:-1;const teamShift=(attacking?-7:3)*direction;y=clamp(y+teamShift);if(attacking&&event?.zone)x=clamp(x+(zoneX(event.zone)-x)*.18);if(!attacking&&event?.zone)x=clamp(x+(zoneX(event.zone)-x)*.1)}const actor=event?.playerId===player.id,assistant=event?.assistPlayerId===player.id;if(actor||assistant){x=zoneX(event.zone);const goalY=side==="home"?94:6;if(event?.type==="corner"){x=event.zone==="left"?6:event.zone==="right"?94:zoneX(event.zone);y=side==="home"?88:12}else if(["chance","goal","penalty","free_kick"].includes(event?.type??"")){const progress=Math.min(1,frame/7);y=clamp((side==="home"?72:28)+(goalY-(side==="home"?72:28))*progress*.5);if(assistant)y=side==="home"?66:34}else{y=clamp(baseY)}}return{player,x,y,actor,assistant,side};});};
 const hp=build("home",session.homeLineupIds,session.homeTactic.formation),ap=build("away",session.awayLineupIds,session.awayTactic.formation),actor=event?.playerId?byId.get(event.playerId):undefined,assist=event?.assistPlayerId?byId.get(event.assistPlayerId):undefined,attacking=event?.team==="home"||event?.team==="away"?event.team:session.possessionHome>=50?"home":"away",goalY=attacking==="home"?96:4,startY=attacking==="home"?62:38,progress=Math.min(1,frame/8);let ballX=50,ballY=50;if(event?.type==="kickoff"){ballX=50;ballY=50}else if(event?.type==="corner"){ballX=frame<3?(event.zone==="right"?96:4):zoneX(event.zone);ballY=attacking==="home"?(frame<3?94:82):(frame<3?6:18)}else if(["chance","goal","free_kick","penalty"].includes(event?.type??"")){ballX=zoneX(event?.zone);ballY=startY+(goalY-startY)*progress}else if(event&&["card","red_card","injury"].includes(event.type)){const pos=[...hp,...ap].find(v=>v.player.id===event.playerId);ballX=pos?.x??50;ballY=pos?.y??50}else{ballX=zoneX(event?.zone);ballY=attacking==="home"?58:42}
 return <section className={styles.wrap}><header><div><span>MOTOR 2D • EVENTO SINCRONIZADO</span><b>{session.currentMinute}′ • {event?label(event.type):"JOGO CORRIDO"}</b></div><small>{event?.text??"Movimentação baseada na posse e estrutura das equipes."}</small></header><div className={`${styles.pitch} ${event?.type==="goal"?styles.goalScene:""}`}><i className={styles.half}/><i className={styles.circle}/><i className={`${styles.box} ${styles.topBox}`}/><i className={`${styles.box} ${styles.bottomBox}`}/><i className={`${styles.goal} ${styles.topGoal}`}/><i className={`${styles.goal} ${styles.bottomGoal}`}/>{[...hp,...ap].map(v=><div key={v.player.id} className={`${styles.player} ${v.side==="home"?styles.home:styles.away} ${v.actor?styles.onBall:""} ${v.assistant?styles.assistant:""}`} style={{left:`${v.x}%`,top:`${v.y}%`}}><b>{v.player.position}</b><span>{v.player.name.split(" ")[0]}</span></div>)}<div className={styles.ball} style={{left:`${ballX}%`,top:`${ballY}%`}}/>{event?.type==="goal"&&<div className={styles.eventBadge}>⚽ {actor?.name??"GOL"}{assist?` • passe de ${assist.name}`:""}</div>}{event&&["card","red_card","injury"].includes(event.type)&&<div className={styles.eventBadge}>{event.type==="card"?"🟨":event.type==="red_card"?"🟥":"🩺"} {actor?.name??event.text}</div>}</div></section>}
