"use client";

import { useState } from "react";
import { AtSign, MessageCircleMore, Newspaper, Radio, UsersRound } from "lucide-react";
import type { LeagueClub } from "@/game-engine/league";
import { REAL_MEDIA_PROFILES, SOCIAL_PROFILES, socialSentiment } from "@/game-engine/media-realism";
import type { LivingWorldState } from "@/game-engine/world-events";
import styles from "./media-center.module.css";

type Tab="radar"|"journalists"|"social";
export default function MediaCenterView({world,club}:{world:LivingWorldState;club:LeagueClub}){
 const[tab,setTab]=useState<Tab>("radar"),sentiment=socialSentiment(world.fanSupport,world.mediaPressure),socialNews=world.news.filter(item=>/social|instagram|threads|tiktok|youtube|\bx\b/i.test(item.source)),pressNews=world.news.filter(item=>!socialNews.includes(item));
 return <div className={styles.wrap}>
  <header className={styles.hero}><div><span>MÍDIA, TORCIDA & INTERNET</span><h2>Ecossistema público de {club.name}</h2><p>Veículos e jornalistas reais como referência editorial; manchetes, perguntas e reações são simulações do universo do jogo.</p></div><div className={styles.sentiment}><small>SENTIMENTO DIGITAL</small><b>{sentiment.toUpperCase()}</b><span>Torcida {world.fanSupport} • Pressão {world.mediaPressure}</span></div></header>
  <nav className={styles.tabs}><button className={tab==="radar"?styles.active:""} onClick={()=>setTab("radar")}><Radio/> Radar</button><button className={tab==="journalists"?styles.active:""} onClick={()=>setTab("journalists")}><Newspaper/> Imprensa real</button><button className={tab==="social"?styles.active:""} onClick={()=>setTab("social")}><AtSign/> Redes sociais</button></nav>
  {tab==="radar"&&<div className={styles.grid}><section className={styles.panel}><header><div><b>REPERCUSSÃO RECENTE</b><small>{pressNews.length} registros de imprensa</small></div></header>{pressNews.slice(0,12).map(item=><article className={styles.story} key={item.id}><div><span>{item.source}</span><small>Rodada {item.round}</small></div><b>{item.headline}</b><p>{item.summary}</p></article>)}{!pressNews.length&&<Empty text="As matérias aparecem depois de jogos, coletivas, crises e decisões."/>}</section><section className={styles.panel}><header><div><b>TERMÔMETRO DA TORCIDA</b><small>Impacto das decisões públicas</small></div></header><div className={styles.gauge}><UsersRound/><strong>{world.fanSupport}</strong><span>{world.fanSupport>=70?"Apoio forte":world.fanSupport>=50?"Torcida dividida":"Pressão das arquibancadas"}</span></div><div className={styles.gauge}><MessageCircleMore/><strong>{world.mediaPressure}</strong><span>{world.mediaPressure>=65?"Cobertura muito crítica":world.mediaPressure>=40?"Cobertura intensa":"Ambiente controlado"}</span></div><p className={styles.note}>O jogo usa estas métricas para alterar coletivas, vazamentos, confiança interna e repercussão após resultados.</p></section></div>}
  {tab==="journalists"&&<section className={styles.panel}><header><div><b>VEÍCULOS E PROFISSIONAIS REAIS</b><small>Base editorial verificada em 2026</small></div></header><div className={styles.people}>{REAL_MEDIA_PROFILES.map(profile=><article key={profile.id}><i><Newspaper/></i><div><b>{profile.journalist??profile.outlet}</b><span>{profile.journalist?profile.outlet:"Veículo esportivo"}</span><small>{profile.role??"cobertura esportiva"} • verificado {profile.verifiedAt}</small></div></article>)}</div><p className={styles.disclaimer}>Importante: quando um destes nomes aparecer em uma coletiva, programa ou manchete, o conteúdo textual é gerado pelo Vestiário 90 e identificado como simulação. Ele não representa uma declaração real da pessoa ou do veículo.</p></section>}
  {tab==="social"&&<div className={styles.grid}><section className={styles.panel}><header><div><b>PLATAFORMAS</b><small>Comportamentos diferentes por rede</small></div></header><div className={styles.platforms}>{SOCIAL_PROFILES.map(item=><article key={item.platform}><AtSign/><div><b>{item.platform}</b><span>{item.strength}</span><p>{item.description}</p></div></article>)}</div></section><section className={styles.panel}><header><div><b>FEED DIGITAL</b><small>{socialNews.length} publicações simuladas</small></div></header>{socialNews.slice(0,12).map(item=><article className={styles.story} key={item.id}><div><span>{item.source}</span><small>Rodada {item.round}</small></div><b>{item.headline}</b><p>{item.summary}</p></article>)}{!socialNews.length&&<Empty text="Posts de atletas, torcida e cortes de programas aparecerão conforme o mundo reage."/>}</section></div>}
 </div>;
}
function Empty({text}:{text:string}){return <div className={styles.empty}><Newspaper/><b>Nenhuma repercussão ainda</b><p>{text}</p></div>}
