"use client";

import{useState}from"react";
import{AtSign,Flame,MessageCircleMore,Mic2,Newspaper,Radio,ShieldCheck,UsersRound}from"lucide-react";
import{hydrateMediaWorld,mediaRelationLabel,pendingMediaSessions}from"@/game-engine/media-world";
import{mediaProfileById,mediaProfilesForCompetition,SOCIAL_PROFILES,socialSentiment}from"@/game-engine/media-realism";
import type{SeasonState}from"@/game-engine/season";
import styles from"./media-center.module.css";

type Tab="radar"|"interviews"|"journalists"|"fans"|"social";
export default function MediaCenterView({season,onAnswer}:{season:SeasonState;onAnswer:(sessionId:string,choiceId:string)=>void}){
 const[tab,setTab]=useState<Tab>("radar"),world=season.livingWorld,club=season.league.clubs.find(c=>c.id===season.selectedClubId)??season.league.clubs[0],media=hydrateMediaWorld(season.mediaWorld,season.competitionId),profiles=mediaProfilesForCompetition(season.competitionId),open=pendingMediaSessions(media,season.competitionId),sentiment=socialSentiment(world.fanSupport,world.mediaPressure),socialNews=world.news.filter(item=>/social|instagram|threads|tiktok|youtube|\bx\b/i.test(item.source)),pressNews=world.news.filter(item=>!socialNews.includes(item)),completed=media.sessions.filter(item=>item.status==="Concluída").slice(0,8);
 return <div className={styles.wrap}>
  <header className={styles.hero}><div><span>MUNDO DO FUTEBOL</span><h2>Mídia, torcida & internet</h2><p>{club.name} vive sob cobertura contínua. Profissionais e veículos são referências reais; perguntas, manchetes e reações abaixo pertencem à simulação do seu save.</p></div><div className={styles.sentiment}><small>SENTIMENTO DIGITAL</small><b>{sentiment.toUpperCase()}</b><span>Torcida {world.fanSupport} • Pressão {world.mediaPressure} • {open.length} entrevista{open.length===1?"":"s"}</span></div></header>
  <nav className={styles.tabs}><button className={tab==="radar"?styles.active:""} onClick={()=>setTab("radar")}><Radio/> Radar</button><button className={tab==="interviews"?styles.active:""} onClick={()=>setTab("interviews")}><Mic2/> Entrevistas {open.length>0&&<i>{open.length}</i>}</button><button className={tab==="journalists"?styles.active:""} onClick={()=>setTab("journalists")}><Newspaper/> Imprensa</button><button className={tab==="fans"?styles.active:""} onClick={()=>setTab("fans")}><UsersRound/> Torcida</button><button className={tab==="social"?styles.active:""} onClick={()=>setTab("social")}><AtSign/> Redes</button></nav>

  {tab==="radar"&&<div className={styles.grid}><section className={styles.panel}><header><div><b>REPERCUSSÃO RECENTE</b><small>{pressNews.length} registros de imprensa</small></div></header>{pressNews.slice(0,10).map(item=><article className={styles.story} key={item.id}><div><span>{item.source}</span><small>Rodada {item.round}</small></div><b>{item.headline}</b><p>{item.summary}</p></article>)}{!pressNews.length&&<Empty text="As matérias aparecem depois de jogos, coletivas, crises e decisões."/>}</section><section className={styles.panel}><header><div><b>PAINEL DE PRESSÃO</b><small>O ambiente público afeta o trabalho</small></div></header><Gauge icon={<UsersRound/>} value={world.fanSupport} label={world.fanSupport>=70?"Apoio forte":world.fanSupport>=50?"Torcida dividida":"Pressão das arquibancadas"}/><Gauge icon={<MessageCircleMore/>} value={world.mediaPressure} label={world.mediaPressure>=65?"Cobertura muito crítica":world.mediaPressure>=40?"Cobertura intensa":"Ambiente controlado"}/><Gauge icon={<ShieldCheck/>} value={world.managerReputation} label="Reputação do treinador"/><p className={styles.note}>Vitórias e derrotas alteram segmentos de torcida. Suas respostas mudam relações individuais com jornalistas, acesso aos veículos, pressão pública e reputação.</p></section></div>}

  {tab==="interviews"&&<div className={styles.interviewStack}>{open.length?open.map(session=>{const profile=mediaProfileById(session.profileId),question=session.questions[session.questionIndex];return <section className={styles.interview} key={session.id}><header><div><span>{session.format.toUpperCase()}</span><h3>{profile?.program??profile?.outlet}</h3><p>{profile?.journalist??profile?.outlet} • {profile?.outlet} • rodada {session.round}</p></div><em>SIMULAÇÃO</em></header><div className={styles.question}><small>{question?.topic}</small><b>{question?.prompt}</b></div><div className={styles.answers}>{question?.choices.map(choice=><button key={choice.id} onClick={()=>onAnswer(session.id,choice.id)}><span>{choice.label}</span><small>{choice.answer}</small></button>)}</div>{session.transcript.length>0&&<details><summary>Ver respostas anteriores</summary>{session.transcript.map((line,index)=><p key={index}>{line}</p>)}</details>}</section>}):<section className={styles.panel}><Empty text="Não há entrevista pendente. Avance o calendário ou jogue uma partida para abrir novas coletivas e convites."/></section>}{completed.length>0&&<section className={styles.panel}><header><div><b>HISTÓRICO DE ENTREVISTAS</b><small>{completed.length} conversas recentes</small></div></header>{completed.map(session=>{const profile=mediaProfileById(session.profileId);return <article className={styles.history} key={session.id}><div><b>{profile?.journalist??profile?.outlet}</b><span>{session.format} • rodada {session.round}</span></div><strong>{session.score>=5?"Boa repercussão":session.score<=0?"Atrito":"Neutra"}</strong></article>})}</section>}</div>}

  {tab==="journalists"&&<section className={styles.panel}><header><div><b>RELAÇÕES COM A IMPRENSA</b><small>{profiles.length} profissionais/veículos ativos nesta competição</small></div></header><div className={styles.people}>{profiles.map(profile=>{const relation=media.relations[profile.id];return <article key={profile.id}><i><Newspaper/></i><div className={styles.personBody}><b>{profile.journalist??profile.outlet}</b><span>{profile.outlet} • {profile.program??"cobertura esportiva"}</span><small>{profile.role??"jornalismo esportivo"} • estilo {profile.style}</small><p>{profile.themes.join(" • ")}</p><div className={styles.relation}><em>{mediaRelationLabel(relation)}</em><span>Respeito <b>{relation.respect}</b></span><span>Acesso <b>{relation.access}</b></span><span>Tensão <b>{relation.tension}</b></span><span>Interações <b>{relation.interactions}</b></span></div></div></article>})}</div><p className={styles.disclaimer}>Os nomes, veículos e programas são referências reais verificadas em 2026. Qualquer pergunta, opinião ou declaração atribuída a eles dentro do Vestiário 90 é uma simulação ficcional e não representa fala real.</p></section>}

  {tab==="fans"&&<div className={styles.fanGrid}>{media.fanSegments.map(group=><article className={styles.fanCard} key={group.id}><UsersRound/><div><span>{group.name.toUpperCase()}</span><b>{group.mood}</b><p>{group.priority}</p><small>Influência {group.influence}/100{group.lastShift?` • último impacto: ${group.lastShift}`:""}</small><em><i style={{width:`${group.mood}%`}}/></em></div></article>)}</div>}

  {tab==="social"&&<div className={styles.grid}><section className={styles.panel}><header><div><b>TRENDING NO SAVE</b><small>{media.trends.length} ondas de repercussão</small></div></header>{media.trends.slice(0,14).map(trend=><article className={`${styles.trend} ${styles[trend.sentiment]}`} key={trend.id}><div><AtSign/><span>{trend.platform}</span><small>alcance {trend.reach}/100</small></div><b>{trend.tag}</b><p>{trend.headline}</p></article>)}{!media.trends.length&&<Empty text="Resultados, crises e entrevistas vão criar hashtags, cortes, memes e discussões."/>}</section><section className={styles.panel}><header><div><b>PLATAFORMAS</b><small>Comportamentos diferentes por rede</small></div></header><div className={styles.platforms}>{SOCIAL_PROFILES.map(item=><article key={item.platform}><AtSign/><div><b>{item.platform}</b><span>{item.strength}</span><p>{item.description}</p></div></article>)}</div>{socialNews.slice(0,6).map(item=><article className={styles.story} key={item.id}><div><span>{item.source}</span><small>R{item.round}</small></div><b>{item.headline}</b></article>)}</section></div>}
 </div>;
}
function Gauge({icon,value,label}:{icon:React.ReactNode;value:number;label:string}){return <div className={styles.gauge}>{icon}<strong>{value}</strong><div><b>{label}</b><em><i style={{width:`${value}%`}}/></em></div></div>}
function Empty({text}:{text:string}){return <div className={styles.empty}><Newspaper/><b>Nenhuma repercussão agora</b><p>{text}</p></div>}
