"use client";
import { Flag, PlaneTakeoff, Search, ShieldCheck, Trophy, UserCheck, UserMinus } from "lucide-react";
import type { SeasonState } from "@/game-engine/season";
import { nationalVacancies, nextNationalFixture } from "@/game-engine/national-team";
import styles from "./national-team-view.module.css";

export default function NationalTeamView({season,onApply,onToggle,onPlay,onResign}:{season:SeasonState;onApply:(teamId:string)=>void;onToggle:(playerId:string)=>void;onPlay:()=>void;onResign:()=>void}){
 const career=season.nationalCareer,managerRep=season.livingWorld.managerReputation;
 if(!career||career.status==="Sem seleção"){const vacancies=nationalVacancies(career,managerRep);return <div className={styles.shell}><section className={styles.hero}><div><span>CARREIRA INTERNACIONAL</span><h2>Seleções também fazem parte da sua trajetória</h2><p>Federações avaliam reputação, momento e compatibilidade de projeto. O cargo internacional é paralelo ao clube.</p></div><Flag/></section><section className={styles.panel}><header><div><span>VAGAS E PROJETOS</span><h3>Federações que podem considerar seu currículo</h3></div><Search/></header><div className={styles.jobs}>{vacancies.map(team=>{const invited=career.offers.some(o=>o.teamId===team.id);return <article key={team.id}><div><b>{team.name}</b><span>{team.confederation} • reputação {team.reputation}</span><small>{invited?"Convite/sondagem ativa":"Manifestação de interesse possível"}</small></div><em>{invited?"CONVITE":team.reputation>managerRep+18?"PROJETO AMBICIOSO":"DISPONÍVEL"}</em><button onClick={()=>onApply(team.id)}>MANIFESTAR INTERESSE</button></article>})}</div></section></div>}
 const next=nextNationalFixture(career,season.currentDate),today=career.fixtures.find(f=>!f.played&&f.date===season.currentDate),selected=new Set(career.squadIds);
 return <div className={styles.shell}><section className={styles.hero}><div><span>SELEÇÃO NACIONAL</span><h2>{career.teamName}</h2><p>Você acumula o cargo com o clube. Datas FIFA têm prioridade e conflitos de calendário são remanejados automaticamente.</p></div><div className={styles.heroStats}><div><small>CONVOCADOS</small><b>{career.squadIds.length}/26</b></div><div><small>PRÓXIMO JOGO</small><b>{next?.date??"—"}</b></div></div></section>{today&&<section className={styles.matchday}><Flag/><div><span>{today.competition} • {today.stage}</span><h3>{today.homeName} × {today.awayName}</h3><p>Convocação: {career.squadIds.length} atletas. A coletiva pré-jogo aparece no módulo de Mídia antes da partida.</p></div><button onClick={onPlay}><PlaneTakeoff/> JOGAR PARTIDA DA SELEÇÃO</button></section>}<div className={styles.grid}><section className={styles.panel}><header><div><span>CALENDÁRIO</span><h3>Compromissos internacionais</h3></div><Trophy/></header><div className={styles.fixtures}>{career.fixtures.map(f=><article key={f.id} className={f.date===season.currentDate?styles.today:""}><time>{f.date}</time><div><b>{f.homeName} × {f.awayName}</b><span>{f.competition} • {f.stage}</span></div><strong>{f.played?`${f.homeGoals} × ${f.awayGoals}`:"Agendado"}</strong></article>)}</div>{career.calendarNotes.length>0&&<div className={styles.notes}>{career.calendarNotes.slice(-5).map((n,i)=><p key={i}>• {n}</p>)}</div>}</section><section className={styles.panel}><header><div><span>HISTÓRICO</span><h3>Seu trabalho internacional</h3></div><ShieldCheck/></header><div className={styles.history}>{career.history.length?career.history.map(h=><article key={h.id}><b className={styles[h.result]}>{h.result}</b><div><strong>{h.score} vs {h.opponent}</strong><span>{h.competition} • {h.stage} • {h.date}</span></div></article>):<p className={styles.empty}>Nenhum jogo disputado ainda.</p>}</div><button className={styles.resign} onClick={onResign}>DEIXAR A SELEÇÃO</button></section></div><section className={styles.panel}><header><div><span>CONVOCAÇÃO</span><h3>Banco mundial + jogadores do campeonato carregado</h3></div><UserCheck/></header><p className={styles.info}>A base atual ainda não possui nacionalidade oficial para todos os atletas. O jogo identifica elegíveis do save e completa a seleção com jogadores virtuais do exterior, sem apresentar esses dados como oficiais.</p><div className={styles.pool}>{career.pool.map(player=><article key={player.id}><div><b>{player.name}</b><span>{player.clubName} • {player.position} • {player.age} anos</span></div><strong>OVR {player.overall}</strong><em>{player.virtual?"EXTERIOR":"BASE DO SAVE"}</em><button className={selected.has(player.id)?styles.cut:""} onClick={()=>onToggle(player.id)}>{selected.has(player.id)?<><UserMinus/> CORTAR</>:<><UserCheck/> CONVOCAR</>}</button></article>)}</div></section></div>;
}
