"use client";

import Image from "next/image";
import { useEffect, useState } from "react";
import { BarChart3, Bell, BriefcaseBusiness, Building2, CalendarDays, ChevronRight, CircleUserRound, ClipboardList, Globe2, Home, Inbox, LayoutGrid, Landmark, MessageSquareText, Megaphone, Newspaper, Play, RotateCcw, Settings, Shield, Shirt, Trophy, Users, Zap } from "lucide-react";
import styles from "./page.module.css";
import seasonStyles from "./season.module.css";
import LiveMatchView from "./live-match-view";
import DressingRoomView from "./dressing-room-view";
import WorldInboxView, { NewsFeedView } from "./world-view";
import MarketView from "./market-view";
import TacticsSetupView from "./tactics-setup-view";
import StatisticsView from "./statistics-view";
import MediaCenterView from "./media-center-view";
import CareerView from "./career-view";
import PlayerManagementView from "./player-management-view";
import ClubManagementView from "./club-management-view";
import MainMenu from "./main-menu";
import FootballWorldView from "./football-world-view";
import AdvancedClubView from "./advanced-club-view";
import { professionalCompetitionById, type ProfessionalCompetitionId } from "@/data/brazil-2026/competitions";
import { leagueClubIdForTransfermarkt } from "@/game-engine/new-game";
import { createSaveSlot, migrateLegacySeason, saveToSlot, type SaveSlot } from "@/game-engine/save-slots";
import { sortedStandings, type LeagueClub, type LeagueFixture, type LeagueStanding } from "@/game-engine/league";
import { DEFAULT_TACTIC, type MatchResult, type MatchTactic } from "@/game-engine/match";
import { createLiveMatch, liveMatchResult, type LiveMatchState } from "@/game-engine/live-match";
import { tacticForClub } from "@/game-engine/club-ai";
import { talkToPlayer, type ConversationAction } from "@/game-engine/people";
import { pendingWorldEvents } from "@/game-engine/world-events";
import { pendingMediaSessions } from "@/game-engine/media-world";
import { advanceCalendarDay, createSeason, getCupMatchContext, getCurrentUserFixture, getSelectedClub, getTodayUserCupMatch, getTodayUserFixture, getUserFixtures, hydrateSeasonState, matchdaySelectionReady, playCurrentCupMatch, playCurrentRound, resolveMediaSessionChoice, resolveSeasonWorldChoice, setMatchdayRole, startNextSeason, toggleLineupPlayer, type MatchdayRole, type SeasonState } from "@/game-engine/season";

const NAV=[["Visão geral",Home],["Caixa de entrada",Inbox],["Elenco",Users],["Vestiário",MessageSquareText],["Clube",Building2],["Táticas",LayoutGrid],["Calendário",CalendarDays],["Classificação",Trophy],["Central de Dados",BarChart3],["Mídia & Redes",Megaphone],["Mundo",Globe2],["Gestão & Legado",Landmark],["Mercado",BarChart3],["Carreira",BriefcaseBusiness],["Notícias",Newspaper]] as const;

export default function Dashboard(){
  const [screen,setScreen]=useState<"menu"|"game">("menu"),[saveId,setSaveId]=useState<string|null>(null),[season,setSeason]=useState<SeasonState>(()=>createSeason("vestiario-90",2026)),[active,setActive]=useState("Visão geral"),[notice,setNotice]=useState(""),[tactic,setTactic]=useState<MatchTactic>(DEFAULT_TACTIC),[match,setMatch]=useState<MatchResult|null>(null),[liveMatch,setLiveMatch]=useState<LiveMatchState|null>(null),[activeCupMatchId,setActiveCupMatchId]=useState<string|null>(null);
  useEffect(()=>{migrateLegacySeason()},[]);
  const league=season.league,competition=professionalCompetitionById(season.competitionId??league.competitionId??"BRA1"),totalRounds=league.totalRounds??Math.max(...league.fixtures.map(f=>f.round),38),todayFixture=getTodayUserFixture(season),todayCup=getTodayUserCupMatch(season),club=getSelectedClub(season),employed=season.career.status==="Empregado",standings=sortedStandings(league),standing=standings.find(s=>s.clubId===club.id)!,position=standings.findIndex(s=>s.clubId===club.id)+1,squadMorale=Math.round(club.players.reduce((sum,p)=>sum+p.morale,0)/club.players.length),squadCondition=Math.round(club.players.reduce((sum,p)=>sum+p.condition,0)/club.players.length),currentFixture=getCurrentUserFixture(season),cupContext=(todayCup?getCupMatchContext(season,todayCup.match.id):activeCupMatchId?getCupMatchContext(season,activeCupMatchId):undefined),opponent=cupContext?(cupContext.userSide==="home"?cupContext.away:cupContext.home):currentFixture?league.clubs.find(c=>c.id===(currentFixture.homeClubId===club.id?currentFixture.awayClubId:currentFixture.homeClubId)):undefined,unavailable=club.players.filter(p=>p.injuryDays>0||p.suspensionMatches>0).length,pendingEvents=pendingWorldEvents(season.livingWorld),unreadEvents=season.livingWorld.inbox.filter(event=>event.unread&&!event.resolved).length,pendingMedia=pendingMediaSessions(season.mediaWorld,season.competitionId),latestNews=season.livingWorld.news.slice(0,3);

  function flash(message:string){setNotice(message);window.setTimeout(()=>setNotice(""),3600)}
  function persist(next:SeasonState){setSeason(next);if(saveId)saveToSlot(saveId,next)}
  function handleLoad(slot:SaveSlot){const next=hydrateSeasonState(slot.state);setSaveId(slot.meta.id);setSeason(next);setScreen("game");setActive("Visão geral");setMatch(null);setLiveMatch(null);setTactic(DEFAULT_TACTIC)}
  function handleStart(competitionId:ProfessionalCompetitionId,clubTransfermarktId:number,saveName?:string){const clubId=leagueClubIdForTransfermarkt(competitionId,clubTransfermarktId),next=createSeason(`career-${Date.now()}-${clubTransfermarktId}`,2026,clubId,competitionId),meta=createSaveSlot(next,saveName);setSaveId(meta?.id??null);setSeason(next);setScreen("game");setActive("Visão geral");setMatch(null);setLiveMatch(null);setTactic(DEFAULT_TACTIC)}
  function handleAdvance(){if(!employed){handleCareerAdvanceRound();return}const result=advanceCalendarDay(season);persist(result.state);if(result.route==="matchday")setActive("Táticas");else if(result.route==="club")setActive("Clube");else if(result.route==="media")setActive("Mídia & Redes");else if(result.route==="inbox")setActive("Caixa de entrada");flash(`${formatDate(result.state.currentDate)} • ${result.reason}`)}
  function handleCareerAdvanceRound(){if(season.completed){handleNextSeason();return}const next=playCurrentRound(season);persist(next);flash(`Rodada ${Math.min(totalRounds,next.currentRound-1)} simulada • estatísticas e evolução atualizadas`)}
  function handleToggleLineup(playerId:string){persist(toggleLineupPlayer(season,playerId))}
  function handleMatchdayRole(playerId:string,role:MatchdayRole){persist(setMatchdayRole(season,playerId,role))}
  function handleConversation(playerId:string,action:ConversationAction){const result=talkToPlayer(season,playerId,action);persist(result.state);flash(result.message)}
  function handleWorldChoice(eventId:string,choiceId:string){const result=resolveSeasonWorldChoice(season,eventId,choiceId);persist(result.state);flash(result.message)}
  function handleMediaChoice(sessionId:string,choiceId:string){const result=resolveMediaSessionChoice(season,sessionId,choiceId);persist(result.state);flash(result.message)}

  function handlePlay(){
    if(!employed){flash("Você precisa assumir um clube antes de voltar ao banco de reservas.");return}
    if(!matchdaySelectionReady(season)){flash(`Complete a convocação: 11 titulares e o banco permitido pela ${competition.shortName}.`);return}
    const cup=todayCup?getCupMatchContext(season,todayCup.match.id):undefined;if(!cup&&!currentFixture){flash("Não há partida pendente.");return}
    if(!cup&&!todayFixture){flash(`A partida está marcada para ${formatDate(currentFixture?.date??season.currentDate)}. Avance os dias até o dia do jogo.`);return}
    const home=cup?.home??league.clubs.find(c=>c.id===currentFixture?.homeClubId),away=cup?.away??league.clubs.find(c=>c.id===currentFixture?.awayClubId);if(!home||!away)return;const userSide=cup?.userSide??(currentFixture?.homeClubId===club.id?"home":"away"),matchKey=cup?.match.id??currentFixture!.id,opponentClub=userSide==="home"?away:home,opponentTactic=opponentClub.id.startsWith("virtual-")?DEFAULT_TACTIC:tacticForClub(season.clubAi,opponentClub.id),session=createLiveMatch(home,away,`${season.baseSeed}:${season.year}:${matchKey}:live`,userSide,season.lineupIds,tactic,season.benchIds,competition.benchSize,competition.maxSubstitutions,opponentTactic);setActiveCupMatchId(cup?.match.id??null);setMatch(null);setLiveMatch(session);
  }
  function handleLiveChange(next:LiveMatchState){setLiveMatch(next);setTactic(next.userSide==="home"?next.homeTactic:next.awayTactic)}
  function handleLiveFinish(session:LiveMatchState){const result=liveMatchResult(session);if(!result)return;const participants=session.usedPlayerIds.filter(id=>club.players.some(p=>p.id===id)),next=activeCupMatchId?playCurrentCupMatch(season,activeCupMatchId,result,participants):playCurrentRound(season,tactic,result,participants);persist(next);setLiveMatch(null);setMatch(result)}
  function handleNextSeason(){const next=startNextSeason(season);persist(next);setMatch(null);setLiveMatch(null);setTactic(DEFAULT_TACTIC);flash(`Temporada ${next.year} iniciada. Idade, potencial e overalls foram recalibrados.`)}

  const persistedCupContext=activeCupMatchId?getCupMatchContext(season,activeCupMatchId):undefined,matchHome=persistedCupContext?.home??(season.lastUserMatch?league.clubs.find(c=>c.id===season.lastUserMatch?.homeClubId):undefined),matchAway=persistedCupContext?.away??(season.lastUserMatch?league.clubs.find(c=>c.id===season.lastUserMatch?.awayClubId):undefined),liveHome=persistedCupContext?.home??(currentFixture?league.clubs.find(c=>c.id===currentFixture.homeClubId):undefined),liveAway=persistedCupContext?.away??(currentFixture?league.clubs.find(c=>c.id===currentFixture.awayClubId):undefined);
  if(screen==="menu")return <MainMenu onLoad={handleLoad} onStart={handleStart}/>;

  return <div className={styles.shell}>
    <aside className={styles.sidebar}><div className={styles.brand}><span>V90</span><div><b>VESTIÁRIO</b><small>90</small></div></div><nav>{NAV.map(([label,Icon])=><button key={label} onClick={()=>{setActive(label);setMatch(null)}} className={active===label?styles.activeNav:""}><Icon size={18}/><span>{label}</span>{label==="Caixa de entrada"&&pendingEvents.length>0&&<i>{Math.min(99,pendingEvents.length)}</i>}{label==="Mídia & Redes"&&pendingMedia.length>0&&<i>{Math.min(9,pendingMedia.length)}</i>}</button>)}</nav><div className={styles.clubCard}>{employed?<ClubLogo club={club} size={38}/>:<BriefcaseBusiness size={28}/>}<div><b>{employed?club.name:"Sem clube"}</b><small>{employed?`${competition.name} • ${season.year}`:"Disponível no mercado"}</small></div><ChevronRight size={17}/></div><button className={styles.settings} onClick={()=>setScreen("menu")}><Settings size={18}/> Menu principal</button><div className={styles.manager}><CircleUserRound/><div><b>Raul Soares</b><small>{employed?"Treinador principal":"Sem clube • mercado aberto"}</small></div></div></aside>
    <main className={styles.main}>
      <header className={styles.topbar}><div className={styles.mobileBrand}>V90</div><div className={styles.season}><span>{employed?competition.name:"Mercado de Treinadores"} • Temporada {season.year}</span><b>{season.completed?"TEMPORADA ENCERRADA":`RODADA ${season.currentRound} DE ${totalRounds}`} • {formatDate(season.currentDate)}</b></div><div className={styles.topActions}><button aria-label="Mensagens" onClick={()=>setActive("Caixa de entrada")}><MessageSquareText size={19}/>{unreadEvents>0&&<i/>}</button><button aria-label="Notificações"><Bell size={19}/><i/></button><button className={styles.advance} onClick={handleAdvance}>{employed?"AVANÇAR DIA":"AVANÇAR RODADA"} <Play size={15} fill="currentColor"/></button></div></header>{notice&&<div className={styles.toast}><Zap size={17}/>{notice}</div>}
      <section className={styles.content}>
        <div className={styles.welcome}><div><p>{season.completed?"FIM DE TEMPORADA":`RODADA ${season.currentRound} • ${competition.name.toUpperCase()}`}</p><h1>{active==="Visão geral"?"Bom dia, Raul.":active}</h1><span>{active==="Visão geral"?(!employed?"Você está sem clube. Avance as rodadas, responda entrevistas e escolha o próximo projeto.":season.completed?"O campeonato terminou. Hora de avaliar a temporada e preparar a próxima.":`${opponent?`Próximo adversário: ${opponent.name}.`:"Sem partida pendente"} ${unavailable?`${unavailable} jogador(es) indisponível(is).`:"Elenco completo à disposição."}`):`Temporada ${season.year} • ${employed?club.name:"Sem clube"}`}</span></div><button onClick={()=>setActive("Calendário")}><ClipboardList size={17}/> Ver calendário</button></div>
        {active==="Elenco"?<PlayerManagementView season={season} onToggleLineup={handleToggleLineup} onResult={({state:next,message})=>{persist(next);flash(message)}}/>:
        active==="Clube"?<ClubManagementView season={season} onOpenInbox={()=>setActive("Caixa de entrada")} onResult={({state:next,message})=>{persist(next);flash(message)}}/>:
        active==="Vestiário"?<DressingRoomView season={season} onConversation={handleConversation}/>:
        active==="Caixa de entrada"?<WorldInboxView world={season.livingWorld} club={club} onResolve={handleWorldChoice}/>:
        active==="Notícias"?<NewsFeedView world={season.livingWorld} club={club}/>:
        active==="Carreira"?<CareerView season={season} onOpenInbox={()=>setActive("Caixa de entrada")} onAdvanceRound={handleCareerAdvanceRound}/>:
        active==="Mercado"?<MarketView season={season} onResult={({state:next,message})=>{persist(next);flash(message)}}/>:
        active==="Mundo"?<FootballWorldView season={season}/>:active==="Gestão & Legado"?<AdvancedClubView season={season} onOpenClub={()=>setActive("Clube")}/>:
        active==="Central de Dados"?<StatisticsView season={season}/>:
        active==="Mídia & Redes"?<MediaCenterView season={season} onAnswer={handleMediaChoice}/>:
        active==="Táticas"?(liveMatch&&liveHome&&liveAway?<LiveMatchView session={liveMatch} home={liveHome} away={liveAway} onChange={handleLiveChange} onFinish={handleLiveFinish}/>:match&&matchHome&&matchAway?<MatchCenter home={matchHome} away={matchAway} result={match} onContinue={()=>{setMatch(null);setActiveCupMatchId(null);setActive("Visão geral")}}/>:season.completed?<SeasonEnd season={season} standings={standings} clubs={league.clubs} onNext={handleNextSeason}/>:opponent?<TacticsView club={club} opponent={opponent} tactic={tactic} onChange={setTactic} lineupIds={season.lineupIds} benchIds={season.benchIds} benchSize={competition.benchSize} onSetRole={handleMatchdayRole} onPlay={handlePlay}/>:<ComingSoon title="Partida"/>):
        active==="Classificação"?<TableView clubs={league.clubs} standings={standings} selectedClubId={club.id} competitionName={competition.name} totalRounds={totalRounds}/>:
        active==="Calendário"?<CalendarView season={season}/>:
        active!=="Visão geral"?<ComingSoon title={active}/>:
        !employed?<CareerView season={season} onOpenInbox={()=>setActive("Caixa de entrada")} onAdvanceRound={handleCareerAdvanceRound}/>:
        <><div className={styles.kpis}><Metric label="POSIÇÃO" value={`${position}º`} detail={`${standing.points} pontos • ${standing.played} jogos`} icon={<Trophy/>} tone="green"/><Metric label="CONDIÇÃO DO ELENCO" value={`${squadCondition}%`} detail={`Moral ${squadMorale}%`} icon={<Users/>} tone="blue"/><Metric label="DISPONIBILIDADE" value={`${club.players.length-unavailable}/${club.players.length}`} detail={unavailable?`${unavailable} fora`:"Todos disponíveis"} icon={<Shield/>} tone="gold"/><Metric label="FORMA RECENTE" value="" detail="Últimos 5 jogos" icon={<BarChart3/>} tone="purple" formValues={season.recentForm}/></div>{season.completed?<SeasonEnd season={season} standings={standings} clubs={league.clubs} onNext={handleNextSeason}/>:<div className={styles.grid}><div className={styles.leftCol}>{currentFixture&&opponent&&<NextMatchCard fixture={currentFixture} club={club} opponent={opponent} standings={standings} tactic={tactic} competitionName={competition.name} onPrepare={()=>setActive("Táticas")}/>}<Agenda fixtures={getUserFixtures(season)} league={league.clubs} currentRound={season.currentRound} competitionName={competition.name} totalRounds={totalRounds}/></div><div className={styles.rightCol}><section className={`${styles.card} ${styles.inboxCard}`}><div className={styles.cardHead}><div>PRECISA DA SUA ATENÇÃO {pendingEvents.length>0&&<i>{pendingEvents.length}</i>}</div><button onClick={()=>setActive("Caixa de entrada")}>Ver inbox <ChevronRight size={15}/></button></div>{pendingEvents.slice(0,3).map((event,index)=><InboxItem key={event.id} urgent={index===0} icon={event.kind.slice(0,2).toUpperCase()} title={event.title} text={event.body} time={`R${event.round}`} onClick={()=>setActive("Caixa de entrada")}/>)}{pendingEvents.length===0&&<InboxItem icon="OK" title="Sem decisões pendentes" text="O mundo está calmo por enquanto. Jogue ou avance para gerar novas situações." time="agora" onClick={()=>setActive("Caixa de entrada")}/>}</section><section className={styles.card}><div className={styles.cardHead}><div>MUNDO VIVO</div><button onClick={()=>setActive("Notícias")}>Ver notícias <ChevronRight size={15}/></button></div>{latestNews[0]?<article className={styles.featureNews}><div><span>{latestNews[0].source.toUpperCase()}</span><b>{latestNews[0].headline}</b><small>Rodada {latestNews[0].round}</small></div></article>:<article className={styles.featureNews}><div><span>FUTEBOL AGORA</span><b>O mundo ainda está esperando sua primeira decisão.</b><small>Temporada {season.year}</small></div></article>}{latestNews.slice(1).map(item=><News key={item.id} initials={item.source.slice(0,2).toUpperCase()} source={item.source} text={item.headline} time={`R${item.round}`}/>)}</section></div></div>}</>}
      </section>
    </main>
    <nav className={styles.mobileNav}>{NAV.slice(0,5).map(([label,Icon])=><button key={label} onClick={()=>{setActive(label);setMatch(null)}} className={active===label?styles.mobileActive:""}><Icon size={20}/><span>{label.split(" ")[0]}</span></button>)}</nav>
  </div>;
}

function ClubLogo({club,size}:{club:LeagueClub;size:number}){return <span className={seasonStyles.logoWrap} style={{width:size,height:size}}><Image src={club.imageUrl} alt={`Escudo ${club.name}`} width={size} height={size} sizes={`${size}px`}/></span>}
function Metric({label,value,detail,icon,tone,formValues}:{label:string;value:string;detail:string;icon:React.ReactNode;tone:string;formValues?:string[]}){return <div className={styles.metric}><div className={`${styles.metricIcon} ${styles[tone]}`}>{icon}</div><div><span>{label}</span>{formValues?<div className={styles.form}>{formValues.length?formValues.map((x,i)=><b key={i} className={x==="V"?styles.win:x==="D"?styles.loss:styles.draw}>{x}</b>):<small>— — — — —</small>}</div>:<strong>{value}</strong>}<small>{detail}</small></div></div>}
function NextMatchCard({fixture,club,opponent,standings,tactic,competitionName,onPrepare}:{fixture:LeagueFixture;club:LeagueClub;opponent:LeagueClub;standings:LeagueStanding[];tactic:MatchTactic;competitionName:string;onPrepare:()=>void}){const isHome=fixture.homeClubId===club.id,home=isHome?club:opponent,away=isHome?opponent:club,clubPosition=standings.findIndex(s=>s.clubId===club.id)+1,opponentPosition=standings.findIndex(s=>s.clubId===opponent.id)+1;return <section className={styles.card}><div className={styles.cardHead}><div><span className={styles.liveDot}/> PRÓXIMA PARTIDA</div><button onClick={onPrepare}>Ver detalhes <ChevronRight size={15}/></button></div><div className={styles.competition}>{competitionName.toUpperCase()} • {formatDate(fixture.date)} • RODADA {fixture.round} <b>{isHome?"CASA":"FORA"}</b></div><div className={styles.versus}><div><ClubLogo club={home} size={58}/><b>{home.name}</b><small>{isHome?`${clubPosition}º lugar`:`${opponentPosition}º lugar`}</small></div><div className={styles.vs}><strong>VS</strong><span>Rodada {fixture.round}</span><small>{isHome?"Seu estádio":"Jogo fora"}</small></div><div><ClubLogo club={away} size={58}/><b>{away.name}</b><small>{isHome?`${opponentPosition}º lugar`:`${clubPosition}º lugar`}</small></div></div><div className={styles.matchFooter}><span><Shirt size={16}/> {tactic.formation} • {tactic.mentality}</span><button onClick={onPrepare}>PREPARAR PARTIDA <ChevronRight size={16}/></button></div></section>}
function Agenda({fixtures,league,currentRound,competitionName,totalRounds}:{fixtures:LeagueFixture[];league:LeagueClub[];currentRound:number;competitionName:string;totalRounds:number}){const visible=fixtures.filter(f=>f.round>=Math.max(1,currentRound-1)&&f.round<=Math.min(totalRounds,currentRound+2)).slice(0,4);return <section className={styles.card}><div className={styles.cardHead}><div>AGENDA</div><button>{totalRounds} rodadas</button></div><div className={styles.fixtures}>{visible.map(f=>{const home=league.find(c=>c.id===f.homeClubId)!,away=league.find(c=>c.id===f.awayClubId)!;return <div className={styles.fixture} key={f.id}><div className={styles.dateBox}><b>{formatShortDate(f.date)}</b><span>R{f.round}</span></div><div className={styles.fixtureInfo}><b>{home.name} <span>×</span> {away.name}</b><small>{f.played?`${f.homeGoals} × ${f.awayGoals}`:competitionName}</small></div><em className={f.round===currentRound?styles.nextTag:""}>{f.played?"FIM":f.round===currentRound?"PRÓXIMO":"AGENDADO"}</em></div>})}</div></section>}
function InboxItem({icon,title,text,time,urgent,onClick}:{icon:string;title:string;text:string;time:string;urgent?:boolean;onClick?:()=>void}){return <button className={styles.inboxItem} onClick={onClick}><span className={urgent?styles.urgentAvatar:""}>{icon}</span><div><b>{title}</b><p>{text}</p><small>{time}{urgent&&" • Decisão necessária"}</small></div><ChevronRight size={17}/></button>}
function News({initials,source,text,time}:{initials:string;source:string;text:string;time:string}){return <div className={styles.newsLine}><span>{initials}</span><div><b>{source}</b><p>{text}</p></div><small>{time}</small></div>}
function TableView({clubs,standings,selectedClubId,competitionName,totalRounds}:{clubs:LeagueClub[];standings:LeagueStanding[];selectedClubId:string;competitionName:string;totalRounds:number}){return <section className={`${styles.card} ${styles.dataCard}`}><div className={styles.cardHead}><div>{competitionName.toUpperCase()}</div><button>{totalRounds} rodadas</button></div><div className={styles.tableScroll}><table className={styles.dataTable}><thead><tr><th>#</th><th>Clube</th><th>J</th><th>V</th><th>E</th><th>D</th><th>GP</th><th>GC</th><th>SG</th><th>PTS</th></tr></thead><tbody>{standings.map((s,i)=>{const c=clubs.find(x=>x.id===s.clubId)!;return <tr key={s.clubId} className={s.clubId===selectedClubId?seasonStyles.myClubRow:""}><td><b>{i+1}</b></td><td><span className={styles.clubName}><i style={{background:c.color}}/>{c.name}</span></td><td>{s.played}</td><td>{s.won}</td><td>{s.drawn}</td><td>{s.lost}</td><td>{s.goalsFor}</td><td>{s.goalsAgainst}</td><td>{s.goalsFor-s.goalsAgainst}</td><td><strong>{s.points}</strong></td></tr>})}</tbody></table></div></section>}
function TacticsView({club,opponent,tactic,onChange,lineupIds,benchIds,benchSize,onSetRole,onPlay}:{club:LeagueClub;opponent:LeagueClub;tactic:MatchTactic;onChange:(t:MatchTactic)=>void;lineupIds:string[];benchIds:string[];benchSize:number;onSetRole:(id:string,role:MatchdayRole)=>void;onPlay:()=>void}){return <TacticsSetupView club={club} opponent={opponent} tactic={tactic} onChange={onChange} lineupIds={lineupIds} benchIds={benchIds} benchSize={benchSize} onSetRole={onSetRole} onPlay={onPlay}/>}
function MatchCenter({home,away,result,onContinue}:{home:LeagueClub;away:LeagueClub;result:MatchResult;onContinue:()=>void}){return <div className={styles.matchCenter}><section className={`${styles.card} ${styles.scoreboard}`}><span>ENCERRADO • RODADA CONCLUÍDA</span><div><b>{home.name}</b><strong>{result.homeGoals} <i>×</i> {result.awayGoals}</strong><b>{away.name}</b></div><small>Posse {result.possessionHome}%–{100-result.possessionHome}% • Finalizações {result.shotsHome}–{result.shotsAway}</small><button className={seasonStyles.continueButton} onClick={onContinue}>CONTINUAR TEMPORADA <ChevronRight size={16}/></button></section><section className={`${styles.card} ${styles.commentary}`}><div className={styles.cardHead}><div>NARRAÇÃO DA PARTIDA</div></div>{result.events.map((event,i)=><article key={`${event.minute}-${i}`} className={event.type==="goal"?styles.goalEvent:""}><time>{event.minute===0?"00'":`${event.minute}'`}</time><span>{event.type==="goal"?"⚽":event.type==="card"?"🟨":event.type==="injury"?"🩺":"•"}</span><p>{event.text}</p></article>)}</section></div>}
function CalendarView({season}:{season:SeasonState}){const fixtures=getUserFixtures(season),clubs=season.league.clubs,totalRounds=season.league.totalRounds??fixtures.length;return <section className={`${styles.card} ${styles.dataCard}`}><div className={styles.cardHead}><div>CALENDÁRIO • {season.year}</div><button>{fixtures.filter(f=>f.played).length}/{totalRounds} jogados</button></div><div className={seasonStyles.calendarList}>{fixtures.map(f=>{const home=clubs.find(c=>c.id===f.homeClubId)!,away=clubs.find(c=>c.id===f.awayClubId)!;return <article key={f.id} className={f.round===season.currentRound?seasonStyles.currentFixture:""}><span>{formatShortDate(f.date)}</span><div><b>{home.name} × {away.name}</b><small>{f.played?`Final • ${f.homeGoals} × ${f.awayGoals}`:f.date===season.currentDate?"HOJE • dia de jogo":f.round===season.currentRound?"Próxima partida":"Agendado"} • Rodada {f.round}</small></div><em>{f.played?"✓":f.homeClubId===season.selectedClubId?"CASA":"FORA"}</em></article>})}</div></section>}
function SeasonEnd({season,standings,clubs,onNext}:{season:SeasonState;standings:LeagueStanding[];clubs:LeagueClub[];onNext:()=>void}){const champion=clubs.find(c=>c.id===season.championClubId),myPosition=standings.findIndex(s=>s.clubId===season.selectedClubId)+1,myStanding=standings.find(s=>s.clubId===season.selectedClubId)!;return <section className={`${styles.card} ${seasonStyles.seasonEnd}`}><Trophy/><span>TEMPORADA {season.year} CONCLUÍDA</span><h2>{champion?.name} é o campeão</h2><p>Você terminou em <b>{myPosition}º</b>, com <b>{myStanding.points} pontos</b>. Estatísticas, idade e desenvolvimento foram persistidos.</p><button onClick={onNext}><RotateCcw size={17}/> INICIAR TEMPORADA {season.year+1}</button></section>}
function formatDate(iso?:string){if(!iso)return"Data a definir";try{return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(`${iso}T12:00:00Z`));}catch{return iso}}
function formatShortDate(iso?:string){if(!iso)return"—";try{return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",timeZone:"UTC"}).format(new Date(`${iso}T12:00:00Z`));}catch{return iso}}
function ComingSoon({title}:{title:string}){return <section className={`${styles.card} ${styles.coming}`}><Zap/><h2>{title}</h2><p>Este módulo permanece no roadmap. A prioridade atual é aprofundar a experiência do treinador dentro da partida e conectar o mundo humano às consequências esportivas.</p></section>}
