"use client";

import { useEffect, useMemo, useState } from "react";
import { BarChart3, Bell, CalendarDays, ChevronRight, CircleUserRound, ClipboardList, Home, Inbox, LayoutGrid, MessageSquareText, Newspaper, Play, Settings, Shield, Shirt, Trophy, Users, Zap } from "lucide-react";
import styles from "./page.module.css";
import { createInitialWorld, advanceDay, type GameWorld } from "@/game-engine/world";
import { loadLocalSave, saveLocalWorld } from "@/game-engine/save";
import { createLeague, sortedStandings, type LeagueClub, type LeagueStanding } from "@/game-engine/league";

const NAV = [["Visão geral",Home],["Caixa de entrada",Inbox],["Elenco",Users],["Táticas",LayoutGrid],["Calendário",CalendarDays],["Classificação",Trophy],["Mercado",BarChart3],["Notícias",Newspaper]] as const;
const form=["V","V","E","D","V"];
const fixtures=[{date:"18 SET",home:"Aurora FC",away:"Ferroviário Azul",venue:"Estádio do Farol",tag:"PRÓXIMO"},{date:"22 SET",home:"União Serrana",away:"Aurora FC",venue:"Arena da Serra",tag:"FORA"},{date:"29 SET",home:"Aurora FC",away:"Nacional do Vale",venue:"Estádio do Farol",tag:"CASA"}];

export default function Dashboard(){
 const [world,setWorld]=useState<GameWorld>(()=>createInitialWorld("vestiario-90-demo")); const [active,setActive]=useState("Visão geral"); const [notice,setNotice]=useState("");
 useEffect(()=>{const saved=loadLocalSave();if(saved)queueMicrotask(()=>setWorld(saved.world))},[]);
 const squadMorale=useMemo(()=>Math.round(world.players.reduce((s,p)=>s+p.morale,0)/world.players.length),[world]);
 const league=useMemo(()=>createLeague("liga-nacional-2026"),[]);
 function handleAdvance(){const next=advanceDay(world);setWorld(next);saveLocalWorld(next);setNotice(`${next.lastEvent} • Jogo salvo`);window.setTimeout(()=>setNotice(""),3600)}
 return <div className={styles.shell}>
  <aside className={styles.sidebar}><div className={styles.brand}><span>V90</span><div><b>VESTIÁRIO</b><small>90</small></div></div><nav>{NAV.map(([label,Icon])=><button key={label} onClick={()=>setActive(label)} className={active===label?styles.activeNav:""}><Icon size={18}/><span>{label}</span>{label==="Caixa de entrada"&&<i>3</i>}</button>)}</nav><div className={styles.clubCard}><div className={styles.crest}>A</div><div><b>Aurora FC</b><small>Liga Nacional</small></div><ChevronRight size={17}/></div><button className={styles.settings}><Settings size={18}/> Configurações</button><div className={styles.manager}><CircleUserRound/><div><b>Raul Soares</b><small>Treinador principal</small></div></div></aside>
  <main className={styles.main}><header className={styles.topbar}><div className={styles.mobileBrand}>V90</div><div className={styles.season}><span>Temporada 2026</span><b>{world.day} SET • QUINTA</b></div><div className={styles.topActions}><button aria-label="Mensagens"><MessageSquareText size={19}/><i/></button><button aria-label="Notificações"><Bell size={19}/><i/></button><button className={styles.advance} onClick={handleAdvance}>AVANÇAR <Play size={15} fill="currentColor"/></button></div></header>
  {notice&&<div className={styles.toast}><Zap size={17}/>{notice}</div>}
  <section className={styles.content}><div className={styles.welcome}><div><p>QUINTA-FEIRA, {world.day} DE SETEMBRO</p><h1>{active==="Visão geral"?"Bom dia, Raul.":active}</h1><span>{active==="Visão geral"?"O elenco se reapresenta às 09:00. Há 3 assuntos esperando sua decisão.":"Temporada 2026 • Aurora FC"}</span></div><button><ClipboardList size={17}/> Ver agenda do dia</button></div>
  {active==="Elenco"?<SquadView club={league.clubs[0]}/>:active==="Classificação"?<TableView clubs={league.clubs} standings={sortedStandings(league)}/>:active!=="Visão geral"?<ComingSoon title={active}/>:<>
  <div className={styles.kpis}><Metric label="POSIÇÃO" value="4º" detail="32 pontos" icon={<Trophy/>} tone="green" trend="↑ 2"/><Metric label="MORAL DO ELENCO" value={`${squadMorale}%`} detail="Ambiente positivo" icon={<Users/>} tone="blue" trend="↑ 4"/><Metric label="DIRETORIA" value="Seguro" detail="Confiança: 74%" icon={<Shield/>} tone="gold"/><Metric label="FORMA RECENTE" value="" detail="Últimos 5 jogos" icon={<BarChart3/>} tone="purple" hasForm/></div>
  <div className={styles.grid}><div className={styles.leftCol}><section className={`${styles.card} ${styles.nextMatch}`}><div className={styles.cardHead}><div><span className={styles.liveDot}/> PRÓXIMA PARTIDA</div><button>Ver detalhes <ChevronRight size={15}/></button></div><div className={styles.competition}>LIGA NACIONAL • RODADA 16 <b>AMANHÃ • 20:30</b></div><div className={styles.versus}><div><div className={`${styles.bigCrest} ${styles.aurora}`}>A</div><b>Aurora FC</b><small>4º lugar</small></div><div className={styles.vs}><strong>VS</strong><span>Estádio do Farol</span><small>Casa • 21°C</small></div><div><div className={`${styles.bigCrest} ${styles.ferro}`}>F</div><b>Ferroviário Azul</b><small>9º lugar</small></div></div><div className={styles.matchFooter}><span><Shirt size={16}/> Escalação não confirmada</span><button>PREPARAR PARTIDA <ChevronRight size={16}/></button></div></section>
  <section className={styles.card}><div className={styles.cardHead}><div>AGENDA</div><button>Calendário completo <ChevronRight size={15}/></button></div><div className={styles.fixtures}>{fixtures.map((f,i)=><div className={styles.fixture} key={f.date}><div className={styles.dateBox}><b>{f.date.split(" ")[0]}</b><span>{f.date.split(" ")[1]}</span></div><div className={styles.fixtureInfo}><b>{f.home} <span>×</span> {f.away}</b><small>{f.venue} • Liga Nacional</small></div><em className={i===0?styles.nextTag:""}>{f.tag}</em></div>)}</div></section></div>
  <div className={styles.rightCol}><section className={`${styles.card} ${styles.inboxCard}`}><div className={styles.cardHead}><div>PRECISA DA SUA ATENÇÃO <i>3</i></div><button>Ver inbox <ChevronRight size={15}/></button></div><InboxItem urgent icon="JP" title="João Pedro quer conversar" text="O atacante está insatisfeito com o tempo no banco." time="12 min"/><InboxItem icon="MR" title="Empresário pede reunião" text="Marcelo Reis quer discutir o futuro de seu cliente." time="1 h"/><InboxItem icon="CE" title="Coletiva pré-jogo" text="A imprensa aguarda sua participação antes da partida." time="2 h"/></section>
  <section className={styles.card}><div className={styles.cardHead}><div>ÚLTIMAS NOTÍCIAS</div><button>Ver todas <ChevronRight size={15}/></button></div><article className={styles.featureNews}><div><span>FUTEBOL AGORA</span><b>Aurora embala e já mira o G-3 da Liga Nacional</b><small>Há 38 min • 24 comentários</small></div></article><News initials="MC" source="Mercado FC" text="Clubes monitoram jovem destaque do Aurora" time="1 h"/><News initials="AB" source="Arquibancada" text="Torcida aprova mudanças no meio-campo" time="3 h"/></section></div></div></>}</section></main>
  <nav className={styles.mobileNav}>{NAV.slice(0,5).map(([label,Icon])=><button key={label} onClick={()=>setActive(label)} className={active===label?styles.mobileActive:""}><Icon size={20}/><span>{label.split(" ")[0]}</span></button>)}</nav>
 </div>
}
function Metric({label,value,detail,icon,tone,trend,hasForm}:{label:string;value:string;detail:string;icon:React.ReactNode;tone:string;trend?:string;hasForm?:boolean}){return <div className={styles.metric}><div className={`${styles.metricIcon} ${styles[tone]}`}>{icon}</div><div><span>{label}</span>{hasForm?<div className={styles.form}>{form.map((x,i)=><b key={i} className={x==="V"?styles.win:x==="D"?styles.loss:styles.draw}>{x}</b>)}</div>:<strong>{value}</strong>}<small>{detail}</small></div>{trend&&<em>{trend}</em>}</div>}
function InboxItem({icon,title,text,time,urgent}:{icon:string;title:string;text:string;time:string;urgent?:boolean}){return <button className={styles.inboxItem}><span className={urgent?styles.urgentAvatar:""}>{icon}</span><div><b>{title}</b><p>{text}</p><small>{time}{urgent&&" • Decisão necessária"}</small></div><ChevronRight size={17}/></button>}
function News({initials,source,text,time}:{initials:string;source:string;text:string;time:string}){return <div className={styles.newsLine}><span>{initials}</span><div><b>{source}</b><p>{text}</p></div><small>{time}</small></div>}
function SquadView({club}:{club:LeagueClub}){return <section className={`${styles.card} ${styles.dataCard}`}><div className={styles.cardHead}><div>30 JOGADORES</div><button>Overall médio: {Math.round(club.players.reduce((s,p)=>s+p.overall,0)/club.players.length)}</button></div><div className={styles.tableScroll}><table className={styles.dataTable}><thead><tr><th>Jogador</th><th>Pos.</th><th>Idade</th><th>OVR</th><th>Condição</th><th>Moral</th><th>Forma</th><th>G</th><th>A</th><th>Status</th></tr></thead><tbody>{club.players.map(p=><tr key={p.id}><td><b>{p.name}</b></td><td><span className={styles.position}>{p.position}</span></td><td>{p.age}</td><td><strong>{p.overall}</strong></td><td><Progress value={p.condition}/></td><td><Progress value={p.morale}/></td><td>{p.form.toFixed(1)}</td><td>{p.goals}</td><td>{p.assists}</td><td><em>{p.status}</em></td></tr>)}</tbody></table></div></section>}
function TableView({clubs,standings}:{clubs:LeagueClub[];standings:LeagueStanding[]}){return <section className={`${styles.card} ${styles.dataCard}`}><div className={styles.cardHead}><div>LIGA NACIONAL</div><button>38 rodadas • pontos corridos</button></div><div className={styles.tableScroll}><table className={styles.dataTable}><thead><tr><th>#</th><th>Clube</th><th>J</th><th>V</th><th>E</th><th>D</th><th>GP</th><th>GC</th><th>SG</th><th>PTS</th></tr></thead><tbody>{standings.map((s,i)=>{const club=clubs.find(c=>c.id===s.clubId)!;return <tr key={s.clubId}><td><b>{i+1}</b></td><td><span className={styles.clubName}><i style={{background:club.color}}/>{club.name}</span></td><td>{s.played}</td><td>{s.won}</td><td>{s.drawn}</td><td>{s.lost}</td><td>{s.goalsFor}</td><td>{s.goalsAgainst}</td><td>{s.goalsFor-s.goalsAgainst}</td><td><strong>{s.points}</strong></td></tr>})}</tbody></table></div></section>}
function Progress({value}:{value:number}){return <span className={styles.progress}><i style={{width:`${value}%`}}/><small>{value}%</small></span>}
function ComingSoon({title}:{title:string}){return <section className={`${styles.card} ${styles.coming}`}><Zap/><h2>{title}</h2><p>Este módulo já está previsto no backlog e será conectado aos sistemas da engine nas próximas entregas.</p></section>}
