"use client";

import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import { Bell, BriefcaseBusiness, CalendarDays, ChevronRight, CircleUserRound, Home, LayoutGrid, MessageSquareText, Play, RotateCcw, Settings, Trophy, Users, Zap } from "lucide-react";
import styles from "./page.module.css";
import seasonStyles from "./season.module.css";
import LiveMatchView from "./live-match-view";
import DressingRoomView from "./dressing-room-view";
import WorldInboxView from "./world-view";
import MarketView from "./market-view";
import TacticsSetupView from "./tactics-setup-view";
import StatisticsView from "./statistics-view";
import MediaCenterView from "./media-center-view";
import CareerView from "./career-view";
import PlayerManagementView from "./player-management-view";
import ClubManagementView from "./club-management-view";
import MainMenu from "./main-menu";
import FootballWorldView from "./football-world-view";
import AdvancedClubView from "./advanced-club-view";
import SeasonCalendarView from "./season-calendar-view";
import NationalTeamView from "./national-team-view";
import NewsCenterView from "./news-center-view";
import GameSettingsView from "./game-settings-view";
import { AdvanceDaysOverlay, PostMatchRoundView } from "./matchday-flow-ui";
import { buildParallelRoundMatches } from "./matchday-context";
import { DataHubDecisionStrip, FM_MOBILE_PRIMARY, FmContextBar, FmMobileMenu, FmSidebarNav, FmSpecialView, ManagerPortal } from "./fm-experience";
import { professionalCompetitionById, type ProfessionalCompetitionId } from "@/data/brazil-2026/competitions";
import { leagueClubIdForTransfermarkt } from "@/game-engine/new-game";
import { activeSaveId, createSaveSlot, migrateLegacySeason, saveToSlot, saveToSlotAsync, type SaveSlot } from "@/game-engine/save-slots";
import { useCareerAutosave } from "./use-career-autosave";
import { recoverOfflineSaves, requestPersistentStorage } from "@/game-engine/offline-save";
import { sortedStandings, type LeagueClub, type LeagueStanding } from "@/game-engine/league";
import { DEFAULT_TACTIC, type MatchResult, type MatchTactic } from "@/game-engine/match";
import { createLiveMatch, liveMatchResult, type LiveMatchState } from "@/game-engine/live-match";
import { tacticForClub } from "@/game-engine/club-ai";
import { talkToPlayer, type ConversationAction } from "@/game-engine/people";
import { pendingWorldEvents } from "@/game-engine/world-events";
import { pendingMediaSessions } from "@/game-engine/media-world";
import type { TrainingPlan } from "@/game-engine/training";
import { workloadAdvice } from "@/game-engine/workload";
import { userWorldCompetitionMatches } from "@/game-engine/world-competitions";
import type { GamePreferences } from "@/game-engine/game-preferences";
import { advanceCalendarDay, applyForNationalTeam, createSeason, getCupMatchContext, getCurrentUserFixture, getSelectedClub, getTodayUserCupMatch, getTodayUserFixture, getUserFixtures, hydrateSeasonState, matchdaySelectionReadyForMatch, playCurrentCupMatch, playCurrentRound, playTodayNationalMatch, resignNationalTeam, delegateMediaSessionToAssistant, applyConfiguredMediaDelegation, resolveMediaSessionText, resolveSeasonWorldChoice, setMatchdayRole, setTrainingPlan, updateGamePreferences, startNextSeason, toggleLineupPlayer, toggleNationalSelection, toggleNationalStartingXI, worldMatchEligiblePlayerIds, worldMatchEligibilityReasons, worldMatchGovernanceSummary, worldMatchdayRules, type MatchdayRole, type SeasonState } from "@/game-engine/season";

const sleep=(ms:number)=>new Promise<void>(resolve=>window.setTimeout(resolve,ms));
const MOBILE_ICONS:Record<(typeof FM_MOBILE_PRIMARY)[number],typeof Home>={"Visão geral":Home,"Elenco":Users,"Táticas":LayoutGrid,"Calendário":CalendarDays};

export default function Dashboard(){
  const [screen,setScreen]=useState<"menu"|"game">("menu"),[saveId,setSaveId]=useState<string|null>(null),[saveRecovery,setSaveRecovery]=useState(0),[season,setSeason]=useState<SeasonState>(()=>createSeason("vestiario-90",2026)),[active,setActive]=useState("Visão geral"),[notice,setNotice]=useState(""),[tactic,setTactic]=useState<MatchTactic>(DEFAULT_TACTIC),[match,setMatch]=useState<MatchResult|null>(null),[liveMatch,setLiveMatch]=useState<LiveMatchState|null>(null),[activeCupMatchId,setActiveCupMatchId]=useState<string|null>(null),[moreOpen,setMoreOpen]=useState(false),[advancing,setAdvancing]=useState(false),[advanceStatus,setAdvanceStatus]=useState({date:"",reason:"",news:[] as SeasonState["livingWorld"]["news"]});
  const navigationReady=useRef(false),lastNavigationKey=useRef("");
  useEffect(()=>{void (async()=>{await requestPersistentStorage();await recoverOfflineSaves();migrateLegacySeason();setSaveRecovery(v=>v+1)})()},[]);
  useCareerAutosave(saveId,season);
  useEffect(()=>{const key=`${screen}:${active}`;if(!navigationReady.current){navigationReady.current=true;lastNavigationKey.current=key;window.history.replaceState({...window.history.state,v90:true,screen,active},"");return}if(lastNavigationKey.current===key)return;lastNavigationKey.current=key;window.history.pushState({v90:true,screen,active},"")},[screen,active]);
  useEffect(()=>{const onPopState=(event:PopStateEvent)=>{const state=event.state as {v90?:boolean;screen?:"menu"|"game";active?:string}|null;if(!state?.v90||!state.screen)return;const nextActive=state.active??"Visão geral";lastNavigationKey.current=`${state.screen}:${nextActive}`;setMoreOpen(false);setMatch(null);if(!liveMatch)setActiveCupMatchId(null);setScreen(state.screen);setActive(nextActive)};window.addEventListener("popstate",onPopState);return()=>window.removeEventListener("popstate",onPopState)},[liveMatch]);

  const league=season.league,competition=professionalCompetitionById(season.competitionId??league.competitionId??"BRA1"),totalRounds=league.totalRounds??Math.max(...league.fixtures.map(f=>f.round),38),todayFixture=getTodayUserFixture(season),todayCup=getTodayUserCupMatch(season),club=getSelectedClub(season),employed=season.career.status==="Empregado",standings=sortedStandings(league),currentFixture=getCurrentUserFixture(season),cupContext=(todayCup?getCupMatchContext(season,todayCup.match.id):activeCupMatchId?getCupMatchContext(season,activeCupMatchId):undefined),matchCompetitionName=cupContext?.tournament.definition.shortName??competition.name,opponent=cupContext?(cupContext.userSide==="home"?cupContext.away:cupContext.home):currentFixture?league.clubs.find(c=>c.id===(currentFixture.homeClubId===club.id?currentFixture.awayClubId:currentFixture.homeClubId)):undefined,pendingEvents=pendingWorldEvents(season.livingWorld),unreadEvents=season.livingWorld.inbox.filter(event=>event.unread&&!event.resolved).length,pendingMedia=pendingMediaSessions(season.mediaWorld,season.competitionId),latestNews=season.livingWorld.news.slice(0,6);
  const nextClubCommitment=(()=>{const leagueItems=getUserFixtures(season).filter(f=>!f.played&&Boolean(f.date)&&f.date!>=season.currentDate).map(f=>{const opponentId=f.homeClubId===club.id?f.awayClubId:f.homeClubId;return{date:f.date!,opponent:league.clubs.find(c=>c.id===opponentId)?.name??"Adversário",competition:competition.shortName??competition.name}}),cupItems=userWorldCompetitionMatches(season.worldCompetitions,club.id).filter(({match})=>!match.played&&match.date>=season.currentDate).map(({tournament,match})=>({date:match.date,opponent:match.home.activeClubId===club.id?match.away.name:match.home.name,competition:tournament.definition.shortName}));return[...leagueItems,...cupItems].sort((a,b)=>a.date.localeCompare(b.date))[0]})();
  const activeLeagueFixtureId=activeCupMatchId?undefined:(todayFixture?.id??currentFixture?.id),parallelMatches=liveMatch&&activeLeagueFixtureId?buildParallelRoundMatches(season,activeLeagueFixtureId):[],socialFeed=(season.mediaWorld.trends??[]).slice(0,5).map(item=>({id:item.id,platform:item.platform,tag:item.tag,headline:item.headline})),completedRound=season.lastUserMatch?league.fixtures.find(f=>f.id===season.lastUserMatch?.fixtureId)?.round:undefined,completedRoundFixtures=completedRound?league.fixtures.filter(f=>f.round===completedRound):[];

  function navigate(label:string){setActive(label);setMatch(null);setMoreOpen(false)}
  function flash(message:string){setNotice(message);window.setTimeout(()=>setNotice(""),3600)}
  function persist(next:SeasonState){setSeason(next);const id=saveId??activeSaveId();if(id&&next.preferences.general.autoSave){const saved=saveToSlot(id,next);if(saved&&!saveId)setSaveId(id);if(!saved)flash("Falha no autosave. A carreira continua aberta, mas use Salvar agora antes de fechar o app.")}}
  function handleLoad(slot:SaveSlot){const next=hydrateSeasonState(slot.state);setSaveId(slot.meta.id);setSeason(next);setScreen("game");setActive(next.preferences.general.landingScreen);setMatch(null);setLiveMatch(null);setTactic(DEFAULT_TACTIC)}
  function handleStart(competitionId:ProfessionalCompetitionId,clubTransfermarktId:number,saveName?:string){const clubId=leagueClubIdForTransfermarkt(competitionId,clubTransfermarktId),next=createSeason(`career-${Date.now()}-${clubTransfermarktId}`,2026,clubId,competitionId),meta=createSaveSlot(next,saveName);setSaveId(meta?.id??null);setSeason(next);setScreen("game");setActive("Visão geral");setMatch(null);setLiveMatch(null);setTactic(DEFAULT_TACTIC)}
  async function handleAdvance(){if(advancing)return;if(!employed){handleCareerAdvanceRound();return}setAdvancing(true);let cursor=season,lastReason="Processando calendário...";try{for(let step=0;step<45;step++){const result=advanceCalendarDay(cursor);cursor=result.state;lastReason=result.reason;setSeason(cursor);setAdvanceStatus({date:cursor.currentDate,reason:result.reason,news:cursor.livingWorld.news.slice(0,3)});await sleep(step===0?240:320);if(!result.route)continue;persist(cursor);const prefs=cursor.preferences;if(result.route==="matchday")setActive("Táticas");else if(result.route==="club"&&prefs.general.autoOpenDecisions)setActive("Diretoria");else if(result.route==="media"&&prefs.general.autoOpenPressConferences)setActive("Mídia & Redes");else if(result.route==="media"&&(getTodayUserFixture(cursor)||getTodayUserCupMatch(cursor)))setActive("Táticas");else if(result.route==="national")setActive("Seleção");else if(result.route==="inbox"&&prefs.general.autoOpenDecisions)setActive("Caixa de entrada");flash(`${formatDate(cursor.currentDate)} • ${result.reason}`);return}persist(cursor);flash(`${formatDate(cursor.currentDate)} • ${lastReason}`)}finally{setAdvancing(false)}}
  function handleCareerAdvanceRound(){if(season.completed){handleNextSeason();return}const next=playCurrentRound(season);persist(next);flash(`Rodada ${Math.min(totalRounds,next.currentRound-1)} simulada • estatísticas e evolução atualizadas`)}
  function handleToggleLineup(playerId:string){persist(toggleLineupPlayer(season,playerId))}
  function handleMatchdayRole(playerId:string,role:MatchdayRole){persist(setMatchdayRole(season,playerId,role))}
  function handleApplyMatchdaySelection(lineupIds:string[],benchIds:string[]){let next=season;for(const player of club.players)next=setMatchdayRole(next,player.id,"out");for(const id of lineupIds)next=setMatchdayRole(next,id,"starter");for(const id of benchIds)next=setMatchdayRole(next,id,"bench");persist(next)}
  function handleTrainingPlan(plan:TrainingPlan){persist(setTrainingPlan(season,plan));flash(`Plano de treino: ${plan}. A comissão técnica executará a diretriz nos próximos dias.`)}
  function handleConversation(playerId:string,action:ConversationAction){const result=talkToPlayer(season,playerId,action);persist(result.state);flash(result.message)}
  function handleWorldChoice(eventId:string,choiceId:string){const result=resolveSeasonWorldChoice(season,eventId,choiceId);persist(result.state);flash(result.message)}
  function handleMediaText(sessionId:string,text:string){const result=resolveMediaSessionText(season,sessionId,text);persist(result.state);flash(result.message)}
  function handleMediaDelegate(sessionId:string){const result=delegateMediaSessionToAssistant(season,sessionId);persist(result.state);flash(result.message)}
  function handlePreferencesChange(preferences:GamePreferences){const next=updateGamePreferences(season,preferences);setSeason(next);if(saveId)saveToSlot(saveId,next);flash("Configurações desta carreira atualizadas.")}
  async function handleSaveNow(){if(!saveId){flash("Este jogo ainda não possui um slot de save.");return}flash("Salvando carreira...");const result=await saveToSlotAsync(saveId,season);flash(result.ok?`Carreira salva e verificada • ${result.durable==="indexeddb"?"armazenamento durável":"cópia local"}`:`Falha ao confirmar o save: ${result.error??"erro desconhecido"}`)}
  function handleNationalApply(teamId:string){const result=applyForNationalTeam(season,teamId);persist(result.state);flash(result.message)}
  function handleNationalToggle(playerId:string){const result=toggleNationalSelection(season,playerId);persist(result.state);flash(result.message)}
  function handleNationalLineup(playerId:string){const result=toggleNationalStartingXI(season,playerId);persist(result.state);flash(result.message)}
  function handleNationalPlay(){const result=playTodayNationalMatch(season);persist(result.state);setActive("Mídia & Redes");flash(result.message)}
  function handleNationalResign(){const result=resignNationalTeam(season);persist(result.state);flash(result.message)}

  function handlePlay(){if(!employed){flash("Você precisa assumir um clube antes de voltar ao banco de reservas.");return}const rule=worldMatchdayRules(season,todayCup?.match.id);if(!matchdaySelectionReadyForMatch(season,todayCup?.match.id)){flash(`Complete a convocação: 11 titulares e o banco permitido (${rule.benchSize}).`);return}const cup=todayCup?getCupMatchContext(season,todayCup.match.id):undefined;if(!cup&&!currentFixture){flash("Não há partida pendente.");return}if(!cup&&!todayFixture){flash(`A partida está marcada para ${formatDate(currentFixture?.date??season.currentDate)}. Avance os dias até o dia do jogo.`);return}const home=cup?.home??league.clubs.find(c=>c.id===currentFixture?.homeClubId),away=cup?.away??league.clubs.find(c=>c.id===currentFixture?.awayClubId);if(!home||!away)return;const userSide=cup?.userSide??(currentFixture?.homeClubId===club.id?"home":"away"),matchKey=cup?.match.id??currentFixture!.id,opponentClub=userSide==="home"?away:home,opponentTactic=opponentClub.id.startsWith("virtual-")?DEFAULT_TACTIC:tacticForClub(season.clubAi,opponentClub.id),matchRules=worldMatchdayRules(season,cup?.match.id),session=createLiveMatch(home,away,`${season.baseSeed}:${season.year}:${matchKey}:live`,userSide,season.lineupIds,tactic,season.benchIds,matchRules.benchSize,matchRules.maxSubstitutions,opponentTactic);setActiveCupMatchId(cup?.match.id??null);setMatch(null);setLiveMatch(session)}
  function handleLiveChange(next:LiveMatchState){setLiveMatch(next);setTactic(next.userSide==="home"?next.homeTactic:next.awayTactic)}
  function handleLiveFinish(session:LiveMatchState){const result=liveMatchResult(session);if(!result)return;const participants=session.usedPlayerIds.filter(id=>club.players.some(p=>p.id===id));let next=activeCupMatchId?playCurrentCupMatch(season,activeCupMatchId,result,participants):playCurrentRound(season,tactic,result,participants);next=applyConfiguredMediaDelegation(next);persist(next);setLiveMatch(null);setMatch(result)}
  function handleNextSeason(){const next=startNextSeason(season);persist(next);setMatch(null);setLiveMatch(null);setTactic(DEFAULT_TACTIC);flash(`Temporada ${next.year} iniciada. Idade, potencial e overalls foram recalibrados.`)}

  const persistedCupContext=activeCupMatchId?getCupMatchContext(season,activeCupMatchId):undefined,matchHome=persistedCupContext?.home??(season.lastUserMatch?league.clubs.find(c=>c.id===season.lastUserMatch?.homeClubId):undefined),matchAway=persistedCupContext?.away??(season.lastUserMatch?league.clubs.find(c=>c.id===season.lastUserMatch?.awayClubId):undefined),liveHome=persistedCupContext?.home??(currentFixture?league.clubs.find(c=>c.id===currentFixture.homeClubId):undefined),liveAway=persistedCupContext?.away??(currentFixture?league.clubs.find(c=>c.id===currentFixture.awayClubId):undefined);
  if(screen==="menu")return <MainMenu key={saveRecovery} onLoad={handleLoad} onStart={handleStart}/>;

  const special=<FmSpecialView active={active} season={season} onNavigate={navigate} onPreferencesChange={handlePreferencesChange}/>;
  return <div className={styles.shell}>
    <aside className={styles.sidebar}><div className={styles.brand}><span>V90</span><div><b>VESTIÁRIO</b><small>90</small></div></div><nav><FmSidebarNav active={active} onNavigate={navigate} pendingEvents={pendingEvents.length} pendingMedia={pendingMedia.length}/></nav><button className={styles.clubCard} onClick={()=>navigate("Clube")}>{employed?<ClubLogo club={club} size={38}/>:<BriefcaseBusiness size={28}/>}<div><b>{employed?club.name:"Sem clube"}</b><small>{employed?`${competition.name} • ${season.year}`:"Disponível no mercado"}</small></div><ChevronRight size={17}/></button><button className={styles.settings} onClick={()=>setScreen("menu")}><Settings size={18}/> Menu principal</button><div className={styles.manager}><CircleUserRound/><div><b>Raul Soares</b><small>{employed?"Treinador principal":"Sem clube • mercado aberto"}</small></div></div></aside>
    <main className={styles.main}>
      <header className={styles.topbar}><div className={styles.mobileBrand}>V90</div><div className={styles.season}><span>{employed?competition.name:"Mercado de Treinadores"} • Temporada {season.year}</span><b>{season.completed?"TEMPORADA ENCERRADA":`RODADA ${season.currentRound} DE ${totalRounds}`} • {formatDate(season.currentDate)}</b></div><div className={styles.headerSchedule}><div><CalendarDays size={16}/><span><small>DATA DO SAVE</small><b>{formatDate(season.currentDate)}</b></span></div><div className={styles.nextCommitment}><Trophy size={16}/><span><small>PRÓXIMO COMPROMISSO</small><b>{nextClubCommitment?`${nextClubCommitment.opponent} • ${nextClubCommitment.competition}`:"Sem jogo agendado"}</b></span></div></div><div className={styles.topActions}><button aria-label="Mensagens" onClick={()=>navigate("Caixa de entrada")}><MessageSquareText size={19}/>{unreadEvents>0&&<i/>}</button><button aria-label="Notícias" onClick={()=>navigate("Notícias")}><Bell size={19}/></button><button className={styles.advance} disabled={advancing} onClick={()=>void handleAdvance()}>{advancing?"AVANÇANDO...":employed?"AVANÇAR":"AVANÇAR RODADA"} <Play size={15} fill="currentColor"/></button></div></header>{notice&&<div className={styles.toast}><Zap size={17}/>{notice}</div>}
      {advancing&&<AdvanceDaysOverlay date={formatDate(advanceStatus.date||season.currentDate)} reason={advanceStatus.reason} news={advanceStatus.news}/>}      
      <section className={styles.content}>
        <FmContextBar season={season} active={active} onNavigate={navigate}/>
        {active!=="Visão geral"&&<div className={styles.welcome}><div><p>{`V90 • ${competition.name.toUpperCase()}`}</p><h1>{active}</h1><span>{`Temporada ${season.year} • ${employed?club.name:"Sem clube"}`}</span></div><button onClick={()=>navigate("Calendário")}><CalendarDays size={17}/> Ver calendário</button></div>}
        {special?special:
        active==="Elenco"?<PlayerManagementView season={season} onToggleLineup={handleToggleLineup} onResult={({state:next,message})=>{persist(next);flash(message)}}/>:
        active==="Clube"?<ClubManagementView season={season} onOpenInbox={()=>navigate("Caixa de entrada")} onResult={({state:next,message})=>{persist(next);flash(message)}}/>:
        active==="Vestiário"?<DressingRoomView season={season} onConversation={handleConversation}/>:
        active==="Caixa de entrada"?<WorldInboxView world={season.livingWorld} club={club} onResolve={handleWorldChoice} onNavigate={navigate}/>:
        active==="Notícias"?<NewsCenterView season={season}/>:
        active==="Carreira"?<CareerView season={season} onOpenInbox={()=>navigate("Caixa de entrada")} onAdvanceRound={handleCareerAdvanceRound}/>:
        active==="Mercado"?<MarketView season={season} onResult={({state:next,message})=>{persist(next);flash(message)}}/>:
        active==="Seleção"?<NationalTeamView season={season} onApply={handleNationalApply} onToggle={handleNationalToggle} onLineup={handleNationalLineup} onPlay={handleNationalPlay} onResign={handleNationalResign}/>:
        active==="Mundo"?<FootballWorldView season={season}/>:
        active==="Gestão & Legado"?<AdvancedClubView season={season} onOpenClub={()=>navigate("Clube")}/>:
        active==="Central de Dados"?<><DataHubDecisionStrip season={season} onNavigate={navigate}/><StatisticsView season={season}/></>:
        active==="Configurações"?<GameSettingsView preferences={season.preferences} onChange={handlePreferencesChange} onSaveNow={()=>void handleSaveNow()}/>:
        active==="Mídia & Redes"?<MediaCenterView season={season} onAnswer={handleMediaText} onDelegate={handleMediaDelegate}/>:
        active==="Táticas"?(liveMatch&&liveHome&&liveAway?<LiveMatchView session={liveMatch} home={liveHome} away={liveAway} defaultSpeed={season.preferences.match.defaultSpeed} assistantTeamTalks={season.preferences.responsibilities.teamTalks==="Adjunto"} showStaffAdvice={season.preferences.match.showStaffAdvice} parallelMatches={parallelMatches} news={latestNews} social={socialFeed} onChange={handleLiveChange} onFinish={handleLiveFinish}/>:match&&matchHome&&matchAway?<PostMatchRoundView home={matchHome} away={matchAway} result={match} roundFixtures={completedRoundFixtures} clubs={league.clubs} standings={standings} selectedClubId={club.id} news={latestNews} onContinue={()=>{setMatch(null);setActiveCupMatchId(null);navigate(pendingMediaSessions(season.mediaWorld,season.competitionId).some(s=>s.format==="Coletiva pós-jogo"&&s.status==="Aberta")?"Mídia & Redes":"Visão geral")}}/>:season.completed?<SeasonEnd season={season} standings={standings} clubs={league.clubs} onNext={handleNextSeason}/>:opponent?<TacticsView club={club} opponent={opponent} isHome={cupContext?cupContext.userSide==="home":currentFixture?.homeClubId===club.id} competitionName={matchCompetitionName} tactic={tactic} onChange={setTactic} lineupIds={season.lineupIds} benchIds={season.benchIds} benchSize={worldMatchdayRules(season,cupContext?.match.id).benchSize} eligiblePlayerIds={cupContext?worldMatchEligiblePlayerIds(season,cupContext.match.id):undefined} availabilityReasons={cupContext?worldMatchEligibilityReasons(season,cupContext.match.id):undefined} governance={cupContext?worldMatchGovernanceSummary(season,cupContext.match.id):undefined} showStaffAdvice={season.preferences.match.showStaffAdvice} workload={workloadAdvice(season,season.currentDate,Boolean(cupContext&&cupContext.tournament.definition.kind==="Continental"&&cupContext.userSide==="away"))} onSetRole={handleMatchdayRole} onApplySelection={handleApplyMatchdaySelection} trainingPlan={season.trainingPlan} onTrainingPlanChange={handleTrainingPlan} onPlay={handlePlay}/>:<ComingSoon title="Partida"/>):
        active==="Classificação"?<TableView clubs={league.clubs} standings={standings} selectedClubId={club.id} competitionName={competition.name} totalRounds={totalRounds}/>:
        active==="Calendário"?<SeasonCalendarView season={season}/>:
        active!=="Visão geral"?<ComingSoon title={active}/>:
        !employed?<CareerView season={season} onOpenInbox={()=>navigate("Caixa de entrada")} onAdvanceRound={handleCareerAdvanceRound}/>:
        <ManagerPortal season={season} onNavigate={navigate}/>}
      </section>
    </main>
    <nav className={styles.mobileNav}>{FM_MOBILE_PRIMARY.map(label=>{const Icon=MOBILE_ICONS[label];return <button key={label} onClick={()=>navigate(label)} className={active===label?styles.mobileActive:""}><Icon size={20}/><span>{label.split(" ")[0]}</span></button>})}<button onClick={()=>setMoreOpen(value=>!value)} className={moreOpen?styles.mobileActive:""}><LayoutGrid size={20}/><span>Mais</span></button></nav>{moreOpen&&<div className={styles.mobileMenuBackdrop} onClick={()=>setMoreOpen(false)}><section className={styles.mobileMenu} onClick={event=>event.stopPropagation()}><header><div><span>NAVEGAÇÃO</span><b>Áreas do treinador</b></div><button onClick={()=>setMoreOpen(false)}>Fechar</button></header><FmMobileMenu active={active} onNavigate={navigate} pendingEvents={pendingEvents.length} pendingMedia={pendingMedia.length} onClose={()=>setMoreOpen(false)}/></section></div>}
  </div>;
}

function ClubLogo({club,size}:{club:LeagueClub;size:number}){return <span className={seasonStyles.logoWrap} style={{width:size,height:size}}><Image src={club.imageUrl} alt={`Escudo ${club.name}`} width={size} height={size} sizes={`${size}px`}/></span>}
function TableView({clubs,standings,selectedClubId,competitionName,totalRounds}:{clubs:LeagueClub[];standings:LeagueStanding[];selectedClubId:string;competitionName:string;totalRounds:number}){return <section className={`${styles.card} ${styles.dataCard}`}><div className={styles.cardHead}><div>{competitionName.toUpperCase()}</div><button>{totalRounds} rodadas</button></div><div className={styles.tableScroll}><table className={styles.dataTable}><thead><tr><th>#</th><th>Clube</th><th>J</th><th>V</th><th>E</th><th>D</th><th>GP</th><th>GC</th><th>SG</th><th>PTS</th></tr></thead><tbody>{standings.map((s,i)=>{const c=clubs.find(x=>x.id===s.clubId)!;return <tr key={s.clubId} className={s.clubId===selectedClubId?seasonStyles.myClubRow:""}><td><b>{i+1}</b></td><td><span className={styles.clubName}><i style={{background:c.color}}/>{c.name}</span></td><td>{s.played}</td><td>{s.won}</td><td>{s.drawn}</td><td>{s.lost}</td><td>{s.goalsFor}</td><td>{s.goalsAgainst}</td><td>{s.goalsFor-s.goalsAgainst}</td><td><strong>{s.points}</strong></td></tr>})}</tbody></table></div></section>}
function TacticsView({club,opponent,isHome,competitionName,showStaffAdvice,tactic,onChange,lineupIds,benchIds,benchSize,eligiblePlayerIds,availabilityReasons,governance,workload,onSetRole,onApplySelection,trainingPlan,onTrainingPlanChange,onPlay}:{club:LeagueClub;opponent:LeagueClub;isHome:boolean;competitionName:string;showStaffAdvice:boolean;tactic:MatchTactic;onChange:(t:MatchTactic)=>void;lineupIds:string[];benchIds:string[];benchSize:number;eligiblePlayerIds?:string[];availabilityReasons?:Record<string,string>;governance?:{title:string;detail:string;rule:{notes:string[]}};workload:{level:string;score:number;detail:string;rotationRecommended:boolean};onSetRole:(id:string,role:MatchdayRole)=>void;onApplySelection:(lineupIds:string[],benchIds:string[])=>void;trainingPlan:TrainingPlan;onTrainingPlanChange:(plan:TrainingPlan)=>void;onPlay:()=>void}){return <TacticsSetupView club={club} opponent={opponent} isHome={isHome} competitionName={competitionName} showStaffAdvice={showStaffAdvice} tactic={tactic} onChange={onChange} lineupIds={lineupIds} benchIds={benchIds} benchSize={benchSize} eligiblePlayerIds={eligiblePlayerIds} availabilityReasons={availabilityReasons} governance={governance} workload={workload} onSetRole={onSetRole} onApplySelection={onApplySelection} trainingPlan={trainingPlan} onTrainingPlanChange={onTrainingPlanChange} onPlay={onPlay}/>}
function SeasonEnd({season,standings,clubs,onNext}:{season:SeasonState;standings:LeagueStanding[];clubs:LeagueClub[];onNext:()=>void}){const champion=clubs.find(c=>c.id===season.championClubId),myPosition=standings.findIndex(s=>s.clubId===season.selectedClubId)+1,myStanding=standings.find(s=>s.clubId===season.selectedClubId)!;return <section className={`${styles.card} ${seasonStyles.seasonEnd}`}><Trophy/><span>TEMPORADA {season.year} CONCLUÍDA</span><h2>{champion?.name} é o campeão</h2><p>Você terminou em <b>{myPosition}º</b>, com <b>{myStanding.points} pontos</b>. Estatísticas, idade e desenvolvimento foram persistidos.</p><button onClick={onNext}><RotateCcw size={17}/> INICIAR TEMPORADA {season.year+1}</button></section>}
function formatDate(iso?:string){if(!iso)return"Data a definir";try{return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(`${iso}T12:00:00Z`))}catch{return iso}}
function ComingSoon({title}:{title:string}){return <section className={`${styles.card} ${styles.coming}`}><Zap/><h2>{title}</h2><p>Este módulo permanece no roadmap. A V90 5.0 prioriza contexto, profundidade e decisões conectadas.</p></section>}
