"use client";

import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
import { CalendarDays, ChevronDown, Eye, Flag, Globe2, History, PauseCircle, Shield, Trophy, X } from "lucide-react";
import { agendaRemainingFutureMatches, buildCalendarAgenda, compactAgendaMatches, type CalendarAgendaKind, type CalendarAgendaMatch } from "@/game-engine/calendar-agenda";
import { nationalSpectatorResult, type NationalWorldFixture } from "@/game-engine/international-calendar";
import type { SeasonState } from "@/game-engine/season";
import styles from "./season-calendar-view.module.css";

type Scope="Meus jogos"|"Todos os jogos";
type KindFilter="Tudo"|"Liga"|"Copas"|"Seleções";
type CompetitionGroup={name:string;kind:CalendarAgendaKind;matches:CalendarAgendaMatch[]};
type DateGroup={date:string;competitions:CompetitionGroup[]};

const MY_INITIAL=10;
const ALL_INITIAL=18;
const LOAD_STEP=18;
const RECENT_MATCHES=6;
const dateLabel=(iso:string)=>new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",weekday:"short",timeZone:"UTC"}).format(new Date(`${iso}T12:00:00Z`));
const longDate=(iso:string)=>new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"long",weekday:"long",timeZone:"UTC"}).format(new Date(`${iso}T12:00:00Z`));
function addDays(iso:string,days:number){const date=new Date(`${iso}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10);}
function dateTitle(iso:string,currentDate:string){if(iso===currentDate)return"Hoje";if(iso===addDays(currentDate,1))return"Amanhã";if(iso===addDays(currentDate,-1))return"Ontem";return longDate(iso);}

export default function SeasonCalendarView({season}:{season:SeasonState}){
 const[scope,setScope]=useState<Scope>("Meus jogos"),[kindFilter,setKindFilter]=useState<KindFilter>("Tudo"),[visibleCount,setVisibleCount]=useState(MY_INITIAL),[showRecent,setShowRecent]=useState(false),[watchedId,setWatchedId]=useState<string|undefined>();
 const watchKey=`v90:national-watch:${season.baseSeed}`;
 useEffect(()=>{const timer=window.setTimeout(()=>{try{setWatchedId(localStorage.getItem(watchKey)??undefined)}catch{setWatchedId(undefined)}},0);return()=>window.clearTimeout(timer)},[watchKey]);
 useEffect(()=>{setVisibleCount(scope==="Meus jogos"?MY_INITIAL:ALL_INITIAL);setShowRecent(false)},[scope,kindFilter]);
 const agenda=useMemo(()=>buildCalendarAgenda(season),[season]);
 const watchedFixture=agenda.nationalFixtures.find(fixture=>fixture.id===watchedId),watchedMatch=watchedId?agenda.allGames.find(item=>item.nationalFixtureId===watchedId):undefined;
 const scoped=useMemo(()=>{const base=scope==="Meus jogos"?[...agenda.myGames]:[...agenda.allGames];if(scope==="Meus jogos"&&watchedMatch&&!base.some(item=>item.id===watchedMatch.id))base.push(watchedMatch);return [...new Map(base.map(item=>[item.id,item])).values()].sort((a,b)=>a.date.localeCompare(b.date)||Number(Boolean(b.isUserClub))-Number(Boolean(a.isUserClub))||a.competition.localeCompare(b.competition));},[agenda.allGames,agenda.myGames,scope,watchedMatch]);
 const filtered=useMemo(()=>scoped.filter(item=>kindFilter==="Tudo"||kindFilter==="Liga"&&item.kind==="Liga"||kindFilter==="Copas"&&item.kind==="Copa"||kindFilter==="Seleções"&&item.kind==="Seleção"),[scoped,kindFilter]);
 const visible=useMemo(()=>compactAgendaMatches(filtered,season.currentDate,visibleCount,showRecent?RECENT_MATCHES:0),[filtered,season.currentDate,visibleCount,showRecent]);
 const groups=useMemo(()=>groupAgenda(visible),[visible]);
 const remaining=agendaRemainingFutureMatches(filtered,season.currentDate,visibleCount),pastCount=filtered.filter(item=>item.date<season.currentDate).length,todayCount=filtered.filter(item=>item.date===season.currentDate).length,upcomingCount=filtered.filter(item=>item.date>=season.currentDate).length;
 const nextClub=agenda.myGames.find(item=>item.isUserClub&&!item.played&&item.date>=season.currentDate),nextWindow=[...agenda.windows].filter(item=>item.endDate>=season.currentDate).sort((a,b)=>a.startDate.localeCompare(b.startDate))[0],windowActive=Boolean(nextWindow&&nextWindow.startDate<=season.currentDate&&nextWindow.endDate>=season.currentDate);
 function watch(fixture:NationalWorldFixture){const next=watchedId===fixture.id?undefined:fixture.id;setWatchedId(next);try{if(next)localStorage.setItem(watchKey,next);else localStorage.removeItem(watchKey)}catch{}}
 return <div className={styles.shell}>
  <section className={styles.hero}><div><span>AGENDA V90 • {season.year}</span><h2>Jogos perto de você, sem lista infinita</h2><p>Seu clube aparece primeiro. Liga, copas, continentais e seleções ficam na mesma agenda, com resultados, agregados e reagendamentos.</p></div><CalendarDays/></section>
  {watchedFixture&&<WatchPanel fixture={watchedFixture} season={season} onClose={()=>watch(watchedFixture)}/>} 
  <section className={styles.agendaHeader}>
   <div className={styles.scopeTabs}>{(["Meus jogos","Todos os jogos"] as Scope[]).map(item=><button key={item} className={scope===item?styles.scopeActive:""} onClick={()=>setScope(item)}>{item}</button>)}</div>
   <div className={styles.todayLine}><div><b>{todayCount?`Hoje (${todayCount} jogo${todayCount===1?"":"s"})`:"Próximos jogos"}</b><small>{dateLabel(season.currentDate)} • {upcomingCount} compromisso{upcomingCount===1?"":"s"} pela frente</small></div>{nextClub&&<span><Shield/> Próximo do seu clube: {dateLabel(nextClub.date)} • {nextClub.competition}</span>}</div>
  </section>
  <div className={styles.filters}>{(["Tudo","Liga","Copas","Seleções"] as KindFilter[]).map(item=><button key={item} className={kindFilter===item?styles.active:""} onClick={()=>setKindFilter(item)}>{item==="Seleções"?<Flag/>:item==="Copas"?<Trophy/>:item==="Liga"?<Shield/>:<Globe2/>}{item}</button>)}</div>
  {nextWindow&&<section className={`${styles.windowStrip} ${windowActive?styles.windowActive:""}`}><PauseCircle/><div><span>{windowActive?"JANELA INTERNACIONAL EM ANDAMENTO":"PRÓXIMA PAUSA INTERNACIONAL"}</span><b>{nextWindow.label} • {nextWindow.competition}</b><small>{dateLabel(nextWindow.startDate)} a {dateLabel(nextWindow.endDate)} • {nextWindow.reason}</small></div>{nextWindow.longBreak&&<em>PAUSA LONGA</em>}</section>}
  <div className={styles.agenda}>{groups.length?groups.map(group=><section key={group.date} className={styles.dayGroup}><header><div><b>{dateTitle(group.date,season.currentDate)}</b><span>{dateLabel(group.date)}</span></div><em>{group.competitions.reduce((sum,item)=>sum+item.matches.length,0)} jogo{group.competitions.reduce((sum,item)=>sum+item.matches.length,0)===1?"":"s"}</em></header><div className={styles.competitionStack}>{group.competitions.map(groupItem=><CompetitionCard key={`${group.date}-${groupItem.name}-${groupItem.kind}`} group={groupItem} season={season} watchedId={watchedId} nationalFixtures={agenda.nationalFixtures} onWatch={watch}/>)}</div></section>):<section className={styles.empty}><CalendarDays/><b>Nenhum jogo encontrado</b><p>Troque o filtro ou avance o calendário para novos compromissos aparecerem.</p></section>}</div>
  <section className={styles.loadControls}>{pastCount>0&&<button className={styles.historyButton} onClick={()=>setShowRecent(value=>!value)}><History/>{showRecent?"Ocultar resultados recentes":`Ver últimos ${Math.min(RECENT_MATCHES,pastCount)} resultados`}</button>}{remaining>0&&<button className={styles.loadMore} onClick={()=>setVisibleCount(value=>value+LOAD_STEP)}><ChevronDown/><span><b>Carregar mais jogos</b><small>{remaining} compromisso{remaining===1?" restante":"s restantes"}</small></span></button>}</section>
 </div>;
}

function CompetitionCard({group,season,watchedId,nationalFixtures,onWatch}:{group:CompetitionGroup;season:SeasonState;watchedId?:string;nationalFixtures:NationalWorldFixture[];onWatch:(fixture:NationalWorldFixture)=>void}){const stages=[...new Set(group.matches.map(item=>item.stage))];return <section className={styles.competitionCard}><header><i className={styles[group.kind.toLowerCase().replace("ç","c")]??""}>{group.kind==="Seleção"?<Flag/>:group.kind==="Liga"?<Shield/>:<Trophy/>}</i><div><b>{group.name}</b><small>{stages.slice(0,2).join(" • ")}{stages.length>2?` • +${stages.length-2} fases`:""}</small></div><em>{group.matches.length} jogo{group.matches.length===1?"":"s"}</em></header><div>{group.matches.map(item=>{const fixture=item.nationalFixtureId?nationalFixtures.find(value=>value.id===item.nationalFixtureId):undefined;return <MatchRow key={item.id} item={item} fixture={fixture} season={season} watched={Boolean(fixture&&watchedId===fixture.id)} onWatch={fixture?()=>onWatch(fixture):undefined}/>})}</div></section>}

function MatchRow({item,fixture,season,watched,onWatch}:{item:CalendarAgendaMatch;fixture?:NationalWorldFixture;season:SeasonState;watched:boolean;onWatch?:()=>void}){const details=[item.stage,item.aggregate,item.decidedByPenalties?"Decidido nos pênaltis":undefined,item.rescheduledReason?`Reagendado${item.originalDate?` de ${dateLabel(item.originalDate)}`:""}`:undefined].filter(Boolean);return <article className={`${styles.matchRow} ${item.isUserClub?styles.userMatch:""}`}><div className={`${styles.team} ${styles.homeTeam}`}><span>{item.homeName}</span><TeamMark name={item.homeName} logo={item.homeLogo}/></div><div className={styles.scoreBox}><strong>{item.score??"VS"}</strong><small className={item.date===season.currentDate&&!item.played?styles.liveStatus:""}>{item.status}</small></div><div className={`${styles.team} ${styles.awayTeam}`}><TeamMark name={item.awayName} logo={item.awayLogo}/><span>{item.awayName}</span></div><div className={styles.matchMeta}><span>{details.join(" • ")}</span>{item.rescheduledReason&&<small>{item.rescheduledReason}</small>}{fixture&&onWatch&&<button className={watched?styles.watchActive:styles.watchButton} onClick={onWatch}><Eye/>{watched?"MARCADO":fixture.date<=season.currentDate?"ACOMPANHAR":"MARCAR"}</button>}</div></article>}

function TeamMark({name,logo}:{name:string;logo?:string}){const initials=name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join("").toUpperCase();return <span className={styles.teamMark}>{logo?<Image src={logo} alt={`Escudo ${name}`} width={30} height={30} sizes="30px"/>:<b>{initials||"—"}</b>}</span>}

function groupAgenda(matches:CalendarAgendaMatch[]):DateGroup[]{const dates=new Map<string,Map<string,CompetitionGroup>>();for(const item of matches){if(!dates.has(item.date))dates.set(item.date,new Map());const byCompetition=dates.get(item.date)!,key=`${item.kind}:${item.competition}`;const existing=byCompetition.get(key);if(existing)existing.matches.push(item);else byCompetition.set(key,{name:item.competition,kind:item.kind,matches:[item]});}return[...dates.entries()].map(([date,competitions])=>({date,competitions:[...competitions.values()]}));}

function WatchPanel({fixture,season,onClose}:{fixture:NationalWorldFixture;season:SeasonState;onClose:()=>void}){const available=fixture.date<=season.currentDate,result=available?nationalSpectatorResult(fixture,season.baseSeed):undefined;return <section className={styles.watchPanel}><header><div><span>PARTIDA DE SELEÇÕES • {fixture.competition}</span><b>{fixture.homeName} × {fixture.awayName}</b><small>{dateLabel(fixture.date)} • {fixture.stage}</small></div><button onClick={onClose}><X/> Remover</button></header>{result?<><div className={styles.watchScore}><div><b>{fixture.homeName}</b><strong>{result.homeGoals}</strong></div><span>FINAL</span><div><strong>{result.awayGoals}</strong><b>{fixture.awayName}</b></div></div><div className={styles.watchStats}><span>Finalizações <b>{result.shotsHome} × {result.shotsAway}</b></span><span>Posse <b>{result.possessionHome}% × {100-result.possessionHome}%</b></span></div><div className={styles.timeline}>{result.events.map((event,index)=><article key={`${event.minute}-${index}`}><time>{event.minute}&apos;</time><i className={event.type==="goal"?styles.goalEvent:event.type==="card"?styles.cardEvent:""}/><span>{event.text}</span></article>)}</div></>:<div className={styles.watchFuture}><Eye/><div><b>Marcado para acompanhar</b><p>Este jogo acontece em {dateLabel(fixture.date)}. Quando a data chegar, o placar, a linha do tempo e as estatísticas ficam disponíveis aqui.</p></div></div>}</section>}
