"use client";
import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Eye, Flag, Globe2, PauseCircle, Shield, Trophy, X } from "lucide-react";
import { clubCommitments } from "@/game-engine/calendar-coordinator";
import { internationalWindowsForSeason, nationalSpectatorResult, worldNationalFixturesForSeason, type NationalWorldFixture } from "@/game-engine/international-calendar";
import type { SeasonState } from "@/game-engine/season";
import { worldCompetitionCalendar } from "@/game-engine/world-competitions";
import styles from "./season-calendar-view.module.css";

type Filter="Meu clube"|"Copas"|"Seleções"|"Tudo";
type CalendarItem={id:string;date:string;competition:string;stage:string;detail:string;kind:"Liga"|"Clube"|"Copa"|"Seleção"|"Pausa";status?:string;score?:string;accent?:boolean;nationalFixture?:NationalWorldFixture;rescheduled?:boolean};
const monthName=(iso:string)=>new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${iso.slice(0,7)}-15T12:00:00Z`));
const dateLabel=(iso:string)=>new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",weekday:"short",timeZone:"UTC"}).format(new Date(`${iso}T12:00:00Z`));

export default function SeasonCalendarView({season}:{season:SeasonState}){
 const[filter,setFilter]=useState<Filter>("Meu clube"),[watchedId,setWatchedId]=useState<string|undefined>(),club=season.league.clubs.find(c=>c.id===season.selectedClubId)??season.league.clubs[0],watchKey=`v90:national-watch:${season.baseSeed}`;
 useEffect(()=>{const timer=window.setTimeout(()=>{try{setWatchedId(localStorage.getItem(watchKey)??undefined)}catch{setWatchedId(undefined)}},0);return()=>window.clearTimeout(timer)},[watchKey]);
 const nationalFixtures=useMemo(()=>worldNationalFixturesForSeason(season.year,season.baseSeed),[season.year,season.baseSeed]);
 const items=useMemo(()=>{
  const commitments=clubCommitments(season);
  const clubItems:CalendarItem[]=commitments.map(item=>({id:`club-${item.kind}-${item.id}`,date:item.date,competition:item.competition,stage:item.stage,detail:`${item.isHome?club.name:item.opponentName} × ${item.isHome?item.opponentName:club.name}${item.originalDate?` • remarcado de ${dateLabel(item.originalDate)}`:""}${item.rescheduledReason?` • ${item.rescheduledReason}`:""}`,kind:item.kind==="league"?"Liga":"Clube",score:item.score,status:item.played?"Final":item.date===season.currentDate?"HOJE":item.rescheduledReason?"Reagendado":"Agendado",accent:item.date===season.currentDate,rescheduled:Boolean(item.rescheduledReason)}));
  const cupMilestones:CalendarItem[]=worldCompetitionCalendar(season.year).map((event,index)=>({id:`world-${event.competitionId}-${event.stage}-${index}-${event.date}`,date:event.date,competition:event.competition,stage:event.stage,detail:`${event.rule} • ${event.format}`,kind:"Copa",status:"Data oficial"}));
  const managedNation:CalendarItem[]=(season.nationalCareer?.fixtures??[]).map(f=>({id:`managed-national-${f.id}`,date:f.date,competition:f.competition,stage:f.stage,detail:`${f.homeName} × ${f.awayName}`,kind:"Seleção",score:f.played?`${f.homeGoals??0} × ${f.awayGoals??0}`:undefined,status:f.played?"Final":f.date===season.currentDate?"HOJE • SUA SELEÇÃO":"Agendado",accent:f.date===season.currentDate}));
  const nations:CalendarItem[]=nationalFixtures.map(fixture=>({id:`national-${fixture.id}`,date:fixture.date,competition:fixture.competition,stage:fixture.stage,detail:`${fixture.homeName} × ${fixture.awayName}`,kind:"Seleção",status:fixture.date<season.currentDate?"Resultado disponível":fixture.date===season.currentDate?"HOJE • pode acompanhar":"Agendado",accent:fixture.date===season.currentDate,nationalFixture:fixture}));
  const windows:CalendarItem[]=internationalWindowsForSeason(season.year).map(window=>({id:`window-${window.id}`,date:window.startDate,competition:window.competition,stage:window.label,detail:`${dateLabel(window.startDate)} a ${dateLabel(window.endDate)} • ${window.reason}`,kind:"Pausa",status:window.longBreak?"PAUSA LONGA DOS CLUBES":"PAUSA DOS CLUBES"}));
  return{clubItems,cupMilestones,nations,managedNation,windows};
 },[season,club.name,nationalFixtures]);
 const visible=useMemo(()=>{const userCups=items.clubItems.filter(item=>item.kind==="Clube"),source=filter==="Meu clube"?items.clubItems:filter==="Copas"?[...userCups,...items.cupMilestones]:filter==="Seleções"?[...items.managedNation,...items.nations,...items.windows]:[...items.clubItems,...items.cupMilestones,...items.managedNation,...items.nations,...items.windows];return source.sort((a,b)=>a.date.localeCompare(b.date)||a.competition.localeCompare(b.competition)||a.id.localeCompare(b.id));},[filter,items]);
 const groups=useMemo(()=>{const map=new Map<string,CalendarItem[]>();for(const item of visible){const key=item.date.slice(0,7);map.set(key,[...(map.get(key)??[]),item]);}return[...map.entries()];},[visible]);
 const clubSchedule=useMemo(()=>items.clubItems.sort((a,b)=>a.date.localeCompare(b.date)||a.competition.localeCompare(b.competition)),[items.clubItems]),todayClub=clubSchedule.filter(item=>item.date===season.currentDate),nextClub=clubSchedule.find(item=>!item.score&&item.date>=season.currentDate),watchedFixture=nationalFixtures.find(f=>f.id===watchedId),watchedToday=watchedFixture?.date===season.currentDate;
 function watch(fixture:NationalWorldFixture){const next=watchedId===fixture.id?undefined:fixture.id;setWatchedId(next);try{if(next)localStorage.setItem(watchKey,next);else localStorage.removeItem(watchKey)}catch{}}
 return <div className={styles.shell}>
  <section className={styles.hero}><div><span>CALENDÁRIO MUNDIAL • {season.year}</span><h2>Um calendário único para clube e seleções</h2><p>Liga, copas, Libertadores/Sul-Americana e janelas internacionais agora disputam as mesmas datas. Conflitos geram reagendamentos e grandes torneios de seleções podem interromper a temporada de clubes.</p></div><CalendarDays/></section>
  {watchedFixture&&<WatchPanel fixture={watchedFixture} season={season} onClose={()=>watch(watchedFixture)}/>} 
  <section className={styles.todayCard}><div className={styles.todayDate}><small>HOJE NO SAVE</small><strong>{dateLabel(season.currentDate)}</strong><span>{season.currentDate}</span></div><div className={styles.todayGames}>{todayClub.length?todayClub.map(item=><article key={`today-${item.id}`}><span>JOGO DO DIA • {item.competition}</span><h3>{item.detail.split(" • ")[0]}</h3><small>{item.stage}{item.status?` • ${item.status}`:""}</small>{item.score&&<b>{item.score}</b>}</article>):<article><span>{watchedToday?"SELEÇÃO MARCADA PARA ACOMPANHAR":"SEM JOGO DO CLUBE HOJE"}</span><h3>{watchedToday?`${watchedFixture.homeName} × ${watchedFixture.awayName}`:nextClub?`Próximo: ${nextClub.detail.split(" • ")[0]}`:"Nenhum compromisso futuro encontrado"}</h3><small>{watchedToday?`${watchedFixture.competition} • ${watchedFixture.stage}`:nextClub?`${dateLabel(nextClub.date)} • ${nextClub.competition} • ${nextClub.stage}`:"A agenda será atualizada quando novos jogos forem definidos."}</small></article>}</div></section>
  <div className={styles.filters}>{(["Meu clube","Copas","Seleções","Tudo"] as Filter[]).map(item=><button key={item} className={filter===item?styles.active:""} onClick={()=>setFilter(item)}>{item==="Seleções"?<Flag/>:item==="Copas"?<Trophy/>:item==="Tudo"?<Globe2/>:<Shield/>}{item}</button>)}</div>
  <section className={styles.summary}><div><small>HOJE NO SAVE</small><b>{dateLabel(season.currentDate)}</b></div><div><small>JOGOS DO CLUBE</small><b>{items.clubItems.length}</b></div><div><small>JANELAS INTERNACIONAIS</small><b>{items.windows.length}</b></div><div><small>JOGOS DE SELEÇÕES</small><b>{items.nations.length}</b></div></section>
  <div className={styles.months}>{groups.map(([month,events])=><section key={month} className={styles.month}><header><b>{monthName(`${month}-01`)}</b><span>{events.length} evento{events.length===1?"":"s"}</span></header><div className={styles.events}>{events.map(item=><article key={item.id} className={`${styles.event} ${item.accent?styles.today:""} ${item.rescheduled?styles.rescheduled:""}`}><time>{dateLabel(item.date)}</time><i className={styles[item.kind.toLowerCase().replace("ç","c")]??""}>{item.kind==="Seleção"?<Flag/>:item.kind==="Liga"?<Shield/>:item.kind==="Pausa"?<PauseCircle/>:<Trophy/>}</i><div className={styles.info}><span>{item.competition}</span><b>{item.stage}</b><small>{item.detail}</small></div>{item.score&&<strong>{item.score}</strong>}{item.nationalFixture&&<button className={`${styles.watchButton} ${watchedId===item.nationalFixture.id?styles.watchActive:""}`} onClick={()=>watch(item.nationalFixture!)}><Eye/>{watchedId===item.nationalFixture.id?"MARCADO":item.date<=season.currentDate?"ACOMPANHAR":"MARCAR"}</button>}<em>{item.status}</em></article>)}</div></section>)}</div>
 </div>;
}

function WatchPanel({fixture,season,onClose}:{fixture:NationalWorldFixture;season:SeasonState;onClose:()=>void}){const available=fixture.date<=season.currentDate,result=available?nationalSpectatorResult(fixture,season.baseSeed):undefined;return <section className={styles.watchPanel}><header><div><span>PARTIDA DE SELEÇÕES • {fixture.competition}</span><b>{fixture.homeName} × {fixture.awayName}</b><small>{dateLabel(fixture.date)} • {fixture.stage}</small></div><button onClick={onClose}><X/> Remover</button></header>{result?<><div className={styles.watchScore}><div><b>{fixture.homeName}</b><strong>{result.homeGoals}</strong></div><span>FINAL</span><div><strong>{result.awayGoals}</strong><b>{fixture.awayName}</b></div></div><div className={styles.watchStats}><span>Finalizações <b>{result.shotsHome} × {result.shotsAway}</b></span><span>Posse <b>{result.possessionHome}% × {100-result.possessionHome}%</b></span></div><div className={styles.timeline}>{result.events.map((event,index)=><article key={`${event.minute}-${index}`}><time>{event.minute}&apos;</time><i className={event.type==="goal"?styles.goalEvent:event.type==="card"?styles.cardEvent:""}/><span>{event.text}</span></article>)}</div></>:<div className={styles.watchFuture}><Eye/><div><b>Marcado para acompanhar</b><p>Este jogo acontece em {dateLabel(fixture.date)}. O calendário vai mantê-lo destacado; quando a data chegar, a narração, o placar e as estatísticas ficam disponíveis aqui.</p></div></div>}</section>}
