"use client";
import{Activity,Brain,ClipboardCheck,ShieldCheck,UsersRound}from"lucide-react";
import type{SeasonState}from"@/game-engine/season";
import type{MatchResult}from"@/game-engine/match";
import{opponentAnalystReport,postMatchAnalysis,staffDashboard}from"@/game-engine/staff-analytics";

export default function StaffAnalyticsPanel({season}:{season:SeasonState}){
 const club=season.league.clubs.find(c=>c.id===season.selectedClubId)!;
 const dash=staffDashboard(club),fixture=season.league.fixtures.find(f=>!f.played&&(f.homeClubId===club.id||f.awayClubId===club.id)),opponent=fixture?season.league.clubs.find(c=>c.id===(fixture.homeClubId===club.id?fixture.awayClubId:fixture.homeClubId)):undefined,pre=opponent?opponentAnalystReport(club,opponent):undefined;
 const last=(season as SeasonState&{lastUserMatch?:{result?:MatchResult;fixtureId?:string}}).lastUserMatch,fixtureLast=last?.fixtureId?season.league.fixtures.find(f=>f.id===last.fixtureId):undefined,userSide=fixtureLast?.homeClubId===club.id?"home":"away",post=last?.result?postMatchAnalysis(last.result,userSide,club):undefined;
 const card={border:"1px solid rgba(255,255,255,.1)",borderRadius:14,padding:16,background:"rgba(255,255,255,.035)"} as const;
 return <div style={{display:"grid",gap:14}}>
  <section style={card}><header style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center"}}><div><small>COMISSÃO TÉCNICA 2.0</small><h2 style={{margin:"4px 0"}}>Staff e delegação</h2></div><UsersRound/></header><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:10,marginTop:12}}>{dash.staff.map(s=><article key={s.id} style={{...card,padding:12}}><b>{s.name}</b><small style={{display:"block",opacity:.7}}>{s.role} • OVR {s.overall}</small><p style={{fontSize:12,margin:"8px 0 0"}}>Tática {s.tactical} • Julgamento {s.judging} • Motivação {s.motivation}<br/>Físico {s.fitness} • Médico {s.medical} • Negociação {s.negotiation}</p></article>)}</div><div style={{display:"flex",flexWrap:"wrap",gap:8,marginTop:12}}>{Object.entries(dash.delegation).map(([k,v])=><span key={k} style={{padding:"6px 9px",borderRadius:999,background:"rgba(255,255,255,.07)",fontSize:12}}>{k}: <b>{v}</b></span>)}</div></section>
  {pre&&<section style={card}><header style={{display:"flex",gap:8,alignItems:"center"}}><ClipboardCheck/><div><small>RELATÓRIO DO ADVERSÁRIO</small><h3 style={{margin:0}}>{opponent?.name} • confiança {pre.confidence}%</h3></div></header><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:10,marginTop:12}}><article style={card}><b>Ponto forte</b><p>{pre.strength}</p></article><article style={card}><b>Fraqueza</b><p>{pre.weakness}</p></article><article style={card}><b>Perigo</b><p>{pre.danger}</p></article><article style={card}><b>Recomendação</b><p>{pre.recommendation}</p></article></div></section>}
  {post&&<section style={card}><header style={{display:"flex",gap:8,alignItems:"center"}}><Activity/><div><small>ANÁLISE PÓS-JOGO</small><h3 style={{margin:0}}>xG {post.xgFor.toFixed(2)} – {post.xgAgainst.toFixed(2)} • confiança {post.analystConfidence}%</h3></div></header><p>{post.summary}</p><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8}}><article style={card}><Brain/><small>Zona produtiva</small><b style={{display:"block"}}>corredor {post.dominantZone}</b></article><article style={card}><ShieldCheck/><small>Zona vulnerável</small><b style={{display:"block"}}>corredor {post.vulnerableZone}</b></article><article style={card}><Activity/><small>Finalizações</small><b style={{display:"block"}}>{post.shotCountFor} – {post.shotCountAgainst}</b></article></div><div style={{position:"relative",height:230,marginTop:12,border:"1px solid rgba(255,255,255,.12)",borderRadius:12,background:"rgba(255,255,255,.025)"}}><div style={{position:"absolute",left:"50%",top:0,bottom:0,width:1,background:"rgba(255,255,255,.12)"}}/>{post.shots.slice(0,40).map((s,i)=>{const x=s.zone==="left"?22:s.zone==="right"?78:50,y=s.side==="for"?70-Math.min(45,s.xg*100):160+Math.min(45,s.xg*100);return <i key={`${s.minute}-${i}`} title={`${s.minute}' • xG ${s.xg.toFixed(2)}`} style={{position:"absolute",left:`${x}%`,top:y,width:Math.max(7,s.xg*36),height:Math.max(7,s.xg*36),borderRadius:"50%",transform:"translate(-50%,-50%)",border:"2px solid currentColor",background:s.goal?"currentColor":"transparent",opacity:.85}}/>})}</div><small style={{opacity:.65}}>Mapa de finalizações: metade superior = seu time; metade inferior = adversário. Tamanho do ponto = xG.</small></section>}
 </div>;
}
