"use client";

import Image from "next/image";
import {useMemo,useState}from"react";
import{Trophy,X}from"lucide-react";
import{BRAZIL_STATE_2026_COMPETITIONS}from"@/data/world-2026/state-competitions.generated";
import styles from"./fm-experience.module.css";

type StateEntity={type:"club"|"competition";id:string;stateCompetitionId:string};
const EVENT="v90-fm-open-entity";
function openEntity(entity:StateEntity){window.dispatchEvent(new CustomEvent(EVENT,{detail:entity}));}
const eur=(value:number|null|undefined)=>!value?"—":value>=1_000_000?`€ ${(value/1_000_000).toLocaleString("pt-BR",{maximumFractionDigits:1})} mi`:`€ ${Math.round(value/1_000).toLocaleString("pt-BR")} mil`;

export default function StateEntityProfile({entity,onClose}:{entity:StateEntity;onClose:()=>void}){
 const competition=BRAZIL_STATE_2026_COMPETITIONS.find(item=>item.id===entity.stateCompetitionId),[tab,setTab]=useState(entity.type==="club"?"Elenco":"Clubes");
 if(!competition)return <Backdrop onClose={onClose}><div className={styles.profileNarrative}><span>ESTADUAL</span><h3>Competição indisponível</h3><p>Este estadual ainda está pendente na base real.</p></div></Backdrop>;
 const club=entity.type==="club"?competition.clubs.find(item=>String(item.transfermarktId)===entity.id):undefined,tabs=club?["Elenco","Visão geral"]:["Clubes","Visão geral"];
 return <Backdrop onClose={onClose}><header className={styles.entityTop}><div>{club?<Image src={club.imageUrl||"/generic-club.svg"} alt={club.name} width={58} height={58}/>:<Trophy size={48}/>}<span><small>Brasil/{competition.state} • {competition.tier}</small><h2>{club?.name??competition.name}</h2><p>{club?`${club.players.length} jogadores no snapshot real`:`${competition.clubs.length} clubes • temporada ${competition.season}`}</p></span></div><button onClick={onClose}><X/></button></header><nav className={styles.entityTabs}>{tabs.map(item=><button key={item} className={tab===item?styles.entityTabActive:""} onClick={()=>setTab(item)}>{item}</button>)}</nav><div className={styles.entityContent}>{club?<ClubProfile club={club} competition={competition} tab={tab}/>:<CompetitionProfile competition={competition} tab={tab}/>}</div></Backdrop>;
}
function Backdrop({children,onClose}:{children:React.ReactNode;onClose:()=>void}){return <div className={styles.entityBackdrop} onClick={onClose}><section className={styles.entitySheet} onClick={event=>event.stopPropagation()}>{children}</section></div>}
function ClubProfile({club,competition,tab}:{club:(typeof BRAZIL_STATE_2026_COMPETITIONS)[number]["clubs"][number];competition:(typeof BRAZIL_STATE_2026_COMPETITIONS)[number];tab:string}){if(tab==="Elenco")return <Squad club={club}/>;return <div className={styles.entityOverview}><div className={styles.entityStats}>{[["ELENCO",String(club.players.length),"jogadores"],["VALOR",eur(club.marketValueEur),"plantel"],["ESTADO",competition.state,"federação"],["DIVISÃO",competition.tier,competition.name]].map(([label,value,detail])=><div key={label} className={styles.fmMetric}><span>{label}</span><b>{value}</b><small>{detail}</small></div>)}</div><section className={styles.profileNarrative}><span>SNAPSHOT REAL</span><h3>{club.name}</h3><p>Este elenco é independente da história de saves em andamento: ele alimenta a base real para novos saves e a consulta do Mundo.</p></section></div>}
function Squad({club}:{club:(typeof BRAZIL_STATE_2026_COMPETITIONS)[number]["clubs"][number]}){const[query,setQuery]=useState(""),[position,setPosition]=useState("TODAS"),positions=useMemo(()=>Array.from(new Set(club.players.map(player=>player.position))).sort(),[club.players]),players=useMemo(()=>{const q=query.trim().toLocaleLowerCase("pt-BR");return club.players.filter(player=>(position==="TODAS"||player.position===position)&&(!q||player.name.toLocaleLowerCase("pt-BR").includes(q))).sort((a,b)=>(b.marketValueEur??0)-(a.marketValueEur??0));},[club.players,position,query]);return <div style={{display:"flex",flexDirection:"column",gap:10}}><section style={{display:"flex",gap:7,alignItems:"center",flexWrap:"wrap",padding:10,border:"1px solid #29332f",borderRadius:11,background:"#131a18"}}><b style={{fontSize:12,color:"#f3f6f4",flex:"1 1 170px"}}>{players.length} de {club.players.length} jogadores</b><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Pesquisar jogador..." style={{height:36,minWidth:170,flex:"1 1 180px",border:"1px solid #33413b",borderRadius:8,background:"#0f1513",color:"#f3f6f4",padding:"0 10px"}}/><select value={position} onChange={event=>setPosition(event.target.value)} style={{height:36,border:"1px solid #33413b",borderRadius:8,background:"#0f1513",color:"#f3f6f4",padding:"0 8px"}}><option value="TODAS">Todas as posições</option>{positions.map(item=><option key={item}>{item}</option>)}</select></section><div className={styles.entityList}>{players.map(player=><article key={`${player.transfermarktId}-${player.name}`}><Image src={`/api/player-photo/${player.transfermarktId}`} alt={player.name} width={42} height={42} unoptimized/><span><b>{player.name}</b><small>{player.position} • {player.age} anos</small></span><strong>{eur(player.marketValueEur)}</strong></article>)}</div></div>}
function CompetitionProfile({competition,tab}:{competition:(typeof BRAZIL_STATE_2026_COMPETITIONS)[number];tab:string}){if(tab==="Clubes")return <div className={styles.entityList}>{competition.clubs.map(club=><button key={club.transfermarktId} onClick={()=>openEntity({type:"club",id:String(club.transfermarktId),stateCompetitionId:competition.id})}><Image src={club.imageUrl||"/generic-club.svg"} alt={club.name} width={34} height={34}/><span><b>{club.name}</b><small>{club.players.length} jogadores • {eur(club.marketValueEur)}</small></span><strong>{competition.state}</strong></button>)}</div>;const players=competition.clubs.reduce((sum,club)=>sum+club.players.length,0);return <div className={styles.entityStats}>{[["CLUBES",String(competition.clubs.length),"participantes"],["JOGADORES",String(players),"snapshot"],["ESTADO",competition.state,"Brasil"],["NÍVEL",competition.tier,"estadual"]].map(([label,value,detail])=><div key={label} className={styles.fmMetric}><span>{label}</span><b>{value}</b><small>{detail}</small></div>)}</div>}
