"use client";

import{useMemo,useState}from"react";
import{Activity,BarChart3,Goal,Star,TrendingDown,TrendingUp,Users}from"lucide-react";
import{sortedStandings,type LeagueClub}from"@/game-engine/league";
import{overallTrend}from"@/game-engine/development";
import type{SeasonState}from"@/game-engine/season";
import styles from"./statistics-view.module.css";

type Tab="competition"|"clubs"|"players";
export default function StatisticsView({season}:{season:SeasonState}){
 const[tab,setTab]=useState<Tab>("competition"),league=season.league,played=league.fixtures.filter(f=>f.played),standings=useMemo(()=>sortedStandings(league),[league]);
 const goals=played.reduce((sum,f)=>sum+(f.homeGoals??0)+(f.awayGoals??0),0),shots=played.reduce((sum,f)=>sum+(f.homeShots??0)+(f.awayShots??0),0),homeWins=played.filter(f=>(f.homeGoals??0)>(f.awayGoals??0)).length,draws=played.filter(f=>f.homeGoals===f.awayGoals).length,awayWins=played.length-homeWins-draws;
 const players=useMemo(()=>league.clubs.flatMap(club=>club.players.map(player=>({player,club}))),[league.clubs]);
 const topScorers=[...players].sort((a,b)=>b.player.goals-a.player.goals||b.player.assists-a.player.assists||b.player.averageRating-a.player.averageRating).slice(0,10),topRatings=[...players].filter(x=>x.player.ratedMatches>0).sort((a,b)=>b.player.averageRating-a.player.averageRating||b.player.goals-a.player.goals).slice(0,10),rising=[...players].sort((a,b)=>overallTrend(b.player)-overallTrend(a.player)||b.player.potential-a.player.potential).slice(0,8);
 const clubStats=standings.map(row=>{const club=league.clubs.find(c=>c.id===row.clubId)!,fixtures=played.filter(f=>f.homeClubId===club.id||f.awayClubId===club.id);let shotsFor=0,shotsAgainst=0,possession=0;for(const f of fixtures){const home=f.homeClubId===club.id;shotsFor+=home?(f.homeShots??0):(f.awayShots??0);shotsAgainst+=home?(f.awayShots??0):(f.homeShots??0);possession+=home?(f.possessionHome??50):100-(f.possessionHome??50);}return{club,row,shotsFor,shotsAgainst,avgPossession:fixtures.length?Math.round(possession/fixtures.length):0};});
 return <div className={styles.wrap}>
  <header className={styles.hero}><div><span>CENTRAL DE DADOS</span><h2>{league.competitionName??"Competição"}</h2><p>Resultados, desempenho coletivo e evolução individual alimentam o mundo esportivo e o desenvolvimento dos jogadores.</p></div><div className={styles.heroStat}><b>{played.length}</b><small>jogos disputados</small></div></header>
  <nav className={styles.tabs}><button className={tab==="competition"?styles.active:""} onClick={()=>setTab("competition")}><BarChart3/> Competição</button><button className={tab==="clubs"?styles.active:""} onClick={()=>setTab("clubs")}><Users/> Clubes</button><button className={tab==="players"?styles.active:""} onClick={()=>setTab("players")}><Star/> Jogadores</button></nav>
  {tab==="competition"&&<><div className={styles.metrics}><Metric icon={<Goal/>} label="GOLS" value={goals} detail={`${played.length?(goals/played.length).toFixed(2):"0.00"} por jogo`}/><Metric icon={<Activity/>} label="FINALIZAÇÕES" value={shots} detail={`${played.length?(shots/played.length).toFixed(1):"0.0"} por jogo`}/><Metric icon={<TrendingUp/>} label="VITÓRIAS CASA" value={homeWins} detail={`${played.length?Math.round(homeWins/played.length*100):0}% dos jogos`}/><Metric icon={<BarChart3/>} label="EMPATES" value={draws} detail={`${awayWins} vitórias visitantes`}/></div><div className={styles.grid}><Leaderboard title="ARTILHEIROS" rows={topScorers}/><Leaderboard title="MELHORES NOTAS" rows={topRatings}/><section className={styles.card}><header><b>EVOLUÇÃO DE OVERALL</b><small>Forma + idade + potencial</small></header>{rising.map(({player,club})=><div className={styles.trend} key={player.id}><span>{overallTrend(player)>=0?<TrendingUp/>:<TrendingDown/>}</span><div><b>{player.name}</b><small>{club.shortName} • {player.age} anos • POT {player.potential}</small></div><strong className={overallTrend(player)>=0?styles.up:styles.down}>{player.overall} {overallTrend(player)>0?`(+${overallTrend(player)})`:overallTrend(player)<0?`(${overallTrend(player)})`:"(=)"}</strong></div>)}</section></div></>}
  {tab==="clubs"&&<section className={styles.card}><header><b>ESTATÍSTICAS DOS CLUBES</b><small>Classificação + produção de jogo</small></header><div className={styles.tableScroll}><table><thead><tr><th>#</th><th>Clube</th><th>J</th><th>PTS</th><th>GP</th><th>GC</th><th>SG</th><th>Chutes</th><th>Contra</th><th>Posse</th></tr></thead><tbody>{clubStats.map(({club,row,shotsFor,shotsAgainst,avgPossession},index)=><tr key={club.id} className={club.id===season.selectedClubId?styles.mine:""}><td>{index+1}</td><td><ClubName club={club}/></td><td>{row.played}</td><td><b>{row.points}</b></td><td>{row.goalsFor}</td><td>{row.goalsAgainst}</td><td>{row.goalsFor-row.goalsAgainst}</td><td>{shotsFor}</td><td>{shotsAgainst}</td><td>{avgPossession}%</td></tr>)}</tbody></table></div></section>}
  {tab==="players"&&<section className={styles.card}><header><b>ESTATÍSTICAS DOS JOGADORES</b><small>Todos os atletas da competição</small></header><div className={styles.tableScroll}><table><thead><tr><th>Jogador</th><th>Clube</th><th>Idade</th><th>OVR</th><th>POT</th><th>Δ</th><th>J</th><th>Min</th><th>G</th><th>A</th><th>Ch</th><th>Nota</th></tr></thead><tbody>{[...players].sort((a,b)=>b.player.goals-a.player.goals||b.player.assists-a.player.assists||b.player.averageRating-a.player.averageRating||b.player.overall-a.player.overall).map(({player,club})=><tr key={player.id}><td><b>{player.name}</b><small className={styles.position}>{player.position}</small></td><td>{club.shortName}</td><td>{player.age}</td><td><strong>{player.overall}</strong></td><td>{player.potential}</td><td className={overallTrend(player)>0?styles.up:overallTrend(player)<0?styles.down:""}>{overallTrend(player)>0?`+${overallTrend(player)}`:overallTrend(player)}</td><td>{player.appearances}</td><td>{player.minutes}</td><td>{player.goals}</td><td>{player.assists}</td><td>{player.shots}</td><td>{player.ratedMatches?player.averageRating.toFixed(2):"—"}</td></tr>)}</tbody></table></div></section>}
 </div>;
}
function Metric({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:number;detail:string}){return <article className={styles.metric}><i>{icon}</i><div><span>{label}</span><b>{value}</b><small>{detail}</small></div></article>}
function Leaderboard({title,rows}:{title:string;rows:Array<{player:{id:string;name:string;goals:number;assists:number;averageRating:number;ratedMatches:number;overall:number;age:number};club:LeagueClub}>}){return <section className={styles.card}><header><b>{title}</b><small>Temporada atual</small></header>{rows.length?rows.map(({player,club},index)=><div className={styles.leader} key={player.id}><em>{index+1}</em><div><b>{player.name}</b><small>{club.shortName} • OVR {player.overall} • {player.age} anos</small></div><strong>{title==="MELHORES NOTAS"?(player.ratedMatches?player.averageRating.toFixed(2):"—"):`${player.goals} G • ${player.assists} A`}</strong></div>):<p className={styles.empty}>As estatísticas aparecem após os primeiros jogos.</p>}</section>}
function ClubName({club}:{club:LeagueClub}){return <span className={styles.club}><i style={{background:club.color}}/>{club.name}</span>}
