"use client";

import{useState,type ReactNode}from"react";
import{Activity,BarChart3,Goal,Star,TrendingDown,TrendingUp,Users}from"lucide-react";
import{sortedStandings,type LeagueClub,type LeaguePlayer,type PlayerCompetitionStats}from"@/game-engine/league";
import{LEAGUE_STATS_SCOPE,overallTrend,playerStatsForScope}from"@/game-engine/development";
import type{SeasonState}from"@/game-engine/season";
import styles from"./statistics-view.module.css";

type Tab="competition"|"clubs"|"players";
type PlayerRow={player:LeaguePlayer;club:LeagueClub;stats:PlayerCompetitionStats};
type LeaderKind="goals"|"assists"|"rating";

export default function StatisticsView({season}:{season:SeasonState}){
 const[tab,setTab]=useState<Tab>("competition"),league=season.league,played=league.fixtures.filter(f=>f.played),scored=played.filter(f=>typeof f.homeGoals==="number"&&typeof f.awayGoals==="number"),standings=sortedStandings(league);
 const goals=scored.reduce((sum,f)=>sum+(f.homeGoals??0)+(f.awayGoals??0),0),shots=played.reduce((sum,f)=>sum+(f.homeShots??0)+(f.awayShots??0),0),homeWins=scored.filter(f=>(f.homeGoals??0)>(f.awayGoals??0)).length,draws=scored.filter(f=>(f.homeGoals??0)===(f.awayGoals??0)).length,awayWins=scored.filter(f=>(f.homeGoals??0)<(f.awayGoals??0)).length;
 const players:PlayerRow[]=league.clubs.flatMap(club=>club.players.map(player=>({player,club,stats:playerStatsForScope(player,LEAGUE_STATS_SCOPE)}))),activePlayers=players.filter(({stats})=>stats.appearances>0);
 const topScorers=[...activePlayers].filter(({stats})=>stats.goals>0).sort((a,b)=>b.stats.goals-a.stats.goals||b.stats.assists-a.stats.assists||b.stats.averageRating-a.stats.averageRating).slice(0,10),topAssists=[...activePlayers].filter(({stats})=>stats.assists>0).sort((a,b)=>b.stats.assists-a.stats.assists||b.stats.goals-a.stats.goals||b.stats.averageRating-a.stats.averageRating).slice(0,10),topRatings=[...activePlayers].filter(({stats})=>stats.ratedMatches>0).sort((a,b)=>b.stats.averageRating-a.stats.averageRating||b.stats.ratedMatches-a.stats.ratedMatches||b.stats.goals-a.stats.goals).slice(0,10),trends=[...players].filter(({player})=>overallTrend(player)!==0).sort((a,b)=>Math.abs(overallTrend(b.player))-Math.abs(overallTrend(a.player))||overallTrend(b.player)-overallTrend(a.player)).slice(0,10);
 const clubStats=standings.map(row=>{const club=league.clubs.find(c=>c.id===row.clubId)!,fixtures=played.filter(f=>f.homeClubId===club.id||f.awayClubId===club.id);let shotsFor=0,shotsAgainst=0,possession=0,possessionSamples=0;for(const f of fixtures){const home=f.homeClubId===club.id;shotsFor+=home?(f.homeShots??0):(f.awayShots??0);shotsAgainst+=home?(f.awayShots??0):(f.homeShots??0);if(typeof f.possessionHome==="number"){possession+=home?f.possessionHome:100-f.possessionHome;possessionSamples++;}}return{club,row,shotsFor,shotsAgainst,avgPossession:possessionSamples?Math.round(possession/possessionSamples):null};});
 const playerTable=[...(activePlayers.length?activePlayers:players)].sort((a,b)=>b.stats.goals-a.stats.goals||b.stats.assists-a.stats.assists||b.stats.averageRating-a.stats.averageRating||b.stats.appearances-a.stats.appearances||b.player.overall-a.player.overall);
 return <div className={styles.wrap}>
  <header className={styles.hero}><div><span>CENTRAL DE DADOS</span><h2>{league.competitionName??"Competição"}</h2><p>Estatísticas da liga separadas das copas: artilharia, assistências, notas e produção coletiva agora usam somente jogos desta competição.</p></div><div className={styles.heroStat}><b>{scored.length}</b><small>jogos computados</small></div></header>
  <div className={styles.scopeNote}><b>ESCOPO ATIVO</b><span>{league.competitionName??"Liga"} • temporada {season.year}</span><small>Copas nacionais e continentais mantêm acumuladores próprios e não alteram os rankings abaixo.</small></div>
  <nav className={styles.tabs}><button className={tab==="competition"?styles.active:""} onClick={()=>setTab("competition")}><BarChart3/> Competição</button><button className={tab==="clubs"?styles.active:""} onClick={()=>setTab("clubs")}><Users/> Clubes</button><button className={tab==="players"?styles.active:""} onClick={()=>setTab("players")}><Star/> Jogadores</button></nav>
  {tab==="competition"&&<><div className={styles.metrics}><Metric icon={<Goal/>} label="GOLS" value={goals} detail={`${scored.length?(goals/scored.length).toFixed(2):"0.00"} por jogo`}/><Metric icon={<Activity/>} label="FINALIZAÇÕES" value={shots} detail={`${played.length?(shots/played.length).toFixed(1):"0.0"} por jogo`}/><Metric icon={<TrendingUp/>} label="VITÓRIAS CASA" value={homeWins} detail={`${scored.length?Math.round(homeWins/scored.length*100):0}% dos jogos`}/><Metric icon={<BarChart3/>} label="EMPATES" value={draws} detail={`${awayWins} vitórias visitantes`}/></div><div className={styles.grid}><Leaderboard title="ARTILHEIROS" kind="goals" rows={topScorers}/><Leaderboard title="ASSISTÊNCIAS" kind="assists" rows={topAssists}/><Leaderboard title="MELHORES NOTAS" kind="rating" rows={topRatings}/></div><section className={`${styles.card} ${styles.trendCard}`}><header><b>EVOLUÇÃO DE OVERALL</b><small>Alterações reais na temporada</small></header>{trends.length?trends.map(({player,club})=><div className={styles.trend} key={player.id}><span>{overallTrend(player)>0?<TrendingUp/>:<TrendingDown/>}</span><div><b>{player.name}</b><small>{club.shortName} • {player.age} anos • POT {player.potential}</small></div><strong className={overallTrend(player)>0?styles.up:styles.down}>{player.overall} {overallTrend(player)>0?`(+${overallTrend(player)})`:`(${overallTrend(player)})`}</strong></div>):<p className={styles.empty}>Nenhum overall mudou até o momento. A lista só aparece quando houver evolução ou queda real.</p>}</section></>}
  {tab==="clubs"&&<section className={styles.card}><header><b>ESTATÍSTICAS DOS CLUBES</b><small>Somente {league.competitionName??"a competição atual"}</small></header><div className={styles.tableScroll}><table><thead><tr><th>#</th><th>Clube</th><th>J</th><th>V</th><th>E</th><th>D</th><th>PTS</th><th>GP</th><th>GC</th><th>SG</th><th>Chutes</th><th>Contra</th><th>Posse</th></tr></thead><tbody>{clubStats.map(({club,row,shotsFor,shotsAgainst,avgPossession},index)=><tr key={club.id} className={club.id===season.selectedClubId?styles.mine:""}><td>{index+1}</td><td><ClubName club={club}/></td><td>{row.played}</td><td>{row.won}</td><td>{row.drawn}</td><td>{row.lost}</td><td><b>{row.points}</b></td><td>{row.goalsFor}</td><td>{row.goalsAgainst}</td><td className={row.goalsFor-row.goalsAgainst>0?styles.up:row.goalsFor-row.goalsAgainst<0?styles.down:""}>{row.goalsFor-row.goalsAgainst>0?"+":""}{row.goalsFor-row.goalsAgainst}</td><td>{shotsFor}</td><td>{shotsAgainst}</td><td>{avgPossession===null?"—":`${avgPossession}%`}</td></tr>)}</tbody></table></div></section>}
  {tab==="players"&&<section className={styles.card}><header><b>ESTATÍSTICAS DOS JOGADORES</b><small>{league.competitionName??"Competição"} • sem números de copas</small></header><div className={styles.tableScroll}><table><thead><tr><th>Jogador</th><th>Clube</th><th>J</th><th>Tit</th><th>Min</th><th>G</th><th>A</th><th>Ch</th><th>Nota</th><th>V</th><th>E</th><th>D</th><th>OVR</th><th>POT</th><th>Δ</th></tr></thead><tbody>{playerTable.map(({player,club,stats})=><tr key={player.id}><td><b>{player.name}</b><small className={styles.position}>{player.position}</small></td><td>{club.shortName}</td><td>{stats.appearances}</td><td>{stats.starts}</td><td>{stats.minutes}</td><td><b>{stats.goals}</b></td><td>{stats.assists}</td><td>{stats.shots}</td><td>{stats.ratedMatches?stats.averageRating.toFixed(2):"—"}</td><td>{stats.wins}</td><td>{stats.draws}</td><td>{stats.losses}</td><td><strong>{player.overall}</strong></td><td>{player.potential}</td><td className={overallTrend(player)>0?styles.up:overallTrend(player)<0?styles.down:""}>{overallTrend(player)>0?`+${overallTrend(player)}`:overallTrend(player)}</td></tr>)}</tbody></table></div></section>}
 </div>;
}
function Metric({icon,label,value,detail}:{icon:ReactNode;label:string;value:number|string;detail:string}){return <article className={styles.metric}><i>{icon}</i><div><span>{label}</span><b>{value}</b><small>{detail}</small></div></article>}
function Leaderboard({title,kind,rows}:{title:string;kind:LeaderKind;rows:PlayerRow[]}){return <section className={styles.card}><header><b>{title}</b><small>Somente liga</small></header>{rows.length?rows.map(({player,club,stats},index)=><div className={styles.leader} key={player.id}><em>{index+1}</em><div><b>{player.name}</b><small>{club.shortName} • {stats.appearances} J • OVR {player.overall}</small></div><strong>{kind==="goals"?`${stats.goals} G`:kind==="assists"?`${stats.assists} A`:stats.averageRating.toFixed(2)}</strong></div>):<p className={styles.empty}>{kind==="goals"?"Ainda não houve gols na competição.":kind==="assists"?"Ainda não houve assistências registradas.":"As notas aparecem após os primeiros jogos."}</p>}</section>}
function ClubName({club}:{club:LeagueClub}){return <span className={styles.club}><i style={{background:club.color}}/>{club.name}</span>}
