"use client";

import{useEffect,useRef,useState,type PointerEvent}from"react";
import { BookmarkPlus, Dumbbell, Lightbulb, Move, Play, Save, Shield, SlidersHorizontal, Sparkles, Trash2, Users } from "lucide-react";
import type { LeagueClub, LeaguePlayer } from "@/game-engine/league";
import type { Formation, MatchTactic, Mentality } from "@/game-engine/match";
import type{MatchdayRole}from"@/game-engine/season";
import { TRAINING_PLAN_DETAILS, TRAINING_PLANS, suggestedTrainingPlan, type TrainingPlan } from "@/game-engine/training";
import { lineupPlacements } from "@/game-engine/tactics-layout";
import{clampTacticalPoint,tacticalFitMultiplier,tacticalZone,type TacticalPoint}from"@/game-engine/tactical-position";
import styles from "./tactics-setup.module.css";

type TacticalRole="GOL"|"ZAG"|"LD"|"LE"|"ALA D"|"ALA E"|"VOL"|"MC"|"MÉDIO-ALA D"|"MÉDIO-ALA E"|"MEI"|"PD"|"PE"|"SA"|"ATA";
type SavedLineup={id:string;name:string;lineupIds:string[];benchIds:string[];tactic:MatchTactic;roles:Record<string,TacticalRole>};
const ROLE_OPTIONS:TacticalRole[]=["GOL","ZAG","LD","LE","ALA D","ALA E","VOL","MC","MÉDIO-ALA D","MÉDIO-ALA E","MEI","PD","PE","SA","ATA"];
const POSITION_ORDER=["GOL","LD","ZAG","LE","VOL","MC","MEI","PD","PE","ATA"];
const rolePoint=(role:TacticalRole):TacticalPoint=>({GOL:{x:50,y:91},ZAG:{x:50,y:75},LD:{x:84,y:70},LE:{x:16,y:70},"ALA D":{x:88,y:52},"ALA E":{x:12,y:52},VOL:{x:50,y:58},MC:{x:50,y:49},"MÉDIO-ALA D":{x:82,y:43},"MÉDIO-ALA E":{x:18,y:43},MEI:{x:50,y:36},PD:{x:82,y:27},PE:{x:18,y:27},SA:{x:50,y:25},ATA:{x:50,y:14}}[role]);
const naturalRole=(p:LeaguePlayer):TacticalRole=>ROLE_OPTIONS.includes(p.position as TacticalRole)?p.position as TacticalRole:"MC";
const scoreYouth=(p:LeaguePlayer)=>((p.age<=21?180:p.age<=23?90:0)+(p.potential*3)+(p.overall*1.2)-p.age);
const positionRank=(position:string)=>{const rank=POSITION_ORDER.indexOf(position);return rank<0?99:rank};
function youthBalancedXI(players:LeaguePlayer[]){const available=players.filter(p=>p.injuryDays===0&&p.suspensionMatches===0),used=new Set<string>(),pick=(positions:string[],count:number)=>{const pool=available.filter(p=>!used.has(p.id)&&positions.includes(p.position)).sort((a,b)=>scoreYouth(b)-scoreYouth(a)).slice(0,count);pool.forEach(p=>used.add(p.id));return pool;};const chosen=[...pick(["GOL"],1),...pick(["ZAG"],2),...pick(["LE","LD"],2),...pick(["VOL","MC","MEI"],3),...pick(["PE","PD","ATA","MEI"],3)];for(const p of [...available].sort((a,b)=>scoreYouth(b)-scoreYouth(a))){if(chosen.length>=11)break;if(!used.has(p.id)){chosen.push(p);used.add(p.id)}}return chosen.slice(0,11);}

export default function TacticsSetupView({club,opponent,isHome,tactic,onChange,lineupIds,benchIds,benchSize,onSetRole,onApplySelection,trainingPlan,onTrainingPlanChange,onPlay}:{club:LeagueClub;opponent:LeagueClub;isHome:boolean;tactic:MatchTactic;onChange:(t:MatchTactic)=>void;lineupIds:string[];benchIds:string[];benchSize:number;onSetRole:(id:string,role:MatchdayRole)=>void;onApplySelection:(lineupIds:string[],benchIds:string[])=>void;trainingPlan:TrainingPlan;onTrainingPlanChange:(plan:TrainingPlan)=>void;onPlay:()=>void}){
 const pitchRef=useRef<HTMLDivElement>(null),[dragging,setDragging]=useState<string|null>(null),[saved,setSaved]=useState<SavedLineup[]>([]),[presetName,setPresetName]=useState(""),[roles,setRoles]=useState<Record<string,TacticalRole>>({});
 const storageKey=`v90:tactics-presets:${club.id}`;
 useEffect(()=>{const timer=window.setTimeout(()=>{try{setSaved(JSON.parse(localStorage.getItem(storageKey)??"[]"))}catch{setSaved([])}},0);return()=>window.clearTimeout(timer)},[storageKey]);
 const starters=lineupIds.map(id=>club.players.find(p=>p.id===id)).filter((p):p is NonNullable<typeof p>=>Boolean(p)),placements=lineupPlacements(starters,tactic.formation,tactic.positions),available=club.players.filter(p=>p.injuryDays===0&&p.suspensionMatches===0),requiredBench=Math.max(0,Math.min(benchSize,available.length-11)),selectionReady=lineupIds.length===11&&benchIds.length===requiredBench;
 const sorted=[...club.players].sort((a,b)=>{const ga=lineupIds.includes(a.id)?0:benchIds.includes(a.id)?1:2,gb=lineupIds.includes(b.id)?0:benchIds.includes(b.id)?1:2;return ga-gb||positionRank(a.position)-positionRank(b.position)||b.overall-a.overall||a.name.localeCompare(b.name)});
 const avgCondition=starters.length?Math.round(starters.reduce((s,p)=>s+p.condition,0)/starters.length):0,avgOverall=starters.length?Math.round(starters.reduce((s,p)=>s+p.overall*tacticalFitMultiplier(p,tactic.positions?.[p.id]),0)/starters.length):0;
 const home=isHome?club:opponent,away=isHome?opponent:club,lowCondition=[...starters].filter(p=>p.condition<80).sort((a,b)=>a.condition-b.condition),strengthGap=opponent.reputation-club.reputation;
 const staffMentality:Mentality=strengthGap>=8?(isHome?"Equilibrada":"Defensiva"):strengthGap<=-8?"Ofensiva":"Equilibrada",staffPressing=avgCondition&&avgCondition<83?Math.min(58,tactic.pressing):staffMentality==="Ofensiva"?72:62,staffTempo=avgCondition&&avgCondition<83?Math.min(56,tactic.tempo):staffMentality==="Ofensiva"?70:60,staffTraining=suggestedTrainingPlan(club);
 function movePlayer(event:PointerEvent<HTMLElement>,id:string){if(dragging!==id||!pitchRef.current)return;const rect=pitchRef.current.getBoundingClientRect(),point=clampTacticalPoint({x:(event.clientX-rect.left)/rect.width*100,y:(event.clientY-rect.top)/rect.height*100});onChange({...tactic,positions:{...(tactic.positions??{}),[id]:point}});}
 function startDrag(event:PointerEvent<HTMLButtonElement>,id:string){event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);setDragging(id);}
 function formation(value:Formation){onChange({...tactic,formation:value,positions:undefined});}
 function setTacticalRole(player:LeaguePlayer,role:TacticalRole){setRoles(prev=>({...prev,[player.id]:role}));onChange({...tactic,positions:{...(tactic.positions??{}),[player.id]:rolePoint(role)}});}
 function persistPresets(next:SavedLineup[]){setSaved(next);localStorage.setItem(storageKey,JSON.stringify(next));}
 function savePreset(){const name=presetName.trim()||`Escalação ${saved.length+1}`,entry:SavedLineup={id:`${Date.now()}`,name,lineupIds:[...lineupIds],benchIds:[...benchIds],tactic:{...tactic,positions:tactic.positions?{...tactic.positions}:undefined},roles:{...roles}};persistPresets([...saved,entry]);setPresetName("");}
 function applyPreset(item:SavedLineup){const valid=new Set(available.map(p=>p.id)),xi=item.lineupIds.filter(id=>valid.has(id)).slice(0,11),xiSet=new Set(xi),bench=item.benchIds.filter(id=>valid.has(id)&&!xiSet.has(id)).slice(0,requiredBench);onApplySelection(xi,bench);setRoles(item.roles??{});onChange(item.tactic);}
 function applyYouth(){const xi=youthBalancedXI(club.players),used=new Set(xi.map(p=>p.id)),bench=[...available].filter(p=>!used.has(p.id)).sort((a,b)=>scoreYouth(b)-scoreYouth(a)).slice(0,requiredBench),nextRoles=Object.fromEntries(xi.map(p=>[p.id,naturalRole(p)])) as Record<string,TacticalRole>;onApplySelection(xi.map(p=>p.id),bench.map(p=>p.id));setRoles(nextRoles);onChange({...tactic,positions:Object.fromEntries(xi.map(p=>[p.id,rolePoint(nextRoles[p.id])]))});}
 return <div className={styles.layout}>
  <section className={styles.pitchCard}>
   <header><div><span>QUADRO TÁTICO FLEXÍVEL • {isHome?"CASA":"FORA"}</span><h2>{home.name} <i>vs</i> {away.name}</h2></div><div className={styles.summary}><b>{tactic.formation}</b><small>{lineupIds.length}/11 titulares • {benchIds.length}/{requiredBench} banco</small></div></header>
   <div className={styles.pitch} ref={pitchRef}><div className={styles.half}/><div className={styles.circle}/><div className={`${styles.box} ${styles.topBox}`}/><div className={`${styles.box} ${styles.bottomBox}`}/>{placements.map(({player,point})=>{const fit=Math.round(tacticalFitMultiplier(player,point)*100),role=roles[player.id]??naturalRole(player);return <button key={player.id} className={`${styles.player} ${dragging===player.id?styles.dragging:""}`} style={{left:`${point.x}%`,top:`${point.y}%`}} onPointerDown={event=>startDrag(event,player.id)} onPointerMove={event=>movePlayer(event,player.id)} onPointerUp={()=>setDragging(null)} onPointerCancel={()=>setDragging(null)} title={`${player.name} • ${role} • ${tacticalZone(point)} • encaixe ${fit}%`}><span>{role}</span><b>{player.name.split(" ")[0]}</b><small>OVR {player.overall} • {fit}%</small></button>})}</div>
   <div className={styles.pitchFooter}><span><Users/> OVR efetivo <b>{avgOverall||"—"}</b></span><span><Shield/> Condição <b>{avgCondition||"—"}%</b></span><small><Move/> Arraste os jogadores ou atribua uma função tática.</small></div>
  </section>
  <section className={styles.side}>
   <button className={styles.play} disabled={!selectionReady} onClick={onPlay}><Play size={16} fill="currentColor"/>{selectionReady?"IR PARA A PARTIDA":lineupIds.length!==11?`SELECIONE 11 TITULARES`:`COMPLETE O BANCO (${benchIds.length}/${requiredBench})`}</button>
   <div className={styles.panel}><header><Lightbulb/><div><b>SUGESTÃO DA COMISSÃO</b><small>Leitura do adversário, mando e condição do seu XI.</small></div></header><div className={styles.staffCards}><div><b>PLANO PARA O JOGO</b><span>{isHome?"Em casa":"Fora de casa"} contra {strengthGap>=8?"um adversário mais forte":strengthGap<=-8?"um adversário teoricamente inferior":"um rival de força semelhante"}. A comissão sugere <strong>{staffMentality}</strong>, pressão {staffPressing} e ritmo {staffTempo}.</span></div><div><b>ELENCO</b><span>{lowCondition.length?`${lowCondition.slice(0,3).map(p=>`${p.name} (${p.condition}%)`).join(", ")} chegam abaixo do ideal e merecem atenção.`:"O XI escolhido chega em boa condição física."}</span></div></div><button className={styles.staffApply} onClick={()=>onChange({...tactic,mentality:staffMentality,pressing:staffPressing,tempo:staffTempo})}>APLICAR AJUSTE SUGERIDO</button></div>
   <div className={styles.panel}><header><Dumbbell/><div><b>PLANO DE TREINO</b><small>Você define a diretriz; a comissão técnica executa automaticamente a cada dia avançado.</small></div></header><div className={styles.trainingRec}><span>Comissão recomenda</span><b>{staffTraining}</b><small>{TRAINING_PLAN_DETAILS[staffTraining]}</small>{staffTraining!==trainingPlan&&<button onClick={()=>onTrainingPlanChange(staffTraining)}>USAR SUGESTÃO</button>}</div><div className={styles.trainingOptions}>{TRAINING_PLANS.map(plan=><button key={plan} className={trainingPlan===plan?styles.trainingActive:""} onClick={()=>onTrainingPlanChange(plan)}><b>{plan}</b><small>{TRAINING_PLAN_DETAILS[plan]}</small></button>)}</div></div>
   <div className={styles.panel}><header><SlidersHorizontal/><div><b>PLANO DE JOGO</b><small>A formação cria a base; depois você pode mover cada jogador livremente.</small></div></header><label>FORMAÇÃO BASE</label><div className={styles.options}>{(["4-2-3-1","4-3-3","4-4-2"] as Formation[]).map(value=><button key={value} className={tactic.formation===value?styles.active:""} onClick={()=>formation(value)}>{value}</button>)}</div><label>MENTALIDADE</label><div className={styles.options}>{(["Defensiva","Equilibrada","Ofensiva"] as Mentality[]).map(value=><button key={value} className={tactic.mentality===value?styles.active:""} onClick={()=>onChange({...tactic,mentality:value})}>{value}</button>)}</div><Range label="Pressão" value={tactic.pressing} onChange={pressing=>onChange({...tactic,pressing})}/><Range label="Ritmo" value={tactic.tempo} onChange={tempo=>onChange({...tactic,tempo})}/></div>
   <div className={styles.panel}><header><BookmarkPlus/><div><b>ESCALAÇÕES SALVAS</b><small>Salve XI, banco, funções e plano tático para trocar de equipe em segundos.</small></div></header><div className={styles.presetActions}><button onClick={applyYouth}><Sparkles size={13}/> JOVENS PROMESSAS</button></div><div className={styles.saveRow}><input value={presetName} onChange={e=>setPresetName(e.target.value)} placeholder="Ex.: Time jovem / Copa"/><button onClick={savePreset} disabled={lineupIds.length!==11}><Save size={13}/> SALVAR</button></div>{saved.length>0&&<div className={styles.savedList}>{saved.map(item=><div key={item.id}><button className={styles.savedMain} onClick={()=>applyPreset(item)}><b>{item.name}</b><small>{item.tactic.formation} • {item.lineupIds.length} titulares</small></button><button className={styles.deletePreset} title="Excluir" onClick={()=>persistPresets(saved.filter(x=>x.id!==item.id))}><Trash2 size={13}/></button></div>)}</div>}</div>
   <div className={styles.panel}><header><Users/><div><b>CONVOCAÇÃO DA PARTIDA</b><small>Titulares primeiro, depois banco e demais jogadores; cada grupo fica ordenado por posição.</small></div></header><div className={styles.selectionSummary}><b>XI {lineupIds.length}/11</b><b>BANCO {benchIds.length}/{requiredBench}</b><b>FORA {club.players.length-lineupIds.length-benchIds.length}</b></div><div className={styles.players}>{sorted.map(p=>{const starter=lineupIds.includes(p.id),bench=benchIds.includes(p.id),blocked=p.injuryDays>0||p.suspensionMatches>0,role=roles[p.id]??naturalRole(p);return <div key={p.id} className={`${styles.playerRow} ${starter?styles.selected:bench?styles.benchSelected:""}`}><i>{p.position}</i><span><b>{p.name}</b><small>{blocked?p.status:`${p.age}a • OVR ${p.overall} • POT ${p.potential} • Cond. ${p.condition}%`}</small>{starter&&<select className={styles.tacticalRole} value={role} onChange={e=>setTacticalRole(p,e.target.value as TacticalRole)}>{ROLE_OPTIONS.map(option=><option key={option}>{option}</option>)}</select>}</span><div className={styles.roles}><button disabled={blocked} className={starter?styles.roleActive:""} onClick={()=>onSetRole(p.id,"starter")}>XI</button><button disabled={blocked} className={bench?styles.roleActive:""} onClick={()=>onSetRole(p.id,"bench")}>B</button><button disabled={blocked} className={!starter&&!bench?styles.roleActive:""} onClick={()=>onSetRole(p.id,"out")}>F</button></div></div>})}</div></div>
  </section>
 </div>;
}
function Range({label,value,onChange}:{label:string;value:number;onChange:(value:number)=>void}){return <label className={styles.range}><span>{label}<b>{value}</b></span><input type="range" min="20" max="90" value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
