"use client";

import Image from "next/image";
import { useMemo, useState } from "react";
import { Trophy, X } from "lucide-react";
import { professionalCompetitionById, type ProfessionalCompetitionId } from "@/data/brazil-2026/competitions";
import { parallelLeagueById, sortedParallelStandings, type ParallelLeagueState, type WorldLeagueTeam } from "@/game-engine/world-leagues";
import type { SeasonState } from "@/game-engine/season";
import styles from "./fm-experience.module.css";

type WorldEntity={type:"club"|"competition";id:string;competitionId:ProfessionalCompetitionId};
const EVENT="v90-fm-open-entity";
function openEntity(entity:WorldEntity){window.dispatchEvent(new CustomEvent(EVENT,{detail:entity}));}

export default function WorldEntityProfile({season,entity,onClose}:{season:SeasonState;entity:WorldEntity;onClose:()=>void}){
 const league=parallelLeagueById(season.worldLeagues,entity.competitionId),definition=professionalCompetitionById(entity.competitionId),[tab,setTab]=useState(entity.type==="club"?"Elenco":"Classificação");
 if(!league)return <Backdrop onClose={onClose}><div className={styles.profileNarrative}><span>MUNDO</span><h3>{definition.name}</h3><p>Esta competição ainda não foi hidratada neste save. Em um novo save, ela será carregada a partir do snapshot atual.</p></div></Backdrop>;
 const team=entity.type==="club"?league.teams.find(item=>item.id===entity.id):undefined;
 const tabs=team?["Elenco","Visão geral","Resultados"]:["Classificação","Estatísticas"];
 return <Backdrop onClose={onClose}><header className={styles.entityTop}><div>{team?<Image src={team.imageUrl||"/generic-club.svg"} alt={team.name} width={58} height={58}/>:<Trophy size={48}/>}<span><small>{definition.country} • {definition.shortName}</small><h2>{team?.name??definition.name}</h2><p>{team?`${rosterFor(league,team,entity.competitionId).length} jogadores • força ${Math.round(team.strength)}`:`${league.teams.length} clubes • temporada ${season.year}`}</p></span></div><button onClick={onClose}><X/></button></header><nav className={styles.entityTabs}>{tabs.map(item=><button key={item} className={tab===item?styles.entityTabActive:""} onClick={()=>setTab(item)}>{item}</button>)}</nav><div className={styles.entityContent}>{team?<ClubWorldProfile league={league} team={team} competitionId={entity.competitionId} tab={tab}/>:<CompetitionWorldProfile league={league} competitionId={entity.competitionId} tab={tab}/>}</div></Backdrop>;
}

function Backdrop({children,onClose}:{children:React.ReactNode;onClose:()=>void}){return <div className={styles.entityBackdrop} onClick={onClose}><section className={styles.entitySheet} onClick={event=>event.stopPropagation()}>{children}</section></div>}

function rosterFor(league:ParallelLeagueState,team:WorldLeagueTeam,competitionId:ProfessionalCompetitionId){const def=professionalCompetitionById(competitionId),index=league.teams.findIndex(item=>item.id===team.id);return def.clubs[index]?.players??[];}
function eur(value:number|null|undefined){if(!value)return "—";return value>=1_000_000?`€ ${(value/1_000_000).toLocaleString("pt-BR",{maximumFractionDigits:1})} mi`:`€ ${Math.round(value/1_000).toLocaleString("pt-BR")} mil`;}

function ClubWorldProfile({league,team,competitionId,tab}:{league:ParallelLeagueState;team:WorldLeagueTeam;competitionId:ProfessionalCompetitionId;tab:string}){
 const table=sortedParallelStandings(league.standings),row=table.find(item=>item.clubId===team.id),position=table.findIndex(item=>item.clubId===team.id)+1,roster=rosterFor(league,team,competitionId),worldPlayers=league.players.filter(player=>player.clubId===team.id),fixtures=league.fixtures.filter(item=>item.homeClubId===team.id||item.awayClubId===team.id),played=fixtures.filter(item=>item.played).slice(-12).reverse();
 if(tab==="Elenco")return <WorldSquad roster={roster} players={worldPlayers}/>;
 if(tab==="Resultados")return <div className={styles.entityList}>{played.length?played.map(match=>{const home=league.teams.find(item=>item.id===match.homeClubId),away=league.teams.find(item=>item.id===match.awayClubId);return <article key={match.id}><span><b>{match.date??`Rodada ${match.round}`}</b><small>{home?.shortName??match.homeClubId} {match.homeGoals} × {match.awayGoals} {away?.shortName??match.awayClubId}</small></span><strong>R{match.round}</strong></article>}):<div className={styles.profileNarrative}><span>RESULTADOS</span><h3>Ainda sem jogos disputados</h3><p>Os resultados aparecerão aqui conforme o calendário mundial do save avançar.</p></div>}</div>;
 return <div className={styles.entityOverview}><div className={styles.entityStats}>{[["POSIÇÃO",position>0?`${position}º`:"—",row?`${row.points} pts`:"sem jogos"],["ELENCO",String(roster.length),"jogadores reais"],["FORÇA",String(Math.round(team.strength)),"nível simulado"],["VALOR",eur(roster.reduce((sum,p)=>sum+(p.marketValueEur??0),0)),professionalCompetitionById(competitionId).shortName]].map(([label,value,detail])=><div key={label} className={styles.fmMetric}><span>{label}</span><b>{value}</b><small>{detail}</small></div>)}</div><section className={styles.profileNarrative}><span>CLUBE NO MUNDO</span><h3>{team.name}</h3><p>O elenco vem do mesmo snapshot real utilizado para criar esta liga. Estatísticas e resultados acompanham a simulação paralela do seu save.</p></section></div>;
}

function WorldSquad({roster,players}:{roster:Array<{transfermarktId:string;name:string;position:string;age:number;marketValueEur:number|null}>;players:ParallelLeagueState["players"]}){
 const[query,setQuery]=useState(""),[position,setPosition]=useState("TODAS"),positions=useMemo(()=>Array.from(new Set(roster.map(player=>player.position))).sort(),[roster]),filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase("pt-BR");return roster.filter(player=>(position==="TODAS"||player.position===position)&&(!q||`${player.name} ${player.position}`.toLocaleLowerCase("pt-BR").includes(q))).sort((a,b)=>(b.marketValueEur??0)-(a.marketValueEur??0));},[roster,query,position]);
 return <div style={{display:"flex",flexDirection:"column",gap:10}}><section style={{display:"flex",gap:7,alignItems:"center",flexWrap:"wrap",padding:10,border:"1px solid #29332f",borderRadius:11,background:"#131a18"}}><div style={{minWidth:160,flex:"1 1 210px"}}><small style={{display:"block",fontSize:7,color:"#54d28c",letterSpacing:".12em",fontWeight:900}}>ELENCO DO CLUBE</small><b style={{fontSize:13,color:"#f3f6f4"}}>{filtered.length} de {roster.length} jogadores</b></div><input aria-label="Pesquisar jogador" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Pesquisar jogador..." style={{height:36,minWidth:170,flex:"1 1 180px",border:"1px solid #33413b",borderRadius:8,background:"#0f1513",color:"#f3f6f4",padding:"0 10px",fontSize:12}}/><select value={position} onChange={event=>setPosition(event.target.value)} style={{height:36,border:"1px solid #33413b",borderRadius:8,background:"#0f1513",color:"#f3f6f4",padding:"0 8px",fontSize:11}}><option value="TODAS">Todas as posições</option>{positions.map(item=><option key={item}>{item}</option>)}</select></section><div className={styles.entityList}>{filtered.map(identity=>{const stat=players.find(player=>player.name===identity.name);const numeric=/^\d+$/.test(identity.transfermarktId);return <article key={`${identity.transfermarktId}-${identity.name}`}>{numeric?<Image src={`/api/player-photo/${identity.transfermarktId}`} alt={identity.name} width={42} height={42} unoptimized/>:<div style={{width:42,height:42,borderRadius:"50%",display:"grid",placeItems:"center",background:"#1c2924",fontSize:10,fontWeight:900}}>{identity.name.split(/\s+/).slice(0,2).map(x=>x[0]).join("")}</div>}<span><b>{identity.name}</b><small>{identity.position} • {identity.age} anos • {stat?.appearances??0} jogos • {stat?.goals??0} G • {stat?.assists??0} A</small></span><strong>{eur(identity.marketValueEur)}</strong></article>})}</div></div>;
}

function CompetitionWorldProfile({league,competitionId,tab}:{league:ParallelLeagueState;competitionId:ProfessionalCompetitionId;tab:string}){const table=sortedParallelStandings(league.standings),played=league.fixtures.filter(item=>item.played),goals=played.reduce((sum,item)=>sum+(item.homeGoals??0)+(item.awayGoals??0),0);if(tab==="Classificação")return <div className={styles.entityList}>{table.map((row,index)=>{const team=league.teams.find(item=>item.id===row.clubId)!;return <button key={team.id} onClick={()=>openEntity({type:"club",id:team.id,competitionId})}><em>{index+1}</em><span><b>{team.name}</b><small>{row.won}V {row.drawn}E {row.lost}D • abrir clube e elenco</small></span><strong>{row.points} pts</strong></button>})}</div>;return <div className={styles.entityStats}>{[["CLUBES",String(league.teams.length),"participantes"],["JOGOS",String(played.length),"disputados"],["GOLS",String(goals),played.length?`${(goals/played.length).toFixed(2)}/jogo`:"—"],["TEMPORADA",String(league.season),professionalCompetitionById(competitionId).country]].map(([label,value,detail])=><div key={label} className={styles.fmMetric}><span>{label}</span><b>{value}</b><small>{detail}</small></div>)}</div>}
