import { SeededRng } from "./rng";
import type { LeagueClub, LeaguePlayer, LeagueWorld, PlayerPersonality } from "./league";
import type { MatchResult } from "./match";
import type { LivingWorldState } from "./world-events";
import type { WorldCompetitionsState } from "./world-competitions";

export type MedicalSeverity="Leve"|"Moderada"|"Grave";
export type ReturnStage="Tratamento"|"Transição"|"Treino parcial"|"Liberado";
export type MedicalCase={id:string;clubId:string;playerId:string;playerName:string;injury:string;severity:MedicalSeverity;startedOn:string;expectedDays:number;recurrenceRisk:number;stage:ReturnStage;closed:boolean};
export type PlayerLifeKind="Adaptação"|"Família"|"Disciplina"|"Entorno social"|"Empresário";
export type PlayerLifeEvent={id:string;clubId:string;playerId:string;playerName:string;kind:PlayerLifeKind;date:string;title:string;summary:string;impact:"Positivo"|"Neutro"|"Negativo"};
export type StadiumClubState={clubId:string;capacity:number;averageAttendance:number;lastAttendance:number;matches:number;atmosphere:number;matchdayRevenueEur:number;recentResults:string[];protest:boolean;mosaic:boolean};
export type ClubFinanceState={clubId:string;cashBalanceEur:number;seasonRevenueEur:number;seasonExpensesEur:number;prizeMoneyEur:number;matchdayRevenueEur:number;projectedBalanceEur:number;lastWageMonth?:string};
export type SeasonHistoryRecord={year:number;competitionName:string;leagueChampion:string;userClub:string;userPosition:number;topScorer:string;topScorerGoals:number;cupChampions:string[];managerStatus:string};
export type AdvancedWorldState={season:number;medicalCases:MedicalCase[];lifeEvents:PlayerLifeEvent[];stadiums:Record<string,StadiumClubState>;finances:Record<string,ClubFinanceState>;history:SeasonHistoryRecord[];sequence:number};

const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,Math.round(v)));
const INJURIES=["Distensão muscular","Entorse de tornozelo","Lesão de posterior","Trauma no joelho","Lesão de adutor","Contusão muscular","Sobrecarga na panturrilha"];
const LIFE:Record<PlayerLifeKind,string[]>={
 "Adaptação":["O jogador relatou evolução na adaptação à cidade e ao clube.","A rotina fora de campo ainda pesa na adaptação e exige atenção do departamento de futebol."],
 "Família":["Uma questão familiar positiva melhorou o ambiente pessoal do atleta.","Uma demanda familiar exigiu flexibilidade na agenda do jogador."],
 "Disciplina":["O atleta foi elogiado internamente pela postura e pontualidade.","O jogador chegou atrasado a uma atividade e recebeu orientação interna."],
 "Entorno social":["O atleta participou de uma ação social do clube e teve boa repercussão.","Uma exposição fora de campo gerou conversa preventiva com o departamento de futebol."],
 "Empresário":["O estafe sinalizou satisfação com o plano esportivo atual.","O empresário pediu uma conversa sobre espaço, contrato e próximos passos da carreira."],
};
const FIRST=["Caio","Davi","Enzo","Gabriel","João","Lucas","Mateus","Pedro","Rafael","Samuel","Theo","Vinícius"];
const LAST=["Almeida","Costa","Ferreira","Gomes","Lima","Martins","Oliveira","Pereira","Ramos","Rocha","Silva","Souza"];
const POS=["GOL","ZAG","ZAG","LD","LE","VOL","MC","MEI","PE","PD","ATA"];
const PERSONALITIES:PlayerPersonality[]=["Profissional","Ambicioso","Competitivo","Leal","Reservado","Temperamental"];

function stadiumFor(club:LeagueClub):StadiumClubState{const capacity=Math.round((16000+club.reputation*520)/1000)*1000;return{clubId:club.id,capacity,averageAttendance:0,lastAttendance:0,matches:0,atmosphere:65,matchdayRevenueEur:0,recentResults:[],protest:false,mosaic:false};}
function financeFor(club:LeagueClub):ClubFinanceState{const opening=Math.max(5_000_000,Math.round((club.transferBudgetEur+club.marketValueEur*.04)/100_000)*100_000);return{clubId:club.id,cashBalanceEur:opening,seasonRevenueEur:0,seasonExpensesEur:0,prizeMoneyEur:0,matchdayRevenueEur:0,projectedBalanceEur:opening};}
export function createAdvancedWorld(league:LeagueWorld,seed:string,year:number):AdvancedWorldState{void seed;return{season:year,medicalCases:[],lifeEvents:[],stadiums:Object.fromEntries(league.clubs.map(c=>[c.id,stadiumFor(c)])),finances:Object.fromEntries(league.clubs.map(c=>[c.id,financeFor(c)])),history:[],sequence:0};}
export function hydrateAdvancedWorld(state:AdvancedWorldState|undefined,league:LeagueWorld,seed:string,year:number){const current=state??createAdvancedWorld(league,seed,year),stadiums={...current.stadiums},finances={...current.finances};for(const club of league.clubs){stadiums[club.id]=stadiums[club.id]??stadiumFor(club);finances[club.id]=finances[club.id]??financeFor(club);}return{...current,season:year,stadiums,finances,medicalCases:current.medicalCases??[],lifeEvents:current.lifeEvents??[],history:current.history??[],sequence:current.sequence??0};}
function findPlayer(league:LeagueWorld,id:string){for(const club of league.clubs){const player=club.players.find(p=>p.id===id);if(player)return{club,player};}return undefined;}
function stageFor(player:LeaguePlayer):ReturnStage{if(player.injuryDays<=0)return"Liberado";if(player.injuryDays<=2)return"Treino parcial";if(player.injuryDays<=5)return"Transição";return"Tratamento";}
function updateMedical(next:AdvancedWorldState,league:LeagueWorld){for(const item of next.medicalCases){if(item.closed)continue;const found=findPlayer(league,item.playerId);if(!found){item.closed=true;continue;}item.stage=stageFor(found.player);if(found.player.injuryDays<=0){item.closed=true;item.stage="Liberado";}}}
function maybeLifeEvent(next:AdvancedWorldState,league:LeagueWorld,clubId:string,date:string,dayNumber:number,seed:string){if(dayNumber%9!==0)return;const club=league.clubs.find(c=>c.id===clubId);if(!club?.players.length)return;const rng=new SeededRng(`${seed}:life:${date}:${clubId}`),player=rng.pick(club.players),kinds=Object.keys(LIFE) as PlayerLifeKind[],kind=rng.pick(kinds),negative=rng.next()<.4,texts=LIFE[kind],summary=texts[negative?1:0],impact=negative?"Negativo":"Positivo" as const;if(negative){player.happiness=clamp(player.happiness-3);player.morale=clamp(player.morale-2);if(kind==="Empresário")player.managerTrust=clamp(player.managerTrust-2);}else{player.happiness=clamp(player.happiness+3);player.morale=clamp(player.morale+2);player.managerTrust=clamp(player.managerTrust+1);}next.sequence++;next.lifeEvents.unshift({id:`life-${next.sequence}`,clubId,playerId:player.id,playerName:player.name,kind,date,title:`${kind}: ${player.name}`,summary,impact});next.lifeEvents=next.lifeEvents.slice(0,80);}
function chargeWages(next:AdvancedWorldState,league:LeagueWorld,clubId:string,date:string){const month=date.slice(0,7),finance=next.finances[clubId],club=league.clubs.find(c=>c.id===clubId);if(!finance||!club||finance.lastWageMonth===month)return;const wageBrl=club.players.reduce((sum,p)=>sum+(p.contract?.salaryBrlMonthly??0),0),estimatedEur=Math.round(wageBrl/6);finance.lastWageMonth=month;finance.seasonExpensesEur+=estimatedEur;finance.cashBalanceEur-=estimatedEur;finance.projectedBalanceEur=finance.cashBalanceEur;}
export function processAdvancedDay(state:AdvancedWorldState|undefined,league:LeagueWorld,clubId:string,date:string,dayNumber:number,seed:string,year:number){const next=structuredClone(hydrateAdvancedWorld(state,league,seed,year));updateMedical(next,league);maybeLifeEvent(next,league,clubId,date,dayNumber,seed);chargeWages(next,league,clubId,date);return next;}
function injurySeverity(days:number):MedicalSeverity{return days>=15?"Grave":days>=7?"Moderada":"Leve";}
export function processAdvancedMatch(state:AdvancedWorldState|undefined,league:LeagueWorld,clubId:string,result:MatchResult,userSide:"home"|"away",date:string,world:LivingWorldState,seed:string,year:number,isHome:boolean){const next=structuredClone(hydrateAdvancedWorld(state,league,seed,year)),club=league.clubs.find(c=>c.id===clubId);if(!club)return next;const gf=userSide==="home"?result.homeGoals:result.awayGoals,ga=userSide==="home"?result.awayGoals:result.homeGoals,outcome=gf>ga?"V":gf<ga?"D":"E";const stadium=next.stadiums[clubId];stadium.recentResults=[...stadium.recentResults,outcome].slice(-5);stadium.protest=stadium.recentResults.slice(-3).every(v=>v==="D")||world.fanSupport<35;stadium.mosaic=(gf>ga&&world.fanSupport>=72)||false;stadium.atmosphere=clamp(stadium.atmosphere+(outcome==="V"?4:outcome==="D"?-4:0)+(world.fanSupport-50)/25);
 if(isHome){const factor=Math.max(.45,Math.min(1,.48+club.reputation/180+world.fanSupport/260+(outcome==="V"?.03:0))),attendance=Math.round(stadium.capacity*factor),ticket=12+club.reputation*.42,revenue=Math.round(attendance*ticket);stadium.lastAttendance=attendance;stadium.matches++;stadium.averageAttendance=Math.round(((stadium.averageAttendance*(stadium.matches-1))+attendance)/stadium.matches);stadium.matchdayRevenueEur+=revenue;const finance=next.finances[clubId];finance.matchdayRevenueEur+=revenue;finance.seasonRevenueEur+=revenue;finance.cashBalanceEur+=revenue;finance.projectedBalanceEur=finance.cashBalanceEur;}
 const rng=new SeededRng(`${seed}:medical:${date}:${clubId}`);for(const event of result.events.filter(e=>e.type==="injury"&&e.team===userSide&&e.playerId)){const player=club.players.find(p=>p.id===event.playerId);if(!player)continue;const days=Math.max(3,player.injuryDays||rng.integer(4,18));player.injuryDays=Math.max(player.injuryDays,days);const previous=next.medicalCases.filter(c=>c.playerId===player.id).length,risk=clamp(10+player.fatigue*.45+previous*8,5,85);next.sequence++;next.medicalCases.unshift({id:`med-${next.sequence}`,clubId,playerId:player.id,playerName:player.name,injury:rng.pick(INJURIES),severity:injurySeverity(days),startedOn:date,expectedDays:days,recurrenceRisk:risk,stage:"Tratamento",closed:false});}next.medicalCases=next.medicalCases.slice(0,100);return next;}
export function awardCompetitionPrize(state:AdvancedWorldState,clubId:string,amountEur:number){const next=structuredClone(state),finance=next.finances[clubId];if(finance){finance.prizeMoneyEur+=amountEur;finance.seasonRevenueEur+=amountEur;finance.cashBalanceEur+=amountEur;finance.projectedBalanceEur=finance.cashBalanceEur;}return next;}
export function prepareAdvancedNextSeason(state:AdvancedWorldState|undefined,league:LeagueWorld,selectedClubId:string,competitionName:string,championClubId:string|undefined,worldCompetitions:WorldCompetitionsState,careerStatus:string,seed:string,nextYear:number){const current=structuredClone(hydrateAdvancedWorld(state,league,seed,nextYear-1)),table=[...league.standings].sort((a,b)=>b.points-a.points||(b.goalsFor-b.goalsAgainst)-(a.goalsFor-a.goalsAgainst)),club=league.clubs.find(c=>c.id===selectedClubId)??league.clubs[0],champion=league.clubs.find(c=>c.id===championClubId)?.name??league.clubs.find(c=>c.id===table[0]?.clubId)?.name??"—",players=league.clubs.flatMap(c=>c.players),top=[...players].sort((a,b)=>(b.goals??0)-(a.goals??0))[0],cups=worldCompetitions.history.filter(h=>h.year===nextYear-1).map(h=>`${h.competitionName}: ${h.championName}`);current.history.unshift({year:nextYear-1,competitionName,leagueChampion:champion,userClub:club.name,userPosition:Math.max(1,table.findIndex(r=>r.clubId===club.id)+1),topScorer:top?.name??"—",topScorerGoals:top?.goals??0,cupChampions:cups,managerStatus:careerStatus});current.history=current.history.slice(0,40);current.season=nextYear;for(const finance of Object.values(current.finances)){finance.seasonRevenueEur=0;finance.seasonExpensesEur=0;finance.prizeMoneyEur=0;finance.matchdayRevenueEur=0;finance.projectedBalanceEur=finance.cashBalanceEur;finance.lastWageMonth=undefined;}return current;}
export function medicalCasesForClub(state:AdvancedWorldState,clubId:string){return state.medicalCases.filter(c=>c.clubId===clubId).slice(0,20);}
export function lifeEventsForClub(state:AdvancedWorldState,clubId:string){return state.lifeEvents.filter(e=>e.clubId===clubId).slice(0,20);}

function newgen(club:LeagueClub,index:number,year:number,seed:string):LeaguePlayer{const rng=new SeededRng(`${seed}:newgen:${year}:${club.id}:${index}`),age=rng.integer(17,20),overall=Math.max(49,Math.min(72,Math.round(club.reputation*.55)+rng.integer(12,22))),potential=Math.min(94,overall+rng.integer(7,16)),position=POS[index%POS.length],name=`${rng.pick(FIRST)} ${rng.pick(LAST)}`;return{id:`${club.id}-ng${year}-${index}`,transfermarktId:`newgen-${year}-${club.id}-${index}`,name,position,age,marketValueEur:null,overall,potential,seasonStartOverall:overall,developmentProgress:0,overallHistory:[{year,round:0,overall,reason:"início"}],morale:72,condition:96,fatigue:2,form:6.4,goals:0,assists:0,shots:0,yellowCards:0,redCards:0,wins:0,draws:0,losses:0,cleanSheets:0,ratingTotal:0,ratedMatches:0,averageRating:0,lastRating:0,injuryDays:0,suspensionMatches:0,status:"Promessa",personality:rng.pick(PERSONALITIES),squadRole:"Promessa",happiness:75,managerTrust:62,appearances:0,starts:0,minutes:0,promises:[],contract:{salaryBrlMonthly:Math.max(25000,overall*900),startYear:year,endYear:year+4,agentName:"Agente da base",releaseClauseEur:null},transferListed:false,wantsToLeave:false};}
export function applyRetirementsAndNewgens(league:LeagueWorld,seed:string,year:number){for(const club of league.clubs){const before=club.players.length;club.players=club.players.filter(player=>{if(player.age<37||player.contract.endYear>=year)return true;const rng=new SeededRng(`${seed}:retire:${year}:${player.id}`),chance=player.age>=39?.92:player.age===38?.65:player.age===37?.38:.18;return rng.next()>=chance;});const lost=before-club.players.length,target=Math.max(22,before);for(let i=0;club.players.length<target&&i<Math.max(2,lost+2);i++)club.players.push(newgen(club,i+1,year,seed));}return league;}
