import{describe,expect,it}from"vitest";
import{applyCareerChoice,careerAfterRound,createManagerCareer}from"./career";
import{createLeague}from"./league";
import{createLivingWorld}from"./world-events";

describe("manager career",()=>{
 const league=createLeague("career-tests",2026),club=league.clubs[0];
 it("começa empregado com histórico aberto",()=>{const career=createManagerCareer(club,2026);expect(career.status).toBe("Empregado");expect(career.currentClubId).toBe(club.id);expect(career.spells).toHaveLength(1)});
 it("demite o treinador quando segurança e diretoria entram em nível crítico",()=>{const career=createManagerCareer(club,2026);career.jobSecurity=17;let world=createLivingWorld(club.name);world={...world,boardConfidence:13};const result=careerAfterRound(career,league,world,8,2026,"dismiss",{goalsFor:0,goalsAgainst:3});expect(result.career.status).toBe("Sem clube");expect(result.career.dismissals).toBe(1);expect(result.world.inbox.some(event=>event.kind==="Carreira"&&event.title.includes("Fim da passagem"))).toBe(true)});
 it("gera entrevista para treinador sem clube",()=>{const career=createManagerCareer(club,2026);career.status="Sem clube";career.currentClubId=undefined;career.lastDismissalRound=6;const result=careerAfterRound(career,league,createLivingWorld(club.name),7,2026,"unemployed");const invite=result.world.inbox.find(event=>event.kind==="Carreira"&&event.choices.some(choice=>choice.careerAction==="accept-interview"));expect(invite).toBeTruthy()});
 it("transforma entrevista forte em proposta e permite assumir outro clube",()=>{let career=createManagerCareer(club,2026);career.status="Sem clube";career.currentClubId=undefined;let world=createLivingWorld(club.name);world={...world,managerReputation:100};const target=league.clubs[1];const acceptInterview={id:"accept",label:"Aceitar",outcome:"ok",effect:{},careerAction:"accept-interview" as const,careerClubId:target.id};let step=applyCareerChoice(career,league,world,acceptInterview,10,2026,"hire");career=step.career;world=step.world;const interview=world.inbox.find(event=>event.kind==="Carreira"&&event.title.includes("Entrevista com"))!;const strong=interview.choices.find(choice=>choice.careerAction==="interview-answer"&&choice.careerScore===16)!;step=applyCareerChoice(career,league,world,strong,10,2026,"hire");const offer=step.world.inbox.find(event=>event.kind==="Carreira"&&event.choices.some(choice=>choice.careerAction==="accept-job"));expect(offer).toBeTruthy();const acceptJob=offer!.choices.find(choice=>choice.careerAction==="accept-job")!;const hired=applyCareerChoice(step.career,league,step.world,acceptJob,10,2026,"hire");expect(hired.career.status).toBe("Empregado");expect(hired.career.currentClubId).toBe(target.id);expect(hired.nextClubId).toBe(target.id)});
});
