import { SeededRng } from "./rng";
import { sortedStandings, type LeagueClub, type LeagueWorld } from "./league";
import type { LivingWorldState, WorldChoice, WorldInboxEvent, WorldNews } from "./world-events";

export type ManagerCareerStatus="Empregado"|"Sem clube";
export type CareerExitReason="Demitido"|"Proposta aceita"|"Fim de temporada";
export type CareerSpell={clubId:string;clubName:string;startYear:number;startRound:number;endYear?:number;endRound?:number;endReason?:CareerExitReason};
export type ManagerCareerState={status:ManagerCareerStatus;currentClubId?:string;jobSecurity:number;matches:number;wins:number;draws:number;losses:number;clubsManaged:number;dismissals:number;interviews:number;offersReceived:number;lastOpportunityRound?:number;lastDismissalRound?:number;spells:CareerSpell[]};
export type CareerRoundResult={goalsFor:number;goalsAgainst:number};
export type CareerResolution={career:ManagerCareerState;world:LivingWorldState;nextClubId?:string;message:string};

const clamp=(value:number)=>Math.max(0,Math.min(100,Math.round(value)));
function addEvent(world:LivingWorldState,event:Omit<WorldInboxEvent,"createdOrder">):LivingWorldState{const order=world.sequence+1;return{...world,sequence:order,inbox:[{...event,createdOrder:order},...world.inbox].slice(0,90)}}
function addNews(world:LivingWorldState,news:Omit<WorldNews,"createdOrder">):LivingWorldState{const order=world.sequence+1;return{...world,sequence:order,news:[{...news,createdOrder:order},...world.news].slice(0,120)}}

export function createManagerCareer(club:LeagueClub,year:number):ManagerCareerState{return{status:"Empregado",currentClubId:club.id,jobSecurity:72,matches:0,wins:0,draws:0,losses:0,clubsManaged:1,dismissals:0,interviews:0,offersReceived:0,spells:[{clubId:club.id,clubName:club.name,startYear:year,startRound:1}]}}
function standingPosition(league:LeagueWorld,clubId:string){return sortedStandings(league).findIndex(row=>row.clubId===clubId)+1}
function candidateClub(career:ManagerCareerState,league:LeagueWorld,seed:string,round:number){const rng=new SeededRng(`${seed}:career:candidate:r${round}:${career.matches}:${career.interviews}`),table=sortedStandings(league),candidates=table.slice(8).map(row=>league.clubs.find(club=>club.id===row.clubId)!).filter(club=>club&&club.id!==career.currentClubId),fallback=league.clubs.filter(club=>club.id!==career.currentClubId),pool=candidates.length?candidates:fallback;if(!pool.length)return undefined;const shortlist=[...pool].sort((a,b)=>Math.abs(a.reputation-68)-Math.abs(b.reputation-68)).slice(0,Math.min(6,pool.length));return rng.pick(shortlist)}
function hasOpenCareerProcess(world:LivingWorldState){return world.inbox.some(event=>event.kind==="Carreira"&&!event.resolved&&event.choices.some(choice=>choice.careerAction&&choice.careerAction!=="ack-dismissal"))}
function hasRecentContextualEvent(world:LivingWorldState,round:number){return world.inbox.some(event=>round-event.round<=2&&["Logística","Comissão técnica","Compromisso","Empresário"].includes(event.kind))}

function contextualCareerBeat(world:LivingWorldState,club:LeagueClub,round:number,seed:string,result?:CareerRoundResult){
 if(round<2||hasRecentContextualEvent(world,round))return world;
 const rng=new SeededRng(`${seed}:career-context:r${round}:${world.sequence}:${club.id}`);
 let next=world;
 if(round%4===0&&rng.integer(1,100)<=72){
  const candidates=club.players.filter(p=>p.squadRole==="Líder"||p.squadRole==="Titular"||p.wantsToLeave).sort((a,b)=>b.overall-a.overall),player=candidates[0]??club.players[0];
  if(player){next=addEvent(next,{id:`agent-context-${player.id}-r${round}-${next.sequence}`,kind:"Empresário",title:`${player.contract.agentName} pede uma conversa sobre ${player.name}`,body:`O empresário quer alinhar status, minutos, valorização e próximos passos. Ele deixa claro que a relação com o treinador será considerada em qualquer decisão futura.`,round,playerId:player.id,unread:true,resolved:false,choices:[{id:"agent-open",label:"Abrir a conversa",outcome:"O empresário valorizou o canal direto e saiu com a sensação de que existe espaço para construir uma solução.",effect:{playerTrust:3,playerHappiness:2,mediaPressure:-1}},{id:"agent-boundary",label:"Reforçar que decisões são esportivas",outcome:"A mensagem foi objetiva. O estafe entendeu os limites, embora tenha aumentado a vigilância sobre os próximos jogos.",effect:{managerReputation:2,playerTrust:-1}},{id:"agent-freeze",label:"Encerrar o assunto",outcome:"A relação esfriou e o estafe passou a considerar outras formas de pressionar o clube.",effect:{playerTrust:-5,playerHappiness:-4,mediaPressure:4}}]});return next}
 }
 if(rng.integer(1,100)>58)return next;
 const scenario=rng.integer(0,4);
 if(scenario===0)return addEvent(next,{id:`travel-r${round}-${next.sequence}`,kind:"Logística",title:"Viagem sofreu atraso e a preparação apertou",body:"Um problema operacional reduziu a janela de descanso antes do próximo compromisso. A comissão pede uma decisão sobre carga de treino e exposição do elenco.",round,unread:true,resolved:false,choices:[{id:"travel-rest",label:"Priorizar recuperação",outcome:"O elenco descansou mais e chegou fisicamente melhor, embora parte do plano tático tenha sido encurtada.",effect:{squadCondition:3,squadFatigue:-4,boardConfidence:1}},{id:"travel-plan",label:"Manter o planejamento",outcome:"A programação foi mantida. A equipe absorveu o conteúdo, mas o desgaste aumentou.",effect:{squadCondition:-2,squadFatigue:3,managerReputation:1}}]});
 if(scenario===1){const player=[...club.players].sort((a,b)=>b.overall-a.overall)[Math.min(4,club.players.length-1)]??club.players[0];return addEvent(next,{id:`late-player-${player.id}-r${round}-${next.sequence}`,kind:"Compromisso",title:`${player.name} chegou atrasado ao treino`,body:"O atraso foi notado por todo o elenco. A forma como você reage pode definir o padrão de disciplina e também sua relação com um jogador importante.",round,playerId:player.id,unread:true,resolved:false,choices:[{id:"late-private",label:"Advertir em particular",outcome:"A cobrança foi firme sem expor o jogador. O grupo percebeu coerência.",effect:{playerTrust:1,playerHappiness:-1,groupTrust:1,managerReputation:1}},{id:"late-fine",label:"Aplicar punição formal",outcome:"A diretoria aprovou a disciplina, mas o jogador ficou incomodado com a rigidez.",effect:{boardConfidence:2,playerTrust:-4,playerHappiness:-3,managerReputation:2}},{id:"late-ignore",label:"Deixar passar",outcome:"O jogador agradeceu a flexibilidade, mas parte do grupo percebeu dois pesos e duas medidas.",effect:{playerTrust:3,groupTrust:-2,boardConfidence:-1}}]})}
 if(scenario===2)return addEvent(next,{id:`staff-offer-r${round}-${next.sequence}`,kind:"Comissão técnica",title:"Membro da comissão recebeu sondagem",body:"Um profissional importante da comissão foi procurado por outro clube e quer entender se ainda faz parte do seu projeto de médio prazo.",round,unread:true,resolved:false,choices:[{id:"staff-value",label:"Reforçar importância no projeto",outcome:"A conversa aumentou o comprometimento e reduziu o risco de saída imediata.",effect:{boardConfidence:1,managerReputation:1}},{id:"staff-career",label:"Não impedir a evolução profissional",outcome:"A postura foi vista como elegante e aumentou sua reputação entre profissionais do mercado.",effect:{managerReputation:3}},{id:"staff-pressure",label:"Cobrar foco total no clube",outcome:"A mensagem encerrou o assunto por agora, mas deixou um clima mais frio na comissão.",effect:{boardConfidence:1,mediaPressure:1}}]});
 if(scenario===3){const player=club.players.find(p=>p.squadRole==="Líder")??club.players[0];return addEvent(next,{id:`family-${player.id}-r${round}-${next.sequence}`,kind:"Jogador",title:`${player.name} pede compreensão por questão familiar`,body:"O jogador relata um problema pessoal e pede uma abordagem mais flexível nos próximos dias. O restante do elenco acompanha como você lida com situações humanas fora de campo.",round,playerId:player.id,unread:true,resolved:false,choices:[{id:"family-support",label:"Liberar e oferecer apoio",outcome:"O gesto teve forte impacto na confiança do jogador e foi bem recebido pelo grupo.",effect:{playerTrust:7,playerHappiness:5,groupTrust:2,managerReputation:1}},{id:"family-limit",label:"Flexibilizar sem comprometer o jogo",outcome:"Você buscou equilíbrio entre o lado humano e a responsabilidade esportiva.",effect:{playerTrust:3,playerHappiness:2,boardConfidence:1}},{id:"family-hard",label:"Exigir rotina normal",outcome:"A decisão protegeu o planejamento, mas desgastou a relação com o jogador.",effect:{playerTrust:-6,playerHappiness:-5,groupTrust:-2,boardConfidence:1}}]})}
 return addEvent(next,{id:`pitch-r${round}-${next.sequence}`,kind:"Logística",title:"Condições do gramado preocupam a comissão",body:`A equipe técnica alertou que o campo do próximo compromisso pode aumentar desgaste e mudar o tipo de jogo. ${result&&result.goalsFor<result.goalsAgainst?"Depois do último resultado, a decisão ganha ainda mais peso.":"A preparação precisa ser adaptada."}`,round,unread:true,resolved:false,choices:[{id:"pitch-adapt",label:"Adaptar treino e estratégia",outcome:"A comissão ajustou a carga e preparou alternativas mais diretas para o jogo.",effect:{squadFatigue:-2,managerReputation:1}},{id:"pitch-normal",label:"Manter identidade de jogo",outcome:"Você preservou o plano principal e reforçou confiança na proposta.",effect:{managerReputation:2,squadFatigue:1}}]});
}

function mediaNarrativeBeat(world:LivingWorldState,club:LeagueClub,round:number,result?:CareerRoundResult){if(!result||round%3!==0)return world;const won=result.goalsFor>result.goalsAgainst,lost=result.goalsFor<result.goalsAgainst;return addNews(world,{id:`manager-narrative-${club.id}-r${round}-${world.sequence}`,headline:won?`Trabalho no ${club.name} começa a ganhar identidade`:lost?`Decisões do treinador entram no centro do debate`:`Projeto do ${club.name} divide opiniões`,summary:won?"A imprensa destaca ambiente, leitura de jogo e gestão de grupo como partes do bom momento.":lost?"Torcedores e comentaristas discutem escolhas, discurso e capacidade de reação do treinador.":"O empate mantém aberta a discussão sobre estilo, liderança e evolução do elenco.",source:"Debate esportivo • simulação",round,tone:won?"positive":lost?"negative":"neutral"})}

export function careerAfterRound(career:ManagerCareerState,league:LeagueWorld,world:LivingWorldState,round:number,year:number,seed:string,result?:CareerRoundResult){
 const nextCareer:ManagerCareerState={...career,spells:career.spells.map(spell=>({...spell}))};let nextWorld=world;
 if(nextCareer.status==="Empregado"&&nextCareer.currentClubId&&result){const win=result.goalsFor>result.goalsAgainst,loss=result.goalsFor<result.goalsAgainst;nextCareer.matches+=1;if(win)nextCareer.wins+=1;else if(loss)nextCareer.losses+=1;else nextCareer.draws+=1;const club=league.clubs.find(item=>item.id===nextCareer.currentClubId),position=club?standingPosition(league,club.id):10,expectationPenalty=club&&club.reputation>=78&&position>15?-4:club&&club.reputation>=78&&position>10?-2:0,resultDelta=win?5:loss?-7:1;nextCareer.jobSecurity=clamp(nextCareer.jobSecurity+resultDelta+expectationPenalty);nextWorld={...nextWorld,boardConfidence:clamp(nextWorld.boardConfidence+(win?2:loss?-4:0))};if(club){nextWorld=mediaNarrativeBeat(nextWorld,club,round,result);nextWorld=contextualCareerBeat(nextWorld,club,round,seed,result)}if(round>=5&&(nextCareer.jobSecurity<=18||nextWorld.boardConfidence<=14)&&club){nextCareer.status="Sem clube";nextCareer.currentClubId=undefined;nextCareer.dismissals+=1;nextCareer.lastDismissalRound=round;const spell=nextCareer.spells.findLast(item=>item.clubId===club.id&&!item.endRound);if(spell){spell.endYear=year;spell.endRound=round;spell.endReason="Demitido"}nextWorld=addNews(nextWorld,{id:`career-dismissal-news-${club.id}-r${round}-${nextWorld.sequence}`,headline:`${club.name} encerra ciclo com o treinador`,summary:"A sequência esportiva e a confiança interna levaram a diretoria a mudar o comando técnico. O treinador volta ao mercado.",source:"Mercado de Treinadores",round,tone:"negative"});nextWorld=addEvent(nextWorld,{id:`career-dismissal-${club.id}-r${round}-${nextWorld.sequence}`,kind:"Carreira",title:`Fim da passagem pelo ${club.name}`,body:"A diretoria comunicou a demissão. A reputação construída permanece, mas agora você está sem clube e pode avançar as rodadas enquanto procura um novo projeto.",round,unread:true,resolved:false,choices:[{id:"career-dismissal-ack",label:"Seguir em frente",outcome:"Você encerrou o ciclo e passou a ouvir o mercado.",effect:{mediaPressure:-3},careerAction:"ack-dismissal"}]})}}
 if(!hasOpenCareerProcess(nextWorld)){const spacing=nextCareer.status==="Sem clube"?2:12,canInvite=nextCareer.status==="Sem clube"?(nextCareer.lastDismissalRound===undefined||round>nextCareer.lastDismissalRound):(round>=12&&round%12===0);if(canInvite&&(nextCareer.lastOpportunityRound===undefined||round-nextCareer.lastOpportunityRound>=spacing)){const candidate=candidateClub(nextCareer,league,seed,round);if(candidate){nextCareer.offersReceived+=1;nextWorld=formalOffer(nextWorld,candidate,round);nextCareer.lastOpportunityRound=round}}}
 return{career:nextCareer,world:nextWorld};
}

function interviewEvent(world:LivingWorldState,career:ManagerCareerState,club:LeagueClub,round:number){const status=career.status==="Empregado"?"Você ainda tem contrato com outro clube.":"Você está livre no mercado.";return addEvent(world,{id:`career-interview-${club.id}-r${round}-${world.sequence}`,kind:"Carreira",title:`Entrevista com o ${club.name}`,body:`A direção pergunta por que você é o nome certo para o projeto. ${status} Sua resposta vai pesar junto com a reputação construída até aqui.`,round,unread:true,resolved:false,choices:[{id:`career-answer-project:${club.id}`,label:"Construir um projeto de longo prazo",outcome:"Você apresentou um plano de evolução, gestão de elenco e estabilidade.",effect:{managerReputation:2},careerAction:"interview-answer",careerClubId:club.id,careerScore:16},{id:`career-answer-results:${club.id}`,label:"Cobrar resultado desde o primeiro dia",outcome:"Você vendeu uma ideia de impacto imediato e alta exigência.",effect:{managerReputation:2,mediaPressure:2},careerAction:"interview-answer",careerClubId:club.id,careerScore:10},{id:`career-answer-control:${club.id}`,label:"Pedir autonomia total",outcome:"Você condicionou o projeto a grande autonomia esportiva. A postura dividiu a direção.",effect:{managerReputation:1},careerAction:"interview-answer",careerClubId:club.id,careerScore:-4}]})}
function formalOffer(world:LivingWorldState,club:LeagueClub,round:number){return addEvent(world,{id:`career-offer-${club.id}-r${round}-${world.sequence}`,kind:"Carreira",title:`Proposta formal do ${club.name}`,body:`O ${club.name} aprovou seu nome e oferece o cargo de treinador principal imediatamente. Se aceitar, você assume o clube na rodada atual e deixa seu vínculo anterior, caso ainda exista.`,round,unread:true,resolved:false,choices:[{id:`career-job-accept:${club.id}`,label:`Assumir o ${club.name}`,outcome:`Você aceitou a proposta e é o novo treinador do ${club.name}.`,effect:{managerReputation:3,mediaPressure:3},careerAction:"accept-job",careerClubId:club.id},{id:`career-job-decline:${club.id}`,label:"Recusar a proposta",outcome:`Você recusou a oferta do ${club.name} e manteve seu caminho atual.`,effect:{managerReputation:1},careerAction:"decline-job",careerClubId:club.id}]})}

export function applyCareerChoice(career:ManagerCareerState,league:LeagueWorld,world:LivingWorldState,choice:WorldChoice,round:number,year:number,seed:string):CareerResolution{
 const club=choice.careerClubId?league.clubs.find(item=>item.id===choice.careerClubId):undefined,nextCareer:ManagerCareerState={...career,spells:career.spells.map(spell=>({...spell}))};let nextWorld=world;
 if(choice.careerAction==="accept-interview"&&club){nextCareer.interviews+=1;nextWorld=interviewEvent(nextWorld,nextCareer,club,round);return{career:nextCareer,world:nextWorld,message:`Entrevista com o ${club.name} agendada.`}}
 if(choice.careerAction==="decline-interview"&&club)return{career:nextCareer,world:nextWorld,message:`Processo com o ${club.name} encerrado.`};
 if(choice.careerAction==="interview-answer"&&club){const rng=new SeededRng(`${seed}:career:interview:${club.id}:r${round}:${choice.id}`),score=world.managerReputation+(choice.careerScore??0)+rng.integer(-8,8)-Math.max(0,club.reputation-72);if(score>=60){nextCareer.offersReceived+=1;nextWorld=formalOffer(nextWorld,club,round);nextWorld=addNews(nextWorld,{id:`career-interview-positive-${club.id}-r${round}-${nextWorld.sequence}`,headline:`${club.name} avança por novo treinador`,summary:"A entrevista foi considerada positiva e a direção decidiu apresentar uma proposta formal.",source:"Mercado de Treinadores",round,tone:"positive"});return{career:nextCareer,world:nextWorld,message:`A entrevista agradou. O ${club.name} enviou uma proposta.`}}nextWorld=addNews(nextWorld,{id:`career-interview-negative-${club.id}-r${round}-${nextWorld.sequence}`,headline:`${club.name} segue busca após entrevistas`,summary:"A direção decidiu seguir com outros nomes depois da rodada de conversas.",source:"Mercado de Treinadores",round,tone:"neutral"});return{career:nextCareer,world:nextWorld,message:`O ${club.name} decidiu seguir com outro perfil.`}}
 if(choice.careerAction==="accept-job"&&club){const previousId=nextCareer.currentClubId;if(previousId&&previousId!==club.id){const spell=nextCareer.spells.findLast(item=>item.clubId===previousId&&!item.endRound);if(spell){spell.endYear=year;spell.endRound=round;spell.endReason="Proposta aceita"}}const alreadyManaged=nextCareer.spells.some(spell=>spell.clubId===club.id);nextCareer.status="Empregado";nextCareer.currentClubId=club.id;nextCareer.jobSecurity=72;if(!alreadyManaged)nextCareer.clubsManaged+=1;nextCareer.spells.push({clubId:club.id,clubName:club.name,startYear:year,startRound:round});nextWorld={...nextWorld,boardConfidence:68,fanSupport:clamp(Math.max(55,nextWorld.fanSupport)),mediaPressure:clamp(nextWorld.mediaPressure+3)};nextWorld=addNews(nextWorld,{id:`career-hired-${club.id}-r${round}-${nextWorld.sequence}`,headline:`${club.name} anuncia novo treinador`,summary:"O acordo foi fechado e o treinador assume imediatamente, com novo vestiário, nova diretoria e novos objetivos.",source:"Mercado de Treinadores",round,tone:"positive"});nextWorld=addEvent(nextWorld,{id:`career-board-welcome-${club.id}-r${round}-${nextWorld.sequence}`,kind:"Diretoria",title:`Primeira reunião no ${club.name}`,body:"A nova diretoria quer alinhar expectativas rapidamente e entender como você pretende conduzir o restante da temporada.",round,unread:true,resolved:false,choices:[{id:"career-newclub-ambition",label:"Prometer competitividade imediata",outcome:"A diretoria aprovou a ambição, mas elevou a cobrança por resultados.",effect:{boardConfidence:4,mediaPressure:3}},{id:"career-newclub-balance",label:"Pedir tempo para conhecer o elenco",outcome:"A direção aceitou uma transição mais equilibrada.",effect:{boardConfidence:2,mediaPressure:-1}},{id:"career-newclub-squad",label:"Colocar o vestiário no centro do projeto",outcome:"A mensagem agradou aos jogadores e reforçou a ideia de reconstrução coletiva.",effect:{groupTrust:2,groupHappiness:2,boardConfidence:1}}]});return{career:nextCareer,world:nextWorld,nextClubId:club.id,message:`Você é o novo treinador do ${club.name}.`}}
 if(choice.careerAction==="decline-job"&&club)return{career:nextCareer,world:nextWorld,message:`Oferta do ${club.name} recusada.`};
 if(choice.careerAction==="ack-dismissal")return{career:nextCareer,world:nextWorld,message:"Você está disponível no mercado."};
 return{career:nextCareer,world:nextWorld,message:choice.outcome};
}
