import{describe,expect,it}from"vitest";
import{clubOperationsProfile,observeYouthProspect,processClubManagementRound,promoteYouthProspect,requestBoardAction,requestExternalScout,requestInternalAssessment}from"./club-management";
import{createSeason}from"./season";

describe("club management",()=>{
 it("cria departamentos e oito jogadores de base para o clube",()=>{const season=createSeason("departments",2026),profile=clubOperationsProfile(season);expect(Object.keys(profile.departments)).toEqual(expect.arrayContaining(["Futebol","Observação","Base","Análise","Médico"]));expect(profile.youth).toHaveLength(8)});
 it("permite pedir observação de atleta externo e entrega relatório em rodada futura",()=>{let season=createSeason("scouting",2026);const target=season.league.clubs[1].players[0];const requested=requestExternalScout(season,target.id);season=requested.state;const task=clubOperationsProfile(season).tasks.find(item=>item.targetPlayerId===target.id)!;expect(task.status).toBe("Em andamento");season=processClubManagementRound({...season,currentRound:task.dueRound});const completed=clubOperationsProfile(season).tasks.find(item=>item.id===task.id)!;expect(completed.status).toBe("Concluída");expect(season.livingWorld.inbox.some(event=>event.title.includes("Relatório concluído"))).toBe(true)});
 it("gera avaliação interna para jogador do próprio elenco",()=>{const season=createSeason("internal",2026),player=season.league.clubs[0].players[0];const result=requestInternalAssessment(season,player.id);const task=clubOperationsProfile(result.state).tasks[0];expect(task.kind).toBe("Relatório interno");expect(task.result).toContain(player.name)});
 it("observa e promove jogador da base para o profissional",()=>{let season=createSeason("academy",2026);const prospect=clubOperationsProfile(season).youth.sort((a,b)=>b.readiness-a.readiness)[0];season=observeYouthProspect(season,prospect.id).state;season=promoteYouthProspect(season,prospect.id).state;expect(season.league.clubs[0].players.some(player=>player.id.includes(prospect.id))).toBe(true);expect(clubOperationsProfile(season).youth.find(item=>item.id===prospect.id)?.promoted).toBe(true)});
 it("diretoria com confiança máxima aprova reforço de orçamento",()=>{const season=createSeason("board",2026);season.livingWorld.boardConfidence=100;season.career.jobSecurity=100;const before=season.league.clubs[0].transferBudgetEur;const result=requestBoardAction(season,"Orçamento de transferências");expect(result.state.league.clubs[0].transferBudgetEur).toBeGreaterThan(before);expect(clubOperationsProfile(result.state).boardRequests[0].approved).toBe(true)});
});
