import type { LeagueClub, LeaguePlayer } from "./league";
import type { MatchResult } from "./match";
import type { ProfessionalCompetitionId } from "../data/brazil-2026/competitions";
import type { WorldCompetitionId, WorldCompetitionsState } from "./world-competitions";
export type CompetitionRule={label:string;listAMax:number;listB:boolean;benchSize:number;maxSubstitutions:number;yellowThreshold:number;yellowAfterFirstBan:number;resetBeforeSemis:boolean;knockoutChanges:number;notes:string[]};
export type CompetitionRegistration={competitionId:WorldCompetitionId;season:number;clubId:string;listAIds:string[];listBIds:string[];changesUsed:number;lastSyncedStage:string};
export type CompetitionDiscipline={competitionId:WorldCompetitionId;playerId:string;yellows:number;yellowSuspensions:number;reds:number;suspensionMatches:number};
export type CompetitionGovernanceState={season:number;registrations:Partial<Record<WorldCompetitionId,CompetitionRegistration>>;discipline:Record<string,CompetitionDiscipline>;notices:string[]};
const UEFA_IDS=new Set<WorldCompetitionId>(["UCL","UEL","UECL"]),CONMEBOL_IDS=new Set<WorldCompetitionId>(["LIB","SUD"]);
const defaultRule=(label:string):CompetitionRule=>({label,listAMax:50,listB:false,benchSize:12,maxSubstitutions:5,yellowThreshold:3,yellowAfterFirstBan:3,resetBeforeSemis:true,knockoutChanges:5,notes:["Lista de competição separada do campeonato nacional.","Suspensões por cartões valem dentro desta competição."]});
export function worldCompetitionRule(id:WorldCompetitionId):CompetitionRule{if(UEFA_IDS.has(id))return{label:"Regulamento UEFA",listAMax:25,listB:true,benchSize:12,maxSubstitutions:5,yellowThreshold:4,yellowAfterFirstBan:2,resetBeforeSemis:true,knockoutChanges:3,notes:["Lista A: máximo de 25; vagas reservadas a atletas formados localmente.","Lista B jovem é adicional quando o atleta cumpre tempo de formação.","Até três novas inscrições podem ser feitas para a fase eliminatória."]};if(CONMEBOL_IDS.has(id))return{...defaultRule("Regulamento CONMEBOL"),listAMax:50,yellowThreshold:3,yellowAfterFirstBan:3,knockoutChanges:5};return defaultRule("Regulamento da copa");}
function countryFor(id:ProfessionalCompetitionId){return id.startsWith("BRA")?"Brasil":id.startsWith("ENG")?"Inglaterra":id.startsWith("ESP")?"Espanha":"França";}
function trained(player:LeaguePlayer,competitionId:ProfessionalCompetitionId){return Boolean((player.clubTrainedYears??0)>=3||player.associationTrained||player.nationality===countryFor(competitionId));}
function buildRegistration(club:LeagueClub,id:WorldCompetitionId,season:number,competitionId:ProfessionalCompetitionId,stage:string):CompetitionRegistration{const rule=worldCompetitionRule(id),players=[...club.players].sort((a,b)=>b.overall-a.overall||b.condition-a.condition),listB=rule.listB?players.filter(p=>p.age<=21&&(p.clubTrainedYears??0)>=2).map(p=>p.id):[],gks=players.filter(p=>p.position==="GOL"&&!listB.includes(p.id)).slice(0,2),locals=players.filter(p=>trained(p,competitionId)&&!gks.some(g=>g.id===p.id)&&!listB.includes(p.id)),localCount=Math.min(8,locals.length),effectiveMax=rule.listB?rule.listAMax-(8-localCount):rule.listAMax,selected=[...gks,...locals.slice(0,localCount)];for(const p of players)if(selected.length<effectiveMax&&!listB.includes(p.id)&&!selected.some(x=>x.id===p.id))selected.push(p);return{competitionId:id,season,clubId:club.id,listAIds:selected.map(p=>p.id),listBIds:listB,changesUsed:0,lastSyncedStage:stage};}
function clubParticipates(world:WorldCompetitionsState,id:WorldCompetitionId,clubId:string){const t=world.tournaments.find(x=>x.definition.id===id);return Boolean(t?.participants.some(p=>p.activeClubId===clubId)||t?.matches.some(m=>m.home.activeClubId===clubId||m.away.activeClubId===clubId));}
export function createCompetitionGovernance(club:LeagueClub,world:WorldCompetitionsState,season:number,competitionId:ProfessionalCompetitionId):CompetitionGovernanceState{const state:CompetitionGovernanceState={season,registrations:{},discipline:{},notices:[]};for(const t of world.tournaments)if(clubParticipates(world,t.definition.id,club.id))state.registrations[t.definition.id]=buildRegistration(club,t.definition.id,season,competitionId,t.currentStage);return state;}
export function hydrateCompetitionGovernance(value:CompetitionGovernanceState|undefined,club:LeagueClub,world:WorldCompetitionsState,season:number,competitionId:ProfessionalCompetitionId){const state=value?.season===season?structuredClone(value):createCompetitionGovernance(club,world,season,competitionId);for(const t of world.tournaments)if(clubParticipates(world,t.definition.id,club.id)&&!state.registrations[t.definition.id])state.registrations[t.definition.id]=buildRegistration(club,t.definition.id,season,competitionId,t.currentStage);return state;}
export function syncCompetitionGovernance(value:CompetitionGovernanceState,club:LeagueClub,world:WorldCompetitionsState,competitionId:ProfessionalCompetitionId){const state=structuredClone(value);for(const t of world.tournaments){if(!clubParticipates(world,t.definition.id,club.id))continue;const reg=state.registrations[t.definition.id];if(!reg){state.registrations[t.definition.id]=buildRegistration(club,t.definition.id,state.season,competitionId,t.currentStage);continue;}const rule=worldCompetitionRule(t.definition.id),knockout=t.definition.stages.findIndex(s=>s.name===t.currentStage)>0;if(knockout&&reg.lastSyncedStage!==t.currentStage&&rule.knockoutChanges>0&&reg.changesUsed<rule.knockoutChanges){const fresh=buildRegistration(club,t.definition.id,state.season,competitionId,t.currentStage),old=new Set(reg.listAIds),newIds=fresh.listAIds.filter(id=>!old.has(id)).slice(0,rule.knockoutChanges-reg.changesUsed);if(newIds.length){const protectedIds=new Set(fresh.listAIds),remove=reg.listAIds.filter(id=>!protectedIds.has(id)).slice(0,newIds.length);reg.listAIds=reg.listAIds.filter(id=>!remove.includes(id)).concat(newIds).slice(0,rule.listAMax);reg.changesUsed+=newIds.length;state.notices.unshift(`${t.definition.shortName}: ${newIds.length} alteração(ões) de inscrição para ${t.currentStage}.`);}}reg.lastSyncedStage=t.currentStage;}state.notices=state.notices.slice(0,20);return state;}
const disciplineKey=(id:WorldCompetitionId,playerId:string)=>`${id}:${playerId}`;
export function eligiblePlayerIds(value:CompetitionGovernanceState,id:WorldCompetitionId,club:LeagueClub){const reg=value.registrations[id];if(!reg)return club.players.map(p=>p.id);const listed=new Set([...reg.listAIds,...reg.listBIds]);return club.players.filter(p=>listed.has(p.id)&&(value.discipline[disciplineKey(id,p.id)]?.suspensionMatches??0)<=0).map(p=>p.id);}
export function governanceSummary(value:CompetitionGovernanceState,id:WorldCompetitionId){const reg=value.registrations[id],rule=worldCompetitionRule(id);if(!reg)return{title:rule.label,detail:"Lista ainda não exigida para o seu clube.",rule};return{title:rule.label,detail:`Lista A ${reg.listAIds.length}/${rule.listAMax}${rule.listB?` • Lista B ${reg.listBIds.length}`:""} • alterações de mata-mata ${reg.changesUsed}/${rule.knockoutChanges}.`,rule};}
export function applyCompetitionDiscipline(value:CompetitionGovernanceState,id:WorldCompetitionId,result:MatchResult,side:"home"|"away",stageBefore:string,stageAfter:string){const state=structuredClone(value),rule=worldCompetitionRule(id);for(const item of Object.values(state.discipline))if(item.competitionId===id&&item.suspensionMatches>0)item.suspensionMatches=Math.max(0,item.suspensionMatches-1);for(const event of result.events.filter(e=>e.team===side&&e.playerId&&(e.type==="card"||e.type==="red_card"))){const playerId=event.playerId!,key=disciplineKey(id,playerId),item=state.discipline[key]??{competitionId:id,playerId,yellows:0,yellowSuspensions:0,reds:0,suspensionMatches:0};if(event.type==="red_card"){item.reds++;item.suspensionMatches=Math.max(item.suspensionMatches,1);}else{item.yellows++;const nextBan=item.yellowSuspensions===0?rule.yellowThreshold:rule.yellowThreshold+item.yellowSuspensions*rule.yellowAfterFirstBan;if(item.yellows>=nextBan){item.yellowSuspensions++;item.suspensionMatches=Math.max(item.suspensionMatches,1);}}state.discipline[key]=item;}if(rule.resetBeforeSemis&&stageBefore==="Quartas de final"&&stageAfter==="Semifinal")for(const item of Object.values(state.discipline))if(item.competitionId===id)item.yellows=0;return state;}
