import { SeededRng } from "./rng";
import type { WorldParticipant } from "./world-competitions";
export type DrawRecord={stage:string;season:number;pots:string[][];groups?:Record<string,string[]>;notes:string[]};
const shuffle=<T>(items:T[],rng:SeededRng)=>{const out=[...items];for(let i=out.length-1;i>0;i--){const j=rng.integer(0,i);[out[i],out[j]]=[out[j],out[i]];}return out;};
function orderedPot(items:WorldParticipant[],rng:SeededRng){return shuffle(items,rng).sort((a,b)=>b.reputation-a.reputation+rng.integer(-1,1));}
export function drawConmebolGroups(participants:WorldParticipant[],seed:string,season:number,stage="Fase de grupos"){const rng=new SeededRng(`${seed}:conmebol-draw:${season}`),ranked=[...participants].sort((a,b)=>b.reputation-a.reputation),pots=[0,1,2,3].map(i=>orderedPot(ranked.slice(i*8,(i+1)*8),rng)),groups:Record<string,WorldParticipant[]>={};for(let i=0;i<8;i++)groups[String.fromCharCode(65+i)]=[];for(let p=0;p<4;p++){const pool=shuffle(pots[p],rng);for(let g=0;g<8;g++){const key=String.fromCharCode(65+g),existing=groups[key],index=pool.findIndex(team=>!existing.some(other=>other.country===team.country));const chosen=pool.splice(index>=0?index:0,1)[0];groups[key].push({...chosen,pot:p+1});}}return{groups:Object.fromEntries(Object.entries(groups).map(([key,value])=>[key,value])),record:{stage,season,pots:pots.map(p=>p.map(x=>x.name)),groups:Object.fromEntries(Object.entries(groups).map(([key,value])=>[key,value.map(x=>x.name)])),notes:["Quatro potes por força/coefficient do save.","Um clube de cada pote por grupo; restrição de mesma associação aplicada quando possível."]} as DrawRecord};}
type Edge={home:WorldParticipant;away:WorldParticipant};
function bestShift(a:WorldParticipant[],b:WorldParticipant[],forbidden:Set<number>){let best=0,bestConf=999;for(let shift=0;shift<b.length;shift++){if(forbidden.has(shift))continue;let conflicts=0;for(let i=0;i<a.length;i++)if(a[i].country===b[(i+shift)%b.length].country)conflicts++;if(conflicts<bestConf){bestConf=conflicts;best=shift;}}return best;}
function arrangeCycle(items:WorldParticipant[],rng:SeededRng){const left=shuffle(items,rng),out:WorldParticipant[]=[];while(left.length){const prev=out.at(-1),index=prev?left.findIndex(x=>x.country!==prev.country):-1;out.push(left.splice(index>=0?index:0,1)[0]);}if(out.length>2&&out[0].country===out.at(-1)?.country){const swap=out.findIndex((x,i)=>i>1&&x.country!==out[0].country&&out[i-1].country!==out.at(-1)?.country);if(swap>0)[out[swap],out[out.length-1]]=[out[out.length-1],out[swap]];}return out;}
function colorEdges(edges:Edge[],rng:SeededRng){for(let attempt=0;attempt<240;attempt++){const order=shuffle(edges,rng),used=new Map<string,Set<number>>(),colors=new Map<Edge,number>();let ok=true;for(const edge of order){const hu=used.get(edge.home.id)??new Set<number>(),au=used.get(edge.away.id)??new Set<number>(),available=[0,1,2,3,4,5,6,7].filter(c=>!hu.has(c)&&!au.has(c));if(!available.length){ok=false;break;}const c=available[rng.integer(0,available.length-1)];colors.set(edge,c);hu.add(c);au.add(c);used.set(edge.home.id,hu);used.set(edge.away.id,au);}if(ok&&[...used.values()].every(set=>set.size===8))return colors;}return null;}
export function drawUefaLeague(participants:WorldParticipant[],seed:string,season:number){const rng=new SeededRng(`${seed}:uefa-draw:${season}`),ranked=[...participants].sort((a,b)=>b.reputation-a.reputation),pots=[0,1,2,3].map(i=>ranked.slice(i*9,(i+1)*9).map(x=>({...x,pot:i+1}))),edges:Edge[]=[];for(const pot of pots){const cycle=arrangeCycle(pot,rng);for(let i=0;i<cycle.length;i++)edges.push({home:cycle[i],away:cycle[(i+1)%cycle.length]});}for(let a=0;a<4;a++)for(let b=a+1;b<4;b++){const pa=arrangeCycle(pots[a],rng),pb=arrangeCycle(pots[b],rng),shift1=bestShift(pa,pb,new Set()),shift2=bestShift(pa,pb,new Set([shift1]));for(let i=0;i<9;i++){edges.push({home:pa[i],away:pb[(i+shift1)%9]});edges.push({home:pb[(i+shift2)%9],away:pa[i]});}}const colors=colorEdges(edges,rng);if(!colors)return null;const rounds=Array.from({length:8},()=>[] as Edge[]);for(const edge of edges)rounds[colors.get(edge)!].push(edge);return{participants:pots.flat(),rounds,record:{stage:"Fase de liga",season,pots:pots.map(p=>p.map(x=>x.name)),notes:["Quatro potes de nove clubes.","Cada clube enfrenta oito adversários: dois de cada pote, com quatro jogos em casa e quatro fora.","Confrontos da mesma associação são evitados pelo algoritmo quando a matriz permite."]} as DrawRecord};}
export function drawSeededKnockout(seeded:WorldParticipant[],unseeded:WorldParticipant[],seed:string){const rng=new SeededRng(`${seed}:seeded-ko`),a=shuffle(seeded,rng),b=shuffle(unseeded,rng),pairs:Array<[WorldParticipant,WorldParticipant]>=[];for(const seedTeam of a){let index=b.findIndex(x=>x.country!==seedTeam.country);if(index<0)index=0;const challenger=b.splice(index,1)[0];if(challenger)pairs.push([challenger,seedTeam]);}return pairs;}
