import type { LeagueClub, LeaguePlayer, LeagueWorld } from "./league";
import { personalityProfile, contractDemandModifier, transferInterestModifier } from "./personality";

const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,Math.round(v)));
function hash(value:string){let h=2166136261;for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function seeded(value:string,min:number,max:number){return min+(hash(value)%(max-min+1));}

export type StaffRole="Adjunto"|"Preparador físico"|"Treinador de goleiros"|"Analista"|"Fisioterapeuta"|"Olheiro"|"Diretor de futebol";
export type StaffMember={id:string;name:string;role:StaffRole;judging:number;tactical:number;motivation:number;fitness:number;medical:number;negotiation:number;youth:number;adaptability:number;overall:number};
const FIRST=["Alexandre","André","Bruno","Carlos","Diego","Eduardo","Fábio","Fernando","Guilherme","Henrique","Marcelo","Paulo","Renato","Ricardo","Rodrigo","Sérgio","Tiago"];
const LAST=["Azevedo","Barros","Campos","Carvalho","Farias","Lopes","Machado","Menezes","Nogueira","Prado","Queiroz","Rezende","Tavares","Vieira"];
const ROLES:StaffRole[]=["Adjunto","Preparador físico","Treinador de goleiros","Analista","Fisioterapeuta","Olheiro","Olheiro","Diretor de futebol"];
export function clubStaff(club:LeagueClub):StaffMember[]{return ROLES.map((role,index)=>{const key=`${club.id}:${club.sourceId}:${role}:${index}`,base=clamp(42+(club.reputation-50)*.55+seeded(`${key}:base`,-8,12),35,94),roleBoost=(target:StaffRole)=>role===target?16:0,attrs={judging:clamp(base+roleBoost("Olheiro")+roleBoost("Diretor de futebol")+seeded(`${key}:j`,-8,8)),tactical:clamp(base+roleBoost("Adjunto")+roleBoost("Analista")+seeded(`${key}:t`,-8,8)),motivation:clamp(base+roleBoost("Adjunto")+seeded(`${key}:m`,-8,8)),fitness:clamp(base+roleBoost("Preparador físico")+seeded(`${key}:f`,-8,8)),medical:clamp(base+roleBoost("Fisioterapeuta")+seeded(`${key}:med`,-8,8)),negotiation:clamp(base+roleBoost("Diretor de futebol")+seeded(`${key}:n`,-8,8)),youth:clamp(base+(role==="Adjunto"||role==="Olheiro"?7:0)+seeded(`${key}:y`,-8,8)),adaptability:clamp(base+seeded(`${key}:a`,-10,10))};const overall=Math.round(Object.values(attrs).reduce((a,b)=>a+b,0)/Object.values(attrs).length);return{id:`staff-${hash(key)}`,name:`${FIRST[seeded(`${key}:fn`,0,FIRST.length-1)]} ${LAST[seeded(`${key}:ln`,0,LAST.length-1)]}`,role,...attrs,overall};});}
export function bestStaff(club:LeagueClub,role:StaffRole){return clubStaff(club).filter(s=>s.role===role).sort((a,b)=>b.overall-a.overall)[0];}
export function delegationQuality(club:LeagueClub,task:"teamTalk"|"lineup"|"scouting"|"medical"|"negotiation"|"youth"){const role:StaffRole=task==="teamTalk"||task==="lineup"?"Adjunto":task==="scouting"?"Olheiro":task==="medical"?"Fisioterapeuta":task==="negotiation"?"Diretor de futebol":"Adjunto",s=bestStaff(club,role);if(!s)return 50;return task==="teamTalk"?Math.round((s.motivation+s.tactical)/2):task==="lineup"?Math.round((s.tactical+s.judging)/2):task==="scouting"?s.judging:task==="medical"?s.medical:task==="negotiation"?s.negotiation:s.youth;}

export type ScoutKnowledgeLevel=0|1|2|3|4|5;
export type ScoutReport={knowledge:ScoutKnowledgeLevel;knowledgeLabel:string;overall:string;potential:string;personality:string;marketValue:string;confidence:number;strengths:string[];risks:string[]};
export function scoutKnowledge(player:LeaguePlayer,userClub:LeagueClub,observationCount=0):ScoutKnowledgeLevel{const scout=delegationQuality(userClub,"scouting"),sameNation=(player.nationality??"")===((userClub.players[0]?.nationality)??"");const familiarity=sameNation?1:0,base=Math.floor((scout-45)/18)+familiarity+Math.floor(observationCount/2);return clamp(base,0,5) as ScoutKnowledgeLevel;}
export function scoutingReport(player:LeaguePlayer,userClub:LeagueClub,observationCount=0):ScoutReport{const knowledge=scoutKnowledge(player,userClub,observationCount),scout=delegationQuality(userClub,"scouting"),spread=Math.max(0,12-knowledge*2-Math.floor((scout-50)/20)),low=clamp(player.overall-spread,35,99),high=clamp(player.overall+spread,35,99),pSpread=Math.max(1,16-knowledge*2-Math.floor((scout-50)/20)),profile=personalityProfile(player),knownPersonality=knowledge>=4?`${profile.headline} • ambição ${profile.ambition} • ego ${profile.ego} • adaptabilidade ${profile.adaptability}`:knowledge>=3?profile.headline:"Desconhecida",knownPotential=knowledge>=5?`${player.potential}`:knowledge>=2?`${clamp(player.potential-pSpread,35,99)}–${clamp(player.potential+pSpread,35,99)}`:"Incerto",value=player.marketValueEur;return{knowledge,knowledgeLabel:["Sem conhecimento","Referência inicial","Observado","Conhecido","Bem conhecido","Dossiê completo"][knowledge],overall:knowledge>=5?`${player.overall}`:`${low}–${high}`,potential:knownPotential,personality:knownPersonality,marketValue:value===null?"Sem referência":knowledge>=3?`€${(value/1_000_000).toFixed(1)} mi`:`€${(Math.max(0,value*.72)/1_000_000).toFixed(1)}–${(value*1.3/1_000_000).toFixed(1)} mi`,confidence:clamp(25+knowledge*14+(scout-50)*.35,20,98),strengths:[player.age<=21?"Margem de desenvolvimento":"Experiência competitiva",profile.professionalism>=70?"Boa abordagem profissional":"Necessita gestão próxima",profile.pressure>=70?"Responde bem à pressão":"Oscila em jogos grandes"],risks:[profile.ego>=75?"Ego alto pode elevar exigências contratuais":"Ego administrável",profile.adaptability<55?"Adaptação a novo contexto pode ser lenta":"Boa capacidade de adaptação"]};}

export type YouthSquad="Sub-17"|"Sub-20";
export type YouthPlan="Físico"|"Técnico"|"Mental"|"Posição"|"Equilibrado";
export type AcademyPlayer={id:string;name:string;age:number;position:string;squad:YouthSquad;overall:number;potential:number;plan:YouthPlan;progress:number;loanRecommended:boolean;personality:string};
const POS=["GOL","LD","ZAG","LE","VOL","MC","MEI","PD","PE","ATA"];
export function academySquads(club:LeagueClub,year:number):AcademyPlayer[]{const structure=Math.max(1,Math.min(5,Math.round((club.reputation-45)/11))),count=structure>=4?20:16;return Array.from({length:count},(_,i)=>{const key=`academy:${club.id}:${year}:${i}`,age=i<count*.45?seeded(`${key}:age`,15,17):seeded(`${key}:age`,17,20),squad:YouthSquad=age<=17?"Sub-17":"Sub-20",overall=seeded(`${key}:ovr`,45+structure,57+structure*2),potential=Math.max(overall+5,seeded(`${key}:pot`,65+structure,84+structure*3)),plans:YouthPlan[]=["Físico","Técnico","Mental","Posição","Equilibrado"],plan=plans[seeded(`${key}:plan`,0,plans.length-1)],progress=clamp(seeded(`${key}:prog`,15,65)+structure*4),pNames=["Arthur","Bernardo","Caio","Davi","Enzo","Gabriel","João","Lucas","Matheus","Pedro","Rafael","Samuel","Vinícius"],lNames=["Almeida","Costa","Ferreira","Gomes","Lima","Martins","Oliveira","Pereira","Ramos","Ribeiro","Santos","Silva","Souza"],personality=["Profissional","Ambicioso","Competitivo","Leal","Reservado","Temperamental"][seeded(`${key}:pers`,0,5)];return{id:`youth-${hash(key)}`,name:`${pNames[seeded(`${key}:fn`,0,pNames.length-1)]} ${lNames[seeded(`${key}:ln`,0,lNames.length-1)]}`,age,position:POS[seeded(`${key}:pos`,0,POS.length-1)],squad,overall,potential,plan,progress,loanRecommended:age>=18&&overall<Math.max(58,club.players.reduce((s,p)=>s+p.overall,0)/Math.max(1,club.players.length)-10),personality};});}
export function annualYouthIntake(club:LeagueClub,year:number){return academySquads(club,year).filter(p=>p.age<=17).sort((a,b)=>b.potential-a.potential).slice(0,6);}
export function youthDevelopmentMultiplier(club:LeagueClub,plan:YouthPlan){const staff=delegationQuality(club,"youth"),structure=Math.max(1,Math.min(5,Math.round((club.reputation-45)/11)));return Math.round((.72+structure*.08+staff/250+(plan==="Equilibrado"?.04:.08))*100)/100;}

export type MedicalDepth={weeklyLoad:number;recurrenceRisk:number;readiness:number;canPlayThroughPain:boolean;doctorOpinion:string;recommendedMinutes:number;injuryHistorySignal:string};
export function medicalDepth(player:LeaguePlayer,club:LeagueClub):MedicalDepth{const physio=delegationQuality(club,"medical"),load=clamp(player.fatigue*.72+(100-player.condition)*.62+(player.minutes>0?Math.min(25,player.minutes/90*8):0)),baseRisk=player.injuryDays>0?45:8,risk=clamp(baseRisk+load*.42+(player.age>=31?8:0)-(physio-50)*.18,3,82),readiness=clamp(player.condition-player.fatigue*.35-(player.injuryDays>0?30:0)+(physio-50)*.08),canPlayThroughPain=player.injuryDays>0&&player.injuryDays<=7&&readiness>=45,rMinutes=readiness>=82?90:readiness>=68?70:readiness>=55?45:readiness>=40?25:0,doctorOpinion=player.injuryDays>0?(canPlayThroughPain?"Pode atuar no sacrifício, mas o risco de agravar a lesão é relevante.":"Não recomendado para competir neste momento."):risk>=50?"Carga alta: reduzir minutos e treino intenso.":risk>=28?"Disponível com monitoramento de carga.":"Liberado sem restrições relevantes.";return{weeklyLoad:load,recurrenceRisk:risk,readiness,recommendedMinutes:rMinutes,canPlayThroughPain,doctorOpinion,injuryHistorySignal:risk>=50?"Histórico e carga elevam risco de reincidência":risk>=28?"Risco moderado de novo problema":"Baixo sinal de reincidência"};}

export type HumanMarketProfile={salaryDemandMultiplier:number;interest:number;agentPressure:number;preferredStatus:string;signingBonusMultiplier:number;rejectionRisk:number;reasons:string[]};
export function humanMarketProfile(player:LeaguePlayer,buyer:LeagueClub,seller?:LeagueClub):HumanMarketProfile{const p=personalityProfile(player),countryChange=Boolean(seller&&seller.players[0]?.nationality!==buyer.players[0]?.nationality),interest=clamp(transferInterestModifier(player,buyer.reputation,countryChange)*68,20,98),agentPressure=clamp((p.ambition+p.ego+p.temperament)/3,20,98),status=p.ego>=78||player.overall>=82?"Jogador-chave":p.ambition>=75?"Titular":"Rotação",salary=contractDemandModifier(player),signing=Math.max(.7,Math.min(1.8,.8+p.ego/130+p.ambition/220)),rejection=clamp(100-interest+(p.loyalty>=80?10:0)+(countryChange&&p.adaptability<55?12:0),2,85),reasons=[buyer.reputation>=75?"Projeto esportivo atrativo":"Prestígio do clube pesa na decisão",p.ambition>=75?"Quer competição continental e protagonismo":"Aceita projeto estável",p.ego>=75?"Empresário cobrará luvas, salário e status altos":"Exigências pessoais moderadas",countryChange&&p.adaptability<55?"Mudança de país é um obstáculo":"Adaptação não deve bloquear o negócio"];return{salaryDemandMultiplier:Math.round(salary*100)/100,interest,agentPressure,preferredStatus:status,signingBonusMultiplier:Math.round(signing*100)/100,rejectionRisk:rejection,reasons};}

export type RivalManager={id:string;name:string;clubId:string;clubName:string;style:string;formation:string;reputation:number;careerYears:number;rivalry:number;provocation:number;jobSecurity:number};
export function managerWorld(league:LeagueWorld,year:number):RivalManager[]{const styles=["Posicional","Pressão alta","Transição","Reativo","Jogo apoiado","Vertical"],forms=["4-2-3-1","4-3-3","4-4-2"],first=["Abel","André","Carlos","Eduardo","Fernando","Gustavo","Jorge","Leonardo","Marcos","Rafael","Renato","Ricardo","Tiago"],last=["Almeida","Barbosa","Ferreira","Jardim","Lima","Martins","Moraes","Oliveira","Pereira","Ramos","Santos","Silva","Souza"];return league.clubs.map((club,i)=>{const key=`manager:${club.id}:${year}`,rep=clamp(club.reputation+seeded(`${key}:rep`,-7,7),35,96);return{id:`mgr-${hash(key)}`,name:`${first[seeded(`${key}:fn`,0,first.length-1)]} ${last[seeded(`${key}:ln`,0,last.length-1)]}`,clubId:club.id,clubName:club.name,style:styles[seeded(`${key}:style`,0,styles.length-1)],formation:forms[seeded(`${key}:form`,0,forms.length-1)],reputation:rep,careerYears:seeded(`${key}:years`,1,18),rivalry:seeded(`${key}:rival`,10,80),provocation:seeded(`${key}:prov`,5,85),jobSecurity:clamp(55+(club.reputation-rep)+seeded(`${key}:job`,-20,20),15,95)};});}
export function managerCareerEvent(manager:RivalManager,position:number,total:number,streak:number){const pressure=(position/Math.max(1,total))*50+Math.max(0,-streak)*8+(100-manager.jobSecurity)*.45;if(pressure>=70)return{type:"Demissão" as const,text:`${manager.name} está sob risco imediato de demissão no ${manager.clubName}.`};if(manager.provocation>=70&&manager.rivalry>=55)return{type:"Provocação" as const,text:`${manager.name} elevou o tom na entrevista e pressionou publicamente o treinador rival.`};return{type:"Estável" as const,text:`${manager.name} mantém seu projeto ${manager.style.toLowerCase()} no ${manager.clubName}.`};}
