import{SeededRng}from"./rng";
import type{LeagueClub,LeaguePlayer,LeagueWorld,OverallHistoryPoint}from"./league";
import type{MatchResult}from"./match";

const clamp=(value:number,min:number,max:number)=>Math.max(min,Math.min(max,value));
const defensivePositions=new Set(["GOL","ZAG","LD","LE","VOL"]);

function teamScore(result:MatchResult,side:"home"|"away"){return side==="home"?{gf:result.homeGoals,ga:result.awayGoals}:{gf:result.awayGoals,ga:result.homeGoals};}
function outcomeDelta(gf:number,ga:number){return gf>ga?.32:gf<ga?-.28:.08;}
function youthBase(age:number){if(age<=18)return.12;if(age<=20)return.09;if(age<=22)return.065;if(age<=24)return.04;if(age<=27)return.018;if(age<=29)return.006;if(age<=31)return-.004;if(age===32)return-.018;if(age===33)return-.032;return-.052;}
function eventCounts(player:LeaguePlayer,result:MatchResult,side:"home"|"away"){const events=result.events.filter(event=>event.team===side),goals=events.filter(event=>event.type==="goal"&&event.playerId===player.id).length,assists=events.filter(event=>event.type==="goal"&&event.assistPlayerId===player.id).length,shots=events.filter(event=>(event.type==="goal"||event.type==="chance")&&event.playerId===player.id).length,yellows=events.filter(event=>event.type==="card"&&event.playerId===player.id).length;return{goals,assists,shots,yellows};}
function matchRating(player:LeaguePlayer,result:MatchResult,side:"home"|"away",started:boolean){const liveRating=result.playerRatings?.[player.id];if(liveRating!==undefined)return clamp(Math.round(liveRating*100)/100,4.5,10);const{gf,ga}=teamScore(result,side),counts=eventCounts(player,result,side);let rating=6.35+outcomeDelta(gf,ga)+(started?.06:0)+counts.goals*.78+counts.assists*.46+Math.max(0,counts.shots-counts.goals)*.04-counts.yellows*.18;if(ga===0&&defensivePositions.has(player.position))rating+=player.position==="GOL"?.48:.26;if(ga>=3&&defensivePositions.has(player.position))rating-=Math.min(.55,(ga-2)*.18);return clamp(Math.round(rating*100)/100,4.5,10);}
function recordOverall(player:LeaguePlayer,year:number,round:number,reason:OverallHistoryPoint["reason"]){const history=player.overallHistory??[];const last=history[history.length-1];if(last?.overall===player.overall&&last.year===year&&last.round===round)return;player.overallHistory=[...history.slice(-11),{year,round,overall:player.overall,reason}];}
function applyProgress(player:LeaguePlayer,rating:number|undefined,played:boolean,year:number,round:number,seed:string){const rng=new SeededRng(`${seed}:${player.id}:dev:${year}:${round}`),gap=Math.max(0,(player.potential??player.overall)-player.overall),potentialFactor=gap>0?Math.min(1.45,.65+gap*.055):0,performance=played&&rating!==undefined?(rating-6.5)*.045:0,minutesFactor=played?1:player.age<=23?.18:.55;let delta=youthBase(player.age)*minutesFactor+performance+(played&&gap>0?.018*potentialFactor:0);if(player.age>=32)delta-=.012;if(player.age<=23&&!played)delta-=.006;delta+=rng.integer(-4,4)/1000;player.developmentProgress=(player.developmentProgress??0)+delta;
 while(player.developmentProgress>=1&&player.overall<player.potential){player.overall++;player.developmentProgress-=1;recordOverall(player,year,round,"forma");}
 while(player.developmentProgress<=-1&&player.overall>45){player.overall--;player.developmentProgress+=1;recordOverall(player,year,round,player.age>=32?"idade":"forma");}
 player.form=clamp(Math.round((player.form*.72+(rating??6.3)*.28)*10)/10,1,10);
}

export function applySportingStatsAndDevelopment(club:LeagueClub,result:MatchResult,side:"home"|"away",participantIds:string[],starterIds:string[],round:number,year:number,seed:string){const participants=new Set(participantIds),starters=new Set(starterIds),{gf,ga}=teamScore(result,side);for(const player of club.players){const played=participants.has(player.id),started=starters.has(player.id);if(played){const counts=eventCounts(player,result,side),rating=matchRating(player,result,side,started);player.appearances=(player.appearances??0)+1;if(started)player.starts=(player.starts??0)+1;player.minutes=(player.minutes??0)+(result.playerMinutes?.[player.id]??(started?75:25));player.goals=(player.goals??0)+counts.goals;player.assists=(player.assists??0)+counts.assists;player.shots=(player.shots??0)+counts.shots;player.yellowCards=(player.yellowCards??0)+counts.yellows;if(gf>ga)player.wins=(player.wins??0)+1;else if(gf<ga)player.losses=(player.losses??0)+1;else player.draws=(player.draws??0)+1;if(ga===0&&defensivePositions.has(player.position))player.cleanSheets=(player.cleanSheets??0)+1;player.lastRating=rating;player.ratingTotal=(player.ratingTotal??0)+rating;player.ratedMatches=(player.ratedMatches??0)+1;player.averageRating=Math.round(player.ratingTotal/player.ratedMatches*100)/100;applyProgress(player,rating,true,year,round,seed);}else applyProgress(player,undefined,false,year,round,seed);}}

function ageDecline(age:number){if(age<=32)return 0;if(age===33)return 1;if(age===34)return 1;if(age===35)return 2;return 2;}
export function preparePlayerDevelopmentNextSeason(league:LeagueWorld,nextYear:number){for(const club of league.clubs){for(const player of club.players){player.age=(player.age??20)+1;const decline=ageDecline(player.age);if(decline){player.overall=Math.max(45,player.overall-decline);player.developmentProgress=Math.min(0,player.developmentProgress??0);recordOverall(player,nextYear,0,"idade");}player.potential=Math.max(player.overall,Math.min(95,(player.potential??player.overall)-(player.age>=31?1:0)));player.seasonStartOverall=player.overall;player.goals=0;player.assists=0;player.shots=0;player.yellowCards=0;player.redCards=0;player.wins=0;player.draws=0;player.losses=0;player.cleanSheets=0;player.ratingTotal=0;player.ratedMatches=0;player.averageRating=0;player.lastRating=0;player.appearances=0;player.starts=0;player.minutes=0;recordOverall(player,nextYear,0,"temporada");}}return league;}

export function overallTrend(player:LeaguePlayer){return player.overall-(player.seasonStartOverall??player.overall);}
