import { SeededRng } from "./rng";
import type { LeagueClub, LeaguePlayer, LeagueWorld, PlayerPersonality } from "./league";
import type { ClubAiState } from "./club-ai";
import type { MatchResult, MatchTactic, MatchSetPieces } from "./match";

export type HiddenPlayerTraits={professionalism:number;ambition:number;loyalty:number;temperament:number;pressure:number;adaptability:number};
export type StaffRole="Adjunto"|"Preparador físico"|"Treinador de goleiros"|"Analista de desempenho"|"Fisioterapeuta"|"Olheiro-chefe"|"Diretor de futebol"|"Responsável pela base";
export type StaffMember={id:string;name:string;role:StaffRole;ability:number;tactics:number;people:number;fitness:number;medical:number;judgingAbility:number;judgingPotential:number;negotiation:number;youth:number;salaryBrlMonthly:number;contractEndYear:number};
export type ScoutingReport={playerId:string;clubId:string;knowledge:number;lastScoutedDate:string;estimatedOverall:[number,number];estimatedPotential:[number,number];fit:number;risks:string[]};
export type ScoutingAssignment={id:string;name:string;scope:"Brasil"|"América do Sul"|"Europa"|"Jovens";focus:string;progress:number;active:boolean};
export type YouthSquad="Sub-17"|"Sub-20";
export type YouthStatus="Base"|"Promovido"|"Dispensado";
export type YouthProspect={id:string;name:string;position:string;age:number;overall:number;potential:number;personality:PlayerPersonality;squad:YouthSquad;status:YouthStatus;generatedYear:number;development:number};
export type MedicalProfile={playerId:string;injuryRisk:number;recurrenceRisk:number;advice:string;minutesRestriction?:number;lastAssessment:string};
export type SetPiecePlan=MatchSetPieces;
export type Mentorship={mentorId:string;menteeId:string;chemistry:number};
export type ManagerRelation={managerName:string;clubId:string;respect:number;rivalry:number;meetings:number;lastRound?:number;lastResult?:string};
export type WeeklyDigest={date:string;title:string;headlines:string[]};
export type FootballNotification={id:string;date:string;kind:"Scouting"|"Base"|"Médico"|"Staff"|"Rivalidade";text:string};
export type FootballDepthState={
 clubId:string;sequence:number;staff:StaffMember[];scoutingReports:ScoutingReport[];assignments:ScoutingAssignment[];youth:YouthProspect[];medical:MedicalProfile[];setPieces:SetPiecePlan;mentorships:Mentorship[];managerRelations:ManagerRelation[];favorites:string[];comparison:string[];weeklyDigests:WeeklyDigest[];notifications:FootballNotification[];lastProcessedDate?:string;lastYouthIntakeYear?:number;
};

const FIRST=["André","Bruno","Caio","Daniel","Eduardo","Felipe","Gustavo","Henrique","Igor","João","Lucas","Marcelo","Nuno","Paulo","Rafael","Renato","Thiago","Victor"];
const LAST=["Almeida","Barbosa","Costa","Faria","Ferreira","Freire","Lima","Martins","Mendes","Moraes","Nunes","Pereira","Prado","Rezende","Ribeiro","Salles","Santos","Tavares"];
const YOUTH_FIRST=["Arthur","Breno","Caio","Davi","Enzo","Gabriel","Heitor","João","Kauã","Lucca","Matheus","Miguel","Pedro","Rafael","Samuel","Theo","Vitor","Yuri"];
const YOUTH_LAST=["Alves","Barbosa","Cardoso","Costa","Dias","Ferreira","Gomes","Lima","Martins","Melo","Mendes","Oliveira","Pereira","Ribeiro","Rocha","Santos","Silva","Souza"];
const POSITIONS=["GOL","ZAG","ZAG","LD","LE","VOL","MC","MC","MEI","PE","PD","ATA"];
const PERSONALITIES:PlayerPersonality[]=["Profissional","Ambicioso","Competitivo","Leal","Reservado","Temperamental"];
const clamp=(value:number,min=0,max=100)=>Math.max(min,Math.min(max,Math.round(value)));
const dateOrdinal=(iso:string)=>Math.floor(new Date(`${iso}T12:00:00Z`).getTime()/86400000);

function traitBase(personality:PlayerPersonality,key:keyof HiddenPlayerTraits){
 const map:Record<PlayerPersonality,Partial<Record<keyof HiddenPlayerTraits,number>>>={
  Profissional:{professionalism:82,temperament:70,pressure:68},Ambicioso:{ambition:86,loyalty:44,pressure:72},Competitivo:{ambition:76,pressure:82,temperament:58},Leal:{loyalty:88,professionalism:70,adaptability:58},Reservado:{temperament:76,pressure:62,adaptability:58},Temperamental:{temperament:30,pressure:58,professionalism:52},
 };
 return map[personality][key]??62;
}
export function hiddenPlayerTraits(player:LeaguePlayer,seed="v90"):HiddenPlayerTraits{
 const rng=new SeededRng(`${seed}:hidden:${player.transfermarktId||player.id}`),keys:(keyof HiddenPlayerTraits)[]=["professionalism","ambition","loyalty","temperament","pressure","adaptability"],out={} as HiddenPlayerTraits;
 for(const key of keys)out[key]=clamp(traitBase(player.personality,key)+rng.integer(-18,18),18,96);
 return out;
}

function staffName(rng:SeededRng){return`${rng.pick(FIRST)} ${rng.pick(LAST)}`;}
function staffMember(role:StaffRole,rng:SeededRng,year:number,index:number):StaffMember{
 const primary=clamp(rng.integer(58,88)+(role==="Diretor de futebol"||role==="Adjunto"?3:0),40,95),secondary=()=>clamp(primary+rng.integer(-20,14),30,96);
 return{id:`staff-${index}-${role.replace(/\s/g,"-").toLowerCase()}`,name:staffName(rng),role,ability:primary,tactics:secondary(),people:secondary(),fitness:role==="Preparador físico"?clamp(primary+5):secondary(),medical:role==="Fisioterapeuta"?clamp(primary+7):secondary(),judgingAbility:role==="Olheiro-chefe"?clamp(primary+7):secondary(),judgingPotential:role==="Olheiro-chefe"||role==="Responsável pela base"?clamp(primary+6):secondary(),negotiation:role==="Diretor de futebol"?clamp(primary+8):secondary(),youth:role==="Responsável pela base"?clamp(primary+8):secondary(),salaryBrlMonthly:Math.round((25_000+primary*1_250)/5_000)*5_000,contractEndYear:year+rng.integer(1,3)};
}
function createStaff(seed:string,clubId:string,year:number){const rng=new SeededRng(`${seed}:staff:${clubId}:${year}`),roles:StaffRole[]=["Adjunto","Preparador físico","Treinador de goleiros","Analista de desempenho","Fisioterapeuta","Olheiro-chefe","Diretor de futebol","Responsável pela base"];return roles.map((role,index)=>staffMember(role,rng,year,index));}
export function staffByRole(depth:FootballDepthState|undefined,role:StaffRole){return depth?.staff.find(item=>item.role===role);}
export function staffQuality(depth:FootballDepthState|undefined,role:StaffRole){return staffByRole(depth,role)?.ability??65;}
export function negotiationStaffBonus(depth:FootballDepthState|undefined){const director=staffByRole(depth,"Diretor de futebol");return director?Math.round((director.negotiation-60)*.22):0;}

function defaultAssignments():ScoutingAssignment[]{return[
 {id:"scout-domestic",name:"Mercado nacional",scope:"Brasil",focus:"Titulares e oportunidades",progress:0,active:true},
 {id:"scout-south",name:"Talentos sul-americanos",scope:"América do Sul",focus:"Até 23 anos e alto potencial",progress:0,active:true},
 {id:"scout-europe",name:"Mercado europeu",scope:"Europa",focus:"Jogadores adaptáveis e oportunidades",progress:0,active:false},
 {id:"scout-youth",name:"Jovens",scope:"Jovens",focus:"Sub-21 com margem de evolução",progress:0,active:true},
];}
function youthIntake(seed:string,club:LeagueClub,year:number,quality:number,count=7):YouthProspect[]{const rng=new SeededRng(`${seed}:academy:${club.id}:${year}`),base=Math.max(46,Math.min(68,Math.round(club.reputation*.55+quality*.18)));return Array.from({length:count},(_,index)=>{const age=rng.integer(15,19),overall=clamp(base+rng.integer(-7,5),42,72),potential=clamp(overall+rng.integer(age<=16?9:5,age<=17?20:16)+Math.round((quality-60)/8),overall,94);return{id:`academy-${club.id}-${year}-${index}`,name:`${rng.pick(YOUTH_FIRST)} ${rng.pick(YOUTH_LAST)}`,position:rng.pick(POSITIONS),age,overall,potential,personality:rng.pick(PERSONALITIES),squad:age<=16?"Sub-17":"Sub-20",status:"Base",generatedYear:year,development:0};});}
function defaultSetPieces(club:LeagueClub):SetPiecePlan{const eligible=[...club.players].sort((a,b)=>b.overall-a.overall),target=[...club.players].filter(p=>p.position==="ZAG"||p.position==="ATA").sort((a,b)=>b.overall-a.overall)[0],creative=[...club.players].filter(p=>["MEI","MC","PD","PE"].includes(p.position)).sort((a,b)=>b.overall-a.overall)[0];return{cornerAttack:"Segundo pau",cornerDefense:"Mista",freeKickTakerId:creative?.id??eligible[0]?.id,penaltyTakerId:[...club.players].filter(p=>["ATA","MEI","PD","PE"].includes(p.position)).sort((a,b)=>b.overall-a.overall)[0]?.id??eligible[0]?.id,targetId:target?.id??eligible[0]?.id};}
function medicalFor(player:LeaguePlayer,date:string,physio=65):MedicalProfile{const ageRisk=player.age>=33?14:player.age>=30?7:player.age<=20?-3:0,injury=player.injuryDays>0?32:0,risk=clamp(7+player.fatigue*.58+(100-player.condition)*.42+ageRisk+injury-(physio-60)*.16,2,96),recurrence=clamp((player.injuryDays>0?55:12)+player.fatigue*.25+Math.max(0,player.age-29)*2-(physio-60)*.12,3,92),advice=player.injuryDays>0?"Em recuperação; evite retorno antecipado.":risk>=72?"Risco alto: rotação e limite de minutos recomendados.":risk>=52?"Risco moderado: monitore carga e recuperação.":"Apto para carga normal.";return{playerId:player.id,injuryRisk:risk,recurrenceRisk:recurrence,advice,minutesRestriction:risk>=72?60:risk>=60?75:undefined,lastAssessment:date};}
function mentorships(club:LeagueClub):Mentorship[]{const mentors=[...club.players].filter(p=>p.age>=27&&(p.squadRole==="Líder"||p.squadRole==="Titular")&&["Profissional","Leal","Competitivo"].includes(p.personality)).sort((a,b)=>b.managerTrust-a.managerTrust||b.overall-a.overall),young=[...club.players].filter(p=>p.age<=22).sort((a,b)=>b.potential-a.potential);return young.slice(0,Math.min(5,mentors.length)).map((mentee,index)=>{const same=mentors.filter(m=>m.position===mentee.position),mentor=(same[index%same.length]??mentors[index%mentors.length]);return{mentorId:mentor.id,menteeId:mentee.id,chemistry:clamp(55+(mentor.personality==="Profissional"?12:0)+(mentor.position===mentee.position?10:0)-Math.abs(mentor.age-mentee.age),35,94)};});}
function notification(depth:FootballDepthState,date:string,kind:FootballNotification["kind"],text:string){depth.sequence++;depth.notifications=[{id:`depth-${depth.sequence}`,date,kind,text},...depth.notifications].slice(0,80);}

export function createFootballDepth(league:LeagueWorld,clubId:string,seed:string,year:number):FootballDepthState{const club=league.clubs.find(c=>c.id===clubId)??league.clubs[0],staff=createStaff(seed,club.id,year),youthQuality=staff.find(s=>s.role==="Responsável pela base")?.youth??65,physio=staff.find(s=>s.role==="Fisioterapeuta")?.medical??65;return{clubId:club.id,sequence:0,staff,scoutingReports:[],assignments:defaultAssignments(),youth:youthIntake(seed,club,year,youthQuality),medical:club.players.map(p=>medicalFor(p,`${year}-01-01`,physio)),setPieces:defaultSetPieces(club),mentorships:mentorships(club),managerRelations:[],favorites:[],comparison:[],weeklyDigests:[],notifications:[],lastYouthIntakeYear:year};}
export function hydrateFootballDepth(value:FootballDepthState|undefined,league:LeagueWorld,clubId:string,seed:string,year:number):FootballDepthState{const club=league.clubs.find(c=>c.id===clubId)??league.clubs[0],base=createFootballDepth(league,club.id,seed,year);if(!value)return base;if(value.clubId!==club.id)return{...base,scoutingReports:value.scoutingReports??[],managerRelations:value.managerRelations??[],favorites:value.favorites??[],comparison:value.comparison??[],weeklyDigests:value.weeklyDigests??[],notifications:value.notifications??[],sequence:value.sequence??0};const staff=value.staff?.length?value.staff:base.staff,physio=staff.find(s=>s.role==="Fisioterapeuta")?.medical??65,medicalById=new Map((value.medical??[]).map(m=>[m.playerId,m]));return{...base,...value,clubId:club.id,staff,assignments:value.assignments?.length?value.assignments:base.assignments,youth:value.youth?.length?value.youth:base.youth,medical:club.players.map(p=>medicalById.get(p.id)??medicalFor(p,value.lastProcessedDate??`${year}-01-01`,physio)),setPieces:{...base.setPieces,...(value.setPieces??{})},mentorships:value.mentorships?.length?value.mentorships:mentorships(club),managerRelations:value.managerRelations??[],favorites:value.favorites??[],comparison:(value.comparison??[]).slice(0,2),weeklyDigests:value.weeklyDigests??[],notifications:value.notifications??[],sequence:value.sequence??0};}

function reportRanges(player:LeaguePlayer,knowledge:number,rng:SeededRng):{overall:[number,number];potential:[number,number]}{const spread=knowledge>=90?0:knowledge>=70?1:knowledge>=50?3:knowledge>=30?5:8,bias=knowledge>=70?0:rng.integer(-2,2),lowO=clamp(player.overall+bias-spread,35,99),highO=clamp(player.overall+bias+spread,35,99),lowP=clamp(player.potential+bias-spread-1,lowO,99),highP=clamp(player.potential+bias+spread+1,lowP,99);return{overall:[lowO,highO],potential:[lowP,highP]};}
function reportRisks(player:LeaguePlayer,seed:string,knowledge:number){if(knowledge<35)return["Pouco observado"];const traits=hiddenPlayerTraits(player,seed),risks:string[]=[];if(traits.adaptability<42)risks.push("Adaptação pode ser lenta");if(traits.temperament<40)risks.push("Temperamento exige gestão");if(traits.loyalty<38&&traits.ambition>72)risks.push("Pode buscar salto rápido de carreira");if(player.injuryDays>0||player.fatigue>65)risks.push("Carga física merece atenção");return risks.length?risks:["Sem alerta relevante no momento"];}
function playerFit(player:LeaguePlayer,club:LeagueClub,seed:string){const traits=hiddenPlayerTraits(player,seed),need=club.players.filter(p=>p.position===player.position).length<=2?14:0,youth=player.age<=23?Math.max(0,player.potential-player.overall)*2:0;return clamp(48+(player.overall-club.players.reduce((s,p)=>s+p.overall,0)/Math.max(1,club.players.length))*2+need+youth+traits.professionalism*.08,20,96);}
export function scoutingSnapshot(depth:FootballDepthState|undefined,player:LeaguePlayer,playerClubId:string,selectedClubId:string,seed:string){if(playerClubId===selectedClubId){const traits=hiddenPlayerTraits(player,seed);return{knowledge:100,overall:[player.overall,player.overall] as [number,number],potential:[player.potential,player.potential] as [number,number],personality:player.personality,traits,fit:100,risks:reportRisks(player,seed,100),marketKnown:true};}const report=depth?.scoutingReports.find(r=>r.playerId===player.id),knowledge=report?.knowledge??12,rng=new SeededRng(`${seed}:scout-view:${player.id}:${knowledge}`),ranges=report?{overall:report.estimatedOverall,potential:report.estimatedPotential}:reportRanges(player,knowledge,rng);return{knowledge,overall:ranges.overall,potential:ranges.potential,personality:knowledge>=70?player.personality:"Desconhecida",traits:knowledge>=82?hiddenPlayerTraits(player,seed):undefined,fit:report?.fit??50,risks:report?.risks??["Relatório incompleto"],marketKnown:knowledge>=45};}
export function requestScouting(depth:FootballDepthState,league:LeagueWorld,selectedClubId:string,playerId:string,date:string,seed:string){const next=structuredClone(depth),found=league.clubs.flatMap(c=>c.players.map(player=>({club:c,player}))).find(x=>x.player.id===playerId);if(!found||found.club.id===selectedClubId)return next;const scout=staffByRole(next,"Olheiro-chefe"),gain=clamp(22+(scout?.judgingAbility??65)/5,20,42),existing=next.scoutingReports.find(r=>r.playerId===playerId),knowledge=clamp((existing?.knowledge??10)+gain),rng=new SeededRng(`${seed}:manual-scout:${playerId}:${date}`),ranges=reportRanges(found.player,knowledge,rng),club=league.clubs.find(c=>c.id===selectedClubId)!;const report:ScoutingReport={playerId,clubId:found.club.id,knowledge,lastScoutedDate:date,estimatedOverall:ranges.overall,estimatedPotential:ranges.potential,fit:playerFit(found.player,club,seed),risks:reportRisks(found.player,seed,knowledge)};next.scoutingReports=[report,...next.scoutingReports.filter(r=>r.playerId!==playerId)].slice(0,160);notification(next,date,"Scouting",`${found.player.name}: conhecimento subiu para ${knowledge}% e o encaixe estimado é ${report.fit}%.`);return next;}

export function processFootballDepthDay(value:FootballDepthState|undefined,league:LeagueWorld,clubId:string,date:string,seed:string,year:number,options:{autoScout:boolean;youthDelegated:boolean}):FootballDepthState{const next=hydrateFootballDepth(value,league,clubId,seed,year);if(next.lastProcessedDate===date)return next;next.lastProcessedDate=date;const club=league.clubs.find(c=>c.id===clubId)??league.clubs[0],ordinal=dateOrdinal(date),physio=staffByRole(next,"Fisioterapeuta"),fitness=staffByRole(next,"Preparador físico"),academy=staffByRole(next,"Responsável pela base"),assistant=staffByRole(next,"Adjunto"),scout=staffByRole(next,"Olheiro-chefe");
 next.medical=club.players.map(player=>medicalFor(player,date,physio?.medical??65));
 if((physio?.medical??0)>=76&&ordinal%3===0)for(const player of club.players)if(player.injuryDays>1)player.injuryDays=Math.max(0,player.injuryDays-1);
 if(ordinal%4===0)for(const player of club.players){if(player.injuryDays>0)continue;if((fitness?.fitness??65)>=72){player.fatigue=Math.max(0,player.fatigue-1);if(player.condition<100)player.condition=Math.min(100,player.condition+1);}if(player.age<=23&&(academy?.youth??65)>=72)player.developmentProgress+=.015;if((assistant?.people??65)>=75&&player.morale<94)player.morale=Math.min(100,player.morale+1);}
 for(const pair of next.mentorships){if(ordinal%5!==0)break;const mentor=club.players.find(p=>p.id===pair.mentorId),mentee=club.players.find(p=>p.id===pair.menteeId);if(mentor&&mentee&&mentor.happiness>=55){mentee.developmentProgress+=pair.chemistry/6000;mentee.managerTrust=clamp(mentee.managerTrust+1);}}
 for(const prospect of next.youth)if(prospect.status==="Base"&&ordinal%4===0){const boost=(academy?.youth??65)+(options.youthDelegated?6:0);prospect.development+=boost/260;while(prospect.development>=100&&prospect.overall<prospect.potential){prospect.overall++;prospect.development-=100;}}
 for(const assignment of next.assignments)if(assignment.active)assignment.progress=clamp(assignment.progress+Math.max(2,Math.round((scout?.judgingAbility??65)/18)),0,100);
 if(options.autoScout&&ordinal%3===0){const rng=new SeededRng(`${seed}:autoscout:${date}`),pool=league.clubs.flatMap(c=>c.id===clubId?[]:c.players.map(player=>({club:c,player}))).filter(x=>x.player.injuryDays<20).sort((a,b)=>(b.player.potential+b.player.overall)-(a.player.potential+a.player.overall));for(let i=0;i<Math.min(3,pool.length);i++){const item=pool[(i+rng.integer(0,Math.min(18,pool.length-1)))%pool.length],existing=next.scoutingReports.find(r=>r.playerId===item.player.id),knowledge=clamp((existing?.knowledge??8)+8+Math.round((scout?.judgingPotential??65)/12)),ranges=reportRanges(item.player,knowledge,rng),report:ScoutingReport={playerId:item.player.id,clubId:item.club.id,knowledge,lastScoutedDate:date,estimatedOverall:ranges.overall,estimatedPotential:ranges.potential,fit:playerFit(item.player,club,seed),risks:reportRisks(item.player,seed,knowledge)};next.scoutingReports=[report,...next.scoutingReports.filter(r=>r.playerId!==item.player.id)].slice(0,160);}}
 const highRisk=next.medical.filter(m=>m.injuryRisk>=72);if(highRisk.length&&ordinal%5===0){const names=highRisk.slice(0,3).map(m=>club.players.find(p=>p.id===m.playerId)?.name).filter(Boolean);if(names.length)notification(next,date,"Médico",`Carga elevada: ${names.join(", ")} ${names.length===1?"precisa":"precisam"} de atenção.`);}
 if(ordinal%7===0&&next.weeklyDigests[0]?.date!==date){const topScout=[...next.scoutingReports].sort((a,b)=>b.fit-a.fit)[0],topYouth=[...next.youth].filter(y=>y.status==="Base").sort((a,b)=>b.potential-a.potential)[0],headlines=[highRisk.length?`${highRisk.length} atleta(s) em risco físico alto.`:"Departamento médico sem alerta crítico.",topScout?`Scouting destaca encaixe ${topScout.fit}% em um alvo observado.`:"Rede de scouting ainda construindo relatórios.",topYouth?`${topYouth.name} lidera a base com potencial ${topYouth.potential}.`:"Sem jovem em destaque nesta semana.",`Coesão de staff: adjunto ${assistant?.ability??65}, olheiro ${scout?.ability??65}, fisioterapia ${physio?.ability??65}.`];next.weeklyDigests=[{date,title:"Resumo da semana",headlines},...next.weeklyDigests].slice(0,30);}
 return next;}

export function processFootballDepthAfterMatch(value:FootballDepthState,club:LeagueClub,result:MatchResult,side:"home"|"away",date:string){const next=structuredClone(value),injuries=result.events.filter(e=>e.type==="injury"&&e.team===side).map(e=>club.players.find(p=>p.id===e.playerId)?.name).filter((x):x is string=>Boolean(x));if(injuries.length)notification(next,date,"Médico",`Pós-jogo: ${injuries.join(", ")} deixou/deixaram a partida com problema físico.`);return next;}
export function recordManagerEncounter(value:FootballDepthState,clubAi:ClubAiState|undefined,opponentClubId:string|undefined,gf:number,ga:number,round:number,date:string){if(!opponentClubId)return value;const manager=clubAi?.managers.find(m=>m.clubId===opponentClubId);if(!manager)return value;const next=structuredClone(value),existing=next.managerRelations.find(r=>r.managerName===manager.managerName),result=gf>ga?"vitória":gf<ga?"derrota":"empate",deltaRivalry=Math.abs(gf-ga)<=1?3:1,relation:ManagerRelation=existing??{managerName:manager.managerName,clubId:opponentClubId,respect:50,rivalry:18,meetings:0};relation.clubId=opponentClubId;relation.meetings++;relation.lastRound=round;relation.lastResult=result;relation.respect=clamp(relation.respect+(gf>ga?2:gf<ga?1:2));relation.rivalry=clamp(relation.rivalry+deltaRivalry+(relation.meetings>=3?2:0));next.managerRelations=[relation,...next.managerRelations.filter(r=>r.managerName!==manager.managerName)];if(relation.rivalry>=55&&relation.meetings>=3&&relation.meetings%2===1)notification(next,date,"Rivalidade",`A rivalidade profissional com ${manager.managerName} está crescendo após ${relation.meetings} confrontos.`);return next;}

export function prepareFootballDepthNextSeason(value:FootballDepthState|undefined,league:LeagueWorld,clubId:string,seed:string,year:number):FootballDepthState{let next=hydrateFootballDepth(value,league,clubId,seed,year);const club=league.clubs.find(c=>c.id===clubId)??league.clubs[0];next={...next,clubId:club.id,lastProcessedDate:undefined,medical:club.players.map(p=>medicalFor(p,`${year}-01-01`,staffByRole(next,"Fisioterapeuta")?.medical??65)),mentorships:mentorships(club)};next.youth=next.youth.map(y=>({...y,age:y.status==="Base"?y.age+1:y.age})).filter(y=>y.status!=="Base"||y.age<=20);if(next.lastYouthIntakeYear!==year){const quality=staffByRole(next,"Responsável pela base")?.youth??65;next.youth=[...youthIntake(seed,club,year,quality),...next.youth].slice(0,28);next.lastYouthIntakeYear=year;notification(next,`${year}-01-05`,"Base",`Nova geração da base chegou com ${next.youth.filter(y=>y.generatedYear===year).length} jogadores.`);}return next;}

export function promoteYouthProspect(value:FootballDepthState,club:LeagueClub,prospectId:string,year:number,seed:string){const next=structuredClone(value),prospect=next.youth.find(y=>y.id===prospectId&&y.status==="Base");if(!prospect)return{depth:next,player:undefined as LeaguePlayer|undefined};const rng=new SeededRng(`${seed}:promote:${prospect.id}:${year}`),player:LeaguePlayer={id:`${club.id}-academy-${year}-${rng.integer(1000,9999)}`,transfermarktId:`academy-${prospect.id}`,name:prospect.name,position:prospect.position,age:prospect.age,nationality:"Brasil",marketValueEur:Math.max(120_000,(prospect.overall-50)*180_000),marketValueUpdated:`${year}-01-05`,overall:prospect.overall,potential:prospect.potential,seasonStartOverall:prospect.overall,developmentProgress:prospect.development/100,overallHistory:[{year,round:0,overall:prospect.overall,reason:"início"}],morale:74,condition:96,fatigue:2,form:6,goals:0,assists:0,shots:0,yellowCards:0,redCards:0,wins:0,draws:0,losses:0,cleanSheets:0,ratingTotal:0,ratedMatches:0,averageRating:0,lastRating:0,injuryDays:0,suspensionMatches:0,status:"Promessa",personality:prospect.personality,squadRole:"Promessa",happiness:82,managerTrust:68,appearances:0,starts:0,minutes:0,promises:[],contract:{salaryBrlMonthly:Math.round((28_000+prospect.overall*900)/5_000)*5_000,startYear:year,endYear:year+3,agentName:`Agência ${prospect.name.split(" ").at(-1)}`,releaseClauseEur:null},transferListed:false,wantsToLeave:false,joinedClubYear:year-2,clubTrainedYears:2,associationTrained:true};prospect.status="Promovido";club.players.push(player);next.mentorships=mentorships(club);notification(next,`${year}-01-06`,"Base",`${prospect.name} foi promovido ao elenco principal.`);return{depth:next,player};}
export function toggleFavorite(value:FootballDepthState,playerId:string){const next=structuredClone(value);next.favorites=next.favorites.includes(playerId)?next.favorites.filter(id=>id!==playerId):[playerId,...next.favorites].slice(0,40);return next;}
export function toggleComparison(value:FootballDepthState,playerId:string){const next=structuredClone(value);next.comparison=next.comparison.includes(playerId)?next.comparison.filter(id=>id!==playerId):[...next.comparison,playerId].slice(-2);return next;}
export function updateSetPiecePlan(value:FootballDepthState,patch:Partial<SetPiecePlan>){return{...value,setPieces:{...value.setPieces,...patch}};}
export function withSetPiecePlan(tactic:MatchTactic,depth:FootballDepthState|undefined):MatchTactic{return depth?{...tactic,setPieces:{...depth.setPieces}}:tactic;}

export function playerTransferInterest(player:LeaguePlayer,buyer:LeagueClub,seller:LeagueClub,salaryBrlMonthly:number,seed:string){const traits=hiddenPlayerTraits(player,seed),raise=(salaryBrlMonthly/Math.max(1,player.contract.salaryBrlMonthly)-1)*100,prestige=(buyer.reputation-seller.reputation)*1.7,score=clamp(48+prestige+raise*.45+(traits.ambition-50)*.22-(traits.loyalty-50)*.2+(traits.adaptability-50)*.12+(player.wantsToLeave?20:0)+(player.happiness<50?10:0),6,97),summary=score>=78?"O jogador vê a mudança como um passo forte de carreira.":score>=58?"Há abertura para negociar, mas salário e projeto pesam.":score>=38?"O jogador precisa ser convencido pelo projeto.":"O jogador prefere permanecer onde está.";return{score,summary,traits};}
export function renewalPersonalityModifier(player:LeaguePlayer,seed:string){const traits=hiddenPlayerTraits(player,seed);return Math.round((traits.loyalty-50)*.2-(traits.ambition-50)*.12+(traits.professionalism-50)*.08);}
