import { SeededRng } from "./rng";
import { PROFESSIONAL_COMPETITIONS, type CompetitionClubRoster, type ProfessionalCompetitionId } from "../data/brazil-2026/competitions";
import type { LeaguePlayer } from "./league";
import type { SeasonState } from "./season";
import { applyDepartureImpact, applyArrivalImpact } from "./social";

export type InternationalTarget={id:string;competitionId:ProfessionalCompetitionId;competitionName:string;country:string;clubTransfermarktId:number;clubName:string;playerTransfermarktId:string;name:string;position:string;age:number;marketValueEur:number|null};
export type InternationalOfferStatus="Pendente"|"Aceita"|"Recusada"|"Concluída"|"Expirada";
export type InternationalOffer={id:string;direction:"Entrada"|"Saída";externalClubName:string;externalCompetitionId:ProfessionalCompetitionId;playerId:string;playerName:string;targetId?:string;feeEur:number;salaryBrlMonthly:number;createdRound:number;expiresRound:number;status:InternationalOfferStatus;message:string};
export type InternationalDeal={id:string;year:number;round:number;playerName:string;from:string;to:string;feeEur:number;kind:"Usuário"|"IA x IA"};
export type InternationalMarketState={sequence:number;offers:InternationalOffer[];history:InternationalDeal[];signedTargetIds:string[];lastProcessedRound?:number};
export type InternationalMarketResult={state:SeasonState;message:string};

const AGENTS=["Global Eleven","Prime Football","Atlas Sports","Bridge Agency","Elite Player Group","Mundo Soccer"];
const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,Math.round(v)));
export function createInternationalMarket():InternationalMarketState{return{sequence:0,offers:[],history:[],signedTargetIds:[]};}
export function hydrateInternationalMarket(state:InternationalMarketState|undefined):InternationalMarketState{return state?{...state,offers:state.offers??[],history:state.history??[],signedTargetIds:state.signedTargetIds??[]}:createInternationalMarket();}
export function isGlobalTransferWindowOpen(date:string,competitionId:ProfessionalCompetitionId){const month=Number(date.slice(5,7));return competitionId.startsWith("BRA")?[1,2,3,7,8,9].includes(month):[1,6,7,8,9].includes(month);}
export function globalWindowLabel(competitionId:ProfessionalCompetitionId){return competitionId.startsWith("BRA")?"jan–mar / jul–set":"jan / jun–set";}
function targetId(compId:string,clubId:number,playerId:string){return`${compId}:${clubId}:${playerId}`;}
function baseOverall(value:number|null,age:number){let overall=value===null?61:value>=120_000_000?90:value>=80_000_000?87:value>=50_000_000?83:value>=30_000_000?80:value>=15_000_000?76:value>=7_000_000?72:value>=3_000_000?68:value>=1_000_000?65:61;if(age<=19)overall-=2;if(age>=34)overall-=2;return clamp(overall,55,94);}
function marketSalary(value:number|null,overall:number,age:number){const base=value?value*.032:Math.max(100_000,(overall-55)*30_000),factor=age<=21?.75:age>=33?.8:1;return Math.max(45_000,Math.round(base*factor/5_000)*5_000);}
function potential(overall:number,age:number){return clamp(overall+(age<=19?10:age<=21?8:age<=23?5:age<=25?3:age<=28?1:0),overall,95);}
export function listInternationalTargets(state:SeasonState,query=""):InternationalTarget[]{const q=query.trim().toLowerCase(),signed=new Set(state.internationalMarket?.signedTargetIds??[]);return PROFESSIONAL_COMPETITIONS.flatMap(comp=>comp.id===state.competitionId?[]:comp.clubs.flatMap(club=>club.players.map(player=>({id:targetId(comp.id,club.transfermarktId,player.transfermarktId),competitionId:comp.id,competitionName:comp.name,country:comp.country,clubTransfermarktId:club.transfermarktId,clubName:club.name,playerTransfermarktId:player.transfermarktId,name:player.name,position:player.position,age:player.age,marketValueEur:player.marketValueEur} as InternationalTarget)))).filter(item=>!signed.has(item.id)&&(!q||item.name.toLowerCase().includes(q)||item.clubName.toLowerCase().includes(q)||item.position.toLowerCase().includes(q)||item.country.toLowerCase().includes(q))).sort((a,b)=>(b.marketValueEur??0)-(a.marketValueEur??0));}
function findTarget(state:SeasonState,id:string){return listInternationalTargets(state).find(target=>target.id===id);}
function toLeaguePlayer(target:InternationalTarget,state:SeasonState):LeaguePlayer{const rng=new SeededRng(`${state.baseSeed}:international-player:${target.id}`),overall=baseOverall(target.marketValueEur,target.age),salary=marketSalary(target.marketValueEur,overall,target.age);return{id:`intl-${target.competitionId}-${target.playerTransfermarktId}-${state.year}-${state.currentRound}`,transfermarktId:target.playerTransfermarktId,name:target.name,position:target.position,age:target.age,marketValueEur:target.marketValueEur,overall,potential:potential(overall,target.age),seasonStartOverall:overall,developmentProgress:0,overallHistory:[{year:state.year,round:state.currentRound,overall,reason:"início"}],morale:76,condition:96,fatigue:4,form:6,goals:0,assists:0,shots:0,yellowCards:0,redCards:0,wins:0,draws:0,losses:0,cleanSheets:0,ratingTotal:0,ratedMatches:0,averageRating:0,lastRating:0,injuryDays:0,suspensionMatches:0,status:"Reserva",personality:rng.pick(["Profissional","Ambicioso","Competitivo","Leal","Reservado","Temperamental"] as const),squadRole:target.age<=21?"Promessa":"Rotação",happiness:72,managerTrust:58,appearances:0,starts:0,minutes:0,promises:[],contract:{salaryBrlMonthly:salary,startYear:state.year,endYear:state.year+3,agentName:rng.pick(AGENTS),releaseClauseEur:target.marketValueEur?Math.round(target.marketValueEur*1.8/100_000)*100_000:null},transferListed:false,wantsToLeave:false};}
function cloneStatePieces(state:SeasonState){const league={...state.league,clubs:state.league.clubs.map(club=>({...club,players:club.players.map(player=>({...player,contract:{...player.contract},promises:(player.promises??[]).map(p=>({...p}))}))})),fixtures:state.league.fixtures.map(f=>({...f})),standings:state.league.standings.map(s=>({...s}))};const internationalMarket={...hydrateInternationalMarket(state.internationalMarket),offers:hydrateInternationalMarket(state.internationalMarket).offers.map(o=>({...o})),history:hydrateInternationalMarket(state.internationalMarket).history.map(h=>({...h})),signedTargetIds:[...hydrateInternationalMarket(state.internationalMarket).signedTargetIds]};return{league,internationalMarket};}
function nextId(market:InternationalMarketState,prefix:string){market.sequence++;return`${prefix}-${market.sequence}`;}
function recommendedFee(target:InternationalTarget){const value=target.marketValueEur??1_000_000;return Math.max(250_000,Math.round(value*1.08/100_000)*100_000);}

export function makeInternationalOffer(state:SeasonState,targetIdValue:string):InternationalMarketResult{
 if(!isGlobalTransferWindowOpen(state.currentDate,state.competitionId))return{state,message:`Janela internacional fechada (${globalWindowLabel(state.competitionId)}).`};
 const target=findTarget(state,targetIdValue);if(!target)return{state,message:"Jogador internacional não encontrado ou já contratado."};
 const {league,internationalMarket}=cloneStatePieces(state),club=league.clubs.find(c=>c.id===state.selectedClubId)!;const fee=recommendedFee(target);if(fee>club.transferBudgetEur)return{state,message:`Orçamento insuficiente para uma proposta estimada em €${Math.round(fee/1_000_000*10)/10} mi.`};
 const rng=new SeededRng(`${state.baseSeed}:intl-offer:${target.id}:r${state.currentRound}`),overall=baseOverall(target.marketValueEur,target.age),salary=Math.round(marketSalary(target.marketValueEur,overall,target.age)*1.12/5_000)*5_000,prestige=(club.reputation-70)*1.2,feeRatio=fee/Math.max(500_000,target.marketValueEur??1_000_000),acceptChance=clamp(42+(feeRatio-1)*80+prestige+(target.age<=23?5:0),12,94);
 const offer:InternationalOffer={id:nextId(internationalMarket,"intl-offer"),direction:"Entrada",externalClubName:target.clubName,externalCompetitionId:target.competitionId,playerId:target.playerTransfermarktId,playerName:target.name,targetId:target.id,feeEur:fee,salaryBrlMonthly:salary,createdRound:state.currentRound,expiresRound:state.currentRound+2,status:"Pendente",message:"Proposta internacional enviada."};
 if(rng.integer(1,100)<=acceptChance){offer.status="Aceita";offer.message=`${target.clubName} aceitou a proposta. Falta concluir os termos com ${target.name}.`;}else{offer.status="Recusada";offer.message=`${target.clubName} recusou a proposta por ${target.name}.`;}
 internationalMarket.offers.unshift(offer);return{state:{...state,league,internationalMarket},message:offer.message};
}
export function concludeInternationalOffer(state:SeasonState,offerId:string):InternationalMarketResult{
 const {league,internationalMarket}=cloneStatePieces(state),offer=internationalMarket.offers.find(o=>o.id===offerId);if(!offer||offer.direction!=="Entrada"||offer.status!=="Aceita"||!offer.targetId)return{state,message:"Negociação internacional indisponível."};
 const target=findTarget({...state,internationalMarket} as SeasonState,offer.targetId);if(!target)return{state,message:"O jogador não está mais disponível."};const club=league.clubs.find(c=>c.id===state.selectedClubId)!;
 const rng=new SeededRng(`${state.baseSeed}:intl-personal:${offer.id}`),chance=clamp(55+(club.reputation-68)*1.5+(offer.salaryBrlMonthly/Math.max(1,marketSalary(target.marketValueEur,baseOverall(target.marketValueEur,target.age),target.age))-1)*80+(target.age<=24?5:0),15,95);if(rng.integer(1,100)>chance){offer.status="Recusada";offer.message=`${target.name} recusou os termos pessoais.`;return{state:{...state,league,internationalMarket},message:offer.message};}
 const player=toLeaguePlayer(target,state);player.contract.salaryBrlMonthly=offer.salaryBrlMonthly;club.players.push(player);club.transferBudgetEur-=offer.feeEur;internationalMarket.signedTargetIds.push(target.id);offer.status="Concluída";offer.message=`${target.name} chega do ${target.clubName}. ${applyArrivalImpact(club,player.id)}`;internationalMarket.history.unshift({id:nextId(internationalMarket,"intl-deal"),year:state.year,round:state.currentRound,playerName:target.name,from:target.clubName,to:club.name,feeEur:offer.feeEur,kind:"Usuário"});return{state:{...state,league,internationalMarket},message:offer.message};
}
export function respondInternationalIncoming(state:SeasonState,offerId:string,accept:boolean):InternationalMarketResult{
 const {league,internationalMarket}=cloneStatePieces(state),offer=internationalMarket.offers.find(o=>o.id===offerId),club=league.clubs.find(c=>c.id===state.selectedClubId)!;if(!offer||offer.direction!=="Saída"||offer.status!=="Pendente")return{state,message:"Proposta internacional indisponível."};if(!accept){offer.status="Recusada";offer.message="Você recusou a oferta internacional.";return{state:{...state,league,internationalMarket},message:offer.message};}
 const index=club.players.findIndex(p=>p.id===offer.playerId);if(index<0)return{state,message:"Jogador não está mais no elenco."};const player=club.players[index],social=applyDepartureImpact(club,player.id);club.players.splice(index,1);club.transferBudgetEur+=offer.feeEur;offer.status="Concluída";offer.message=`${player.name} foi negociado com ${offer.externalClubName}. ${social}`;internationalMarket.history.unshift({id:nextId(internationalMarket,"intl-deal"),year:state.year,round:state.currentRound,playerName:player.name,from:club.name,to:offer.externalClubName,feeEur:offer.feeEur,kind:"Usuário"});return{state:{...state,league,internationalMarket,lineupIds:state.lineupIds.filter(id=>id!==player.id),benchIds:state.benchIds.filter(id=>id!==player.id)},message:offer.message};
}

function externalClubPool(active:ProfessionalCompetitionId){return PROFESSIONAL_COMPETITIONS.flatMap(comp=>comp.id===active?[]:comp.clubs.map(club=>({competitionId:comp.id,name:club.name,reputation:Math.max(50,Math.min(96,52+Math.round(Math.log10(Math.max(1,club.marketValueEur))*6))),club}))));}
export function processInternationalMarketRound(state:SeasonState):SeasonState{
 const {league,internationalMarket}=cloneStatePieces(state);if(internationalMarket.lastProcessedRound===state.currentRound)return state;internationalMarket.lastProcessedRound=state.currentRound;for(const offer of internationalMarket.offers)if(offer.status==="Pendente"&&offer.expiresRound<state.currentRound)offer.status="Expirada";
 const club=league.clubs.find(c=>c.id===state.selectedClubId)!;if(!isGlobalTransferWindowOpen(state.currentDate,state.competitionId))return{...state,league,internationalMarket};const rng=new SeededRng(`${state.baseSeed}:global-market:r${state.currentRound}`),externals=externalClubPool(state.competitionId);
 if(externals.length&&club.players.length&&rng.integer(1,100)<=58){const player=rng.pick([...club.players].sort((a,b)=>(b.marketValueEur??0)-(a.marketValueEur??0)).slice(0,Math.min(12,club.players.length))),buyer=rng.pick(externals),fee=Math.max(300_000,Math.round((player.marketValueEur??1_000_000)*(rng.integer(92,125)/100)/100_000)*100_000);if(!internationalMarket.offers.some(o=>o.direction==="Saída"&&o.playerId===player.id&&o.status==="Pendente"))internationalMarket.offers.unshift({id:nextId(internationalMarket,"intl-in"),direction:"Saída",externalClubName:buyer.name,externalCompetitionId:buyer.competitionId,playerId:player.id,playerName:player.name,feeEur:fee,salaryBrlMonthly:Math.round(player.contract.salaryBrlMonthly*1.15/5_000)*5_000,createdRound:state.currentRound,expiresRound:state.currentRound+2,status:"Pendente",message:`${buyer.name} fez uma proposta internacional por ${player.name}.`});}
 if(externals.length>=2&&rng.integer(1,100)<=72){const seller=rng.pick(externals),buyers=externals.filter(item=>item.name!==seller.name),buyer=rng.pick(buyers),players=seller.club.players.filter(p=>p.marketValueEur!==null);if(players.length){const player=rng.pick(players),fee=Math.max(200_000,Math.round((player.marketValueEur??1_000_000)*(rng.integer(90,120)/100)/100_000)*100_000);internationalMarket.history.unshift({id:nextId(internationalMarket,"ai-deal"),year:state.year,round:state.currentRound,playerName:player.name,from:seller.name,to:buyer.name,feeEur:fee,kind:"IA x IA"});}}
 internationalMarket.history=internationalMarket.history.slice(0,120);return{...state,league,internationalMarket};
}
export function prepareInternationalMarketNextSeason(state:InternationalMarketState|undefined){const market=hydrateInternationalMarket(state);return{...market,lastProcessedRound:undefined,offers:market.offers.filter(o=>o.status==="Concluída").slice(0,20)};}
