import{SeededRng}from"./rng";
import{professionalCompetitionById,competitionStartDate,type CompetitionClubRoster,type ProfessionalCompetitionId}from"../data/brazil-2026/competitions";

export type PlayerPersonality="Profissional"|"Ambicioso"|"Competitivo"|"Leal"|"Reservado"|"Temperamental";
export type SquadRole="Líder"|"Titular"|"Rotação"|"Reserva"|"Promessa";
export type PlayerPromise={id:string;type:"Mais minutos";createdRound:number;deadlineRound:number;targetAppearances:number;progressAppearances:number;status:"Ativa"|"Cumprida"|"Quebrada"};
export type PlayerContract={salaryBrlMonthly:number;startYear:number;endYear:number;agentName:string;releaseClauseEur:number|null};
export type OverallHistoryPoint={year:number;round:number;overall:number;reason:"início"|"forma"|"idade"|"temporada"};
export type PlayerCompetitionStats={appearances:number;starts:number;minutes:number;goals:number;assists:number;shots:number;yellowCards:number;wins:number;draws:number;losses:number;cleanSheets:number;ratingTotal:number;ratedMatches:number;averageRating:number;lastRating:number};
export type LeaguePlayer={
 id:string;transfermarktId:string;name:string;position:string;age:number;marketValueEur:number|null;marketValueUpdated?:string;
 overall:number;potential:number;seasonStartOverall:number;developmentProgress:number;overallHistory:OverallHistoryPoint[];
 morale:number;condition:number;fatigue:number;form:number;goals:number;assists:number;shots:number;yellowCards:number;redCards:number;wins:number;draws:number;losses:number;cleanSheets:number;ratingTotal:number;ratedMatches:number;averageRating:number;lastRating:number;competitionStats?:Record<string,PlayerCompetitionStats>;
 injuryDays:number;suspensionMatches:number;status:string;personality:PlayerPersonality;squadRole:SquadRole;happiness:number;managerTrust:number;appearances:number;starts:number;minutes:number;promises:PlayerPromise[];contract:PlayerContract;transferListed:boolean;wantsToLeave:boolean;lastConversationRound?:number;
};
export type LeagueClub={id:string;sourceId:number;transfermarktId:number;name:string;shortName:string;imageUrl:string;color:string;reputation:number;marketValueEur:number;transferBudgetEur:number;wageBudgetBrlMonthly:number;players:LeaguePlayer[]};
export type LeagueFixture={id:string;round:number;homeClubId:string;awayClubId:string;played:boolean;date?:string;homeGoals?:number;awayGoals?:number;homeShots?:number;awayShots?:number;possessionHome?:number;homeYellowCards?:number;awayYellowCards?:number};
export type LeagueStanding={clubId:string;played:number;won:number;drawn:number;lost:number;goalsFor:number;goalsAgainst:number;points:number};
export type LeagueWorld={clubs:LeagueClub[];fixtures:LeagueFixture[];standings:LeagueStanding[];competitionId?:ProfessionalCompetitionId;competitionName?:string;totalRounds?:number};

const COLORS=["#159447","#d33e34","#151515","#d43832","#ececec","#4a78d0","#d84137","#2b6fdd","#111111","#222222","#6c1f35","#171717","#2b78c5","#d42d2d","#e9e9e9","#d43b2d","#208251","#d5e7e2","#e0bd2b","#1e4ea3"];
const PERSONALITIES:PlayerPersonality[]=["Profissional","Ambicioso","Competitivo","Leal","Reservado","Temperamental"];
const AGENTS=["André Moraes","Bruno Salles","Carlos Faria","Diego Neves","Eduardo Lima","Felipe Tavares","Gustavo Nunes","Henrique Prado","Igor Martins","João Vilela","Lucas Freire","Marcelo Rezende"];

function simulatedSalary(valueEur:number|null,overall:number,age:number,rng:SeededRng){const marketBase=valueEur?valueEur*.032:Math.max(90_000,(overall-55)*24_000);const ageFactor=age<=21?.72:age>=33?.78:1;return Math.max(35_000,Math.round((marketBase*ageFactor*(rng.integer(86,114)/100))/5_000)*5_000);}
function assignRoles(players:LeaguePlayer[]){const ranked=[...players].sort((a,b)=>b.overall-a.overall);ranked.forEach((player,index)=>{const role:SquadRole=player.age<=21&&index>10?"Promessa":index<3?"Líder":index<11?"Titular":index<18?"Rotação":index<25?"Reserva":"Promessa";player.squadRole=role;player.status=role;if(role==="Líder")player.managerTrust=Math.min(100,player.managerTrust+8);});}
function strengthRange(id:ProfessionalCompetitionId){if(id==="ENG1")return[62,94]as const;if(id==="ESP1")return[61,93]as const;if(id==="FRA1")return[58,90]as const;if(id==="BRA1")return[58,86]as const;if(id==="BRA2")return[54,79]as const;return[50,74]as const;}
function reputationRange(id:ProfessionalCompetitionId){if(id==="ENG1")return[67,96]as const;if(id==="ESP1")return[64,95]as const;if(id==="FRA1")return[58,92]as const;if(id==="BRA1")return[58,88]as const;if(id==="BRA2")return[48,75]as const;return[40,68]as const;}
function valueOverall(value:number|null):number|null{if(value===null)return null;if(value>=150_000_000)return 92;if(value>=100_000_000)return 89;if(value>=70_000_000)return 86;if(value>=50_000_000)return 83;if(value>=30_000_000)return 80;if(value>=20_000_000)return 77;if(value>=10_000_000)return 74;if(value>=5_000_000)return 70;if(value>=2_000_000)return 67;if(value>=1_000_000)return 64;if(value>=500_000)return 61;return 58;}
function competitionRatingBias(id:ProfessionalCompetitionId){return id==="ENG1"?1:id==="ESP1"?1:id==="FRA1"?0:id==="BRA1"?-1:id==="BRA2"?-2:-3;}
function initialOverall(value:number|null,age:number,id:ProfessionalCompetitionId,rng:SeededRng){const[min,max]=strengthRange(id),fromValue=valueOverall(value);if(fromValue===null)return rng.integer(min,Math.max(min,Math.min(max,min+13)));const youthAdjustment=age<=17?-5:age===18?-4:age===19?-2:age===20?-1:0,ageAdjustment=age>=36?-3:age>=34?-2:age>=32?-1:0;return Math.max(min,Math.min(max,fromValue+competitionRatingBias(id)+youthAdjustment+ageAdjustment+rng.integer(-2,2)));}
function initialPotential(overall:number,age:number,value:number|null,rng:SeededRng){const headroom=age<=17?12:age<=19?10:age<=21?8:age<=23?6:age<=25?4:age<=27?2:age<=29?1:0,marketBonus=value&&value>=30_000_000?2:value&&value>=10_000_000?1:0;return Math.max(overall,Math.min(95,overall+headroom+marketBonus+rng.integer(-1,2)));}
function generatePlayers(clubId:string,roster:CompetitionClubRoster,rng:SeededRng,year:number,competitionId:ProfessionalCompetitionId):LeaguePlayer[]{
 const players=roster.players.map((identity,index):LeaguePlayer=>{const overall=initialOverall(identity.marketValueEur,identity.age,competitionId,rng),potential=initialPotential(overall,identity.age,identity.marketValueEur,rng),salary=simulatedSalary(identity.marketValueEur,overall,identity.age,rng),endYear=year+rng.integer(identity.age>=32?1:1,identity.age<=23?4:3),clause=identity.marketValueEur&&identity.age<31?Math.round(identity.marketValueEur*(rng.integer(140,220)/100)/100_000)*100_000:null;return{id:`${clubId}-p${index+1}`,transfermarktId:identity.transfermarktId,name:identity.name,position:identity.position,age:identity.age,marketValueEur:identity.marketValueEur,marketValueUpdated:identity.marketValueUpdated,overall,potential,seasonStartOverall:overall,developmentProgress:0,overallHistory:[{year,round:0,overall,reason:"início"}],morale:rng.integer(66,86),condition:rng.integer(88,100),fatigue:rng.integer(0,9),form:rng.integer(5,8),goals:0,assists:0,shots:0,yellowCards:0,redCards:0,wins:0,draws:0,losses:0,cleanSheets:0,ratingTotal:0,ratedMatches:0,averageRating:0,lastRating:0,injuryDays:0,suspensionMatches:0,status:"Reserva",personality:rng.pick(PERSONALITIES),squadRole:"Reserva",happiness:rng.integer(64,88),managerTrust:rng.integer(54,76),appearances:0,starts:0,minutes:0,promises:[],contract:{salaryBrlMonthly:salary,startYear:year,endYear,agentName:rng.pick(AGENTS),releaseClauseEur:clause},transferListed:false,wantsToLeave:false};});assignRoles(players);return players;
}
function addDays(iso:string,days:number){const date=new Date(`${iso}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10);}
export function generateFixtures(clubIds:string[],startDate="2026-01-28",roundCadenceDays=7,doubleRoundRobin=true):LeagueFixture[]{
 const teams=[...clubIds];if(teams.length%2)teams.push("BYE");const fixed=teams[0],rotating=teams.slice(1),half=teams.length/2,first:LeagueFixture[]=[];
 for(let round=1;round<teams.length;round++){const row=[fixed,...rotating];for(let i=0;i<half;i++){const a=row[i],b=row[row.length-1-i];if(a!=="BYE"&&b!=="BYE"){const swap=(round+i)%2===0;first.push({id:`r${round}-${a}-${b}`,round,homeClubId:swap?b:a,awayClubId:swap?a:b,played:false,date:addDays(startDate,(round-1)*roundCadenceDays)});}}rotating.unshift(rotating.pop()!);}
 if(!doubleRoundRobin)return first;const offset=teams.length-1;return[...first,...first.map(f=>({...f,id:`r${f.round+offset}-${f.awayClubId}-${f.homeClubId}`,round:f.round+offset,homeClubId:f.awayClubId,awayClubId:f.homeClubId,date:addDays(startDate,(f.round+offset-1)*roundCadenceDays)}))];
}
export function createLeague(seed:string,year=2026,competitionId:ProfessionalCompetitionId="BRA1"):LeagueWorld{
 const competition=professionalCompetitionById(competitionId),rng=new SeededRng(seed),[repMin,repMax]=reputationRange(competitionId);
 const clubs=competition.clubs.map((identity,index)=>{const id=`club-${index+1}`,players=generatePlayers(id,identity,rng,year,competitionId),wageSpend=players.reduce((sum,p)=>sum+p.contract.salaryBrlMonthly,0);return{id,sourceId:identity.sourceId,transfermarktId:identity.transfermarktId,name:identity.name,shortName:identity.shortName,imageUrl:identity.imageUrl,color:COLORS[index%COLORS.length],reputation:rng.integer(repMin,repMax),marketValueEur:identity.marketValueEur,transferBudgetEur:Math.max(800_000,Math.round(identity.marketValueEur*(rng.integer(8,16)/100)/100_000)*100_000),wageBudgetBrlMonthly:Math.round(wageSpend*(rng.integer(112,125)/100)/10_000)*10_000,players};});
 const fixtures=generateFixtures(clubs.map(c=>c.id),competitionStartDate(competitionId,year),competition.roundCadenceDays,competition.doubleRoundRobin);
 return{clubs,fixtures,standings:clubs.map(c=>({clubId:c.id,played:0,won:0,drawn:0,lost:0,goalsFor:0,goalsAgainst:0,points:0})),competitionId,competitionName:competition.name,totalRounds:Math.max(...fixtures.map(f=>f.round),0)};
}
export function sortedStandings(world:LeagueWorld):LeagueStanding[]{return[...world.standings].sort((a,b)=>b.points-a.points||(b.goalsFor-b.goalsAgainst)-(a.goalsFor-a.goalsAgainst)||b.goalsFor-a.goalsFor);}
export function playerAvailability(player:LeaguePlayer):"Lesionado"|"Suspenso"|"Disponível"{if(player.injuryDays>0)return"Lesionado";if(player.suspensionMatches>0)return"Suspenso";return"Disponível";}
