/* eslint-disable prefer-const */
import { SeededRng } from "./rng";
import type { LeagueClub, LeaguePlayer } from "./league";
import { DEFAULT_TACTIC, normalizeTactic, pickStartingXI, type MatchEvent, type MatchResult, type MatchTactic } from "./match";
import { tacticalFitMultiplier } from "./tactical-position";
import { pressurePerformanceModifier } from "./personality";

export type LiveMatchPhase="pre_match"|"first_half"|"halftime"|"second_half_window"|"fulltime";
export type TeamTalk="Cobrar"|"Incentivar"|"Acalmar";
export type MatchSide="home"|"away";
export type MatchSpeed="normal"|"fast"|"very_fast";
export type AttackZone="left"|"center"|"right";
export type HeatCell="def-left"|"def-center"|"def-right"|"mid-left"|"mid-center"|"mid-right"|"att-left"|"att-center"|"att-right";
export type LiveSubstitution={side:MatchSide;outPlayerId:string;inPlayerId:string;minute:number};
export type LivePlayerState={condition:number;fatigue:number;rating:number;minutes:number};
export type ZoneStats={left:number;center:number;right:number};
export type LiveTacticalChange={minute:number;side:MatchSide;summary:string};
export type LiveMatchState={
 seed:string;phase:LiveMatchPhase;currentMinute:number;userSide:MatchSide;
 homeLineupIds:string[];awayLineupIds:string[];homeBenchIds:string[];awayBenchIds:string[];maxSubstitutions:number;
 homeTactic:MatchTactic;awayTactic:MatchTactic;
 homeGoals:number;awayGoals:number;possessionHome:number;possessionSamples:number;shotsHome:number;shotsAway:number;xgHome:number;xgAway:number;bigChancesHome:number;bigChancesAway:number;passesHome:number;passesAway:number;tacklesHome:number;tacklesAway:number;interceptionsHome:number;interceptionsAway:number;
 events:MatchEvent[];substitutions:LiveSubstitution[];injuredPlayerIds:string[];sentOffPlayerIds:string[];usedPlayerIds:string[];playerStates:Record<string,LivePlayerState>;teamTalk?:TeamTalk;aiAdjustments:number;
 momentumHome?:number;momentumHistory?:Array<{minute:number;home:number}>;homeAttackZones?:ZoneStats;awayAttackZones?:ZoneStats;homeHeatmap?:Record<HeatCell,number>;awayHeatmap?:Record<HeatCell,number>;cornersHome?:number;cornersAway?:number;freeKicksHome?:number;freeKicksAway?:number;tacticalChanges?:LiveTacticalChange[];
};

const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
const round1=(v:number)=>Math.round(v*10)/10,round2=(v:number)=>Math.round(v*100)/100;
const EMPTY_ZONES:ZoneStats={left:0,center:0,right:0};
const HEAT_CELLS:HeatCell[]=["def-left","def-center","def-right","mid-left","mid-center","mid-right","att-left","att-center","att-right"];
const emptyHeat=()=>Object.fromEntries(HEAT_CELLS.map(k=>[k,0])) as Record<HeatCell,number>;
function zones(v:ZoneStats|undefined){return v??{...EMPTY_ZONES};}
function heat(v:Record<HeatCell,number>|undefined){return v??emptyHeat();}
function availableBench(club:LeagueClub,lineupIds:string[],size=12){const selected=new Set(lineupIds);return club.players.filter(p=>p.injuryDays===0&&p.suspensionMatches===0&&!selected.has(p.id)).sort((a,b)=>b.overall-a.overall).slice(0,size).map(p=>p.id);}
function selectedBench(club:LeagueClub,lineupIds:string[],benchIds:string[]|undefined,size:number){if(!benchIds?.length)return availableBench(club,lineupIds,size);const starters=new Set(lineupIds);return benchIds.filter((id,i)=>benchIds.indexOf(id)===i&&!starters.has(id)&&club.players.some(p=>p.id===id&&p.injuryDays===0&&p.suspensionMatches===0)).slice(0,size);}
function exactLineup(club:LeagueClub,ids:string[]){return ids.map(id=>club.players.find(p=>p.id===id)).filter((p):p is LeaguePlayer=>Boolean(p));}
function activePhase(s:LiveMatchState){return s.phase==="first_half"||s.phase==="second_half_window";}
function canDecide(s:LiveMatchState){return activePhase(s)||s.phase==="halftime";}
function liveState(s:LiveMatchState,p:LeaguePlayer){return s.playerStates[p.id]??{condition:p.condition,fatigue:p.fatigue,rating:6,minutes:0};}
function strength(s:LiveMatchState,club:LeagueClub,ids:string[],raw:MatchTactic,momentum=0){const xi=exactLineup(club,ids),t=normalizeTactic(raw);if(!xi.length)return 35;const base=xi.reduce((sum,p)=>{const live=liveState(s,p),importance=s.currentMinute>=70?1:.55;return sum+p.overall*(live.condition/100)*(.92+p.morale/1250)*Math.max(.72,1-live.fatigue/210)*tacticalFitMultiplier(p,t.positions?.[p.id])*pressurePerformanceModifier(p,importance);},0)/Math.max(11,xi.length),mentality=t.mentality==="Ofensiva"?2.2:t.mentality==="Defensiva"?-.9:0,line=t.defensiveLine==="Alta"?.8:t.defensiveLine==="Baixa"?-.35:0,build=t.buildUp==="Direta"?.35:t.buildUp==="Curta"?.2:0,focus=t.attackFocus==="Equilibrado"?0:.35;return base+mentality+(t.pressing-50)*.026+(t.tempo-50)*.021+line+build+focus+momentum-Math.max(0,11-xi.length)*3.8;}
function rolePool(xi:LeaguePlayer[],positions:string[]){const pool=xi.filter(p=>positions.includes(p.position));return pool.length?pool:xi;}
function zoneWeights(raw:MatchTactic){const t=normalizeTactic(raw);let left=33,center=34,right=33;if(t.attackFocus==="Pelos lados"){left=42;center=16;right=42;}else if(t.attackFocus==="Por dentro"){left=20;center=60;right=20;}else if(t.attackFocus==="Esquerda"){left=61;center=25;right=14;}else if(t.attackFocus==="Direita"){left=14;center=25;right=61;}if(t.width==="Ampla"){left+=5;right+=5;center-=10;}else if(t.width==="Estreita"){left-=5;right-=5;center+=10;}return{left:Math.max(5,left),center:Math.max(5,center),right:Math.max(5,right)};}
function pickZone(rng:SeededRng,tactic:MatchTactic):AttackZone{const w=zoneWeights(tactic),total=w.left+w.center+w.right,r=rng.integer(1,total);return r<=w.left?"left":r<=w.left+w.center?"center":"right";}
function attacking(rng:SeededRng,xi:LeaguePlayer[],zone:AttackZone){if(zone==="left")return rng.pick(rolePool(xi,["PE","LE","MEI","MC","ATA"]));if(zone==="right")return rng.pick(rolePool(xi,["PD","LD","MEI","MC","ATA"]));return rng.pick(rolePool(xi,["ATA","MEI","MC","VOL"]));}
function assist(rng:SeededRng,xi:LeaguePlayer[],scorer:LeaguePlayer){const p=xi.filter(x=>x.id!==scorer.id&&["ATA","PE","PD","MEI","MC","VOL","LE","LD"].includes(x.position));return p.length&&rng.next()<.73?rng.pick(p):undefined;}
function setPiecePlayer(xi:LeaguePlayer[],id:string|undefined,fallback:string[]){return (id?xi.find(p=>p.id===id):undefined)??[...rolePool(xi,fallback)].sort((a,b)=>b.overall-a.overall)[0]??xi[0];}
function talkMomentum(s:LiveMatchState,m:number){if(m>68)return 0;const decay=Math.max(0,1-(m-46)/25),winning=s.userSide==="home"?s.homeGoals>s.awayGoals:s.awayGoals>s.homeGoals,losing=s.userSide==="home"?s.homeGoals<s.awayGoals:s.awayGoals<s.homeGoals,raw=s.teamTalk==="Cobrar"?(losing?1.7:winning?-.2:.9):s.teamTalk==="Incentivar"?1:s.teamTalk==="Acalmar"?(winning?.8:.25):0;return raw*decay;}
function minuteRng(s:LiveMatchState,m:number){const ht=normalizeTactic(s.homeTactic),at=normalizeTactic(s.awayTactic);return new SeededRng(`${s.seed}:m${m}:${s.substitutions.length}:${s.homeGoals}-${s.awayGoals}:${ht.mentality}:${at.mentality}:${ht.attackFocus}:${at.attackFocus}:${ht.buildUp}:${at.buildUp}`);}
function initStates(home:LeagueClub,away:LeagueClub){const states:Record<string,LivePlayerState>={};for(const p of [...home.players,...away.players])states[p.id]={condition:p.condition,fatigue:p.fatigue,rating:6,minutes:0};return states;}
function adjust(states:Record<string,LivePlayerState>,id:string|undefined,d:number){if(id&&states[id])states[id]={...states[id],rating:round2(clamp(states[id].rating+d,4,10))};}
function wear(s:LiveMatchState,home:LeagueClub,away:LeagueClub){const states=Object.fromEntries(Object.entries(s.playerStates).map(([id,v])=>[id,{...v}]));for(const [club,ids,raw] of [[home,s.homeLineupIds,s.homeTactic],[away,s.awayLineupIds,s.awayTactic]] as const){const t=normalizeTactic(raw);for(const p of exactLineup(club,ids)){const cur=states[p.id]??{condition:p.condition,fatigue:p.fatigue,rating:6,minutes:0},intensity=((t.pressing-20)/70)*.045+((t.tempo-20)/70)*.035+(t.defensiveLine==="Alta"?.012:0)+(t.marking==="Individual"?.008:0),age=p.age>=33?.018:p.age<=21?-.006:0,load=cur.fatigue>=70?.025:cur.fatigue>=50?.012:0,loss=.045+intensity+age+load,gain=.055+intensity*1.35+age;let rating=cur.rating;if(cur.condition<68)rating-=.004;if(cur.condition<58)rating-=.006;states[p.id]={condition:round1(clamp(cur.condition-loss,32,100)),fatigue:round1(clamp(cur.fatigue+gain,0,100)),rating:round2(clamp(rating,4,10)),minutes:cur.minutes+1};}}return states;}
function updateMomentum(current:number,homeThreat:number,awayThreat:number,homeGoalDelta:number,awayGoalDelta:number){const impulse=(homeThreat-awayThreat)*18+(homeGoalDelta-awayGoalDelta)*32;return round1(clamp(current*.78+impulse,-100,100));}
function addHeat(map:Record<HeatCell,number>,zone:AttackZone,phase:"def"|"mid"|"att",amount=1){const key=`${phase}-${zone}` as HeatCell;map[key]=(map[key]??0)+amount;}
function tacticSummary(before:MatchTactic,after:MatchTactic){const b=normalizeTactic(before),a=normalizeTactic(after),parts:string[]=[];if(a.mentality!==b.mentality)parts.push(a.mentality);if(a.attackFocus!==b.attackFocus)parts.push(`ataque: ${a.attackFocus.toLowerCase()}`);if(a.defensiveLine!==b.defensiveLine)parts.push(`linha ${a.defensiveLine.toLowerCase()}`);if(a.width!==b.width)parts.push(`amplitude ${a.width.toLowerCase()}`);if(a.buildUp!==b.buildUp)parts.push(`construção ${a.buildUp.toLowerCase()}`);if(a.marking!==b.marking)parts.push(`marcação ${a.marking.toLowerCase()}`);if(Math.abs(a.pressing-b.pressing)>=5)parts.push(`pressão ${a.pressing}`);if(Math.abs(a.tempo-b.tempo)>=5)parts.push(`ritmo ${a.tempo}`);return parts.join(" • ")||"ajuste fino";}

export function createLiveMatch(home:LeagueClub,away:LeagueClub,seed:string,userSide:MatchSide,userLineupIds:string[],userTactic:MatchTactic=DEFAULT_TACTIC,userBenchIds?:string[],benchSize=12,maxSubstitutions=5,opponentTactic:MatchTactic=DEFAULT_TACTIC):LiveMatchState{const homeIds=userSide==="home"?pickStartingXI(home,userLineupIds).map(p=>p.id):pickStartingXI(home).map(p=>p.id),awayIds=userSide==="away"?pickStartingXI(away,userLineupIds).map(p=>p.id):pickStartingXI(away).map(p=>p.id);return{seed,phase:"pre_match",currentMinute:0,userSide,homeLineupIds:homeIds,awayLineupIds:awayIds,homeBenchIds:userSide==="home"?selectedBench(home,homeIds,userBenchIds,benchSize):availableBench(home,homeIds,benchSize),awayBenchIds:userSide==="away"?selectedBench(away,awayIds,userBenchIds,benchSize):availableBench(away,awayIds,benchSize),maxSubstitutions,homeTactic:userSide==="home"?{...DEFAULT_TACTIC,...userTactic}:opponentTactic,awayTactic:userSide==="away"?{...DEFAULT_TACTIC,...userTactic}:opponentTactic,homeGoals:0,awayGoals:0,possessionHome:50,possessionSamples:0,shotsHome:0,shotsAway:0,xgHome:0,xgAway:0,bigChancesHome:0,bigChancesAway:0,passesHome:0,passesAway:0,tacklesHome:0,tacklesAway:0,interceptionsHome:0,interceptionsAway:0,events:[{minute:0,type:"kickoff",team:"neutral",text:`Tudo pronto para ${home.name} × ${away.name}.`}],substitutions:[],injuredPlayerIds:[],sentOffPlayerIds:[],usedPlayerIds:[...new Set([...homeIds,...awayIds])],playerStates:initStates(home,away),aiAdjustments:0,momentumHome:0,momentumHistory:[{minute:0,home:0}],homeAttackZones:{...EMPTY_ZONES},awayAttackZones:{...EMPTY_ZONES},homeHeatmap:emptyHeat(),awayHeatmap:emptyHeat(),cornersHome:0,cornersAway:0,freeKicksHome:0,freeKicksAway:0,tacticalChanges:[]};}
export function startLiveMatch(s:LiveMatchState,home:LeagueClub):LiveMatchState{return s.phase!=="pre_match"?s:{...s,phase:"first_half",events:[...s.events,{minute:0,type:"kickoff",team:"neutral",text:`Bola rolando. ${home.name} dá a saída.`}]};}
export function resumeSecondHalf(s:LiveMatchState):LiveMatchState{if(s.phase!=="halftime"||requiredUserSubstitutions(s).length)return s;return{...s,phase:"second_half_window",events:[...s.events,{minute:46,type:"kickoff",team:"neutral",text:`Começa o segundo tempo.${s.teamTalk?` A mensagem foi: ${s.teamTalk.toLowerCase()}.`:""}`}]};}
function autoReplace(s:LiveMatchState,side:MatchSide):LiveMatchState{if(side===s.userSide)return s;let next=s;const lineup=()=>side==="home"?next.homeLineupIds:next.awayLineupIds,bench=()=>side==="home"?next.homeBenchIds:next.awayBenchIds;for(const injured of [...next.injuredPlayerIds])if(lineup().includes(injured)&&bench().length)next=makeSubstitution(next,side,injured,bench()[0]);return next;}
function autoAi(s:LiveMatchState,home:LeagueClub,away:LeagueClub,minute:number):LiveMatchState{if(![55,65,73,82].includes(minute))return s;const side:MatchSide=s.userSide==="home"?"away":"home",club=side==="home"?home:away,lineup=side==="home"?s.homeLineupIds:s.awayLineupIds,bench=side==="home"?s.homeBenchIds:s.awayBenchIds,losing=side==="home"?s.homeGoals<s.awayGoals:s.awayGoals<s.homeGoals,winning=side==="home"?s.homeGoals>s.awayGoals:s.awayGoals>s.homeGoals,raw=side==="home"?s.homeTactic:s.awayTactic,t=normalizeTactic(raw);let patch:MatchTactic={...raw,mentality:losing?"Ofensiva":winning&&minute>=70?"Defensiva":"Equilibrada",pressing:clamp(t.pressing+(losing?8:winning?-5:0),20,90),tempo:clamp(t.tempo+(losing?7:winning?-4:0),20,90),attackFocus:losing?(minute%2?"Pelos lados":"Por dentro"):t.attackFocus,defensiveLine:losing?"Alta":winning&&minute>=73?"Baixa":t.defensiveLine,buildUp:losing?"Direta":winning?"Curta":t.buildUp,width:losing?"Ampla":t.width};let next=updateLiveTactic(s,side,patch),subs=next.substitutions.filter(x=>x.side===side).length;if(subs<next.maxSubstitutions&&bench.length){const tired=[...lineup].sort((a,b)=>(next.playerStates[a]?.condition??100)-(next.playerStates[b]?.condition??100))[0];if(tired&&(next.playerStates[tired]?.condition??100)<76)next=makeSubstitution(next,side,tired,bench[0]);}return{...next,aiAdjustments:next.aiAdjustments+1,events:[...next.events,{minute,type:"tactical",team:side,text:`${club.shortName} muda o plano: ${tacticSummary(raw,patch)}.`}]};}

export function advanceLiveMatchMinute(s:LiveMatchState,home:LeagueClub,away:LeagueClub):LiveMatchState{
 if(!activePhase(s)||requiredUserSubstitutions(s).length)return s;const minute=s.currentMinute+1;if(minute>90)return s;
 const rng=minuteRng(s,minute),playerStates=wear(s,home,away),working={...s,playerStates},homeXI=exactLineup(home,s.homeLineupIds),awayXI=exactLineup(away,s.awayLineupIds),talk=minute>=46?talkMomentum(s,minute):0,currentMomentum=s.momentumHome??0,hs=strength(working,home,s.homeLineupIds,s.homeTactic,(currentMomentum/100)*2+(s.userSide==="home"?talk:0))+2,as=strength(working,away,s.awayLineupIds,s.awayTactic,(-currentMomentum/100)*2+(s.userSide==="away"?talk:0)),diff=hs-as,ht=normalizeTactic(s.homeTactic),at=normalizeTactic(s.awayTactic),buildPoss=(ht.buildUp==="Curta"?3:ht.buildUp==="Direta"?-2:0)-(at.buildUp==="Curta"?3:at.buildUp==="Direta"?-2:0),target=clamp(50+diff*.72+buildPoss+rng.integer(-5,5),32,68),samples=s.possessionSamples+1,possessionHome=Math.round((s.possessionHome*s.possessionSamples+target)/samples);
 let homeGoals=s.homeGoals,awayGoals=s.awayGoals,shotsHome=s.shotsHome,shotsAway=s.shotsAway,xgHome=s.xgHome,xgAway=s.xgAway,bigHome=s.bigChancesHome,bigAway=s.bigChancesAway,passesHome=s.passesHome+Math.max(1,Math.round(target/(ht.buildUp==="Curta"?7.5:ht.buildUp==="Direta"?11:9)+rng.integer(-2,2))),passesAway=s.passesAway+Math.max(1,Math.round((100-target)/(at.buildUp==="Curta"?7.5:at.buildUp==="Direta"?11:9)+rng.integer(-2,2))),tacklesHome=s.tacklesHome+(rng.next()<(ht.marking==="Individual"?.24:.19)?1:0),tacklesAway=s.tacklesAway+(rng.next()<(at.marking==="Individual"?.24:.19)?1:0),interceptionsHome=s.interceptionsHome+(rng.next()<(ht.marking==="Zona"?.17:.13)?1:0),interceptionsAway=s.interceptionsAway+(rng.next()<(at.marking==="Zona"?.17:.13)?1:0),cornersHome=s.cornersHome??0,cornersAway=s.cornersAway??0,freeKicksHome=s.freeKicksHome??0,freeKicksAway=s.freeKicksAway??0;
 const events:MatchEvent[]=[],injured=[...s.injuredPlayerIds],sent=[...s.sentOffPlayerIds],homeZones={...zones(s.homeAttackZones)},awayZones={...zones(s.awayAttackZones)},homeHeat={...heat(s.homeHeatmap)},awayHeat={...heat(s.awayHeatmap)};let homeThreat=0,awayThreat=0;
 const visualRng=new SeededRng(`${s.seed}:visual-def:${minute}`),defensiveEvent=(side:MatchSide,type:"interception"|"tackle")=>{const xi=side==="home"?homeXI:awayXI,club=side==="home"?home:away,pool=rolePool(xi,["ZAG","VOL","MC","LE","LD"]);if(!pool.length)return;const player=visualRng.pick(pool);events.push({minute,type,team:side,playerId:player.id,text:type==="interception"?`${player.name} lê a jogada e intercepta para ${club.shortName}.`:`${player.name} entra no tempo certo e recupera a posse para ${club.shortName}.`});};
 if(interceptionsHome>s.interceptionsHome)defensiveEvent("home","interception");if(interceptionsAway>s.interceptionsAway)defensiveEvent("away","interception");if(tacklesHome>s.tacklesHome)defensiveEvent("home","tackle");if(tacklesAway>s.tacklesAway)defensiveEvent("away","tackle");
 const attack=(side:MatchSide)=>{const isHome=side==="home",xi=isHome?homeXI:awayXI,current=isHome?home:away,opponent=isHome?away:home,tactic=isHome?s.homeTactic:s.awayTactic,t=normalizeTactic(tactic),oppT=isHome?at:ht,strengthDiff=isHome?diff:-diff,zone=pickZone(rng,tactic),chance=clamp(.087+strengthDiff*.003+(t.tempo-50)*.0008+(t.mentality==="Ofensiva"?.018:t.mentality==="Defensiva"?-.012:0)+(t.buildUp==="Direta"?.009:t.buildUp==="Curta"?.002:0)+(oppT.defensiveLine==="Alta"?.009:oppT.defensiveLine==="Baixa"?-.005:0),.045,.21);if(isHome){homeZones[zone]++;addHeat(homeHeat,zone,rng.next()<.7?"att":"mid");}else{awayZones[zone]++;addHeat(awayHeat,zone,rng.next()<.7?"att":"mid");}if(!xi.length||rng.next()>=chance)return;const threat=.4+chance*3;if(isHome)homeThreat+=threat;else awayThreat+=threat;if(isHome)shotsHome++;else shotsAway++;const player=attacking(rng,xi,zone),focusBonus=(t.attackFocus==="Por dentro"&&zone==="center")||((t.attackFocus==="Pelos lados"||t.width==="Ampla")&&zone!=="center")?.018:0,shotXg=clamp(.105+strengthDiff*.004+rng.integer(-4,12)/100+focusBonus+(oppT.defensiveLine==="Alta"?.016:oppT.defensiveLine==="Baixa"?-.008:0),.025,.48);if(isHome){xgHome+=shotXg;if(shotXg>=.25)bigHome++;}else{xgAway+=shotXg;if(shotXg>=.25)bigAway++;}adjust(playerStates,player.id,.07);if(rng.next()<shotXg){if(isHome)homeGoals++;else awayGoals++;const a=assist(rng,xi,player);adjust(playerStates,player.id,.92);adjust(playerStates,a?.id,.48);events.push({minute,type:"goal",team:side,playerId:player.id,assistPlayerId:a?.id,zone,xg:round2(shotXg),text:`GOL DO ${current.shortName}! ${player.name} aparece pelo ${zone==="center"?"corredor central":zone==="left"?"lado esquerdo":"lado direito"} e converte xG ${shotXg.toFixed(2)}${a?` após passe de ${a.name}`:""}.`});}else events.push({minute,type:"chance",team:side,playerId:player.id,zone,xg:round2(shotXg),text:`${player.name} finaliza pelo ${zone==="center"?"centro":zone==="left"?"lado esquerdo":"lado direito"} (xG ${shotXg.toFixed(2)}), mas o ${opponent.shortName} resiste.`});
 if(rng.next()<.23){if(isHome)cornersHome++;else cornersAway++;const taker=setPiecePlayer(xi,t.setPieces.cornerTakerId,["MEI","PE","PD","MC"]),targetPlayer=setPiecePlayer(xi,t.setPieces.targetPlayerId,["ZAG","ATA"]),setXg=clamp(.045+(targetPlayer.overall-60)*.0015+(t.setPieces.cornerAttack==="Centro"?.012:0),.035,.14);events.push({minute,type:"corner",team:side,playerId:taker.id,zone,text:`Escanteio: ${taker.name} cobra no ${t.setPieces.cornerAttack.toLowerCase()}, procurando ${targetPlayer.name}.`});if(rng.next()<setXg){if(isHome)homeGoals++;else awayGoals++;if(isHome)xgHome+=setXg;else xgAway+=setXg;adjust(playerStates,targetPlayer.id,.9);adjust(playerStates,taker.id,.42);events.push({minute,type:"goal",team:side,playerId:targetPlayer.id,assistPlayerId:taker.id,xg:setXg,text:`GOL EM BOLA PARADA! ${targetPlayer.name} ganha a disputa após cobrança de ${taker.name}.`});}}
 };
 attack("home");attack("away");
 for(const side of ["home","away"] as const){const xi=side==="home"?homeXI:awayXI,t=normalizeTactic(side==="home"?s.homeTactic:s.awayTactic);if(!xi.length)continue;if(rng.next()<.011){const p=rng.pick(xi);adjust(playerStates,p.id,-.2);events.push({minute,type:"card",team:side,playerId:p.id,text:`Cartão amarelo para ${p.name}.`});}if(rng.next()<.0018&&xi.length>7){const p=rng.pick(xi);if(!sent.includes(p.id)){sent.push(p.id);adjust(playerStates,p.id,-.65);events.push({minute,type:"red_card",team:side,playerId:p.id,text:`EXPULSO! ${p.name} deixa a equipe com um jogador a menos.`});}}const risk=xi.reduce((acc,p)=>acc+Math.max(0,(playerStates[p.id]?.fatigue??0)-62),0)/Math.max(1,xi.length);if(rng.next()<.0007+risk/180000){const p=rng.pick(xi);if(!injured.includes(p.id)){injured.push(p.id);adjust(playerStates,p.id,-.08);events.push({minute,type:"injury",team:side,playerId:p.id,text:`${p.name} sente um problema físico. A carga acumulada preocupa a equipe médica.`});}}if(rng.next()<.012){if(side==="home")freeKicksHome++;else freeKicksAway++;const taker=setPiecePlayer(xi,t.setPieces.freeKickTakerId,["MEI","MC","PE","PD"]),fkXg=clamp(.05+(taker.overall-60)*.0018,.04,.15);events.push({minute,type:"free_kick",team:side,playerId:taker.id,xg:fkXg,text:`Falta em zona perigosa. ${taker.name} assume a bola.`});if(rng.next()<fkXg){if(side==="home")homeGoals++;else awayGoals++;events.push({minute,type:"goal",team:side,playerId:taker.id,xg:fkXg,text:`GOLAÇO DE FALTA! ${taker.name} converte a bola parada.`});}}}
 const homeGoalDelta=homeGoals-s.homeGoals,awayGoalDelta=awayGoals-s.awayGoals,momentumHome=updateMomentum(currentMomentum,homeThreat,awayThreat,homeGoalDelta,awayGoalDelta),momentumHistory=[...(s.momentumHistory??[{minute:0,home:0}]),{minute,home:momentumHome}].slice(-30);
 let next:LiveMatchState={...s,currentMinute:minute,playerStates,homeGoals,awayGoals,possessionHome,possessionSamples:samples,shotsHome,shotsAway,xgHome:round2(xgHome),xgAway:round2(xgAway),bigChancesHome:bigHome,bigChancesAway:bigAway,passesHome,passesAway,tacklesHome,tacklesAway,interceptionsHome,interceptionsAway,events:[...s.events,...events],injuredPlayerIds:injured,sentOffPlayerIds:sent,homeLineupIds:s.homeLineupIds.filter(id=>!sent.includes(id)),awayLineupIds:s.awayLineupIds.filter(id=>!sent.includes(id)),momentumHome,momentumHistory,homeAttackZones:homeZones,awayAttackZones:awayZones,homeHeatmap:homeHeat,awayHeatmap:awayHeat,cornersHome,cornersAway,freeKicksHome,freeKicksAway,tacticalChanges:s.tacticalChanges??[]};
 next=autoReplace(next,next.userSide==="home"?"away":"home");next=autoAi(next,home,away,minute);if(minute===45)next={...next,phase:"halftime",events:[...next.events,{minute:45,type:"halftime",team:"neutral",text:"Intervalo. Momentum, zonas e carga física são recalculados pela comissão."}]};if(minute===90)next={...next,phase:"fulltime",events:[...next.events,{minute:90,type:"fulltime",team:"neutral",text:`Fim de jogo: ${home.name} ${next.homeGoals} × ${next.awayGoals} ${away.name}.`}]};return next;
}

export function makeSubstitution(s:LiveMatchState,side:MatchSide,outPlayerId:string,inPlayerId:string):LiveMatchState{if(!canDecide(s)||s.substitutions.filter(x=>x.side===side).length>=s.maxSubstitutions)return s;const lineKey=side==="home"?"homeLineupIds":"awayLineupIds",benchKey=side==="home"?"homeBenchIds":"awayBenchIds",line=s[lineKey],bench=s[benchKey];if(!line.includes(outPlayerId)||!bench.includes(inPlayerId))return s;const nextLine=line.map(id=>id===outPlayerId?inPlayerId:id),nextBench=bench.filter(id=>id!==inPlayerId),sub:LiveSubstitution={side,outPlayerId,inPlayerId,minute:s.currentMinute};return{...s,[lineKey]:nextLine,[benchKey]:nextBench,substitutions:[...s.substitutions,sub],usedPlayerIds:[...new Set([...s.usedPlayerIds,inPlayerId])],events:[...s.events,{minute:s.currentMinute,type:"tactical",team:side,text:`Substituição: entra um novo jogador para alterar energia e encaixe da equipe.`}]};}
export function updateLiveTactic(s:LiveMatchState,side:MatchSide,tactic:MatchTactic):LiveMatchState{if(!canDecide(s))return s;const before=side==="home"?s.homeTactic:s.awayTactic,summary=tacticSummary(before,tactic),change:LiveTacticalChange={minute:s.currentMinute,side,summary};return side==="home"?{...s,homeTactic:tactic,tacticalChanges:[...(s.tacticalChanges??[]),change],events:[...s.events,{minute:s.currentMinute,type:"tactical",team:side,text:`Ajuste tático: ${summary}.`}]}:{...s,awayTactic:tactic,tacticalChanges:[...(s.tacticalChanges??[]),change],events:[...s.events,{minute:s.currentMinute,type:"tactical",team:side,text:`Ajuste tático: ${summary}.`}]};}
export function setTeamTalk(s:LiveMatchState,talk:TeamTalk):LiveMatchState{return s.phase!=="halftime"?s:{...s,teamTalk:talk};}
export function requiredUserSubstitutions(s:LiveMatchState){const line=s.userSide==="home"?s.homeLineupIds:s.awayLineupIds;return s.injuredPlayerIds.filter(id=>line.includes(id));}
export function isLiveMatchRunning(s:LiveMatchState){return activePhase(s);}
export function liveMatchResult(s:LiveMatchState):MatchResult{return{homeGoals:s.homeGoals,awayGoals:s.awayGoals,possessionHome:s.possessionHome,shotsHome:s.shotsHome,shotsAway:s.shotsAway,events:s.events,xgHome:s.xgHome,xgAway:s.xgAway,bigChancesHome:s.bigChancesHome,bigChancesAway:s.bigChancesAway,passesHome:s.passesHome,passesAway:s.passesAway,tacklesHome:s.tacklesHome,tacklesAway:s.tacklesAway,interceptionsHome:s.interceptionsHome,interceptionsAway:s.interceptionsAway,playerRatings:Object.fromEntries(Object.entries(s.playerStates).filter(([,v])=>v.minutes>0).map(([id,v])=>[id,v.rating])),playerConditionAfter:Object.fromEntries(Object.entries(s.playerStates).filter(([,v])=>v.minutes>0).map(([id,v])=>[id,v.condition])),playerFatigueAfter:Object.fromEntries(Object.entries(s.playerStates).filter(([,v])=>v.minutes>0).map(([id,v])=>[id,v.fatigue])),playerMinutes:Object.fromEntries(Object.entries(s.playerStates).filter(([,v])=>v.minutes>0).map(([id,v])=>[id,v.minutes]))};}
