import type { LeagueWorld } from "./league";

export type LegacySeason={year:number;clubName:string;position:number;points:number;goalsFor:number;goalsAgainst:number;topScorer:string;topScorerGoals:number;reputation:number};
export type PlayerCareerLine={playerId:string;name:string;clubName:string;seasons:number;appearances:number;goals:number;assists:number;bestRating:number;lastOverall:number;peakOverall:number;lastYear:number};
export type HallOfFameEntry={playerId:string;name:string;clubName:string;score:number;appearances:number;goals:number;assists:number;peakOverall:number;lastYear:number};
export type ClubRecordBook={bestPosition:number;bestPoints:number;mostGoals:number;bestScorer:string;bestScorerGoals:number;seasons:number};
export type LongTermWorldState={seasons:LegacySeason[];playerCareers:Record<string,PlayerCareerLine>;hallOfFame:HallOfFameEntry[];clubRecords:Record<string,ClubRecordBook>;leagueReputation:number;createdYear:number;updatedYear:number};

const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,Math.round(v)));
export function createLongTermWorld(year:number):LongTermWorldState{return{seasons:[],playerCareers:{},hallOfFame:[],clubRecords:{},leagueReputation:60,createdYear:year,updatedYear:year};}
export function hydrateLongTermWorld(state:LongTermWorldState|undefined,year:number):LongTermWorldState{const base=state??createLongTermWorld(year);return{...base,seasons:base.seasons??[],playerCareers:base.playerCareers??{},hallOfFame:base.hallOfFame??[],clubRecords:base.clubRecords??{},leagueReputation:base.leagueReputation??60,createdYear:base.createdYear??year,updatedYear:year};}
export function closeLongTermSeason(state:LongTermWorldState|undefined,league:LeagueWorld,year:number,selectedClubId:string){const next=structuredClone(hydrateLongTermWorld(state,year)),table=[...league.standings].sort((a,b)=>b.points-a.points||(b.goalsFor-b.goalsAgainst)-(a.goalsFor-a.goalsAgainst)),club=league.clubs.find(c=>c.id===selectedClubId)??league.clubs[0],row=table.find(r=>r.clubId===club.id),position=Math.max(1,table.findIndex(r=>r.clubId===club.id)+1),top=[...club.players].sort((a,b)=>(b.goals??0)-(a.goals??0)||(b.assists??0)-(a.assists??0))[0];
 next.seasons.unshift({year,clubName:club.name,position,points:row?.points??0,goalsFor:row?.goalsFor??0,goalsAgainst:row?.goalsAgainst??0,topScorer:top?.name??"—",topScorerGoals:top?.goals??0,reputation:club.reputation});next.seasons=next.seasons.slice(0,50);
 for(const c of league.clubs)for(const p of c.players){const old=next.playerCareers[p.id];next.playerCareers[p.id]={playerId:p.id,name:p.name,clubName:c.name,seasons:(old?.seasons??0)+1,appearances:(old?.appearances??0)+(p.appearances??0),goals:(old?.goals??0)+(p.goals??0),assists:(old?.assists??0)+(p.assists??0),bestRating:Math.max(old?.bestRating??0,p.averageRating??0),lastOverall:p.overall,peakOverall:Math.max(old?.peakOverall??p.overall,p.overall),lastYear:year};}
 const candidates=Object.values(next.playerCareers).map(p=>({...p,score:Math.round(p.goals*4+p.assists*2+p.appearances*.35+p.peakOverall*1.8+p.bestRating*12)})).sort((a,b)=>b.score-a.score).slice(0,30);next.hallOfFame=candidates.map(p=>({playerId:p.playerId,name:p.name,clubName:p.clubName,score:p.score,appearances:p.appearances,goals:p.goals,assists:p.assists,peakOverall:p.peakOverall,lastYear:p.lastYear}));
 for(const c of league.clubs){const r=table.find(x=>x.clubId===c.id),pos=Math.max(1,table.findIndex(x=>x.clubId===c.id)+1),scorer=[...c.players].sort((a,b)=>(b.goals??0)-(a.goals??0))[0],old=next.clubRecords[c.name];next.clubRecords[c.name]={bestPosition:Math.min(old?.bestPosition??99,pos),bestPoints:Math.max(old?.bestPoints??0,r?.points??0),mostGoals:Math.max(old?.mostGoals??0,r?.goalsFor??0),bestScorer:(scorer?.goals??0)>=(old?.bestScorerGoals??0)?scorer?.name??"—":old?.bestScorer??"—",bestScorerGoals:Math.max(old?.bestScorerGoals??0,scorer?.goals??0),seasons:(old?.seasons??0)+1};}
 const avgRep=league.clubs.reduce((s,c)=>s+c.reputation,0)/Math.max(1,league.clubs.length),continentalBonus=Math.min(8,next.hallOfFame.filter(p=>p.peakOverall>=84).length*.25);next.leagueReputation=clamp(avgRep*.75+next.leagueReputation*.25+continentalBonus,35,95);next.updatedYear=year;return next;}
