import{describe,expect,it}from"vitest";
import{createSeason,startNextSeason}from"./season";
import{createMarketState,isTransferWindowOpen,makeOfferForPlayer,processMarketRound,recommendedOffer,renewPlayerContract,toggleTransferList}from"./market";

describe("Sprint 6 — Mercado e contratos",()=>{
 it("gera contratos e orçamentos para toda a liga",()=>{const season=createSeason("contracts");for(const club of season.league.clubs){expect(club.transferBudgetEur).toBeGreaterThan(0);expect(club.wageBudgetBrlMonthly).toBeGreaterThan(0);for(const player of club.players){expect(player.contract.salaryBrlMonthly).toBeGreaterThan(0);expect(player.contract.endYear).toBeGreaterThanOrEqual(2027);expect(player.contract.agentName.length).toBeGreaterThan(3)}}});
 it("mapeia as duas janelas de 2026 para as rodadas do jogo",()=>{expect(isTransferWindowOpen(1)).toBe(true);expect(isTransferWindowOpen(6)).toBe(true);expect(isTransferWindowOpen(7)).toBe(false);expect(isTransferWindowOpen(19)).toBe(true);expect(isTransferWindowOpen(26)).toBe(true);expect(isTransferWindowOpen(27)).toBe(false)});
 it("lista e retira um jogador do mercado",()=>{const season=createSeason("listing"),player=season.league.clubs[0].players[0];let result=toggleTransferList(season,player.id);expect(result.state.league.clubs[0].players[0].transferListed).toBe(true);result=toggleTransferList(result.state,player.id);expect(result.state.league.clubs[0].players[0].transferListed).toBe(false)});
 it("impede transferência doméstica depois de 12 jogos",()=>{const season=createSeason("limit"),target=season.league.clubs[1].players[0];target.appearances=13;const result=makeOfferForPlayer(season,target.id);expect(result.state).toBe(season);expect(result.message).toContain("12 jogos")});
 it("registra uma proposta enviada durante a janela",()=>{const season=createSeason("offer"),target=season.league.clubs[1].players.sort((a,b)=>recommendedOffer(a)-recommendedOffer(b))[0];season.league.clubs[0].transferBudgetEur=100_000_000;season.league.clubs[0].wageBudgetBrlMonthly=100_000_000;const result=makeOfferForPlayer(season,target.id);expect(result.state.market.offers).toHaveLength(1);expect(result.state.market.offers[0].buyerClubId).toBe(season.selectedClubId);expect(["Aceita","Recusada"]).toContain(result.state.market.offers[0].status)});
 it("renovação nunca reduz salário nem duração",()=>{const season=createSeason("renew"),player=season.league.clubs[0].players.find(p=>p.personality==="Leal")??season.league.clubs[0].players[0],oldSalary=player.contract.salaryBrlMonthly,oldEnd=player.contract.endYear;season.league.clubs[0].wageBudgetBrlMonthly=100_000_000;const result=renewPlayerContract(season,player.id,3),next=result.state.league.clubs[0].players.find(p=>p.id===player.id)!;if(result.message.startsWith("Renovação fechada")){expect(next.contract.endYear).toBeGreaterThanOrEqual(oldEnd);expect(next.contract.salaryBrlMonthly).toBeGreaterThanOrEqual(oldSalary)}else expect(result.message).toContain("recusou")});
 it("IA de mercado é determinística por rodada",()=>{const a=processMarketRound(createSeason("ai-market")),b=processMarketRound(createSeason("ai-market"));expect(a.market).toEqual(b.market)});
 it("transferências manuais do save sobrevivem à virada da temporada quando o contrato segue vigente",()=>{const season=createSeason("career"),from=season.league.clubs[1],to=season.league.clubs[0],player=from.players.pop()!;player.contract.endYear=2029;to.players.push(player);season.completed=true;season.market=createMarketState();const next=startNextSeason(season);expect(next.year).toBe(2027);expect(next.league.clubs[0].players.some(p=>p.id===player.id)).toBe(true);expect(next.league.clubs[1].players.some(p=>p.id===player.id)).toBe(false);expect(next.league.fixtures).toHaveLength(380)});
});
