import type { MatchSide } from "./live-match";
import type { MatchScenePlan,SceneAction,SceneActor,ScenePoint } from "./match-2d-scene";
export type MotionBody={x:number;y:number;vx:number;vy:number;heading:number};
const clamp=(v:number,min=2,max=98)=>Math.max(min,Math.min(max,v));
const norm=(x:number,y:number)=>{const d=Math.hypot(x,y)||1;return{x:x/d,y:y/d}};
const other=(s:MatchSide):MatchSide=>s==="home"?"away":"home";
function roleLane(a:SceneActor,ball:ScenePoint,plan:MatchScenePlan){const attack=a.side===plan.attackingSide,dir=a.side==="home"?-1:1;let x=a.base.x,y=a.base.y;if(attack){const advance=["ATA","PE","PD","MEI"].includes(a.position)?9:["MC","VOL","LE","LD"].includes(a.position)?4:1;y+=dir*advance;x+=(ball.x-50)*(["PE","PD","LE","LD"].includes(a.position)?.18:.07);if(["LE","LD"].includes(a.position)&&Math.abs(ball.x-a.base.x)<24)y+=dir*5}else{y-=dir*2;x+=(ball.x-50)*.10}return{x:clamp(x),y:clamp(y)}}
export function desiredPlayerPoint(a:SceneActor,actors:SceneActor[],plan:MatchScenePlan,action:SceneAction,progress:number,ball:ScenePoint){let target=roleLane(a,ball,plan);const defending=a.side===other(plan.attackingSide);if(a.id===action.actorId){target={x:action.from.x+(action.to.x-action.from.x)*Math.min(.82,progress*.72),y:action.from.y+(action.to.y-action.from.y)*Math.min(.82,progress*.72)}}else if(a.id===action.receiverId){target={x:action.to.x,y:action.to.y}}else if(a.id===action.defenderId){target={x:action.to.x,y:action.to.y}}else if(defending){const mates=actors.filter(m=>m.side===a.side),nearest=[...mates].sort((p,q)=>Math.hypot(p.base.x-ball.x,p.base.y-ball.y)-Math.hypot(q.base.x-ball.x,q.base.y-ball.y)).slice(0,2).some(p=>p.id===a.id);if(nearest){target.x=target.x+(ball.x-target.x)*.42;target.y=target.y+(ball.y-target.y)*.36}else{target.x=target.x+(ball.x-target.x)*.10;target.y=target.y+(ball.y-target.y)*.08}}return{x:clamp(target.x),y:clamp(target.y)}}
export function stepMotion(body:MotionBody,target:ScenePoint,dt:number,overall:number,position:string){const dx=target.x-body.x,dy=target.y-body.y,d=Math.hypot(dx,dy),n=norm(dx,dy);const pace=(position==="GOL"?12:16)+(overall-60)*.075,maxSpeed=Math.max(10,pace),desired=Math.min(maxSpeed,d*3.0),dvx=n.x*desired-body.vx,dvy=n.y*desired-body.vy,maxAccel=34*dt,change=Math.hypot(dvx,dvy),scale=change>maxAccel?maxAccel/change:1;body.vx+=dvx*scale;body.vy+=dvy*scale;if(d<.7){body.vx*=Math.pow(.10,dt);body.vy*=Math.pow(.10,dt)}const speed=Math.hypot(body.vx,body.vy);if(speed>maxSpeed){body.vx=body.vx/speed*maxSpeed;body.vy=body.vy/speed*maxSpeed}body.x=clamp(body.x+body.vx*dt);body.y=clamp(body.y+body.vy*dt);if(speed>.2)body.heading=Math.atan2(body.vy,body.vx);return body}
export function initialMotion(a:SceneActor):MotionBody{return{x:a.base.x,y:a.base.y,vx:0,vy:0,heading:0}}
