import { SeededRng } from "./rng";
import type { LeagueClub, LeaguePlayer } from "./league";
import { tacticalFitMultiplier, type TacticalPoint } from "./tactical-position";
import { pressurePerformanceModifier } from "./personality";

export type Formation="4-2-3-1"|"4-3-3"|"4-4-2";
export type Mentality="Defensiva"|"Equilibrada"|"Ofensiva";
export type AttackFocus="Equilibrado"|"Pelos lados"|"Por dentro"|"Esquerda"|"Direita";
export type DefensiveLine="Baixa"|"Média"|"Alta";
export type TeamWidth="Estreita"|"Normal"|"Ampla";
export type BuildUp="Curta"|"Mista"|"Direta";
export type Marking="Zona"|"Individual"|"Mista";
export type SetPiecePost="Primeiro pau"|"Segundo pau"|"Centro";
export type SetPiecePlan={cornerAttack:SetPiecePost;cornerDefense:"Zona"|"Individual"|"Mista";cornerTakerId?:string;freeKickTakerId?:string;penaltyTakerId?:string;targetPlayerId?:string};
export type MatchTactic={formation:Formation;mentality:Mentality;pressing:number;tempo:number;positions?:Record<string,TacticalPoint>;attackFocus?:AttackFocus;defensiveLine?:DefensiveLine;width?:TeamWidth;buildUp?:BuildUp;marking?:Marking;setPieces?:SetPiecePlan};
export type MatchEventType="kickoff"|"chance"|"goal"|"card"|"red_card"|"injury"|"halftime"|"fulltime"|"corner"|"free_kick"|"penalty"|"tactical";
export type MatchEvent={minute:number;type:MatchEventType;team:"home"|"away"|"neutral";text:string;playerId?:string;assistPlayerId?:string;zone?:"left"|"center"|"right";xg?:number};
export type MatchResult={homeGoals:number;awayGoals:number;possessionHome:number;shotsHome:number;shotsAway:number;events:MatchEvent[];xgHome?:number;xgAway?:number;bigChancesHome?:number;bigChancesAway?:number;passesHome?:number;passesAway?:number;tacklesHome?:number;tacklesAway?:number;interceptionsHome?:number;interceptionsAway?:number;playerRatings?:Record<string,number>;playerConditionAfter?:Record<string,number>;playerFatigueAfter?:Record<string,number>;playerMinutes?:Record<string,number>};
export const DEFAULT_TACTIC:MatchTactic={formation:"4-2-3-1",mentality:"Equilibrada",pressing:62,tempo:58,attackFocus:"Equilibrado",defensiveLine:"Média",width:"Normal",buildUp:"Mista",marking:"Mista",setPieces:{cornerAttack:"Centro",cornerDefense:"Mista"}};

const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
export function normalizeTactic(tactic:MatchTactic):Required<Omit<MatchTactic,"positions"|"setPieces">>&{positions?:Record<string,TacticalPoint>;setPieces:SetPiecePlan}{return{formation:tactic.formation,mentality:tactic.mentality,pressing:tactic.pressing,tempo:tactic.tempo,positions:tactic.positions,attackFocus:tactic.attackFocus??"Equilibrado",defensiveLine:tactic.defensiveLine??"Média",width:tactic.width??"Normal",buildUp:tactic.buildUp??"Mista",marking:tactic.marking??"Mista",setPieces:{cornerAttack:tactic.setPieces?.cornerAttack??"Centro",cornerDefense:tactic.setPieces?.cornerDefense??"Mista",cornerTakerId:tactic.setPieces?.cornerTakerId,freeKickTakerId:tactic.setPieces?.freeKickTakerId,penaltyTakerId:tactic.setPieces?.penaltyTakerId,targetPlayerId:tactic.setPieces?.targetPlayerId}};}
export function pickStartingXI(club:LeagueClub,lineupIds?:string[]):LeaguePlayer[]{const available=club.players.filter(p=>p.injuryDays===0&&p.suspensionMatches===0),requested=(lineupIds??[]).map(id=>available.find(p=>p.id===id)).filter((p):p is LeaguePlayer=>Boolean(p)),selected=[...requested];for(const player of [...available].sort((a,b)=>b.overall-a.overall)){if(selected.length>=11)break;if(!selected.some(p=>p.id===player.id))selected.push(player);}return selected.slice(0,11);}
function rolePool(xi:LeaguePlayer[],positions:string[]){const pool=xi.filter(p=>positions.includes(p.position));return pool.length?pool:xi;}
function widthModifier(t:ReturnType<typeof normalizeTactic>){return t.width==="Ampla"?1.04:t.width==="Estreita"?.98:1;}
function buildModifier(t:ReturnType<typeof normalizeTactic>){return t.buildUp==="Curta"?{possession:1.08,chance:.96,turnover:.92}:t.buildUp==="Direta"?{possession:.94,chance:1.08,turnover:1.08}:{possession:1,chance:1,turnover:1};}
function lineModifier(t:ReturnType<typeof normalizeTactic>){return t.defensiveLine==="Alta"?{press:.8,risk:1.1}:t.defensiveLine==="Baixa"?{press:-.45,risk:.94}:{press:0,risk:1};}
function tacticalStrength(club:LeagueClub,tactic:MatchTactic,lineupIds?:string[]){const eleven=pickStartingXI(club,lineupIds),t=normalizeTactic(tactic);if(!eleven.length)return 40;const base=eleven.reduce((sum,p)=>sum+p.overall*(p.condition/100)*(.92+p.morale/1250)*Math.max(.78,1-p.fatigue/240)*tacticalFitMultiplier(p,t.positions?.[p.id])*pressurePerformanceModifier(p,.55),0)/eleven.length,mentality=t.mentality==="Ofensiva"?2.1:t.mentality==="Defensiva"?-1:0,shape=lineModifier(t),focus=t.attackFocus==="Equilibrado"?0:.45,mark=t.marking==="Individual"?.35:t.marking==="Zona"?.15:.25;return base+mentality+(t.pressing-50)*.025+(t.tempo-50)*.02+shape.press+focus+mark;}
function zoneWeights(tactic:MatchTactic){const t=normalizeTactic(tactic);let left=33,center=34,right=33;if(t.attackFocus==="Pelos lados"){left=42;center=16;right=42;}if(t.attackFocus==="Por dentro"){left=20;center=60;right=20;}if(t.attackFocus==="Esquerda"){left=60;center=25;right=15;}if(t.attackFocus==="Direita"){left=15;center=25;right=60;}if(t.width==="Ampla"){left+=5;right+=5;center-=10;}if(t.width==="Estreita"){left-=5;right-=5;center+=10;}return{left:Math.max(5,left),center:Math.max(5,center),right:Math.max(5,right)};}
function pickZone(rng:SeededRng,tactic:MatchTactic):"left"|"center"|"right"{const w=zoneWeights(tactic),total=w.left+w.center+w.right,r=rng.integer(1,total);return r<=w.left?"left":r<=w.left+w.center?"center":"right";}
function attackingPlayer(rng:SeededRng,xi:LeaguePlayer[],zone:"left"|"center"|"right"){if(zone==="left")return rng.pick(rolePool(xi,["PE","LE","MEI","MC","ATA"]));if(zone==="right")return rng.pick(rolePool(xi,["PD","LD","MEI","MC","ATA"]));return rng.pick(rolePool(xi,["ATA","MEI","MC","VOL"]));}
function assister(rng:SeededRng,xi:LeaguePlayer[],scorer:LeaguePlayer){const pool=xi.filter(p=>p.id!==scorer.id&&["ATA","PE","PD","MEI","MC","VOL","LE","LD"].includes(p.position));return pool.length&&rng.next()<.74?rng.pick(pool):undefined;}
function setPiecePlayer(club:LeagueClub,xi:LeaguePlayer[],id:string|undefined,fallback:string[]){return (id?xi.find(p=>p.id===id):undefined)??[...rolePool(xi,fallback)].sort((a,b)=>b.overall-a.overall)[0]??xi[0];}

export function simulateMatch(home:LeagueClub,away:LeagueClub,seed:string,homeTactic:MatchTactic=DEFAULT_TACTIC,awayTactic:MatchTactic=DEFAULT_TACTIC,homeLineupIds?:string[],awayLineupIds?:string[]):MatchResult{
 const rng=new SeededRng(seed),homeXI=pickStartingXI(home,homeLineupIds),awayXI=pickStartingXI(away,awayLineupIds),ht=normalizeTactic(homeTactic),at=normalizeTactic(awayTactic),homeStrength=tacticalStrength(home,homeTactic,homeLineupIds)+2.2,awayStrength=tacticalStrength(away,awayTactic,awayLineupIds),hb=buildModifier(ht),ab=buildModifier(at),share=clamp(Math.round(50+(homeStrength-awayStrength)*.8+(ht.buildUp==="Curta"?3:ht.buildUp==="Direta"?-2:0)-(at.buildUp==="Curta"?3:at.buildUp==="Direta"?-2:0)+rng.integer(-4,4)),35,65),shotsHome=Math.max(4,Math.round((9+(homeStrength-awayStrength)*.32+(ht.tempo-50)*.06+rng.integer(-2,4))*hb.chance*widthModifier(ht))),shotsAway=Math.max(4,Math.round((9+(awayStrength-homeStrength)*.28+(at.tempo-50)*.05+rng.integer(-2,3))*ab.chance*widthModifier(at))),events:MatchEvent[]=[{minute:0,type:"kickoff",team:"neutral",text:`Bola rolando. ${home.name} começa com a posse.`}];
 let homeGoals=0,awayGoals=0,xgHome=0,xgAway=0,bigHome=0,bigAway=0;
 const chances:Array<{minute:number;team:"home"|"away";xg:number;goal:boolean;zone:"left"|"center"|"right"}>=[];
 for(const [team,count,tactic,strengthDiff] of [["home",shotsHome,homeTactic,homeStrength-awayStrength],["away",shotsAway,awayTactic,awayStrength-homeStrength]] as const){for(let i=0;i<count;i++){const zone=pickZone(rng,tactic),t=normalizeTactic(tactic),zoneBonus=(t.attackFocus==="Por dentro"&&zone==="center")||((t.attackFocus==="Pelos lados"||t.width==="Ampla")&&zone!=="center")?.018:0,lineRisk=(team==="home"?at:ht).defensiveLine==="Alta"?.018:(team==="home"?at:ht).defensiveLine==="Baixa"?-.01:0,xg=clamp(.105+strengthDiff*.004+rng.integer(-5,10)/100+zoneBonus+lineRisk,.025,.48);chances.push({minute:rng.integer(3,89),team,xg,goal:rng.next()<xg,zone});if(team==="home"){xgHome+=xg;if(xg>=.25)bigHome++;}else{xgAway+=xg;if(xg>=.25)bigAway++;}}}
 chances.sort((a,b)=>a.minute-b.minute).forEach(chance=>{const club=chance.team==="home"?home:away,opponent=chance.team==="home"?away:home,xi=chance.team==="home"?homeXI:awayXI,attacker=attackingPlayer(rng,xi,chance.zone);if(chance.goal){if(chance.team==="home")homeGoals++;else awayGoals++;const assist=assister(rng,xi,attacker);events.push({minute:chance.minute,type:"goal",team:chance.team,playerId:attacker.id,assistPlayerId:assist?.id,zone:chance.zone,xg:chance.xg,text:`GOL DO ${club.shortName}! ${attacker.name} ataca pelo ${chance.zone==="center"?"corredor central":chance.zone==="left"?"lado esquerdo":"lado direito"} e conclui${assist?` após passe de ${assist.name}`:""}.`});}else events.push({minute:chance.minute,type:"chance",team:chance.team,playerId:attacker.id,zone:chance.zone,xg:chance.xg,text:`${attacker.name} cria pelo ${chance.zone==="center"?"centro":chance.zone==="left"?"lado esquerdo":"lado direito"} e finaliza (xG ${chance.xg.toFixed(2)}), mas o ${opponent.shortName} resiste.`});});
 for(const [side,club,xi,tactic] of [["home",home,homeXI,ht],["away",away,awayXI,at]] as const){const corners=Math.max(0,Math.round((side==="home"?shotsHome:shotsAway)/4+rng.integer(-1,1)));for(let i=0;i<corners;i++){const minute=rng.integer(8,88),taker=setPiecePlayer(club,xi,tactic.setPieces.cornerTakerId,["MEI","PE","PD","MC"]),target=setPiecePlayer(club,xi,tactic.setPieces.targetPlayerId,["ZAG","ATA"]),xg=.055+(target.overall-65)*.0016+(tactic.setPieces.cornerAttack==="Centro"?.012:0);events.push({minute,type:"corner",team:side,playerId:taker.id,zone:tactic.setPieces.cornerAttack==="Primeiro pau"?"left":tactic.setPieces.cornerAttack==="Segundo pau"?"right":"center",text:`Escanteio de ${taker.name} no ${tactic.setPieces.cornerAttack.toLowerCase()}, buscando ${target.name}.`});if(rng.next()<xg){if(side==="home")homeGoals++;else awayGoals++;if(side==="home")xgHome+=xg;else xgAway+=xg;events.push({minute,type:"goal",team:side,playerId:target.id,assistPlayerId:taker.id,xg,text:`GOL EM BOLA PARADA! ${target.name} vence a disputa após cobrança de ${taker.name}.`});}}
 if(rng.next()<.28){const minute=rng.integer(20,86),taker=setPiecePlayer(club,xi,tactic.setPieces.freeKickTakerId,["MEI","MC","PE","PD"]),xg=.07+(taker.overall-65)*.002;events.push({minute,type:"free_kick",team:side,playerId:taker.id,xg,text:`Falta direta para ${club.shortName}. ${taker.name} prepara a cobrança.`});if(rng.next()<xg){if(side==="home")homeGoals++;else awayGoals++;events.push({minute,type:"goal",team:side,playerId:taker.id,xg,text:`GOLAÇO DE FALTA! ${taker.name} acerta a cobrança direta.`});}}
 }
 events.push({minute:45,type:"halftime",team:"neutral",text:"Intervalo. As comissões recalibram estrutura, pressão e zonas de ataque."});
 if(rng.next()<.78){const homeCard=rng.next()<.5,xi=homeCard?homeXI:awayXI,player=rng.pick(xi);events.push({minute:rng.integer(51,82),type:"card",team:homeCard?"home":"away",playerId:player.id,text:`Cartão amarelo para ${player.name}.`});}
 if(rng.next()<.12){const homeRed=rng.next()<.5,xi=homeRed?homeXI:awayXI,player=rng.pick(xi);events.push({minute:rng.integer(58,87),type:"red_card",team:homeRed?"home":"away",playerId:player.id,text:`EXPULSO! ${player.name} recebe cartão vermelho e deixa sua equipe com um a menos.`});}
 for(const [team,xi] of [["home",homeXI],["away",awayXI]] as const){if(rng.next()<.08){const player=rng.pick(xi);events.push({minute:rng.integer(18,84),type:"injury",team,playerId:player.id,text:`${player.name} sente um problema físico e preocupa a comissão médica.`});}}
 events.push({minute:90,type:"fulltime",team:"neutral",text:`Fim de jogo: ${home.name} ${homeGoals} × ${awayGoals} ${away.name}.`});const order:MatchEventType[]=["kickoff","tactical","chance","corner","free_kick","penalty","goal","card","red_card","injury","halftime","fulltime"];events.sort((a,b)=>a.minute-b.minute||(order.indexOf(a.type)-order.indexOf(b.type)));
 return{homeGoals,awayGoals,possessionHome:share,shotsHome,shotsAway,events,xgHome:Math.round(xgHome*100)/100,xgAway:Math.round(xgAway*100)/100,bigChancesHome:bigHome,bigChancesAway:bigAway,passesHome:Math.round((290+share*4+rng.integer(-25,35))*hb.possession),passesAway:Math.round((290+(100-share)*4+rng.integer(-25,35))*ab.possession),tacklesHome:rng.integer(10,22)+(ht.marking==="Individual"?3:0),tacklesAway:rng.integer(10,22)+(at.marking==="Individual"?3:0),interceptionsHome:rng.integer(6,16)+(ht.marking==="Zona"?3:0),interceptionsAway:rng.integer(6,16)+(at.marking==="Zona"?3:0)};
}
