import { SeededRng } from "./rng";
import type { LeagueClub } from "./league";
import type { ProfessionalCompetitionId } from "../data/brazil-2026/competitions";
import { mediaProfileById, mediaProfilesForCompetition, SOCIAL_PROFILES, type MediaProfile, type SocialPlatform } from "./media-realism";

export type MediaSessionFormat="Coletiva pré-jogo"|"Coletiva pós-jogo"|"Programa esportivo"|"Zona mista";
export type MediaSessionStatus="Aberta"|"Concluída";
export type MediaRelation={profileId:string;respect:number;access:number;tension:number;interactions:number;lastRound?:number;lastOutcome?:string};
export type FanSegmentId="arquibancada"|"organizadas"|"socios"|"digital";
export type FanSegment={id:FanSegmentId;name:string;mood:number;influence:number;priority:string;lastShift?:string};
export type MediaChoiceEffect={mediaPressure?:number;fanSupport?:number;managerReputation?:number;boardConfidence?:number;respect?:number;access?:number;tension?:number;fanMood?:number};
export type MediaQuestionChoice={id:string;label:string;answer:string;effect:MediaChoiceEffect};
export type MediaQuestion={id:string;topic:string;prompt:string;choices:MediaQuestionChoice[]};
export type MediaSession={id:string;profileId:string;round:number;format:MediaSessionFormat;context:string;status:MediaSessionStatus;questionIndex:number;questions:MediaQuestion[];transcript:string[];score:number};
export type SocialTrend={id:string;platform:SocialPlatform;tag:string;headline:string;sentiment:"positivo"|"dividido"|"negativo";reach:number;round:number;source:string};
export type MediaWorldState={sequence:number;relations:Record<string,MediaRelation>;fanSegments:FanSegment[];sessions:MediaSession[];trends:SocialTrend[];lastPreMatchRound?:number;lastPostMatchRound?:number;lastProgramRound?:number};
export type MediaChoiceResult={mediaWorld:MediaWorldState;effect:MediaChoiceEffect;message:string;completed:boolean};

const clamp=(value:number)=>Math.max(0,Math.min(100,Math.round(value)));
const sanitizeTag=(name:string)=>name.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9]/g,"").slice(0,18)||"V90";

function relationFor(profile:MediaProfile):MediaRelation{return{profileId:profile.id,respect:55,access:48,tension:22,interactions:0};}
function defaultFanSegments():FanSegment[]{return[
 {id:"arquibancada",name:"Arquibancada",mood:72,influence:80,priority:"resultado, entrega e identidade"},
 {id:"organizadas",name:"Torcida organizada",mood:68,influence:86,priority:"raça, rivalidades e postura pública"},
 {id:"socios",name:"Sócios e frequentadores",mood:74,influence:65,priority:"planejamento, competitividade e ambiente"},
 {id:"digital",name:"Torcida digital",mood:70,influence:72,priority:"momento, escalações, memes e narrativas"},
];}
function ensureRelations(state:MediaWorldState,competitionId:ProfessionalCompetitionId){const relations={...state.relations};for(const profile of mediaProfilesForCompetition(competitionId))if(!relations[profile.id])relations[profile.id]=relationFor(profile);return{...state,relations};}
export function createMediaWorld(competitionId:ProfessionalCompetitionId):MediaWorldState{return ensureRelations({sequence:0,relations:{},fanSegments:defaultFanSegments(),sessions:[],trends:[]},competitionId);}
export function hydrateMediaWorld(value:MediaWorldState|undefined,competitionId:ProfessionalCompetitionId):MediaWorldState{if(!value)return createMediaWorld(competitionId);return ensureRelations({...value,relations:{...(value.relations??{})},fanSegments:(value.fanSegments?.length?value.fanSegments:defaultFanSegments()).map(item=>({...item})),sessions:(value.sessions??[]).map(session=>({...session,questions:session.questions.map(question=>({...question,choices:question.choices.map(choice=>({...choice,effect:{...choice.effect}}))})),transcript:[...session.transcript]})),trends:(value.trends??[]).map(item=>({...item}))},competitionId);}

function toneQuestion(profile:MediaProfile,context:string,phase:"pre"|"post"){const style=profile.style??"Analítico";if(phase==="pre"){if(style==="Provocador")return`A pressão sobre o trabalho cresceu. O que você diz a quem afirma que ${context} pode definir seu futuro?`;if(style==="Bastidores")return`Nos bastidores, existe confiança total nas suas escolhas para ${context}?`;if(style==="Torcida")return`O torcedor espera uma resposta forte em ${context}. Você promete protagonismo?`;return`Qual é a ideia central para enfrentar ${context} sem perder identidade?`;}if(style==="Provocador")return`O resultado muda a leitura sobre seu trabalho ou você acha que a cobrança está exagerada?`;if(style==="Bastidores")return`Que mensagem foi passada ao vestiário imediatamente depois do jogo?`;if(style==="Torcida")return`Que resposta você dá ao torcedor depois deste resultado?`;return`Qual aspecto do desempenho explica melhor o resultado de hoje?`;}
function standardChoices(phase:"pre"|"post",won?:boolean):MediaQuestionChoice[]{return[
 {id:"protect",label:"Proteger o grupo",answer:"O treinador protegeu o elenco e assumiu a responsabilidade pelo contexto.",effect:{respect:2,access:1,tension:-2,mediaPressure:phase==="post"&&won?-2:1,fanSupport:1,boardConfidence:-1}},
 {id:"direct",label:"Ser direto e cobrar",answer:"O treinador elevou publicamente o nível de exigência e cobrou resposta imediata.",effect:{respect:3,tension:3,mediaPressure:4,managerReputation:2,fanSupport:won?2:0}},
 {id:"confident",label:"Mostrar confiança",answer:"O treinador sustentou suas escolhas e transmitiu convicção no planejamento.",effect:{respect:2,access:2,tension:1,managerReputation:2,fanSupport:2,boardConfidence:1}},
];}
function secondQuestion(profile:MediaProfile,phase:"pre"|"post",won?:boolean):MediaQuestion{return{id:`${phase}-follow`,topic:phase==="pre"?"Escalação e ambiente":"Consequências",prompt:phase==="pre"?`${profile.journalist??profile.outlet} insiste: quanto a escolha dos titulares responde ao mérito e quanto responde ao momento do vestiário?`:`${profile.journalist??profile.outlet} pergunta sobre a sequência: este jogo muda hierarquia, confiança ou planejamento para a próxima rodada?`,choices:[
 {id:"merit",label:"Mérito acima de nomes",answer:"O treinador reforçou que a hierarquia será definida por rendimento e comportamento.",effect:{respect:3,tension:1,managerReputation:2,fanMood:1}},
 {id:"stability",label:"Preservar hierarquia",answer:"O treinador defendeu estabilidade e confiança nos líderes do elenco.",effect:{access:2,tension:-2,mediaPressure:-1,boardConfidence:1}},
 {id:"open",label:"Deixar disputa aberta",answer:"O treinador deixou a concorrência aberta e aumentou a expectativa para os próximos treinos.",effect:{respect:1,access:1,mediaPressure:2,fanSupport:won?1:0}},
]};}
function buildSession(profile:MediaProfile,round:number,format:MediaSessionFormat,context:string,phase:"pre"|"post"|"program",won?:boolean):MediaSession{const first:MediaQuestion=phase==="program"?{id:"program-main",topic:"Projeto",prompt:`No ${profile.program??profile.outlet}, a conversa é mais longa: qual deve ser a marca do seu trabalho nesta temporada?`,choices:[
 {id:"identity",label:"Identidade de jogo",answer:"O treinador colocou identidade tática e evolução coletiva no centro do projeto.",effect:{respect:4,access:3,managerReputation:2,mediaPressure:-1}},
 {id:"results",label:"Resultado acima de tudo",answer:"O treinador disse que o futebol profissional será sempre julgado principalmente pelos resultados.",effect:{respect:2,tension:2,fanSupport:2,mediaPressure:2,boardConfidence:2}},
 {id:"people",label:"Pessoas e ambiente",answer:"O treinador destacou gestão humana, confiança e desenvolvimento do elenco.",effect:{access:4,tension:-2,managerReputation:1,fanSupport:1}},
]}:{id:`${phase}-main`,topic:phase==="pre"?"Preparação":"Leitura do jogo",prompt:toneQuestion(profile,context,phase),choices:standardChoices(phase,won)};const questions=phase==="program"?[first,secondQuestion(profile,"pre")]:[first,secondQuestion(profile,phase,won)];return{id:`media-${round}-${format.replace(/\s/g,"-").toLowerCase()}-${profile.id}`,profileId:profile.id,round,format,context,status:"Aberta",questionIndex:0,questions,transcript:[],score:0};}
function pickProfile(state:MediaWorldState,competitionId:ProfessionalCompetitionId,seed:string,round:number,kind:string){const profiles=mediaProfilesForCompetition(competitionId),rng=new SeededRng(`${seed}:media:${round}:${kind}:${state.sequence}`);return rng.pick(profiles.length?profiles:mediaProfilesForCompetition("BRA1"));}
function addSession(state:MediaWorldState,session:MediaSession){if(state.sessions.some(item=>item.id===session.id))return state;return{...state,sequence:state.sequence+1,sessions:[session,...state.sessions].slice(0,36)};}
function shiftFans(state:MediaWorldState,delta:number,reason:string){return{...state,fanSegments:state.fanSegments.map(segment=>{const weight=segment.id==="organizadas"?1.15:segment.id==="digital"?1.1:segment.id==="socios"?.85:1;return{...segment,mood:clamp(segment.mood+delta*weight),lastShift:reason};})};}
function addTrend(state:MediaWorldState,trend:Omit<SocialTrend,"id">){const id=`trend-${state.sequence+1}-${trend.platform}-${trend.round}`;return{...state,sequence:state.sequence+1,trends:[{...trend,id},...state.trends].slice(0,48)};}

export function mediaBeforeRound(value:MediaWorldState|undefined,competitionId:ProfessionalCompetitionId,club:LeagueClub,round:number,seed:string,mediaPressure=40):MediaWorldState{let state=hydrateMediaWorld(value,competitionId);if(state.lastPreMatchRound===round)return state;state={...state,lastPreMatchRound:round};const profile=pickProfile(state,competitionId,seed,round,"pre"),shouldOpen=round===1||round%2===0||mediaPressure>=62;if(shouldOpen)state=addSession(state,buildSession(profile,round,"Coletiva pré-jogo",`a próxima partida do ${club.name}`,"pre"));if(round%4===0&&state.lastProgramRound!==round){const guest=pickProfile(state,competitionId,seed,round,"program");state=addSession({...state,lastProgramRound:round},buildSession(guest,round,"Programa esportivo",club.name,"program"));}return state;}
export function mediaAfterMatch(value:MediaWorldState|undefined,competitionId:ProfessionalCompetitionId,club:LeagueClub,round:number,goalsFor:number,goalsAgainst:number,seed:string):MediaWorldState{let state=hydrateMediaWorld(value,competitionId);if(state.lastPostMatchRound===round)return state;const won=goalsFor>goalsAgainst,lost=goalsFor<goalsAgainst,profile=pickProfile(state,competitionId,seed,round,"post"),context=won?`a vitória por ${goalsFor}–${goalsAgainst}`:lost?`a derrota por ${goalsFor}–${goalsAgainst}`:`o empate por ${goalsFor}–${goalsAgainst}`;state={...state,lastPostMatchRound:round};state=addSession(state,buildSession(profile,round,"Coletiva pós-jogo",context,"post",won));state=shiftFans(state,won?4:lost?-5:0,won?"vitória":lost?"derrota":"empate");const rng=new SeededRng(`${seed}:social:${round}:${club.id}`),platforms=SOCIAL_PROFILES.map(item=>item.platform),count=won||lost?2:1;for(let i=0;i<count;i++){const platform=rng.pick(platforms),positive=won||( !lost&&rng.next()>.45),sentiment=positive?"positivo":lost?"negativo":"dividido",tag=`#${sanitizeTag(club.shortName||club.name)}${positive?"EmAlta":"Pressao"}`;state=addTrend(state,{platform,tag,headline:positive?`${club.name} ganha força na conversa digital`:`Cobrança sobre ${club.name} cresce nas redes`,sentiment,reach:rng.integer(38,96),round,source:`${platform} • simulação`});}return state;}

export function answerMediaSession(value:MediaWorldState|undefined,competitionId:ProfessionalCompetitionId,sessionId:string,choiceId:string):MediaChoiceResult{const state=hydrateMediaWorld(value,competitionId),index=state.sessions.findIndex(item=>item.id===sessionId);if(index<0)return{mediaWorld:state,effect:{},message:"Entrevista não encontrada.",completed:false};const session={...state.sessions[index],questions:state.sessions[index].questions.map(question=>({...question,choices:question.choices.map(choice=>({...choice,effect:{...choice.effect}}))})),transcript:[...state.sessions[index].transcript]};if(session.status==="Concluída")return{mediaWorld:state,effect:{},message:"Esta entrevista já foi concluída.",completed:true};const question=session.questions[session.questionIndex],choice=question?.choices.find(item=>item.id===choiceId);if(!question||!choice)return{mediaWorld:state,effect:{},message:"Resposta inválida.",completed:false};const profile=mediaProfileById(session.profileId),relation={...(state.relations[session.profileId]??relationFor(profile!))};relation.respect=clamp(relation.respect+(choice.effect.respect??0));relation.access=clamp(relation.access+(choice.effect.access??0));relation.tension=clamp(relation.tension+(choice.effect.tension??0));relation.interactions++;relation.lastRound=session.round;relation.lastOutcome=choice.answer;session.transcript.push(`${profile?.journalist??profile?.outlet??"Imprensa"}: ${question.prompt}`,`Treinador: ${choice.answer}`);session.score+=((choice.effect.respect??0)+(choice.effect.access??0)-(choice.effect.tension??0));session.questionIndex++;const completed=session.questionIndex>=session.questions.length;if(completed)session.status="Concluída";const sessions=[...state.sessions];sessions[index]=session;let mediaWorld={...state,relations:{...state.relations,[session.profileId]:relation},sessions};if(choice.effect.fanMood)mediaWorld=shiftFans(mediaWorld,choice.effect.fanMood,"declaração pública");const name=profile?.journalist??profile?.outlet??"a imprensa";return{mediaWorld,effect:choice.effect,message:completed?`Entrevista com ${name} concluída. A relação com a imprensa e a torcida foi atualizada.`:`Resposta registrada. ${name} tem mais uma pergunta.`,completed};}
export function pendingMediaSessions(value:MediaWorldState|undefined,competitionId:ProfessionalCompetitionId){return hydrateMediaWorld(value,competitionId).sessions.filter(session=>session.status==="Aberta");}
export function mediaRelationLabel(relation:MediaRelation){if(relation.tension>=68)return"Tensa";if(relation.respect>=72&&relation.access>=62)return"Próxima";if(relation.respect>=62)return"Respeitosa";if(relation.respect<=38)return"Fria";return"Profissional";}
