import type { LeaguePlayer } from "./league";
import type { SeasonState } from "./season";
import { returnToPlayAssessment } from "./player-health";
import { workloadAdvice, type WorkloadLevel } from "./workload";

export type MedicalRisk="Baixo"|"Moderado"|"Alto"|"Crítico";
export type PlayerMedicalReport={playerId:string;playerName:string;availability:"Indisponível"|"Restrito"|"Liberado";risk:MedicalRisk;recommendedMinutes:number;condition:number;fatigue:number;injuryDays:number;reason:string};
export type MedicalSquadReport={date:string;departmentLevel:number;teamLoad:WorkloadLevel;rotationRecommended:boolean;recommendedTraining:"Recuperação"|"Equilibrado";unavailable:number;restricted:number;highRisk:number;players:PlayerMedicalReport[]};

function clamp(v:number,min:number,max:number){return Math.max(min,Math.min(max,v));}
function riskFor(player:LeaguePlayer,teamLoad:WorkloadLevel,medicalLevel:number):MedicalRisk{if(player.injuryDays>0)return"Crítico";let score=Math.max(0,player.fatigue-35)*.9+Math.max(0,82-player.condition)*1.05+(player.age>=34?10:player.age>=31?5:0)+(teamLoad==="Crítica"?25:teamLoad==="Alta"?14:teamLoad==="Moderada"?6:0)-(medicalLevel-3)*5;score=clamp(score,0,100);return score>=70?"Crítico":score>=48?"Alto":score>=25?"Moderado":"Baixo";}
export function playerMedicalReport(state:SeasonState,playerId:string,date=state.currentDate):PlayerMedicalReport|undefined{const club=state.league.clubs.find(c=>c.id===state.selectedClubId),player=club?.players.find(p=>p.id===playerId);if(!player)return undefined;const load=workloadAdvice(state,date),returning=returnToPlayAssessment(player),risk=riskFor(player,load.level,load.medicalLevel),availability=returning.status==="Indisponível"?"Indisponível":returning.status==="Liberado com restrições"||risk==="Crítico"||risk==="Alto"?"Restrito":"Liberado",recommendedMinutes=availability==="Indisponível"?0:availability==="Restrito"?Math.min(returning.recommendedMinutes,risk==="Crítico"?30:60):90;return{playerId:player.id,playerName:player.name,availability,risk,recommendedMinutes,condition:Math.round(player.condition),fatigue:Math.round(player.fatigue),injuryDays:player.injuryDays,reason:`${returning.reason} Carga coletiva ${load.level.toLowerCase()} (${load.score}/100).`};}
export function medicalSquadReport(state:SeasonState,date=state.currentDate):MedicalSquadReport{const club=state.league.clubs.find(c=>c.id===state.selectedClubId)??state.league.clubs[0],load=workloadAdvice(state,date),players=club.players.map(player=>playerMedicalReport(state,player.id,date)!).sort((a,b)=>{const rank=(r:MedicalRisk)=>r==="Crítico"?4:r==="Alto"?3:r==="Moderado"?2:1;return rank(b.risk)-rank(a.risk)||a.recommendedMinutes-b.recommendedMinutes;});return{date,departmentLevel:load.medicalLevel,teamLoad:load.level,rotationRecommended:load.rotationRecommended,recommendedTraining:load.recommendedTraining,unavailable:players.filter(p=>p.availability==="Indisponível").length,restricted:players.filter(p=>p.availability==="Restrito").length,highRisk:players.filter(p=>p.risk==="Crítico"||p.risk==="Alto").length,players};}
