import { NATIONAL_TEAMS_2026, NATIONS_LEAGUE_2026_27_GROUPS, WORLD_CUP_2026_GROUPS, type NationalTeam } from "../data/national-teams-2026";
import { SeededRng } from "./rng";
import type { LeagueWorld } from "./league";

export type NationalCareerStatus="Sem seleção"|"Empregado";
export type NationalPoolPlayer={id:string;sourcePlayerId?:string;name:string;position:string;age:number;overall:number;clubName:string;nationality:string;virtual:boolean};
export type NationalFixture={id:string;date:string;competition:"Copa do Mundo"|"Nations League"|"Amistoso";stage:string;homeTeamId:string;awayTeamId:string;homeName:string;awayName:string;played:boolean;homeGoals?:number;awayGoals?:number;shotsHome?:number;shotsAway?:number;possessionHome?:number;tieId?:string;leg?:1|2;winnerTeamId?:string;decidedByPenalties?:boolean};
export type NationalJobOffer={id:string;teamId:string;teamName:string;reputation:number;expiresRound:number};
export type NationalHistory={id:string;date:string;competition:string;stage:string;opponent:string;score:string;result:"V"|"E"|"D"};
export type NationalCompetitionStatus={competition:"Copa do Mundo"|"Nations League";stage:string;status:"Em andamento"|"Classificado"|"Eliminado"|"Campeão"|"Encerrado";played:number;points:number;goalsFor:number;goalsAgainst:number;note?:string};
export type NationalCareerState={status:NationalCareerStatus;teamId?:string;teamName?:string;sequence:number;offers:NationalJobOffer[];pool:NationalPoolPlayer[];squadIds:string[];lineupIds:string[];fixtures:NationalFixture[];history:NationalHistory[];calendarNotes:string[];lastOfferRound?:number;selectedFormation?:"4-2-3-1"|"4-3-3"|"4-4-2";competitionStatus?:NationalCompetitionStatus[]};
export type NationalActionResult={career:NationalCareerState;message:string;playedFixture?:NationalFixture;usedSourcePlayerIds?:string[]};

const byName=(name:string)=>NATIONAL_TEAMS_2026.find(t=>t.name===name);
const byId=(id:string)=>NATIONAL_TEAMS_2026.find(t=>t.id===id);
function opponentsForNations(name:string){for(const leagues of Object.values(NATIONS_LEAGUE_2026_27_GROUPS))for(const teams of Object.values(leagues))if((teams as readonly string[]).includes(name))return [...teams].filter(t=>t!==name);return[];}
function nationsTier(name:string){for(const [tier,groups] of Object.entries(NATIONS_LEAGUE_2026_27_GROUPS))for(const teams of Object.values(groups))if((teams as readonly string[]).includes(name))return tier;return undefined;}
function wcGroup(name:string){for(const [group,teams] of Object.entries(WORLD_CUP_2026_GROUPS))if(teams.includes(name))return{group,teams};return undefined;}
function fixture(id:string,date:string,competition:NationalFixture["competition"],stage:string,home:string,away:string,extra:Partial<NationalFixture>={}):NationalFixture{const h=byName(home),a=byName(away);return{id,date,competition,stage,homeTeamId:h?.id??home,awayTeamId:a?.id??away,homeName:home,awayName:away,played:false,...extra};}
function friendlyOpponent(team:NationalTeam,seed:string,key:string,exclude:string[]=[]){const rng=new SeededRng(`${seed}:friendly:${team.id}:${key}`),pool=NATIONAL_TEAMS_2026.filter(t=>t.id!==team.id&&!exclude.includes(t.name));return rng.pick(pool.length?pool:NATIONAL_TEAMS_2026.filter(t=>t.id!==team.id));}
function buildFixtures(team:NationalTeam,year:number,seed:string){const out:NationalFixture[]=[],used=new Set<string>();const add=(f:NationalFixture)=>{if(!used.has(f.date)){out.push(f);used.add(f.date)}};const wc=year===2026?wcGroup(team.name):undefined;if(wc){const dates=["2026-06-12","2026-06-18","2026-06-24"];wc.teams.filter(n=>n!==team.name).forEach((opp,i)=>add(fixture(`nat-wc-${team.id}-${i+1}`,dates[i],"Copa do Mundo",`Grupo ${wc.group} • rodada ${i+1}`,i%2===0?team.name:opp,i%2===0?opp:team.name)));}
 const nations=year===2026?opponentsForNations(team.name):[];if(nations.length){const dates=["2026-09-24","2026-09-28","2026-10-02","2026-10-06","2026-11-13","2026-11-17"];[...nations,...nations].forEach((opp,i)=>add(fixture(`nat-unl-${team.id}-${i+1}`,dates[i],"Nations League",`Fase de grupos • rodada ${i+1}`,i<3?team.name:opp,i<3?opp:team.name)));}
 const officialOpponents=out.flatMap(f=>[f.homeName,f.awayName]);const friendlyDates=[`${year}-03-28`,`${year}-06-05`,...(!nations.length?[`${year}-09-26`,`${year}-11-14`]:[])];friendlyDates.forEach((date,i)=>{if(used.has(date))return;const opp=friendlyOpponent(team,seed,`${year}:${i}`,officialOpponents);add(fixture(`nat-friendly-${team.id}-${year}-${i+1}`,date,"Amistoso","Data FIFA",i%2===0?team.name:opp.name,i%2===0?opp.name:team.name));});return out.sort((a,b)=>a.date.localeCompare(b.date));}
function virtualPool(team:NationalTeam,seed:string){const rng=new SeededRng(`${seed}:virtual-national:${team.id}`),positions=["GOL","GOL","GOL","ZAG","ZAG","ZAG","ZAG","LD","LE","VOL","VOL","MC","MC","MC","MEI","MEI","PD","PE","ATA","ATA","ATA"];return Array.from({length:38},(_,i):NationalPoolPlayer=>({id:`nat-virtual-${team.id}-${i+1}`,name:`${team.shortName} ${i+1}`,position:positions[i%positions.length],age:rng.integer(19,32),overall:Math.max(58,Math.min(93,team.reputation+rng.integer(-13,3))),clubName:"Exterior",nationality:team.name,virtual:true}));}
function buildPool(team:NationalTeam,league:LeagueWorld,seed:string){const real=league.clubs.flatMap(club=>club.players.filter(p=>p.nationality===team.name).map((p):NationalPoolPlayer=>({id:`nat-${p.id}`,sourcePlayerId:p.id,name:p.name,position:p.position,age:p.age,overall:p.overall,clubName:club.name,nationality:team.name,virtual:false})));return[...real,...virtualPool(team,seed)].sort((a,b)=>b.overall-a.overall).slice(0,72);}
const DEF=new Set(["ZAG","LD","LE"]),MID=new Set(["VOL","MC","MEI"]),ATT=new Set(["PD","PE","ATA"]);
function bestLineup(pool:NationalPoolPlayer[],squadIds:string[]){const selected=pool.filter(p=>squadIds.includes(p.id)).sort((a,b)=>b.overall-a.overall),chosen:NationalPoolPlayer[]=[];const take=(positions:Set<string>,count:number)=>{for(const p of selected.filter(p=>positions.has(p.position)))if(chosen.length<11&&chosen.filter(c=>positions.has(c.position)).length<count&&!chosen.some(c=>c.id===p.id))chosen.push(p)};take(new Set(["GOL"]),1);take(DEF,4);take(MID,3);take(ATT,3);for(const p of selected)if(chosen.length<11&&!chosen.some(c=>c.id===p.id))chosen.push(p);return chosen.slice(0,11).map(p=>p.id);}
function initialOffers(managerReputation:number,round:number,seed:string){const rng=new SeededRng(`${seed}:national-offers:${round}`),eligible=NATIONAL_TEAMS_2026.filter(t=>t.reputation<=managerReputation+18).sort((a,b)=>b.reputation-a.reputation).slice(0,36),picked:NationalTeam[]=[];while(eligible.length&&picked.length<4)picked.push(eligible.splice(rng.integer(0,eligible.length-1),1)[0]);return picked.map((t,i)=>({id:`nat-offer-${round}-${i}-${t.id}`,teamId:t.id,teamName:t.name,reputation:t.reputation,expiresRound:round+4}));}
function pointsFor(career:NationalCareerState,competition:NationalFixture["competition"],groupOnly=true){if(!career.teamId)return{played:0,points:0,gf:0,ga:0};const matches=career.fixtures.filter(f=>f.played&&f.competition===competition&&(!groupOnly||f.stage.includes("Grupo")||f.stage.includes("Fase de grupos")));let points=0,gf=0,ga=0;for(const f of matches){const home=f.homeTeamId===career.teamId,a=home?(f.homeGoals??0):(f.awayGoals??0),b=home?(f.awayGoals??0):(f.homeGoals??0);gf+=a;ga+=b;points+=a>b?3:a===b?1:0;}return{played:matches.length,points,gf,ga};}
function opponentForKnockout(career:NationalCareerState,seed:string,stage:string){const recent=new Set(career.fixtures.flatMap(f=>[f.homeName,f.awayName])),rng=new SeededRng(`${seed}:nat-ko:${career.teamId}:${stage}:${career.sequence}`),pool=NATIONAL_TEAMS_2026.filter(t=>t.id!==career.teamId&&!recent.has(t.name));return rng.pick(pool.length?pool:NATIONAL_TEAMS_2026.filter(t=>t.id!==career.teamId));}
function addKnockout(career:NationalCareerState,competition:"Copa do Mundo"|"Nations League",stage:string,date:string,seed:string,extra:Partial<NationalFixture>={}){if(career.fixtures.some(f=>f.competition===competition&&f.stage===stage))return;const opp=opponentForKnockout(career,seed,`${competition}:${stage}`),home=career.sequence%2===0?career.teamName!:opp.name,away=career.sequence%2===0?opp.name:career.teamName!;career.fixtures.push(fixture(`nat-ko-${career.teamId}-${competition}-${stage.replace(/\W+/g,"-").toLowerCase()}`,date,competition,stage,home,away,extra));career.fixtures.sort((a,b)=>a.date.localeCompare(b.date));}
function matchResultForTeam(career:NationalCareerState,f:NationalFixture){const home=f.homeTeamId===career.teamId,gf=home?(f.homeGoals??0):(f.awayGoals??0),ga=home?(f.awayGoals??0):(f.homeGoals??0),won=f.winnerTeamId?f.winnerTeamId===career.teamId:gf>ga;return{gf,ga,won};}
function setStatus(career:NationalCareerState,next:NationalCompetitionStatus){career.competitionStatus=career.competitionStatus??[];const i=career.competitionStatus.findIndex(s=>s.competition===next.competition);if(i>=0)career.competitionStatus[i]=next;else career.competitionStatus.push(next);}
function syncCompetitionProgress(career:NationalCareerState,seed:string){if(career.status!=="Empregado"||!career.teamId)return career;const wcGroupMatches=career.fixtures.filter(f=>f.competition==="Copa do Mundo"&&f.stage.includes("Grupo")),wcStats=pointsFor(career,"Copa do Mundo");if(wcGroupMatches.length){let status:NationalCompetitionStatus={competition:"Copa do Mundo",stage:wcStats.played<3?"Fase de grupos":"Classificação",status:"Em andamento",played:wcStats.played,points:wcStats.points,goalsFor:wcStats.gf,goalsAgainst:wcStats.ga,note:"Avançam os dois primeiros e os oito melhores terceiros."};if(wcStats.played>=3){const qualified=wcStats.points>=4||(wcStats.points===3&&wcStats.gf-wcStats.ga>=0);if(qualified){status={...status,stage:"32 avos",status:"Classificado",note:"Vaga confirmada no mata-mata."};addKnockout(career,"Copa do Mundo","32 avos","2026-06-30",seed);}else status={...status,status:"Eliminado",note:"Campanha encerrada na fase de grupos."};}
 const stages=["32 avos","Oitavas de final","Quartas de final","Semifinais","Final"];const dates=["2026-06-30","2026-07-05","2026-07-10","2026-07-14","2026-07-19"];for(let i=0;i<stages.length;i++){const f=career.fixtures.find(x=>x.competition==="Copa do Mundo"&&x.stage===stages[i]);if(!f?.played)break;const r=matchResultForTeam(career,f);if(!r.won){if(stages[i]==="Semifinais")addKnockout(career,"Copa do Mundo","3º lugar","2026-07-18",seed);status={...status,stage:stages[i],status:"Eliminado",note:`Eliminado em ${stages[i]}.`};break;}if(stages[i]==="Final"){status={...status,stage:"Final",status:"Campeão",note:"Campeão mundial."};break;}const next=stages[i+1];status={...status,stage:next,status:"Classificado",note:`Classificado para ${next}.`};addKnockout(career,"Copa do Mundo",next,dates[i+1],seed);}
 setStatus(career,status);}
 const nlGroup=career.fixtures.filter(f=>f.competition==="Nations League"&&f.stage.includes("Fase de grupos")),nlStats=pointsFor(career,"Nations League");if(nlGroup.length){let status:NationalCompetitionStatus={competition:"Nations League",stage:nlStats.played<6?"Fase de grupos":"Classificação",status:"Em andamento",played:nlStats.played,points:nlStats.points,goalsFor:nlStats.gf,goalsAgainst:nlStats.ga,note:"Seis jogos na fase de grupos."};if(nlStats.played>=6){const tier=nationsTier(career.teamName!);if(tier==="A"&&nlStats.points>=9){status={...status,stage:"Quartas de final",status:"Classificado",note:"Classificado às quartas da Liga A."};const tie=`nat-unl-qf-${career.teamId}`;if(!career.fixtures.some(f=>f.tieId===tie)){const opp=opponentForKnockout(career,seed,"Nations League:Quartas de final");career.fixtures.push(fixture(`${tie}-ida`,"2027-03-25","Nations League","Quartas • ida",career.teamName!,opp.name,{tieId:tie,leg:1}),fixture(`${tie}-volta`,"2027-03-29","Nations League","Quartas • volta",opp.name,career.teamName!,{tieId:tie,leg:2}));career.fixtures.sort((a,b)=>a.date.localeCompare(b.date));}}else status={...status,status:"Encerrado",note:tier==="A"?"Não avançou às quartas.":"Fase de grupos encerrada nesta edição."};}
 const qf=career.fixtures.filter(f=>f.competition==="Nations League"&&f.tieId===`nat-unl-qf-${career.teamId}`).sort((a,b)=>(a.leg??0)-(b.leg??0));if(qf.length===2&&qf.every(f=>f.played)){let gf=0,ga=0;for(const f of qf){const r=matchResultForTeam(career,f);gf+=r.gf;ga+=r.ga;}const qualified=gf>ga||(gf===ga&&qf[1].winnerTeamId===career.teamId);if(qualified){status={...status,stage:"Semifinais",status:"Classificado",note:`Quartas vencidas no agregado por ${gf}–${ga}.`};addKnockout(career,"Nations League","Semifinais","2027-06-09",seed);}else status={...status,stage:"Quartas de final",status:"Eliminado",note:`Eliminado nas quartas por ${gf}–${ga} no agregado.`};}
 const semi=career.fixtures.find(f=>f.competition==="Nations League"&&f.stage==="Semifinais");if(semi?.played){if(matchResultForTeam(career,semi).won){status={...status,stage:"Final",status:"Classificado",note:"Classificado à final da Nations League."};addKnockout(career,"Nations League","Final","2027-06-13",seed);}else status={...status,stage:"Semifinais",status:"Eliminado",note:"Eliminado na semifinal."};}
 const final=career.fixtures.find(f=>f.competition==="Nations League"&&f.stage==="Final");if(final?.played)status={...status,status:matchResultForTeam(career,final).won?"Campeão":"Eliminado",stage:"Final",note:matchResultForTeam(career,final).won?"Campeão da Nations League.":"Vice-campeão da Nations League."};setStatus(career,status);}
 return career;}
export function createNationalCareer(league:LeagueWorld,seed:string,year:number,managerReputation=55,round=1):NationalCareerState{return{status:"Sem seleção",sequence:0,offers:initialOffers(managerReputation,round,seed),pool:[],squadIds:[],lineupIds:[],fixtures:[],history:[],calendarNotes:[],lastOfferRound:round,selectedFormation:"4-2-3-1",competitionStatus:[]};}
export function hydrateNationalCareer(value:NationalCareerState|undefined,league:LeagueWorld,seed:string,year:number,managerReputation=55,round=1,currentDate?:string){const state=value?structuredClone(value):createNationalCareer(league,seed,year,managerReputation,round);state.offers=(state.offers??[]).filter(o=>o.expiresRound>=round);state.history=state.history??[];state.calendarNotes=state.calendarNotes??[];state.competitionStatus=state.competitionStatus??[];state.selectedFormation=state.selectedFormation??"4-2-3-1";if(state.status==="Empregado"&&state.teamId){const team=byId(state.teamId);if(team){state.teamName=team.name;state.pool=buildPool(team,league,seed);const generated=buildFixtures(team,year,seed),existing=new Set((state.fixtures??[]).map(f=>f.id));state.fixtures=(state.fixtures??[]).filter(f=>!(currentDate&&f.competition==="Amistoso"&&!f.played&&f.date<currentDate));for(const f of generated)if(!existing.has(f.id)&&(!currentDate||f.date>=currentDate))state.fixtures.push(f);state.fixtures.sort((a,b)=>a.date.localeCompare(b.date));state.squadIds=(state.squadIds??[]).filter(id=>state.pool.some(p=>p.id===id));if(state.squadIds.length<18)state.squadIds=state.pool.slice(0,26).map(p=>p.id);state.lineupIds=(state.lineupIds??[]).filter(id=>state.squadIds.includes(id));if(state.lineupIds.length!==11)state.lineupIds=bestLineup(state.pool,state.squadIds);syncCompetitionProgress(state,seed);}}else if(!state.offers.length&&(state.lastOfferRound===undefined||round-state.lastOfferRound>=4)){state.offers=initialOffers(managerReputation,round,seed);state.lastOfferRound=round;}return state;}
export function nationalVacancies(state:NationalCareerState,managerReputation:number){const offered=new Set(state.offers.map(o=>o.teamId));return NATIONAL_TEAMS_2026.filter(t=>offered.has(t.id)||t.reputation<=managerReputation+12).sort((a,b)=>b.reputation-a.reputation).slice(0,16);}
export function applyForNationalTeam(state:NationalCareerState,teamId:string,league:LeagueWorld,seed:string,year:number,round:number,managerReputation:number,currentDate?:string):NationalActionResult{const team=byId(teamId);if(!team)return{career:state,message:"Seleção não encontrada."};if(state.status==="Empregado"&&state.teamId===team.id)return{career:state,message:`Você já comanda ${team.name}.`};const gap=team.reputation-managerReputation;if(gap>24)return{career:state,message:`A federação de ${team.name} considera seu currículo ainda insuficiente para o projeto atual.`};const rng=new SeededRng(`${seed}:national-application:${team.id}:${year}:r${round}`),offerBonus=state.offers.some(o=>o.teamId===team.id)?28:0,chance=Math.max(10,Math.min(94,58-gap*1.8+offerBonus));if(rng.integer(1,100)>chance)return{career:{...state,offers:state.offers.filter(o=>o.teamId!==team.id)},message:`${team.name} agradeceu o interesse, mas escolheu outro perfil neste momento.`};const pool=buildPool(team,league,seed),squad=pool.slice(0,26).map(p=>p.id),career:NationalCareerState={...state,status:"Empregado",teamId:team.id,teamName:team.name,pool,squadIds:squad,lineupIds:bestLineup(pool,squad),fixtures:buildFixtures(team,year,seed).filter(f=>!currentDate||f.date>=currentDate),offers:[],calendarNotes:[],selectedFormation:"4-2-3-1",competitionStatus:[]};syncCompetitionProgress(career,seed);return{career,message:`Você foi anunciado como treinador de ${team.name}. Convocação, amistosos e competições oficiais já estão no calendário.`};}
export function resignNationalTeam(state:NationalCareerState):NationalActionResult{return{career:{...state,status:"Sem seleção",teamId:undefined,teamName:undefined,pool:[],squadIds:[],lineupIds:[],fixtures:[],calendarNotes:[],competitionStatus:[]},message:"Você deixou o comando da seleção e continua normalmente a carreira de clubes."};}
export function toggleNationalCallUp(state:NationalCareerState,playerId:string):NationalActionResult{if(state.status!=="Empregado")return{career:state,message:"Você não comanda uma seleção."};if(!state.pool.some(p=>p.id===playerId))return{career:state,message:"Jogador não elegível."};const selected=state.squadIds.includes(playerId);if(!selected&&state.squadIds.length>=26)return{career:state,message:"A convocação já tem 26 jogadores. Corte alguém antes de incluir outro atleta."};const squadIds=selected?state.squadIds.filter(id=>id!==playerId):[...state.squadIds,playerId],lineupIds=state.lineupIds.filter(id=>squadIds.includes(id));return{career:{...state,squadIds,lineupIds:lineupIds.length===11?lineupIds:bestLineup(state.pool,squadIds)},message:selected?"Jogador retirado da convocação.":"Jogador convocado."};}
export function toggleNationalLineup(state:NationalCareerState,playerId:string):NationalActionResult{if(!state.squadIds.includes(playerId))return{career:state,message:"O atleta precisa estar convocado antes de entrar no XI."};const current=state.lineupIds.includes(playerId);if(!current&&state.lineupIds.length>=11)return{career:state,message:"O XI já tem 11 jogadores. Retire um titular antes da troca."};const lineupIds=current?state.lineupIds.filter(id=>id!==playerId):[...state.lineupIds,playerId];return{career:{...state,lineupIds},message:current?"Jogador retirado do XI inicial.":"Jogador incluído no XI inicial."};}
export function nationalSelectionIssues(state:NationalCareerState){const selected=state.pool.filter(p=>state.squadIds.includes(p.id)),issues:string[]=[];if(selected.length<18)issues.push(`Convocação incompleta: ${selected.length}/18 mínimo.`);if(selected.filter(p=>p.position==="GOL").length<2)issues.push("Recomendado convocar ao menos 2 goleiros.");if(state.lineupIds.length!==11)issues.push(`XI inicial incompleto: ${state.lineupIds.length}/11.`);if(!state.pool.some(p=>state.lineupIds.includes(p.id)&&p.position==="GOL"))issues.push("O XI precisa ter um goleiro.");return issues;}
function resultCode(gf:number,ga:number):"V"|"E"|"D"{return gf>ga?"V":gf<ga?"D":"E";}
function goals(rng:SeededRng,lambda:number){let v=0;for(let i=0;i<6;i++)if(rng.next()<Math.max(.04,Math.min(.5,lambda/6)))v++;return v;}
export function playNationalFixture(state:NationalCareerState,date:string,seed:string):NationalActionResult{if(state.status!=="Empregado"||!state.teamId)return{career:state,message:"Você não comanda uma seleção."};const career=structuredClone(state),match=career.fixtures.filter(f=>!f.played&&f.date<=date).sort((a,b)=>a.date.localeCompare(b.date))[0];if(!match)return{career:state,message:"Não há partida da sua seleção disponível hoje."};const issues=nationalSelectionIssues(career),blocking=issues.filter(i=>i.includes("incompleta")||i.includes("XI")||i.includes("precisa ter"));if(blocking.length)return{career:state,message:blocking[0]};const team=byId(state.teamId)!,xi=career.lineupIds.map(id=>career.pool.find(p=>p.id===id)).filter((p):p is NationalPoolPlayer=>Boolean(p));if(xi.length!==11)return{career:state,message:"Defina os 11 titulares antes da partida."};const our=Math.round(xi.reduce((s,p)=>s+p.overall,0)/11),oppName=match.homeTeamId===team.id?match.awayName:match.homeName,opp=byName(oppName),oppStrength=opp?.reputation??72,rng=new SeededRng(`${seed}:national-match:${match.id}`),homeUser=match.homeTeamId===team.id,delta=our-oppStrength+(homeUser?2:0);const hg=goals(rng,homeUser?1.4+delta*.035:1.15-delta*.03),ag=goals(rng,homeUser?1.1-delta*.03:1.35+delta*.035);const knockout=match.competition!=="Amistoso"&&!match.stage.includes("Grupo")&&!match.stage.includes("Fase de grupos"),leg2=match.leg===2;if(knockout&&!match.tieId&&hg===ag){const userWins=rng.next()<Math.max(.25,Math.min(.75,.5+delta*.015));match.winnerTeamId=userWins?team.id:(opp?.id??oppName);match.decidedByPenalties=true;}match.played=true;match.homeGoals=hg;match.awayGoals=ag;match.shotsHome=Math.max(4,rng.integer(7,17)+Math.round((homeUser?delta:-delta)/5));match.shotsAway=Math.max(4,rng.integer(7,17)-Math.round((homeUser?delta:-delta)/5));match.possessionHome=Math.max(36,Math.min(64,50+Math.round((homeUser?delta:-delta)/2)));if(leg2&&match.tieId){const tie=career.fixtures.filter(f=>f.tieId===match.tieId&&f.played);let userAgg=0,oppAgg=0;for(const f of tie){const r=matchResultForTeam(career,f);userAgg+=r.gf;oppAgg+=r.ga;}if(userAgg===oppAgg){const userWins=rng.next()<Math.max(.25,Math.min(.75,.5+delta*.015));match.winnerTeamId=userWins?team.id:(opp?.id??oppName);match.decidedByPenalties=true;}else match.winnerTeamId=userAgg>oppAgg?team.id:(opp?.id??oppName);}
 const gf=homeUser?hg:ag,ga=homeUser?ag:hg;career.sequence++;career.history.unshift({id:`nat-history-${career.sequence}`,date:match.date,competition:match.competition,stage:match.stage,opponent:oppName,score:`${gf}–${ga}${match.decidedByPenalties?" (p)":""}`,result:match.winnerTeamId?match.winnerTeamId===team.id?"V":"D":resultCode(gf,ga)});syncCompetitionProgress(career,seed);const bench=career.pool.filter(p=>career.squadIds.includes(p.id)&&!career.lineupIds.includes(p.id)).sort((a,b)=>b.overall-a.overall).slice(0,3),used=[...xi,...bench].map(p=>p.sourcePlayerId).filter((id):id is string=>Boolean(id));return{career,message:`${team.name} ${gf} × ${ga} ${oppName}${match.decidedByPenalties?" • decisão nos pênaltis":""}. Resultado registrado no calendário internacional.`,playedFixture:match,usedSourcePlayerIds:used};}
export function todayNationalFixture(state:NationalCareerState|undefined,date:string){return state?.status==="Empregado"?state.fixtures.filter(f=>!f.played&&f.date<=date).sort((a,b)=>a.date.localeCompare(b.date))[0]:undefined;}
export function nextNationalFixture(state:NationalCareerState|undefined,date:string){if(state?.status!=="Empregado")return undefined;return state.fixtures.filter(f=>!f.played).sort((a,b)=>a.date.localeCompare(b.date))[0]??state.fixtures.filter(f=>!f.played&&f.date>=date).sort((a,b)=>a.date.localeCompare(b.date))[0];}
