import { NATIONAL_TEAMS_2026, NATIONS_LEAGUE_2026_27_GROUPS, WORLD_CUP_2026_GROUPS, type NationalTeam } from "../data/national-teams-2026";
import { SeededRng } from "./rng";
import type { LeagueWorld } from "./league";

export type NationalCareerStatus="Sem seleção"|"Empregado";
export type NationalPoolPlayer={id:string;sourcePlayerId?:string;name:string;position:string;age:number;overall:number;clubName:string;nationality:string;virtual:boolean};
export type NationalFixture={id:string;date:string;competition:"Copa do Mundo"|"Nations League"|"Amistoso";stage:string;homeTeamId:string;awayTeamId:string;homeName:string;awayName:string;played:boolean;homeGoals?:number;awayGoals?:number;shotsHome?:number;shotsAway?:number;possessionHome?:number};
export type NationalJobOffer={id:string;teamId:string;teamName:string;reputation:number;expiresRound:number};
export type NationalHistory={id:string;date:string;competition:string;stage:string;opponent:string;score:string;result:"V"|"E"|"D"};
export type NationalCareerState={status:NationalCareerStatus;teamId?:string;teamName?:string;sequence:number;offers:NationalJobOffer[];pool:NationalPoolPlayer[];squadIds:string[];lineupIds:string[];fixtures:NationalFixture[];history:NationalHistory[];calendarNotes:string[];lastOfferRound?:number};
export type NationalActionResult={career:NationalCareerState;message:string;playedFixture?:NationalFixture;usedSourcePlayerIds?:string[]};

const byName=(name:string)=>NATIONAL_TEAMS_2026.find(t=>t.name===name);
const byId=(id:string)=>NATIONAL_TEAMS_2026.find(t=>t.id===id);
function opponentsForNations(name:string){for(const leagues of Object.values(NATIONS_LEAGUE_2026_27_GROUPS))for(const teams of Object.values(leagues))if((teams as readonly string[]).includes(name))return [...teams].filter(t=>t!==name);return[];}
function wcGroup(name:string){for(const [group,teams] of Object.entries(WORLD_CUP_2026_GROUPS))if(teams.includes(name))return{group,teams};return undefined;}
function fixture(id:string,date:string,competition:NationalFixture["competition"],stage:string,home:string,away:string):NationalFixture{const h=byName(home),a=byName(away);return{id,date,competition,stage,homeTeamId:h?.id??home,awayTeamId:a?.id??away,homeName:home,awayName:away,played:false};}
function buildFixtures(team:NationalTeam,year:number,seed:string){const out:NationalFixture[]=[];const wc=wcGroup(team.name);if(year===2026&&wc){const dates=["2026-06-12","2026-06-18","2026-06-24"];wc.teams.filter(n=>n!==team.name).forEach((opp,i)=>out.push(fixture(`nat-wc-${team.id}-${i+1}`,dates[i],"Copa do Mundo",`Grupo ${wc.group} • rodada ${i+1}`,i%2===0?team.name:opp,i%2===0?opp:team.name)));}const nations=opponentsForNations(team.name);if(nations.length){const dates=[`${year}-09-24`,`${year}-09-28`,`${year}-10-02`,`${year}-10-06`,`${year}-11-13`,`${year}-11-17`];[...nations,...nations].forEach((opp,i)=>out.push(fixture(`nat-unl-${team.id}-${i+1}`,dates[i],"Nations League",`Fase de grupos • rodada ${i+1}`,i<3?team.name:opp,i<3?opp:team.name)));}if(!out.length){const rng=new SeededRng(`${seed}:national-friendlies:${team.id}:${year}`),others=NATIONAL_TEAMS_2026.filter(t=>t.id!==team.id);[`${year}-03-28`,`${year}-06-05`,`${year}-09-26`,`${year}-11-14`].forEach((date,i)=>{const opp=rng.pick(others);out.push(fixture(`nat-friendly-${team.id}-${i+1}`,date,"Amistoso","Data FIFA",i%2===0?team.name:opp.name,i%2===0?opp.name:team.name));});}return out.sort((a,b)=>a.date.localeCompare(b.date));}
function virtualPool(team:NationalTeam,seed:string){const rng=new SeededRng(`${seed}:virtual-national:${team.id}`),positions=["GOL","GOL","ZAG","ZAG","ZAG","LD","LE","VOL","VOL","MC","MC","MEI","PD","PE","ATA","ATA"];return Array.from({length:28},(_,i):NationalPoolPlayer=>({id:`nat-virtual-${team.id}-${i+1}`,name:`${team.shortName} ${i+1}`,position:positions[i%positions.length],age:rng.integer(19,32),overall:Math.max(58,Math.min(93,team.reputation+rng.integer(-13,3))),clubName:"Exterior",nationality:team.name,virtual:true}));}
function buildPool(team:NationalTeam,league:LeagueWorld,seed:string){const real=league.clubs.flatMap(club=>club.players.filter(p=>p.nationality===team.name).map((p):NationalPoolPlayer=>({id:`nat-${p.id}`,sourcePlayerId:p.id,name:p.name,position:p.position,age:p.age,overall:p.overall,clubName:club.name,nationality:team.name,virtual:false})));return[...real,...virtualPool(team,seed)].sort((a,b)=>b.overall-a.overall).slice(0,60);}
function initialOffers(managerReputation:number,round:number,seed:string){const rng=new SeededRng(`${seed}:national-offers:${round}`),eligible=NATIONAL_TEAMS_2026.filter(t=>t.reputation<=managerReputation+18).sort((a,b)=>b.reputation-a.reputation).slice(0,36),picked:NationalTeam[]=[];while(eligible.length&&picked.length<4){picked.push(eligible.splice(rng.integer(0,eligible.length-1),1)[0]);}return picked.map((t,i)=>({id:`nat-offer-${round}-${i}-${t.id}`,teamId:t.id,teamName:t.name,reputation:t.reputation,expiresRound:round+4}));}
export function createNationalCareer(league:LeagueWorld,seed:string,year:number,managerReputation=55,round=1):NationalCareerState{return{status:"Sem seleção",sequence:0,offers:initialOffers(managerReputation,round,seed),pool:[],squadIds:[],lineupIds:[],fixtures:[],history:[],calendarNotes:[],lastOfferRound:round};}
export function hydrateNationalCareer(value:NationalCareerState|undefined,league:LeagueWorld,seed:string,year:number,managerReputation=55,round=1){let state=value?structuredClone(value):createNationalCareer(league,seed,year,managerReputation,round);state.offers=(state.offers??[]).filter(o=>o.expiresRound>=round);state.history=state.history??[];state.calendarNotes=state.calendarNotes??[];if(state.status==="Empregado"&&state.teamId){const team=byId(state.teamId);if(team){state.teamName=team.name;state.pool=buildPool(team,league,seed);state.fixtures=state.fixtures?.length?state.fixtures:buildFixtures(team,year,seed);state.squadIds=(state.squadIds??[]).filter(id=>state.pool.some(p=>p.id===id));if(state.squadIds.length<18)state.squadIds=state.pool.slice(0,26).map(p=>p.id);state.lineupIds=(state.lineupIds??[]).filter(id=>state.squadIds.includes(id));if(state.lineupIds.length<11)state.lineupIds=state.squadIds.slice(0,11);}}else if(!state.offers.length&&(state.lastOfferRound===undefined||round-state.lastOfferRound>=4)){state.offers=initialOffers(managerReputation,round,seed);state.lastOfferRound=round;}return state;}
export function nationalVacancies(state:NationalCareerState,managerReputation:number){const offered=new Set(state.offers.map(o=>o.teamId));return NATIONAL_TEAMS_2026.filter(t=>offered.has(t.id)||t.reputation<=managerReputation+12).sort((a,b)=>b.reputation-a.reputation).slice(0,16);}
export function applyForNationalTeam(state:NationalCareerState,teamId:string,league:LeagueWorld,seed:string,year:number,round:number,managerReputation:number):NationalActionResult{const team=byId(teamId);if(!team)return{career:state,message:"Seleção não encontrada."};if(state.status==="Empregado"&&state.teamId===team.id)return{career:state,message:`Você já comanda ${team.name}.`};const gap=team.reputation-managerReputation;if(gap>24)return{career:state,message:`A federação de ${team.name} considera seu currículo ainda insuficiente para o projeto atual.`};const rng=new SeededRng(`${seed}:national-application:${team.id}:${year}:r${round}`),offerBonus=state.offers.some(o=>o.teamId===team.id)?28:0,chance=Math.max(10,Math.min(94,58-gap*1.8+offerBonus));if(rng.integer(1,100)>chance)return{career:{...state,offers:state.offers.filter(o=>o.teamId!==team.id)},message:`${team.name} agradeceu o interesse, mas escolheu outro perfil neste momento.`};const pool=buildPool(team,league,seed),squad=pool.slice(0,26).map(p=>p.id),career:NationalCareerState={...state,status:"Empregado",teamId:team.id,teamName:team.name,pool,squadIds:squad,lineupIds:squad.slice(0,11),fixtures:buildFixtures(team,year,seed),offers:[],calendarNotes:[]};return{career,message:`Você foi anunciado como treinador de ${team.name}. A convocação e o calendário internacional já estão disponíveis.`};}
export function resignNationalTeam(state:NationalCareerState):NationalActionResult{return{career:{...state,status:"Sem seleção",teamId:undefined,teamName:undefined,pool:[],squadIds:[],lineupIds:[],fixtures:[],calendarNotes:[]},message:"Você deixou o comando da seleção e continua normalmente a carreira de clubes."};}
export function toggleNationalCallUp(state:NationalCareerState,playerId:string):NationalActionResult{if(state.status!=="Empregado")return{career:state,message:"Você não comanda uma seleção."};if(!state.pool.some(p=>p.id===playerId))return{career:state,message:"Jogador não elegível."};const selected=state.squadIds.includes(playerId);if(!selected&&state.squadIds.length>=26)return{career:state,message:"A convocação já tem 26 jogadores. Corte alguém antes de incluir outro atleta."};const squadIds=selected?state.squadIds.filter(id=>id!==playerId):[...state.squadIds,playerId],lineupIds=state.lineupIds.filter(id=>squadIds.includes(id));while(lineupIds.length<Math.min(11,squadIds.length)){const next=squadIds.find(id=>!lineupIds.includes(id));if(!next)break;lineupIds.push(next);}return{career:{...state,squadIds,lineupIds},message:selected?"Jogador retirado da convocação.":"Jogador convocado."};}
function resultCode(gf:number,ga:number):"V"|"E"|"D"{return gf>ga?"V":gf<ga?"D":"E";}
export function playNationalFixture(state:NationalCareerState,date:string,seed:string):NationalActionResult{if(state.status!=="Empregado"||!state.teamId)return{career:state,message:"Você não comanda uma seleção."};const career=structuredClone(state),match=career.fixtures.find(f=>!f.played&&f.date===date);if(!match)return{career:state,message:"Não há partida da sua seleção hoje."};if(career.squadIds.length<18)return{career:state,message:"A convocação precisa ter ao menos 18 jogadores."};const team=byId(career.teamId)!,selected=career.pool.filter(p=>career.squadIds.includes(p.id)).sort((a,b)=>b.overall-a.overall),our=Math.round(selected.slice(0,11).reduce((s,p)=>s+p.overall,0)/Math.max(1,Math.min(11,selected.length))),oppName=match.homeTeamId===team.id?match.awayName:match.homeName,opp=byName(oppName),oppStrength=opp?.reputation??72,rng=new SeededRng(`${seed}:national-match:${match.id}`),homeUser=match.homeTeamId===team.id,delta=(our-oppStrength)*(homeUser?1:-1);let hg=Math.max(0,rng.integer(0,2)+(delta>5?1:0)+(homeUser?1:0)),ag=Math.max(0,rng.integer(0,2)+(delta<-5?1:0));if(match.competition!=="Amistoso"&&!match.stage.startsWith("Grupo")&&!match.stage.includes("Fase de grupos")&&hg===ag)homeUser?hg++:ag++;match.played=true;match.homeGoals=hg;match.awayGoals=ag;match.shotsHome=Math.max(4,rng.integer(7,17)+Math.round(delta/5));match.shotsAway=Math.max(4,rng.integer(7,17)-Math.round(delta/5));match.possessionHome=Math.max(36,Math.min(64,50+Math.round(delta/2)));const gf=homeUser?hg:ag,ga=homeUser?ag:hg;career.sequence++;career.history.unshift({id:`nat-history-${career.sequence}`,date:match.date,competition:match.competition,stage:match.stage,opponent:oppName,score:`${gf}–${ga}`,result:resultCode(gf,ga)});const used=selected.slice(0,14).map(p=>p.sourcePlayerId).filter((id):id is string=>Boolean(id));return{career,message:`${team.name} ${gf} × ${ga} ${oppName}. Resultado registrado no calendário internacional.`,playedFixture:match,usedSourcePlayerIds:used};}
export function todayNationalFixture(state:NationalCareerState|undefined,date:string){return state?.status==="Empregado"?state.fixtures.find(f=>!f.played&&f.date===date):undefined;}
export function nextNationalFixture(state:NationalCareerState|undefined,date:string){return state?.status==="Empregado"?state.fixtures.filter(f=>!f.played&&f.date>=date).sort((a,b)=>a.date.localeCompare(b.date))[0]:undefined;}
