import {describe,expect,it} from "vitest";
import {createLeague} from "./league";
import {createNationalCareer,hydrateNationalCareer,nationalSelectionIssues,playNationalFixture,toggleNationalLineup,type NationalCareerState} from "./national-team";

describe("national team functional calendar",()=>{
 it("keeps friendlies alongside official World Cup matches",()=>{const league=createLeague("nat-test",2026,"BRA1"),base=createNationalCareer(league,"nat-test",2026,100,1),career:NationalCareerState={...base,status:"Empregado",teamId:"brasil",teamName:"Brasil",pool:[],squadIds:[],lineupIds:[],fixtures:[]};const h=hydrateNationalCareer(career,league,"nat-test",2026,100,1,"2026-01-10");expect(h.fixtures.filter(f=>f.competition==="Copa do Mundo").length).toBe(3);expect(h.fixtures.some(f=>f.competition==="Amistoso")).toBe(true);expect(h.lineupIds).toHaveLength(11)});
 it("uses and validates an explicit national XI",()=>{const league=createLeague("nat-xi",2026,"BRA1"),career=hydrateNationalCareer({...createNationalCareer(league,"nat-xi",2026,100,1),status:"Empregado",teamId:"brasil",teamName:"Brasil"},league,"nat-xi",2026,100,1,"2026-01-10");const first=career.lineupIds[0],changed=toggleNationalLineup(career,first).career;expect(changed.lineupIds).toHaveLength(10);expect(nationalSelectionIssues(changed).some(i=>i.includes("XI"))).toBe(true);});
 it("advances a qualifying World Cup campaign into knockout",()=>{const league=createLeague("nat-ko",2026,"BRA1"),career=hydrateNationalCareer({...createNationalCareer(league,"nat-ko",2026,100,1),status:"Empregado",teamId:"brasil",teamName:"Brasil"},league,"nat-ko",2026,100,1,"2026-01-10");const group=career.fixtures.filter(f=>f.competition==="Copa do Mundo");for(const f of group){f.played=true;const home=f.homeTeamId===career.teamId;f.homeGoals=home?2:0;f.awayGoals=home?0:2;}const synced=hydrateNationalCareer(career,league,"nat-ko",2026,100,1,"2026-06-25");expect(synced.fixtures.some(f=>f.stage==="32 avos")).toBe(true);expect(synced.competitionStatus?.find(s=>s.competition==="Copa do Mundo")?.status).toBe("Classificado");});
 it("can play an overdue official fixture instead of deadlocking the save",()=>{const league=createLeague("nat-due",2026,"BRA1"),career=hydrateNationalCareer({...createNationalCareer(league,"nat-due",2026,100,1),status:"Empregado",teamId:"brasil",teamName:"Brasil"},league,"nat-due",2026,100,1,"2026-01-10"),first=career.fixtures.find(f=>f.competition==="Amistoso")!;const result=playNationalFixture(career,"2026-04-01","nat-due");expect(result.playedFixture?.id).toBe(first.id);expect(result.career.history.length).toBe(1);});
});
