import type { SeasonState } from "./season";
import type { SaveSlotMeta } from "./save-slots";

const DB="vestiario90-offline-v2",STORE="saves",VERSION=1,INDEX_KEY="vestiario90:saves:v1",ACTIVE_KEY="vestiario90:active-save:v1",PREFIX="vestiario90:save:v1:";
type OfflineSnapshot={id:string;meta:SaveSlotMeta;state:SeasonState;writtenAt:string};
function openDb(){return new Promise<IDBDatabase>((resolve,reject)=>{if(typeof indexedDB==="undefined")return reject(new Error("IndexedDB indisponível"));const req=indexedDB.open(DB,VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:"id"});};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
export async function mirrorOfflineSave(id:string,state:SeasonState,meta:SaveSlotMeta){try{const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put({id,meta,state,writtenAt:new Date().toISOString()} satisfies OfflineSnapshot);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});db.close();}catch{}}
export async function removeOfflineSave(id:string){try{const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});db.close();}catch{}}
export async function recoverOfflineSaves(){if(typeof window==="undefined")return 0;try{const db=await openDb(),items=await new Promise<OfflineSnapshot[]>((resolve,reject)=>{const tx=db.transaction(STORE,"readonly"),req=tx.objectStore(STORE).getAll();req.onsuccess=()=>resolve(req.result as OfflineSnapshot[]);req.onerror=()=>reject(req.error);}),localRaw=window.localStorage.getItem(INDEX_KEY),local:SaveSlotMeta[]=localRaw?JSON.parse(localRaw):[],byId=new Map(local.map(x=>[x.id,x]));let restored=0;for(const item of items){const current=byId.get(item.id);if(!current||item.meta.updatedAt>current.updatedAt){window.localStorage.setItem(`${PREFIX}${item.id}`,JSON.stringify(item.state));byId.set(item.id,item.meta);restored++;}}const merged=[...byId.values()].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));if(merged.length){window.localStorage.setItem(INDEX_KEY,JSON.stringify(merged));const active=window.localStorage.getItem(ACTIVE_KEY);if(!active||!byId.has(active))window.localStorage.setItem(ACTIVE_KEY,merged[0].id);}db.close();return restored;}catch{return 0;}}
export async function requestPersistentStorage(){try{return Boolean(await navigator.storage?.persist?.());}catch{return false;}}
