import type { SeasonState } from "./season";
import type { SaveSlotMeta } from "./save-slots";

const DB="vestiario90-offline-v2",STORE="saves",BACKUP_STORE="backups",VERSION=2,INDEX_KEY="vestiario90:saves:v1",ACTIVE_KEY="vestiario90:active-save:v1",PREFIX="vestiario90:save:v1:";
export const OFFLINE_SAVE_VERSION=2;
export type OfflineSnapshot={id:string;meta:SaveSlotMeta;state:SeasonState;writtenAt:string;checksum:string;sizeBytes:number;version:number};
type BackupBundle={id:string;snapshots:OfflineSnapshot[]};
export type OfflineWriteResult={ok:boolean;checksum?:string;sizeBytes?:number;backupCount:number;writtenAt?:string;error?:string};

export function checksumText(raw:string){let h1=2166136261,h2=2246822519;for(let i=0;i<raw.length;i++){const c=raw.charCodeAt(i);h1^=c;h1=Math.imul(h1,16777619);h2^=c;h2=Math.imul(h2,3266489917)}return`${(h1>>>0).toString(16).padStart(8,"0")}${(h2>>>0).toString(16).padStart(8,"0")}:${raw.length}`;}
export function compareSaveFreshness(aMeta:SaveSlotMeta,aState:SeasonState,bMeta:SaveSlotMeta,bState:SeasonState){const timestamp=aMeta.updatedAt.localeCompare(bMeta.updatedAt);if(timestamp!==0)return timestamp;const date=(aState.currentDate??aMeta.currentDate).localeCompare(bState.currentDate??bMeta.currentDate);if(date!==0)return date;const round=(aState.currentRound??aMeta.currentRound)-(bState.currentRound??bMeta.currentRound);if(round!==0)return round;return(aState.year??aMeta.year)-(bState.year??bMeta.year);}
function snapshotFor(id:string,state:SeasonState,meta:SaveSlotMeta):OfflineSnapshot{const raw=JSON.stringify(state);return{id,meta:{...meta,saveVersion:OFFLINE_SAVE_VERSION,checksum:checksumText(raw),sizeBytes:new Blob([raw]).size,storage:"indexeddb"},state,writtenAt:new Date().toISOString(),checksum:checksumText(raw),sizeBytes:new Blob([raw]).size,version:OFFLINE_SAVE_VERSION};}
function validSnapshot(item:OfflineSnapshot|undefined|null){if(!item?.state||!item.checksum)return false;try{return checksumText(JSON.stringify(item.state))===item.checksum}catch{return false}}
export function freshestValidSnapshot(items:(OfflineSnapshot|undefined|null)[]){const valid=items.filter((item):item is OfflineSnapshot=>Boolean(item&&validSnapshot(item)));return valid.sort((a,b)=>compareSaveFreshness(b.meta,b.state,a.meta,a.state))[0];}
function openDb(){return new Promise<IDBDatabase>((resolve,reject)=>{if(typeof indexedDB==="undefined")return reject(new Error("IndexedDB indisponível"));const req=indexedDB.open(DB,VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:"id"});if(!db.objectStoreNames.contains(BACKUP_STORE))db.createObjectStore(BACKUP_STORE,{keyPath:"id"});};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error??new Error("Falha ao abrir IndexedDB"));});}
async function readBundle(db:IDBDatabase,id:string){return new Promise<BackupBundle|undefined>((resolve,reject)=>{const tx=db.transaction(BACKUP_STORE,"readonly"),req=tx.objectStore(BACKUP_STORE).get(id);req.onsuccess=()=>resolve(req.result as BackupBundle|undefined);req.onerror=()=>reject(req.error);});}
async function readPrimary(db:IDBDatabase,id:string){return new Promise<OfflineSnapshot|undefined>((resolve,reject)=>{const tx=db.transaction(STORE,"readonly"),req=tx.objectStore(STORE).get(id);req.onsuccess=()=>resolve(req.result as OfflineSnapshot|undefined);req.onerror=()=>reject(req.error);});}
function parseLocalState(raw:string|null){if(!raw)return undefined;try{return JSON.parse(raw)as SeasonState}catch{return undefined}}
async function promotePrimary(db:IDBDatabase,snapshot:OfflineSnapshot){await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(snapshot);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}

export async function persistOfflineSave(id:string,state:SeasonState,meta:SaveSlotMeta):Promise<OfflineWriteResult>{let db:IDBDatabase|undefined;try{db=await openDb();const snapshot=snapshotFor(id,state,meta),previous=await readPrimary(db,id),bundle=await readBundle(db,id),history=[...(bundle?.snapshots??[])];if(previous&&validSnapshot(previous)&&previous.checksum!==snapshot.checksum)history.unshift(previous);const unique=history.filter((item,index,all)=>validSnapshot(item)&&all.findIndex(other=>other.checksum===item.checksum)===index).sort((a,b)=>compareSaveFreshness(b.meta,b.state,a.meta,a.state)).slice(0,3);await new Promise<void>((resolve,reject)=>{const tx=db!.transaction([STORE,BACKUP_STORE],"readwrite");tx.objectStore(STORE).put(snapshot);tx.objectStore(BACKUP_STORE).put({id,snapshots:unique} satisfies BackupBundle);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error??new Error("Falha na transação de save"));tx.onabort=()=>reject(tx.error??new Error("Save abortado"));});const verified=await readPrimary(db,id);if(!validSnapshot(verified)||verified?.checksum!==snapshot.checksum)throw new Error("Verificação de integridade falhou");return{ok:true,checksum:snapshot.checksum,sizeBytes:snapshot.sizeBytes,backupCount:unique.length,writtenAt:snapshot.writtenAt};}catch(error){return{ok:false,backupCount:0,error:error instanceof Error?error.message:"Falha desconhecida ao salvar"};}finally{db?.close();}}

export async function mirrorOfflineSave(id:string,state:SeasonState,meta:SaveSlotMeta){return persistOfflineSave(id,state,meta);}
export async function loadOfflineSave(id:string):Promise<{snapshot:OfflineSnapshot;recoveredFromBackup:boolean}|undefined>{let db:IDBDatabase|undefined;try{db=await openDb();const primary=await readPrimary(db,id),bundle=await readBundle(db,id),freshest=freshestValidSnapshot([primary,...(bundle?.snapshots??[])]);if(!freshest)return;const recoveredFromBackup=!primary||primary.checksum!==freshest.checksum;if(recoveredFromBackup)await promotePrimary(db,freshest);return{snapshot:freshest,recoveredFromBackup};}catch{return;}finally{db?.close();}}
export async function restoreOfflineBackup(id:string):Promise<OfflineSnapshot|undefined>{let db:IDBDatabase|undefined;try{db=await openDb();const bundle=await readBundle(db,id),backup=freshestValidSnapshot(bundle?.snapshots??[]);if(!backup)return;await promotePrimary(db,backup);return backup;}catch{return;}finally{db?.close();}}
export async function offlineBackupCount(id:string){let db:IDBDatabase|undefined;try{db=await openDb();const bundle=await readBundle(db,id);return(bundle?.snapshots??[]).filter(validSnapshot).length;}catch{return 0;}finally{db?.close();}}
export async function removeOfflineSave(id:string){let db:IDBDatabase|undefined;try{db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db!.transaction([STORE,BACKUP_STORE],"readwrite");tx.objectStore(STORE).delete(id);tx.objectStore(BACKUP_STORE).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}catch{}finally{db?.close();}}
export async function recoverOfflineSaves(){if(typeof window==="undefined")return 0;let db:IDBDatabase|undefined;try{db=await openDb();const primaries=await new Promise<OfflineSnapshot[]>((resolve,reject)=>{const tx=db!.transaction(STORE,"readonly"),req=tx.objectStore(STORE).getAll();req.onsuccess=()=>resolve(req.result as OfflineSnapshot[]);req.onerror=()=>reject(req.error);}),localRaw=window.localStorage.getItem(INDEX_KEY),local:SaveSlotMeta[]=localRaw?JSON.parse(localRaw):[],byId=new Map(local.map(x=>[x.id,x]));let restored=0;for(const primary of primaries){const bundle=await readBundle(db,primary.id),item=freshestValidSnapshot([primary,...(bundle?.snapshots??[])]);if(!item)continue;if(primary.checksum!==item.checksum)await promotePrimary(db,item);const current=byId.get(item.id),localState=parseLocalState(window.localStorage.getItem(`${PREFIX}${item.id}`)),meta={...item.meta,saveVersion:OFFLINE_SAVE_VERSION,checksum:item.checksum,sizeBytes:item.sizeBytes,storage:"indexeddb" as const,backupCount:(bundle?.snapshots??[]).filter(validSnapshot).length,lastVerifiedAt:item.writtenAt};const localWins=Boolean(current&&localState&&compareSaveFreshness(current,localState,item.meta,item.state)>0);if(localWins)continue;byId.set(item.id,meta);restored++;try{window.localStorage.setItem(`${PREFIX}${item.id}`,JSON.stringify(item.state));}catch{/* Saves grandes permanecem íntegros no IndexedDB. */}}const merged=[...byId.values()].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));if(merged.length){try{window.localStorage.setItem(INDEX_KEY,JSON.stringify(merged));const active=window.localStorage.getItem(ACTIVE_KEY);if(!active||!byId.has(active))window.localStorage.setItem(ACTIVE_KEY,merged[0].id);}catch{/* O índice será reconstruído novamente pelo IndexedDB no próximo boot. */}}return restored;}catch{return 0;}finally{db?.close();}}
export async function requestPersistentStorage(){try{return Boolean(await navigator.storage?.persist?.());}catch{return false;}}
