import{SEASON_SAVE_KEY,type SeasonState}from"./season";
import{professionalCompetitionById,type ProfessionalCompetitionId}from"../data/brazil-2026/competitions";

export const SAVE_INDEX_KEY="vestiario90:saves:v1";
export const ACTIVE_SAVE_KEY="vestiario90:active-save:v1";
export const SAVE_PREFIX="vestiario90:save:v1:";
export type SaveSlotMeta={id:string;name:string;createdAt:string;updatedAt:string;competitionId:ProfessionalCompetitionId;competitionName:string;clubName:string;year:number;currentDate:string;currentRound:number};
export type SaveSlot={meta:SaveSlotMeta;state:SeasonState};
type StorageLike=Pick<Storage,"getItem"|"setItem"|"removeItem">;
function storage(explicit?:StorageLike):StorageLike|undefined{return explicit??(typeof window!=="undefined"?window.localStorage:undefined);}
function parseIndex(raw:string|null):SaveSlotMeta[]{try{const parsed=raw?JSON.parse(raw):[];return Array.isArray(parsed)?parsed:[];}catch{return[];}}
function safeId(){return`save-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;}
function competitionIdOf(state:SeasonState):ProfessionalCompetitionId{return(state.competitionId??state.league.competitionId??"BRA1")as ProfessionalCompetitionId;}
function currentDateOf(state:SeasonState){return state.currentDate??state.league.fixtures.find(f=>f.round===state.currentRound)?.date??`${state.year}-01-01`;}
export function defaultSaveName(state:SeasonState){const club=state.league.clubs.find(c=>c.id===state.selectedClubId),competition=professionalCompetitionById(competitionIdOf(state));return`${club?.name??"Carreira"} • ${competition.shortName}`;}
function metaFor(state:SeasonState,id:string,name:string,createdAt:string,updatedAt:string):SaveSlotMeta{const competitionId=competitionIdOf(state),competition=professionalCompetitionById(competitionId),club=state.league.clubs.find(c=>c.id===state.selectedClubId);return{id,name,createdAt,updatedAt,competitionId,competitionName:competition.name,clubName:state.career?.status==="Sem clube"?"Sem clube":club?.name??"Clube",year:state.year,currentDate:currentDateOf(state),currentRound:state.currentRound};}
export function listSaveSlots(explicit?:StorageLike){const s=storage(explicit);if(!s)return[];try{return parseIndex(s.getItem(SAVE_INDEX_KEY)).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));}catch{return[];}}
function writeIndex(s:StorageLike,index:SaveSlotMeta[]){s.setItem(SAVE_INDEX_KEY,JSON.stringify(index));}
function mirror(id:string,state:SeasonState,meta:SaveSlotMeta){if(typeof window!=="undefined")void import("./offline-save").then(m=>m.mirrorOfflineSave(id,state,meta));}
export function createSaveSlot(state:SeasonState,name?:string,explicit?:StorageLike):SaveSlotMeta|undefined{const s=storage(explicit);if(!s)return;const now=new Date().toISOString(),id=safeId(),meta=metaFor(state,id,name?.trim()||defaultSaveName(state),now,now);/* Mirror first: IndexedDB has a much larger quota than localStorage and is the durable offline copy. */mirror(id,state,meta);try{s.setItem(`${SAVE_PREFIX}${id}`,JSON.stringify(state));writeIndex(s,[meta,...listSaveSlots(s)]);s.setItem(ACTIVE_SAVE_KEY,id);}catch{/* IndexedDB mirror remains available for recovery even if localStorage quota is exhausted. */}return meta;}
export function saveToSlot(id:string,state:SeasonState,explicit?:StorageLike){const s=storage(explicit);if(!s)return;const index=listSaveSlots(s),existing=index.find(item=>item.id===id);if(!existing)return;const now=new Date().toISOString(),meta=metaFor(state,id,existing.name,existing.createdAt,now),payload=JSON.stringify(state);/* Never make the offline mirror depend on a successful localStorage write. Large careers can exceed the ~5MB localStorage quota. */mirror(id,state,meta);try{s.setItem(`${SAVE_PREFIX}${id}`,payload);writeIndex(s,[meta,...index.filter(item=>item.id!==id)]);s.setItem(ACTIVE_SAVE_KEY,id);const verify=s.getItem(`${SAVE_PREFIX}${id}`);if(!verify||verify.length!==payload.length)return meta;}catch{/* IndexedDB is the fallback source of truth; recoverOfflineSaves restores the slot on startup. */}return meta;}
export function renameSaveSlot(id:string,name:string,explicit?:StorageLike){const s=storage(explicit);if(!s||!name.trim())return;try{const index=listSaveSlots(s),target=index.find(item=>item.id===id);if(!target)return;target.name=name.trim();target.updatedAt=new Date().toISOString();writeIndex(s,index);return target;}catch{return;}}
export function loadSaveSlot(id:string,explicit?:StorageLike):SaveSlot|undefined{const s=storage(explicit);if(!s)return;try{const meta=listSaveSlots(s).find(item=>item.id===id),raw=s.getItem(`${SAVE_PREFIX}${id}`);if(!meta||!raw)return;const state=JSON.parse(raw)as SeasonState;s.setItem(ACTIVE_SAVE_KEY,id);return{meta,state};}catch{return;}}
export function deleteSaveSlot(id:string,explicit?:StorageLike){const s=storage(explicit);if(!s)return;try{const index=listSaveSlots(s).filter(item=>item.id!==id);writeIndex(s,index);s.removeItem(`${SAVE_PREFIX}${id}`);if(s.getItem(ACTIVE_SAVE_KEY)===id)s.removeItem(ACTIVE_SAVE_KEY);void import("./offline-save").then(m=>m.removeOfflineSave(id));}catch{return;}}
export function activeSaveId(explicit?:StorageLike){try{return storage(explicit)?.getItem(ACTIVE_SAVE_KEY)??undefined;}catch{return;}}
export function migrateLegacySeason(explicit?:StorageLike){const s=storage(explicit);if(!s||listSaveSlots(s).length)return;try{const raw=s.getItem(SEASON_SAVE_KEY);if(!raw)return;const state=JSON.parse(raw)as SeasonState;return createSaveSlot(state,`${defaultSaveName(state)} • save antigo`,s);}catch{return;}}
