import{describe,expect,it}from"vitest";
import{coordinateSeasonCalendars}from"./calendar-coordinator";
import{pickAiStartingXI}from"./club-ai";
import{internationalDutyPlayerIds}from"./international-duty";
import{createSeason}from"./season";
import{auditSeasonIntegrity,repairSeasonIntegrity}from"./season-integrity";
import{processWorldCompetitionsByDate}from"./world-competitions";

describe("season integrity",()=>{
 it("adds verified state championships to Brazilian saves and starts before the first user state match",()=>{const state=createSeason("state-calendar",2026),states=state.worldCompetitions.tournaments.filter(t=>t.definition.kind==="Estadual");expect(states.length).toBeGreaterThanOrEqual(10);const userMatches=states.flatMap(t=>t.matches).filter(m=>m.home.activeClubId===state.selectedClubId||m.away.activeClubId===state.selectedClubId).sort((a,b)=>a.date.localeCompare(b.date));expect(userMatches.length).toBeGreaterThan(0);expect(state.currentDate<userMatches[0].date).toBe(true)});
 it("processes cup fixtures by real calendar date instead of league round",()=>{const state=createSeason("cup-by-date",2026),pending=state.worldCompetitions.tournaments.flatMap(t=>t.matches).filter(m=>!m.played).sort((a,b)=>a.date.localeCompare(b.date)),target=pending[0];expect(target).toBeTruthy();const next=processWorldCompetitionsByDate(state.worldCompetitions,target.date,"cup-by-date");const played=next.tournaments.flatMap(t=>t.matches).find(m=>m.id===target.id);expect(played?.played).toBe(true)});
 it("keeps called-up players out of club selections during international windows",()=>{const state=createSeason("international-duty",2026);state.currentDate="2026-03-25";const duty=internationalDutyPlayerIds(state),club=state.league.clubs.map(c=>({club:c,count:c.players.filter(p=>duty.has(p.id)).length})).sort((a,b)=>b.count-a.count)[0];expect(duty.size).toBeGreaterThan(0);expect(club.count).toBeGreaterThan(0);const xi=pickAiStartingXI(club.club,state.clubAi,duty);expect(xi.every(player=>!duty.has(player.id))).toBe(true)});
 it("recovers an overdue user cup match instead of letting it disappear",()=>{const state=createSeason("legacy-cup-repair",2026),match=state.worldCompetitions.tournaments.flatMap(t=>t.matches).find(m=>m.home.activeClubId===state.selectedClubId||m.away.activeClubId===state.selectedClubId);expect(match).toBeTruthy();state.currentDate="2026-09-01";match!.date="2026-04-01";match!.played=false;match!.originalDate=undefined;const repaired=coordinateSeasonCalendars(state),fixed=repaired.worldCompetitions.tournaments.flatMap(t=>t.matches).find(m=>m.id===match!.id)!;expect(fixed.date>=state.currentDate).toBe(true);expect(fixed.originalDate).toBe("2026-04-01");expect(fixed.rescheduledReason).toContain("pendente recuperada")});
 it("accepts a freshly generated save in the structural auditor",()=>{const state=createSeason("integrity-fresh",2026),report=auditSeasonIntegrity(state);expect(report.errors).toBe(0);expect(report.ok).toBe(true)});
 it("detects structural corruption before it spreads to future seasons",()=>{const state=createSeason("integrity-detect",2026);state.league.fixtures[0].date="invalid-date";state.league.fixtures[1].id=state.league.fixtures[0].id;state.completed=true;const report=auditSeasonIntegrity(state);expect(report.ok).toBe(false);expect(report.issues.some(item=>item.code==="MISSING_LEAGUE_DATE")).toBe(true);expect(report.issues.some(item=>item.code==="DUPLICATE_LEAGUE_FIXTURE_ID")).toBe(true);expect(report.issues.some(item=>item.code==="PREMATURE_SEASON_CLOSURE")).toBe(true)});
 it("repairs safe save corruption without inventing sporting results",()=>{const state=createSeason("integrity-repair",2026),valid=state.lineupIds[0];state.lineupIds=[valid,valid,"player-that-does-not-exist"];state.benchIds=[valid,...state.benchIds,state.benchIds[0]];state.completed=true;state.seasonHistory=[{year:2025,closedAt:"2025-12-20",leagueChampion:"A",userLeaguePosition:1,honors:[]},{year:2025,closedAt:"2025-12-21",leagueChampion:"A",userLeaguePosition:1,honors:[]}];const firstHistory=state.worldCompetitions.history[0];if(firstHistory)state.worldCompetitions.history.push({...firstHistory});const repaired=repairSeasonIntegrity(state);expect(repaired.state.completed).toBe(false);expect(new Set(repaired.state.lineupIds).size).toBe(repaired.state.lineupIds.length);const club=repaired.state.league.clubs.find(item=>item.id===repaired.state.selectedClubId)!;expect(repaired.state.lineupIds.every(id=>club.players.some(player=>player.id===id))).toBe(true);expect(repaired.state.benchIds.some(id=>repaired.state.lineupIds.includes(id))).toBe(false);expect(repaired.state.seasonHistory).toHaveLength(1);expect(repaired.repairs.length).toBeGreaterThan(0)});
});
