import { SeededRng } from "./rng";
import { PROFESSIONAL_COMPETITIONS, type ProfessionalCompetitionId } from "../data/brazil-2026/competitions";
import { sortedStandings } from "./league";
import { sortedParallelStandings } from "./world-leagues";
import type { SeasonState } from "./season";
import type { WorldCompetitionId } from "./world-competitions";
export type EcosystemClub={name:string;shortName:string;country:string;competitionId:ProfessionalCompetitionId;reputation:number;points:number;position:number};
export type DomesticMovement={clubName:string;from:string;to:string;reason:string};
export type QualificationEntrant={name:string;shortName:string;country:string;reputation:number;reason:string};
export type LeagueArchive={competitionId:ProfessionalCompetitionId;competitionName:string;champion:string;runnerUp:string;topScorer?:string;topScorerGoals?:number};
export type SeasonArchive={year:number;leagues:LeagueArchive[];continental:Array<{competitionId:WorldCompetitionId;name:string;champion:string;runnerUp?:string}>;movements:DomesticMovement[];qualifiers:Array<{competitionId:WorldCompetitionId;clubs:string[]}>};
export type FootballEcosystemState={archives:SeasonArchive[];coefficients:Record<string,number>;nextDomesticParticipants:Partial<Record<ProfessionalCompetitionId,string[]>>;nextInternationalEntrants:Partial<Record<WorldCompetitionId,QualificationEntrant[]>>;lastFinalizedYear?:number};
export function createFootballEcosystem():FootballEcosystemState{return{archives:[],coefficients:{},nextDomesticParticipants:{},nextInternationalEntrants:{}};}
export function hydrateFootballEcosystem(value:FootballEcosystemState|undefined){return value?{...createFootballEcosystem(),...value,archives:value.archives??[],coefficients:value.coefficients??{},nextDomesticParticipants:value.nextDomesticParticipants??{},nextInternationalEntrants:value.nextInternationalEntrants??{}}:createFootballEcosystem();}
function table(state:SeasonState,id:ProfessionalCompetitionId):EcosystemClub[]{const def=PROFESSIONAL_COMPETITIONS.find(c=>c.id===id)!;if(id===state.competitionId){return sortedStandings(state.league).map((row,index)=>{const club=state.league.clubs.find(c=>c.id===row.clubId)!;return{name:club.name,shortName:club.shortName,country:def.country,competitionId:id,reputation:club.reputation,points:row.points,position:index+1};});}const league=state.worldLeagues.leagues[id];if(!league)return[];return sortedParallelStandings(league.standings).map((row,index)=>{const club=league.teams.find(c=>c.id===row.clubId)!;return{name:club.name,shortName:club.shortName,country:def.country,competitionId:id,reputation:Math.round(club.strength),points:row.points,position:index+1};});}
function completed(state:SeasonState,id:ProfessionalCompetitionId){if(id===state.competitionId)return state.league.fixtures.every(f=>f.played);return state.worldLeagues.leagues[id]?.fixtures.every(f=>f.played)??false;}
function playoff(a:EcosystemClub,b:EcosystemClub,seed:string){const rng=new SeededRng(seed),sa=a.points+a.reputation*.28+rng.integer(-5,5),sb=b.points+b.reputation*.28+rng.integer(-5,5);return sa>=sb?a:b;}
function promotions(state:SeasonState,id:ProfessionalCompetitionId){const rows=table(state,id);if(id==="BRA2")return[...rows.slice(0,2),playoff(rows[2],rows[5],`${state.baseSeed}:${state.year}:b2p1`),playoff(rows[3],rows[4],`${state.baseSeed}:${state.year}:b2p2`)].filter(Boolean);if(id==="BRA3"){const rng=new SeededRng(`${state.baseSeed}:${state.year}:c-second`);return rows.slice(0,8).map(x=>({x,score:x.points+x.reputation*.22+rng.integer(-7,7)})).sort((a,b)=>b.score-a.score).slice(0,4).map(x=>x.x);}if(id==="ENG2"||id==="ESP2"){const semi1=playoff(rows[2],rows[5],`${state.baseSeed}:${state.year}:${id}:s1`),semi2=playoff(rows[3],rows[4],`${state.baseSeed}:${state.year}:${id}:s2`);return[...rows.slice(0,2),playoff(semi1,semi2,`${state.baseSeed}:${state.year}:${id}:final`)].filter(Boolean);}if(id==="FRA2")return rows.slice(0,2);return[];}
const RESERVE:Partial<Record<ProfessionalCompetitionId,string[]>>={BRA3:["Santa Cruz","América-RN","ASA","Caxias","Maringá","Brasiliense"],ENG2:["Stockport County","Huddersfield Town","Reading","Barnsley","Blackpool","Plymouth Argyle"],ESP2:["Real Murcia","Nàstic Tarragona","Málaga B","Ponferradina","Lugo","Hércules"],FRA2:["Le Mans","Orléans","Valenciennes","Rouen","Caen","Versailles"]};
function unique(items:string[]){const seen=new Set<string>();return items.filter(x=>{const k=x.toLowerCase();if(seen.has(k))return false;seen.add(k);return true;});}
function transitionPair(state:SeasonState,top:ProfessionalCompetitionId,lower:ProfessionalCompetitionId,relegatedCount:number,lowerExternalDrop:number,movements:DomesticMovement[],next:Partial<Record<ProfessionalCompetitionId,string[]>>){const topRows=table(state,top),lowRows=table(state,lower);if(!topRows.length||!lowRows.length||!completed(state,top)||!completed(state,lower)){next[top]=topRows.map(x=>x.name);next[lower]=lowRows.map(x=>x.name);return;}const promoted=promotions(state,lower),relegated=topRows.slice(-relegatedCount),externalDrop=lowRows.slice(-lowerExternalDrop),reserve=(RESERVE[lower]??[]).filter(name=>!lowRows.some(x=>x.name===name)).slice(0,externalDrop.length);next[top]=unique(topRows.filter(x=>!relegated.includes(x)).map(x=>x.name).concat(promoted.map(x=>x.name))).slice(0,topRows.length);next[lower]=unique(lowRows.filter(x=>!promoted.includes(x)&&!externalDrop.includes(x)).map(x=>x.name).concat(relegated.map(x=>x.name),reserve)).slice(0,lowRows.length);for(const x of relegated)movements.push({clubName:x.name,from:top,to:lower,reason:"Rebaixamento"});for(const x of promoted)movements.push({clubName:x.name,from:lower,to:top,reason:"Acesso"});for(const name of reserve)movements.push({clubName:name,from:"DIVISÃO INFERIOR",to:lower,reason:"Acesso"});}
function tournamentChampion(state:SeasonState,id:WorldCompetitionId){const t=state.worldCompetitions.tournaments.find(x=>x.definition.id===id),p=t?.participants.find(x=>x.id===t.championId);return p;}
function fillEntrants(base:QualificationEntrant[],state:SeasonState,id:WorldCompetitionId,count:number){const tournament=state.worldCompetitions.tournaments.find(t=>t.definition.id===id),pool=(tournament?.participants??[]).sort((a,b)=>b.reputation-a.reputation).map(p=>({name:p.name,shortName:p.shortName,country:p.country,reputation:p.reputation,reason:"Coeficiente/rota continental"}));for(const p of pool)if(base.length<count&&!base.some(x=>x.name===p.name))base.push(p);let i=1;while(base.length<count){base.push({name:`Classificado ${id} ${i}`,shortName:`${id}${i}`,country:id==="LIB"||id==="SUD"?"CONMEBOL":"Europa",reputation:62,reason:"Qualificatória continental"});i++;}return base.slice(0,count);}
function associationPerformance(state:SeasonState){const score:Record<string,number>={};for(const id of ["UCL","UEL","UECL"] as WorldCompetitionId[]){const t=state.worldCompetitions.tournaments.find(x=>x.definition.id===id);for(const m of t?.matches.filter(x=>x.played)??[]){const hg=m.homeGoals??0,ag=m.awayGoals??0;score[m.home.country]=(score[m.home.country]??0)+(hg>ag?2:hg===ag?1:0);score[m.away.country]=(score[m.away.country]??0)+(ag>hg?2:hg===ag?1:0);}}return Object.entries(score).sort((a,b)=>b[1]-a[1]).slice(0,2).map(([country])=>country);}
function internationalPlan(state:SeasonState){const result:Partial<Record<WorldCompetitionId,QualificationEntrant[]>>={},bra=table(state,"BRA1"),eng=table(state,"ENG1"),esp=table(state,"ESP1"),fra=table(state,"FRA1"),toEntry=(x:EcosystemClub,reason:string):QualificationEntrant=>({name:x.name,shortName:x.shortName,country:x.country,reputation:x.reputation,reason});const lib:QualificationEntrant[]=[],sud:QualificationEntrant[]=[];const cdb=tournamentChampion(state,"CDB"),libChamp=tournamentChampion(state,"LIB"),sudChamp=tournamentChampion(state,"SUD");for(const p of [libChamp,sudChamp,cdb])if(p?.country==="Brasil"&&!lib.some(x=>x.name===p.name))lib.push({name:p.name,shortName:p.shortName,country:p.country,reputation:p.reputation,reason:p===cdb?"Campeão da Copa do Brasil":"Campeão continental"});for(const x of bra.slice(0,5))if(!lib.some(p=>p.name===x.name))lib.push(toEntry(x,x.position<=4?"Brasileirão • vaga direta":"Brasileirão • rota preliminar"));for(const x of bra.slice(5,12))if(!lib.some(p=>p.name===x.name)&&!sud.some(p=>p.name===x.name))sud.push(toEntry(x,"Brasileirão • Sul-Americana"));result.LIB=fillEntrants(lib,state,"LIB",32);result.SUD=fillEntrants(sud,state,"SUD",32);
  const perf=new Set(associationPerformance(state)),ucl:QualificationEntrant[]=[],uel:QualificationEntrant[]=[],uecl:QualificationEntrant[]=[];const add=(arr:QualificationEntrant[],x:EcosystemClub|undefined,reason:string)=>{if(x&&!arr.some(p=>p.name===x.name))arr.push(toEntry(x,reason));};const uclChamp=tournamentChampion(state,"UCL"),uelChamp=tournamentChampion(state,"UEL");for(const p of [uclChamp,uelChamp])if(p&&!ucl.some(x=>x.name===p.name))ucl.push({name:p.name,shortName:p.shortName,country:p.country,reputation:p.reputation,reason:p===uclChamp?"Campeão da Champions":"Campeão da Europa League"});for(const rows of [eng,esp]){rows.slice(0,4).forEach(x=>add(ucl,x,"Classificação nacional"));if(perf.has(rows[0]?.country))add(ucl,rows[4],"Vaga extra por desempenho UEFA");add(uel,rows[4],"Classificação nacional");add(uecl,rows[5],"Classificação nacional");}fra.slice(0,3).forEach(x=>add(ucl,x,"Classificação nacional"));add(ucl,fra[3],"Rota preliminar da Champions");add(uel,fra[4],"Classificação nacional");add(uecl,fra[5],"Classificação nacional");for(const [cupId,rows] of [["FAC",eng],["CDR",esp],["CDF",fra]] as const){const winner=tournamentChampion(state,cupId);if(winner&&!uel.some(x=>x.name===winner.name))uel.unshift({name:winner.name,shortName:winner.shortName,country:winner.country,reputation:winner.reputation,reason:"Campeão da copa nacional"});else add(uel,rows[5],"Vaga redistribuída pela liga");}result.UCL=fillEntrants(ucl,state,"UCL",36);result.UEL=fillEntrants(uel,state,"UEL",36);result.UECL=fillEntrants(uecl,state,"UECL",36);return result;}
function updateCoefficients(state:SeasonState,current:Record<string,number>){const next={...current};for(const t of state.worldCompetitions.tournaments.filter(x=>x.definition.kind==="Continental")){for(const p of t.participants)next[p.name]=Math.max(0,(next[p.name]??p.reputation*.6)*.82);for(const m of t.matches.filter(x=>x.played)){const hg=m.homeGoals??0,ag=m.awayGoals??0;next[m.home.name]=(next[m.home.name]??m.home.reputation*.6)+(hg>ag?2:hg===ag?1:0);next[m.away.name]=(next[m.away.name]??m.away.reputation*.6)+(ag>hg?2:hg===ag?1:0);}}return next;}
function leagueArchives(state:SeasonState){return PROFESSIONAL_COMPETITIONS.filter(c=>completed(state,c.id)).map(def=>{const rows=table(state,def.id),league=state.worldLeagues.leagues[def.id],active=def.id===state.competitionId,players=active?state.league.clubs.flatMap(c=>c.players):league?.players??[],scorer=[...players].sort((a,b)=>(b.goals??0)-(a.goals??0))[0];return{competitionId:def.id,competitionName:def.name,champion:rows[0]?.name??"—",runnerUp:rows[1]?.name??"—",topScorer:scorer?.name,topScorerGoals:scorer?.goals??0};});}
export function finalizeFootballEcosystem(state:SeasonState){const base=hydrateFootballEcosystem(state.ecosystem);if(base.lastFinalizedYear===state.year)return base;const nextDomestic:Partial<Record<ProfessionalCompetitionId,string[]>>={},movements:DomesticMovement[]=[];transitionPair(state,"BRA1","BRA2",4,4,movements,nextDomestic);transitionPair(state,"BRA2","BRA3",4,2,movements,nextDomestic);transitionPair(state,"ENG1","ENG2",3,3,movements,nextDomestic);transitionPair(state,"ESP1","ESP2",3,4,movements,nextDomestic);transitionPair(state,"FRA1","FRA2",2,3,movements,nextDomestic);for(const def of PROFESSIONAL_COMPETITIONS)if(!nextDomestic[def.id])nextDomestic[def.id]=table(state,def.id).map(x=>x.name);const intl=internationalPlan(state),continental=state.worldCompetitions.tournaments.filter(t=>t.definition.kind==="Continental"&&t.completed).map(t=>{const champion=t.participants.find(p=>p.id===t.championId)?.name??"—",final=t.matches.filter(m=>m.stage==="Final"&&m.played).at(-1),runner=final?(final.home.name===champion?final.away.name:final.home.name):undefined;return{competitionId:t.definition.id,name:t.definition.name,champion,runnerUp:runner};}),archive:SeasonArchive={year:state.year,leagues:leagueArchives(state),continental,movements,qualifiers:Object.entries(intl).map(([competitionId,clubs])=>({competitionId:competitionId as WorldCompetitionId,clubs:(clubs??[]).slice(0,12).map(x=>x.name)}))};return{archives:[archive,...base.archives].slice(0,30),coefficients:updateCoefficients(state,base.coefficients),nextDomesticParticipants:nextDomestic,nextInternationalEntrants:intl,lastFinalizedYear:state.year};}
export function nextCompetitionForClub(ecosystem:FootballEcosystemState,clubName:string,current:ProfessionalCompetitionId){for(const [id,names] of Object.entries(ecosystem.nextDomesticParticipants) as Array<[ProfessionalCompetitionId,string[]|undefined]>)if(names?.includes(clubName))return id;return current;}
