import { SeededRng } from "./rng";
import { PROFESSIONAL_COMPETITIONS, type ProfessionalCompetitionId } from "../data/brazil-2026/competitions";
import { sortedStandings } from "./league";
import { sortedParallelStandings } from "./world-leagues";
import type { SeasonState } from "./season";
import type { WorldCompetitionId } from "./world-competitions";

export type EcosystemClub={name:string;shortName:string;country:string;competitionId:ProfessionalCompetitionId;reputation:number;points:number;position:number};
export type DomesticMovement={clubName:string;from:string;to:string;reason:string};
export type QualificationEntrant={name:string;shortName:string;country:string;reputation:number;reason:string};
export type LeagueArchive={competitionId:ProfessionalCompetitionId;competitionName:string;champion:string;runnerUp:string;topScorer?:string;topScorerGoals?:number};
export type SeasonArchive={year:number;leagues:LeagueArchive[];continental:Array<{competitionId:WorldCompetitionId;name:string;champion:string;runnerUp?:string}>;movements:DomesticMovement[];qualifiers:Array<{competitionId:WorldCompetitionId;clubs:string[]}>};
export type FootballEcosystemState={archives:SeasonArchive[];coefficients:Record<string,number>;nextDomesticParticipants:Partial<Record<ProfessionalCompetitionId,string[]>>;nextInternationalEntrants:Partial<Record<WorldCompetitionId,QualificationEntrant[]>>;lastFinalizedYear?:number};
type EntrySource={name:string;shortName:string;country:string;reputation:number};

export function createFootballEcosystem():FootballEcosystemState{return{archives:[],coefficients:{},nextDomesticParticipants:{},nextInternationalEntrants:{}};}
export function hydrateFootballEcosystem(value:FootballEcosystemState|undefined){return value?{...createFootballEcosystem(),...value,archives:value.archives??[],coefficients:value.coefficients??{},nextDomesticParticipants:value.nextDomesticParticipants??{},nextInternationalEntrants:value.nextInternationalEntrants??{}}:createFootballEcosystem();}

function clubKey(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim().replace(/\s+/g," ");}
function uniqueNames(items:string[]){const seen=new Set<string>();return items.filter(item=>{const key=clubKey(item);if(seen.has(key))return false;seen.add(key);return true;});}
function table(state:SeasonState,id:ProfessionalCompetitionId):EcosystemClub[]{const def=PROFESSIONAL_COMPETITIONS.find(c=>c.id===id)!;if(id===state.competitionId){return sortedStandings(state.league).map((row,index)=>{const club=state.league.clubs.find(c=>c.id===row.clubId)!;return{name:club.name,shortName:club.shortName,country:def.country,competitionId:id,reputation:club.reputation,points:row.points,position:index+1};});}const league=state.worldLeagues.leagues[id];if(!league)return[];return sortedParallelStandings(league.standings).map((row,index)=>{const club=league.teams.find(c=>c.id===row.clubId)!;return{name:club.name,shortName:club.shortName,country:def.country,competitionId:id,reputation:Math.round(club.strength),points:row.points,position:index+1};});}
function completed(state:SeasonState,id:ProfessionalCompetitionId){if(id===state.competitionId)return state.league.fixtures.every(f=>f.played);return state.worldLeagues.leagues[id]?.fixtures.every(f=>f.played)??false;}
function transitionRows(state:SeasonState,id:ProfessionalCompetitionId){const rows=table(state,id);if(!rows.length||completed(state,id))return rows;const rng=new SeededRng(`${state.baseSeed}:${state.year}:${id}:offscreen-transition`);return rows.map(row=>({row,score:row.points*5+row.reputation*.75+rng.integer(-12,12)})).sort((a,b)=>b.score-a.score).map(({row},index)=>({...row,position:index+1}));}
function playoff(a:EcosystemClub|undefined,b:EcosystemClub|undefined,seed:string){if(!a)return b;if(!b)return a;const rng=new SeededRng(seed),sa=a.points+a.reputation*.28+rng.integer(-5,5),sb=b.points+b.reputation*.28+rng.integer(-5,5);return sa>=sb?a:b;}
function promotions(state:SeasonState,id:ProfessionalCompetitionId,rows=table(state,id)){if(id==="BRA2")return[...rows.slice(0,2),playoff(rows[2],rows[5],`${state.baseSeed}:${state.year}:b2p1`),playoff(rows[3],rows[4],`${state.baseSeed}:${state.year}:b2p2`)].filter((x):x is EcosystemClub=>Boolean(x));if(id==="BRA3"){const rng=new SeededRng(`${state.baseSeed}:${state.year}:c-second`);return rows.slice(0,8).map(x=>({x,score:x.points+x.reputation*.22+rng.integer(-7,7)})).sort((a,b)=>b.score-a.score).slice(0,4).map(x=>x.x);}if(id==="BRA4")return rows.slice(0,6);if(id==="ENG2"||id==="ESP2"){const semi1=playoff(rows[2],rows[5],`${state.baseSeed}:${state.year}:${id}:s1`),semi2=playoff(rows[3],rows[4],`${state.baseSeed}:${state.year}:${id}:s2`),winner=playoff(semi1,semi2,`${state.baseSeed}:${state.year}:${id}:final`);return[...rows.slice(0,2),winner].filter((x):x is EcosystemClub=>Boolean(x));}if(id==="FRA2")return rows.slice(0,2);return[];}

const RESERVE:Partial<Record<ProfessionalCompetitionId,string[]>>={ENG2:["Stockport County","Huddersfield Town","Reading","Barnsley","Blackpool","Plymouth Argyle"],ESP2:["Real Murcia","Nàstic Tarragona","Málaga B","Ponferradina","Lugo","Hércules"],FRA2:["Le Mans","Orléans","Valenciennes","Rouen","Caen","Versailles"]};
function transitionPair(state:SeasonState,top:ProfessionalCompetitionId,lower:ProfessionalCompetitionId,relegatedCount:number,lowerExternalDrop:number,movements:DomesticMovement[],next:Partial<Record<ProfessionalCompetitionId,string[]>>){const topRows=table(state,top),lowRows=table(state,lower);if(!topRows.length||!lowRows.length||!completed(state,top)||!completed(state,lower)){next[top]=topRows.map(x=>x.name);next[lower]=lowRows.map(x=>x.name);return;}const promoted=promotions(state,lower,lowRows),relegated=topRows.slice(-relegatedCount),externalDrop=lowRows.slice(-lowerExternalDrop),reserve=(RESERVE[lower]??[]).filter(name=>!lowRows.some(x=>clubKey(x.name)===clubKey(name))).slice(0,externalDrop.length);next[top]=uniqueNames(topRows.filter(x=>!relegated.includes(x)).map(x=>x.name).concat(promoted.map(x=>x.name))).slice(0,topRows.length);next[lower]=uniqueNames(lowRows.filter(x=>!promoted.includes(x)&&!externalDrop.includes(x)).map(x=>x.name).concat(relegated.map(x=>x.name),reserve)).slice(0,lowRows.length);for(const x of relegated)movements.push({clubName:x.name,from:top,to:lower,reason:"Rebaixamento"});for(const x of promoted)movements.push({clubName:x.name,from:lower,to:top,reason:"Acesso"});for(const name of reserve)movements.push({clubName:name,from:"DIVISÃO INFERIOR",to:lower,reason:"Acesso"});}

const BRAZIL_SERIE_D_ENTRY_POOL=["EC São Bento","XV de Piracicaba","CA Juventus","EC Taubaté","Portuguesa Santista","CA Linense","Comercial FC","Monte Azul","Bangu AC","America-RJ","Cabofriense","Macaé Esporte","Villa Nova-MG","URT","Tupi FC","Democrata-GV","Guarani de Divinópolis","Rio Branco-ES","Desportiva Ferroviária","Vitória-ES","Itabaiana-SE","Sergipe","Juazeirense","Fluminense de Feira","Central-PE","Santa Cruz de Natal","Potiguar de Mossoró","River-PI","Altos-PI","Moto Club-MA","Maranhão AC","Tocantinópolis","São Raimundo-RR","Nacional-AM","Fast Clube","Trem-AP","São Francisco-PA"] as const;
function brazilSerieCRelegationSlots(year:number){return year<=2027?2:6;}
function serieDExternalQualifiers(state:SeasonState,count:number,occupied:string[]){if(count<=0)return[];const blocked=new Set(occupied.map(clubKey)),rng=new SeededRng(`${state.baseSeed}:${state.year}:serie-d-state-qualifiers`);return BRAZIL_SERIE_D_ENTRY_POOL.filter(name=>!blocked.has(clubKey(name))).map((name,index)=>({name,score:100-index+rng.integer(0,35)})).sort((a,b)=>b.score-a.score).slice(0,count).map(item=>item.name);}
function preserveBrazilParticipants(state:SeasonState,next:Partial<Record<ProfessionalCompetitionId,string[]>>){for(const id of ["BRA1","BRA2","BRA3","BRA4"] as ProfessionalCompetitionId[])next[id]=table(state,id).map(x=>x.name);}
function transitionBrazilPyramid(state:SeasonState,movements:DomesticMovement[],next:Partial<Record<ProfessionalCompetitionId,string[]>>){if(state.completed&&state.competitionId.startsWith("BRA")&&!completed(state,state.competitionId)){preserveBrazilParticipants(state,next);return;}const a=transitionRows(state,"BRA1"),b=transitionRows(state,"BRA2"),c=transitionRows(state,"BRA3"),d=transitionRows(state,"BRA4");if(!a.length||!b.length||!c.length||!d.length){preserveBrazilParticipants(state,next);return;}const aDown=a.slice(-4),bUp=promotions(state,"BRA2",b),bDown=b.slice(-4),cUp=promotions(state,"BRA3",c),cDown=c.slice(-brazilSerieCRelegationSlots(state.year)),dUp=promotions(state,"BRA4",d),neededExternal=Math.max(0,dUp.length-cDown.length),occupied=[...a,...b,...c,...d].map(x=>x.name),external=serieDExternalQualifiers(state,neededExternal,occupied);next.BRA1=uniqueNames(a.filter(x=>!aDown.includes(x)).map(x=>x.name).concat(bUp.map(x=>x.name))).slice(0,a.length);next.BRA2=uniqueNames(b.filter(x=>!bUp.includes(x)&&!bDown.includes(x)).map(x=>x.name).concat(aDown.map(x=>x.name),cUp.map(x=>x.name))).slice(0,b.length);next.BRA3=uniqueNames(c.filter(x=>!cUp.includes(x)&&!cDown.includes(x)).map(x=>x.name).concat(bDown.map(x=>x.name),dUp.map(x=>x.name)));let serieD=uniqueNames(d.filter(x=>!dUp.includes(x)).map(x=>x.name).concat(cDown.map(x=>x.name),external));const refill=serieDExternalQualifiers(state,Math.max(0,d.length-serieD.length),occupied.concat(serieD,external));serieD=uniqueNames(serieD.concat(refill)).slice(0,d.length);next.BRA4=serieD;for(const x of aDown)movements.push({clubName:x.name,from:"BRA1",to:"BRA2",reason:"Rebaixamento"});for(const x of bUp)movements.push({clubName:x.name,from:"BRA2",to:"BRA1",reason:"Acesso"});for(const x of bDown)movements.push({clubName:x.name,from:"BRA2",to:"BRA3",reason:"Rebaixamento"});for(const x of cUp)movements.push({clubName:x.name,from:"BRA3",to:"BRA2",reason:"Acesso"});for(const x of cDown)movements.push({clubName:x.name,from:"BRA3",to:"BRA4",reason:"Rebaixamento"});for(const x of dUp)movements.push({clubName:x.name,from:"BRA4",to:"BRA3",reason:"Acesso"});for(const name of external)movements.push({clubName:name,from:"ESTADUAL/RNC",to:"BRA4",reason:"Classificação estadual/ranking nacional"});for(const name of refill)movements.push({clubName:name,from:"BASE DE DADOS",to:"BRA4",reason:"Correção de integridade: duplicidade entre divisões"});}

function tournamentChampion(state:SeasonState,id:WorldCompetitionId){const tournament=state.worldCompetitions.tournaments.find(x=>x.definition.id===id);return tournament?.participants.find(x=>x.id===tournament.championId);}
function tournamentRunnerUp(state:SeasonState,id:WorldCompetitionId){const tournament=state.worldCompetitions.tournaments.find(x=>x.definition.id===id),champion=tournament?.participants.find(x=>x.id===tournament.championId),final=tournament?.matches.filter(match=>match.stage==="Final"&&match.played).sort((a,b)=>a.date.localeCompare(b.date)).at(-1);if(!champion||!final)return undefined;return final.home.id===champion.id?final.away:final.home;}
function entry(source:EntrySource,reason:string):QualificationEntrant{return{name:source.name,shortName:source.shortName,country:source.country,reputation:source.reputation,reason};}
function addEntry(target:QualificationEntrant[],source:EntrySource|undefined,reason:string,blocked?:Set<string>){if(!source)return false;const key=clubKey(source.name);if(blocked?.has(key)||target.some(item=>clubKey(item.name)===key))return false;target.push(entry(source,reason));return true;}
function fillEntrants(base:QualificationEntrant[],state:SeasonState,id:WorldCompetitionId,count:number,blocked=new Set<string>()){const own=new Set(base.map(item=>clubKey(item.name))),tournament=state.worldCompetitions.tournaments.find(t=>t.definition.id===id),pool=[...(tournament?.participants??[])].sort((a,b)=>b.reputation-a.reputation);for(const participant of pool){const key=clubKey(participant.name);if(base.length>=count)break;if(blocked.has(key)||own.has(key))continue;base.push(entry(participant,"Coeficiente/rota continental"));own.add(key);}let i=1;while(base.length<count){const name=`Classificado ${id} ${i}`,key=clubKey(name);if(!blocked.has(key)&&!own.has(key)){base.push({name,shortName:`${id}${i}`,country:id==="LIB"||id==="SUD"?"CONMEBOL":"Europa",reputation:62,reason:"Qualificatória continental"});own.add(key);}i++;}return base.slice(0,count);}
function associationPerformance(state:SeasonState){const score:Record<string,number>={};for(const id of ["UCL","UEL","UECL"] as WorldCompetitionId[]){const tournament=state.worldCompetitions.tournaments.find(x=>x.definition.id===id);for(const match of tournament?.matches.filter(x=>x.played)??[]){const hg=match.homeGoals??0,ag=match.awayGoals??0;score[match.home.country]=(score[match.home.country]??0)+(hg>ag?2:hg===ag?1:0);score[match.away.country]=(score[match.away.country]??0)+(ag>hg?2:hg===ag?1:0);}}return Object.entries(score).sort((a,b)=>b[1]-a[1]).slice(0,2).map(([country])=>country);}
function addLeagueSlots(target:QualificationEntrant[],rows:EcosystemClub[],slots:number,reason:string,blocked:Set<string>){let added=0;for(const club of rows){if(added>=slots)break;if(addEntry(target,club,reason,blocked)){blocked.add(clubKey(club.name));added++;}}}

function internationalPlan(state:SeasonState){const result:Partial<Record<WorldCompetitionId,QualificationEntrant[]>>={},bra=transitionRows(state,"BRA1"),eng=transitionRows(state,"ENG1"),esp=transitionRows(state,"ESP1"),fra=transitionRows(state,"FRA1");
 const lib:QualificationEntrant[]=[],domesticLib=new Set<string>(),libChamp=tournamentChampion(state,"LIB"),sudChamp=tournamentChampion(state,"SUD"),cdbChampion=tournamentChampion(state,"CDB"),cdbRunner=tournamentRunnerUp(state,"CDB");
 for(const champion of [libChamp,sudChamp])if(champion?.country==="Brasil")addEntry(lib,champion,"Campeão continental");
 const addDomesticLib=(source:EntrySource|undefined,reason:string)=>{if(!source)return;const key=clubKey(source.name);domesticLib.add(key);addEntry(lib,source,reason);};
 addDomesticLib(cdbChampion,"Campeão da Copa do Brasil • fase de grupos");
 addDomesticLib(cdbRunner,"Vice da Copa do Brasil • pré-Libertadores");
 for(const club of bra){if(domesticLib.size>=7)break;addDomesticLib(club,club.position<=5?"Brasileirão • vaga Libertadores":"Brasileirão • vaga redistribuída");}
 result.LIB=fillEntrants(lib,state,"LIB",32);
 const libKeys=new Set((result.LIB??[]).map(item=>clubKey(item.name))),sud:QualificationEntrant[]=[];
 for(const club of bra){if(sud.length>=6)break;addEntry(sud,club,"Brasileirão • Sul-Americana",libKeys);}
 result.SUD=fillEntrants(sud,state,"SUD",32,libKeys);

 const perf=new Set(associationPerformance(state)),ucl:QualificationEntrant[]=[],uel:QualificationEntrant[]=[],uecl:QualificationEntrant[]=[],uclOccupied=new Set<string>(),uclChamp=tournamentChampion(state,"UCL"),uelChamp=tournamentChampion(state,"UEL");
 for(const champion of [uclChamp,uelChamp])if(champion&&addEntry(ucl,champion,champion===uclChamp?"Campeão da Champions":"Campeão da Europa League",uclOccupied))uclOccupied.add(clubKey(champion.name));
 for(const rows of [eng,esp]){addLeagueSlots(ucl,rows,4,"Classificação nacional",uclOccupied);if(perf.has(rows[0]?.country??""))addLeagueSlots(ucl,rows.slice(4),1,"Vaga extra por desempenho UEFA",uclOccupied);}
 addLeagueSlots(ucl,fra,3,"Classificação nacional",uclOccupied);addLeagueSlots(ucl,fra.slice(3),1,"Rota preliminar da Champions",uclOccupied);
 result.UCL=fillEntrants(ucl,state,"UCL",36);
 for(const qualifier of result.UCL??[])uclOccupied.add(clubKey(qualifier.name));

 const addEuropaAssociation=(rows:EcosystemClub[],cupId:WorldCompetitionId)=>{const country=rows[0]?.country,chosen=()=>uel.filter(item=>item.country===country).length,winner=tournamentChampion(state,cupId);if(winner?.country===country)addEntry(uel,winner,"Campeão da copa nacional",uclOccupied);for(const club of rows){if(chosen()>=2)break;addEntry(uel,club,"Classificação nacional / vaga redistribuída",uclOccupied);}};
 addEuropaAssociation(eng,"FAC");addEuropaAssociation(esp,"CDR");addEuropaAssociation(fra,"CDF");
 result.UEL=fillEntrants(uel,state,"UEL",36,uclOccupied);
 const allUefaOccupied=new Set(uclOccupied);for(const qualifier of result.UEL??[])allUefaOccupied.add(clubKey(qualifier.name));

 const eflWinner=tournamentChampion(state,"EFL");if(!addEntry(uecl,eflWinner,"Campeão da Copa da Liga",allUefaOccupied))addLeagueSlots(uecl,eng,1,"Classificação nacional / vaga redistribuída",allUefaOccupied);else if(eflWinner)allUefaOccupied.add(clubKey(eflWinner.name));
 addLeagueSlots(uecl,esp,1,"Classificação nacional",allUefaOccupied);addLeagueSlots(uecl,fra,1,"Classificação nacional",allUefaOccupied);
 result.UECL=fillEntrants(uecl,state,"UECL",36,allUefaOccupied);
 return result;
}

function updateCoefficients(state:SeasonState,current:Record<string,number>){const next={...current};for(const tournament of state.worldCompetitions.tournaments.filter(x=>x.definition.kind==="Continental")){for(const participant of tournament.participants)next[participant.name]=Math.max(0,(next[participant.name]??participant.reputation*.6)*.82);for(const match of tournament.matches.filter(x=>x.played)){const hg=match.homeGoals??0,ag=match.awayGoals??0;next[match.home.name]=(next[match.home.name]??match.home.reputation*.6)+(hg>ag?2:hg===ag?1:0);next[match.away.name]=(next[match.away.name]??match.away.reputation*.6)+(ag>hg?2:hg===ag?1:0);}}return next;}
function leagueArchives(state:SeasonState){return PROFESSIONAL_COMPETITIONS.filter(c=>completed(state,c.id)).map(def=>{const rows=table(state,def.id),league=state.worldLeagues.leagues[def.id],active=def.id===state.competitionId,players=active?state.league.clubs.flatMap(c=>c.players):league?.players??[],scorer=[...players].sort((a,b)=>(b.goals??0)-(a.goals??0))[0];return{competitionId:def.id,competitionName:def.name,champion:rows[0]?.name??"—",runnerUp:rows[1]?.name??"—",topScorer:scorer?.name,topScorerGoals:scorer?.goals??0};});}

export function finalizeFootballEcosystem(state:SeasonState){const base=hydrateFootballEcosystem(state.ecosystem);if(base.lastFinalizedYear===state.year)return base;const nextDomestic:Partial<Record<ProfessionalCompetitionId,string[]>>={},movements:DomesticMovement[]=[];transitionBrazilPyramid(state,movements,nextDomestic);transitionPair(state,"ENG1","ENG2",3,3,movements,nextDomestic);transitionPair(state,"ESP1","ESP2",3,4,movements,nextDomestic);transitionPair(state,"FRA1","FRA2",2,3,movements,nextDomestic);for(const def of PROFESSIONAL_COMPETITIONS)if(!nextDomestic[def.id])nextDomestic[def.id]=table(state,def.id).map(x=>x.name);const intl=internationalPlan(state),continental=state.worldCompetitions.tournaments.filter(t=>t.definition.kind==="Continental"&&t.completed).map(t=>{const champion=t.participants.find(p=>p.id===t.championId)?.name??"—",final=t.matches.filter(m=>m.stage==="Final"&&m.played).at(-1),runner=final?(final.home.name===champion?final.away.name:final.home.name):undefined;return{competitionId:t.definition.id,name:t.definition.name,champion,runnerUp:runner};}),archive:SeasonArchive={year:state.year,leagues:leagueArchives(state),continental,movements,qualifiers:Object.entries(intl).map(([competitionId,clubs])=>({competitionId:competitionId as WorldCompetitionId,clubs:(clubs??[]).slice(0,12).map(x=>x.name)}))};return{archives:[archive,...base.archives].slice(0,30),coefficients:updateCoefficients(state,base.coefficients),nextDomesticParticipants:nextDomestic,nextInternationalEntrants:intl,lastFinalizedYear:state.year};}
export function nextCompetitionForClub(ecosystem:FootballEcosystemState,clubName:string,current:ProfessionalCompetitionId){for(const [id,names] of Object.entries(ecosystem.nextDomesticParticipants) as Array<[ProfessionalCompetitionId,string[]|undefined]>)if(names?.some(name=>clubKey(name)===clubKey(clubName)))return id;return current;}
