import{describe,expect,it}from"vitest";
import{professionalCompetitionById}from"../data/brazil-2026/competitions";
import{applySportingStatsAndDevelopment,preparePlayerDevelopmentNextSeason}from"./development";
import{createLeague}from"./league";
import type{MatchResult}from"./match";
import{createSeason,matchdaySelectionReady,playCurrentRound,setMatchdayRole}from"./season";
import{naturalTacticalPoint,tacticalFitMultiplier}from"./tactical-position";

describe("Sprint 13 — Europa e evolução",()=>{
 it("carrega as três primeiras divisões europeias com o snapshot 2026/27",()=>{const eng=professionalCompetitionById("ENG1"),esp=professionalCompetitionById("ESP1"),fra=professionalCompetitionById("FRA1");expect(eng.clubs).toHaveLength(20);expect(esp.clubs).toHaveLength(20);expect(fra.clubs).toHaveLength(18);expect(eng.clubs.flatMap(c=>c.players)).toHaveLength(545);expect(esp.clubs.flatMap(c=>c.players)).toHaveLength(510);expect(fra.clubs.flatMap(c=>c.players)).toHaveLength(470);expect(eng.clubs.map(c=>c.name)).toEqual(expect.arrayContaining(["Manchester City FC","Coventry City","Hull City","Ipswich Town FC"]));expect(esp.clubs.map(c=>c.name)).toEqual(expect.arrayContaining(["Real Madrid CF","FC Barcelona","Málaga CF","Racing Santander"]));expect(fra.clubs.map(c=>c.name)).toEqual(expect.arrayContaining(["Paris Saint-Germain","Le Mans FC","ESTAC Troyes"]))});
 it("cria convocação pré-jogo com titulares e banco conforme a liga",()=>{let state=createSeason("eng-matchday",2026,"club-1","ENG1");expect(state.lineupIds).toHaveLength(11);expect(state.benchIds).toHaveLength(9);expect(matchdaySelectionReady(state)).toBe(true);const removed=state.benchIds[0];state=setMatchdayRole(state,removed,"out");expect(state.benchIds).toHaveLength(8);expect(matchdaySelectionReady(state)).toBe(false);const replacement=state.league.clubs[0].players.find(p=>!state.lineupIds.includes(p.id)&&!state.benchIds.includes(p.id)&&p.id!==removed&&p.injuryDays===0&&p.suspensionMatches===0)!;state=setMatchdayRole(state,replacement.id,"bench");expect(matchdaySelectionReady(state)).toBe(true)});
 it("faz posicionamento natural render melhor que deslocamento extremo",()=>{const player=createLeague("fit",2026,"ENG1").clubs[0].players.find(p=>p.position==="GOL")!,natural=naturalTacticalPoint(player.position);expect(tacticalFitMultiplier(player,natural)).toBeGreaterThan(tacticalFitMultiplier(player,{x:10,y:10}));});
 it("estatísticas de partida alimentam a evolução de um jovem com potencial",()=>{const league=createLeague("development",2026,"ENG1"),club=league.clubs[0],player=club.players.filter(p=>p.age<=21&&p.potential>p.overall).sort((a,b)=>b.potential-b.overall-(a.potential-a.overall))[0],start=player.overall;expect(player).toBeTruthy();for(let round=1;round<=12;round++){const result:MatchResult={homeGoals:2,awayGoals:0,possessionHome:60,shotsHome:12,shotsAway:5,events:[{minute:20,type:"goal",team:"home",playerId:player.id,text:"gol"},{minute:50,type:"chance",team:"home",playerId:player.id,text:"chance"},{minute:90,type:"fulltime",team:"neutral",text:"fim"}]};applySportingStatsAndDevelopment(club,result,"home",[player.id],[player.id],round,2026,"dev-test");}expect(player.appearances).toBe(12);expect(player.goals).toBe(12);expect(player.averageRating).toBeGreaterThan(7);expect(player.overall).toBeGreaterThan(start);expect(player.overall).toBeLessThanOrEqual(player.potential)});
 it("regrede veteranos na virada de temporada e zera estatísticas sazonais",()=>{const league=createLeague("aging",2026,"ENG1"),veteran=league.clubs.flatMap(c=>c.players).find(p=>p.age>=34)!;veteran.goals=7;const age=veteran.age,overall=veteran.overall;preparePlayerDevelopmentNextSeason(league,2027);expect(veteran.age).toBe(age+1);expect(veteran.overall).toBeLessThan(overall);expect(veteran.goals).toBe(0);expect(veteran.seasonStartOverall).toBe(veteran.overall)});
 it("persiste dados coletivos e individuais ao simular uma rodada",()=>{const state=playCurrentRound(createSeason("stats-round",2026,"club-1","ENG1")),played=state.league.fixtures.filter(f=>f.played),players=state.league.clubs.flatMap(c=>c.players);expect(played).toHaveLength(10);expect(played.every(f=>typeof f.homeShots==="number"&&typeof f.awayShots==="number"&&typeof f.possessionHome==="number")).toBe(true);expect(players.filter(p=>p.appearances===1).length).toBe(220);expect(players.some(p=>p.ratedMatches===1)).toBe(true)});
});
