import{describe,expect,it}from"vitest";
import{createSeason,setIndividualTrainingFocus,setPlayerMentor,setPlayerRetrainingPosition}from"./season";
import{applyTrainingDay}from"./training";
import{playerAttributeProfile}from"./player-attributes";
import{buildNewsEngineV2}from"./news-engine";
import{processWorldLeaguesThroughDate}from"./world-leagues";
import{aggregateScoreForMatch,type WorldTournamentState,type WorldCompetitionMatch}from"./world-competitions";

describe("Sprint C + news + aggregate",()=>{it("individual training improves a focused attribute and mentoring is persistent",()=>{let state=createSeason("sprint-c",2026);const club=state.league.clubs[0],player=club.players.find(p=>p.position!=="GOL")!,mentor=club.players.filter(p=>p.id!==player.id&&p.age>=player.age+3).sort((a,b)=>b.age-a.age)[0];state=setIndividualTrainingFocus(state,player.id,"Passe");if(mentor)state=setPlayerMentor(state,player.id,mentor.id);state=setPlayerRetrainingPosition(state,player.id,"MC");const current=state.league.clubs[0].players.find(p=>p.id===player.id)!,before=playerAttributeProfile(current).technical.find(a=>a.key==="passe")!.value;for(let i=0;i<20;i++)applyTrainingDay(state.league.clubs[0],"Equilibrado");const afterPlayer=state.league.clubs[0].players.find(p=>p.id===player.id)!,after=playerAttributeProfile(afterPlayer).technical.find(a=>a.key==="passe")!.value;expect(after).toBeGreaterThanOrEqual(before+1);expect(afterPlayer.individualTrainingFocus).toBe("Passe");});
 it("news engine covers parallel active leagues",()=>{const state=createSeason("world-news",2026);state.worldLeagues=processWorldLeaguesThroughDate(state.worldLeagues,state.baseSeed,"2027-06-30");const news=buildNewsEngineV2(state),parallel=Object.values(state.worldLeagues.leagues).find(Boolean)!;expect(news.some(item=>item.tags.includes(parallel.competitionId))).toBe(true);});
 it("computes aggregate relative to the displayed leg",()=>{const a={id:"a",name:"A",shortName:"A",country:"X",reputation:80},b={id:"b",name:"B",shortName:"B",country:"X",reputation:80};const legs=[{id:"t:L1",competitionId:"LIB",stage:"Oitavas",roundDue:1,date:"2026-01-01",home:a,away:b,played:true,homeGoals:2,awayGoals:0,leg:1,tieId:"t"},{id:"t:L2",competitionId:"LIB",stage:"Oitavas",roundDue:2,date:"2026-01-08",home:b,away:a,played:true,homeGoals:1,awayGoals:0,leg:2,tieId:"t",winnerId:"a"}] as WorldCompetitionMatch[];const tournament={matches:legs} as WorldTournamentState;expect(aggregateScoreForMatch(tournament,legs[1])).toMatchObject({homeGoals:1,awayGoals:2,legsPlayed:2,legsTotal:2,winnerId:"a"});});});
