import type { SeasonState } from "./season";
export type WorkloadLevel="Baixa"|"Moderada"|"Alta"|"Crítica";
export type CongestionMetrics={restDays:number;matchesLast7:number;matchesLast14:number;matchesNext7:number;matchesNext14:number;denseEightDayWindow:number};
export type WorkloadAdvice={level:WorkloadLevel;score:number;detail:string;rotationRecommended:boolean;loadPenalty:number;medicalLevel:number;recommendedTraining:"Recuperação"|"Equilibrado";congestion:CongestionMetrics};
const DAY=86400000;
const days=(a:string,b:string)=>Math.round((new Date(`${a}T12:00:00Z`).getTime()-new Date(`${b}T12:00:00Z`).getTime())/DAY);
function userMatchDates(state:SeasonState){const league=state.league.fixtures.filter(f=>f.date&&(f.homeClubId===state.selectedClubId||f.awayClubId===state.selectedClubId)).map(f=>f.date!),cups=state.worldCompetitions.tournaments.flatMap(t=>t.matches.filter(m=>m.home.activeClubId===state.selectedClubId||m.away.activeClubId===state.selectedClubId).map(m=>m.date));return[...league,...cups].sort();}
export function congestionMetrics(matchDates:string[],date:string):CongestionMetrics{const unique=[...new Set(matchDates)].sort(),past=unique.filter(d=>d<date),future=unique.filter(d=>d>date),last=past.at(-1),restDays=last?Math.max(0,days(date,last)):7,matchesLast7=past.filter(d=>days(date,d)<=7).length,matchesLast14=past.filter(d=>days(date,d)<=14).length,matchesNext7=future.filter(d=>days(d,date)<=7).length,matchesNext14=future.filter(d=>days(d,date)<=14).length,window=unique.filter(d=>Math.abs(days(d,date))<=4).length;return{restDays,matchesLast7,matchesLast14,matchesNext7,matchesNext14,denseEightDayWindow:window};}
function medicalLevel(state:SeasonState){const level=state.clubManagement?.clubs?.[state.selectedClubId]?.departments?.["Médico"]?.level??3;return Math.max(1,Math.min(5,Math.round(level)));}
export function workloadAdvice(state:SeasonState,date=state.currentDate,continentalAway=false){const congestion=congestionMetrics(userMatchDates(state),date),selected=state.league.clubs.find(c=>c.id===state.selectedClubId),avgFatigue=selected&&selected.players.length?selected.players.reduce((s,p)=>s+p.fatigue,0)/selected.players.length:0,medical=medicalLevel(state),rest=congestion.restDays;let score=(rest<=2?44:rest===3?27:rest===4?13:4)+Math.max(0,congestion.matchesLast14-2)*9+Math.max(0,congestion.matchesNext7-1)*8+Math.max(0,congestion.denseEightDayWindow-2)*8+Math.max(0,avgFatigue-35)*.55+(continentalAway?12:0)-(medical-3)*3;score=Math.round(Math.max(0,Math.min(100,score)));const level:WorkloadLevel=score>=72?"Crítica":score>=52?"Alta":score>=28?"Moderada":"Baixa",loadPenalty=Math.max(0,Math.round((score>=72?8:score>=52?5:score>=28?2:0)+(continentalAway?2:0)-(medical>=5?2:medical>=4?1:0))),recommendedTraining=score>=52||congestion.matchesNext7>=2?"Recuperação":"Equilibrado";return{level,score,rotationRecommended:score>=45,loadPenalty,medicalLevel:medical,recommendedTraining,congestion,detail:`${rest} dia(s) desde o último jogo • ${congestion.matchesLast7} jogo(s) nos últimos 7 dias • ${congestion.matchesNext7} compromisso(s) nos próximos 7 • fadiga média ${Math.round(avgFatigue)}% • depto. médico nível ${medical}.${continentalAway?" Viagem continental fora de casa aumenta a carga.":""}`} as WorkloadAdvice;}
