import { SeededRng } from "./rng";
import { createLeague, createLeagueFromClubNames, type LeagueFixture, type LeagueStanding } from "./league";
import { PROFESSIONAL_COMPETITIONS, professionalCompetitionById, type ProfessionalCompetitionId } from "../data/brazil-2026/competitions";
import { consumePendingNewGameSetup, type ManagerSetupProfile } from "./new-game-setup";
import { auditResults, calibratedExpectedGoals, samplePoisson, type RealismAudit } from "./match-realism";
import { postMatchPhysicalUpdate, recoverPhysicalState, returnToPlayAssessment, rollMatchInjury } from "./player-health";

export type WorldLeagueTeam={id:string;name:string;shortName:string;imageUrl:string;strength:number;medicalLevel:number};
export type WorldLeaguePlayer={id:string;clubId:string;name:string;position:string;age:number;marketValueEur:number|null;appearances:number;goals:number;assists:number;ratingTotal:number;ratedMatches:number;averageRating:number;condition:number;fatigue:number;injuryDays:number;lastAppearanceDate?:string;lastHealthDate?:string};
export type ParallelInjury={playerId:string;playerName:string;clubId:string;date:string;days:number;severity:string};
export type ParallelLeagueState={competitionId:ProfessionalCompetitionId;name:string;shortName:string;country:string;season:number;teams:WorldLeagueTeam[];fixtures:LeagueFixture[];standings:LeagueStanding[];players:WorldLeaguePlayer[];realismAudit?:RealismAudit;injuryLog?:ParallelInjury[]};
export type WorldLeaguesState={season:number;leagues:Partial<Record<ProfessionalCompetitionId,ParallelLeagueState>>;lastProcessedDate?:string;loadedCompetitionIds?:ProfessionalCompetitionId[];managerProfile?:ManagerSetupProfile};

const teamStrength=(market:number)=>Math.max(52,Math.min(94,56+Math.log10(Math.max(1_000_000,market)/1_000_000)*11));
const positionWeight=(position:string)=>position==="ATA"?6:["PE","PD"].includes(position)?5:position==="MEI"?4:["MC","VOL"].includes(position)?3:["LD","LE"].includes(position)?2.2:position==="ZAG"?1.2:.35;
const DAY=86_400_000;
function daysBetween(a:string,b:string){return Math.max(0,Math.round((new Date(`${a}T12:00:00Z`).getTime()-new Date(`${b}T12:00:00Z`).getTime())/DAY));}
function weightedPick<T>(rng:SeededRng,items:T[],weight:(item:T)=>number){const total=items.reduce((sum,item)=>sum+Math.max(.05,weight(item)),0);let roll=rng.next()*total;for(const item of items){roll-=Math.max(.05,weight(item));if(roll<=0)return item;}return items[items.length-1];}
function standingFor(league:ParallelLeagueState,id:string){return league.standings.find(item=>item.clubId===id)!;}
function updateTable(league:ParallelLeagueState,fixture:LeagueFixture,hg:number,ag:number){const h=standingFor(league,fixture.homeClubId),a=standingFor(league,fixture.awayClubId);h.played++;a.played++;h.goalsFor+=hg;h.goalsAgainst+=ag;a.goalsFor+=ag;a.goalsAgainst+=hg;if(hg>ag){h.won++;a.lost++;h.points+=3}else if(ag>hg){a.won++;h.lost++;a.points+=3}else{h.drawn++;a.drawn++;h.points++;a.points++;}}
function ratePlayers(players:WorldLeaguePlayer[],won:boolean,draw:boolean,goalIds:string[],assistIds:string[],rng:SeededRng){for(const player of players){player.appearances++;let rating=6.25+(won?.35:draw?.08:-.18)+rng.integer(-18,18)/100+goalIds.filter(id=>id===player.id).length*.75+assistIds.filter(id=>id===player.id).length*.45;rating=Math.max(4.8,Math.min(9.8,rating));player.ratingTotal+=rating;player.ratedMatches++;player.averageRating=Math.round(player.ratingTotal/player.ratedMatches*100)/100;}}
function advanceHealth(players:WorldLeaguePlayer[],date:string,medicalLevel:number){for(const player of players){if(!player.lastHealthDate){player.lastHealthDate=date;continue;}const elapsed=daysBetween(date,player.lastHealthDate);if(elapsed<=0)continue;const recovered=recoverPhysicalState(player,elapsed,{medicalLevel,recoveryTraining:player.fatigue>=62||player.injuryDays>0});player.condition=recovered.condition;player.fatigue=recovered.fatigue;player.injuryDays=recovered.injuryDays;player.lastHealthDate=date;}}
function selectionScore(player:WorldLeaguePlayer){const clearance=returnToPlayAssessment(player),restriction=clearance.status==="Liberado com restrições"?18:clearance.status==="Indisponível"?80:0;return Math.log10(Math.max(100_000,player.marketValueEur??100_000))*20+player.condition*.35-player.fatigue*.3-restriction;}
function selectXI(players:WorldLeaguePlayer[]){const healthy=players.filter(player=>player.injuryDays===0).sort((a,b)=>selectionScore(b)-selectionScore(a));if(healthy.length>=11)return healthy.slice(0,11);return[...healthy,...players.filter(player=>player.injuryDays>0).sort((a,b)=>a.injuryDays-b.injuryDays||selectionScore(b)-selectionScore(a))].slice(0,11);}
function physicalStrength(xi:WorldLeaguePlayer[]){if(!xi.length)return 0;const availability=xi.reduce((sum,p)=>sum+(p.condition/100)*Math.max(.78,1-p.fatigue/220),0)/xi.length;return(availability- .86)*13;}
function applyParallelMatchLoad(league:ParallelLeagueState,team:WorldLeagueTeam,players:WorldLeaguePlayer[],date:string,rng:SeededRng){for(const player of players){const rest=player.lastAppearanceDate?daysBetween(date,player.lastAppearanceDate):6,clearance=returnToPlayAssessment(player),physical=postMatchPhysicalUpdate(player,{minutes:90,pressing:58,tempo:56,restDays:rest,medicalLevel:team.medicalLevel,returnRestriction:clearance.status==="Liberado com restrições"},rng);player.condition=physical.condition;player.fatigue=physical.fatigue;player.lastAppearanceDate=date;player.lastHealthDate=date;if(player.injuryDays>0)continue;const injury=rollMatchInjury(rng,physical.injuryProbability);if(!injury.injured)continue;player.injuryDays=injury.days;player.condition=Math.min(player.condition,injury.days>=25?56:injury.days>=9?66:injury.days>=4?74:82);(league.injuryLog??=[]).push({playerId:player.id,playerName:player.name,clubId:player.clubId,date,days:injury.days,severity:injury.severity??"indefinida"});}}
function simulateFixture(league:ParallelLeagueState,fixture:LeagueFixture,seed:string){const date=fixture.date??`${league.season}-01-01`,home=league.teams.find(t=>t.id===fixture.homeClubId)!,away=league.teams.find(t=>t.id===fixture.awayClubId)!,rng=new SeededRng(`${seed}:${league.competitionId}:${fixture.id}`),homePlayers=league.players.filter(p=>p.clubId===home.id),awayPlayers=league.players.filter(p=>p.clubId===away.id);advanceHealth(homePlayers,date,home.medicalLevel);advanceHealth(awayPlayers,date,away.medicalLevel);const homePool=selectXI(homePlayers),awayPool=selectXI(awayPlayers),homeStrength=home.strength+physicalStrength(homePool)+1.9,awayStrength=away.strength+physicalStrength(awayPool),expected=calibratedExpectedGoals(homeStrength,awayStrength),hg=samplePoisson(rng,expected.home),ag=samplePoisson(rng,expected.away),delta=(homeStrength-awayStrength)/13,homeGoals:string[]=[],awayGoals:string[]=[],homeAssists:string[]=[],awayAssists:string[]=[];
  for(let i=0;i<hg;i++){const scorer=weightedPick(rng,homePool,p=>positionWeight(p.position)*(1+Math.log10(Math.max(100_000,p.marketValueEur??100_000)/100_000)*.08));scorer.goals++;homeGoals.push(scorer.id);const others=homePool.filter(p=>p.id!==scorer.id);if(others.length&&rng.next()<.74){const assist=weightedPick(rng,others,p=>positionWeight(p.position));assist.assists++;homeAssists.push(assist.id);}}
  for(let i=0;i<ag;i++){const scorer=weightedPick(rng,awayPool,p=>positionWeight(p.position)*(1+Math.log10(Math.max(100_000,p.marketValueEur??100_000)/100_000)*.08));scorer.goals++;awayGoals.push(scorer.id);const others=awayPool.filter(p=>p.id!==scorer.id);if(others.length&&rng.next()<.74){const assist=weightedPick(rng,others,p=>positionWeight(p.position));assist.assists++;awayAssists.push(assist.id);}}
  ratePlayers(homePool,hg>ag,hg===ag,homeGoals,homeAssists,rng);ratePlayers(awayPool,ag>hg,hg===ag,awayGoals,awayAssists,rng);applyParallelMatchLoad(league,home,homePool,date,rng);applyParallelMatchLoad(league,away,awayPool,date,rng);updateTable(league,fixture,hg,ag);fixture.played=true;fixture.homeGoals=hg;fixture.awayGoals=ag;fixture.homeShots=Math.max(hg+3,Math.round(expected.home*5.8+rng.integer(2,6)));fixture.awayShots=Math.max(ag+3,Math.round(expected.away*5.8+rng.integer(2,6)));fixture.possessionHome=Math.max(35,Math.min(65,Math.round(50+delta*3+rng.integer(-5,5))));}
function createParallelLeague(baseSeed:string,year:number,id:ProfessionalCompetitionId,names?:string[]):ParallelLeagueState{const def=professionalCompetitionById(id),detail=names?.length?createLeagueFromClubNames(`${baseSeed}:${year}:${id}:parallel`,year,id,names):createLeague(`${baseSeed}:${year}:${id}:parallel`,year,id),teams=detail.clubs.map(club=>{const strength=teamStrength(club.marketValueEur);return{id:club.id,name:club.name,shortName:club.shortName,imageUrl:club.imageUrl,strength,medicalLevel:Math.max(1,Math.min(5,Math.round((strength-50)/10)))}}),players:WorldLeaguePlayer[]=detail.clubs.flatMap(club=>club.players.map(player=>({id:player.id,clubId:club.id,name:player.name,position:player.position,age:player.age,marketValueEur:player.marketValueEur,appearances:0,goals:0,assists:0,ratingTotal:0,ratedMatches:0,averageRating:0,condition:player.condition,fatigue:player.fatigue,injuryDays:player.injuryDays}))),fixtures=detail.fixtures;return{competitionId:id,name:def.name,shortName:def.shortName,country:def.country,season:year,teams,fixtures,standings:teams.map(t=>({clubId:t.id,played:0,won:0,drawn:0,lost:0,goalsFor:0,goalsAgainst:0,points:0})),players,injuryLog:[]};}
function normalizeLoaded(ids:ProfessionalCompetitionId[]|undefined,currentCompetitionId:ProfessionalCompetitionId){const valid=new Set(PROFESSIONAL_COMPETITIONS.map(item=>item.id));const chosen=(ids??PROFESSIONAL_COMPETITIONS.map(item=>item.id)).filter(id=>valid.has(id));return Array.from(new Set<ProfessionalCompetitionId>([currentCompetitionId,...chosen]));}
function buildWorldLeagues(baseSeed:string,year:number,currentCompetitionId:ProfessionalCompetitionId,overrides:Partial<Record<ProfessionalCompetitionId,string[]>>,loadedCompetitionIds:ProfessionalCompetitionId[],managerProfile?:ManagerSetupProfile):WorldLeaguesState{const leagues:Partial<Record<ProfessionalCompetitionId,ParallelLeagueState>>={};for(const comp of PROFESSIONAL_COMPETITIONS)if(comp.id!==currentCompetitionId)leagues[comp.id]=createParallelLeague(baseSeed,year,comp.id,overrides[comp.id]);return{season:year,leagues,loadedCompetitionIds,managerProfile};}
export function createWorldLeagues(baseSeed:string,year:number,currentCompetitionId:ProfessionalCompetitionId,overrides:Partial<Record<ProfessionalCompetitionId,string[]>>={}):WorldLeaguesState{const pending=consumePendingNewGameSetup(),loadedCompetitionIds=normalizeLoaded(pending?.loadedCompetitionIds,currentCompetitionId);return buildWorldLeagues(baseSeed,year,currentCompetitionId,overrides,loadedCompetitionIds,pending?.manager);}
export function processWorldLeaguesThroughDate(value:WorldLeaguesState,baseSeed:string,date:string){const state:WorldLeaguesState=structuredClone(value),active=new Set(normalizeLoaded(state.loadedCompetitionIds,PROFESSIONAL_COMPETITIONS.find(item=>!state.leagues[item.id])?.id??PROFESSIONAL_COMPETITIONS[0].id));for(const league of Object.values(state.leagues)){if(!league||!active.has(league.competitionId))continue;const due=league.fixtures.filter(fixture=>!fixture.played&&fixture.date&&fixture.date<=date).sort((a,b)=>(a.date??"").localeCompare(b.date??"")||a.round-b.round);for(const fixture of due)simulateFixture(league,fixture,`${baseSeed}:${state.season}:parallel`);const played=league.fixtures.filter(f=>f.played&&f.homeGoals!==undefined&&f.awayGoals!==undefined).map(f=>({homeGoals:f.homeGoals!,awayGoals:f.awayGoals!}));if(played.length>=20)league.realismAudit=auditResults(played);if((league.injuryLog?.length??0)>250)league.injuryLog=league.injuryLog!.slice(-250);}state.lastProcessedDate=date;return state;}
export function hydrateWorldLeagues(value:WorldLeaguesState|undefined,baseSeed:string,year:number,currentCompetitionId:ProfessionalCompetitionId,currentDate:string){const loadedCompetitionIds=normalizeLoaded(value?.loadedCompetitionIds,currentCompetitionId),managerProfile=value?.managerProfile,state=value?.season===year?structuredClone(value):buildWorldLeagues(baseSeed,year,currentCompetitionId,{},loadedCompetitionIds,managerProfile);state.loadedCompetitionIds=loadedCompetitionIds;if(managerProfile)state.managerProfile=managerProfile;for(const comp of PROFESSIONAL_COMPETITIONS){if(comp.id===currentCompetitionId){delete state.leagues[comp.id];continue}if(!state.leagues[comp.id])state.leagues[comp.id]=createParallelLeague(baseSeed,year,comp.id);const league=state.leagues[comp.id]!;league.injuryLog??=[];for(const team of league.teams)team.medicalLevel=team.medicalLevel??Math.max(1,Math.min(5,Math.round((team.strength-50)/10)));for(const player of league.players){player.age=player.age??26;player.condition=player.condition??100;player.fatigue=player.fatigue??0;player.injuryDays=player.injuryDays??0;player.lastHealthDate=player.lastHealthDate??state.lastProcessedDate;}}return processWorldLeaguesThroughDate(state,baseSeed,currentDate);}
export function parallelLeagueById(state:WorldLeaguesState,id:ProfessionalCompetitionId){return state.leagues[id];}
export function worldLeagueIsLoaded(state:WorldLeaguesState,id:ProfessionalCompetitionId){return(state.loadedCompetitionIds??PROFESSIONAL_COMPETITIONS.map(item=>item.id)).includes(id);}
export function sortedParallelStandings(standings:LeagueStanding[]){return[...standings].sort((a,b)=>b.points-a.points||(b.goalsFor-b.goalsAgainst)-(a.goalsFor-a.goalsAgainst)||b.goalsFor-a.goalsFor);}
export function parallelTopPlayers(league:ParallelLeagueState,key:"goals"|"assists"|"averageRating",limit=10){return[...league.players].filter(p=>key!=="averageRating"||p.ratedMatches>=2).sort((a,b)=>b[key]-a[key]||b.goals-a.goals).slice(0,limit);}
