/* eslint-disable prefer-const */
import { SeededRng } from "./rng";
import { PROFESSIONAL_COMPETITIONS, type ProfessionalCompetitionId } from "../data/brazil-2026/competitions";
import type { LeagueWorld } from "./league";
import type { MatchResult } from "./match";

export type WorldCompetitionId="CDB"|"LIB"|"SUD"|"FAC"|"EFL"|"CDR"|"CDF"|"UCL"|"UEL"|"UECL";
export type WorldCompetitionKind="Copa nacional"|"Continental";
export type WorldCompetitionFormat="Mata-mata"|"Grupos + mata-mata"|"Liga + mata-mata";
export type WorldStageDefinition={name:string;dates:string[];legs:1|2;kind:"knockout"|"groups"|"league";rule:string};
export type WorldCompetitionDefinition={id:WorldCompetitionId;name:string;shortName:string;country?:string;kind:WorldCompetitionKind;participants:number;roundInterval:number;format:WorldCompetitionFormat;rulesSummary:string;stages:WorldStageDefinition[];leaguePhaseMatches?:number;groupCount?:number;groupSize?:number;entryNote?:string};
export type WorldParticipant={id:string;name:string;shortName:string;country:string;reputation:number;activeClubId?:string};
export type WorldCompetitionMatch={id:string;competitionId:WorldCompetitionId;stage:string;roundDue:number;date:string;home:WorldParticipant;away:WorldParticipant;played:boolean;homeGoals?:number;awayGoals?:number;winnerId?:string;decidedByPenalties?:boolean;leg?:1|2;tieId?:string;group?:string;matchday?:number;tableStage?:boolean};
export type WorldTournamentState={definition:WorldCompetitionDefinition;participants:WorldParticipant[];matches:WorldCompetitionMatch[];currentStage:string;currentStageIndex?:number;directQualifierIds?:string[];championId?:string;completed:boolean};
export type WorldCompetitionsState={formatVersion?:number;season:number;tournaments:WorldTournamentState[];lastProcessedRound?:number;lastProcessedDate?:string;history:Array<{year:number;competitionId:WorldCompetitionId;competitionName:string;championName:string}>;roundDates?:Array<{round:number;date:string}>};

const CDB:WorldCompetitionDefinition={id:"CDB",name:"Copa do Brasil",shortName:"Copa do Brasil",country:"Brasil",kind:"Copa nacional",participants:126,roundInterval:2,format:"Mata-mata",entryNote:"Os 20 clubes da Série A entram na 5ª fase.",rulesSummary:"126 clubes e nove fases. 1ª, 3ª e 4ª fases em jogo único; 2ª fase em ida e volta; da 5ª fase até a semifinal em ida e volta; final em jogo único. Empate nos confrontos eliminatórios é decidido nos pênaltis.",stages:[
 {name:"1ª fase",dates:["2026-02-18"],legs:1,kind:"knockout",rule:"28 clubes • jogo único"},{name:"2ª fase",dates:["2026-02-25","2026-03-04"],legs:2,kind:"knockout",rule:"88 clubes • ida e volta"},{name:"3ª fase",dates:["2026-03-11"],legs:1,kind:"knockout",rule:"48 clubes • jogo único"},{name:"4ª fase",dates:["2026-03-18"],legs:1,kind:"knockout",rule:"24 clubes • jogo único"},{name:"5ª fase",dates:["2026-04-22","2026-05-13"],legs:2,kind:"knockout",rule:"32 clubes • entrada da Série A • ida e volta"},{name:"Oitavas de final",dates:["2026-08-01","2026-08-05"],legs:2,kind:"knockout",rule:"Ida e volta"},{name:"Quartas de final",dates:["2026-08-26","2026-09-02"],legs:2,kind:"knockout",rule:"Ida e volta"},{name:"Semifinal",dates:["2026-10-21","2026-10-28"],legs:2,kind:"knockout",rule:"Ida e volta"},{name:"Final",dates:["2026-12-06"],legs:1,kind:"knockout",rule:"Jogo único"}]};
const LIB:WorldCompetitionDefinition={id:"LIB",name:"CONMEBOL Libertadores",shortName:"Libertadores",kind:"Continental",participants:32,roundInterval:3,format:"Grupos + mata-mata",groupCount:8,groupSize:4,rulesSummary:"32 clubes em oito grupos de quatro, com seis jogos por clube em turno e returno. Os dois primeiros de cada grupo avançam. Oitavas, quartas e semifinais são em ida e volta; a final é em jogo único.",stages:[
 {name:"Fase de grupos",dates:["2026-04-07","2026-04-14","2026-04-28","2026-05-05","2026-05-19","2026-05-26"],legs:1,kind:"groups",rule:"8 grupos de 4 • turno e returno"},{name:"Oitavas de final",dates:["2026-08-12","2026-08-19"],legs:2,kind:"knockout",rule:"Ida e volta"},{name:"Quartas de final",dates:["2026-09-09","2026-09-16"],legs:2,kind:"knockout",rule:"Ida e volta"},{name:"Semifinal",dates:["2026-10-14","2026-10-21"],legs:2,kind:"knockout",rule:"Ida e volta"},{name:"Final",dates:["2026-11-28"],legs:1,kind:"knockout",rule:"Jogo único • Montevidéu"}]};
const SUD:WorldCompetitionDefinition={id:"SUD",name:"CONMEBOL Sudamericana",shortName:"Sul-Americana",kind:"Continental",participants:32,roundInterval:3,format:"Grupos + mata-mata",groupCount:8,groupSize:4,rulesSummary:"32 clubes em oito grupos de quatro, seis jogos por clube. Os líderes avançam direto às oitavas; os segundos disputam play-off em ida e volta contra terceiros da Libertadores. Oitavas a semifinais são em ida e volta; final em jogo único.",stages:[
 {name:"Fase de grupos",dates:["2026-04-07","2026-04-14","2026-04-28","2026-05-05","2026-05-19","2026-05-26"],legs:1,kind:"groups",rule:"8 grupos de 4 • turno e returno"},{name:"Play-off",dates:["2026-07-22","2026-07-29"],legs:2,kind:"knockout",rule:"2º dos grupos × 3º da Libertadores • ida e volta"},{name:"Oitavas de final",dates:["2026-08-12","2026-08-19"],legs:2,kind:"knockout",rule:"Ida e volta"},{name:"Quartas de final",dates:["2026-09-09","2026-09-16"],legs:2,kind:"knockout",rule:"Ida e volta"},{name:"Semifinal",dates:["2026-10-14","2026-10-21"],legs:2,kind:"knockout",rule:"Ida e volta"},{name:"Final",dates:["2026-11-21"],legs:1,kind:"knockout",rule:"Jogo único • Barranquilla"}]};
const FAC:WorldCompetitionDefinition={id:"FAC",name:"FA Cup",shortName:"FA Cup",country:"Inglaterra",kind:"Copa nacional",participants:745,roundInterval:3,format:"Mata-mata",entryNote:"Clubes da Premier League entram na 3ª fase (Third Round Proper).",rulesSummary:"Mata-mata em jogo único, sem replay. Clubes da Premier League e Championship entram na terceira fase principal. Empate após prorrogação é decidido nos pênaltis.",stages:[
 {name:"1ª fase principal",dates:["2026-11-07"],legs:1,kind:"knockout",rule:"Jogo único"},{name:"2ª fase principal",dates:["2026-12-05"],legs:1,kind:"knockout",rule:"Jogo único"},{name:"3ª fase",dates:["2027-01-09"],legs:1,kind:"knockout",rule:"Entrada da Premier League • jogo único"},{name:"4ª fase",dates:["2027-02-13"],legs:1,kind:"knockout",rule:"Jogo único"},{name:"Oitavas de final",dates:["2027-03-06"],legs:1,kind:"knockout",rule:"Jogo único"},{name:"Quartas de final",dates:["2027-04-03"],legs:1,kind:"knockout",rule:"Jogo único"},{name:"Semifinal",dates:["2027-04-24"],legs:1,kind:"knockout",rule:"Jogo único • Wembley"},{name:"Final",dates:["2027-05-22"],legs:1,kind:"knockout",rule:"Jogo único • Wembley"}]};
const EFL:WorldCompetitionDefinition={id:"EFL",name:"EFL Cup (Carabao Cup)",shortName:"Carabao Cup",country:"Inglaterra",kind:"Copa nacional",participants:92,roundInterval:2,format:"Mata-mata",entryNote:"Clubes da Premier League fora das competições UEFA entram na 2ª fase; os nove clubes ingleses em torneios UEFA entram na 3ª.",rulesSummary:"92 clubes. Mata-mata em jogo único até as quartas. As semifinais são em ida e volta e a final é em jogo único.",stages:[
 {name:"1ª fase",dates:["2026-08-08"],legs:1,kind:"knockout",rule:"Jogo único • regionalização Norte/Sul"},{name:"2ª fase",dates:["2026-08-26"],legs:1,kind:"knockout",rule:"Entrada de clubes da Premier fora da UEFA • jogo único"},{name:"3ª fase",dates:["2026-09-09","2026-09-16"],legs:1,kind:"knockout",rule:"Entrada dos clubes ingleses em competições UEFA • jogo único"},{name:"Oitavas de final",dates:["2026-10-28"],legs:1,kind:"knockout",rule:"Jogo único"},{name:"Quartas de final",dates:["2026-12-16"],legs:1,kind:"knockout",rule:"Jogo único"},{name:"Semifinal",dates:["2027-01-13","2027-02-03"],legs:2,kind:"knockout",rule:"Ida e volta"},{name:"Final",dates:["2027-03-21"],legs:1,kind:"knockout",rule:"Jogo único • Wembley"}]};
const CDR:WorldCompetitionDefinition={id:"CDR",name:"Copa del Rey",shortName:"Copa del Rey",country:"Espanha",kind:"Copa nacional",participants:116,roundInterval:3,format:"Mata-mata",rulesSummary:"Eliminatórias em jogo único até as quartas de final, com mando do clube de divisão inferior quando aplicável. As semifinais são em ida e volta; a final é em jogo único.",stages:[
 {name:"1ª fase",dates:["2026-10-28"],legs:1,kind:"knockout",rule:"Jogo único"},{name:"2ª fase",dates:["2026-12-02"],legs:1,kind:"knockout",rule:"Jogo único"},{name:"32 avos",dates:["2026-12-16"],legs:1,kind:"knockout",rule:"Jogo único"},{name:"Oitavas de final",dates:["2027-01-06"],legs:1,kind:"knockout",rule:"Jogo único"},{name:"Quartas de final",dates:["2027-01-13"],legs:1,kind:"knockout",rule:"Jogo único"},{name:"Semifinal",dates:["2027-02-10","2027-03-03"],legs:2,kind:"knockout",rule:"Ida e volta"},{name:"Final",dates:["2027-04-24"],legs:1,kind:"knockout",rule:"Jogo único"}]};
const CDF:WorldCompetitionDefinition={id:"CDF",name:"Coupe de France",shortName:"Coupe de France",country:"França",kind:"Copa nacional",participants:7000,roundInterval:3,format:"Mata-mata",entryNote:"Clubes da Ligue 1 entram nos 32es de finale (64 clubes).",rulesSummary:"Grande copa nacional francesa em mata-mata de jogo único. A Ligue 1 entra na fase de 64 clubes; todas as eliminatórias, incluindo semifinal e final, são decididas em uma partida.",stages:[
 {name:"7ª rodada",dates:["2026-11-14"],legs:1,kind:"knockout",rule:"Entrada da Ligue 2 • jogo único"},{name:"8ª rodada",dates:["2026-11-28"],legs:1,kind:"knockout",rule:"Jogo único"},{name:"32es de finale",dates:["2026-12-20"],legs:1,kind:"knockout",rule:"Entrada da Ligue 1 • 64 clubes • jogo único"},{name:"16es de finale",dates:["2027-01-09"],legs:1,kind:"knockout",rule:"Jogo único"},{name:"Oitavas de final",dates:["2027-02-03"],legs:1,kind:"knockout",rule:"Jogo único"},{name:"Quartas de final",dates:["2027-03-03"],legs:1,kind:"knockout",rule:"Jogo único"},{name:"Semifinal",dates:["2027-04-21"],legs:1,kind:"knockout",rule:"Jogo único"},{name:"Final",dates:["2027-05-15"],legs:1,kind:"knockout",rule:"Jogo único"}]};
function uefa(id:"UCL"|"UEL"|"UECL",name:string,shortName:string,matches:number,leagueDates:string[],knockoutDates:Array<[string,string[]]>):WorldCompetitionDefinition{return{id,name,shortName,kind:"Continental",participants:36,roundInterval:2,format:"Liga + mata-mata",leaguePhaseMatches:matches,rulesSummary:`36 clubes em uma liga única; cada clube faz ${matches} jogos contra adversários diferentes. Os oito primeiros avançam direto às oitavas; do 9º ao 24º disputam play-off em ida e volta. Do play-off às semifinais os confrontos são em ida e volta; final em jogo único.`,stages:[{name:"Fase de liga",dates:leagueDates,legs:1,kind:"league",rule:`36 clubes • ${matches} jogos por clube`},...knockoutDates.map(([stage,dates])=>({name:stage,dates,legs:(stage==="Final"?1:2) as 1|2,kind:"knockout" as const,rule:stage==="Final"?"Jogo único":"Ida e volta"}))]};}
const UCL=uefa("UCL","UEFA Champions League","Champions League",8,["2026-09-08","2026-10-13","2026-10-20","2026-11-03","2026-11-24","2026-12-08","2027-01-19","2027-01-27"],[["Play-off",["2027-02-17","2027-02-24"]],["Oitavas de final",["2027-03-10","2027-03-17"]],["Quartas de final",["2027-04-07","2027-04-14"]],["Semifinal",["2027-04-28","2027-05-05"]],["Final",["2027-06-05"]]]);
const UEL=uefa("UEL","UEFA Europa League","Europa League",8,["2026-09-16","2026-10-15","2026-10-22","2026-11-05","2026-11-26","2026-12-10","2027-01-21","2027-01-28"],[["Play-off",["2027-02-18","2027-02-25"]],["Oitavas de final",["2027-03-11","2027-03-18"]],["Quartas de final",["2027-04-08","2027-04-15"]],["Semifinal",["2027-04-29","2027-05-06"]],["Final",["2027-05-26"]]]);
const UECL=uefa("UECL","UEFA Conference League","Conference League",6,["2026-10-15","2026-10-22","2026-11-05","2026-11-26","2026-12-10","2026-12-17"],[["Play-off",["2027-02-18","2027-02-25"]],["Oitavas de final",["2027-03-11","2027-03-18"]],["Quartas de final",["2027-04-08","2027-04-15"]],["Semifinal",["2027-04-29","2027-05-06"]],["Final",["2027-06-02"]]]);
export const WORLD_COMPETITIONS:WorldCompetitionDefinition[]=[CDB,LIB,SUD,FAC,EFL,CDR,CDF,UCL,UEL,UECL];

const LIB_GROUPS:Record<string,string[]>={A:["Flamengo","Estudiantes","Cusco","Independiente Medellín"],B:["Nacional","Universitario","Coquimbo Unido","Tolima"],C:["Fluminense","Bolívar","Deportivo La Guaira","Independiente Rivadavia"],D:["Boca Juniors","Cruzeiro","Universidad Católica","Barcelona SC"],E:["Platense","Corinthians","Santa Fe","Peñarol"],F:["Junior","Palmeiras","Sporting Cristal","Cerro Porteño"],G:["Always Ready","LDU Quito","Mirassol","Lanús"],H:["UCV FC","Libertad","Rosario Central","Independiente del Valle"]};
const SUD_GROUPS:Record<string,string[]>={A:["América de Cali","Tigre","Macará","Alianza Atlético"],B:["Atlético Mineiro","Cienciano","Puerto Cabello","Juventud"],C:["O’Higgins","Millonarios","Boston River","São Paulo"],D:["Deportivo Cuenca","Santos","Recoleta","San Lorenzo"],E:["Independiente Petrolero","Racing Club","Botafogo","Caracas"],F:["Deportivo Riestra","Palestino","Montevideo City Torque","Grêmio"],G:["Barracas Central","Vasco da Gama","Audax Italiano","Olimpia"],H:["Blooming","River Plate","Red Bull Bragantino","Carabobo"]};
const UEFA_TEAMS:Record<"UCL"|"UEL"|"UECL",string[]>={
 UCL:["AEK Athens","Arsenal","Aston Villa","Atlético de Madrid","Barcelona","Bayern München","Bodø/Glimt","Borussia Dortmund","Club Brugge","Como","Fenerbahçe","Feyenoord","Galatasaray","Inter","LASK","Leipzig","Lens","Lille","Liverpool","Manchester City","Manchester United","Napoli","Paris Saint-Germain","Porto","PSV","Real Betis","Real Madrid","Roma","Sabah","Shakhtar","Slavia Praha","Slovan Bratislava","Sporting CP","Stuttgart","Viking","Villarreal"],
 UEL:["Bayer Leverkusen","Benfica","Juventus","Milan","Lyon","AZ","Olympiacos","Real Sociedad","Marseille","Ferencváros","Viktoria Plzeň","Union SG","Dinamo Zagreb","Salzburg","Celtic","Sparta Praha","Rennes","Anderlecht","Sturm Graz","Lech Poznań","Crystal Palace","Bournemouth","Sunderland","Celje","Jagiellonia","Omonia","Celta","Hoffenheim","Beşiktaş","Torreense","Hapoel Be’er Sheva","NEC","OFI Crete","Lillestrøm","Levski Sofia","Ararat-Armenia"],
 UECL:["Atalanta","Braga","Ajax","Freiburg","Monaco","Copenhagen","Midtjylland","Crvena Zvezda","Gent","Panathinaikos","Pafos","Brighton","Lugano","Getafe","KuPS","Twente","Lincoln Red Imps","Borac","Sint-Truidense","Brann","Hearts","Kairat","Trabzonspor","U Craiova","Riga","Hajduk Split","Jablonec","Nordsjælland","Aarhus","Inter Escaldes","Thun","CSKA Sofia","Kauno Žalgiris","Mjällby","Iberia Tbilisi","Egnatia"]
};
const addDays=(iso:string,days:number)=>{const d=new Date(`${iso}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)};
function seasonDate(template:string,year:number){const sourceYear=Number(template.slice(0,4));return`${year+(sourceYear-2026)}${template.slice(4)}`;}
function repFromValue(value:number){if(value>=1_000_000_000)return 95;if(value>=600_000_000)return 90;if(value>=300_000_000)return 84;if(value>=150_000_000)return 78;if(value>=70_000_000)return 72;if(value>=30_000_000)return 66;if(value>=12_000_000)return 59;return 52;}
function sourceCountry(id:ProfessionalCompetitionId){return id.startsWith("BRA")?"Brasil":id==="ENG1"?"Inglaterra":id==="ESP1"?"Espanha":"França";}
function normalize(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\b(fc|afc|cf|ec|sc|saf)\b/g," ").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();}
const NAME_EQUIV:Record<string,string>={"man city":"manchester city","man utd":"manchester united","paris":"paris saint germain","atleti":"atletico de madrid","vasco":"vasco da gama","atletico mg":"atletico mineiro","red bull bragantino sp":"red bull bragantino","sao paulo futebol clube":"sao paulo"};
function equivalent(a:string,b:string){let x=NAME_EQUIV[normalize(a)]??normalize(a),y=NAME_EQUIV[normalize(b)]??normalize(b);return x===y||x.includes(y)||y.includes(x);}
function allParticipants(activeCompetitionId:ProfessionalCompetitionId,league:LeagueWorld){const active=league.clubs.map(club=>({id:`active:${club.id}`,name:club.name,shortName:club.shortName,country:sourceCountry(activeCompetitionId),reputation:club.reputation,activeClubId:club.id}));const external=PROFESSIONAL_COMPETITIONS.flatMap(comp=>comp.id===activeCompetitionId?[]:comp.clubs.map(club=>({id:`ext:${comp.id}:${club.transfermarktId}`,name:club.name,shortName:club.shortName,country:comp.country,reputation:repFromValue(club.marketValueEur)})));return[...active,...external];}
function virtual(name:string,country:string,idSuffix:string):WorldParticipant{return{id:`virtual-${idSuffix}`,name,shortName:name.split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase(),country,reputation:68};}
function fromName(name:string,pool:WorldParticipant[],country="Internacional"){return pool.find(p=>equivalent(p.name,name))??virtual(name,country,normalize(name).replace(/\s/g,"-")||"club");}
function uniqueParticipants(items:WorldParticipant[]){const out:WorldParticipant[]=[];for(const p of items)if(!out.some(x=>x.id===p.id))out.push(p);return out;}
function fill(pool:WorldParticipant[],country:string,count:number,prefix:string){const base=pool.filter(p=>p.country===country),out=uniqueParticipants(base).slice(0,count);let i=1;while(out.length<count){out.push(virtual(`${prefix} ${String(i).padStart(2,"0")}`,country,`${prefix}-${i}`));i++;}return out;}
function roundDates(league:LeagueWorld){return league.fixtures.filter(f=>Boolean(f.date)).map(f=>({round:f.round,date:f.date!})).sort((a,b)=>a.date.localeCompare(b.date));}
function dueForDate(state:WorldCompetitionsState,date:string){const dates=state.roundDates??[];return dates.find(item=>item.date>=date)?.round??Math.max(1,...dates.map(item=>item.round));}
function shuffle<T>(items:T[],rng:SeededRng){const out=[...items];for(let i=out.length-1;i>0;i--){const j=rng.integer(0,i);[out[i],out[j]]=[out[j],out[i]];}return out;}
function pairings(items:WorldParticipant[],rounds:number){const teams=[...items];if(teams.length%2)teams.push(virtual("BYE","—","bye"));const fixed=teams[0],rotating=teams.slice(1),all:Array<Array<[WorldParticipant,WorldParticipant]>>=[];for(let r=0;r<rounds;r++){const row=[fixed,...rotating],pairs:Array<[WorldParticipant,WorldParticipant]>=[];for(let i=0;i<row.length/2;i++){const a=row[i],b=row[row.length-1-i];if(!a.id.includes("bye")&&!b.id.includes("bye"))pairs.push(r%2?[b,a]:[a,b]);}all.push(pairs);rotating.unshift(rotating.pop()!);}return all;}
function groupMatches(def:WorldCompetitionDefinition,groups:Record<string,string[]>,pool:WorldParticipant[],state:WorldCompetitionsState,seed:string){const stage=def.stages[0],matches:WorldCompetitionMatch[]=[],participants:WorldParticipant[]=[];for(const [group,names] of Object.entries(groups)){const teams=names.map(name=>fromName(name,pool,def.id==="LIB"||def.id==="SUD"?"CONMEBOL":"Internacional"));participants.push(...teams);const rounds=pairings(teams,6);rounds.forEach((pairs,md)=>pairs.forEach(([home,away],index)=>{const date=seasonDate(stage.dates[md],state.season);matches.push({id:`${def.id}:GROUP-${group}:MD${md+1}:${index}`,competitionId:def.id,stage:stage.name,roundDue:dueForDate(state,date),date,home,away,played:false,group,matchday:md+1,tableStage:true});}));}return{participants:uniqueParticipants(participants),matches};}
function leagueMatches(def:WorldCompetitionDefinition,names:string[],pool:WorldParticipant[],state:WorldCompetitionsState,seed:string){const rng=new SeededRng(`${seed}:${def.id}:league`),participants=shuffle(names.map(name=>fromName(name,pool,"Europa")),rng),rounds=pairings(participants,def.leaguePhaseMatches??8),matches:WorldCompetitionMatch[]=[];rounds.forEach((pairs,md)=>pairs.forEach(([home,away],index)=>{const date=seasonDate(def.stages[0].dates[md],state.season);matches.push({id:`${def.id}:LEAGUE:MD${md+1}:${index}`,competitionId:def.id,stage:def.stages[0].name,roundDue:dueForDate(state,date),date,home,away,played:false,matchday:md+1,tableStage:true});}));return{participants,matches};}
function knockoutMatches(t:WorldTournamentState,participants:WorldParticipant[],stageIndex:number,state:WorldCompetitionsState,seed:string){const stage=t.definition.stages[stageIndex],rng=new SeededRng(`${seed}:${t.definition.id}:${stage.name}:${state.season}`),ordered=shuffle(participants,rng),matches:WorldCompetitionMatch[]=[];for(let i=0;i+1<ordered.length;i+=2){const home=ordered[i],away=ordered[i+1],tieId=`${t.definition.id}:${stageIndex}:${i/2}`;for(let leg=0;leg<stage.legs;leg++){const date=seasonDate(stage.dates[Math.min(leg,stage.dates.length-1)],state.season),firstHome=leg===0?home:away,firstAway=leg===0?away:home;matches.push({id:`${tieId}:L${leg+1}`,competitionId:t.definition.id,stage:stage.name,roundDue:dueForDate(state,date),date,home:firstHome,away:firstAway,played:false,leg:(leg+1) as 1|2,tieId});}}return matches;}
function table(matches:WorldCompetitionMatch[],participants:WorldParticipant[]){const rows=new Map(participants.map(p=>[p.id,{p,pts:0,gf:0,ga:0,w:0}]));for(const m of matches.filter(x=>x.played)){const h=rows.get(m.home.id),a=rows.get(m.away.id);if(!h||!a)continue;const hg=m.homeGoals??0,ag=m.awayGoals??0;h.gf+=hg;h.ga+=ag;a.gf+=ag;a.ga+=hg;if(hg>ag){h.pts+=3;h.w++;}else if(ag>hg){a.pts+=3;a.w++;}else{h.pts++;a.pts++;}}return[...rows.values()].sort((a,b)=>b.pts-a.pts||(b.gf-b.ga)-(a.gf-a.ga)||b.gf-a.gf||b.w-a.w||b.p.reputation-a.p.reputation);}
function groupQualifiers(t:WorldTournamentState,matches:WorldCompetitionMatch[],take:number){const result:WorldParticipant[]=[];for(const group of [...new Set(matches.map(m=>m.group).filter(Boolean))] as string[]){const gm=matches.filter(m=>m.group===group),ids=new Set(gm.flatMap(m=>[m.home.id,m.away.id])),participants=t.participants.filter(p=>ids.has(p.id));result.push(...table(gm,participants).slice(0,take).map(r=>r.p));}return result;}
function resolveKnockoutWinners(matches:WorldCompetitionMatch[],seed:string){const ties=new Map<string,WorldCompetitionMatch[]>();for(const m of matches){const key=m.tieId??m.id;ties.set(key,[...(ties.get(key)??[]),m]);}const winners:WorldParticipant[]=[];for(const [key,legs] of ties){const first=legs[0],ids=[first.home.id,first.away.id],score=new Map(ids.map(id=>[id,0]));for(const leg of legs){score.set(leg.home.id,(score.get(leg.home.id)??0)+(leg.homeGoals??0));score.set(leg.away.id,(score.get(leg.away.id)??0)+(leg.awayGoals??0));}let winnerId=ids.sort((a,b)=>(score.get(b)??0)-(score.get(a)??0))[0];if((score.get(ids[0])??0)===(score.get(ids[1])??0)){const rng=new SeededRng(`${seed}:${key}:penalties`);winnerId=rng.next()<.5?ids[0]:ids[1];const last=legs[legs.length-1];last.decidedByPenalties=true;}for(const leg of legs)leg.winnerId=winnerId;const sample=legs.find(l=>l.home.id===winnerId)?.home??legs.find(l=>l.away.id===winnerId)?.away;if(sample)winners.push(sample);}return winners;}
function simulate(match:WorldCompetitionMatch,rng:SeededRng){const delta=(match.home.reputation-match.away.reputation)*.035+.2;let hg=Math.max(0,rng.integer(0,2)+(delta>1?1:0)),ag=Math.max(0,rng.integer(0,2)+(delta<-1?1:0));match.homeGoals=hg;match.awayGoals=ag;match.played=true;if(!match.tableStage&&(match.leg??1)===1&&!match.tieId&&hg===ag){match.decidedByPenalties=true;match.winnerId=rng.next()<.5?match.home.id:match.away.id;}else if(!match.tableStage&&hg!==ag)match.winnerId=hg>ag?match.home.id:match.away.id;}
function progressTournament(t:WorldTournamentState,state:WorldCompetitionsState,seed:string){if(t.completed)return;const index=t.currentStageIndex??0,stage=t.definition.stages[index],stageMatches=t.matches.filter(m=>m.stage===t.currentStage);if(!stageMatches.length||!stageMatches.every(m=>m.played))return;
 let nextParticipants:WorldParticipant[]=[];
 if(stage.kind==="groups"){
  if(t.definition.id==="LIB")nextParticipants=groupQualifiers(t,stageMatches,2);
  else{const leaders=groupQualifiers(t,stageMatches,1),runners:WorldParticipant[]=[];for(const group of [...new Set(stageMatches.map(m=>m.group).filter(Boolean))] as string[]){const gm=stageMatches.filter(m=>m.group===group),ids=new Set(gm.flatMap(m=>[m.home.id,m.away.id])),participants=t.participants.filter(p=>ids.has(p.id));const second=table(gm,participants)[1]?.p;if(second)runners.push(second);}t.directQualifierIds=leaders.map(p=>p.id);nextParticipants=[...runners,...Array.from({length:8},(_,i)=>virtual(`3º Libertadores Grupo ${String.fromCharCode(65+i)}`,"CONMEBOL",`lib3-${i}`))];}
 }else if(stage.kind==="league"){
  const ranking=table(stageMatches,t.participants);t.directQualifierIds=ranking.slice(0,8).map(r=>r.p.id);nextParticipants=ranking.slice(8,24).map(r=>r.p);
 }else nextParticipants=resolveKnockoutWinners(stageMatches,`${seed}:${t.definition.id}:${stage.name}`);
 if(nextParticipants.length===1&&index===t.definition.stages.length-1){t.completed=true;t.championId=nextParticipants[0].id;state.history.unshift({year:state.season,competitionId:t.definition.id,competitionName:t.definition.name,championName:nextParticipants[0].name});return;}
 const nextIndex=index+1;if(nextIndex>=t.definition.stages.length){if(nextParticipants.length===1){t.completed=true;t.championId=nextParticipants[0].id;}return;}
 if(stage.name==="Play-off"&&t.directQualifierIds?.length){const direct=t.participants.filter(p=>t.directQualifierIds!.includes(p.id));nextParticipants=[...direct,...nextParticipants];t.directQualifierIds=undefined;}
 t.currentStageIndex=nextIndex;t.currentStage=t.definition.stages[nextIndex].name;t.matches.push(...knockoutMatches(t,nextParticipants,nextIndex,state,seed));
}
function domesticStartIndex(def:WorldCompetitionDefinition){if(def.id==="CDB")return 4;if(def.id==="FAC")return 2;if(def.id==="EFL")return 2;if(def.id==="CDR")return 2;if(def.id==="CDF")return 2;return 0;}
function domesticFieldSize(def:WorldCompetitionDefinition){if(def.id==="FAC"||def.id==="CDR"||def.id==="CDF")return 64;return 32;}
function createTournament(def:WorldCompetitionDefinition,pool:WorldParticipant[],state:WorldCompetitionsState,activeCountry:string,seed:string):WorldTournamentState{
 if(def.id==="LIB"||def.id==="SUD"){const grouped=groupMatches(def,def.id==="LIB"?LIB_GROUPS:SUD_GROUPS,pool,state,seed);return{definition:def,participants:grouped.participants,matches:grouped.matches,currentStage:def.stages[0].name,currentStageIndex:0,completed:false};}
 if(def.id==="UCL"||def.id==="UEL"||def.id==="UECL"){const league=leagueMatches(def,UEFA_TEAMS[def.id],pool,state,seed);return{definition:def,participants:league.participants,matches:league.matches,currentStage:def.stages[0].name,currentStageIndex:0,completed:false};}
 const start=domesticStartIndex(def),country=def.country!,participants=fill(pool,country,domesticFieldSize(def),def.shortName),t:WorldTournamentState={definition:def,participants,matches:[],currentStage:def.stages[start].name,currentStageIndex:start,completed:false};t.matches=knockoutMatches(t,participants,start,state,seed);return t;
}
export function createWorldCompetitions(activeCompetitionId:ProfessionalCompetitionId,league:LeagueWorld,year:number,seed:string):WorldCompetitionsState{const state:WorldCompetitionsState={formatVersion:3,season:year,tournaments:[],history:[],roundDates:roundDates(league)},pool=allParticipants(activeCompetitionId,league),country=sourceCountry(activeCompetitionId);state.tournaments=WORLD_COMPETITIONS.map(def=>createTournament(def,pool,state,country,seed));return state;}
export function hydrateWorldCompetitions(state:WorldCompetitionsState|undefined,activeCompetitionId:ProfessionalCompetitionId,league:LeagueWorld,year:number,seed:string){if(!state||state.formatVersion!==3){const fresh=createWorldCompetitions(activeCompetitionId,league,year,seed);if(state?.history)fresh.history=[...state.history].slice(0,80);return fresh;}return{...state,roundDates:state.roundDates?.length?state.roundDates:roundDates(league),tournaments:state.tournaments.map(t=>({...t,definition:WORLD_COMPETITIONS.find(d=>d.id===t.definition.id)??t.definition}))};}
function processMatches(next:WorldCompetitionsState,predicate:(m:WorldCompetitionMatch)=>boolean,seed:string,userClubId?:string){const rng=new SeededRng(seed);for(const tournament of next.tournaments){if(tournament.completed)continue;for(const match of tournament.matches.filter(m=>!m.played&&predicate(m))){const userInvolved=userClubId&&(match.home.activeClubId===userClubId||match.away.activeClubId===userClubId);if(!userInvolved)simulate(match,rng);}progressTournament(tournament,next,seed);}return next;}
export function processWorldCompetitions(state:WorldCompetitionsState,round:number,seed:string,userClubId?:string){if(state.lastProcessedRound===round)return state;const next=structuredClone(state);next.lastProcessedRound=round;return processMatches(next,m=>m.roundDue<=round,`${seed}:world-cups:r${round}`,userClubId);}
export function processWorldCompetitionsByDate(state:WorldCompetitionsState,date:string,seed:string,userClubId?:string){if(state.lastProcessedDate===date)return state;const next=structuredClone(state);next.lastProcessedDate=date;return processMatches(next,m=>m.date<=date,`${seed}:world-cups:${date}`,userClubId);}
export function playWorldCompetitionMatch(state:WorldCompetitionsState,matchId:string,result:MatchResult,round:number,seed:string){const next=structuredClone(state);for(const tournament of next.tournaments){const match=tournament.matches.find(m=>m.id===matchId);if(!match)continue;match.homeGoals=result.homeGoals;match.awayGoals=result.awayGoals;match.played=true;if(!match.tableStage&&(match.leg??1)===1&&tournament.definition.stages[tournament.currentStageIndex??0].legs===1){if(result.homeGoals===result.awayGoals){const rng=new SeededRng(`${seed}:penalties:${match.id}`);match.decidedByPenalties=true;match.winnerId=rng.next()<.5?match.home.id:match.away.id;}else match.winnerId=result.homeGoals>result.awayGoals?match.home.id:match.away.id;}progressTournament(tournament,next,seed);break;}return next;}
export function competitionPrizeEur(id:WorldCompetitionId,stage:string,won:boolean){const continental=["LIB","UCL","UEL","UECL"].includes(id),base=continental?1_800_000:450_000,mult=stage==="Final"?6:stage==="Semifinal"?3:stage==="Quartas de final"?2:1;return Math.round(base*mult*(won?1:.35));}
export function prepareWorldCompetitionsNextSeason(state:WorldCompetitionsState,activeCompetitionId:ProfessionalCompetitionId,league:LeagueWorld,year:number,seed:string){const fresh=createWorldCompetitions(activeCompetitionId,league,year,seed);fresh.history=[...state.history,...fresh.history].slice(0,80);return fresh;}
export function userWorldCompetitionMatches(state:WorldCompetitionsState,clubId:string){return state.tournaments.flatMap(t=>t.matches.filter(m=>m.home.activeClubId===clubId||m.away.activeClubId===clubId).map(match=>({tournament:t,match}))).sort((a,b)=>a.match.date.localeCompare(b.match.date));}
export function userWorldCompetitionMatchByDate(state:WorldCompetitionsState,clubId:string,date:string){return userWorldCompetitionMatches(state,clubId).find(item=>!item.match.played&&item.match.date===date);}
export function worldCompetitionMatchById(state:WorldCompetitionsState,id:string){for(const tournament of state.tournaments){const match=tournament.matches.find(m=>m.id===id);if(match)return{tournament,match};}return undefined;}
export function worldCompetitionCalendar(year:number){return WORLD_COMPETITIONS.flatMap(def=>def.stages.flatMap(stage=>stage.dates.map(date=>({competitionId:def.id,competition:def.shortName,stage:stage.name,date:seasonDate(date,year),rule:stage.rule,format:def.format,kind:def.kind})))).sort((a,b)=>a.date.localeCompare(b.date));}
