import { SeededRng } from "./rng";
import { createLeagueFromClubNames, type LeagueFixture, type LeagueStanding } from "./league";
import { PROFESSIONAL_COMPETITIONS, professionalCompetitionById, type ProfessionalCompetitionId } from "../data/brazil-2026/competitions";
import { consumePendingNewGameSetup, type ManagerSetupProfile } from "./new-game-setup";

export type WorldLeagueTeam={id:string;name:string;shortName:string;imageUrl:string;strength:number};
export type WorldLeaguePlayer={id:string;clubId:string;name:string;position:string;marketValueEur:number|null;appearances:number;goals:number;assists:number;ratingTotal:number;ratedMatches:number;averageRating:number};
export type ParallelLeagueState={competitionId:ProfessionalCompetitionId;name:string;shortName:string;country:string;season:number;teams:WorldLeagueTeam[];fixtures:LeagueFixture[];standings:LeagueStanding[];players:WorldLeaguePlayer[]};
export type WorldLeaguesState={season:number;leagues:Partial<Record<ProfessionalCompetitionId,ParallelLeagueState>>;lastProcessedDate?:string;loadedCompetitionIds?:ProfessionalCompetitionId[];managerProfile?:ManagerSetupProfile};

const teamStrength=(market:number)=>Math.max(52,Math.min(94,56+Math.log10(Math.max(1_000_000,market)/1_000_000)*11));
const positionWeight=(position:string)=>position==="ATA"?6:["PE","PD"].includes(position)?5:position==="MEI"?4:["MC","VOL"].includes(position)?3:["LD","LE"].includes(position)?2.2:position==="ZAG"?1.2:.35;
function weightedPick<T>(rng:SeededRng,items:T[],weight:(item:T)=>number){const total=items.reduce((sum,item)=>sum+Math.max(.05,weight(item)),0);let roll=rng.next()*total;for(const item of items){roll-=Math.max(.05,weight(item));if(roll<=0)return item;}return items[items.length-1];}
function goals(rng:SeededRng,lambda:number){let value=0;const attempts=6,p=Math.max(.04,Math.min(.58,lambda/attempts));for(let i=0;i<attempts;i++)if(rng.next()<p)value++;return value;}
function standingFor(league:ParallelLeagueState,id:string){return league.standings.find(item=>item.clubId===id)!;}
function updateTable(league:ParallelLeagueState,fixture:LeagueFixture,hg:number,ag:number){const h=standingFor(league,fixture.homeClubId),a=standingFor(league,fixture.awayClubId);h.played++;a.played++;h.goalsFor+=hg;h.goalsAgainst+=ag;a.goalsFor+=ag;a.goalsAgainst+=hg;if(hg>ag){h.won++;a.lost++;h.points+=3}else if(ag>hg){a.won++;h.lost++;a.points+=3}else{h.drawn++;a.drawn++;h.points++;a.points++;}}
function ratePlayers(players:WorldLeaguePlayer[],won:boolean,draw:boolean,goalIds:string[],assistIds:string[],rng:SeededRng){for(const player of players){player.appearances++;let rating=6.25+(won?.35:draw?.08:-.18)+rng.integer(-18,18)/100+goalIds.filter(id=>id===player.id).length*.75+assistIds.filter(id=>id===player.id).length*.45;rating=Math.max(4.8,Math.min(9.8,rating));player.ratingTotal+=rating;player.ratedMatches++;player.averageRating=Math.round(player.ratingTotal/player.ratedMatches*100)/100;}}
function simulateFixture(league:ParallelLeagueState,fixture:LeagueFixture,seed:string){const home=league.teams.find(t=>t.id===fixture.homeClubId)!,away=league.teams.find(t=>t.id===fixture.awayClubId)!,rng=new SeededRng(`${seed}:${league.competitionId}:${fixture.id}`),delta=(home.strength-away.strength)/13,hg=goals(rng,1.48+delta*.32),ag=goals(rng,1.18-delta*.27),homePool=league.players.filter(p=>p.clubId===home.id).sort((a,b)=>(b.marketValueEur??0)-(a.marketValueEur??0)).slice(0,11),awayPool=league.players.filter(p=>p.clubId===away.id).sort((a,b)=>(b.marketValueEur??0)-(a.marketValueEur??0)).slice(0,11),homeGoals:string[]=[],awayGoals:string[]=[],homeAssists:string[]=[],awayAssists:string[]=[];
  for(let i=0;i<hg;i++){const scorer=weightedPick(rng,homePool,p=>positionWeight(p.position)*(1+Math.log10(Math.max(100_000,p.marketValueEur??100_000)/100_000)*.08));scorer.goals++;homeGoals.push(scorer.id);const others=homePool.filter(p=>p.id!==scorer.id);if(others.length&&rng.next()<.74){const assist=weightedPick(rng,others,p=>positionWeight(p.position));assist.assists++;homeAssists.push(assist.id);}}
  for(let i=0;i<ag;i++){const scorer=weightedPick(rng,awayPool,p=>positionWeight(p.position)*(1+Math.log10(Math.max(100_000,p.marketValueEur??100_000)/100_000)*.08));scorer.goals++;awayGoals.push(scorer.id);const others=awayPool.filter(p=>p.id!==scorer.id);if(others.length&&rng.next()<.74){const assist=weightedPick(rng,others,p=>positionWeight(p.position));assist.assists++;awayAssists.push(assist.id);}}
  ratePlayers(homePool,hg>ag,hg===ag,homeGoals,homeAssists,rng);ratePlayers(awayPool,ag>hg,hg===ag,awayGoals,awayAssists,rng);updateTable(league,fixture,hg,ag);fixture.played=true;fixture.homeGoals=hg;fixture.awayGoals=ag;fixture.homeShots=Math.max(hg+3,rng.integer(7,17));fixture.awayShots=Math.max(ag+3,rng.integer(6,15));fixture.possessionHome=Math.max(35,Math.min(65,Math.round(50+delta*3+rng.integer(-6,6))));}
function createParallelLeague(baseSeed:string,year:number,id:ProfessionalCompetitionId,names?:string[]):ParallelLeagueState{const def=professionalCompetitionById(id),detail=createLeagueFromClubNames(`${baseSeed}:${year}:${id}:parallel`,year,id,names?.length?names:def.clubs.map(c=>c.name)),teams=detail.clubs.map(club=>({id:club.id,name:club.name,shortName:club.shortName,imageUrl:club.imageUrl,strength:teamStrength(club.marketValueEur)})),players:WorldLeaguePlayer[]=detail.clubs.flatMap(club=>club.players.map(player=>({id:player.id,clubId:club.id,name:player.name,position:player.position,marketValueEur:player.marketValueEur,appearances:0,goals:0,assists:0,ratingTotal:0,ratedMatches:0,averageRating:0}))),fixtures=detail.fixtures;return{competitionId:id,name:def.name,shortName:def.shortName,country:def.country,season:year,teams,fixtures,standings:teams.map(t=>({clubId:t.id,played:0,won:0,drawn:0,lost:0,goalsFor:0,goalsAgainst:0,points:0})),players};}
function normalizeLoaded(ids:ProfessionalCompetitionId[]|undefined,currentCompetitionId:ProfessionalCompetitionId){const valid=new Set(PROFESSIONAL_COMPETITIONS.map(item=>item.id));const chosen=(ids??PROFESSIONAL_COMPETITIONS.map(item=>item.id)).filter(id=>valid.has(id));return Array.from(new Set<ProfessionalCompetitionId>([currentCompetitionId,...chosen]));}
function buildWorldLeagues(baseSeed:string,year:number,currentCompetitionId:ProfessionalCompetitionId,overrides:Partial<Record<ProfessionalCompetitionId,string[]>>,loadedCompetitionIds:ProfessionalCompetitionId[],managerProfile?:ManagerSetupProfile):WorldLeaguesState{const leagues:Partial<Record<ProfessionalCompetitionId,ParallelLeagueState>>={};for(const comp of PROFESSIONAL_COMPETITIONS)if(comp.id!==currentCompetitionId)leagues[comp.id]=createParallelLeague(baseSeed,year,comp.id,overrides[comp.id]);return{season:year,leagues,loadedCompetitionIds,managerProfile};}
export function createWorldLeagues(baseSeed:string,year:number,currentCompetitionId:ProfessionalCompetitionId,overrides:Partial<Record<ProfessionalCompetitionId,string[]>>={}):WorldLeaguesState{const pending=consumePendingNewGameSetup(),loadedCompetitionIds=normalizeLoaded(pending?.loadedCompetitionIds,currentCompetitionId);return buildWorldLeagues(baseSeed,year,currentCompetitionId,overrides,loadedCompetitionIds,pending?.manager);}
export function processWorldLeaguesThroughDate(value:WorldLeaguesState,baseSeed:string,date:string){const state:WorldLeaguesState=structuredClone(value),active=new Set(normalizeLoaded(state.loadedCompetitionIds,PROFESSIONAL_COMPETITIONS.find(item=>!state.leagues[item.id])?.id??PROFESSIONAL_COMPETITIONS[0].id));for(const league of Object.values(state.leagues)){if(!league||!active.has(league.competitionId))continue;for(const fixture of league.fixtures)if(!fixture.played&&fixture.date&&fixture.date<=date)simulateFixture(league,fixture,`${baseSeed}:${state.season}:parallel`);}state.lastProcessedDate=date;return state;}
export function hydrateWorldLeagues(value:WorldLeaguesState|undefined,baseSeed:string,year:number,currentCompetitionId:ProfessionalCompetitionId,currentDate:string){const loadedCompetitionIds=normalizeLoaded(value?.loadedCompetitionIds,currentCompetitionId),managerProfile=value?.managerProfile,state=value?.season===year?structuredClone(value):buildWorldLeagues(baseSeed,year,currentCompetitionId,{},loadedCompetitionIds,managerProfile);state.loadedCompetitionIds=loadedCompetitionIds;if(managerProfile)state.managerProfile=managerProfile;for(const comp of PROFESSIONAL_COMPETITIONS){if(comp.id===currentCompetitionId){delete state.leagues[comp.id];continue}if(!state.leagues[comp.id])state.leagues[comp.id]=createParallelLeague(baseSeed,year,comp.id);}return processWorldLeaguesThroughDate(state,baseSeed,currentDate);}
export function parallelLeagueById(state:WorldLeaguesState,id:ProfessionalCompetitionId){return state.leagues[id];}
export function worldLeagueIsLoaded(state:WorldLeaguesState,id:ProfessionalCompetitionId){return(state.loadedCompetitionIds??PROFESSIONAL_COMPETITIONS.map(item=>item.id)).includes(id);}
export function sortedParallelStandings(standings:LeagueStanding[]){return[...standings].sort((a,b)=>b.points-a.points||(b.goalsFor-b.goalsAgainst)-(a.goalsFor-a.goalsAgainst)||b.goalsFor-a.goalsFor);}
export function parallelTopPlayers(league:ParallelLeagueState,key:"goals"|"assists"|"averageRating",limit=10){return[...league.players].filter(p=>key!=="averageRating"||p.ratedMatches>=2).sort((a,b)=>b[key]-a[key]||b.goals-a.goals).slice(0,limit);}
