/* eslint-disable prefer-const */
import { SeededRng } from "./rng";
import { PROFESSIONAL_COMPETITIONS, type ProfessionalCompetitionId } from "../data/brazil-2026/competitions";
import type { LeagueWorld } from "./league";
import type { MatchResult } from "./match";

export type WorldCompetitionId="CDB"|"LIB"|"SUD"|"FAC"|"CDR"|"CDF"|"UCL"|"UEL"|"UECL";
export type WorldCompetitionKind="Copa nacional"|"Continental";
export type WorldCompetitionDefinition={id:WorldCompetitionId;name:string;shortName:string;country?:string;kind:WorldCompetitionKind;participants:number;roundInterval:number};
export type WorldParticipant={id:string;name:string;shortName:string;country:string;reputation:number;activeClubId?:string};
export type WorldCompetitionMatch={id:string;competitionId:WorldCompetitionId;stage:string;roundDue:number;date:string;home:WorldParticipant;away:WorldParticipant;played:boolean;homeGoals?:number;awayGoals?:number;winnerId?:string;decidedByPenalties?:boolean};
export type WorldTournamentState={definition:WorldCompetitionDefinition;participants:WorldParticipant[];matches:WorldCompetitionMatch[];currentStage:string;championId?:string;completed:boolean};
export type WorldCompetitionsState={season:number;tournaments:WorldTournamentState[];lastProcessedRound?:number;history:Array<{year:number;competitionId:WorldCompetitionId;competitionName:string;championName:string}>};
export const WORLD_COMPETITIONS:WorldCompetitionDefinition[]=[{id:"CDB",name:"Copa do Brasil",shortName:"Copa do Brasil",country:"Brasil",kind:"Copa nacional",participants:32,roundInterval:4},{id:"LIB",name:"CONMEBOL Libertadores",shortName:"Libertadores",kind:"Continental",participants:32,roundInterval:4},{id:"SUD",name:"CONMEBOL Sudamericana",shortName:"Sul-Americana",kind:"Continental",participants:32,roundInterval:4},{id:"FAC",name:"FA Cup",shortName:"FA Cup",country:"Inglaterra",kind:"Copa nacional",participants:32,roundInterval:4},{id:"CDR",name:"Copa del Rey",shortName:"Copa del Rey",country:"Espanha",kind:"Copa nacional",participants:32,roundInterval:4},{id:"CDF",name:"Coupe de France",shortName:"Coupe de France",country:"França",kind:"Copa nacional",participants:32,roundInterval:4},{id:"UCL",name:"UEFA Champions League",shortName:"Champions League",kind:"Continental",participants:32,roundInterval:4},{id:"UEL",name:"UEFA Europa League",shortName:"Europa League",kind:"Continental",participants:32,roundInterval:4},{id:"UECL",name:"UEFA Conference League",shortName:"Conference League",kind:"Continental",participants:32,roundInterval:4}];
const addDays=(iso:string,days:number)=>{const d=new Date(`${iso}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)};
function repFromValue(value:number){if(value>=1_000_000_000)return 95;if(value>=600_000_000)return 90;if(value>=300_000_000)return 84;if(value>=150_000_000)return 78;if(value>=70_000_000)return 72;if(value>=30_000_000)return 66;if(value>=12_000_000)return 59;return 52;}
function sourceCountry(id:ProfessionalCompetitionId){return id.startsWith("BRA")?"Brasil":id==="ENG1"?"Inglaterra":id==="ESP1"?"Espanha":"França";}
function allParticipants(activeCompetitionId:ProfessionalCompetitionId,league:LeagueWorld){const active=league.clubs.map(club=>({id:`active:${club.id}`,name:club.name,shortName:club.shortName,country:sourceCountry(activeCompetitionId),reputation:club.reputation,activeClubId:club.id}));const external=PROFESSIONAL_COMPETITIONS.flatMap(comp=>comp.id===activeCompetitionId?[]:comp.clubs.map(club=>({id:`ext:${comp.id}:${club.transfermarktId}`,name:club.name,shortName:club.shortName,country:comp.country,reputation:repFromValue(club.marketValueEur)})));return[...active,...external];}
function activeEligibility(def:WorldCompetitionDefinition,league:LeagueWorld){const ranked=[...league.clubs].sort((a,b)=>b.reputation-a.reputation),ids=new Set<string>();if(def.kind==="Copa nacional")ranked.forEach(c=>ids.add(c.id));else if(def.id==="LIB")ranked.slice(0,6).forEach(c=>ids.add(c.id));else if(def.id==="SUD")ranked.slice(6,12).forEach(c=>ids.add(c.id));else if(def.id==="UCL")ranked.slice(0,4).forEach(c=>ids.add(c.id));else if(def.id==="UEL")ranked.slice(4,8).forEach(c=>ids.add(c.id));else if(def.id==="UECL")ranked.slice(8,12).forEach(c=>ids.add(c.id));return ids;}
function chooseParticipants(def:WorldCompetitionDefinition,pool:WorldParticipant[],activeCountry:string,league:LeagueWorld){let candidates:WorldParticipant[];if(def.kind==="Copa nacional")candidates=pool.filter(p=>p.country===def.country);else if(def.id==="LIB"||def.id==="SUD")candidates=pool.filter(p=>p.country==="Brasil");else candidates=pool.filter(p=>["Inglaterra","Espanha","França"].includes(p.country));const eligible=activeEligibility(def,league);candidates=candidates.filter(p=>!p.activeClubId||eligible.has(p.activeClubId));const ranked=[...candidates].sort((a,b)=>b.reputation-a.reputation);if(def.id==="SUD")ranked.reverse();if(def.id==="UEL")ranked.splice(0,Math.min(10,ranked.length));if(def.id==="UECL")ranked.splice(0,Math.min(18,ranked.length));const selected:WorldParticipant[]=[];for(const participant of ranked.filter(p=>p.activeClubId&&p.country===activeCountry)){if(selected.length>=12)break;selected.push(participant);}for(const participant of ranked){if(selected.length>=def.participants)break;if(!selected.some(p=>p.id===participant.id))selected.push(participant);}while(selected.length>2&&(selected.length&(selected.length-1))!==0)selected.pop();return selected;}
function stageFor(count:number){return count>=32?"16 avos":count===16?"Oitavas de final":count===8?"Quartas de final":count===4?"Semifinal":"Final";}
function dateForRound(league:LeagueWorld,round:number){const leagueDate=league.fixtures.find(f=>f.round===Math.min(round,league.totalRounds??round))?.date??league.fixtures.find(f=>f.date)?.date??`${new Date().getUTCFullYear()}-02-01`;return addDays(leagueDate,-3);}
function pair(def:WorldCompetitionDefinition,participants:WorldParticipant[],stage:string,roundDue:number,date:string,rng:SeededRng){const shuffled=[...participants];for(let i=shuffled.length-1;i>0;i--){const j=rng.integer(0,i);[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]];}const matches:WorldCompetitionMatch[]=[];for(let i=0;i<shuffled.length;i+=2){if(shuffled[i+1])matches.push({id:`${def.id}:${stage}:${roundDue}:${i/2}`,competitionId:def.id,stage,roundDue,date,home:shuffled[i],away:shuffled[i+1],played:false});}return matches;}
function simulate(match:WorldCompetitionMatch,rng:SeededRng){const delta=(match.home.reputation-match.away.reputation)*.035+.2;let hg=Math.max(0,rng.integer(0,2)+(delta>1?1:0)),ag=Math.max(0,rng.integer(0,2)+(delta<-1?1:0));if(hg===ag){match.decidedByPenalties=true;match.winnerId=rng.integer(1,100)<=Math.max(20,Math.min(80,50+(match.home.reputation-match.away.reputation)))?match.home.id:match.away.id;}else match.winnerId=hg>ag?match.home.id:match.away.id;match.homeGoals=hg;match.awayGoals=ag;match.played=true;}
function progressTournament(t:WorldTournamentState,state:WorldCompetitionsState,round:number,seed:string){const stageMatches=t.matches.filter(m=>m.stage===t.currentStage);if(!stageMatches.length||!stageMatches.every(m=>m.played))return;const winners=stageMatches.map(m=>m.winnerId===m.home.id?m.home:m.away);if(winners.length===1){t.completed=true;t.championId=winners[0].id;state.history.unshift({year:state.season,competitionId:t.definition.id,competitionName:t.definition.name,championName:winners[0].name});return;}const nextStage=stageFor(winners.length),lastDate=stageMatches.map(m=>m.date).sort().at(-1)!,nextDate=addDays(lastDate,t.definition.roundInterval*7),rng=new SeededRng(`${seed}:${t.definition.id}:${nextStage}:${round}`);t.currentStage=nextStage;t.matches.push(...pair(t.definition,winners,nextStage,round+t.definition.roundInterval,nextDate,rng));}
export function createWorldCompetitions(activeCompetitionId:ProfessionalCompetitionId,league:LeagueWorld,year:number,seed:string):WorldCompetitionsState{const rng=new SeededRng(`${seed}:world-competitions:${year}`),pool=allParticipants(activeCompetitionId,league),country=sourceCountry(activeCompetitionId),relevant=WORLD_COMPETITIONS.filter(def=>def.kind==="Continental"||def.country===country),tournaments=relevant.map(def=>{const participants=chooseParticipants(def,pool,country,league),roundDue=Math.max(2,def.roundInterval),stage=stageFor(participants.length),matches=pair(def,participants,stage,roundDue,dateForRound(league,roundDue),rng);return{definition:def,participants,matches,currentStage:stage,completed:false} satisfies WorldTournamentState;});return{season:year,tournaments,history:[]};}
export function hydrateWorldCompetitions(state:WorldCompetitionsState|undefined,activeCompetitionId:ProfessionalCompetitionId,league:LeagueWorld,year:number,seed:string){return state??createWorldCompetitions(activeCompetitionId,league,year,seed);}
export function processWorldCompetitions(state:WorldCompetitionsState,round:number,seed:string,userClubId?:string){if(state.lastProcessedRound===round)return state;const next=structuredClone(state);next.lastProcessedRound=round;const rng=new SeededRng(`${seed}:world-cups:r${round}`);for(const tournament of next.tournaments){if(tournament.completed)continue;for(const match of tournament.matches.filter(m=>!m.played&&m.roundDue<=round)){const userInvolved=userClubId&&(match.home.activeClubId===userClubId||match.away.activeClubId===userClubId);if(!userInvolved)simulate(match,rng);}progressTournament(tournament,next,round,seed);}return next;}
export function playWorldCompetitionMatch(state:WorldCompetitionsState,matchId:string,result:MatchResult,round:number,seed:string){const next=structuredClone(state);for(const tournament of next.tournaments){const match=tournament.matches.find(m=>m.id===matchId);if(!match)continue;match.homeGoals=result.homeGoals;match.awayGoals=result.awayGoals;match.played=true;if(result.homeGoals===result.awayGoals){const rng=new SeededRng(`${seed}:penalties:${match.id}`);match.decidedByPenalties=true;match.winnerId=rng.next()<.5?match.home.id:match.away.id;}else match.winnerId=result.homeGoals>result.awayGoals?match.home.id:match.away.id;progressTournament(tournament,next,round,seed);break;}return next;}
export function competitionPrizeEur(id:WorldCompetitionId,stage:string,won:boolean){const continental=["LIB","UCL","UEL","UECL"].includes(id),base=continental?1_800_000:450_000,mult=stage==="Final"?6:stage==="Semifinal"?3:stage==="Quartas de final"?2:1;return Math.round(base*mult*(won?1:.35));}
export function prepareWorldCompetitionsNextSeason(state:WorldCompetitionsState,activeCompetitionId:ProfessionalCompetitionId,league:LeagueWorld,year:number,seed:string){const fresh=createWorldCompetitions(activeCompetitionId,league,year,seed);fresh.history=[...state.history,...fresh.history].slice(0,80);return fresh;}
export function userWorldCompetitionMatches(state:WorldCompetitionsState,clubId:string){return state.tournaments.flatMap(t=>t.matches.filter(m=>m.home.activeClubId===clubId||m.away.activeClubId===clubId).map(match=>({tournament:t,match}))).sort((a,b)=>a.match.date.localeCompare(b.match.date));}
export function userWorldCompetitionMatchByDate(state:WorldCompetitionsState,clubId:string,date:string){return userWorldCompetitionMatches(state,clubId).find(item=>!item.match.played&&item.match.date===date);}
export function worldCompetitionMatchById(state:WorldCompetitionsState,id:string){for(const tournament of state.tournaments){const match=tournament.matches.find(m=>m.id===id);if(match)return{tournament,match};}return undefined;}
