from pathlib import Path
import re


def sub_required(text, pattern, repl, label, flags=0, count=1):
    new, n = re.subn(pattern, repl, text, count=count, flags=flags)
    if n != count:
        raise SystemExit(f"{label}: expected {count} replacement(s), got {n}")
    return new


def replace_required(text, old, new, label):
    if old not in text:
        raise SystemExit(f"{label}: marker missing")
    return text.replace(old, new, 1)

p = Path('src/game-engine/season.ts')
s = p.read_text()
s = replace_required(s,'import { createClubManagementState, hydrateClubManagement, prepareNextClubManagementSeason, processClubManagementRound, type ClubManagementState } from "./club-management";\n','import { createClubManagementState, hydrateClubManagement, prepareNextClubManagementSeason, processClubManagementRound, type ClubManagementState } from "./club-management";\nimport { competitionStartDate, professionalCompetitionById, type ProfessionalCompetitionId } from "../data/brazil-2026/competitions";\n','season competition import')
s = replace_required(s,'  clubManagement:ClubManagementState;\n  championClubId?:string;','  clubManagement:ClubManagementState;\n  competitionId:ProfessionalCompetitionId;\n  currentDate:string;\n  championClubId?:string;','season fields')
s = replace_required(s,'  return{\n    clubs:','  return{\n    ...league,\n    clubs:','clone league metadata')
s = replace_required(s,'function defaultLineup(club:LeagueClub):string[]{return pickStartingXI(club).map(p=>p.id);}\n\nexport function createSeason(baseSeed:string,year=2026,selectedClubId="club-1"):SeasonState{\n  const league=createLeague(`${baseSeed}:${year}`,year);\n  const club=league.clubs.find(c=>c.id===selectedClubId)??league.clubs[0];\n  const lineupIds=defaultLineup(club);\n  club.players.forEach(player=>refreshStatus(player,lineupIds.includes(player.id)));\n  return{baseSeed,year,league,currentRound:1,selectedClubId:club.id,lineupIds,recentForm:[],completed:false,livingWorld:createLivingWorld(club.name),market:createMarketState(),career:createManagerCareer(club,year),clubManagement:createClubManagementState(league,baseSeed,year)};\n}\n','function defaultLineup(club:LeagueClub):string[]{return pickStartingXI(club).map(p=>p.id);}\nfunction addIsoDays(iso:string,days:number){const date=new Date(`${iso}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10);}\n\nexport function createSeason(baseSeed:string,year=2026,selectedClubId="club-1",competitionId:ProfessionalCompetitionId="BRA1"):SeasonState{\n  const league=createLeague(`${baseSeed}:${year}:${competitionId}`,year,competitionId);\n  const club=league.clubs.find(c=>c.id===selectedClubId)??league.clubs[0];\n  const lineupIds=defaultLineup(club);\n  club.players.forEach(player=>refreshStatus(player,lineupIds.includes(player.id)));\n  const firstDate=league.fixtures.find(f=>f.round===1)?.date??competitionStartDate(competitionId,year);\n  return{baseSeed,year,league,currentRound:1,selectedClubId:club.id,lineupIds,recentForm:[],completed:false,livingWorld:createLivingWorld(club.name),market:createMarketState(),career:createManagerCareer(club,year),clubManagement:createClubManagementState(league,baseSeed,year),competitionId,currentDate:addIsoDays(firstDate,-7)};\n}\n','create season')
s = replace_required(s,'  const completed=state.currentRound>=TOTAL_ROUNDS;\n  const championClubId=completed?sortedStandings(league)[0]?.clubId:undefined;\n  const nextRound=completed?TOTAL_ROUNDS+1:state.currentRound+1;','  const totalRounds=league.totalRounds??Math.max(...league.fixtures.map(f=>f.round),TOTAL_ROUNDS);\n  const completed=state.currentRound>=totalRounds;\n  const championClubId=completed?sortedStandings(league)[0]?.clubId:undefined;\n  const nextRound=completed?totalRounds+1:state.currentRound+1;','dynamic rounds')
calendar_block='''export type CalendarRoute="matchday"|"inbox"|"club"|null;\nexport type CalendarAdvanceResult={state:SeasonState;route:CalendarRoute;reason:string};\n\nexport function getTodayUserFixture(state:SeasonState):LeagueFixture|undefined{\n  return getUserFixtures(state).find(f=>!f.played&&f.date===state.currentDate);\n}\n\nexport function advanceCalendarDay(state:SeasonState):CalendarAdvanceResult{\n  const todayMatch=getTodayUserFixture(state);\n  if(todayMatch)return{state,route:"matchday",reason:"Hoje é dia de jogo. A comissão já encaminhou você para a preparação da partida."};\n  const current=state.currentDate??state.league.fixtures.find(f=>!f.played)?.date??`${state.year}-01-01`;\n  const nextDate=addIsoDays(current,1);\n  const dayNumber=Math.max(1,Math.floor((new Date(`${nextDate}T12:00:00Z`).getTime()-new Date(`${state.year}-01-01T12:00:00Z`).getTime())/86400000)+1);\n  const next=advanceSeasonDay({...state,currentDate:nextDate},dayNumber);\n  if(getTodayUserFixture(next))return{state:next,route:"matchday",reason:"Hoje é dia de jogo. Vá para a preparação da partida."};\n  const pending=next.livingWorld.inbox.find(event=>event.unread&&!event.resolved);\n  if(pending?.kind==="Diretoria")return{state:next,route:"club",reason:`A diretoria precisa de você: ${pending.title}.`};\n  if(pending)return{state:next,route:"inbox",reason:`Há uma decisão pendente: ${pending.title}.`};\n  return{state:next,route:null,reason:"Dia avançado. Nenhuma decisão obrigatória surgiu."};\n}\n\n'''
s = replace_required(s,'export function resolveSeasonWorldChoice(state:SeasonState,eventId:string,choiceId:string){',calendar_block+'export function resolveSeasonWorldChoice(state:SeasonState,eventId:string,choiceId:string){','calendar block')
s = replace_required(s,'  prepared.league.fixtures=generateFixtures(prepared.league.clubs.map(c=>c.id));','  const competitionId=state.competitionId??state.league.competitionId??"BRA1",competition=professionalCompetitionById(competitionId);\n  prepared.league.fixtures=generateFixtures(prepared.league.clubs.map(c=>c.id),competitionStartDate(competitionId,nextYear),competition.roundCadenceDays,competition.doubleRoundRobin);\n  prepared.league.competitionId=competitionId;prepared.league.competitionName=competition.name;prepared.league.totalRounds=Math.max(...prepared.league.fixtures.map(f=>f.round),0);','next season fixtures')
s = replace_required(s,'  return{...state,year:nextYear,league:prepared.league,currentRound:1,lineupIds,recentForm:[],completed:false,championClubId:undefined,lastUserMatch:undefined,livingWorld,market:prepared.market,career:state.career??createManagerCareer(club,nextYear),clubManagement};','  const firstDate=prepared.league.fixtures.find(f=>f.round===1)?.date??competitionStartDate(competitionId,nextYear);\n  return{...state,year:nextYear,league:prepared.league,currentRound:1,lineupIds,recentForm:[],completed:false,championClubId:undefined,lastUserMatch:undefined,livingWorld,market:prepared.market,career:state.career??createManagerCareer(club,nextYear),clubManagement,competitionId,currentDate:addIsoDays(firstDate,-7)};','next season state')
load_pattern=r'''export function loadSeasonLocal\(\):SeasonState\|null\{\n  if\(typeof window==="undefined"\)return null;\n  try\{\n    const raw=window\.localStorage\.getItem\(SEASON_SAVE_KEY\);\n    if\(!raw\)return null;\n    const parsed=JSON\.parse\(raw\) as SeasonState;\n    if\(!parsed\?\.baseSeed\|\|!parsed\.league\?\.clubs\?\.length\|\|!Array\.isArray\(parsed\.lineupIds\)\|\|!parsed\.livingWorld\|\|!parsed\.market\)return null;\n    if\(!parsed\.career\)\{const club=parsed\.league\.clubs\.find\(c=>c\.id===parsed\.selectedClubId\)\?\?parsed\.league\.clubs\[0\];parsed\.career=createManagerCareer\(club,parsed\.year\?\?2026\);\}\n    if\(!parsed\.clubManagement\)parsed\.clubManagement=hydrateClubManagement\(parsed\);\n    return parsed;\n  \}catch\{return null;\}\n\}'''
load_repl='''export function hydrateSeasonState(parsed:SeasonState):SeasonState{\n  const competitionId=(parsed.competitionId??parsed.league?.competitionId??"BRA1") as ProfessionalCompetitionId;\n  const competition=professionalCompetitionById(competitionId),year=parsed.year??2026;\n  parsed.competitionId=competitionId;parsed.league.competitionId=competitionId;parsed.league.competitionName=competition.name;\n  if(parsed.league.fixtures.some(f=>!f.date)){\n    const dated=generateFixtures(parsed.league.clubs.map(c=>c.id),competitionStartDate(competitionId,year),competition.roundCadenceDays,competition.doubleRoundRobin);\n    const dateByRound=new Map(dated.map(f=>[f.round,f.date]));\n    parsed.league.fixtures=parsed.league.fixtures.map(f=>({...f,date:f.date??dateByRound.get(f.round)}));\n  }\n  parsed.league.totalRounds=parsed.league.totalRounds??Math.max(...parsed.league.fixtures.map(f=>f.round),0);\n  if(!parsed.currentDate){const next=parsed.league.fixtures.find(f=>!f.played&&f.round===parsed.currentRound)?.date??parsed.league.fixtures.find(f=>!f.played)?.date??competitionStartDate(competitionId,year);parsed.currentDate=addIsoDays(next,-1);}\n  if(!parsed.career){const club=parsed.league.clubs.find(c=>c.id===parsed.selectedClubId)??parsed.league.clubs[0];parsed.career=createManagerCareer(club,year);}\n  if(!parsed.clubManagement)parsed.clubManagement=hydrateClubManagement(parsed);\n  return parsed;\n}\n\nexport function loadSeasonLocal():SeasonState|null{\n  if(typeof window==="undefined")return null;\n  try{const raw=window.localStorage.getItem(SEASON_SAVE_KEY);if(!raw)return null;const parsed=JSON.parse(raw) as SeasonState;if(!parsed?.baseSeed||!parsed.league?.clubs?.length||!Array.isArray(parsed.lineupIds)||!parsed.livingWorld||!parsed.market)return null;return hydrateSeasonState(parsed);}catch{return null;}\n}'''
s = sub_required(s,load_pattern,load_repl,'hydrate load',flags=re.S)
p.write_text(s)

p=Path('src/app/page.tsx')
s=p.read_text()
s=replace_required(s,'import ClubManagementView from "./club-management-view";\nimport { SOCCERWIKI_COMPETITION } from "@/data/soccerwiki";\nimport { createInitialWorld, advanceDay, type GameWorld } from "@/game-engine/world";\nimport { loadLocalSave, saveLocalWorld } from "@/game-engine/save";\n','import ClubManagementView from "./club-management-view";\nimport MainMenu from "./main-menu";\nimport { professionalCompetitionById, type ProfessionalCompetitionId } from "@/data/brazil-2026/competitions";\nimport { leagueClubIdForTransfermarkt } from "@/game-engine/new-game";\nimport { createSaveSlot, migrateLegacySeason, saveToSlot, type SaveSlot } from "@/game-engine/save-slots";\n','page imports')
s=replace_required(s,'import { advanceSeasonDay, createSeason, getCurrentUserFixture, getSelectedClub, getUserFixtures, loadSeasonLocal, playCurrentRound, resolveSeasonWorldChoice, saveSeasonLocal, startNextSeason, toggleLineupPlayer, type SeasonState } from "@/game-engine/season";','import { advanceCalendarDay, createSeason, getCurrentUserFixture, getSelectedClub, getTodayUserFixture, getUserFixtures, hydrateSeasonState, playCurrentRound, resolveSeasonWorldChoice, startNextSeason, toggleLineupPlayer, type SeasonState } from "@/game-engine/season";','season imports page')
s=replace_required(s,'  const [world,setWorld]=useState<GameWorld>(()=>createInitialWorld("vestiario-90-demo"));\n  const [season,setSeason]=useState<SeasonState>(()=>createSeason("brasileirao-soccerwiki",2026));','  const [screen,setScreen]=useState<"menu"|"game">("menu");\n  const [saveId,setSaveId]=useState<string|null>(null);\n  const [season,setSeason]=useState<SeasonState>(()=>createSeason("vestiario-90",2026));','page state')
s=replace_required(s,'  useEffect(()=>{\n    const saved=loadLocalSave();\n    const savedSeason=loadSeasonLocal();\n    queueMicrotask(()=>{if(saved)setWorld(saved.world);if(savedSeason)setSeason(savedSeason)});\n  },[]);','  useEffect(()=>{migrateLegacySeason()},[]);','page migration effect')
s=replace_required(s,'  const league=season.league;\n  const club=getSelectedClub(season);','  const league=season.league;\n  const competition=professionalCompetitionById(season.competitionId??league.competitionId??"BRA1");\n  const totalRounds=league.totalRounds??Math.max(...league.fixtures.map(f=>f.round),38);\n  const todayFixture=getTodayUserFixture(season);\n  const club=getSelectedClub(season);','page competition vars')
s=replace_required(s,'  function persist(next:SeasonState){setSeason(next);saveSeasonLocal(next)}\n  function handleAdvance(){if(!employed){handleCareerAdvanceRound();return}const nextWorld=advanceDay(world),nextSeason=advanceSeasonDay(season,nextWorld.day);setWorld(nextWorld);saveLocalWorld(nextWorld);persist(nextSeason);flash(`${nextWorld.lastEvent} • condição física atualizada`)}\n  function handleCareerAdvanceRound(){if(season.completed){handleNextSeason();return}const next=playCurrentRound(season);persist(next);flash(`Rodada ${Math.min(38,next.currentRound-1)} simulada • mercado de treinadores atualizado`)}','  function persist(next:SeasonState){setSeason(next);if(saveId)saveToSlot(saveId,next)}\n  function handleLoad(slot:SaveSlot){const next=hydrateSeasonState(slot.state);setSaveId(slot.meta.id);setSeason(next);setScreen("game");setActive("Visão geral");setMatch(null);setLiveMatch(null)}\n  function handleStart(competitionId:ProfessionalCompetitionId,clubTransfermarktId:number,saveName?:string){const clubId=leagueClubIdForTransfermarkt(competitionId,clubTransfermarktId),next=createSeason(`career-${Date.now()}-${clubTransfermarktId}`,2026,clubId,competitionId),meta=createSaveSlot(next,saveName);setSaveId(meta?.id??null);setSeason(next);setScreen("game");setActive("Visão geral");setMatch(null);setLiveMatch(null)}\n  function handleAdvance(){if(!employed){handleCareerAdvanceRound();return}const result=advanceCalendarDay(season);persist(result.state);if(result.route==="matchday")setActive("Táticas");else if(result.route==="club")setActive("Clube");else if(result.route==="inbox")setActive("Caixa de entrada");flash(`${formatDate(result.state.currentDate)} • ${result.reason}`)}\n  function handleCareerAdvanceRound(){if(season.completed){handleNextSeason();return}const next=playCurrentRound(season);persist(next);flash(`Rodada ${Math.min(totalRounds,next.currentRound-1)} simulada • mercado de treinadores atualizado`)}','page persistence')
s=replace_required(s,'    if(!currentFixture){flash("Não há partida pendente nesta rodada.");return}\n    const home=','    if(!currentFixture){flash("Não há partida pendente nesta rodada.");return}\n    if(!todayFixture){flash(`A partida está marcada para ${formatDate(currentFixture.date??season.currentDate)}. Avance os dias até o dia do jogo.`);return}\n    const home=','match date guard')
s=replace_required(s,'  return <div className={styles.shell}>','  if(screen==="menu")return <MainMenu onLoad={handleLoad} onStart={handleStart}/>;\n\n  return <div className={styles.shell}>','menu return')
s=replace_required(s,'${SOCCERWIKI_COMPETITION.name} • ${season.year}','${competition.name} • ${season.year}','sidebar comp')
s=replace_required(s,'<button className={styles.settings}><Settings size={18}/> Configurações</button>','<button className={styles.settings} onClick={()=>setScreen("menu")}><Settings size={18}/> Menu principal</button>','menu button')
s=replace_required(s,'{employed?SOCCERWIKI_COMPETITION.name:"Mercado de Treinadores"} • Temporada {season.year}','{employed?competition.name:"Mercado de Treinadores"} • Temporada {season.year}','top comp')
s=replace_required(s,'{season.completed?"TEMPORADA ENCERRADA":`RODADA ${season.currentRound} DE 38`} • {world.day} SET','{season.completed?"TEMPORADA ENCERRADA":`RODADA ${season.currentRound} DE ${totalRounds}`} • {formatDate(season.currentDate)}','top date')
s=replace_required(s,'{employed?"AVANÇAR":"AVANÇAR RODADA"}','{employed?"AVANÇAR DIA":"AVANÇAR RODADA"}','advance label')
s=replace_required(s,'${SOCCERWIKI_COMPETITION.name.toUpperCase()}','${competition.name.toUpperCase()}','welcome comp')
s=replace_required(s,'active==="Clube"?<ClubManagementView season={season} onResult={({state:next,message})=>{persist(next);flash(message)}}/>:','active==="Clube"?<ClubManagementView season={season} onOpenInbox={()=>setActive("Caixa de entrada")} onResult={({state:next,message})=>{persist(next);flash(message)}}/>:','club inbox prop')
s=replace_required(s,'active==="Classificação"?<TableView clubs={league.clubs} standings={standings} selectedClubId={club.id}/>','active==="Classificação"?<TableView clubs={league.clubs} standings={standings} selectedClubId={club.id} competitionName={competition.name} totalRounds={totalRounds}/>','table call')
s=replace_required(s,'<NextMatchCard fixture={currentFixture} club={club} opponent={opponent} standings={standings} tactic={tactic} onPrepare={()=>setActive("Táticas")}/>','<NextMatchCard fixture={currentFixture} club={club} opponent={opponent} standings={standings} tactic={tactic} competitionName={competition.name} onPrepare={()=>setActive("Táticas")}/>','next match call')
s=replace_required(s,'<Agenda fixtures={getUserFixtures(season)} league={league.clubs} currentRound={season.currentRound}/>','<Agenda fixtures={getUserFixtures(season)} league={league.clubs} currentRound={season.currentRound} competitionName={competition.name} totalRounds={totalRounds}/>','agenda call')
s=sub_required(s,r'function NextMatchCard\(\{fixture,club,opponent,standings,tactic,onPrepare\}:\{fixture:LeagueFixture;club:LeagueClub;opponent:LeagueClub;standings:LeagueStanding\[\];tactic:MatchTactic;onPrepare:\(\)=>void\}\)\{(.*?)<div className=\{styles\.competition\}>\{SOCCERWIKI_COMPETITION\.name\.toUpperCase\(\)\} • RODADA \{fixture\.round\}',r'function NextMatchCard({fixture,club,opponent,standings,tactic,competitionName,onPrepare}:{fixture:LeagueFixture;club:LeagueClub;opponent:LeagueClub;standings:LeagueStanding[];tactic:MatchTactic;competitionName:string;onPrepare:()=>void}){\1<div className={styles.competition}>{competitionName.toUpperCase()} • {formatDate(fixture.date)} • RODADA {fixture.round}','next match helper',flags=re.S)
s=sub_required(s,r'function Agenda\(\{fixtures,league,currentRound\}:\{fixtures:LeagueFixture\[\];league:LeagueClub\[\];currentRound:number\}\)\{.*?\}\nfunction InboxItem','function Agenda({fixtures,league,currentRound,competitionName,totalRounds}:{fixtures:LeagueFixture[];league:LeagueClub[];currentRound:number;competitionName:string;totalRounds:number}){const visible=fixtures.filter(f=>f.round>=Math.max(1,currentRound-1)&&f.round<=Math.min(totalRounds,currentRound+2)).slice(0,4);return <section className={styles.card}><div className={styles.cardHead}><div>AGENDA</div><button>{totalRounds} rodadas</button></div><div className={styles.fixtures}>{visible.map(f=>{const home=league.find(c=>c.id===f.homeClubId)!,away=league.find(c=>c.id===f.awayClubId)!;return <div className={styles.fixture} key={f.id}><div className={styles.dateBox}><b>{formatShortDate(f.date)}</b><span>R{f.round}</span></div><div className={styles.fixtureInfo}><b>{home.name} <span>×</span> {away.name}</b><small>{f.played?`${f.homeGoals} × ${f.awayGoals}`:competitionName}</small></div><em className={f.round===currentRound?styles.nextTag:""}>{f.played?"FIM":f.round===currentRound?"PRÓXIMO":"AGENDADO"}</em></div>})}</div></section>}\nfunction InboxItem','agenda helper',flags=re.S)
s=sub_required(s,r'function TableView\(\{clubs,standings,selectedClubId\}:\{clubs:LeagueClub\[\];standings:LeagueStanding\[\];selectedClubId:string\}\)\{return <section className=\{`\$\{styles\.card\} \$\{styles\.dataCard\}`\}><div className=\{styles\.cardHead\}><div>\{SOCCERWIKI_COMPETITION\.name\.toUpperCase\(\)\}</div><button>38 rodadas • pontos corridos</button>','function TableView({clubs,standings,selectedClubId,competitionName,totalRounds}:{clubs:LeagueClub[];standings:LeagueStanding[];selectedClubId:string;competitionName:string;totalRounds:number}){return <section className={`${styles.card} ${styles.dataCard}`}><div className={styles.cardHead}><div>{competitionName.toUpperCase()}</div><button>{totalRounds} rodadas</button>','table helper')
s=sub_required(s,r'function CalendarView\(\{season\}:\{season:SeasonState\}\)\{.*?\}\nfunction SeasonEnd','function CalendarView({season}:{season:SeasonState}){const fixtures=getUserFixtures(season),clubs=season.league.clubs,totalRounds=season.league.totalRounds??fixtures.length;return <section className={`${styles.card} ${styles.dataCard}`}><div className={styles.cardHead}><div>CALENDÁRIO • {season.year}</div><button>{fixtures.filter(f=>f.played).length}/{totalRounds} jogados</button></div><div className={seasonStyles.calendarList}>{fixtures.map(f=>{const home=clubs.find(c=>c.id===f.homeClubId)!,away=clubs.find(c=>c.id===f.awayClubId)!;return <article key={f.id} className={f.round===season.currentRound?seasonStyles.currentFixture:""}><span>{formatShortDate(f.date)}</span><div><b>{home.name} × {away.name}</b><small>{f.played?`Final • ${f.homeGoals} × ${f.awayGoals}`:f.date===season.currentDate?"HOJE • dia de jogo":f.round===season.currentRound?"Próxima partida":"Agendado"} • Rodada {f.round}</small></div><em>{f.played?"✓":f.homeClubId===season.selectedClubId?"CASA":"FORA"}</em></article>})}</div></section>}\nfunction SeasonEnd','calendar helper',flags=re.S)
s=replace_required(s,'function ComingSoon({title}:{title:string})','function formatDate(iso?:string){if(!iso)return"Data a definir";try{return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(`${iso}T12:00:00Z`));}catch{return iso}}\nfunction formatShortDate(iso?:string){if(!iso)return"—";try{return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",timeZone:"UTC"}).format(new Date(`${iso}T12:00:00Z`));}catch{return iso}}\nfunction ComingSoon({title}:{title:string})','date helpers')
p.write_text(s)

p=Path('src/app/club-management-view.tsx')
s=p.read_text()
s=replace_required(s,'export default function ClubManagementView({season,onResult}:{season:SeasonState;onResult:(result:ClubActionResult)=>void}){','export default function ClubManagementView({season,onResult,onOpenInbox}:{season:SeasonState;onResult:(result:ClubActionResult)=>void;onOpenInbox?:()=>void}){','club props')
s=replace_required(s,' const board=season.livingWorld.boardConfidence;\n return <div className={styles.shell}>',' const board=season.livingWorld.boardConfidence;\n const boardMeeting=season.livingWorld.inbox.find(event=>event.kind==="Diretoria"&&event.unread&&!event.resolved);\n return <div className={styles.shell}>\n  {boardMeeting&&<section className={styles.panel}><header><div><span>AGENDA DA DIRETORIA</span><h3>{boardMeeting.title}</h3></div><Building2/></header><p className={styles.intro}>{boardMeeting.body}</p><button className={styles.bigAction} onClick={onOpenInbox}><ClipboardList/> ABRIR PAUTA E RESPONDER <ChevronRight/></button></section>}','board meeting')
p.write_text(s)

p=Path('next.config.ts')
s=p.read_text()
s=replace_required(s,'remotePatterns:[{protocol:"https",hostname:"cdn.soccerwiki.org",pathname:"/images/**"}],','remotePatterns:[{protocol:"https",hostname:"cdn.soccerwiki.org",pathname:"/images/**"},{protocol:"https",hostname:"tmssl.akamaized.net",pathname:"/images/**"}],','tm image host')
p.write_text(s)
print('Sprint 12 patch applied')
