from pathlib import Path

match = r'''import { SeededRng } from "./rng";
import type { LeagueClub, LeaguePlayer } from "./league";
import{tacticalFitMultiplier,type TacticalPoint}from"./tactical-position";

export type Formation = "4-2-3-1" | "4-3-3" | "4-4-2";
export type Mentality = "Defensiva" | "Equilibrada" | "Ofensiva";
export type PlayerInstruction="Livre"|"Apoio"|"Atacar"|"Segurar";
export type MatchTactic = { formation:Formation; mentality:Mentality; pressing:number; tempo:number; positions?:Record<string,TacticalPoint>; roles?:Record<string,PlayerInstruction> };
export type MatchEventType = "kickoff" | "chance" | "goal" | "card" | "red_card" | "injury" | "tactical" | "halftime" | "fulltime";
export type MatchEvent = { minute:number; type:MatchEventType; team:"home"|"away"|"neutral"; text:string; playerId?:string; assistPlayerId?:string };
export type ShotRecord={team:"home"|"away";minute:number;playerId?:string;x:number;y:number;xg:number;goal:boolean;bigChance:boolean};
export type AttackZones={left:number;center:number;right:number};
export type MatchResult = { homeGoals:number; awayGoals:number; possessionHome:number; shotsHome:number; shotsAway:number; events:MatchEvent[]; playerRatings?:Record<string,number>; playerConditionAfter?:Record<string,number>; playerFatigueAfter?:Record<string,number>; playerMinutes?:Record<string,number>;xgHome?:number;xgAway?:number;bigChancesHome?:number;bigChancesAway?:number;passesHome?:number;passesAway?:number;tacklesHome?:number;tacklesAway?:number;interceptionsHome?:number;interceptionsAway?:number;attackZonesHome?:AttackZones;attackZonesAway?:AttackZones;shotMap?:ShotRecord[];redCardsHome?:number;redCardsAway?:number };

export const DEFAULT_TACTIC:MatchTactic={formation:"4-2-3-1",mentality:"Equilibrada",pressing:62,tempo:58};

export function pickStartingXI(club:LeagueClub,lineupIds?:string[]):LeaguePlayer[]{
  const available=club.players.filter(p=>p.injuryDays===0&&p.suspensionMatches===0);
  const requested=(lineupIds??[]).map(id=>available.find(p=>p.id===id)).filter((p):p is LeaguePlayer=>Boolean(p));
  const selected=[...requested];
  for(const player of [...available].sort((a,b)=>b.overall-a.overall)){
    if(selected.length>=11)break;
    if(!selected.some(p=>p.id===player.id))selected.push(player);
  }
  return selected.slice(0,11);
}
function roleFactor(tactic:MatchTactic,playerId:string){const role=tactic.roles?.[playerId]??"Livre";return role==="Atacar"?1.012:role==="Segurar"?.994:role==="Apoio"?1.006:1;}
function strength(club:LeagueClub,tactic:MatchTactic,lineupIds?:string[],sentOff=new Set<string>()){
  const eleven=pickStartingXI(club,lineupIds).filter(player=>!sentOff.has(player.id));if(!eleven.length)return 40;
  const base=eleven.reduce((sum,p)=>sum+p.overall*(p.condition/100)*(.92+p.morale/1250)*Math.max(.76,1-p.fatigue/235)*tacticalFitMultiplier(p,tactic.positions?.[p.id])*roleFactor(tactic,p.id),0)/Math.max(11,eleven.length);
  const mentality=tactic.mentality==="Ofensiva"?2:tactic.mentality==="Defensiva"?-1:0;
  return base+mentality+(tactic.pressing-50)*.025+(tactic.tempo-50)*.02-Math.max(0,11-eleven.length)*2.8;
}
function assister(rng:SeededRng,xi:LeaguePlayer[],scorer:LeaguePlayer){const pool=xi.filter(p=>p.id!==scorer.id&&["ATA","PE","PD","MEI","MC","VOL"].includes(p.position));return pool.length&&rng.next()<.72?rng.pick(pool):undefined;}
function attackingPool(xi:LeaguePlayer[],tactic:MatchTactic){const base=xi.filter(p=>["ATA","PE","PD","MEI","MC"].includes(p.position));const pool=base.length?base:xi;return pool.flatMap(player=>tactic.roles?.[player.id]==="Atacar"?[player,player,player]:tactic.roles?.[player.id]==="Apoio"?[player,player]:[player]);}
function xgForShot(rng:SeededRng,strengthDiff:number,tactic:MatchTactic){const central=rng.next()<.58,close=rng.next()<Math.max(.18,Math.min(.44,.28+strengthDiff*.006+(tactic.mentality==="Ofensiva"?.04:0))),xg=Math.max(.025,Math.min(.62,(close?.29:.08)+(central?.055:0)+strengthDiff*.004+rng.integer(-18,18)/1000));return Math.round(xg*1000)/1000;}
function zoneSample(rng:SeededRng,tactic:MatchTactic):"left"|"center"|"right"{const roll=rng.integer(1,100),center=tactic.formation==="4-2-3-1"?44:38;if(roll<=center)return"center";return roll<=center+(100-center)/2?"left":"right";}
function zonesFrom(samples:Array<"left"|"center"|"right">):AttackZones{const total=Math.max(1,samples.length),left=Math.round(samples.filter(v=>v==="left").length/total*100),center=Math.round(samples.filter(v=>v==="center").length/total*100);return{left,center,right:Math.max(0,100-left-center)};}

export function simulateMatch(home:LeagueClub,away:LeagueClub,seed:string,homeTactic:MatchTactic=DEFAULT_TACTIC,awayTactic:MatchTactic=DEFAULT_TACTIC,homeLineupIds?:string[],awayLineupIds?:string[]):MatchResult{
  const rng=new SeededRng(seed),homeXI=pickStartingXI(home,homeLineupIds),awayXI=pickStartingXI(away,awayLineupIds),sentHome=new Set<string>(),sentAway=new Set<string>();
  const homeStrength=strength(home,homeTactic,homeLineupIds)+2.2,awayStrength=strength(away,awayTactic,awayLineupIds),diff=homeStrength-awayStrength;
  const share=Math.max(36,Math.min(64,Math.round(50+diff*.8+rng.integer(-4,4))));
  const shotsHome=Math.max(4,Math.round(9+diff*.32+(homeTactic.tempo-50)*.06+rng.integer(-2,4))),shotsAway=Math.max(4,Math.round(9-diff*.28+(awayTactic.tempo-50)*.04+rng.integer(-2,3)));
  const events:MatchEvent[]=[{minute:0,type:"kickoff",team:"neutral",text:`Bola rolando. ${home.name} começa com a posse.`}],shotMap:ShotRecord[]=[],homeZones:Array<"left"|"center"|"right">=[],awayZones:Array<"left"|"center"|"right">=[];let homeGoals=0,awayGoals=0,xgHome=0,xgAway=0,bigChancesHome=0,bigChancesAway=0;
  const chances:Array<{minute:number;team:"home"|"away"}>=[];for(let i=0;i<shotsHome;i++)chances.push({minute:rng.integer(3,89),team:"home"});for(let i=0;i<shotsAway;i++)chances.push({minute:rng.integer(3,89),team:"away"});
  chances.sort((a,b)=>a.minute-b.minute).forEach(chance=>{const isHome=chance.team==="home",club=isHome?home:away,opponent=isHome?away:home,tactic=isHome?homeTactic:awayTactic,xi=(isHome?homeXI:awayXI).filter(p=>!(isHome?sentHome:sentAway).has(p.id)),strengthDiff=isHome?diff:-diff;if(!xi.length)return;const attacker=rng.pick(attackingPool(xi,tactic)),assist=assister(rng,xi,attacker),xg=xgForShot(rng,strengthDiff,tactic),goal=rng.next()<Math.max(.035,Math.min(.72,xg)),big=xg>=.25,zone=zoneSample(rng,tactic);if(isHome){xgHome+=xg;if(big)bigChancesHome++;homeZones.push(zone);}else{xgAway+=xg;if(big)bigChancesAway++;awayZones.push(zone);}shotMap.push({team:chance.team,minute:chance.minute,playerId:attacker.id,x:rng.integer(68,96),y:zone==="left"?rng.integer(12,38):zone==="right"?rng.integer(62,88):rng.integer(38,62),xg,goal,bigChance:big});if(goal){if(isHome)homeGoals++;else awayGoals++;events.push({minute:chance.minute,type:"goal",team:chance.team,playerId:attacker.id,assistPlayerId:assist?.id,text:`GOL DO ${club.shortName}! ${attacker.name} conclui uma chance de ${(xg).toFixed(2)} xG${assist?` após passe de ${assist.name}`:""}.`});}else events.push({minute:chance.minute,type:"chance",team:chance.team,playerId:attacker.id,text:big?`${attacker.name} desperdiça uma grande chance contra o ${opponent.shortName}.`:`${attacker.name} finaliza, mas a defesa do ${opponent.shortName} resiste.`});});
  events.push({minute:45,type:"halftime",team:"neutral",text:"Intervalo. As comissões ajustam posicionamento e intensidade."});
  for(const [team,xi,set] of [["home",homeXI,sentHome],["away",awayXI,sentAway]] as const){if(rng.next()<.095){const player=rng.pick(xi),minute=rng.integer(38,84);set.add(player.id);events.push({minute,type:"red_card",team,playerId:player.id,text:`CARTÃO VERMELHO! ${player.name} é expulso e sua equipe fica com um jogador a menos.`});}else if(rng.next()<.72){const player=rng.pick(xi);events.push({minute:rng.integer(22,83),type:"card",team,playerId:player.id,text:`Cartão amarelo para ${player.name}.`});}}
  for(const [team,xi] of [["home",homeXI],["away",awayXI]] as const)if(rng.next()<.08){const player=rng.pick(xi);events.push({minute:rng.integer(18,84),type:"injury",team,playerId:player.id,text:`${player.name} sente um problema físico e preocupa a comissão médica.`});}
  const passesHome=Math.round(235+share*4.4+rng.integer(-28,38)),passesAway=Math.round(235+(100-share)*4.4+rng.integer(-28,38)),tacklesHome=rng.integer(11,22),tacklesAway=rng.integer(11,22),interceptionsHome=rng.integer(7,18),interceptionsAway=rng.integer(7,18);
  events.push({minute:90,type:"fulltime",team:"neutral",text:`Fim de jogo: ${home.name} ${homeGoals} × ${awayGoals} ${away.name}.`});const order=["kickoff","chance","goal","card","red_card","injury","tactical","halftime","fulltime"];events.sort((a,b)=>a.minute-b.minute||(order.indexOf(a.type)-order.indexOf(b.type)));
  return{homeGoals,awayGoals,possessionHome:share,shotsHome,shotsAway,events,xgHome:Math.round(xgHome*100)/100,xgAway:Math.round(xgAway*100)/100,bigChancesHome,bigChancesAway,passesHome,passesAway,tacklesHome,tacklesAway,interceptionsHome,interceptionsAway,attackZonesHome:zonesFrom(homeZones),attackZonesAway:zonesFrom(awayZones),shotMap,redCardsHome:sentHome.size,redCardsAway:sentAway.size};
}
'''

live = r'''import { SeededRng } from "./rng";
import type { LeagueClub, LeaguePlayer } from "./league";
import { DEFAULT_TACTIC, pickStartingXI, type AttackZones, type MatchEvent, type MatchResult, type MatchTactic, type PlayerInstruction, type ShotRecord } from "./match";
import { tacticalFitMultiplier } from "./tactical-position";

export type LiveMatchPhase="pre_match"|"first_half"|"halftime"|"second_half_window"|"fulltime";
export type TeamTalk="Cobrar"|"Incentivar"|"Acalmar";export type MatchSide="home"|"away";export type MatchSpeed="normal"|"fast"|"very_fast";
export type LiveSubstitution={side:MatchSide;outPlayerId:string;inPlayerId:string;minute:number};export type LivePlayerState={condition:number;fatigue:number;rating:number;minutes:number};
export type LiveMatchState={seed:string;phase:LiveMatchPhase;currentMinute:number;userSide:MatchSide;homeLineupIds:string[];awayLineupIds:string[];homeBenchIds:string[];awayBenchIds:string[];maxSubstitutions:number;homeTactic:MatchTactic;awayTactic:MatchTactic;homeGoals:number;awayGoals:number;possessionHome:number;possessionSamples:number;shotsHome:number;shotsAway:number;xgHome:number;xgAway:number;bigChancesHome:number;bigChancesAway:number;passesHome:number;passesAway:number;tacklesHome:number;tacklesAway:number;interceptionsHome:number;interceptionsAway:number;attackZoneSamplesHome:Array<"left"|"center"|"right">;attackZoneSamplesAway:Array<"left"|"center"|"right">;shotMap:ShotRecord[];events:MatchEvent[];substitutions:LiveSubstitution[];injuredPlayerIds:string[];sentOffPlayerIds:string[];usedPlayerIds:string[];playerStates:Record<string,LivePlayerState>;teamTalk?:TeamTalk;};
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v)),round1=(v:number)=>Math.round(v*10)/10,round2=(v:number)=>Math.round(v*100)/100;
function availableBench(club:LeagueClub,lineupIds:string[],size=12){const selected=new Set(lineupIds);return club.players.filter(p=>p.injuryDays===0&&p.suspensionMatches===0&&!selected.has(p.id)).sort((a,b)=>b.overall-a.overall).slice(0,size).map(p=>p.id)}
function selectedBench(club:LeagueClub,lineupIds:string[],benchIds:string[]|undefined,size:number){if(!benchIds?.length)return availableBench(club,lineupIds,size);const starters=new Set(lineupIds);return benchIds.filter((id,index)=>benchIds.indexOf(id)===index&&!starters.has(id)&&club.players.some(p=>p.id===id&&p.injuryDays===0&&p.suspensionMatches===0)).slice(0,size)}
function exactLineup(club:LeagueClub,ids:string[]){return ids.map(id=>club.players.find(p=>p.id===id)).filter((p):p is LeaguePlayer=>Boolean(p))}function activePhase(s:LiveMatchState){return s.phase==="first_half"||s.phase==="second_half_window"}function canDecide(s:LiveMatchState){return activePhase(s)||s.phase==="halftime"}function livePlayerState(s:LiveMatchState,p:LeaguePlayer){return s.playerStates[p.id]??{condition:p.condition,fatigue:p.fatigue,rating:6,minutes:0}}
function roleFactor(t:MatchTactic,id:string){const role=t.roles?.[id]??"Livre";return role==="Atacar"?1.018:role==="Apoio"?1.008:role==="Segurar"?.995:1}
function strength(s:LiveMatchState,club:LeagueClub,lineupIds:string[],tactic:MatchTactic,momentum=0){const lineup=exactLineup(club,lineupIds);if(!lineup.length)return35;const base=lineup.reduce((sum,p)=>{const live=livePlayerState(s,p);return sum+p.overall*(live.condition/100)*(.92+p.morale/1250)*Math.max(.72,1-live.fatigue/210)*tacticalFitMultiplier(p,tactic.positions?.[p.id])*roleFactor(tactic,p.id)},0)/11,mentality=tactic.mentality==="Ofensiva"?2.2:tactic.mentality==="Defensiva"?-.9:0;return base+mentality+(tactic.pressing-50)*.026+(tactic.tempo-50)*.021+momentum-Math.max(0,11-lineup.length)*3.2}
function attackingPlayer(rng:SeededRng,lineup:LeaguePlayer[],tactic:MatchTactic){const candidates=lineup.filter(p=>["ATA","PE","PD","MEI","MC"].includes(p.position)),base=candidates.length?candidates:lineup,pool=base.flatMap(p=>tactic.roles?.[p.id]==="Atacar"?[p,p,p]:tactic.roles?.[p.id]==="Apoio"?[p,p]:[p]);return rng.pick(pool)}function assistPlayer(rng:SeededRng,lineup:LeaguePlayer[],scorer:LeaguePlayer){const pool=lineup.filter(p=>p.id!==scorer.id&&["ATA","PE","PD","MEI","MC","VOL"].includes(p.position));return pool.length&&rng.next()<.72?rng.pick(pool):undefined}
function teamTalkMomentum(s:LiveMatchState,minute:number){if(minute>68)return 0;const decay=Math.max(0,1-(minute-46)/25),winning=s.userSide==="home"?s.homeGoals>s.awayGoals:s.awayGoals>s.homeGoals,losing=s.userSide==="home"?s.homeGoals<s.awayGoals:s.awayGoals<s.homeGoals,raw=s.teamTalk==="Cobrar"?(losing?1.7:winning?-.2:.9):s.teamTalk==="Incentivar"?1:s.teamTalk==="Acalmar"?(winning?.8:.25):0;return raw*decay}
function minuteRng(s:LiveMatchState,minute:number){const tactics=`${s.homeTactic.formation}:${s.homeTactic.mentality}:${s.homeTactic.pressing}:${s.homeTactic.tempo}:${s.awayTactic.formation}:${s.awayTactic.mentality}:${s.awayTactic.pressing}:${s.awayTactic.tempo}`;return new SeededRng(`${s.seed}:m${minute}:${s.substitutions.length}:${s.homeGoals}-${s.awayGoals}:${tactics}`)}
function initializePlayerStates(home:LeagueClub,away:LeagueClub){const states:Record<string,LivePlayerState>={};for(const p of [...home.players,...away.players])states[p.id]={condition:p.condition,fatigue:p.fatigue,rating:6,minutes:0};return states}function adjustRating(states:Record<string,LivePlayerState>,id:string|undefined,delta:number){if(!id||!states[id])return;states[id]={...states[id],rating:round2(clamp(states[id].rating+delta,4,10))}}
function applyMinuteWear(s:LiveMatchState,home:LeagueClub,away:LeagueClub,minute:number){const states=Object.fromEntries(Object.entries(s.playerStates).map(([id,v])=>[id,{...v}]));for(const[side,club,lineupIds,tactic]of[["home",home,s.homeLineupIds,s.homeTactic],["away",away,s.awayLineupIds,s.awayTactic]]as const){for(const p of exactLineup(club,lineupIds)){const current=states[p.id]??{condition:p.condition,fatigue:p.fatigue,rating:6,minutes:0},intensity=((tactic.pressing-20)/70)*.045+((tactic.tempo-20)/70)*.035,ageLoad=p.age>=33?.018:p.age<=21?-.006:0,existingLoad=current.fatigue>=70?.025:current.fatigue>=50?.012:0;let rating=current.rating;if(current.condition<68)rating-=.004;if(current.condition<58)rating-=.006;states[p.id]={condition:round1(clamp(current.condition-(.045+intensity+ageLoad+existingLoad),35,100)),fatigue:round1(clamp(current.fatigue+.055+intensity*1.35+ageLoad,0,100)),rating:round2(clamp(rating,4,10)),minutes:current.minutes+1}}const leading=side==="home"?s.homeGoals>s.awayGoals:s.awayGoals>s.homeGoals;if(leading&&minute>60)for(const id of lineupIds)adjustRating(states,id,.0015)}return states}
function zone(rng:SeededRng,t:MatchTactic):"left"|"center"|"right"{const r=rng.integer(1,100),center=t.formation==="4-2-3-1"?44:38;return r<=center?"center":r<=center+(100-center)/2?"left":"right"}function zones(samples:Array<"left"|"center"|"right">):AttackZones{const total=Math.max(1,samples.length),left=Math.round(samples.filter(v=>v==="left").length/total*100),center=Math.round(samples.filter(v=>v==="center").length/total*100);return{left,center,right:Math.max(0,100-left-center)}}
export function createLiveMatch(home:LeagueClub,away:LeagueClub,seed:string,userSide:MatchSide,userLineupIds:string[],userTactic:MatchTactic=DEFAULT_TACTIC,userBenchIds?:string[],benchSize=12,maxSubstitutions=5,aiTactic:MatchTactic=DEFAULT_TACTIC):LiveMatchState{const homeIds=userSide==="home"?pickStartingXI(home,userLineupIds).map(p=>p.id):pickStartingXI(home).map(p=>p.id),awayIds=userSide==="away"?pickStartingXI(away,userLineupIds).map(p=>p.id):pickStartingXI(away).map(p=>p.id);return{seed,phase:"pre_match",currentMinute:0,userSide,homeLineupIds:homeIds,awayLineupIds:awayIds,homeBenchIds:userSide==="home"?selectedBench(home,homeIds,userBenchIds,benchSize):availableBench(home,homeIds,benchSize),awayBenchIds:userSide==="away"?selectedBench(away,awayIds,userBenchIds,benchSize):availableBench(away,awayIds,benchSize),maxSubstitutions,homeTactic:userSide==="home"?userTactic:aiTactic,awayTactic:userSide==="away"?userTactic:aiTactic,homeGoals:0,awayGoals:0,possessionHome:50,possessionSamples:0,shotsHome:0,shotsAway:0,xgHome:0,xgAway:0,bigChancesHome:0,bigChancesAway:0,passesHome:0,passesAway:0,tacklesHome:0,tacklesAway:0,interceptionsHome:0,interceptionsAway:0,attackZoneSamplesHome:[],attackZoneSamplesAway:[],shotMap:[],events:[{minute:0,type:"kickoff",team:"neutral",text:`Tudo pronto para ${home.name} × ${away.name}.`}],substitutions:[],injuredPlayerIds:[],sentOffPlayerIds:[],usedPlayerIds:[...new Set([...homeIds,...awayIds])],playerStates:initializePlayerStates(home,away)}}
export function startLiveMatch(s:LiveMatchState,home:LeagueClub){return s.phase!=="pre_match"?s:{...s,phase:"first_half",events:[...s.events,{minute:0,type:"kickoff",team:"neutral",text:`Bola rolando. ${home.name} dá a saída.`}]}}
export function resumeSecondHalf(s:LiveMatchState){if(s.phase!=="halftime"||requiredUserSubstitutions(s).length)return s;const talk=s.teamTalk?` A mensagem no vestiário foi: ${s.teamTalk.toLowerCase()}.`:"";return{...s,phase:"second_half_window",events:[...s.events,{minute:46,type:"kickoff",team:"neutral",text:`Começa o segundo tempo.${talk}`}]}}
function autoReplaceInjuries(s:LiveMatchState,side:MatchSide){if(side===s.userSide)return s;let next=s;const lineup=()=>side==="home"?next.homeLineupIds:next.awayLineupIds,bench=()=>side==="home"?next.homeBenchIds:next.awayBenchIds;for(const injured of [...next.injuredPlayerIds])if(lineup().includes(injured)&&bench().length)next=makeSubstitution(next,side,injured,bench()[0]);return next}
function autoAiDecision(s:LiveMatchState,home:LeagueClub,away:LeagueClub,minute:number){const side:s["userSide"]=s.userSide==="home"?"away":"home",club=side==="home"?home:away,lineup=side==="home"?s.homeLineupIds:s.awayLineupIds,bench=side==="home"?s.homeBenchIds:s.awayBenchIds,subs=s.substitutions.filter(x=>x.side===side).length;let next=s;if([58,68,78].includes(minute)&&subs<(s.maxSubstitutions??5)&&bench.length){const candidates=lineup.map(id=>({id,state:s.playerStates[id]})).filter(x=>x.state&&!s.sentOffPlayerIds.includes(x.id)).sort((a,b)=>(a.state?.condition??100)-(b.state?.condition??100));if(candidates[0]&&(candidates[0].state?.condition??100)<76)next=makeSubstitution(next,side,candidates[0].id,bench[0])}const losing=side==="home"?next.homeGoals<next.awayGoals:next.awayGoals<next.homeGoals,winning=side==="home"?next.homeGoals>next.awayGoals:next.awayGoals>next.homeGoals;if((minute===65&&losing)||(minute===76&&(losing||winning))){const tactic=side==="home"?next.homeTactic:next.awayTactic,changed={...tactic,mentality:losing?"Ofensiva" as const:winning?"Defensiva" as const:tactic.mentality,pressing:Math.round(clamp(tactic.pressing+(losing?8:-7),25,90)),tempo:Math.round(clamp(tactic.tempo+(losing?7:-6),25,90))};next=side==="home"?{...next,homeTactic:changed}:{...next,awayTactic:changed};next={...next,events:[...next.events,{minute,type:"tactical",team:side,text:`A comissão do ${club.shortName} muda o plano: ${changed.mentality.toLowerCase()}, pressão ${changed.pressing} e ritmo ${changed.tempo}.`}]}}return next}
export function advanceLiveMatchMinute(s:LiveMatchState,home:LeagueClub,away:LeagueClub):LiveMatchState{if(!activePhase(s)||requiredUserSubstitutions(s).length)return s;const minute=s.currentMinute+1;if(minute>90)return s;const rng=minuteRng(s,minute),playerStates=applyMinuteWear(s,home,away,minute),working={...s,playerStates},homeLineup=exactLineup(home,s.homeLineupIds),awayLineup=exactLineup(away,s.awayLineupIds),momentum=minute>=46?teamTalkMomentum(s,minute):0,homeStrength=strength(working,home,s.homeLineupIds,s.homeTactic,s.userSide==="home"?momentum:0)+2,awayStrength=strength(working,away,s.awayLineupIds,s.awayTactic,s.userSide==="away"?momentum:0),diff=homeStrength-awayStrength,targetPossession=Math.max(32,Math.min(68,50+diff*.72+rng.integer(-5,5))),samples=s.possessionSamples+1,possessionHome=Math.round((s.possessionHome*s.possessionSamples+targetPossession)/samples);let homeGoals=s.homeGoals,awayGoals=s.awayGoals,shotsHome=s.shotsHome,shotsAway=s.shotsAway,xgHome=s.xgHome,xgAway=s.xgAway,bigChancesHome=s.bigChancesHome,bigChancesAway=s.bigChancesAway;const events:MatchEvent[]=[],injured=[...s.injuredPlayerIds],sentOff=[...s.sentOffPlayerIds],shotMap=[...s.shotMap],zonesHome=[...s.attackZoneSamplesHome],zonesAway=[...s.attackZoneSamplesAway];const passesHome=s.passesHome+rng.integer(3,9),passesAway=s.passesAway+rng.integer(3,9),tacklesHome=s.tacklesHome+(rng.next()<.17?1:0),tacklesAway=s.tacklesAway+(rng.next()<.17?1:0),interceptionsHome=s.interceptionsHome+(rng.next()<.12?1:0),interceptionsAway=s.interceptionsAway+(rng.next()<.12?1:0);
 const attack=(side:MatchSide)=>{const isHome=side==="home",lineup=(isHome?homeLineup:awayLineup).filter(p=>!sentOff.includes(p.id)),currentClub=isHome?home:away,opponent=isHome?away:home,tactic=isHome?s.homeTactic:s.awayTactic,strengthDiff=isHome?diff:-diff;if(!lineup.length)return;const shotChance=Math.max(.05,Math.min(.2,.093+strengthDiff*.003+(tactic.tempo-50)*.0008+(tactic.mentality==="Ofensiva"?.018:tactic.mentality==="Defensiva"?-.012:0)));if(rng.next()>=shotChance)return;if(isHome)shotsHome++;else shotsAway++;const player=attackingPlayer(rng,lineup,tactic),central=rng.next()<.58,close=rng.next()<Math.max(.17,Math.min(.46,.27+strengthDiff*.006)),xg=round2(Math.max(.025,Math.min(.62,(close?.29:.08)+(central?.055:0)+strengthDiff*.004+rng.integer(-15,15)/1000))),big=xg>=.25,goal=rng.next()<xg,area=zone(rng,tactic);if(isHome){xgHome+=xg;if(big)bigChancesHome++;zonesHome.push(area)}else{xgAway+=xg;if(big)bigChancesAway++;zonesAway.push(area)}shotMap.push({team:side,minute,playerId:player.id,x:rng.integer(68,96),y:area==="left"?rng.integer(12,38):area==="right"?rng.integer(62,88):rng.integer(38,62),xg,goal,bigChance:big});adjustRating(playerStates,player.id,.07);if(goal){if(isHome)homeGoals++;else awayGoals++;const assist=assistPlayer(rng,lineup,player);adjustRating(playerStates,player.id,.92);adjustRating(playerStates,assist?.id,.48);for(const id of(isHome?s.awayLineupIds:s.homeLineupIds))adjustRating(playerStates,id,-.035);events.push({minute,type:"goal",team:side,playerId:player.id,assistPlayerId:assist?.id,text:`GOL DO ${currentClub.shortName}! ${player.name} converte uma chance de ${xg.toFixed(2)} xG${assist?` após passe de ${assist.name}`:""}.`})}else events.push({minute,type:"chance",team:side,playerId:player.id,text:big?`${player.name} desperdiça uma grande chance do ${currentClub.shortName}.`:`${player.name} finaliza com ${xg.toFixed(2)} xG e o ${opponent.shortName} resiste.`})};attack("home");attack("away");
 for(const side of["home","away"]as const){const lineup=(side==="home"?homeLineup:awayLineup).filter(p=>!sentOff.includes(p.id));if(!lineup.length)continue;if(rng.next()<.0105){const p=rng.pick(lineup);adjustRating(playerStates,p.id,-.85);events.push({minute,type:"red_card",team:side,playerId:p.id,text:`CARTÃO VERMELHO! ${p.name} é expulso e deixa sua equipe em inferioridade numérica.`});sentOff.push(p.id)}else if(rng.next()<.011){const p=rng.pick(lineup);adjustRating(playerStates,p.id,-.2);events.push({minute,type:"card",team:side,playerId:p.id,text:`Cartão amarelo para ${p.name}.`})}if(rng.next()<.00085){const p=rng.pick(lineup);if(!injured.includes(p.id)&&!sentOff.includes(p.id))injured.push(p.id);adjustRating(playerStates,p.id,-.08);events.push({minute,type:"injury",team:side,playerId:p.id,text:`${p.name} sente um problema físico e pede atendimento.`})}}
 let homeIds=s.homeLineupIds.filter(id=>!sentOff.includes(id)),awayIds=s.awayLineupIds.filter(id=>!sentOff.includes(id));let next:LiveMatchState={...s,currentMinute:minute,homeLineupIds:homeIds,awayLineupIds:awayIds,homeGoals,awayGoals,shotsHome,shotsAway,xgHome:round2(xgHome),xgAway:round2(xgAway),bigChancesHome,bigChancesAway,passesHome,passesAway,tacklesHome,tacklesAway,interceptionsHome,interceptionsAway,possessionHome,possessionSamples:samples,injuredPlayerIds:injured,sentOffPlayerIds:sentOff,shotMap,attackZoneSamplesHome:zonesHome,attackZoneSamplesAway:zonesAway,events:[...s.events,...events],playerStates};next=autoReplaceInjuries(autoReplaceInjuries(next,"home"),"away");next=autoAiDecision(next,home,away,minute);if(minute===45)next={...next,phase:"halftime",events:[...next.events,{minute:45,type:"halftime",team:"neutral",text:`Intervalo: ${home.name} ${homeGoals} × ${awayGoals} ${away.name}.`}]};if(minute===90)next={...next,phase:"fulltime",events:[...next.events,{minute:90,type:"fulltime",team:"neutral",text:`Fim de jogo: ${home.name} ${homeGoals} × ${awayGoals} ${away.name}.`}]};return next}
export function updateLiveTactic(s:LiveMatchState,side:MatchSide,tactic:MatchTactic){if(!canDecide(s))return s;return side==="home"?{...s,homeTactic:tactic}:{...s,awayTactic:tactic}}export function updatePlayerRole(s:LiveMatchState,side:MatchSide,playerId:string,role:PlayerInstruction){if(!canDecide(s)&&s.phase!=="pre_match")return s;const tactic=side==="home"?s.homeTactic:s.awayTactic,roles={...(tactic.roles??{}),[playerId]:role};return updateLiveTactic({...s,phase:s.phase},side,{...tactic,roles})}export function setTeamTalk(s:LiveMatchState,talk:TeamTalk){return s.phase==="halftime"?{...s,teamTalk:talk}:s}
export function makeSubstitution(s:LiveMatchState,side:MatchSide,outPlayerId:string,inPlayerId:string):LiveMatchState{if(!canDecide(s))return s;const sideSubs=s.substitutions.filter(x=>x.side===side);if(sideSubs.length>=(s.maxSubstitutions??5))return s;const lineup=side==="home"?s.homeLineupIds:s.awayLineupIds,bench=side==="home"?s.homeBenchIds:s.awayBenchIds;if(!lineup.includes(outPlayerId)||!bench.includes(inPlayerId)||s.sentOffPlayerIds.includes(inPlayerId))return s;const nextLineup=lineup.map(id=>id===outPlayerId?inPlayerId:id),nextBench=bench.filter(id=>id!==inPlayerId),minute=s.phase==="halftime"?46:Math.max(1,s.currentMinute),next={...s,substitutions:[...s.substitutions,{side,outPlayerId,inPlayerId,minute}],usedPlayerIds:[...new Set([...s.usedPlayerIds,inPlayerId])],injuredPlayerIds:s.injuredPlayerIds.filter(id=>id!==outPlayerId),events:[...s.events,{minute,type:"tactical" as const,team:side,text:`Substituição aos ${minute}': mudança preparada pela comissão técnica.`}]};return side==="home"?{...next,homeLineupIds:nextLineup,homeBenchIds:nextBench}:{...next,awayLineupIds:nextLineup,awayBenchIds:nextBench}}
export function requiredUserSubstitutions(s:LiveMatchState){const lineup=s.userSide==="home"?s.homeLineupIds:s.awayLineupIds;return s.injuredPlayerIds.filter(id=>lineup.includes(id)&&!s.sentOffPlayerIds.includes(id))}export function isLiveMatchRunning(s:LiveMatchState){return activePhase(s)&&s.currentMinute<90}function legacyAutoResolve(s:LiveMatchState){let next=s;for(const id of requiredUserSubstitutions(next)){const bench=next.userSide==="home"?next.homeBenchIds:next.awayBenchIds;if(bench[0])next=makeSubstitution(next,next.userSide,id,bench[0])}return next}export function playFirstHalf(s:LiveMatchState,home:LeagueClub,away:LeagueClub){let next=startLiveMatch(s,home);while(next.phase==="first_half"){next=legacyAutoResolve(next);next=advanceLiveMatchMinute(next,home,away)}return next}export function playSecondHalf(s:LiveMatchState,home:LeagueClub,away:LeagueClub){let next=resumeSecondHalf(legacyAutoResolve(s));while(next.phase==="second_half_window"&&next.currentMinute<70){next=legacyAutoResolve(next);next=advanceLiveMatchMinute(next,home,away)}return next}export function playFinalMinutes(s:LiveMatchState,home:LeagueClub,away:LeagueClub){let next=s.phase==="halftime"?resumeSecondHalf(legacyAutoResolve(s)):legacyAutoResolve(s);while(next.phase==="second_half_window"){next=legacyAutoResolve(next);next=advanceLiveMatchMinute(next,home,away)}return next}
export function liveMatchResult(s:LiveMatchState):MatchResult|null{if(s.phase!=="fulltime")return null;const playerRatings:Record<string,number>={},playerConditionAfter:Record<string,number>={},playerFatigueAfter:Record<string,number>={},playerMinutes:Record<string,number>={};for(const id of s.usedPlayerIds){const live=s.playerStates[id];if(!live)continue;playerRatings[id]=round2(live.rating);playerConditionAfter[id]=round1(live.condition);playerFatigueAfter[id]=round1(live.fatigue);playerMinutes[id]=live.minutes}return{homeGoals:s.homeGoals,awayGoals:s.awayGoals,possessionHome:s.possessionHome,shotsHome:s.shotsHome,shotsAway:s.shotsAway,events:s.events,playerRatings,playerConditionAfter,playerFatigueAfter,playerMinutes,xgHome:round2(s.xgHome),xgAway:round2(s.xgAway),bigChancesHome:s.bigChancesHome,bigChancesAway:s.bigChancesAway,passesHome:s.passesHome,passesAway:s.passesAway,tacklesHome:s.tacklesHome,tacklesAway:s.tacklesAway,interceptionsHome:s.interceptionsHome,interceptionsAway:s.interceptionsAway,attackZonesHome:zones(s.attackZoneSamplesHome),attackZonesAway:zones(s.attackZoneSamplesAway),shotMap:s.shotMap,redCardsHome:s.sentOffPlayerIds.filter(id=>homeIds(s).includes(id)).length,redCardsAway:s.sentOffPlayerIds.filter(id=>awayIds(s).includes(id)).length}}
function homeIds(s:LiveMatchState){return[...new Set([...s.homeLineupIds,...s.substitutions.filter(x=>x.side==="home").map(x=>x.outPlayerId)])]}function awayIds(s:LiveMatchState){return[...new Set([...s.awayLineupIds,...s.substitutions.filter(x=>x.side==="away").map(x=>x.outPlayerId])]}
'''

world = r'''import { SeededRng } from "./rng";
import { PROFESSIONAL_COMPETITIONS, type ProfessionalCompetitionId } from "../data/brazil-2026/competitions";
import { createLeague, type LeagueClub, type LeagueWorld } from "./league";
import type { MatchResult } from "./match";
export type WorldCompetitionId="CDB"|"LIB"|"SUD"|"FAC"|"CDR"|"CDF"|"UCL"|"UEL"|"UECL";export type WorldCompetitionKind="Copa nacional"|"Continental";
export type WorldCompetitionDefinition={id:WorldCompetitionId;name:string;shortName:string;country?:string;kind:WorldCompetitionKind;participants:number;roundInterval:number;startRound:number};
export type WorldParticipant={id:string;name:string;shortName:string;country:string;reputation:number;activeClubId?:string};
export type WorldCompetitionMatch={id:string;competitionId:WorldCompetitionId;stage:string;roundDue:number;date:string;home:WorldParticipant;away:WorldParticipant;played:boolean;homeGoals?:number;awayGoals?:number;winnerId?:string;shootoutHome?:number;shootoutAway?:number};
export type WorldTournamentState={definition:WorldCompetitionDefinition;participants:WorldParticipant[];matches:WorldCompetitionMatch[];currentStage:string;championId?:string;completed:boolean};export type WorldCompetitionsState={season:number;tournaments:WorldTournamentState[];lastProcessedRound?:number;history:Array<{year:number;competitionId:WorldCompetitionId;competitionName:string;championName:string}>};
export const WORLD_COMPETITIONS:WorldCompetitionDefinition[]=[{id:"CDB",name:"Copa do Brasil",shortName:"Copa do Brasil",country:"Brasil",kind:"Copa nacional",participants:32,roundInterval:4,startRound:3},{id:"LIB",name:"CONMEBOL Libertadores",shortName:"Libertadores",kind:"Continental",participants:32,roundInterval:4,startRound:4},{id:"SUD",name:"CONMEBOL Sudamericana",shortName:"Sul-Americana",kind:"Continental",participants:32,roundInterval:4,startRound:5},{id:"FAC",name:"FA Cup",shortName:"FA Cup",country:"Inglaterra",kind:"Copa nacional",participants:32,roundInterval:4,startRound:3},{id:"CDR",name:"Copa del Rey",shortName:"Copa del Rey",country:"Espanha",kind:"Copa nacional",participants:32,roundInterval:4,startRound:3},{id:"CDF",name:"Coupe de France",shortName:"Coupe de France",country:"França",kind:"Copa nacional",participants:32,roundInterval:4,startRound:3},{id:"UCL",name:"UEFA Champions League",shortName:"Champions League",kind:"Continental",participants:32,roundInterval:4,startRound:4},{id:"UEL",name:"UEFA Europa League",shortName:"Europa League",kind:"Continental",participants:32,roundInterval:4,startRound:5},{id:"UECL",name:"UEFA Conference League",shortName:"Conference League",kind:"Continental",participants:32,roundInterval:4,startRound:6}];
function addDays(iso:string,days:number){const d=new Date(`${iso}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}function rep(value:number){return value>=1e9?95:value>=6e8?90:value>=3e8?84:value>=1.5e8?78:value>=7e7?72:value>=3e7?66:value>=1.2e7?59:52}function country(id:ProfessionalCompetitionId){return id.startsWith("BRA")?"Brasil":id==="ENG1"?"Inglaterra":id==="ESP1"?"Espanha":"França"}function roundDate(league:LeagueWorld,round:number){return league.fixtures.find(f=>f.round===round)?.date??league.fixtures[0]?.date??`${new Date().getUTCFullYear()}-01-15`}function dateFor(league:LeagueWorld,round:number,def:WorldCompetitionDefinition){const base=roundDate(league,Math.max(1,round)),offset=def.kind==="Copa nacional"?-3:def.id==="LIB"||def.id==="UCL"?2:def.id==="SUD"||def.id==="UEL"?3:1;return addDays(base,offset)}
function allParticipants(active:ProfessionalCompetitionId,league:LeagueWorld){const local=league.clubs.map(c=>({id:`active:${c.id}`,name:c.name,shortName:c.shortName,country:country(active),reputation:c.reputation,activeClubId:c.id})),external=PROFESSIONAL_COMPETITIONS.flatMap(comp=>comp.id===active?[]:comp.clubs.map(c=>({id:`ext:${comp.id}:${c.transfermarktId}`,name:c.name,shortName:c.shortName,country:comp.country,reputation:rep(c.marketValueEur)})));return[...local,...external]}
function activeBand(def:WorldCompetitionDefinition,ranked:WorldParticipant[]){const active=ranked.filter(p=>p.activeClubId);if(def.kind==="Copa nacional")return active;if(def.id==="LIB"||def.id==="UCL")return active.slice(0,6);if(def.id==="SUD"||def.id==="UEL")return active.slice(6,12);if(def.id==="UECL")return active.slice(12,18);return active}
function choose(def:WorldCompetitionDefinition,pool:WorldParticipant[],activeCountry:string){let candidates=def.kind==="Copa nacional"?pool.filter(p=>p.country===def.country):(def.id==="LIB"||def.id==="SUD")?pool.filter(p=>p.country==="Brasil"):pool.filter(p=>["Inglaterra","Espanha","França"].includes(p.country));const ranked=[...candidates].sort((a,b)=>b.reputation-a.reputation),band=activeBand(def,ranked),selected:WorldParticipant[]=[];for(const p of band)if(selected.length<Math.min(6,def.participants))selected.push(p);let externalRanked=ranked.filter(p=>!p.activeClubId);if(def.id==="SUD"||def.id==="UEL")externalRanked=externalRanked.slice(Math.min(6,externalRanked.length));if(def.id==="UECL")externalRanked=externalRanked.slice(Math.min(12,externalRanked.length));for(const p of [...externalRanked,...ranked])if(selected.length<def.participants&&!selected.some(x=>x.id===p.id))selected.push(p);while(selected.length>2&&(selected.length&(selected.length-1))!==0)selected.pop();return selected}
function stage(count:number){return count>=32?"16 avos":count===16?"Oitavas de final":count===8?"Quartas de final":count===4?"Semifinal":"Final"}function pair(def:WorldCompetitionDefinition,participants:WorldParticipant[],stageName:string,roundDue:number,date:string,rng:SeededRng){const shuffled=[...participants];for(let i=shuffled.length-1;i>0;i--){const j=rng.integer(0,i);[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]]}const matches:WorldCompetitionMatch[]=[];for(let i=0;i<shuffled.length;i+=2)if(shuffled[i+1])matches.push({id:`${def.id}:${stageName}:${roundDue}:${i/2}`,competitionId:def.id,stage:stageName,roundDue,date,home:shuffled[i],away:shuffled[i+1],played:false});return matches}
function simulate(m:WorldCompetitionMatch,rng:SeededRng){const delta=(m.home.reputation-m.away.reputation)*.035+.2;let hg=Math.max(0,rng.integer(0,2)+(delta>1?1:0)),ag=Math.max(0,rng.integer(0,2)+(delta<-1?1:0));if(hg===ag){m.shootoutHome=rng.integer(3,5);m.shootoutAway=rng.integer(2,5);if(m.shootoutHome===m.shootoutAway)m.shootoutHome++;}m.homeGoals=hg;m.awayGoals=ag;m.played=true;m.winnerId=hg>ag?m.home.id:ag>hg?m.away.id:(m.shootoutHome??0)>(m.shootoutAway??0)?m.home.id:m.away.id}
function advance(t:WorldTournamentState,state:WorldCompetitionsState,round:number,seed:string){const stageMatches=t.matches.filter(m=>m.stage===t.currentStage);if(!stageMatches.length||!stageMatches.every(m=>m.played))return;const winners=stageMatches.map(m=>m.winnerId===m.home.id?m.home:m.away);if(winners.length===1){t.completed=true;t.championId=winners[0].id;if(!state.history.some(h=>h.year===state.season&&h.competitionId===t.definition.id))state.history.unshift({year:state.season,competitionId:t.definition.id,competitionName:t.definition.name,championName:winners[0].name});return}const nextStage=stage(winners.length),roundDue=Math.max(round,...stageMatches.map(m=>m.roundDue))+t.definition.roundInterval,date=addDays(stageMatches.map(m=>m.date).sort().at(-1)??`${state.season}-01-15`,Math.max(10,t.definition.roundInterval*5)),rng=new SeededRng(`${seed}:${t.definition.id}:${nextStage}:${roundDue}`);t.currentStage=nextStage;t.matches.push(...pair(t.definition,winners,nextStage,roundDue,date,rng))}
export function createWorldCompetitions(active:ProfessionalCompetitionId,league:LeagueWorld,year:number,seed:string):WorldCompetitionsState{const rng=new SeededRng(`${seed}:world-competitions:${year}`),pool=allParticipants(active,league),activeCountry=country(active),relevant=WORLD_COMPETITIONS.filter(def=>def.kind==="Continental"||def.country===activeCountry),tournaments=relevant.map(def=>{const participants=choose(def,pool,activeCountry),stageName=stage(participants.length),matches=pair(def,participants,stageName,def.startRound,dateFor(league,def.startRound,def),rng);return{definition:def,participants,matches,currentStage:stageName,completed:false} satisfies WorldTournamentState});return{season:year,tournaments,history:[]}}
export function hydrateWorldCompetitions(s:WorldCompetitionsState|undefined,active:ProfessionalCompetitionId,league:LeagueWorld,year:number,seed:string){return s??createWorldCompetitions(active,league,year,seed)}
export function processWorldCompetitions(s:WorldCompetitionsState,round:number,seed:string,userClubId?:string){if(s.lastProcessedRound===round)return s;const next:WorldCompetitionsState={...s,lastProcessedRound:round,tournaments:s.tournaments.map(t=>({...t,participants:[...t.participants],matches:t.matches.map(m=>({...m,home:{...m.home},away:{...m.away}}))})),history:[...s.history]},rng=new SeededRng(`${seed}:world-cups:r${round}`);for(const t of next.tournaments){if(t.completed)continue;for(const m of t.matches.filter(m=>!m.played&&m.roundDue<=round)){const userInvolved=userClubId&&(m.home.activeClubId===userClubId||m.away.activeClubId===userClubId);if(!userInvolved)simulate(m,rng)}advance(t,next,round,seed)}return next}
export function completeWorldCompetitionMatch(s:WorldCompetitionsState,matchId:string,result:MatchResult,seed:string){const next:WorldCompetitionsState={...s,tournaments:s.tournaments.map(t=>({...t,participants:[...t.participants],matches:t.matches.map(m=>({...m,home:{...m.home},away:{...m.away}}))})),history:[...s.history]},t=next.tournaments.find(t=>t.matches.some(m=>m.id===matchId)),m=t?.matches.find(m=>m.id===matchId);if(!t||!m||m.played)return next;m.homeGoals=result.homeGoals;m.awayGoals=result.awayGoals;m.played=true;if(result.homeGoals===result.awayGoals){const rng=new SeededRng(`${seed}:pens:${matchId}:${result.homeGoals}-${result.awayGoals}`);m.shootoutHome=rng.integer(3,5);m.shootoutAway=rng.integer(2,5);if(m.shootoutHome===m.shootoutAway)m.shootoutAway++;m.winnerId=(m.shootoutHome??0)>(m.shootoutAway??0)?m.home.id:m.away.id}else m.winnerId=result.homeGoals>result.awayGoals?m.home.id:m.away.id;advance(t,next,m.roundDue,seed);return next}
export function todayWorldCompetitionMatch(s:WorldCompetitionsState,clubId:string,date:string){return s.tournaments.flatMap(t=>t.matches.map(match=>({tournament:t,match}))).filter(x=>!x.match.played&&x.match.date===date&&(x.match.home.activeClubId===clubId||x.match.away.activeClubId===clubId)).sort((a,b)=>a.match.date.localeCompare(b.match.date))[0]}
export function nextUserWorldCompetitionMatch(s:WorldCompetitionsState,clubId:string,fromDate?:string){return s.tournaments.flatMap(t=>t.matches.map(match=>({tournament:t,match}))).filter(x=>!x.match.played&&(x.match.home.activeClubId===clubId||x.match.away.activeClubId===clubId)&&(!fromDate||x.match.date>=fromDate)).sort((a,b)=>a.match.date.localeCompare(b.match.date))[0]}
export function userWorldCompetitionMatches(s:WorldCompetitionsState,clubId:string){return s.tournaments.flatMap(t=>t.matches.filter(m=>m.home.activeClubId===clubId||m.away.activeClubId===clubId).map(match=>({tournament:t,match}))).sort((a,b)=>a.match.date.localeCompare(b.match.date))}
function cloneExternal(club:LeagueClub,prefix:string):LeagueClub{return{...club,id:prefix,players:club.players.map(p=>({...p,id:`${prefix}:${p.id}`,contract:{...p.contract},promises:p.promises.map(x=>({...x})),overallHistory:p.overallHistory.map(x=>({...x}))}))}}
export function worldParticipantClub(participant:WorldParticipant,activeLeague:LeagueWorld,year:number,seed:string):LeagueClub{if(participant.activeClubId){const club=activeLeague.clubs.find(c=>c.id===participant.activeClubId);if(club)return club}const parts=participant.id.split(":"),competitionId=parts[1] as ProfessionalCompetitionId,tmId=Number(parts[2]),external=createLeague(`${seed}:world-opponent:${competitionId}:${year}`,year,competitionId),club=external.clubs.find(c=>c.transfermarktId===tmId)??external.clubs[0];return cloneExternal(club,participant.id)}
export function prepareWorldCompetitionsNextSeason(s:WorldCompetitionsState,active:ProfessionalCompetitionId,league:LeagueWorld,year:number,seed:string){const fresh=createWorldCompetitions(active,league,year,seed);fresh.history=[...s.history].slice(0,100);return fresh}
'''

Path('src/game-engine/match.ts').write_text(match)
Path('src/game-engine/live-match.ts').write_text(live)
Path('src/game-engine/world-competitions.ts').write_text(world)

# Development: red-card statistics and rating effect.
p=Path('src/game-engine/development.ts');s=p.read_text()
s=s.replace('yellows=events.filter(event=>event.type==="card"&&event.playerId===player.id).length;return{goals,assists,shots,yellows};','yellows=events.filter(event=>event.type==="card"&&event.playerId===player.id).length,reds=events.filter(event=>event.type==="red_card"&&event.playerId===player.id).length;return{goals,assists,shots,yellows,reds};')
s=s.replace('-counts.yellows*.18;', '-counts.yellows*.18-counts.reds*.85;')
s=s.replace('player.yellowCards=(player.yellowCards??0)+counts.yellows;', 'player.yellowCards=(player.yellowCards??0)+counts.yellows;player.redCards=(player.redCards??0)+counts.reds;')
p.write_text(s)
print('match engine 2.0 and competitions 2.0 written')
