from pathlib import Path


def replace(path, old, new):
    p=Path(path); text=p.read_text()
    if old not in text:
        raise SystemExit(f'pattern not found in {path}: {old[:100]}')
    p.write_text(text.replace(old,new,1))

# season: exact competition reasons + allow removing blocked selected players + correct cup bench limit
p='src/game-engine/season.ts'
replace(p,
'import { createGamePreferences, hydrateGamePreferences, type GamePreferences } from "./game-preferences";',
'import { createGamePreferences, hydrateGamePreferences, type GamePreferences } from "./game-preferences";\nimport { competitionAvailabilityMap } from "./competition-availability";')
old='export function setMatchdayRole(state:SeasonState,playerId:string,role:MatchdayRole):SeasonState{const club=getSelectedClub(state),player=club.players.find(p=>p.id===playerId),cup=getTodayUserCupMatch(state),cupEligible=cup?new Set(eligiblePlayerIds(state.competitionGovernance,cup.tournament.definition.id,club)):undefined;if(!player||player.injuryDays>0||(cupEligible?!cupEligible.has(player.id):player.suspensionMatches>0))return state;const limit=matchdayLimit(state),lineup=(state.lineupIds??[]).filter(id=>id!==playerId),bench=(state.benchIds??[]).filter(id=>id!==playerId);if(role==="starter"&&lineup.length<11)lineup.push(playerId);if(role==="bench"&&bench.length<limit)bench.push(playerId);const league=cloneLeague(state.league),nextClub=league.clubs.find(c=>c.id===state.selectedClubId)!;nextClub.players.forEach(current=>refreshStatus(current,lineup.includes(current.id),bench.includes(current.id)));return{...state,league,lineupIds:lineup,benchIds:bench};}'
new='export function setMatchdayRole(state:SeasonState,playerId:string,role:MatchdayRole):SeasonState{const club=getSelectedClub(state),player=club.players.find(p=>p.id===playerId),cup=getTodayUserCupMatch(state),cupEligible=cup?new Set(eligiblePlayerIds(state.competitionGovernance,cup.tournament.definition.id,club)):undefined;if(!player)return state;const blocked=player.injuryDays>0||(cupEligible?!cupEligible.has(player.id):player.suspensionMatches>0);if(role!=="out"&&blocked)return state;const limit=cup?worldCompetitionRule(cup.tournament.definition.id).benchSize:matchdayLimit(state),lineup=(state.lineupIds??[]).filter(id=>id!==playerId),bench=(state.benchIds??[]).filter(id=>id!==playerId);if(role==="starter"&&lineup.length<11)lineup.push(playerId);if(role==="bench"&&bench.length<limit)bench.push(playerId);const league=cloneLeague(state.league),nextClub=league.clubs.find(c=>c.id===state.selectedClubId)!;nextClub.players.forEach(current=>refreshStatus(current,lineup.includes(current.id),bench.includes(current.id)));return{...state,league,lineupIds:lineup,benchIds:bench};}'
replace(p,old,new)
old='export function worldMatchEligiblePlayerIds(state:SeasonState,matchId:string){const item=worldCompetitionMatchById(state.worldCompetitions,matchId);return item?eligiblePlayerIds(state.competitionGovernance,item.tournament.definition.id,getSelectedClub(state)):getSelectedClub(state).players.map(p=>p.id);}'
new=old+'\nexport function worldMatchEligibilityReasons(state:SeasonState,matchId:string){const item=worldCompetitionMatchById(state.worldCompetitions,matchId);if(!item)return{};const map=competitionAvailabilityMap(state.competitionGovernance,item.tournament.definition.id,getSelectedClub(state));return Object.fromEntries(Object.entries(map).filter(([,value])=>!value.eligible).map(([id,value])=>[id,value.reason??"Indisponível nesta competição"]));}'
replace(p,old,new)

# page: pass eligibility reasons
p='src/app/page.tsx'
replace(p,'worldMatchEligiblePlayerIds, worldMatchGovernanceSummary, worldMatchdayRules','worldMatchEligiblePlayerIds, worldMatchEligibilityReasons, worldMatchGovernanceSummary, worldMatchdayRules')
replace(p,'eligiblePlayerIds={cupContext?worldMatchEligiblePlayerIds(season,cupContext.match.id):undefined} governance=', 'eligiblePlayerIds={cupContext?worldMatchEligiblePlayerIds(season,cupContext.match.id):undefined} availabilityReasons={cupContext?worldMatchEligibilityReasons(season,cupContext.match.id):undefined} governance=')

# tactics setup: exact reasons, valid bench, FM-style presets and advanced custom controls
p='src/app/tactics-setup-view.tsx'
replace(p,'import type { Formation, MatchTactic, Mentality } from "@/game-engine/match";','import type { AttackFocus, BuildUp, DefensiveLine, Formation, Marking, MatchTactic, Mentality, TeamWidth } from "@/game-engine/match";')
replace(p,'import{clampTacticalPoint,tacticalFitMultiplier,tacticalZone,type TacticalPoint}from"@/game-engine/tactical-position";','import{clampTacticalPoint,tacticalFitMultiplier,tacticalZone,type TacticalPoint}from"@/game-engine/tactical-position";\nimport { applyTacticalStyle, TACTICAL_STYLE_PRESETS } from "@/game-engine/tactical-presets";')
replace(p,'benchSize:number;eligiblePlayerIds?:string[];governance?:', 'benchSize:number;eligiblePlayerIds?:string[];availabilityReasons?:Record<string,string>;governance?:')
replace(p,'benchSize,eligiblePlayerIds,governance,workload', 'benchSize,eligiblePlayerIds,availabilityReasons,governance,workload')
old='const eligibleSet=eligiblePlayerIds?new Set(eligiblePlayerIds):undefined,starters=lineupIds.map(id=>club.players.find(p=>p.id===id)).filter((p):p is NonNullable<typeof p>=>Boolean(p)),placements=lineupPlacements(starters,tactic.formation,tactic.positions),available=club.players.filter(p=>p.injuryDays===0&&(eligibleSet?eligibleSet.has(p.id):p.suspensionMatches===0)),requiredBench=Math.max(0,Math.min(benchSize,available.length-11)),selectionReady=lineupIds.length===11&&benchIds.length===requiredBench;'
new='const eligibleSet=eligiblePlayerIds?new Set(eligiblePlayerIds):undefined,starters=lineupIds.map(id=>club.players.find(p=>p.id===id)).filter((p):p is NonNullable<typeof p>=>Boolean(p)),placements=lineupPlacements(starters,tactic.formation,tactic.positions),available=club.players.filter(p=>p.injuryDays===0&&(eligibleSet?eligibleSet.has(p.id):p.suspensionMatches===0)),availableIds=new Set(available.map(p=>p.id)),validLineupIds=lineupIds.filter(id=>availableIds.has(id)),validBenchIds=benchIds.filter(id=>availableIds.has(id)&&!validLineupIds.includes(id)),requiredBench=Math.max(0,Math.min(benchSize,available.length-11)),selectionReady=validLineupIds.length===11&&validBenchIds.length===requiredBench;'
replace(p,old,new)
replace(p,'<small>{lineupIds.length}/11 titulares • {benchIds.length}/{requiredBench} banco</small>','<small>{validLineupIds.length}/11 titulares • {validBenchIds.length}/{requiredBench} banco</small>')
replace(p,'`COMPLETE O BANCO (${benchIds.length}/${requiredBench})`','`COMPLETE O BANCO (${validBenchIds.length}/${requiredBench})`')
old='<div className={styles.panel}><header><SlidersHorizontal/><div><b>PLANO DE JOGO</b><small>A formação cria a base; depois você pode mover cada jogador livremente.</small></div></header><label>FORMAÇÃO BASE</label>'
new='<div className={styles.panel}><header><SlidersHorizontal/><div><b>PLANO DE JOGO</b><small>Escolha uma identidade estilo FM e personalize cada instrução.</small></div></header><label>ESTILO TÁTICO</label><div className={styles.presetActions}>{TACTICAL_STYLE_PRESETS.map(style=><button key={style.id} title={style.description} onClick={()=>onChange(applyTacticalStyle(tactic,style))}><Sparkles size={13}/>{style.name.toUpperCase()}</button>)}</div><label>FORMAÇÃO BASE</label>'
replace(p,old,new)
replace(p,'<Range label="Ritmo" value={tactic.tempo} onChange={tempo=>onChange({...tactic,tempo})}/></div>', '<Range label="Ritmo" value={tactic.tempo} onChange={tempo=>onChange({...tactic,tempo})}/><SelectOption label="FOCO DE ATAQUE" value={tactic.attackFocus??"Equilibrado"} options={["Equilibrado","Pelos lados","Por dentro","Esquerda","Direita"]} onChange={value=>onChange({...tactic,attackFocus:value as AttackFocus})}/><SelectOption label="LINHA DEFENSIVA" value={tactic.defensiveLine??"Média"} options={["Baixa","Média","Alta"]} onChange={value=>onChange({...tactic,defensiveLine:value as DefensiveLine})}/><SelectOption label="AMPLITUDE" value={tactic.width??"Normal"} options={["Estreita","Normal","Ampla"]} onChange={value=>onChange({...tactic,width:value as TeamWidth})}/><SelectOption label="CONSTRUÇÃO" value={tactic.buildUp??"Mista"} options={["Curta","Mista","Direta"]} onChange={value=>onChange({...tactic,buildUp:value as BuildUp})}/><SelectOption label="MARCAÇÃO" value={tactic.marking??"Mista"} options={["Zona","Individual","Mista"]} onChange={value=>onChange({...tactic,marking:value as Marking})}/></div>')
old='const starter=lineupIds.includes(p.id),bench=benchIds.includes(p.id),blocked=p.injuryDays>0||(eligibleSet?!eligibleSet.has(p.id):p.suspensionMatches>0),role=roles[p.id]??naturalRole(p);return <div key={p.id}'
new='const starter=lineupIds.includes(p.id),bench=benchIds.includes(p.id),blocked=p.injuryDays>0||(eligibleSet?!eligibleSet.has(p.id):p.suspensionMatches>0),blockedReason=availabilityReasons?.[p.id]??(p.injuryDays>0?p.status:p.suspensionMatches>0?p.status:"Não inscrito ou suspenso nesta competição"),role=roles[p.id]??naturalRole(p);return <div key={p.id}'
replace(p,old,new)
replace(p,'{blocked?(p.injuryDays>0?p.status:eligibleSet&&!eligibleSet.has(p.id)?"Não elegível nesta competição":p.status):', '{blocked?blockedReason:')
replace(p,'<button disabled={blocked} className={!starter&&!bench?styles.roleActive:""} onClick={()=>onSetRole(p.id,"out")}>F</button>', '<button className={!starter&&!bench?styles.roleActive:""} onClick={()=>onSetRole(p.id,"out")}>F</button>')
replace(p,'<b>BANCO {benchIds.length}/{requiredBench}</b>', '<b>BANCO {validBenchIds.length}/{requiredBench}</b>')
replace(p,'function Range({label,value,onChange}:{label:string;value:number;onChange:(value:number)=>void}){return <label className={styles.range}><span>{label}<b>{value}</b></span><input type="range" min="20" max="90" value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}', 'function Range({label,value,onChange}:{label:string;value:number;onChange:(value:number)=>void}){return <label className={styles.range}><span>{label}<b>{value}</b></span><input type="range" min="20" max="90" value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}\nfunction SelectOption({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(value:string)=>void}){return <label className={styles.range}><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(option=><option key={option}>{option}</option>)}</select></label>}')

# live match: commentary beside score, FM event block, goal flash and staff substitution advice
p='src/app/live-match-view.tsx'
replace(p,'import { useEffect, useMemo, useState } from "react";','import { useEffect, useMemo, useRef, useState } from "react";')
replace(p,'const [finishing,setFinishing]=useState(false);','const [finishing,setFinishing]=useState(false);\n  const [goalFlash,setGoalFlash]=useState(false);\n  const seenGoal=useRef("");')
marker='const momentum=(userSide==="home"?1:-1)*(session.momentumHome??0);'
insert=marker+'\n  const latestEvent=session.events[session.events.length-1];\n  const importantEvents=session.events.filter(event=>["goal","card","red_card","injury"].includes(event.type)).slice(-8).reverse();\n  const latestGoal=[...session.events].reverse().find(event=>event.type==="goal");\n  const goalKey=latestGoal?`${latestGoal.minute}:${latestGoal.team}:${latestGoal.playerId??""}:${session.homeGoals}-${session.awayGoals}`:"";\n  useEffect(()=>{if(!goalKey||goalKey===seenGoal.current)return;seenGoal.current=goalKey;setGoalFlash(true);const timer=window.setTimeout(()=>setGoalFlash(false),2600);return()=>window.clearTimeout(timer)},[goalKey]);'
replace(p,marker,insert)
marker='const substitute=()=>{if(!outId||!inId)return;onChange(makeSubstitution(session,userSide,outId,inId));setOutId("");setInId("")};'
insert=marker+'\n  const cardedIds=new Set(session.events.filter(event=>event.team===userSide&&(event.type==="card"||event.type==="red_card")&&event.playerId).map(event=>event.playerId!));\n  const subCandidates=lineup.map(id=>({id,player:byId.get(id),state:session.playerStates[id],score:(100-(session.playerStates[id]?.condition??100))*1.4+Math.max(0,6.2-(session.playerStates[id]?.rating??6))*18+(cardedIds.has(id)?18:0)})).filter(item=>item.player).sort((a,b)=>b.score-a.score);\n  const suggestedOut=subCandidates[0],suggestedIn=bench.map(id=>byId.get(id)).filter((player):player is NonNullable<typeof player>=>Boolean(player)).sort((a,b)=>b.overall-a.overall)[0];\n  const canSuggestSub=subs.length<session.maxSubstitutions&&session.currentMinute>=50&&suggestedOut&&suggestedIn&&(suggestedOut.score>=16||momentum<-25||gf<ga);\n  const subReason=suggestedOut?(cardedIds.has(suggestedOut.id)?"está pendurado e corre risco":(suggestedOut.state?.condition??100)<68?`caiu para ${Math.round(suggestedOut.state?.condition??100)}% de condição`:(suggestedOut.state?.rating??6)<5.9?`está com nota ${(suggestedOut.state?.rating??6).toFixed(1)}`:gf<ga?"pode dar mais energia enquanto buscamos o resultado":momentum<-25?"pode ajudar a recuperar o controle":"é a troca de maior impacto agora"):"";'
replace(p,marker,insert)
# scoreboard commentary strip after matchStats
old='<div className={liveStyles.matchStats}><span>POSSE <b>{session.possessionHome}%</b>–<b>{100-session.possessionHome}%</b></span><span>CHUTES <b>{session.shotsHome}</b>–<b>{session.shotsAway}</b></span><span>xG <b>{session.xgHome.toFixed(2)}</b>–<b>{session.xgAway.toFixed(2)}</b></span><span>ESCANTEIOS <b>{session.cornersHome??0}</b>–<b>{session.cornersAway??0}</b></span></div>'
new=old+'<div className={`${liveStyles.liveCommentary} ${goalFlash?liveStyles.goalFlash:""}`}><b>{latestEvent?.minute??0}′</b><span>{latestEvent?.type==="goal"?"⚽ ":latestEvent?.type==="card"?"🟨 ":latestEvent?.type==="red_card"?"🟥 ":latestEvent?.type==="injury"?"🩺 ":""}{latestEvent?.text??"Aguardando o início da partida."}{latestEvent?.type==="goal"&&latestEvent.assistPlayerId?<small> Assistência: {byId.get(latestEvent.assistPlayerId)?.name}</small>:null}</span></div><div className={liveStyles.eventBoard}>{importantEvents.map((event,index)=><div key={`${event.minute}-${event.type}-${index}`}><b>{event.minute}′</b><i>{event.type==="goal"?"⚽":event.type==="card"?"🟨":event.type==="red_card"?"🟥":"🩺"}</i><span>{event.playerId?byId.get(event.playerId)?.name:event.text}{event.type==="goal"&&event.assistPlayerId?<small> • assistência {byId.get(event.assistPlayerId)?.name}</small>:null}</span></div>)}</div>'
replace(p,old,new)
# staff suggestion append before closing staff panel
old='{patch&&<button onClick={()=>change(patch)}>APLICAR AJUSTE</button>}</div>}'
new='{patch&&<button onClick={()=>change(patch)}>APLICAR AJUSTE</button>}{canSuggestSub&&<div className={liveStyles.subAdvice}><b>SUGESTÃO DE TROCA</b><span>Sair: {suggestedOut.player?.name} • Entrar: {suggestedIn.name}. {subReason}.</span><button onClick={()=>{setOutId(suggestedOut.id);setInId(suggestedIn.id)}}>PREPARAR TROCA</button></div>}</div>}'
replace(p,old,new)

# live CSS
p='src/app/live-match.module.css'
css=Path(p).read_text()
css+='''\n.liveCommentary{max-width:760px;margin:10px auto 6px;padding:10px 14px;border:1px solid rgba(255,255,255,.12);border-radius:10px;display:grid;grid-template-columns:48px 1fr;gap:10px;align-items:center;background:rgba(5,15,13,.72);transition:.25s ease}.liveCommentary>b{font-size:18px}.liveCommentary span{font-weight:700}.liveCommentary small{display:block;opacity:.75;margin-top:3px}.goalFlash{animation:v90GoalFlash .45s ease-in-out 5;background:rgba(20,120,65,.38);box-shadow:0 0 28px rgba(40,220,120,.35)}@keyframes v90GoalFlash{0%,100%{transform:scale(1)}50%{transform:scale(1.018);filter:brightness(1.45)}}.eventBoard{max-width:760px;margin:0 auto 8px;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px}.eventBoard>div{padding:6px 8px;border-radius:8px;background:rgba(255,255,255,.055);display:grid;grid-template-columns:32px 22px 1fr;gap:4px;font-size:11px;align-items:center}.eventBoard span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.eventBoard small{opacity:.7}.subAdvice{margin-top:12px;padding-top:10px;border-top:1px solid rgba(255,255,255,.12);display:grid;gap:6px}.subAdvice b{font-size:11px;letter-spacing:.08em}.subAdvice span{font-size:12px;line-height:1.4}@media(max-width:720px){.eventBoard{grid-template-columns:repeat(2,minmax(0,1fr))}}\n'''
Path(p).write_text(css)
