from pathlib import Path

# News: guarantee coverage for every active team and competition.
p=Path('src/game-engine/news-engine.ts')
s=p.read_text()
needle=''' return out.sort((a,b)=>b.relevance-a.relevance||b.round-a.round).slice(0,180);\n}\n'''
insert=r''' // Cobertura editorial garantida: todo clube ativo aparece com seu resultado mais recente.
 const existingText=()=>out.map(item=>`${item.title} ${item.summary}`).join("\n");
 for(const club of season.league.clubs){
  const latest=played.filter(f=>f.homeClubId===club.id||f.awayClubId===club.id).sort((a,b)=>b.round-a.round)[0];
  if(!latest||existingText().includes(club.name))continue;
  const home=clubs.get(latest.homeClubId),away=clubs.get(latest.awayClubId);if(!home||!away)continue;
  const result=clubResult(latest,club.id),tone:NewsEngineTone=result==="V"?"positive":result==="D"?"negative":"neutral";
  out.push({id:`club-latest-${competition.id}-${club.id}-${latest.round}`,title:`${club.name}: último compromisso termina ${score(latest)}`,summary:`${home.name} ${score(latest)} ${away.name}. O resultado da rodada ${latest.round} entra no giro completo do ${competition.name}.`,source:"Giro dos Clubes • V90",meta:`${competition.shortName} • ${club.shortName} • R${latest.round}`,round:latest.round,tone,relevance:52,tags:[competition.id,"todos os clubes",club.id]});
 }
 // Todas as ligas paralelas: um registro por time, além de tabela e destaques individuais.
 for(const parallel of Object.values(season.worldLeagues?.leagues??{})){if(!parallel)continue;const pPlayed=parallel.fixtures.filter(f=>f.played&&f.homeGoals!==undefined&&f.awayGoals!==undefined);if(!pPlayed.length)continue;const teams=new Map(parallel.teams.map(t=>[t.id,t])),pLatest=Math.max(...pPlayed.map(f=>f.round)),table=[...parallel.standings].sort((a,b)=>b.points-a.points||(b.goalsFor-b.goalsAgainst)-(a.goalsFor-a.goalsAgainst)||b.goalsFor-a.goalsFor),leader=table[0],leaderTeam=leader?teams.get(leader.clubId):undefined,scorer=[...parallel.players].sort((a,b)=>b.goals-a.goals||b.averageRating-a.averageRating)[0];
  if(leaderTeam)out.push({id:`parallel-table-${parallel.competitionId}-${pLatest}`,title:`${leaderTeam.name} lidera ${parallel.shortName}`,summary:`O ${leaderTeam.name} soma ${leader.points} pontos após a rodada ${pLatest}.${scorer&&scorer.goals>0?` ${scorer.name} é o principal artilheiro acompanhado, com ${scorer.goals} gols.`:""}`,source:"Classificação Mundial • V90",meta:`${parallel.country} • ${parallel.shortName}`,round:pLatest,tone:"neutral",relevance:74,tags:[parallel.competitionId,"classificação","mundo"]});
  for(const team of parallel.teams){const latest=pPlayed.filter(f=>f.homeClubId===team.id||f.awayClubId===team.id).sort((a,b)=>b.round-a.round)[0];if(!latest)continue;const h=teams.get(latest.homeClubId),a=teams.get(latest.awayClubId),homeSide=latest.homeClubId===team.id,gf=homeSide?latest.homeGoals!:latest.awayGoals!,ga=homeSide?latest.awayGoals!:latest.homeGoals!,tone:NewsEngineTone=gf>ga?"positive":gf<ga?"negative":"neutral";out.push({id:`parallel-club-${parallel.competitionId}-${team.id}-${latest.round}`,title:`${team.name}: ${gf>ga?"vitória":gf<ga?"derrota":"empate"} no giro de ${parallel.shortName}`,summary:`${h?.name??"Mandante"} ${score(latest)} ${a?.name??"Visitante"}. O V90 acompanha todos os clubes ativos desta competição.`,source:"Giro Internacional • V90",meta:`${parallel.country} • ${parallel.shortName} • R${latest.round}`,round:latest.round,tone,relevance:50+(latest.round===pLatest?7:0),tags:[parallel.competitionId,"todos os clubes",team.id]});}
 }
 // Copas: publicar cada confronto recente, não apenas um jogo representativo da fase.
 for(const tournament of season.worldCompetitions?.tournaments??[]){const cupPlayed=tournament.matches.filter(m=>m.played&&m.homeGoals!==undefined&&m.awayGoals!==undefined).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,24);for(const m of cupPlayed){out.push({id:`cup-match-full-${tournament.definition.id}-${m.id}`,title:`${tournament.definition.shortName}: ${m.home.name} ${m.homeGoals}–${m.awayGoals} ${m.away.name}`,summary:`Confronto pela ${m.stage} da ${tournament.definition.name}.${m.decidedByPenalties?" A classificação foi decidida nos pênaltis.":""}`,source:"Copas & Continentes • V90",meta:`${tournament.definition.shortName} • ${m.stage} • ${m.date}`,round:m.roundDue,tone:"neutral",relevance:68,tags:[tournament.definition.id,"copa","placar completo"]});}}
 const unique=new Map<string,GeneratedSportsNews>();for(const item of out)if(!unique.has(item.id))unique.set(item.id,item);
 return [...unique.values()].sort((a,b)=>b.relevance-a.relevance||b.round-a.round).slice(0,420);
}
'''
if needle not in s: raise SystemExit('news return needle missing')
p.write_text(s.replace(needle,insert))

# Rewrite 2D as an event-directed animation instead of generic jitter.
Path('src/app/match-2d-pitch.tsx').write_text(r'''"use client";
import{useEffect,useMemo,useState}from"react";
import type{LeagueClub,LeaguePlayer}from"@/game-engine/league";
import type{LiveMatchState,MatchSide}from"@/game-engine/live-match";
import type{MatchEvent}from"@/game-engine/match";
import{layoutLineup}from"@/game-engine/tactics-layout";
import styles from"./match-2d-pitch.module.css";
const clamp=(v:number,min=4,max=96)=>Math.max(min,Math.min(max,v));
const zoneX=(zone?:"left"|"center"|"right")=>zone==="left"?24:zone==="right"?76:50;
function label(type:MatchEvent["type"]){return type==="goal"?"GOL":type==="chance"?"FINALIZAÇÃO":type==="corner"?"ESCANTEIO":type==="free_kick"?"FALTA":type==="penalty"?"PÊNALTI":type==="card"?"CARTÃO":type==="red_card"?"EXPULSÃO":type==="injury"?"ATENDIMENTO":type==="tactical"?"AJUSTE TÁTICO":type==="halftime"?"INTERVALO":type==="fulltime"?"FIM DE JOGO":"JOGO CORRIDO"}
export default function Match2DPitch({session,home,away}:{session:LiveMatchState;home:LeagueClub;away:LeagueClub}){const[frame,setFrame]=useState(0);const event=session.events[session.events.length-1];const eventKey=`${event?.minute}:${event?.type}:${event?.team}:${event?.playerId??""}:${event?.assistPlayerId??""}:${session.homeGoals}-${session.awayGoals}`;useEffect(()=>{setFrame(0);if(session.phase==="pre_match"||session.phase==="fulltime")return;const id=window.setInterval(()=>setFrame(v=>(v+1)%12),110);return()=>window.clearInterval(id)},[eventKey,session.phase]);const byId=useMemo(()=>new Map([...home.players,...away.players].map(p=>[p.id,p])),[home,away]);
 const build=(side:MatchSide,ids:string[],formation:string)=>{const players=ids.map(id=>byId.get(id)).filter((p):p is LeaguePlayer=>Boolean(p)),layout=layoutLineup(players,formation as never),attacking=event?.team===side,stopped=event&&["card","red_card","injury","halftime","fulltime"].includes(event.type);return layout.map(({player,slot})=>{const baseX=side==="home"?slot.x:100-slot.x,baseY=side==="home"?8+slot.y*.78:92-slot.y*.78;let x=baseX,y=baseY;if(!stopped){const direction=side==="home"?1:-1;const teamShift=(attacking?-7:3)*direction;y=clamp(y+teamShift);if(attacking&&event?.zone)x=clamp(x+(zoneX(event.zone)-x)*.18);if(!attacking&&event?.zone)x=clamp(x+(zoneX(event.zone)-x)*.1)}const actor=event?.playerId===player.id,assistant=event?.assistPlayerId===player.id;if(actor||assistant){x=zoneX(event.zone);const goalY=side==="home"?94:6;if(event?.type==="corner"){x=event.zone==="left"?6:event.zone==="right"?94:zoneX(event.zone);y=side==="home"?88:12}else if(["chance","goal","penalty","free_kick"].includes(event?.type??"")){const progress=Math.min(1,frame/7);y=clamp((side==="home"?72:28)+(goalY-(side==="home"?72:28))*progress*.5);if(assistant)y=side==="home"?66:34}else{y=clamp(baseY)}}return{player,x,y,actor,assistant,side};});};
 const hp=build("home",session.homeLineupIds,session.homeTactic.formation),ap=build("away",session.awayLineupIds,session.awayTactic.formation),actor=event?.playerId?byId.get(event.playerId):undefined,assist=event?.assistPlayerId?byId.get(event.assistPlayerId):undefined,attacking=event?.team==="home"||event?.team==="away"?event.team:session.possessionHome>=50?"home":"away",goalY=attacking==="home"?96:4,startY=attacking==="home"?62:38,progress=Math.min(1,frame/8);let ballX=50,ballY=50;if(event?.type==="kickoff"){ballX=50;ballY=50}else if(event?.type==="corner"){ballX=frame<3?(event.zone==="right"?96:4):zoneX(event.zone);ballY=attacking==="home"?(frame<3?94:82):(frame<3?6:18)}else if(["chance","goal","free_kick","penalty"].includes(event?.type??"")){ballX=zoneX(event?.zone);ballY=startY+(goalY-startY)*progress}else if(event&&["card","red_card","injury"].includes(event.type)){const pos=[...hp,...ap].find(v=>v.player.id===event.playerId);ballX=pos?.x??50;ballY=pos?.y??50}else{ballX=zoneX(event?.zone);ballY=attacking==="home"?58:42}
 return <section className={styles.wrap}><header><div><span>MOTOR 2D • EVENTO SINCRONIZADO</span><b>{session.currentMinute}′ • {event?label(event.type):"JOGO CORRIDO"}</b></div><small>{event?.text??"Movimentação baseada na posse e estrutura das equipes."}</small></header><div className={`${styles.pitch} ${event?.type==="goal"?styles.goalScene:""}`}><i className={styles.half}/><i className={styles.circle}/><i className={`${styles.box} ${styles.topBox}`}/><i className={`${styles.box} ${styles.bottomBox}`}/><i className={`${styles.goal} ${styles.topGoal}`}/><i className={`${styles.goal} ${styles.bottomGoal}`}/>{[...hp,...ap].map(v=><div key={v.player.id} className={`${styles.player} ${v.side==="home"?styles.home:styles.away} ${v.actor?styles.onBall:""} ${v.assistant?styles.assistant:""}`} style={{left:`${v.x}%`,top:`${v.y}%`}}><b>{v.player.position}</b><span>{v.player.name.split(" ")[0]}</span></div>)}<div className={styles.ball} style={{left:`${ballX}%`,top:`${ballY}%`}}/>{event?.type==="goal"&&<div className={styles.eventBadge}>⚽ {actor?.name??"GOL"}{assist?` • passe de ${assist.name}`:""}</div>}{event&&["card","red_card","injury"].includes(event.type)&&<div className={styles.eventBadge}>{event.type==="card"?"🟨":event.type==="red_card"?"🟥":"🩺"} {actor?.name??event.text}</div>}</div></section>}
''')
Path('src/app/match-2d-pitch.module.css').write_text(r'''.wrap{display:grid;gap:8px;margin:10px 0 16px}.wrap header{display:flex;justify-content:space-between;gap:12px;align-items:end}.wrap header div{display:grid}.wrap header span{font-size:10px;font-weight:900;letter-spacing:.12em;opacity:.62}.wrap header b{font-size:13px}.wrap header small{font-size:10px;opacity:.72;text-align:right;max-width:58%;line-height:1.35}.pitch{position:relative;aspect-ratio:1.55/1;min-height:330px;border:1px solid rgba(255,255,255,.16);border-radius:16px;overflow:hidden;background:linear-gradient(90deg,rgba(255,255,255,.025) 50%,rgba(0,0,0,.04) 50%),repeating-linear-gradient(0deg,rgba(255,255,255,.025) 0 9%,transparent 9% 18%),#174c32;box-shadow:inset 0 0 0 4px rgba(255,255,255,.035)}.half{position:absolute;left:4%;right:4%;top:50%;border-top:1px solid rgba(255,255,255,.45)}.circle{position:absolute;width:18%;aspect-ratio:1;left:41%;top:50%;transform:translateY(-50%);border:1px solid rgba(255,255,255,.45);border-radius:50%}.box{position:absolute;left:29%;width:42%;height:16%;border:1px solid rgba(255,255,255,.42)}.topBox{top:0;border-top:0}.bottomBox{bottom:0;border-bottom:0}.goal{position:absolute;left:43%;width:14%;height:2.5%;border:1px solid rgba(255,255,255,.6)}.topGoal{top:0}.bottomGoal{bottom:0}.player{position:absolute;transform:translate(-50%,-50%);transition:left .18s ease-out,top .18s ease-out;display:grid;place-items:center;width:26px;height:26px;border-radius:50%;border:2px solid rgba(255,255,255,.9);box-shadow:0 3px 10px rgba(0,0,0,.35);z-index:3}.player b{font-size:7px;line-height:1}.player span{position:absolute;top:27px;white-space:nowrap;font-size:8px;font-weight:800;text-shadow:0 1px 3px #000}.home{background:#19a15f}.away{background:#273149}.onBall{box-shadow:0 0 0 5px rgba(255,214,64,.35),0 3px 10px #000;z-index:5}.assistant{box-shadow:0 0 0 4px rgba(85,200,255,.28),0 3px 10px #000}.ball{position:absolute;width:10px;height:10px;border-radius:50%;background:#fff;border:1px solid #222;transform:translate(-50%,-50%);transition:left .11s linear,top .11s linear;z-index:6;box-shadow:0 0 9px rgba(255,255,255,.85)}.eventBadge{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);z-index:10;background:rgba(4,12,9,.82);border:1px solid rgba(255,255,255,.22);padding:8px 12px;border-radius:10px;font-size:11px;font-weight:900;pointer-events:none}.goalScene{box-shadow:inset 0 0 0 4px rgba(255,214,64,.08),0 0 20px rgba(255,214,64,.08)}@media(max-width:720px){.pitch{min-height:390px;aspect-ratio:.78/1}.wrap header{align-items:start}.wrap header small{max-width:52%}.player span{font-size:7px}.eventBadge{max-width:72%;text-align:center}}
''')

# Regression tests for full news coverage.
Path('src/game-engine/news-full-coverage.test.ts').write_text(r'''import{describe,expect,it}from"vitest";import{createSeason,advanceCalendarDay}from"./season";import{buildNewsEngineV2}from"./news-engine";
describe("news full coverage",()=>{it("covers every active parallel league after games are played",()=>{let s=createSeason("news-all",2026);for(let i=0;i<20;i++)s=advanceCalendarDay(s).state;const news=buildNewsEngineV2(s),ids=new Set(news.flatMap(n=>n.tags));for(const league of Object.values(s.worldLeagues.leagues)){if(!league)continue;if(league.fixtures.some(f=>f.played))expect(ids.has(league.competitionId)).toBe(true)}});it("does not hide clubs from the active league once they have played",()=>{let s=createSeason("news-clubs",2026);for(let i=0;i<20;i++)s=advanceCalendarDay(s).state;const text=buildNewsEngineV2(s).map(n=>`${n.title} ${n.summary}`).join(" ");for(const club of s.league.clubs){if(s.league.fixtures.some(f=>f.played&&(f.homeClubId===club.id||f.awayClubId===club.id)))expect(text.includes(club.name)).toBe(true)}})});
''')
